### ISSUE TITLE
[NBug] Value of '-1' is not valid for 'Value'. 'Value' should be b...

### ISSUE THREAD

**Issue by msallin** [gitextensions/gitextensions#7263] opened 2019-10-08 11:22 UTC
## Error Details
```
System.ArgumentOutOfRangeException: Value of '-1' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value
   at System.Windows.Forms.ProgressBar.set_Value(Int32 value)
   at GitUI.CommandsDialogs.FormCommit.ResetSoftClick(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.FormCommit.ResetSelectedFiles()
   at GitUI.CommandsDialogs.FormCommit.ExecuteCommand(Int32 cmd)
   at ResourceManager.GitExtensionsFormBase.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

## Additional information
It is a empty repo. Then I created some files and staged them. I did some changes to the staged files. Then, I reset the not yet staged files and in a second step, I tried to reset the staged files.

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3460.0
- DPI 96dpi (no scaling)

**Comment by hieuxlu** [comment] 2019-10-15 17:39
@RussKie Can you assign this to me, will investigate in coming days. I think this issue got fixed when we refactor `ResetSoftClick` to use `RunBatchCommand`, but need to debug to confirm.

**Comment by mstv** [comment] 2019-10-16 21:10
`Staged.SelectedItems` is evaluated twice in the function `Unstaged`. Perhaps it has changed due to some async action.
The returned (reference to the) `IEnumerable` should be stored in a function-local variable.

`toolStripProgressBar1.Maximum` is not set by the function `ResetSoftClick`.

**Comment by hieuxlu** [comment] 2019-10-17 09:09
@mstv ATM, I can't reproduce so it's difficult to investigate/guess-fixing. The bug seems obvious, 2 people have filed this same issue, but I just can't reproduce it. Really need a step by step feedback from @msallin

**Comment by gerhardol** [comment] 2019-10-17 10:36
@hieuxlu 
If the cause is clear and there is no reason to make an exception, it can be OK to just avoid the exception. Whatever that improves the user experience.

**Comment by msallin** [comment] 2019-10-18 07:00
Hi guys

I tried to reproduce it but unfortunately was not successful.

```
toolStripProgressBar1.Visible = true;
toolStripProgressBar1.Maximum = Staged.SelectedItems.Count() * 2;
toolStripProgressBar1.Value = 0;
Staged.StoreNextIndexToSelect();

var files = new List<GitItemStatus>();
var allFiles = new List<GitItemStatus>();

var shouldRescanChanges = false;
foreach (var item in Staged.SelectedItems)
{
    toolStripProgressBar1.Value = Math.Min(toolStripProgressBar1.Maximum - 1, toolStripProgressBar1.Value + 1);
    if (!item.IsNew)
    {
        toolStripProgressBar1.Value = Math.Min(toolStripProgressBar1.Maximum - 1, toolStripProgressBar1.Value + 1);
        Module.UnstageFileToRemove(item.Name);
....
}
```
As @mstv mentioned, it seems like the value of Staged.SelectedItems is different on the first enumeration (Count()) and on the second (foreach). As far as I remember I had items selected, which means, that the first iteration does return the wrong "wrong"/not expected result. 

A workaround would be to ensure that toolStripProgressBar1.Maximum = Staged.SelectedItems.Count() * 2; is min 1 but might would be better to do a root cause analysis.

Thanks for your effort!

**Comment by hieuxlu** [comment] 2019-10-18 08:56
I was able to reproduce the bug, here's the step.

1. Open FormCommit in any repository with already staged files
2. Focus on the empty area of the Staged section, but not selecting any staged items
3. Press 'U' to unstaged file -> no files will be unstaged
4. Select any staged files 
5. Press 'R' to reset

Exception will be thrown because at step 3, no file is selected, but below code still executed.
`toolStripProgressBar1.Maximum = Staged.SelectedItems.Count() * 2;`

Will commit fix in following days.

**Comment by RussKie** [comment] 2019-10-19 02:39
Could you please verify we are not susceptible to the same issue in the Unstaged list.

**Comment by hieuxlu** [comment] 2019-10-19 04:18
> Could you please verify we are not susceptible to the same issue in the Unstaged list.

It doesn't. Unstaged uses `GitModule.StageFile` method. This method always check if the list is empty before staging.
The root cause is the method `FormCommit.ResetSelectedFiles`. This method does not initialize progressbar value/max value, not even set the progress bar visible.

**Closed** 2019-10-20 00:03 UTC
Labels: :beetle: type: bug, :construction: status: in progress, status: incorrectly filled template
