### ISSUE TITLE
Bug: File tree is empty

### ISSUE THREAD

**Issue by avosskoetter** [gitextensions/gitextensions#4413] opened 2018-01-31 09:58 UTC
Bug: File tree (Dateibaum) is empty

![filetree](https://user-images.githubusercontent.com/16896106/35616199-d4724618-0674-11e8-9e18-132e058f1c10.png)

Environment:
- GitExtensions version: 2.50.02 (Windows)
- GIT version: Version 2.12.0.1 (Windows)
- OS version: Windows 7 SP1 64 bit

Did this work in previous version of GitExtensions (which)?
- Yes
- Version 2.49

**Comment by RussKie** [comment] 2018-01-31 10:49
Duplicate of #3875

**Closed by RussKie** 2018-01-31 10:49 UTC
