### ISSUE TITLE
[NBug] Unable to parse object ID "a".

### ISSUE THREAD

**Issue by MaksimSimkin** [gitextensions/gitextensions#9511] opened 2021-08-17 07:42 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.FormatException: Unable to parse object ID "a".
   bei GitUIPluginInterfaces.ObjectId.Parse(String s)
   bei GitCommands.GitModule.GetFileBlobHash(String fileName, ObjectId objectId)
   bei GitUI.Editor.FileViewer.ViewGitItemAsync(GitItemStatus file, ObjectId objectId, FileStatusItem item, Action openWithDifftool)
   bei GitUI.Editor.FileViewer.ViewGitItemAsync(FileStatusItem item, Action openWithDifftool)
   bei GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, String defaultText, Action openWithDiffTool)
   bei GitUI.CommandsDialogs.RevisionDiffControl.<ShowSelectedFileDiffAsync>d__41.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei GitUI.CommandsDialogs.RevisionDiffControl.<<DiffFiles_SelectedIndexChanged>b__42_0>d.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Just switched from one repository to another

## Environment
- Git Extensions 3.5.2.12435
- Build 77413699a9c25b160a6a622311529372b5d87f5b
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2021-08-17 11:03
Likely a duplicate of #9195, corrected in master in #9196

**Closed** 2021-08-17 11:03 UTC
Labels: potential-duplicate
