### ISSUE TITLE
[NBug] Value must not be null.

### ISSUE THREAD

**Issue by the-programmer** [gitextensions/gitextensions#11813] opened 2024-07-18 14:25 UTC
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.45.2.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.32
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.Exception: Value must not be null.
   at void Microsoft.Validates.Fail(string message) in C:/projects/gitextensions/GitExtUtils/Validates.cs:line 35
   at async void GitUI.CommandsDialogs.FormCheckoutBranch.Branches_SelectedIndexChanged(object sender, EventArgs e)+(?) => { } in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCheckoutBranch.cs:line 489
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 28
```

Got an error that the remote head didn't exist when cloning. When trying to check-out this happens.

### Steps to reproduce

I don't know the exact steps, this is what i know

The remote is a file-system remote as public repo.
While cloning I got an error about the remote head. 
When I next tried to check-out the remote branch I got this error. 
If you press ignore everything works fine.

**Comment by pmiossec** [comment] 2024-07-18 14:28
Thanks for the report.

Duplicate of #11498
Fixed in #11500

**Closed by pmiossec** 2024-07-18 14:28 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
