### ISSUE TITLE
FormStatus steals focus from other windows

### ISSUE THREAD

**Issue by jakebathman** [gitextensions/gitextensions#3570] opened 2017-03-03 16:47 UTC
--- GitExtensions2.49, Git 2.8.4.windows.1, Microsoft Windows 10 Pro 10.0.14393 (Build 14393)

When taking action on a remote (such as pushing, fetching, etc), the `FormStatus`dialog box steals focus from other windows every time it gets spawned for a new action.

For example, a commit and push from the commit dialog spawns four actions for me:

1. commit
2. fetch
3. push
4. push origin --tags (from a script triggered on AfterPush)

With `Keep dialog open` *not* checked in any `FormStatus` dialogs, this will spawn and close four instances of `FormStatus` sequentially as each command is executed.

If I click `Commit & push` and then go to another window (e.g. Google Chrome), each of the instances of `FormStatus`steal focus back from wherever it was in the operating system.

**Comment by EbenZhang** [comment] 2017-03-05 13:51
Interesting, I find my GE will be send back behind the browser(or whatever window was behind GE) if reset a branch to a commit.

But I would just disable the buggy ConEmu.

![disableconemu](https://cloud.githubusercontent.com/assets/596334/23587753/d78187f6-01ed-11e7-9c1f-37f878d2a4d9.png)

**Comment by jakebathman** [comment] 2017-03-06 20:13
Didn't realize that was for the same window, I'll disable and test a bit.

**Comment by jbialobr** [comment] 2017-05-17 10:51
Could not figure out how to fix this issue. It seems that conemu makes a lot of effort to gain the focus back.

**Comment by StefanoChiodino** [comment] 2018-07-09 16:24
@EbenZhang workaround works for me! Thanks!

**Comment by gerhardol** [comment] 2019-07-22 23:17
Duplicate of #6220

**Closed by gerhardol** 2019-07-22 23:17 UTC
Labels: type: bug
