### ISSUE TITLE
[NBug] An item with the same key has already been added.

### ISSUE THREAD

**Issue by xJom** [gitextensions/gitextensions#6818] opened 2019-06-18 06:07 UTC
## Current behaviour

The app crashes.

## Expected behaviour

The app is not crashing.

## Steps to reproduce

From a repository with a long history, add a graft point without parent, to cut off old history.

E.g A0 => A1 => A2 => ... => A90 => A91 => ... => A601

echo <sha-1 for A91> > .git/info/grafts

Open GitExtensions to view. The app crashes with error below.

## Error Details
```
System.ArgumentException: En post med samma nyckel har redan lagts till.
   vid System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   vid System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   vid GitUI.CommitInfo.CommitInfo.<LoadSortedRefsAsync>g__ToDictionary|55_0(IReadOnlyList`1 list)
   vid GitUI.CommitInfo.CommitInfo.<LoadSortedRefsAsync>d__55.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid GitUI.CommitInfo.CommitInfo.<<RefreshSortedRefs>b__49_0>d.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by xJom** [comment] 2019-06-18 06:15
I do not have any spaces in the end of the branches. I only have two branches, and they do not actually branch. The develop-branch does have a replace/-reference on top of the other branch (withoutAPI). Maybe this might be the issue?

A91 => ... => A400 (withoutAPI) => .. => A601 (develop) 
                 \
                   => A400' replace/<sha for A399>

Just removing the graft point from .git/info/grafts will still give the exception.

**Comment by xJom** [comment] 2019-06-18 07:00
WORKAROUND: Do not echo graftpoint into .git/info/grafts. Do a git replace --grafts instead. This command was not available on my Unix machine (locked down to git 2.9 currently on RHEL), but I moved it to the Windows machine, where git was updated to 2.22.0.

**Comment by gerhardol** [comment] 2019-06-18 10:25
Duplicate of #6616
Please try the latest dev build to make sure the issue is solved - this could be a separate occurrence

**Comment by xJom** [comment] 2019-06-18 10:42
I tried 3.2.0.6118 but the app still crashes:

## Error Details
```
System.ArgumentException: En post med samma nyckel har redan lagts till.
   vid System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   vid System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   vid GitUI.CommitInfo.CommitInfo.GetSortedRefs()
   vid GitUI.CommitInfo.CommitInfo.<LoadSortedRefsAsync>d__55.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid GitUI.CommitInfo.CommitInfo.<<RefreshSortedRefs>b__48_0>d.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```


## Environment
- Git Extensions 3.2.0.6118
- Build 6767731f758d2b45bbdd8125fada5b564d5f46d2 (Dirty)
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2019-06-18 13:01
Would you be able to run the following command and either post `refs.txt` here or send to my email? I would like to add a test case to our test suite.
```
$ git for-each-ref --sort=-committerdate --sort=-taggerdate --format="%(refname)" refs/ > refs.txt
```

**Comment by RussKie** [comment] 2019-06-18 13:02
Are you in a position to debug it?

**Comment by xJom** [comment] 2019-06-18 13:15
refs/replace/585dfd0ae42e4ad707bca6cd46de4abd07c0f33e
refs/heads/withoutApi
refs/heads/develop

That is the answer to the git-command above. I will try to start a debug session.

**Comment by xJom** [comment] 2019-06-18 13:44
Sorry. I could not debug since NuGet is blocket at our site. :(

**Comment by RussKie** [comment] 2019-06-18 13:48
Could out please redirect the output into a file and post the actual file here. I'd like to know if there are any special/invisible chars

**Comment by xJom** [comment] 2019-06-18 13:50
[refs.txt](https://github.com/gitextensions/gitextensions/files/3301778/refs.txt)

**Comment by RussKie** [comment] 2019-06-18 13:55
![image](https://user-images.githubusercontent.com/4403806/59689997-fdbc5680-9223-11e9-98a1-0dedfcba8acc.png)


![image](https://user-images.githubusercontent.com/4403806/59690278-81764300-9224-11e9-9464-0e5578de0e0c.png)


There must be something else at play...
🤔

**Comment by xJom** [comment] 2019-06-18 14:07
Yes, I think that somewhere, something gets confused about the grafts and replace/-grafts, since the Unix machine has Git 2.9 (which do not have replace/-grafts) and the Windows machine has 2.22 (which do have replace/-grafts). But I am not entirely sure about where those "somewhere" and "something" are. I tried to start a debugging session on the pre-compiled "portable" with the "pdbs" added, but it only complained about not finding mscorlib... So it would not point anywhere closer to the problem, even if I could actually see the exception in Visual Studio.

**Comment by xJom** [comment] 2019-06-18 14:08
And there is a workaround: Avoiding grafting on the Unix-machine helps in my case, at least.

**Comment by RussKie** [comment] 2019-06-19 01:51
Are you able to create a test repo that exhibits the same behavior?

**Closed** 2019-10-04 04:51 UTC
Labels: :eyeglasses: status: needs review, :mailbox_with_no_mail: needs: author feedback, :zzz: status: no recent activity, status: workaround available
