### ISSUE TITLE
JoinPendingOperationsAsync hangs in ConfigureJoinableTaskFactoryAttribute.AfterTest

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7742] opened 2020-02-08 12:46 UTC
## Current behaviour

Occasionally, some tests hang in the `JoinPendingOperationsAsync`  in `ConfigureJoinableTaskFactoryAttribute.AfterTest` after the actual test has passed.
The `CancellationTokenSource(UnexpectedTimeout)` has no effect.
NUnit cancels the wait by a `ThreadAbortException`.
This seems to happen more often with the Release variant than with Debug.

Affected test cases (perhaps more):
- `GitUITests.CommitInfo.CommitInfoTests.GetSortedTags_should_remove_duplicate_refs`
- `GitUITests.CommitInfo.CommitInfoTests.GetSortedTags_should_load_ref_with_extra_spaces`
- `GitUITests.CommitInfo.CommitInfoTests.GetSortedTags_should_split_output_if_no_warning` 
- `UITests.CommandsDialogs.FormBrowseLeftPanelReorderNodesTest.RepoObjectTree_moving_node_legally_moves_it`
- `UITests.CommandsDialogs.FormBrowseLeftPanelReorderNodesTest.RepoObjectTree_moving_node_across_hidden_trees_skips_them`

example: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/30627268

## Expected behaviour

no timeout at all, especially no hang in `JoinPendingOperationsAsync`

## Steps to reproduce

run the test on AppVeyor several times

## Environment

- GE d5a44082
- AppVeyor
- Windows 10

**Comment by mstv** [comment] 2020-02-08 12:46
@sharwell, could you have a look at this, please?

**Comment by sharwell** [comment] 2020-02-09 07:00
https://github.com/gitextensions/gitextensions/pull/7747 may improve this

**Comment by sharwell** [comment] 2020-02-09 22:11
The hang may be caused by the thread exception UI getting shown. This UI needs to be disabled during tests, and instead log an exception that gets thrown during the next `AfterTest` execution.

**Comment by sharwell** [comment] 2020-02-09 23:29
The main issue here is background operations do not prevent the owning dialog from closing. As a broader work item, we need to modify each form to join its own background operations before closing, so we know after it is closed there is no other work left to join.

**Comment by sharwell** [comment] 2020-02-09 23:31
Note that in both #7750 and #7753, the cause of the _hang_ is the incorrect behavior of assertion UI during testing (https://github.com/gitextensions/gitextensions/issues/7742#issuecomment-583899915). The fixes I submitted prevent exceptions from being thrown on these paths, but do not prevent similar exceptions from causing hangs in other cases.

**Closed** 2020-03-21 20:00 UTC
Labels: area: tests
