### ISSUE TITLE
[NBug] Der Objektverweis wurde nicht auf eine Objektinstanz festge...

### ISSUE THREAD

**Issue by mariolorenz** [gitextensions/gitextensions#9068] opened 2021-04-14 06:56 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Steps to reproduce

Switch from one Repo to another

## Error Details
```
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei GitUI.BranchTreePanel.RepoObjectsTree.BaseBranchNode.ApplyStyle()
   bei GitUI.BranchTreePanel.RepoObjectsTree.BaseBranchLeafNode.ApplyStyle()
   bei GitUI.BranchTreePanel.RepoObjectsTree.LocalBranchNode.ApplyStyle()
   bei GitUI.BranchTreePanel.RepoObjectsTree.BaseBranchLeafNode.set_IsMerged(Boolean value)
   bei GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass45_1.<SelectionChanged>b__3(BaseBranchLeafNode node)
   bei System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   bei GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass45_0.<<SelectionChanged>b__0>d.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.5.0.11509
- Build 009d10c765a90aa00e043e40d5117256b793bc8c (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment] 2021-04-14 21:19
A possible regression in 3.5

**Comment by mstv** [comment] 2021-04-14 21:47
Closing as duplicate of #9065.

**Closed by mstv** 2021-04-14 21:47 UTC
Labels: :beetle: type: bug, :grey_exclamation: priority: high, type: regression
