### ISSUE TITLE
Can't authorize GitHub plugin (under Windows - old IE version)

### ISSUE THREAD

**Issue by ghost** [gitextensions/gitextensions#3712] opened 2017-05-19 17:34 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I can't authorize the GitHub plugin under Windows

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Plugin->GitHub
2. Enter credentials
3. I receive a warning that I'm using an unsupported version of IE. It doesn't seem to use the IE 11 version on my Windows 7 computer (which is supported and working on GitHub).
4. I can't click the button Authorize

**What is the expected behavior?**
I should be able to click the Authorize button

**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
GitExtensions 2.49.03 on Windows 7

**Comment by esayli** [comment] 2017-07-05 18:10
I have the same issue, is there a solution for this ?

**Comment by esayli** [comment] 2017-07-05 18:22
Ok , I found a solution for this.

On the page , right click, and click "properties"

Then you see the URL address . Copy that and open that on chrome. 

You will be able to authorize that way.

**Comment by gabrielcossette-ca** [comment] 2017-07-19 15:25
Good workaround @esayli, thanks!

**Comment by esayli** [comment] 2017-07-19 16:35
you're welcome :) I am glad it solved your issue too.

**Comment by stavBodik** [comment] 2019-02-18 07:10
@ghost HaHa Amazing thanks !

**Comment by gerhardol** [comment] 2019-03-02 23:09
Duplicate of #4800 
Setting this as a duplicate even if it was first and describes a workaround, as #4800 has discussions on how to proceed

**Closed by gerhardol** 2019-03-02 23:09 UTC
Labels: area: plugins, type: bug

**Comment by nblumoe** [comment] 2019-03-15 08:08
I couldn't get the URL via right click as described by @esayli on MacOS.

However, opening the dev tools (CMD+ALT+i) and then `location.href` from the console provided me a URL I could use to authenticate in my normal web browser.
