### ISSUE TITLE
Add Edit functionality in Advanced menu

### ISSUE THREAD

**Issue by lowdev** [gitextensions/gitextensions#3166] opened 2016-04-10 10:49 UTC
Add Edit functionality in Advanced menu.
By clicking it, it will :
- launch a git rebase interactive on one of the commit parent.
- replace automatically the first "pick" by "e".

![gitextension_editmenu](https://cloud.githubusercontent.com/assets/3659358/14409654/cd21d96e-ff19-11e5-8914-fe5e9d0a48a3.png)

Btw, If it's ok with you i will do the same for the functionality "rename" a commit.

**Comment by Radrik5** [comment] 2016-04-10 11:19
Possible duplicate of #2794.

**Comment by lowdev** [comment] 2016-04-10 13:03
In some cases we cannot edit a commit with fixup...
For example, you have 3 commits : A, B, C.
You want fix the commit A with some change in the commit B, you need to use
edit functionality.

It's just a case there is some other when editing is useful.

About renaming a commit with git extension : 
-> Click right on the commit
-> Click on "rebase on current branch...."
-> Click on "show options"
-> Check "Interactive rebase"
-> Click on rebase
-> edit the rebase interactive file : change pick by r
-> Save the file
-> close it
-> Here we go we can rename...

With Rename functionality in Advanced menu:
-> Click right on the commit
-> click on "edit commit"
-> Here we go we can rename

There is simply too much click to rename a commit...

In my company we care about commit message like a lot
and with gerrit review, we have a lot of renaming to do.
I converted a lot of people to git extension but they start complaining about that.
Moreover there is a plugin in eclipse which does this functionality...

**Comment by vbjay** [comment] 2016-04-10 17:00
That explanation makes it a little bit better.  The only critique I would
have is that a rename has a different SHA-1.  You could depending on the
state of remote branches end up with merge conflicts.

**Comment by lowdev** [comment] 2016-04-10 18:08
Thanks you for the response.

About the comment on "rename functionality", i'm note sure to understand correctly.
Let's take this case : 
We have three commits on your local branch: 
C (SHA-1: 3333)
B (SHA-1: 2222)
A (SHA-1: 1111)
if i rename the commit A, i will have a new SHA-1: 4444. The remote branches doesn't have my
local changes so no merge conflict issue here when i will push my 3 commits.

A second case:
If i tried to rename just a commit on the remote branch called "branch A".
My local branch will have this commit with a new commit message.
Now if i rebase my local branch on "branch A" => My commit with a new commit message will disappear because there is no change. Nothing new to applied on "branch A".

I don't think there is a case where, just by changing the commit message, will end up with merge conflicts.
If you see an user case, please advice me. I will test it.

All is about having a good local branch before pushing.
With gerrit review, we have to take care about our local branch. (fixup is used but also edit and rename in some case it's easier to use this git feature)

**Comment by Radrik5** [comment] 2016-04-10 18:45
I would call it "reword" to be consistent with git interactive rebase.

**Comment by lowdev** [comment] 2016-04-10 19:02
+1 for "reword".
Btw i have already did a change request to add "edit" functionality
https://github.com/gitextensions/gitextensions/pull/3167#discussion_r59133329

Once it's merged i will do the "reword" functionality.

**Comment by vbjay** [comment] 2016-04-10 21:05
If you rename a commit that has already been pushed you will get a merge
conflict if someone else pushed other changes.

**Comment by lowdev** [comment] 2016-04-11 10:35
Thank you for your use case I will test it.

However about your comment
https://github.com/gitextensions/gitextensions/issues/3166#issuecomment-208015583,
we can already do a rebase interactive and reword a commit of a remote branch.

Your critic is not about my commit but about git. Isn't it ?

**Comment by vbjay** [comment] 2016-04-11 12:27
Yes.  You never check out remote branches and commit on them.  You check
out the local branch and merge or rebase the remote into local, and then do
your work and push to the remote.

http://www.gitguys.com/topics/tracking-branches-and-remote-tracking-branches/

**Comment by lowdev** [comment] 2016-04-11 18:51
ok I guess we agree.

**Comment by lowdev** [comment] 2016-04-14 16:35
Do you want me to prevent the fixup (and squash) when the commit is already on the remote branch ?

**Comment by Radrik5** [comment] 2016-04-14 18:26
I don't think so. The user should be able to modify any history and do a force push if it's necessary.

**Comment by lowdev** [comment] 2016-04-14 18:42
Yeah i think so too...
About "reword" functionality. Do you want me to push it in the same feature branch (/feature/edit_advanced_menu) or should i create another branch ?

**Comment by Radrik5** [comment] 2016-04-16 14:12
I think it's better to use the same pull request. Don't expect your pull request to be reviewed and merged quickly. This is not very active project. My pull requests are usually merged within 1 - 6 months. But there is one opened on 18 Sep 2015 and still not reviewed.

**Comment by lowdev** [comment] 2016-04-18 08:53
Thanks for your responses Radrik5 !
I will take your advice and be patient ^^.

**Closed** 2017-04-22 05:37 UTC
