### ISSUE TITLE
No selection indicators in any file list boxes

### ISSUE THREAD

**Issue by BlackStarX42** [gitextensions/gitextensions#6289] opened 2019-02-21 13:56 UTC
## Current behaviour
I cannot see which file I selected in any list box displaying files.
## Expected behaviour
There should be some selection in these boxes indicating which file(s) I have selected.
## Screenshots
![gitex2](https://user-images.githubusercontent.com/41993823/53173771-a0ebbf00-35e8-11e9-86ea-3e39b0cc48d1.png)
![gitex2b](https://user-images.githubusercontent.com/41993823/53173772-a0ebbf00-35e8-11e9-951b-116b954bcea5.png)
## Did this work in previous version of GitExtensions
Yes.
## Environment
- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment] 2019-02-21 14:00
That's because you are using Windows classic appearance.

Really wish people would search issues first.

**Comment by BlackStarX42** [comment] 2019-02-21 14:04
I searched for "file list box selection" and did not find an appropriate topic. Also, I care less about the reason but more about a solution, because I do have selection bars in list boxes in other .Net applications :-)

**Comment by vbjay** [comment] 2019-02-21 14:10
https://github.com/gitextensions/gitextensions/search?q=selection+file&type=Issues

**Comment by BlackStarX42** [comment] 2019-02-21 14:23
Thank you.

Btw, I hope trying to explain other people how using a bug reporting site works by properly using the search function and which are the right keywords they should have used to actually find the appropriate, already reported issue, and thus implying how incapable they are, is not the common way to welcome new people :-)

**Comment by vbjay** [comment] 2019-02-21 15:13
It was more a point in one of the many issues that would hopefully get
people to see that is a known issue and stop creating multiple issues.

**Comment by RussKie** [comment] 2019-02-21 20:51
Duplicate of #5499

**Closed by RussKie** 2019-02-21 20:51 UTC
