### ISSUE TITLE
it is black???

### ISSUE THREAD

**Issue by shiningrise** [gitextensions/gitextensions#3391] opened 2016-10-28 00:26 UTC
--- GitExtensions2.49RC2, Git 2.10.1.windows.1, Microsoft Windows NT 6.1.7601 Service Pack 1
![Uploading image.png…]()

**Comment by RussKie** [comment] 2016-10-28 11:16
Image didn't upload... you may want to upload it again

**Comment by KindDragon** [comment] 2016-10-28 12:15
I think it's duplicate of #3382

**Closed by KindDragon** 2016-10-28 12:15 UTC
