### ISSUE TITLE
Graph column sometimes not painting last row

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5168] opened 2018-07-16 08:07 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug, following #5087.

**What is the current behavior?**

When the revision grid/graph first appears, the partially visible row at the end of the UI is not rendered. 

![image](https://user-images.githubusercontent.com/350947/42738540-3e428f1e-887d-11e8-8cba-685f3e4f059a.png)

Scrolling fixes the problem.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Resize the grid so there is a partial row.
1. Refresh the revisions.

**What is the expected behavior?**

Graph is always fully rendered.

**Environment you encounter the issue:**

- GitExtensions version: master

**Comment by drewnoakes** [comment] 2018-07-25 19:22
For this to occur the left tree must be hidden.

**Comment by wplpgr** [comment] 2018-07-26 14:17
@drewnoakes Do you mean the left "Branches" tree? Because if you do, I see this problem with the Branches panel enabled. I have also seen multiple lines of the graph missing after a refresh (such that it happens consistently on each refresh), but haven't managed to work out how to reproduce it yet.

**Comment by drewnoakes** [comment] 2018-07-26 14:44
Yes that's what I meant. Thanks for the detail.

I haven't seen multiple lines blank before, only the last partial line. Is it just the graph column that's blank, or are the text columns to the right also blank?

**Comment by wplpgr** [comment] 2018-07-26 14:49
Just the graph column.

**Comment by wplpgr** [comment] 2018-08-02 09:30
A bit more information, that may (or may not) be the same problem.
1. load a repository (latest commit at the top of the view)
1. scroll the view a few lines
1. select a commit at the bottom of the view
1. hit the refresh button

And then you get something that looks like:
![ge-missing-graph](https://user-images.githubusercontent.com/13469396/43575139-f66cdd38-963d-11e8-80ed-75c0463a6660.png)

Basically, the number of blank lines corresponds to the number of lines scrolled off the top. Furthermore, as far as I can work it out (by testing), the width of the graph is calculated based on the bits that are _actually_ being displayed.

So... I think that this is actually the cause of the problem in Issue #5167: if you select a commit which is further down than the number of lines in the view, all the graph segments are blank, and the graph column is sized accordingly: 1 wide.

I couldn't decide whether to log it against this one, or that one.
(Tested against fe59613e642a67636f325174ab214a723a82223e)

**Comment by NikolayXHD** [comment] 2018-09-01 23:37
the scenario from the [comment](https://github.com/gitextensions/gitextensions/issues/5168#issuecomment-409865924) above was fixed by PR #5356

Tested with the builds before and after the PR
`View` -> `Order revisions by date` option from graph context is enabled

Before

![image](https://user-images.githubusercontent.com/12046452/44950747-bca3b300-ae58-11e8-9e1b-173c272cee5f.png)

After

![image](https://user-images.githubusercontent.com/12046452/44950745-aeee2d80-ae58-11e8-9a4f-8b7d84df8ff4.png)

**Comment by RussKie** [comment] 2018-09-02 05:42
Yes, I haven't observed the issue since #5356
I'm going to close this; if the problem resurfaces again, we'll re-open the issue.

**Closed by RussKie** 2018-09-02 05:42 UTC
Labels: high priority, type: bug, type: regression
