### ISSUE TITLE
After Git Extension 4.0 upgrade,  with multiple GIT extension windows (one for each reposiotry), none/only one  is getting selected on mouse click

### ISSUE THREAD

**Issue by matt5Github** [gitextensions/gitextensions#10582] opened 2022-12-26 07:13 UTC
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Open multiple GIT extension windows with different repository. And use mouse to select any one of the repository, it won't select a GIT extension window. This worked correctly with previous version.

### Steps to reproduce

1) Upgrade GIT extension to 4.0 or later.
2) Open multiple GIT Extension windows for each repository. I have three GT extension windows open  one for UI, one for API, one for Legacy.
3) Use mouse to select any one of the repository window,  only one(always gets selected)/none is getting selected on mouse click.
4)  Use ALT+TAB key to select correct GitExtension repository.

### Did this work in previous version of GitExtensions?

yes, it selected correct GIT repository window on mouse click.

**Comment by pmiossec** [comment] 2022-12-26 08:04
I don't really understand what you mean by 'select'. Is it a duplicate of #10398 or #9752 ? 
If yes, you can try a workaround explained in #10119 (see there the setting to set)

**Comment by vbjay** [comment] 2022-12-26 11:32
Record an animation using screen2gif.

**Comment by matt5Github** [comment] 2022-12-27 04:31
Below workaround kind of fixes the issue -  GE(Git Extension) window gets selected on mouse click but doesn't open in Maximize mode. 

Let's say I do Ctrl-M to minimize all windows and then try to select a GE window on taskbar, it opens in normal size  mode, not in maximized window mode. I have to click on maximize icon on the window in order to maximize each opened GE window.

Its kind of annoying to always do Maximize each GE window after using Ctrl-M (minimize all). By using below fix, at least it is able to open GE window. I wish I would not have upgraded GE to version 4.0.
-----------------------------------------
Re-posting the workaround here since it requires a bit of digging to find the solution:

%APPDATA%\GitExtensions\GitExtensions\GitExtensions.settings
(e.g. C:\Users\user\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings

  <item>
    <key>
      <string>WorkaroundRestoreFromMinimize</string>
    </key>
    <value>
      <string>true</string>
    </value>
  </item>

**Comment by gerhardol** [comment] 2023-01-06 14:24
Duplicate of #10398
See https://github.com/gitextensions/gitextensions/issues/10398#issuecomment-1313378235 for a workaround

**Closed by gerhardol** 2023-01-06 14:24 UTC
Labels: :eyeglasses: status: needs review

**Comment by matt5Github** [comment] 2023-01-12 15:10
- Reverted to [version 4.0,](https://github.com/gitextensions/gitextensions/releases/tag/v4), this issue and file history shows as expected.
