### ISSUE TITLE
[NBug] Value cannot be null. (Parameter 'targetName')

### ISSUE THREAD

**Issue by Esurnir** [gitextensions/gitextensions#11907] opened 2024-09-11 08:39 UTC
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.44.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.8
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.ArgumentNullException: Value cannot be null. (Parameter 'targetName')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at GitExtensions.Extensibility.Settings.CredentialsManager.SetCredentials(SettingLevel settingLevel, String name, NetworkCredential value) in C:\projects\gitextensions\src\app\GitExtensions.Extensibility\Settings\CredentialsManager.cs:line 69
   at GitExtensions.Extensibility.Settings.CredentialsSetting.SaveValue(SettingsSource settings, String userName, String password) in C:\projects\gitextensions\src\app\GitExtensions.Extensibility\Settings\CredentialsSetting.cs:line 42
   at GitExtensions.Extensibility.Settings.CredentialsSetting.CredentialsControlBinding.SaveSetting(SettingsSource settings, CredentialsControl control) in C:\projects\gitextensions\src\app\GitExtensions.Extensibility\Settings\CredentialsSetting.cs:line 86
   at GitExtensions.Extensibility.Settings.SettingControlBinding`2.SaveSetting(SettingsSource settings) in C:\projects\gitextensions\src\app\GitExtensions.Extensibility\Settings\SettingControlBinding.cs:line 42
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.PageToSettings() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\SettingsPageBase.cs:line 123
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.SaveSettings() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\SettingsPageBase.cs:line 110
   at GitUI.CommandsDialogs.FormSettings.Save() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 233
   at GitUI.CommandsDialogs.FormSettings.buttonApply_Click(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 324
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

Tentative de set de jira commit hint

### Steps to reproduce

Post update, I tried to use the jira plugin for the fist time and set some setting, to see it crash.

**Comment by Esurnir** [comment] 2024-09-11 09:42
I think this is due to the update process and if I uninstall then reinstall removing all settings folder everything is fine and dandy.

**Comment by gerhardol** [comment] 2024-09-11 09:53
(Seems) duplicate of https://github.com/gitextensions/gitextensions/issues/11892. Fixed by https://github.com/gitextensions/gitextensions/pull/11893

You could test the portable version to confirm if issue is fixed: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/50564009/artifacts

Ask for reopen if it's not the case.(Seems) duplicate of https://github.com/gitextensions/gitextensions/issues/11892. Fixed by https://github.com/gitextensions/gitextensions/pull/11893

You could test the portable version to confirm if issue is fixed: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/50564009/artifacts

Ask for reopen if it's not the case.

**Comment by RussKie** [comment] 2024-09-11 10:17
Looking at the stack trace it doesn't look like a duplicate. This one is
about the JIRA plugin, the others are about the scripts handling.

**Comment by mstv** [comment] 2024-09-11 21:27
Which settings source have you chosen?

![image](https://github.com/user-attachments/assets/cb4f36e0-f7ee-43d0-9528-009250eca68a)

**Comment by Esurnir** [comment] 2024-09-14 01:11
> Which settings source have you chosen?
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/cb4f36e0-f7ee-43d0-9528-009250eca68a)

As dumb as it sound, at the time I had left it as the default option.

**Comment by mstv** [comment] 2024-09-14 12:01
I could not reproduce the issue.

Does it work if you explicitly choose the memory location?

**Comment by Esurnir** [comment] 2024-09-14 13:16
> I could not reproduce the issue.
> 
> 
> 
> Does it work if you explicitly choose the memory location?

I couldn't reproduce it with a fresh install, it was on an install after an upgrade from the previous v4 (I think the latest v4  but I'm not 100% certain) to v5. After I imported the settings from the v4 that I had this issue.

I apologize if I don't have an easy to reproduce test case.

**Comment by pmiossec** [comment] 2024-09-24 15:04
I don't know if that's the way it has been encountered but we can reproduce it by trying to set the Jira credentials while keeping settings "Effective" but **when settings are opened from the dashboard** (i.e. no repositories are loaded).

I think that the solution is to set "Global for all repositories" by default when settings are opened from dashboard and settings source should be disabled.

**Closed** 2024-10-19 22:17 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
