### ISSUE TITLE
Help > Report an issue Uses the wrong GitHub URL now.

### ISSUE THREAD

**Issue by chris-findlay** [gitextensions/gitextensions#6103] opened 2019-01-14 22:32 UTC
## Current behaviour
It goes to `https://github.com/gitextensions/gitextensions/issues/new`

Which means I get a blank issue, not a template or a template-choice.

## Expected behaviour
It should go to `https://github.com/gitextensions/gitextensions/issues/new/choose`

## Steps to reproduce
`Help` > `Report an issue`

## Did this work in previous version of GitExtensions

N/A

## Environment

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment] 2019-01-14 22:35
Please search issues first.

**Comment by vbjay** [comment] 2019-01-14 22:37
https://github.com/gitextensions/gitextensions/pull/6087/commits/700ff3f90e80adaad0c54073da51b9b00a9be8e2

**Comment by gerhardol** [comment] 2019-01-14 22:42
Duplicate of #6075

**Closed by gerhardol** 2019-01-14 22:42 UTC
