### ISSUE TITLE
[NBug] Change not parsed correctly: Binary files a/ja.png and /dev...

### ISSUE THREAD

**Issue by shirayuki** [gitextensions/gitextensions#11657] opened 2024-03-25 11:42 UTC
### Environment

- Git Extensions 33.33.33
- Build 
- Git 2.44.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 8.0.3
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.FormatException: Change not parsed correctly: Binary files a/ja.png and /dev/null differ
   at Patch GitCommands.Patches.PatchProcessor.CreatePatchFromString(string[] lines, Lazy<Encoding> filesContentEncoding, ref int lineIndex) in C:/git/gitextensions/GitCommands/Patches/PatchProcessor.cs:line 183
   at IEnumerable<Patch> GitCommands.Patches.PatchProcessor.CreatePatchesFromString(string patchText, Lazy<Encoding> filesContentEncoding)+MoveNext() in C:/git/gitextensions/GitCommands/Patches/PatchProcessor.cs:line 59
   at new System.Collections.Generic.List<T>(IEnumerable<T> collection)
   at List<TSource> System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
   at async Task<(Patch patch, string errorMessage)> GitCommands.GitModule.GetSingleDiffAsync(ObjectId firstId, ObjectId secondId, string fileName, string oldFileName, string extraDiffArguments, Encoding encoding, bool cacheResult, bool isTracked, bool useGitColoring, GitCommandConfiguration commandConfiguration, CancellationToken cancellationToken) in C:/git/gitextensions/GitCommands/Git/GitModule.cs:line 2227
   at async Task GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, CancellationToken cancellationToken, int? line, string defaultText, Action openWithDiffTool, string additionalCommandInfo)+GetItemPatchAsync(?) in C:/git/gitextensions/GitUI/GitUIExtensions.cs:line 200
   at async Task GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, CancellationToken cancellationToken, int? line, string defaultText, Action openWithDiffTool, string additionalCommandInfo)+GetSelectedPatchAsync(?) in C:/git/gitextensions/GitUI/GitUIExtensions.cs:line 180
   at async Task GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, CancellationToken cancellationToken, int? line, string defaultText, Action openWithDiffTool, string additionalCommandInfo) in C:/git/gitextensions/GitUI/GitUIExtensions.cs:line 134
   at async Task GitUI.CommandsDialogs.RevisionDiffControl.ShowSelectedFileDiffAsync(bool ensureNoSwitchToFilter, int? line) in C:/git/gitextensions/GitUI/CommandsDialogs/RevisionDiffControl.cs:line 595
   at async void GitUI.TaskManager.InvokeAndForget(Control control, Func<Task> asyncAction, CancellationToken cancellationToken)+(?) => { } [1] in C:/git/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 119
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/git/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 32
```

### Steps to reproduce

1. Select a commit that includes the deletion of a binary file or an image file.
2. Open the Diff pane.
3. Select the binary file or image file in question, which will trigger an exception.

### Did this work in previous version of GitExtensions?

Git Extensions 4.2.1.17611

**Comment by shirayuki** [comment] 2024-03-25 12:25
Based on my investigation, it appears that commit f201220e is the cause of this bug.

**Comment by gerhardol** [comment] 2024-03-25 13:03
Duplicate of #11630
Pr to be merged soon

**Closed** 2024-03-25 13:03 UTC
Labels: :eyeglasses: status: needs review
