### ISSUE TITLE
Application hangs when going to the settings without a reository open

### ISSUE THREAD

**Issue by Krimsar** [gitextensions/gitextensions#10472] opened 2022-11-29 17:01 UTC
### Environment

- GitExtensions version: 4.0.0.15569
- GIT version: 2.38.1.windows.1
- OS version: NT 10.0.19045.0
- .NET version: 6.0.11

### Issue description

If you go to Tools -> Settings without a repository opened, the application hangs with high CPU usage. I can select stuff inside the dialogue, but nothing changes and I also cannot exit the dialogue itself. At this point I can only forcefully close the application.

### Steps to reproduce

1) Open Git Extensions 
2) Go to Tools -> Settings
3) App hangs

**Comment by mstv** [comment] 2022-11-29 17:21
Duplicate of #10215.
Fixed by #10455.

**Closed** 2022-11-29 21:05 UTC
