### ISSUE TITLE
Context menu handlers not showing

### ISSUE THREAD

**Issue by youssefsharief** [gitextensions/gitextensions#6425] opened 2019-03-30 09:05 UTC
## Current behaviour

"GitExt Browse" context menu handler is not there. I have uninstalled fully through CCleaner and installed "Git Extensions" again but it is still not there. I tried with both version 2.5 and version 3. I tried with both the 65MB msi and the 15MB msi. 

The screenshot below shows that the context menu handlers are missing in two scenarios. First, when I right-click in the directory and second, when I right-click a file.

![Capture](https://user-images.githubusercontent.com/21158003/55273917-7f15e400-52da-11e9-853c-d7f6366846da.PNG)

![Capture](https://user-images.githubusercontent.com/21158003/55273982-68bc5800-52db-11e9-8a65-7bcb2e74973d.PNG)

**I also opened "regedit" and verified that the keys are there as shown from the 3 screenshots below.**

![Capture](https://user-images.githubusercontent.com/21158003/55273934-d1570500-52da-11e9-81a6-894643e85f79.PNG)

![Capture](https://user-images.githubusercontent.com/21158003/55273944-e92e8900-52da-11e9-8402-0fcafbc80f2d.PNG)

![Capture](https://user-images.githubusercontent.com/21158003/55273949-f8153b80-52da-11e9-98f5-cc089832d11e.PNG)

## Environment

- GitExtensions version: 2.50.02
- GIT version: 2.15.1.windows.2
- OS version: Windows 10

**Comment by illfated** [comment] 2019-03-30 11:21
Cannot reproduce, but then again, I always select "Entire feature will be installed on local hard drive" during install.
- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)

I have also tested going back to 2.51.05, the only related difference is that the 3.0x versions use "GitExt Open repository" instead of "GitExt Browse".

As far as I can remember, I have always had the option "GitExt Browse" on my installed 2.x versions.
(Maybe it is a result from always selecting to install everything during the installation.)

**Comment by youssefsharief** [comment] 2019-03-30 11:51
@illfated Thank you. I also selected to install features during installation. It was working for me but when I changed something in regedit from about 2 days ago, it stopped working, but I could not know exactly what I did :(

**Comment by illfated** [comment] 2019-03-30 12:27
Oh, right. That is one of the reasons it is useful to have a registry backup before making manual changes in the registry.
You could of course try using System Restore to see if you have got a restore point from before, 
but that method will remove other changes you may not want to have removed.

Anyway, this seems to be a user setup / OS configuration issue and not a gitextensions issue.
Would you like to close this ticket?

**Comment by youssefsharief** [comment] 2019-03-30 12:33
@illfated  Yes, you are right. I should have backed up my registry. The thing is I uninstalled GitExtensions fully and reinstalled it. Also, there other context menu handlers that appear like VS code's one. I am not sure if the issue is related to GitExtensions or if it is related to OS configuration. I prefer to let the ticket open.   Thank you

**Comment by illfated** [comment] 2019-03-30 12:37
Very well, fair enough. Thanks for mentioning VS Code. I noticed it in your screenshots, but I don't know how much or how little it could interfere with GE's windows explorer context menus.

**Comment by youssefsharief** [comment] 2019-03-30 13:11
@illfated I mentioned VS code to prove that there other context menu handlers that exists on my PC. Thank you

**Comment by RussKie** [comment] 2019-03-31 12:04
* How does your config look like for _Git Extensions > Shell extensions_ menu?
* Do you have `GitExtensionsShellEx32.dll` and `GitExtensionsShellEx64.dll` in `C:\Program Files (x86)\GitExtensions`?

**Comment by youssefsharief** [comment] 2019-03-31 17:50
@RussKie 
Thank you for trying to help me. 

- I did not understand the first question

- Yes, I have those files

**Comment by mstv** [comment] 2019-03-31 20:10
I guess he asked for the GE's shell extensions settings:
![shell extensions](https://user-images.githubusercontent.com/36601201/55294350-54727b00-5401-11e9-86cc-80087d668f30.png)

which results in the following context menu (for me):
![context menu](https://user-images.githubusercontent.com/36601201/55294359-7f5ccf00-5401-11e9-9457-81aa0f3afc78.png)

**Comment by RussKie** [comment] 2019-03-31 21:29
Here's the script that registers the shell extensions: https://github.com/gitextensions/gitextensions/blob/dd029a54c2d4d555bc0881a19df360b45c7fee89/Setup/RegisterShellExtension.wxi

You may want to check the corresponding keys.

**Comment by youssefsharief** [comment] 2019-04-01 05:09
@RussKie 
Yes, I think I have the correct key which is "3C16B20A-BA16-4156-916F-0A375ECFFE24". It is the same one mentioned in the link below. 
https://github.com/gitextensions/gitextensions/blob/c7209c422d3a819e11d4dd0d3555d18efdfc0687/GitExtensionsShellEx/ShellEx.cpp

**Comment by youssefsharief** [comment] 2019-04-01 05:11
@mstv  Sadly, this does not work for me.

**Comment by youssefsharief** [comment] 2019-04-03 08:57
Thank you all guys.   It turned out the problem is not related to GitExtensions at all. This answer helped me resolve the issue. https://superuser.com/a/773206.  The context menu works for right-clicking a directory but not for right-clicking for a single file. Anyway, thank you all for the help

**Comment by RussKie** [comment] 2019-04-03 10:04
Thank you for the follow up.

It should work in both cases:
![image](https://user-images.githubusercontent.com/4403806/55470780-05705400-5654-11e9-8350-87c410e3c62b.png)
(left - folder, right - file)

**Closed by RussKie** 2019-04-03 10:04 UTC
Labels: area: shell extension, status: more info requested
