### ISSUE TITLE
Version 3.5.1 is not found when checking for updates from version 3.4.3

### ISSUE THREAD

**Issue by adamralph** [gitextensions/gitextensions#9333] opened 2021-07-04 13:52 UTC
## Current behaviour

I'm using version 3.4.3.9999. When I click Help -> Check for updates, no updates are found.

## Expected behaviour

Version 3.5.1 should be found — https://github.com/gitextensions/gitextensions/releases/tag/v3.5.1

## Steps to reproduce

- Open version 3.4.3.9999
- Help -> Check for updates

## Screenshots

![image](https://user-images.githubusercontent.com/677704/124387484-2f0b0080-dcdf-11eb-9490-342782ea4d9f.png)

![image](https://user-images.githubusercontent.com/677704/124387504-40eca380-dcdf-11eb-8466-fecb739bcc4b.png)

## Did this work in previous version of GitExtensions

Not sure.

## Environment

- GitExtensions version:
- GIT version: `git version 2.32.0.windows.1`
- OS version: `10.0.19042 Build 19042`
- .NET version: 4.8.4360.0

**Comment by pmiossec** [comment] 2021-07-04 14:07
That's not a bug but a team choice to decide when the next update is proposed to the update check.

v3.5 has still not been proposed because we had concerning crash reports. They should have been fixed with v3.5.1 so if returns are good maybe sometime it will be proposed.

Closing because working as desired.

**Closed** 2021-07-04 14:07 UTC

**Comment by adamralph** [comment] 2021-07-04 14:11
OK, but can you see why I was led to raise this as a bug? If the UI told me what you just told me, then I wouldn't have raised it.

**Comment by RussKie** [comment] 2021-07-05 10:15
The UI told you that- no update available. Once the team is satisfied with
the quality, the auto update will be available.

**Comment by vbjay** [comment] 2021-07-05 12:09
https://github.com/gitextensions/gitextensions/tree/configdata.

**Comment by adamralph** [comment] 2021-07-05 12:14
- The UI tells me there is no update available past 3.4.3.
- GitHub tells me that 3.5.1 is available.

Can you see why this looks like a bug to a user?

**Comment by vbjay** [comment] 2021-07-05 21:12
No. A lot of places do a release that lets you test and when the bugs are
delt with they let the auto update functionality kick in. That is how it is
done here. You can try the latest release by manually downloading.

**Comment by pmiossec** [comment] 2021-07-05 21:26
@adamralph i understand that it could be strange from an outside point of view but what you are asking, to better handle this case by more information or something else, requires a lot of effort for very few added value...
