### ISSUE TITLE
[NBug] Illegales Zeichen im Pfad.

### ISSUE THREAD

**Issue by AndiLeni** [gitextensions/gitextensions#8095] opened 2020-05-12 10:14 UTC
## Steps to reproduce
I opened Git extensions and clicked on the "clone repo" button, and this caused this crash.

## Error Details
```
System.ArgumentException: Illegales Zeichen im Pfad.
   bei System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   bei System.IO.Path.Combine(String path1, String path2)
   bei GitUI.CommandsDialogs.FormClone.ToTextUpdate(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   bei System.Windows.Forms.Control.set_Text(String value)
   bei System.Windows.Forms.TextBoxBase.set_Text(String value)
   bei System.Windows.Forms.TextBox.set_Text(String value)
   bei GitUI.CommandsDialogs.FormClone.FromTextUpdate(Object sender, EventArgs e)
   bei GitUI.CommandsDialogs.FormClone.OnRuntimeLoad(EventArgs e)
   bei GitUI.GitExtensionsForm.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.17.1.windows.2 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2020-05-12 11:37
Duplicate of #7528
You entered characters in the path that are illegal
So the workaround is to just dont do that

A check added in master #7633 (so popup instead)
Please try 3.4 RC

**Closed by gerhardol** 2020-05-12 11:37 UTC
Labels: potential-duplicate
