### ISSUE TITLE
3.5.0: Colours for local vs remote branches reversed

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#9113] opened 2021-04-25 15:29 UTC
## Current behaviour

Local branches are shown in green, remote branches in red.

## Expected behaviour

Local branches are shown in red, remote branches in green - as it was in 3.4.3.

## Steps to reproduce

Upgrade from 3.4.3 to 3.5.0.

## Did this work in previous version of GitExtensions

Yes.

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 144dpi (150% scaling)

**Comment by ivangrek** [comment] 2021-04-25 16:20
Like in git. According to logo green is new red is old.

![image](https://user-images.githubusercontent.com/3169265/116001006-21f4d580-a5fb-11eb-98b5-a7401f7cdd3a.png)

**Comment by jrfnl** [comment] 2021-04-25 16:50
What is being done elsewhere is not directly relevant. It's a change which I couldn't find an explicit mention of in the changelog and which has already had me delete remote branches, when I intended to delete local branches.
On the command-line that wouldn't have happened and the colours don't have that effect. In a GUI, colours take on meaning and **WILL** impact peoples workflow.

**Comment by ivangrek** [comment] 2021-04-25 18:21
>What is being done elsewhere is not directly relevant. It's a change which I couldn't find an explicit mention of in the changelog and which has already had me delete remote branches, when I intended to delete local branches.
On the command-line that wouldn't have happened and the colours don't have that effect. In a GUI, colours take on meaning and WILL impact peoples workflow.

I agree, colors matter. The local branch is green and safe to remove, the remote branch is not safe and is red in color.

**Comment by gerhardol** [comment] 2021-04-25 19:06
This is #8900 (added to the 3.5 milestone but not seen now? @RussKie any explanation?).

There was some discussions about this (also in other issues) to follow what Git does (in this case the command line).

You can use a custom theme to revert.

**Comment by jrfnl** [comment] 2021-04-25 19:49
> You can use a custom theme to revert.

@gerhardol Thanks, and yes, I've already set this up now, but kind of had other plans for today.... Also, a custom theme still doesn't allow me to make all the necessary changes, so things like #9111 still can't be fixed via a custom theme.


More than anything my point is that this is a change which can be made in a major with an appropriate warning, but should never have been allowed to go into a minor and definitely shouldn't have been released without a big bold warning about this in the changelog.

Might be a point of feedback anyway: the GH issue references and technical descriptions in the changelog are all nice and good and have their place, but a human readable changelog written for end-users would be a lot more useful.

**Comment by jrfnl** [comment] 2021-04-25 19:52
> I agree, colors matter. The local branch is green and safe to remove, the remote branch is not safe and is red in color.

That's a matter of interpretation. For me it is: red is local, so be very careful when removing it, however when _accompanied by_ green, it is "safe" as that means there is also a server copy.

**Comment by vbjay** [comment] 2021-04-25 19:54
Changelog is a md file. Could make that part bold to make it stand out.

**Comment by gerhardol** [comment] 2021-04-25 19:56
> More than anything my point is that this is a change which can be made in a major with an appropriate warning, but should never have been allowed to go into a minor and definitely shouldn't have been released without a big bold warning about this in the changelog.

You do not have to convince me here - I was voted down.

> Might be a point of feedback anyway: the GH issue references and technical descriptions in the changelog are all nice and good and have their place, but a human readable changelog written for end-users would be a lot more useful.

It is very timeconsuming to make a release anyway and the contents of  a manual presentation is very subjective in GE that is a collection of many utilities on top of Git.

**Comment by jrfnl** [comment] 2021-04-25 20:05
> Changelog is a md file. Could make that part bold to make it stand out.

> It is very timeconsuming to make a release anyway and the contents of a manual presentation is very subjective in GE that is a collection of many utilities on top of Git.

I hear you and I do feel your pain in that sense as I'm often enough the one making changelogs myself.

Just leaving this here as possible suggestions for the changelog without needing too much manual labor:
* What about collecting the changes which could directly impact end-users and their workflow at the top of the list ? So, basically split the list in two: "User facing changes" and "Other changes".
* Or what about having a short summary with the highlights (= most important changes for end-users to be aware of) of the release in human readable language at the top of the changelog for a release ?

**Comment by RussKie** [comment] 2021-04-26 03:00
> This is #8900 (added to the 3.5 milestone but not seen now? @RussKie Igor Velikorossov FTE any explanation?).

The PR was merged in the master, hence 3.6. Later it was cherry-picked into 3.5 https://github.com/gitextensions/gitextensions/commit/55721154e004edb04713ecce7e926bb6b02b6c0b

**Comment by RussKie** [comment] 2021-04-26 03:03
> This is #8900 (added to the 3.5 milestone but not seen now? @RussKie Igor Velikorossov FTE any explanation?).

The PR was merged in the master, hence 3.6. Later it was cherry-picked into 3.5 https://github.com/gitextensions/gitextensions/commit/55721154e004edb04713ecce7e926bb6b02b6c0b
The changelog is generated against issues and PRs belonging to a specific milestone, so the cherrypicked commits are obviously ignored.

**Comment by RussKie** [comment] 2021-04-26 03:11
> Just leaving this here as possible suggestions for the changelog without needing too much manual labor:
> 
> * What about collecting the changes which could directly impact end-users and their workflow at the top of the list ? So, basically split the list in two: "User facing changes" and "Other changes".
> * Or what about having a short summary with the highlights (= most important changes for end-users to be aware of) of the release in human readable language at the top of the changelog for a release ?

Thank you for the suggestions. I totally agree with you, but as @gerhardol said this is very time-consuming. The current release is already several months behind the expected release date, and if I were to go through hundreds of issues we've dealt with in the release - we won't release at all...
If you have spare time, feel free to draft a better changelog, and we'll publish it.

**Comment by RussKie** [comment] 2021-04-26 03:12
Closing as by design.

**Closed by RussKie** 2021-04-26 03:12 UTC

**Comment by jrfnl** [comment] 2021-04-26 03:24
> If you have spare time, feel free to draft a better changelog, and we'll publish it.

I don't, but more so, I'm not a Windows dev, so would often not be able to gauge the impact of changes for end-users correctly, so I wouldn't be the right person anyway.

Believe me when I say I understand the pressure to release, I have several (10+) projects currently ongoing with delayed releases due to external changes (new PHP release breaking way too much) and high pressure to release.

> if I were to go through hundreds of issues we've dealt with in the release - we won't release at all...

One last suggestion which may help in that regard: what about keeping an "Unreleased" section at the top of the changelog where any notable changes will be listed straight away after the PR has been merged ? At that time it is still fresh in people's minds and clear what the impact will be and whether it needs mentioning for end-user impact.

The generated list can then be added below that at the time of the release.

Example of a project which does this: https://github.com/squizlabs/php_codesniffer/
