### ISSUE TITLE
NullReferenceException when accessing the branch filter

### ISSUE THREAD

**Issue by jeffqc** [gitextensions/gitextensions#2610] opened 2015-01-13 20:42 UTC
I have a repository that constantly crashes when I try to access the branch filter. I get the following error:

System.NullReferenceException
Object reference not set to an instance of an object.
Boolean <UpdateBranchFilterItems>b__16(System.String) @ GitUI.FilterBranchHelper+<>c__DisplayClass17
GitExtensions.exe [2.48.03]

I can't reproduce with another repo. I already have a fix for it and will create a pull request shortly.

**Comment by mouseas** [comment] 2015-01-22 17:06
I have been experiencing this bug as well. For me, it occurs when I try to enter multiple branches into the filter and any of the branch names I've entered doesn't exist.

Since GitExt tries to auto-load, it can crash when I'm in the middle of typing branch names, especially if I pause too long while typing.

**Comment by jeffqc** [comment] 2015-01-22 18:56
The bug you are describing sounds more like the issue #2544 (https://github.com/gitextensions/gitextensions/issues/2544). They are relatively similar.

**Comment by KindDragon** [comment] 2015-01-22 22:31
Duplicate of #2597

**Closed by KindDragon** 2015-01-22 22:31 UTC
