### ISSUE TITLE
There is no focus on the "checkout" button in the "checkout branch" window

### ISSUE THREAD

**Issue by andrey-helldar** [gitextensions/gitextensions#9271] opened 2021-06-07 18:15 UTC
## Current behaviour

When the "checkout branch" window is opened, the focus is on the "select branch" field.

## Expected behaviour

When you open the "checkout branch" window, focus the selection on the "checkout" button.

## Steps to reproduce

1. In the commit tree, I press the right mouse button;
2. I select the "checkout branch" menu item;
3. In the menu sub-item, I select the desired branch.

## Screenshots

![image](https://user-images.githubusercontent.com/10347617/121068142-91520d80-c7d4-11eb-989e-ab37434efa23.png)

![image](https://user-images.githubusercontent.com/10347617/121068423-ef7ef080-c7d4-11eb-8b25-695e875a9f99.png)

## Did this work in previous version of GitExtensions

The focus on the button was lost after updating to version 3.5.0.11713 from version 3.4.3.9999.

## Environment

- Git Extensions 3.5.0.11713
- Build `0a5ef9ca6ce87754a510aa02c7a96d8b915714ac` (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment] 2021-06-07 18:58
Duplicate of #9251, fixed by #9265 for dev branch and by #9272 for release

**Comment by lhiginbotham** [comment] 2021-10-07 01:30
@mstv so should this be closed out?

**Comment by RussKie** [comment] 2021-10-07 04:42
Yes, thank you

**Closed** 2021-10-07 04:42 UTC
