### ISSUE TITLE
Commit window file list scrolls to top and selects wrong file

### ISSUE THREAD

**Issue by duncanawoods** [gitextensions/gitextensions#4787] opened 2018-04-05 15:16 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The wrong file is selected in the commit window when clicked because the list auto-scrolls to the top and then a file at the correct screen location but now different scroll position is selected.

https://i.imgur.com/eff22vA.mp4

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. 50 locally modified files 
2. Open the commit window
3. Stage a file and write a commit message
4. Have the file list scrolled down and select a file
5. Click commit-push
6. Select a visible file
7. The file list scrolls up to the top and selects a file different to the one that was clicked

**What is the expected behavior?**

On clicking, the scroll position should not be changed and the correct file should be selected

**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 2.51
- OS version: Windows 10 Home

**Did this work in previous version of GitExtensions (which)?**

Don't know

**Comment by emilsteen** [comment] 2019-10-12 16:59
This happens every time the list has lost it's focus and the list is scrollable (has more files that fits in the list).
It happens in both "Working directory changes" and in "Staged files".

**Reproduce:**
1. Select the other list so the scrollable list looses focus.
2. Scroll down the scrollable list.
3. Select a file.
4. Wrong file is selected.

**Comment by mstv** [comment] 2019-10-12 21:34
@emilsteen, this issue might have been fixed by the PR #7247.
Could you try [the current development build (portable version)](https://ci.appveyor.com/api/buildjobs/4wfnkmkpqigmspy3/artifacts/Setup%2FGitExtensions-Portable-3.3.0.6869.zip), please?

**Comment by emilsteen** [comment] 2019-10-14 12:40
Unfortunately, it is not solved in version 3.3.0.6869.

**Comment by emilsteen** [comment] 2019-10-14 13:01
But I can't reproduce it when I clone the repository and run it from Visual Studio.
Both Debug and Release configuration works. 

Is there something with that zip-file I tried?

**Comment by emilsteen** [comment] 2019-10-14 14:28
After lots of testing it looks like this was resolved in commit acf2fe01 in branch #7267.

**Comment by mstv** [comment] 2019-10-14 20:14
Thank you for testing again! Sorry for the confusion I caused by pointing to the wrong fix.

**Comment by emilsteen** [comment] 2019-10-18 11:11
> 
> Has this been fixed?

It works on my machine.
=D

**Closed** 2019-10-18 11:59 UTC
Labels: :beetle: type: bug, :mailbox_with_no_mail: needs: author feedback, area: user experience
