### ISSUE TITLE
Cant run gitextension3.0 in ubuntu mono 

### ISSUE THREAD

**Issue by johnd3v** [gitextensions/gitextensions#5940] opened 2018-12-18 02:33 UTC
mono GitExtensions.exe and this results to 
Gtk-Message: 10:29:00.908: Failed to load module "canberra-gtk-module"

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'GitUI.FontUtil' threw an exception. ---> System.DllNotFoundException: uxtheme.dll
  at (wrapper managed-to-native) GitUI.NativeMethods.OpenThemeData(intptr,string)
  at GitUI.FontUtil..cctor () [0x00000] in <36ab48be24cf4e0b8ce0f075bf6dcb29>:0 
   --- End of inner exception stack trace ---
  at GitUI.CommandsDialogs.SettingsDialog.Pages.FormChooseTranslation..ctor () [0x0000c] in <36ab48be24cf4e0b8ce0f075bf6dcb29>:0 
  at (wrapper remoting-invoke-with-check) GitUI.CommandsDialogs.SettingsDialog.Pages.FormChooseTranslation..ctor()
  at GitExtensions.Program.RunApplication () [0x00044] in <abf89b0081db49299416365187e739cc>:0 
  at GitExtensions.Program.Main () [0x000a7] in <abf89b0081db49299416365187e739cc>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'GitUI.FontUtil' threw an exception. ---> System.DllNotFoundException: uxtheme.dll
  at (wrapper managed-to-native) GitUI.NativeMethods.OpenThemeData(intptr,string)
  at GitUI.FontUtil..cctor () [0x00000] in <36ab48be24cf4e0b8ce0f075bf6dcb29>:0 
   --- End of inner exception stack trace ---
  at GitUI.CommandsDialogs.SettingsDialog.Pages.FormChooseTranslation..ctor () [0x0000c] in <36ab48be24cf4e0b8ce0f075bf6dcb29>:0 
  at (wrapper remoting-invoke-with-check) GitUI.CommandsDialogs.SettingsDialog.Pages.FormChooseTranslation..ctor()
  at GitExtensions.Program.RunApplication () [0x00044] in <abf89b0081db49299416365187e739cc>:0 
  at GitExtensions.Program.Main () [0x000a7] in <abf89b0081db49299416365187e739cc>:0 

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**

**Comment by RussKie** [comment] 2018-12-18 02:39
v2.5x is x-plat, and v3 only works on Windows, please refer to the [readme](https://github.com/gitextensions/gitextensions/blob/master/README.md) and the [changelog](https://github.com/gitextensions/gitextensions/releases/tag/v3.00.00)

**Comment by RussKie** [comment] 2018-12-18 02:39
Duplicate of #5914

**Closed by RussKie** 2018-12-18 02:39 UTC
