### ISSUE TITLE
Broken hotkey Ctrl-. for checkout branch

### ISSUE THREAD

**Issue by kbilsted** [gitextensions/gitextensions#10503] opened 2022-12-07 11:28 UTC
### Environment

- GitExtensions version:
 GitExtensions-Portable-4.0.0-cba315df5
- GIT version: 
 x
- OS version: 
windows 10

- .NET version: 
6

### Issue description

Ctrl-. used to work for checking out a branch. it does not any more

### Steps to reproduce

Press Ctrl-.  and you will not get a prompt as in earlier versions. The menu works, and right-clicking in the tree and selecting checkout branch works too

### Did this work in previous version of GitExtensions?

yes

**Comment by pmiossec** [comment] 2022-12-07 11:44
Duplicate of  #10465 and of  #10495 where there is a beginning of discussion even if the issue is closed. Please contribute there if you have some other information...

**Closed by pmiossec** 2022-12-07 11:44 UTC
Labels: :eyeglasses: status: needs review
