### ISSUE TITLE
[NBug] 

### ISSUE THREAD

**Issue by matusqo** [gitextensions/gitextensions#11261] opened 2023-10-11 15:48 UTC
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.3
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.20
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: remote
Working directory: C:\Users\mkopac\source\repos\DataHub Services\Product\

```
GitExtUtils.ExternalOperationException
 ---> System.Exception
   --- End of inner exception stack trace ---
   at async Task<ExecutionResult> GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action<StreamWriter> writeInput, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes, bool throwOnErrorExit, CancellationToken cancellationToken) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 323
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTask<T>.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<T>(Func<Task<T>> asyncMethod, JoinableTaskCreationOptions creationOptions) x 2
   at ExecutionResult GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action<StreamWriter> writeInput, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes, bool throwOnErrorExit, CancellationToken cancellationToken) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 259
   at IReadOnlyList<string> GitCommands.GitModule.GetRemoteNames() in C:/projects/gitextensions/GitCommands/Git/GitModule.cs:line 2220
   at IReadOnlyList<IHostedRemote> GitExtensions.Plugins.GitHub3.GitHub3Plugin.GetHostedRemotesForModule()+Remotes() in C:/projects/gitextensions/Plugins/GitHub3/GitHub3Plugin.cs:line 235
   at new System.Collections.Generic.List<T>(IEnumerable<T> collection)
   at List<TSource> System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
   at IReadOnlyList<IHostedRemote> GitExtensions.Plugins.GitHub3.GitHub3Plugin.GetHostedRemotesForModule() in C:/projects/gitextensions/Plugins/GitHub3/GitHub3Plugin.cs:line 229
   at bool GitExtensions.Plugins.GitHub3.GitHub3Plugin.GitModuleIsRelevantToMe() in C:/projects/gitextensions/Plugins/GitHub3/GitHub3Plugin.cs:line 215
   at IRepositoryHostPlugin GitUI.PluginRegistry.TryGetGitHosterForModule(GitModule module)+(IRepositoryHostPlugin gitHoster) => { } in C:/projects/gitextensions/GitUI/Plugin/PluginRegistry.cs:line 59
   at TSource System.Linq.Enumerable.TryGetFirst<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate, out bool found)
   at TSource System.Linq.Enumerable.FirstOrDefault<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate)
   at IRepositoryHostPlugin GitUI.PluginRegistry.TryGetGitHosterForModule(GitModule module) in C:/projects/gitextensions/GitUI/Plugin/PluginRegistry.cs:line 59
   at void GitUI.CommandsDialogs.RevisionDiffControl.RegisterGitHostingPluginInBlameControl() in C:/projects/gitextensions/GitUI/CommandsDialogs/RevisionDiffControl.cs:line 1466
   at async GitUI.CommandsDialogs.FormBrowse(GitUICommands commands, BrowseArguments args)+(?) => { } in C:/projects/gitextensions/GitUI/CommandsDialogs/FormBrowse.cs:line 280
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { } in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 29
```

Just opened GitExtensions

### Steps to reproduce

I have just opened GitExtensions from context menu from repository folder after few weeks not using GitExtensions and got this message all of a sudden.
![image](https://github.com/gitextensions/gitextensions/assets/50449453/cac56d20-9060-4d72-9478-9c04ac865680)

### Did this work in previous version of GitExtensions?

Yes

**Comment by pmiossec** [comment] 2023-10-11 15:56
>after few weeks not using GitExtensions and got this message all of a sudden.

And an update of git?

I think it is a duplicate of #11039 fixed by next release. Maybe it's a good idea to test the RC1:

https://github.com/gitextensions/gitextensions/releases/tag/v4.2-rc1

**Comment by pmiossec** [comment] 2023-10-11 15:57
And indeed, report if you still have a problem with the RC1...

**Closed** 2023-10-12 06:39 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate

**Comment by matusqo** [comment] 2023-10-16 17:03
Git update didn't help on first attempt but the problem disappeared later

**Comment by pmiossec** [comment] 2023-10-16 17:23
My remark was more: did you do a git update? Because that's a specific
version of Git that introduces a new security check that breaker
GitExtensions...

But anyway, if it works now....
