### ISSUE TITLE
False? positive antivirus thread from GitExtSshAskPass.exe

### ISSUE THREAD

**Issue by jakubsuchybio** [gitextensions/gitextensions#8127] opened 2020-05-20 12:04 UTC
## Current behaviour
BitDefender antivirus identifies
```
C:\Program Files (x86)\GitExtensions\GitExtSshAskPass.exe
```
as virus:
```
Gen:Variant.Fugrafa.35927
```
and deletes it

## Expected behaviour
Having BitDefender not deleting anything

## Steps to reproduce
1. Having GitExtensions installed
2. Having BitDefender installed
3. Full scan
4. False positive

## Screenshots
![image](https://user-images.githubusercontent.com/6567287/82443785-5df5f100-9aa2-11ea-9976-b54236912969.png)

## Did this work in previous version of GitExtensions
I have GitExtensions for like 6 months and BitDefender too, so I guess either bitdefender update broke it or GitExtensions update broke it.

## Environment

- GitExtensions version: 3.4.0.9381
- GIT version: 2.26.2.windows.1
- OS version: Windows 10 Pro 1909 18363.836
- .NET version: .NET Framework 4.8.4180.0

**Comment by gerhardol** [comment] 2020-05-20 14:19
Duplicate of #8109 

The source code has not been changed since 2013, unknown what triggers this in BitDefender

**Closed by gerhardol** 2020-05-20 14:19 UTC

**Comment by RussKie** [comment] 2020-05-21 09:35
Speculations that something has changed in C++ libraries....
Outside of our control.
