### ISSUE TITLE
ConEmu window exiting

### ISSUE THREAD

**Issue by gszo123** [gitextensions/gitextensions#3360] opened 2016-10-16 10:13 UTC
GitExtensions 2.49RC1

After commiting, there is a message "Press Enter or Esc to close console..." displayed in ConEmu window:

![commit](https://cloud.githubusercontent.com/assets/14149738/19416767/5a46ceee-9399-11e6-99a8-bace5da29476.png)

If you then press Enter or Esc, console exits leaving empty window:

![commit_empty](https://cloud.githubusercontent.com/assets/14149738/19416774/89eeec58-9399-11e6-977e-bb28ab9a6b4a.png)

I think it would be better to either: 
- prevent ConEmu console from closing or 
- close the whole window since it does not contain any useful information.

**Comment by KindDragon** [comment] 2016-10-16 12:18
@hypersw @Maximus5 It possible to disable closing console by keys?

**Comment by Maximus5** [comment] 2016-10-16 13:32
Possible. In future ConEmu release

**Comment by Maximus5** [comment] 2016-10-16 13:34
Do you want ConEmu to print something instead of "Press Esc to close"? Otherwise users may think process is active yet.

**Comment by KindDragon** [comment] 2016-10-16 19:31
Thank you. We find out that incorrect behaviour was caused by my changes, so first I'll try to fix by myself

**Closed** 2016-10-17 09:28 UTC
Labels: bug
