### ISSUE TITLE
Visual Studio 2013 does not open after upgrade to 2.48.03

### ISSUE THREAD

**Issue by szyb** [gitextensions/gitextensions#2587] opened 2014-12-29 09:12 UTC
I've just installed Git extensions 2.48.03 with VS plugin integration. After installation I tried to open VS 2013 and just after that, VS has stopped to respond. I had to change installation and remove VS plugin integration to make it work again. What could be the problem?
EDIT: I changed installation again and installed only plugin integration. VS works as expected now. There was something wrong on first update.

**Comment by shinywong** [comment] 2015-01-02 05:19
I have the same problem. I may have found the cause of the problem. That is if you disable GitExtensions toolbar, VS 2013 will crash at next startup.

Steps to fix this:
1. Uninstall GitExtensions.
2. Open Visual Studio 2013, then close it.
3. Install GitExtensions.
4. Of course, do not disable GitExtensions afterwards.

I don't know whether your causes are same as mine, but you guys can give it a try.

**Closed** 2015-01-22 21:24 UTC

**Comment by allsorts46** [comment] 2015-04-22 17:43
This was closed as fixed in January, but I can't see any update newer than 2.48.03... is there a release with the fix? Thanks

**Comment by asgerhallas** [comment] 2015-04-27 08:38
@shinywong great find. At least I now know what hit me :)

**Comment by thehexgod** [comment] 2015-04-28 21:12
As another fix for this, if you don't want to uninstall git extensions: is to delete all git plugin files from the Visual Studio 2013/Addins Folder.

**Comment by KindDragon** [comment] 2015-05-12 13:58
Try GitExt 2.48.04

**Comment by allsorts46** [comment] 2015-05-16 19:34
Perfect, thanks.
