### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Linq.Parallel, Vers...

### ISSUE THREAD

**Issue by bmondragon** [gitextensions/gitextensions#10803] opened 2023-03-15 21:53 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.14
- DPI 96dpi (no scaling)

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Linq.Parallel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Linq.Parallel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.<ShowRecentRepositories>g__BindRepositories|60_0(IReadOnlyList`1 repos, Boolean isFavourite)
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.ShowRecentRepositories(Boolean reloadData)
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.Dashboard.RefreshContent()
   at GitUI.CommandsDialogs.FormBrowse.ShowDashboard()
   at GitUI.CommandsDialogs.FormBrowse.SetGitModule(Object sender, GitModuleEventArgs e)
   at GitUI.CommandsDialogs.FormBrowse.SetWorkingDir(String path, ObjectId selectedId, ObjectId firstId)
   at GitUI.CommandsDialogs.FormBrowse.CloseToolStripMenuItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Unsure - was closing repo and going back to dashboard

### Steps to reproduce

Close repo, back to dashboard, error happened

**Comment by gerhardol** [comment] 2023-03-15 22:33
Duplicate of https://github.com/gitextensions/gitextensions/issues/10368
Duplicate of https://github.com/gitextensions/gitextensions/issues/10624

This error seem to occur related to Windows and/or .NET updates and seem to be resolved by app or possible PC restarts.
Not sure if this can be detected, this has occurred a number of times.

Similar issues can occur if a portable installation is updated by overwriting the with new version.
You can copy the settings though from old to new.

**Closed** 2023-03-19 17:18 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
