### ISSUE TITLE
Alter {UserInput}  Add prompt

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#5298] opened 2018-08-06 15:29 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
A plain generic prompt.  
![image](https://user-images.githubusercontent.com/3629489/43725847-9f15ee04-996b-11e8-9cde-50d560436770.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
{UserInput:PROMPT HERE}

{UserInput:Enter remote name}
The prompt dialog would take an optional prompt and allow the dialog to ask for a specific value.
**Environment you encounter the issue:**

- GitExtensions version:2.51.04, could also apply to master
- GIT version: NA
- OS version: NA
- .NET version: NA

**Did this work in previous version of GitExtensions (which)?**
No

**Comment by h0lg** [comment] 2022-01-22 05:39
+1 This would indeed come in handy for multiple user inputs.

**Comment by RussKie** [comment] 2022-02-02 07:15
Duplicate of #4395

**Closed by RussKie** 2022-02-02 07:15 UTC
