### ISSUE TITLE
Commits by same author not highlighted anymore.

### ISSUE THREAD

**Issue by RequiDev** [gitextensions/gitextensions#5978] opened 2018-12-22 04:18 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Commits by the same author are not highlighted anymore since the most recent update.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
It's just like that.

**What is the expected behavior?**
Commits by the same author should be highlighted if a commit is selected
How it looks.
![image](https://user-images.githubusercontent.com/7763240/50370513-6645b600-05a8-11e9-881c-805c468ba782.png)
How it looked before
![image](https://user-images.githubusercontent.com/7763240/50370519-8c6b5600-05a8-11e9-914c-5fe8f6619f2c.png)

**Environment you encounter the issue:**
Newest update on Windows 8.1

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
Yes. In the previous stable version.

**Comment by gerhardol** [comment] 2018-12-22 09:09
Duplicate of #5197

The committer is in bold
However, this will likely be reintroduced
(the setting has no effect)

**Closed by gerhardol** 2018-12-22 09:09 UTC
