### ISSUE TITLE
Win32Exception at System.Drawing.Icon.Initialize(Int32, Int32)

### ISSUE THREAD

**Issue by lucas-foreflight** [gitextensions/gitextensions#9052] opened 2021-04-06 15:25 UTC
Hi guys,

Love this product!
Recently i've run into an issue that I haven't had before. Not sure exactly when it started.
We recently moved our repository from bitbucket to github, thats about the only thing that has changed recently that i can think of.

## Current behaviour

Sometimes when switching branches and then opening the pull dialog gitextensions will hang and then crash without any error dialog. 

## Expected behaviour

Gitextensions should not crash after switching branches and opening the pull dialog.

## Steps to reproduce

Change branch and then open the pull dialog

## Did this work in previous version of GitExtensions

I have used git extensions for many years and I believe this bug might be recently added

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 120dpi (125% scaling)

## Diagnostics

I grabbed a stacktrace from windows event log

```
Application: GitExtensions.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at System.Drawing.Icon.Initialize(Int32, Int32)
   at System.Drawing.Icon..ctor(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.SerializationInvoke(System.IRuntimeMethodInfo, System.Object, System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext ByRef)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(System.Object, System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(System.Runtime.Serialization.ObjectHolder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(System.Runtime.Remoting.Messaging.HeaderHandler, System.Runtime.Serialization.Formatters.Binary.__BinaryParser, Boolean, Boolean, System.Runtime.Remoting.Messaging.IMethodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(System.IO.Stream, System.Runtime.Remoting.Messaging.HeaderHandler, Boolean, Boolean, System.Runtime.Remoting.Messaging.IMethodCallMessage)
   at System.Resources.ResourceReader.DeserializeObject(Int32)
   at System.Resources.ResourceReader._LoadObjectV2(Int32, System.Resources.ResourceTypeCode ByRef)
   at System.Resources.ResourceReader.LoadObjectV2(Int32, System.Resources.ResourceTypeCode ByRef)
   at System.Resources.ResourceReader.LoadObject(Int32, System.Resources.ResourceTypeCode ByRef)
   at System.Resources.RuntimeResourceSet.GetObject(System.String, Boolean, Boolean)
   at System.Resources.RuntimeResourceSet.GetObject(System.String, Boolean)
   at System.Resources.ResourceManager.GetObject(System.String, System.Globalization.CultureInfo, Boolean)
   at System.Resources.ResourceManager.GetObject(System.String, System.Globalization.CultureInfo)
   at ResourceManager.Properties.Resources.get_GitExtensionsLogoIcon()
   at ResourceManager.GitExtensionsFormBase..ctor()
   at GitUI.GitExtensionsForm..ctor(Boolean)
   at GitUI.NBugReports.BugReportForm..ctor()
   at GitExtensions.Program.ReportBug(System.Exception)
   at GitExtensions.Program+<>c.<Main>b__1_2(System.Object, System.Threading.ThreadExceptionEventArgs)
   at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception)
   at System.Windows.Forms.Control.WndProcException(System.Exception)
   at System.Windows.Forms.Control+ControlNativeWindow.OnThreadException(System.Exception)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
```

And heres the loaded modules reported by event log
``` 
Version=1
EventType=CLR20r3
EventTime=132621951880386169
ReportType=2
Consent=1
UploadTime=132621951937756160
ReportStatus=268435456
ReportIdentifier=27976c58-b231-4df2-9d7d-5fd2ead4ba06
IntegratorReportIdentifier=f9232128-3312-4a77-b409-e9b6034de3db
Wow64Host=34404
Wow64Guest=332
NsAppName=GitExtensions.exe
OriginalFilename=GitExtensions.exe
AppSessionGuid=00002114-0001-0025-57a4-011af91ed701
TargetAppId=W:000633049ceecb4dce1b74c33c1c1288e91900000000!0000bba7b2666d1253d23dd06194edc44587d9d56c85!GitExtensions.exe
TargetAppVer=2076//12//23:07:27:35!14b3a!GitExtensions.exe
BootId=4294967295
TargetAsId=1047
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=07e61985c78fcb645e5d7287e68eb7de
Response.BucketTable=5
Response.LegacyBucketId=2188030921986193374
Response.type=4
Sig[0].Name=Problem Signature 01
Sig[0].Value=GitExtensions.exe
Sig[1].Name=Problem Signature 02
Sig[1].Value=3.4.3.9999
Sig[2].Name=Problem Signature 03
Sig[2].Value=c938aa67
Sig[3].Name=Problem Signature 04
Sig[3].Value=System.Drawing
Sig[4].Name=Problem Signature 05
Sig[4].Value=4.8.4084.0
Sig[5].Name=Problem Signature 06
Sig[5].Value=5dda3e18
Sig[6].Name=Problem Signature 07
Sig[6].Value=30f
Sig[7].Name=Problem Signature 08
Sig[7].Value=479
Sig[8].Name=Problem Signature 09
Sig[8].Value=N3CTRYE2KN3C34SGL4ZQYRBFTE4M13NB
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.19042.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=8192
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=bfec
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=bfec3067bf44575e5da02649664924d5
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=336a
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=336ae6cf6bb90315d88f955115151c0d
UI[2]=C:\Program Files (x86)\GitExtensions\GitExtensions.exe
LoadedModule[0]=C:\Program Files (x86)\GitExtensions\GitExtensions.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.dll
LoadedModule[3]=C:\WINDOWS\SYSTEM32\MSCOREE.DLL
LoadedModule[4]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[5]=C:\Windows\System32\hmpalert.dll
LoadedModule[6]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[7]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[8]=C:\WINDOWS\System32\sechost.dll
LoadedModule[9]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[10]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll
LoadedModule[11]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[12]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
LoadedModule[13]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[14]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
LoadedModule[15]=C:\WINDOWS\System32\USER32.dll
LoadedModule[16]=C:\WINDOWS\System32\win32u.dll
LoadedModule[17]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[18]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[19]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[20]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[21]=C:\WINDOWS\SYSTEM32\VCRUNTIME140_CLR0400.dll
LoadedModule[22]=C:\WINDOWS\SYSTEM32\ucrtbase_clr0400.dll
LoadedModule[23]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[24]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\mscorlib\218db16dceaef380c6daf35c6a48f313\mscorlib.ni.dll
LoadedModule[25]=C:\WINDOWS\System32\ole32.dll
LoadedModule[26]=C:\WINDOWS\System32\combase.dll
LoadedModule[27]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[28]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[29]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System\258d4259dd4377d917679ad4b058966e\System.ni.dll
LoadedModule[30]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[31]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[32]=C:\WINDOWS\System32\bcrypt.dll
LoadedModule[33]=C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
LoadedModule[34]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\GitExtensions\951508e1104d2064131e4243e10e0d67\GitExtensions.ni.exe
LoadedModule[35]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Drawing\3ba373bc0e75eeb7db9c82fe06787344\System.Drawing.ni.dll
LoadedModule[36]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Windows.Forms\7ee507b29b8c55d7e4c07798c42b24fd\System.Windows.Forms.ni.dll
LoadedModule[37]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Core\44e36f78b5e2f34aba2d7b5667796954\System.Core.ni.dll
LoadedModule[38]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\GitUI\cb7e63ce41d758e11ec5cd9ef86ace44\GitUI.ni.dll
LoadedModule[39]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\GitExtUtils\e7155a7f0b5da2cc2a0cf41dacc9f837\GitExtUtils.ni.dll
LoadedModule[40]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\GitCommands\da49c7c150da9be84036f5a3fd7fcb92\GitCommands.ni.dll
LoadedModule[41]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[42]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[43]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\ResourceManager\36da794e55003fb78a5324939b74a546\ResourceManager.ni.dll
LoadedModule[44]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\GitUIPlugin6b34c31c#\d0840c985b1fe08cf79588f17fc68ee3\GitUIPluginInterfaces.ni.dll
LoadedModule[45]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.IO.A6c43dedd#\a9e175f144564a0b2675126af2c831a6\System.IO.Abstractions.ni.dll
LoadedModule[46]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Configuration\02c0e0f2ac437bb15273bcf97e53b7e3\System.Configuration.ni.dll
LoadedModule[47]=C:\WINDOWS\SYSTEM32\urlmon.dll
LoadedModule[48]=C:\WINDOWS\SYSTEM32\iertutil.dll
LoadedModule[49]=C:\WINDOWS\System32\shcore.dll
LoadedModule[50]=C:\WINDOWS\SYSTEM32\SspiCli.dll
LoadedModule[51]=C:\WINDOWS\SYSTEM32\windows.storage.dll
LoadedModule[52]=C:\WINDOWS\SYSTEM32\Wldp.dll
LoadedModule[53]=C:\WINDOWS\SYSTEM32\PROPSYS.dll
LoadedModule[54]=C:\WINDOWS\System32\WINTRUST.dll
LoadedModule[55]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[56]=C:\WINDOWS\SYSTEM32\MSASN1.dll
LoadedModule[57]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsecimpl.dll
LoadedModule[58]=C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.844_none_11adecdf30011423\COMCTL32.dll
LoadedModule[59]=C:\WINDOWS\System32\imagehlp.dll
LoadedModule[60]=C:\WINDOWS\SYSTEM32\gpapi.dll
LoadedModule[61]=C:\Windows\System32\cryptnet.dll
LoadedModule[62]=C:\WINDOWS\SYSTEM32\profapi.dll
LoadedModule[63]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
LoadedModule[64]=C:\WINDOWS\SYSTEM32\WINNSI.DLL
LoadedModule[65]=C:\WINDOWS\System32\NSI.dll
LoadedModule[66]=C:\WINDOWS\SYSTEM32\WINHTTP.dll
LoadedModule[67]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[68]=C:\WINDOWS\system32\mswsock.dll
LoadedModule[69]=C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
LoadedModule[70]=C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
LoadedModule[71]=C:\WINDOWS\SYSTEM32\webio.dll
LoadedModule[72]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[73]=C:\Windows\System32\rasadhlp.dll
LoadedModule[74]=C:\WINDOWS\System32\fwpuclnt.dll
LoadedModule[75]=C:\WINDOWS\System32\shell32.dll
LoadedModule[76]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Xml\040fa6ee0be6d987f3e8edf9010ce68a\System.Xml.ni.dll
LoadedModule[77]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Deployment\d248c01148ab24a6fc1969bac803ee38\System.Deployment.ni.dll
LoadedModule[78]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll
LoadedModule[79]=C:\WINDOWS\System32\psapi.dll
LoadedModule[80]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.ValueTuple\34ffba90bca911a3129ec0b0b205a091\System.ValueTuple.ni.dll
LoadedModule[81]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\EasyHook\ff0512adb749ef0a647a8ad5327f6d37\EasyHook.ni.dll
LoadedModule[82]=C:\Program Files (x86)\GitExtensions\EasyHook32.dll
LoadedModule[83]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\ICSharpCode05d32fe8#\01faa817e0cd05c4e7f708538dd7e9fa\ICSharpCode.TextEditor.ni.dll
LoadedModule[84]=C:\WINDOWS\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.789_none_429ddec08a8f10c1\gdiplus.dll
LoadedModule[85]=C:\WINDOWS\SYSTEM32\DWrite.dll
LoadedModule[86]=C:\WINDOWS\System32\TextShaping.dll
LoadedModule[87]=C:\WINDOWS\System32\clbcatq.dll
LoadedModule[88]=C:\WINDOWS\system32\dataexchange.dll
LoadedModule[89]=C:\WINDOWS\system32\d3d11.dll
LoadedModule[90]=C:\WINDOWS\system32\dcomp.dll
LoadedModule[91]=C:\WINDOWS\system32\dxgi.dll
LoadedModule[92]=C:\WINDOWS\system32\twinapi.appcore.dll
LoadedModule[93]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Microsoft.Aa9ae3ab0#\de76079f5a5e22ac45f27104edba0891\Microsoft.ApplicationInsights.ni.dll
LoadedModule[94]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Xml.Linq\1fa17c3b5c3c63ace250e50f002604c7\System.Xml.Linq.ni.dll
LoadedModule[95]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Microsoft.Vbeb7089b#\6afd4ed6d302951fa7abbbd60ed58830\Microsoft.VisualStudio.Threading.ni.dll
LoadedModule[96]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\netstandard\978639a6b3edb626ba5d40a18739cbdc\netstandard.ni.dll
LoadedModule[97]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Microsoft.Vd43b287e#\2ec2820dcf786a8b2952c7771c101668\Microsoft.VisualStudio.Validation.ni.dll
LoadedModule[98]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Runt54187d77#\3d3942dadcd35c1cac46df0fe3ab1090\System.Runtime.InteropServices.RuntimeInformation.ni.dll
LoadedModule[99]=C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
LoadedModule[100]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Accessibility\148ff8c58268aba5a5792a515af54963\Accessibility.ni.dll
LoadedModule[101]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Coll4a4f96a7#\0b4e85e320cbd237c0d3940427b672d8\System.Collections.Immutable.ni.dll
LoadedModule[102]=C:\WINDOWS\SYSTEM32\RichEd20.DLL
LoadedModule[103]=C:\WINDOWS\SYSTEM32\USP10.dll
LoadedModule[104]=C:\WINDOWS\SYSTEM32\msls31.dll
LoadedModule[105]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Reactive\e2a6888140c231f11453d950eb4c5319\System.Reactive.ni.dll
LoadedModule[106]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\SmartFormat\bf8949cb40fc7ebfe95a9903a59d7f9c\SmartFormat.ni.dll
LoadedModule[107]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Ben.Demystifier\aef2567b422db0100cf5084e667527e6\Ben.Demystifier.ni.dll
LoadedModule[108]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Microsoft.Vfd40090d#\dbd29afc3ef1a936d9bb18df7066d234\Microsoft.VisualStudio.Composition.ni.dll
LoadedModule[109]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Microsoft.Wfbf9373c#\09f93beda3b4a7fcf3061d14eff773a2\Microsoft.WindowsAPICodePack.Shell.ni.dll
LoadedModule[110]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Microsoft.W8090224c#\13647aa00e40c55c2eba9661b0f83c24\Microsoft.WindowsAPICodePack.ni.dll
LoadedModule[111]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\ConEmu.WinForms\f7ff51737ade6f906c4f438a5de359e8\ConEmu.WinForms.ni.dll
LoadedModule[112]=C:\WINDOWS\SYSTEM32\textinputframework.dll
LoadedModule[113]=C:\WINDOWS\System32\CoreUIComponents.dll
LoadedModule[114]=C:\WINDOWS\System32\CoreMessaging.dll
LoadedModule[115]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[116]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[117]=C:\WINDOWS\system32\Oleacc.dll
LoadedModule[118]=C:\WINDOWS\system32\explorerframe.dll
LoadedModule[119]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Thre3435c1dc#\f8f15d3734dc0e460fa6ed47caac6112\System.Threading.Tasks.Dataflow.ni.dll
LoadedModule[120]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Thre7bb2aad0#\6fa446b05c749879e9a7719fc5775524\System.Threading.Tasks.ni.dll
LoadedModule[121]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Runtime\85a8cc028ebc5fd3a368a609230d0e3a\System.Runtime.ni.dll
LoadedModule[122]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Colldfb0b5ae#\960ba43a18e4ade4d588a62330dbefa1\System.Collections.Concurrent.ni.dll
LoadedModule[123]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Diagd2d95910#\4bb6e8fc46e4161c13cdb036eac433e4\System.Diagnostics.Tracing.ni.dll
LoadedModule[124]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Compba577418#\b7b4c0c13078b20de6243b522910ef4b\System.ComponentModel.Composition.ni.dll
LoadedModule[125]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Net.Http\1b2351bce088fef13d3ed096d6033fc4\System.Net.Http.ni.dll
LoadedModule[126]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\RestSharp\166af168e7a253ce9a42198366586dae\RestSharp.ni.dll
LoadedModule[127]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Comp787a79cf#\bee87191c4d719ea4638475b2c41cc82\System.Composition.AttributedModel.ni.dll
LoadedModule[128]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.ServiceModel\1664b52ea8e0604d1afc3eed2bac7dfc\System.ServiceModel.ni.dll
LoadedModule[129]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Runteb92aa12#\8e54272dd2ed41ee65c2f42f2bbe4cf6\System.Runtime.Serialization.ni.dll
LoadedModule[130]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Comp46f2b404#\7c877c40b3b8b01634f08e1ef067393d\System.ComponentModel.DataAnnotations.ni.dll
LoadedModule[131]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Git.hub\bb58662a8034d69e690afb0b5bda9746\Git.hub.ni.dll
LoadedModule[132]=C:\WINDOWS\SYSTEM32\policymanager.dll
LoadedModule[133]=C:\WINDOWS\SYSTEM32\msvcp110_win.dll
LoadedModule[134]=C:\WINDOWS\System32\CFGMGR32.dll
LoadedModule[135]=C:\WINDOWS\SYSTEM32\wininet.dll
LoadedModule[136]=C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll
LoadedModule[137]=C:\WINDOWS\SYSTEM32\rasapi32.dll
LoadedModule[138]=C:\WINDOWS\SYSTEM32\rasman.dll
LoadedModule[139]=C:\WINDOWS\SYSTEM32\rtutils.dll
LoadedModule[140]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Web\dddc343ceb71a81c0373f5ec731e09de\System.Web.ni.dll
LoadedModule[141]=C:\WINDOWS\SYSTEM32\secur32.dll
LoadedModule[142]=C:\WINDOWS\System32\schannel.dll
LoadedModule[143]=C:\WINDOWS\SYSTEM32\mskeyprotect.dll
LoadedModule[144]=C:\WINDOWS\SYSTEM32\NTASN1.dll
LoadedModule[145]=C:\WINDOWS\SYSTEM32\ncrypt.dll
LoadedModule[146]=C:\WINDOWS\system32\ncryptsslp.dll
LoadedModule[147]=C:\WINDOWS\SYSTEM32\sxs.dll
LoadedModule[148]=C:\WINDOWS\system32\napinsp.dll
LoadedModule[149]=C:\WINDOWS\system32\pnrpnsp.dll
LoadedModule[150]=C:\WINDOWS\system32\wshbth.dll
LoadedModule[151]=C:\WINDOWS\system32\NLAapi.dll
LoadedModule[152]=C:\WINDOWS\System32\winrnr.dll
LoadedModule[153]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\NetSpell.Sp28e7a725#\ebba7bd5815721302ac5972845934943\NetSpell.SpellChecker.ni.dll
LoadedModule[154]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Microsoft.CSharp\0c120e97f16fd568e452f73b7f7c4849\Microsoft.CSharp.ni.dll
LoadedModule[155]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Dynamic\22b854c793bc9398a604a86186302860\System.Dynamic.ni.dll
LoadedModule[156]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\WindowsBase\1c3c9a90b8dcd44b44fbb8a8d68e4617\WindowsBase.ni.dll
LoadedModule[157]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\PresentationNative_v0400.dll
LoadedModule[158]=C:\WINDOWS\SYSTEM32\edputil.dll
LoadedModule[159]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\PSTaskDialog\f7799aed87f6fa8281e6d3ef91e2c3c1\PSTaskDialog.ni.dll
LoadedModule[160]=C:\WINDOWS\system32\apphelp.dll
LoadedModule[161]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Data\9a539c0943d820a2fd5453ee60269f38\System.Data.ni.dll
LoadedModule[162]=C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
LoadedModule[163]=C:\Program Files (x86)\Common Files\microsoft shared\ink\tiptsf.dll
LoadedModule[164]=C:\WINDOWS\SYSTEM32\atlthunk.dll
LoadedModule[165]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\webengine4.dll
LoadedModule[166]=C:\WINDOWS\SYSTEM32\USERENV.dll
LoadedModule[167]=C:\WINDOWS\system32\Ninput.dll
LoadedModule[168]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=19042
OsInfo[3].Key=ubr
OsInfo[3].Value=867
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=61
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=221033892
OsInfo[15].Key=osinsty
OsInfo[15].Value=1
OsInfo[16].Key=iever
OsInfo[16].Value=11.789.19041.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=32509
OsInfo[19].Key=svolsz
OsInfo[19].Value=936
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=191206
OsInfo[22].Key=bldtm
OsInfo[22].Value=1406
OsInfo[23].Key=bldbrch
OsInfo[23].Value=vb_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.19041.867.amd64fre.vb_release.191206-1406
OsInfo[30].Key=buildflightid
OsInfo[30].Value=AFBFD20A-E84A-4FA1-8A13-8B50298D5BBA.1
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[33].Key=expid
OsInfo[34].Key=fconid
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=1
FriendlyEventName=Stopped working
ConsentKey=CLR20r3
AppName=Git Extensions
AppPath=C:\Program Files (x86)\GitExtensions\GitExtensions.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=AFE71C6C925F6880133CDC94F2078914
MetadataHash=1637884508
```

**Comment by gerhardol** [comment] 2021-04-06 22:15
The original cause is unknown, this is the NBug reporter that crashes...

Can you please try 3.5 SP1 (portable version is fine) to see if the problem still occurs?
There has been changes to the error handling in 3.5. (Some tweaks are still done.)

**Comment by lucas-foreflight** [comment] 2021-04-07 08:45
Sure, ill give it a shot. Do remember that it doesnt always happen. So I will use this for a couple of days and see if the issue occurs along the way.

**Comment by mstv** [comment] 2021-04-07 15:29
I could not reproduce this issue, but found #9055.

> The original cause is unknown, this is the NBug reporter that crashes...

> We recently moved our repository from bitbucket to github

Just guessing: The GitHub plugin might have triggered the BugReportForm.

Though anyway, there must have been displayed a TaskDialog with an error message before attempting to open the BugReportForm.
Do you remember the message?

**Comment by lucas-foreflight** [comment] 2021-04-08 07:58
I dont use the github plugin. I interact with github via putty and ssh.
I didnt get any popup no. As stated the application simply hangs when attempting to open the pull dialog after swithing branches.
My default action is to open the dialog.
The other issue you mentioned mentions switching repos, which i dont do either.

**Comment by mstv** [comment] 2021-04-08 22:07
Sorry, I must have been in hurry and mixed things up.
Do you use only the toolbar for switching branches and to open the pull dialog? How quickly do you open it?

I still guess that a background action (either built-in or a plug-in) threw an unhandled exception.
I expect with 3.5 RC1, it will result in #9047. So it might be worth to rather run #9048.

**Comment by lucas-foreflight** [comment] 2021-04-09 07:59
I was using the toolbar for both yes. Usually i open the pull dialog as soon as the branch is rendered, ie. it looks ready for use.

**Comment by RussKie** [comment] 2021-04-10 02:21
Thanks for the report. Looks like something failed while you're opening the dialog, and the app was trying to show the bug report form:
```
   at ResourceManager.Properties.Resources.get_GitExtensionsLogoIcon()
   at ResourceManager.GitExtensionsFormBase..ctor()
   at GitUI.GitExtensionsForm..ctor(Boolean)
   at GitUI.NBugReports.BugReportForm..ctor()
   at GitExtensions.Program.ReportBug(System.Exception)
   at GitExtensions.Program+<>c.<Main>b__1_2(System.Object, System.Threading.ThreadExceptionEventArgs)
```

Without a stable repro I'm not sure we can intelligently reason about this failure.


@mstv it is possible that the exception came from a background thread, which could have thrown a wrench into the mix...

**Comment by lucas-foreflight** [comment] 2021-05-04 09:51
Just wanted to let you know that I havent experienced the issue yet on 
- Git Extensions 3.5.0.11509
- Build 009d10c765a90aa00e043e40d5117256b793bc8c (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 120dpi (125% scaling)

**Comment by RussKie** [comment] 2021-05-05 08:20
Thanks for the follow up. I'm going to close it, but holler back if you experience this again.

**Closed by RussKie** 2021-05-05 08:20 UTC
Labels: :beetle: type: bug
