### ISSUE TITLE
GitExtensions freezes when commit button is clicked

### ISSUE THREAD

**Issue by arijit-code** [gitextensions/gitextensions#8403] opened 2020-08-13 20:17 UTC
## Current behaviour
![image](https://user-images.githubusercontent.com/59074787/90181802-db5d9480-dd65-11ea-8a4c-d9cc11008247.png)

![image](https://user-images.githubusercontent.com/59074787/90181899-02b46180-dd66-11ea-878a-24f1b451c1b3.png)
When the commit button is clicked no window is opened and GitExtensions is freezing and stops responding altogether.  I have to kill it using the Task Manager.

## Expected behaviour
Should open commit window

## Steps to reproduce
- Open GitExtensions
- Click on Commit button

## Screenshots
![image](https://user-images.githubusercontent.com/59074787/90182236-7f474000-dd66-11ea-93f6-cced3589db76.png)

## Did this work in previous version of GitExtensions
Yes

## Environment
Windows 10 Enterprise. 64 Bit OS.

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4200.0
- DPI 144dpi (150% scaling)

My most cordial Thanks for writing such a helpful product. I use it regularly and it has helped me a lot.  Thank you.

**Comment by pmiossec** [comment] 2020-08-13 20:25
Duplicate of #6427. 
That's a problem with commit form positioning. 
See there for a workaround... 

https://github.com/gitextensions/gitextensions/issues/6427#issuecomment-573628576

**Comment by pmiossec** [comment] 2020-08-13 20:29
I don't know if #8341 could solve this problem...

**Closed** 2020-08-13 20:57 UTC
