### ISSUE TITLE
[NBug] Ungültiger URI: Der Hostname konnte nicht analysiert werden.

### ISSUE THREAD

**Issue by satdast** [gitextensions/gitextensions#9287] opened 2021-06-14 08:16 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.UriFormatException: Ungültiger URI: Der Hostname konnte nicht analysiert werden.
   bei System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   bei System.Uri..ctor(String uriString)
   bei RestSharp.RestClient..ctor(String baseUrl)
   bei GitExtensions.GitLab.Client.Client..ctor(String gitLabDomain, String oAuthToken)
   bei GitExtensions.GitLab.GitLabPlugin.InitializeConfiguredParameters(IGitModule gitModule)
   bei GitExtensions.GitLab.GitLabPlugin.Register(IGitUICommands gitUiCommands)
   bei GitUI.PluginRegistry.<>c__DisplayClass12_0.<Register>b__0(IGitPlugin p)
   bei System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   bei GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
   bei GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   bei GitUI.CommandsDialogs.FormBrowse.SetGitModule(Object sender, GitModuleEventArgs e)
   bei GitUI.CommandsDialogs.BrowseDialog.DashboardControl.Dashboard.OnModuleChanged(Object sender, GitModuleEventArgs e)
   bei GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.OnModuleChanged(GitModuleEventArgs args)
   bei GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.listView1_MouseClick(Object sender, MouseEventArgs e)
   bei System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   bei System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   bei System.Windows.Forms.ListView.WndProc(Message& m)
   bei GitUI.UserControls.ExListView.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Added gitlab plugin

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4360.0
- DPI 144dpi (150% scaling)

**Comment by gerhardol** [comment] 2021-06-14 10:25
Please submit the bug to the GitLab plugin repo https://github.com/ahmeturun/GitExtensions.GitLab

Duplicate of https://github.com/ahmeturun/GitExtensions.GitLab/issues/3
and likely also https://github.com/ahmeturun/GitExtensions.GitLab/issues/2

**Closed by gerhardol** 2021-06-14 10:25 UTC
