### ISSUE TITLE
[NBug] Blame when opened from VS GitExtensions plugin (Object reference not set to an instance of an object.)

### ISSUE THREAD

**Issue by Payn** [gitextensions/gitextensions#10395] opened 2022-11-13 17:49 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.Blame.BlameControl.SelectedLineChanged(Object sender, SelectedLineEventArgs e)
   at GitUI.Editor.FileViewer.<.ctor>b__53_12(Object sender, SelectedLineEventArgs e)
   at GitUI.Editor.FileViewerInternal.<.ctor>b__31_10(Object s, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseDown(MouseEventArgs e)
   at ICSharpCode.TextEditor.TextArea.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```
Might be more likely a VS plugin issue.

### Steps to reproduce

Open Blame from within Visual Studio 2019 GitExtensions plugin and click on any line.

### Did this work in previous version of GitExtensions?

Yes in 3.5.4

**Comment by mstv** [comment] 2022-11-13 17:57
#10316 should have bugfixed this.

**Comment by gerhardol** [comment] 2022-11-13 19:34
Duplicate of  #10314

**Closed by gerhardol** 2022-11-13 19:34 UTC
Labels: :eyeglasses: status: needs review
