### ISSUE TITLE
[NBug] Value must not be null.

### ISSUE THREAD

**Issue by MarcoMiXtelematics** [gitextensions/gitextensions#11777] opened 2024-06-03 10:14 UTC
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.30
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.Exception: Value must not be null.
   at void Microsoft.Validates.Fail(string message) in C:/projects/gitextensions/GitExtUtils/Validates.cs:line 35
   at async void GitUI.CommandsDialogs.FormCheckoutBranch.Branches_SelectedIndexChanged(object sender, EventArgs e)+(?) => { } in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCheckoutBranch.cs:line 489
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

### Steps to reproduce

created a branch as an orphan. checked out a different branch

**Comment by gerhardol** [comment] 2024-06-03 10:56
Duplicate of https://github.com/gitextensions/gitextensions/issues/11498
Fixed in https://github.com/gitextensions/gitextensions/pull/11500

Also related to https://github.com/gitextensions/gitextensions/issues/11562

**Closed by gerhardol** 2024-06-03 10:56 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
