### ISSUE TITLE
[NBug] fatal: .git/index: index file open failed: Permission denied

### ISSUE THREAD

**Issue by vocko** [gitextensions/gitextensions#11111] opened 2023-07-24 04:09 UTC
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.20
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c color.ui=never -c diff.submodule=short -c diff.noprefix=false -c diff.mnemonicprefix=false -c diff.ignoreSubmodules=none -c core.safecrlf=false diff --find-renames --find-copies -U1000000 -- "Interfaces/ILockService.cs"
Working directory: D:\Code\NimbusWopi\

```
GitExtUtils.ExternalOperationException: fatal: .git/index: index file open failed: Permission denied
 ---> System.Exception: fatal: .git/index: index file open failed: Permission denied
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 128
   at GitCommands.GitModule.GetCurrentChangesAsync(String fileName, String oldFileName, Boolean staged, String extraDiffArguments, Encoding encoding, Boolean noLocks) in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 2817
   at GitUI.AutoCompletion.CommitAutoCompleteProvider.GetChangedFileTextAsync(GitModule module, GitItemStatus file) in C:\projects\gitextensions\GitUI\AutoCompletion\CommitAutoCompleteProvider.cs:line 161
   at GitUI.AutoCompletion.CommitAutoCompleteProvider.GetAutoCompleteWordsAsync(CancellationToken cancellationToken) in C:\projects\gitextensions\GitUI\AutoCompletion\CommitAutoCompleteProvider.cs:line 57
   at GitUI.SpellChecker.EditNetSpell.<InitializeAutoCompleteWordsTask>b__109_0() in C:\projects\gitextensions\GitUI\SpellChecker\EditNetSpell.cs:line 888
   at Microsoft.VisualStudio.Threading.AwaitExtensions.ExecuteContinuationSynchronouslyAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Threading.AsyncLazy`1.<>c__DisplayClass13_0.<<GetValueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitUI.SpellChecker.EditNetSpell.UpdateOrShowAutoComplete(Boolean calledByUser)
   at GitUI.SpellChecker.EditNetSpell.AutoCompleteTimer_Tick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\SpellChecker\EditNetSpell.cs:line 1076
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Not sure what is the source of the problem, started to appear while typing commit message

### Steps to reproduce

I was just trying to type commit message during commit preparation.

### Did this work in previous version of GitExtensions?

Never had this problem before.

**Comment by gerhardol** [comment] 2023-07-24 07:49
Duplicate of #10499
Fixed in #11030 next release
In this scenario the exception can be ignored

**Closed** 2023-07-24 07:50 UTC
Labels: potential-duplicate
