### ISSUE TITLE
[NBug] Cannot start process because a file name has not been provi...

### ISSUE THREAD

**Issue by LightCC** [gitextensions/gitextensions#6875] opened 2019-06-27 16:48 UTC
# Current behaviour
Merge with a conflicting binary file. Open the "Resolve merge conflicts" window and select the conflicted binary file. Then either click the `Merge` button (that generated this particular error case), or click the `Open in code` button - both appear to crash every time.

### Other Comments:
* This is a fresh install of v3.x WITHOUT kdiff3 installed on the machine - not sure if that is related.
* the specific binary files typically used are Matlab/Simulink model files (*.slx), which are zipped xml files with other embedded data (like thumbnail images).
* The merge tool is setup for VS Code in the global git config - which works fine for text file merge conflicts. It also launches fine from the `mergetool` script (which can be launched from the `run mergetool` button). So the git config appears to be fine.
* Here's the appropriate sections of my config, with the VS Code binary home (where code.exe exists) on the path:
```
[merge]
	tool = code
	guitool = code
[mergetool]
	prompt = false
[difftool "code"]
	cmd = code --wait --diff \"$LOCAL\" \"$REMOTE\"
[mergetool "code"]
	cmd = code --wait \"$MERGED\"
```

I've tried several different things without success, it appears to be completely repeatable. Occurs on a peer's setup as well, with similar versions and tool setup.

## Expected behaviour
Should not crash (provide the function of the related buttons).

## Steps to reproduce
See "Current behaviour" for steps to reproduce.

## Error Details
```
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.ExecutableExtensions.<ExecuteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, Boolean stripAnsiEscapeCodes)
   at GitUI.CommandsDialogs.FormResolveConflicts.ResolveFilesConflict(ConflictData item)
   at GitUI.CommandsDialogs.FormResolveConflicts.ResolveItemConflict(ConflictData item)
   at GitUI.CommandsDialogs.FormResolveConflicts.ConflictedFiles_DoubleClick(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.FormResolveConflicts.OpenMergetool_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-06-27 16:56
Duplicate of #6687

Diff tool is not found by ge. Set the full path. 
Please try latest master.

**Closed by gerhardol** 2019-06-27 16:56 UTC

**Comment by RussKie** [comment] 2019-06-29 06:26
Please try the latest dev build to see if the issue is fixed
https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts
