### ISSUE TITLE
"Clean working directory" log shows part of the command line

### ISSUE THREAD

**Issue by pedrolamas** [gitextensions/gitextensions#9100] opened 2021-04-23 08:24 UTC
## Current behaviour

First line of the "Clean working directory" log window will show "lean -x -d --dry-run"

## Expected behaviour

"Clean working directory" log window just shows output of the command, but not the command itself.

## Steps to reproduce

- Go to `Commands` and click `Clean working directory`
- Click `Preview` button

## Screenshots

![image](https://user-images.githubusercontent.com/85504/115842233-85bda980-a415-11eb-9e72-071fe4d7a74a.png)

## Did this work in previous version of GitExtensions

Yes, but I'm not sure which one I last saw it correctly...

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4341.0
- DPI 192dpi (200% scaling)

**Comment by pmiossec** [comment] 2021-04-23 08:40
Duplicate of #8580. Fixed in next release by https://github.com/gitextensions/conemu-inside/pull/24

**Comment by pmiossec** [comment] 2021-04-23 08:41
You could still test the development version to confirm: https://github.com/gitextensions/gitextensions#downloads

**Closed by pmiossec** 2021-04-23 08:40 UTC

**Comment by pedrolamas** [comment] 2021-04-25 11:15
Confirmed, this issue has been fixed in 3.5.0.11713 (which I just installed!)

Thank you for your help! 🙂
