### ISSUE TITLE
show remote branches always has check mark

### ISSUE THREAD

**Issue by vzabavnov** [gitextensions/gitextensions#4367] opened 2018-01-17 15:47 UTC
version 2.50.02
The context menu View->Show Remote Branches always has check mark on

**Comment by gerhardol** [comment] 2018-01-17 23:59
Seem to be working for me in 2.51.RC2

**Comment by RussKie** [comment] 2018-01-18 11:05
Duplicate of #3730

**Closed by RussKie** 2018-01-18 11:05 UTC
