### ISSUE TITLE
.NET popup directs user to incorrect version (6.0.11)

### ISSUE THREAD

**Issue by EchelonForce** [gitextensions/gitextensions#10403] opened 2022-11-14 13:10 UTC
### Environment

- GitExtensions version: 4.0.0.15569
- GIT version: 2.30.2
- OS version: Windows NT 10.0.19042.0
- .NET version: 6.0.11

### Issue description

When GE checks for .NET 6.0.9, and doesn't find it, it opens a page for .net 6.0.11 (probably the latest page). Installing 6.0.11 doesn't satisfy the app's check, so one must manually find and install 6.0.9.

Either the check is too restrictive (6.0.11 seems to work if 6.0.9 is also installed) or the link in the download dialog is wrong.

### Steps to reproduce

Uninstalled GitExtensions-3.5.4.12724 per 4.0.0 installer's request.
Clean install GitExtensions-4.0.0-cba315df5.msi (installed for user only), otherwise all default selections.
Launch GE, dialog pops up for .NET 6.0.9 installer download. 
Click through to page in dialog, which leads to .Net 6.0.11 installer.
Download and install .Net 6.0.11
Launch GE, dialog pops up for .NET 6.0.9 installer download. 

Work around:
Manually install .NET 6.0.9 from different link.

### Did this work in previous version of GitExtensions?

Not applicable. Manual .NET install not required in older versions.

**Comment by RussKie** [comment] 2022-11-14 13:13
Duplicate of #10337

**Comment by RussKie** [comment] 2022-11-14 13:13
Please install .NET Desktop runtime.

**Closed by RussKie** 2022-11-14 13:13 UTC
Labels: :eyeglasses: status: needs review
