### ISSUE TITLE
Not able to launch GIT Extensions 2.49

### ISSUE THREAD

**Issue by whpham** [gitextensions/gitextensions#3487] opened 2017-01-09 19:22 UTC
When I launch Git Extensions, I get a System.UnauthorizedAccessException. I have tried uninstalling, delete C:\Users\wpham\AppData\Roaming\GitExtensions and reinstalling. I also had IT grant me Admin rights. Still having this issue when I try to run Git Extensions.

Installed:
Win 7 Pro SP1
Git 2.11.0 64 Bit
Git Extensions 2.49

Issue:
When I launch Git Extensions, I get a System.UnauthorizedAccessException

   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at Microsoft.Win32.Registry.SetValue(String keyName, String valueName, Object value, RegistryValueKind valueKind)
   at GitExtensions.Program.Main()

Target Site: Void Win32Error(Int32, System.String) @ Microsoft.Win32.RegistryKey
Application: GitExtensions.exe [2.49]
NBug: 1.2.0.0
CLR: 4.0.30319.42000

**Comment by vbjay** [comment] 2017-01-09 22:39
We need to yank out registry access.  The settings have been moved to user
profile files a long time ago.

**Comment by whpham** [comment] 2017-01-10 15:19
I uninstalled Git Extensions version 2.49 and installed an older version of Git Extensions (2.48.05). 
Git Extensions will now launch and does not throw a System.UnauthorizedAccessException.

**Comment by rbares** [comment] 2017-05-01 13:33
Likely to be caused by WebBrowserEmulationMode.SetBrowserFeatureControl(). Exception should certainly be caught but failure may result in a regression #2654 so uncertain how best to warn user of the potential issue. As the lack of permissions may not change I suspect we should give option to not warn again.

**Comment by jbialobr** [comment] 2017-05-04 11:22
We can show `reg add` command to add this key manually or we can offer to run that command with elevated privilages. Even silently catching this exception is better than crashing the app.

**Comment by RussKie** [comment] 2018-06-26 04:04
This should have been fixed in d2977ba08d234cc093d7da0c2f7b44327f14b957

**Closed by RussKie** 2018-06-26 04:04 UTC
Labels: bug
