### ISSUE TITLE
Avatars makes app unresponsive on slow internet connection

### ISSUE THREAD

**Issue by patrikturi** [gitextensions/gitextensions#5309] opened 2018-08-10 15:06 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I open a repository in GitExtensions with gitex.cmd sometimes the window goes to "not responding" for 15-30 seconds. It does now always happen. I've checked it and git commands take below 100ms and CPU usage is low. Also I noticed that if it is a freshly cloned repository, it greatly increases the chance of this bug happening (new repo about 30%, old repo just 5%). Killing the window and re-opening will get "not responding" again. However, if I wait until the "not responding" phase is done, re-opening the same repo is fine, the bug does not happen.
There is no other GitExtensions instance open when the issue happens.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.04
- GIT version: git version 2.18.0.windows.1 (most likely irrelevant)
- OS version: both Win7 and Win10
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**
I think last version I tried without this bug was 2.49.03. After 2.50.0 I was constantly updating hoping it is fixed but it was not.

**Comment by vbjay** [comment] 2018-08-10 17:13
Run this in git bash in the folder where the repo is located.
```bash
git count-objects -v -H >before.txt
git gc --aggressive
git count-objects -v -H >after.txt  
cat before.txt after.txt >full.txt
```

Show the contents of the full.txt file.

**Comment by RussKie** [comment] 2018-08-20 07:58
Could you post the timings from gitcommand log (Tools > Gitcommand log)?

Do you have an antivirus that may be interfering?

**Comment by Dimitri0xff** [comment] 2018-08-30 12:16
I have used 2.49.03 for a week and zero issues. Same git, same windows, same anti virus (Symantec).

Now I have switched back to 2.51.04 and the issue popped up after some hours again.

Here is the Command log after the issue happened:
![log](https://user-images.githubusercontent.com/13408366/44850866-ded1e100-ac5e-11e8-95c4-0be5aada550e.png)

@vbjay 
I tried but if I do your commands after the issue happened, it shows no difference. If I clone the project again, then the "Not responding" issue does not happen. Sorry I think I was wrong that it happens more often with fresh repositories, it happens just as well with existing ones.

**Comment by RussKie** [comment] 2018-08-30 12:34
Nothing in your log looks out of ordinary, timings are in hundreds of ms

**Comment by vbjay** [comment] 2018-08-30 12:40
Try turning off your antivirus. Load a repo. Let us know the results. 95%
of the time it's antivirus.

**Comment by Dimitri0xff** [comment] 2018-08-30 16:08
Turned off antivirus, it happened again. And it does not happen with 2.49.03 and antivirus.

I don't use any submodules.
It seems to affect all repos, as the occurence seems to be random.

**Comment by vbjay** [comment] 2018-08-30 20:04
Show your git config -l results.

**Comment by Dimitri0xff** [comment] 2018-08-31 12:56
Now I have experienced it happens when I click on the commit of a new person for the very first time, and also happens after I do a  "Clear image cache" and restart GitExtensions.

I was using the Identicon image service, now I have set the image service to None but the issue is still there. Any tips how to disable this feature completely? Because now that I have set it to None most people are shown black, but a for few who have uploaded a picture, that picture is still shown to me after clearing the cache.

![gitext](https://user-images.githubusercontent.com/13408366/44913533-fa57ed00-ad2d-11e8-908a-2654be3214b2.png)

**Comment by RussKie** [comment] 2018-09-01 06:39
Images are stored under `C:\Users\<user>\AppData\Roaming\GitExtensions\GitExtensions\Images`.
`Clear image cache` option will delete all images from that folder.

`No image service` is a flag to tell avatar resolution service that _if avatar can't be found, use the default one_ (the `None` option). Other options (`Identicon` et al) will hit gravatar.com to source images.

**Comment by Dimitri0xff** [comment] 2018-09-07 18:40
I had gravatar turned off all week and zero issues, so that is it.

**Comment by drewnoakes** [comment] 2018-09-07 19:12
This should definitely not be blocking the UI.

**Comment by gerhardol** [comment] 2019-01-03 23:37
A change related to this is done in #5878, planned for 3.0.1

**Comment by drewnoakes** [comment] 2019-01-04 11:48
See also #5859.

**Comment by RussKie** [comment] 2019-02-25 11:23
Fixed in https://github.com/gitextensions/gitextensions/pull/6287

**Closed by RussKie** 2019-02-25 11:23 UTC
Labels: type: bug
