### ISSUE TITLE
Unable to activate Git Extensions window with using Taskbar Thumbnail Preview

### ISSUE THREAD

**Issue by shirayuki** [gitextensions/gitextensions#10175] opened 2022-09-01 03:10 UTC
### Environment

- Git Extensions 33.33.33
- Build 649eef87a9f6276e5035a979c563fddd827391d5
- Git 2.37.2.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET 6.0.8

### Issue description

Unable to activate Git Extensions window with using Taskbar Thumbnail Preview

### Steps to reproduce

- Launch multiple Git Extensions and open a repository in each.
- Minimize all windows.
- Hover over Git Extensions icon in the taskbar.
- Click one of Taskbar Thumbnail Previews.
- Git Extensions window is not activated.

**Comment by gerhardol** [comment] 2022-09-01 06:51
Duplicate of #9752 

The problem does not occur for all and some more steps are required to reproduce for me.
A fix exists in #10119 but it seem to have other consequences.

The problem seem to have started with .NET5. I have had it with .NET6.0.3 or so (?) and 6.0.8 too.
I have Microsoft Windows NT 10.0.19044.0 at work where I see this more often

**Closed by gerhardol** 2022-09-01 06:51 UTC
Labels: :eyeglasses: status: needs review
