### ISSUE TITLE
Reorder Browse buttons

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5319] opened 2018-08-15 21:06 UTC
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
GE lists Browse buttons as: Stash, Commit, Pull, Push
![image](https://user-images.githubusercontent.com/6248932/44172736-55f36b00-a0de-11e8-8552-32a82b69794d.png)

When a repo is loaded and stash count or commit count are added to the buttons, it is easy to miss Pull and click another button instead. repo/branch is still dynamic, but that size is update quicker.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/6248932/44173168-69530600-a0df-11e8-93f8-92024d042e43.png)

This is just a few lines of change.

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
no

**Comment by RussKie** [comment] 2018-08-16 09:59
Duplicate of #1931?

**Comment by gerhardol** [comment] 2018-08-16 20:06
> Duplicate of #1931?

There it was, I was looking for a comment in a recent PR/issue!

**Closed** 2018-08-16 20:12 UTC
