### ISSUE TITLE
Improve AppVeyor icon

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5290] opened 2018-08-05 18:02 UTC
**Do you want to request a *feature* or report a *bug*?**

UI improvement

**What is the current behavior?**

The current AppVeyor icon doesn't have a transparent background:

![image](https://user-images.githubusercontent.com/350947/43688500-ece095ec-98e1-11e8-9ab4-ded392c11036.png)

**What is the expected behavior?**

Renders more nicely, with proper transparency.

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**

No.

**Comment by illfated** [comment] 2018-10-17 16:33
Well, being a newbie to the Git Extensions source, I had a go at searching and browsing the code to see where these bits are located (and I failed). I did find the internal .png icon files, but not AppVeyor. I tried to see if I could make out which part of the code is responsible for this AppVeyor icon, but I was unable to distinguish regular code from particular pointers to where the icon is located. Would it be OK to ask for hints to where this code is located?

**Comment by jbialobr** [comment] 2018-10-17 17:37
It is loaded dynamically from the build server. See https://github.com/gitextensions/gitextensions/blob/7edc265403b54dd8ea2b8402f8790219d8d42077/GitUI/CommandsDialogs/BuildReportTabPageExtension.cs#L134

**Comment by drewnoakes** [comment] 2018-10-17 18:55
It may be that the downloaded file does not have an alpha channel.

We currently bundle icons for GitHub, visualstudio.com, Bit bucket. We could introduce others.

**Comment by illfated** [comment] 2018-10-17 19:11
> It may be that the downloaded file does not have an alpha channel.

Yes, that was on my mind too. Or that maybe there exists a circular icon instead of the square one.

**Comment by wischi-chr** [comment] 2020-10-21 20:47
AppVeyor changed their favicon and the current one looks pretty crisp.
Should we still consider shipping own icons for the build report tab?

**Comment by drewnoakes** [comment] 2020-10-21 21:15
@wischi-chr can you share a screenshot?

**Comment by wischi-chr** [comment] 2020-10-21 21:20
Sure.

![image](https://user-images.githubusercontent.com/2495113/96788381-b8013680-13f3-11eb-94e6-f09a057f0256.png)

and again with the dark theme

![image](https://user-images.githubusercontent.com/2495113/96788412-c3ecf880-13f3-11eb-8539-8956518b0f9d.png)

Compared to the original screenshot it looks awesome ^^

**Comment by pmiossec** [comment] 2020-10-21 21:41
I have started to do it one year ago...
See https://github.com/pmiossec/gitextensions/tree/embedded_CI_icons

I don't exactly remember why I didn't gave it a last effort before doing a PR.

Maybe because the icon was used as a flag to see if the control was already initialized and that required some more tests to see if no regression was introduced....
Or perhaps because priority changed...

**Comment by pmiossec** [comment] 2020-10-21 21:48
Oh and feel free to continue what I started if you want...

**Comment by drewnoakes** [comment] 2020-10-22 10:07
Given the icon now looks good I'm not sure what value shipping our own has.

**Comment by wischi-chr** [comment] 2020-11-01 16:35
IMO it's probably not worth the effort. The only value it would potentially provide, would be the fact that shipping our own could prevent a regression if AppVeyor would change their favicon again to something that doesn't look good.

I think we should close it - and only ship an embedded icon in the (very unlikely case) that the issue resurfaces.

**Closed** 2020-11-02 01:34 UTC
Labels: :neckbeard: status: pull request only, :nerd_face: good first issue, area: user experience, up-for-grabs
