### ISSUE TITLE
Button in Open Repository... not fully visible.

### ISSUE THREAD

**Issue by tompollok** [gitextensions/gitextensions#4335] opened 2018-01-08 11:35 UTC
**Do you want to request a *feature* or report a *bug*?**

UI bug: The open local repository dialog occludes the open button.

![grafik](https://user-images.githubusercontent.com/4457821/34669064-4a70b794-f470-11e7-9267-173f2c3dd59d.png)

**What is the current behavior?**

button is not fully visible

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Strg+O

System: Windows 10 with 4K Displays

**What is the expected behavior?**

The button should be fully visible

**Environment you encounter the issue:**

- GitExtensions version: 2.51.RC1 

**Did this work in previous version of GitExtensions (which)?**

no

**Comment by tompollok** [comment] 2018-01-08 12:43
Same for Clone repository

![grafik](https://user-images.githubusercontent.com/4457821/34671220-f8b7c1e0-f479-11e7-9efb-3ab1ddb57917.png)

**Comment by RussKie** [comment] 2018-01-08 13:31
What's "Strg"? Is that a CTRL key?

**Comment by RussKie** [comment] 2018-01-08 13:32
Duplicate of #4174

**Comment by RussKie** [comment] 2018-01-08 13:33
Have a look at https://github.com/gitextensions/gitextensions/issues/4099 for possible workaround

**Closed by RussKie** 2018-01-08 13:32 UTC
Labels: visual hdpi
