### ISSUE TITLE
[NBug] fatal: bad revision 'NXP/10.5.0'

### ISSUE THREAD

**Issue by dima1308** [gitextensions/gitextensions#11178] opened 2023-08-28 11:02 UTC
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET 6.0.16
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" --max-count=100000 --glob=refs/stas[h] NXP/10.5.0 --
Working directory: C:\git\portfolio\

```
GitExtUtils.ExternalOperationException: fatal: bad revision 'NXP/10.5.0'
 ---> System.Exception: fatal: bad revision 'NXP/10.5.0'
   --- End of inner exception stack trace ---
   at void GitUI.RevisionGridControl.PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs, bool forceRefresh)+() => { } in C:/projects/gitextensions/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:line 1309
   at async Task GitUI.GitUIExtensions.InvokeAsync(Control control, Action action, CancellationToken token) in C:/projects/gitextensions/GitUI/GitUIExtensions.cs:line 239
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { } in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 41
```

I'm trying to filter branches. When entering branch name (NXP/10.5.0), the SW crashes.
Note: NXP/10.5.0 is existing branch in my repo.

### Steps to reproduce

1. Open our repository
2. In branches filter type NXP/10.5.0 (this is the existing branch in our repo)
3. Click enter - After clicking enter the SW crashes

### Did this work in previous version of GitExtensions?

I don't know

**Comment by vbjay** [comment] 2023-08-28 11:08
Read the error. It did not crash. It is exposung the error from git. Double check spelling.

**Comment by gerhardol** [comment] 2023-08-28 12:43
Duplicate of #10981
There should be another popup in 4.1, from #10832 

The presentation of errors from Git is changed in master

**Comment by dima1308** [comment] 2023-08-28 13:19
After looking into it more deeply, I saw that the issue is happening for branches that have files that are not allowed in Windows (for example `con.c` or `prn.txt`), see: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions
It should not be an error since no one asked to checkout the branch that includes the reserved file name - I only asked to filter branches.

**Comment by gerhardol** [comment] 2023-08-28 13:40
It is a Git issue.
GE should not swallow all issues from Git, it is up to the user to decide what to do.

**Comment by RussKie** [comment] 2023-10-12 07:06
The stack trace is similar to #11204, though the means to trigger the exception are different.
We need a more graceful handling of non-existing or otherwise unavailable branches.

I'm going to close this (though this is an older report) in favour of #11204 because the steps reported there are easier to replicate.

**Comment by RussKie** [comment] 2023-10-12 07:06
Duplicate of #11204

**Closed by RussKie** 2023-10-12 07:06 UTC
Labels: type: git issue
