### ISSUE TITLE
Git Addin make VS2013 Crash

### ISSUE THREAD

**Issue by Xarkam** [gitextensions/gitextensions#2601] opened 2015-01-07 19:25 UTC
I updated GE 2.48 to 2.48.3 and now my vs 2013 don't start.
So my windows event log see: 
```
Nom de l’application défaillante devenv.exe, version : 12.0.31101.0, horodatage : 0x54548724
Nom du module défaillant : clr.dll, version : 4.0.30319.34209, horodatage : 0x5348961e
Code d’exception : 0xc00000fd
Décalage d’erreur : 0x00050a8d
ID du processus défaillant : 0x1d88
Heure de début de l’application défaillante : 0x01d02aacf2fb43fb
Chemin d’accès de l’application défaillante : C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe
Chemin d’accès du module défaillant: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
ID de rapport : 35bd63d5-96a0-11e4-82b5-448a5b401d84
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 
```

To tempory resolve this problem, I removed 
* GitPlugin.AddIn
* GitPlugin.dll
* En-us folder

**Comment by Phil350** [comment] 2015-01-07 23:44
I have the same problem: An unhandled Microsoft .NET Framework exception occurred in devenv.exe [6276].

Having the gitExtentions toolbar enabled fixes the startup problem. IE Hidden, it will crash VS2013 at startup every time. Visable, all good.

**Comment by okli23** [comment] 2015-01-08 09:12
I have similar (the same?) problem.

### How to reproduce:
1. Move toolbar to the first line (maybe not necessary)
2. Hide toolbar

### Result:
In the 
`C:\Users\[username]\Documents\Visual Studio 2013\Settings\CurrentSettings.vssettings`
there is an entry:
`
<add_toolbar Menu="{19872127-B0D9-11D2-8792-00C04F7971A5}:00000003" Name="G&amp;itExt" MenuType="menu"/><add_toolbar Menu="{19872127-B0D9-11D2-8792-00C04F7971A5}:00000004" Name="GitExtensions" MenuType="toolbar"/><modify_toolbar Menu="{19872127-B0D9-11D2-8792-00C04F7971A5}:00000004" Name="GitExtensions" Visibility="hide" FullScreen="hide" Dock="top" Row="1" FloatRectangle="0,0,208,26" DockRectangle="31,0,208,26"/>
`

### Workaround:
Remove the `<modify_toolbar ... />` entry, move Visibility and FullScreen attributes to the `<add_toolbar ... />` entry, to have:
`
<add_toolbar Menu="{19872127-B0D9-11D2-8792-00C04F7971A5}:00000003" Name="G&amp;itExt" MenuType="menu"/><add_toolbar Menu="{19872127-B0D9-11D2-8792-00C04F7971A5}:00000004" Name="GitExtensions" MenuType="toolbar" Visibility="hide" FullScreen="hide"/>
`

**Comment by KindDragon** [comment] 2015-01-22 21:10
Duplicate of #2587

**Closed by KindDragon** 2015-01-22 21:10 UTC
