### ISSUE TITLE
[NBug] Cannot start process because a file name has not been provi...

### ISSUE THREAD

**Issue by dev-felix-1** [gitextensions/gitextensions#7896] opened 2020-03-25 13:18 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitUI.CommandsDialogs.FormBrowse.GenerateOrImportKeyToolStripMenuItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
i tried to add a pub key and opened "import" on tools->putty

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3056.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment] 2020-03-25 13:47
Duplicate of #7167

The PuTTY key was not added before use
Can you reproduce the problem?

**Comment by dev-felix-1** [comment] 2020-03-25 15:38
Yes. it will crash everytime I try click on the Import Option. Maybe I need to Do some setup before

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by RussKie** [comment] 2020-03-31 11:41
Do you have PuTTY installed? It should be in C:\Program Files (x86)\GitExtensions\PuTTY.
How's your SSH client is configured? It is under _Settings > Git Extensions > SSH_ and _Settings > Git > Paths_.

**Closed** 2020-05-14 18:00 UTC
Labels: :mailbox_with_no_mail: needs: author feedback, :zzz: status: no recent activity
