### ISSUE TITLE
[NBug] 'wsl -d Ubuntu-20.04 git config --includes --get user.name' returned non-zero exit code.

### ISSUE THREAD

**Issue by marekbuxobucek** [gitextensions/gitextensions#11436] opened 2023-12-10 13:49 UTC
### Environment

- Git Extensions 4.2.0.17591
- Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 1
Command: wsl
Arguments: -d Ubuntu-20.04 git config --includes --get user.name
Working directory: \\wsl$\Ubuntu-20.04\home\buxkso\projects\durance\api\

```
GitExtUtils.ExternalOperationException: External program returned non-zero exit code.
 ---> System.Exception: External program returned non-zero exit code.
   --- End of inner exception stack trace ---
   at async Task<string> GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 129
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTask<T>.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<T>(Func<Task<T>> asyncMethod, JoinableTaskCreationOptions creationOptions) x 2
   at string GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 43
   at string GitCommands.GitModule.GetEffectiveGitSetting(string setting, bool cache) in C:/projects/gitextensions/GitCommands/Git/GitModule.cs:line 2421
   at async void GitUI.CommandsDialogs.FormCommit.UpdateAuthorInfo()+(?) => { } in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCommit.cs:line 2726
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

I have created project in WSL 2 on windows and I cant openrepository from there

### Steps to reproduce

Open repository on windows from linux subsystem in wsl. Path to this project is not resolved

**Comment by gerhardol** [comment] 2023-12-10 22:15
Duplicate of https://github.com/gitextensions/gitextensions/issues/11366
Just set email/name - you cannot commit anyway
Changed in https://github.com/gitextensions/gitextensions/pull/11369 (you get the Git error when committing)

**Closed by gerhardol** 2023-12-10 22:15 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate

**Comment by sharwell** [comment] 2023-12-20 20:54
Duplicate of #11364
