### ISSUE TITLE
Problem with interactive rebase & fixup. It is not working in Git Extensions 2.49

### ISSUE THREAD

**Issue by webmaster33** [gitextensions/gitextensions#3537] opened 2017-02-20 18:19 UTC
--- GitExtensions2.49, Git 2.9.2.windows.1, Microsoft Windows NT 6.1.7601 Service Pack 1

I have a problem with interactive rebase & fixup. It is not working in Git Extensions 2.49.
Worked fine in Git Extensions 2.48 or earlier.
Using GIT 2.9.1 locally in Windows 7.
```
$ git --version
git version 2.9.1
```

Doing rebase to merge the fixup commits.
I select an earlier commit, then select Rebase current branch on master.
In Rebase window I click Show Options, the tick Interactive rebase & Preserve merges options.
Click Rebase button.

Process dialog shows the following:
`"git" rebase  -i --no-autosquash --preserve-merges "dc695e3a1e2080c69bbb1a31b435e268abdb7da0"`

The following file content appears in my Notepad++ text editor:
```
noop

# Rebase dc695e3..5081303 onto dc695e3 (1 command(s))
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

Then without ability to edit text, the file is deleted, and following result appears in the process window:
```
"git" rebase  -i --no-autosquash --preserve-merges "dc695e3a1e2080c69bbb1a31b435e268abdb7da0"
Successfully rebased and updated refs/heads/live_master.
Done
Press Enter or Esc to close console...
```

The result seems like if I had do a 
`git reset --hard "dc695e3a1e2080c69bbb1a31b435e268abdb7da0"`

I can only restore the original state by resetting to remote HEAD.
```
"git" reset --hard "50813033ba413aeeef7dd509769cf947243d3911"
HEAD is now at 5081303 fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! Create bash script.
Done
Press Enter or Esc to close console...
```

Let me know if you need further info or tests.

Could be possible to fix this?

**Comment by Radrik5** [comment] 2017-02-20 18:58
See `git help rebase`:

--preserve-merges
Recreate merge commits instead of flattening the history by replaying commits a merge commit introduces. Merge conflict resolutions or manual amendments to merge commits are not preserved.
This uses the --interactive machinery internally, but combining it with the --interactive option explicitly is generally not a good idea unless you know what you are doing (see BUGS below).

**Comment by webmaster33** [comment] 2017-02-20 20:01
Anyway, the rebase or fixup problem still have to be fixed.

**Comment by Radrik5** [comment] 2017-02-21 06:05
Try not enabling Preserve merges. Interactive rebase should work fine.

**Comment by webmaster33** [comment] 2017-02-21 07:20
I still get the following rebase file with just interactive rebase:
```
noop

# Rebase 8a242fa..9211781 onto 8a242fa (1 command(s))
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out

```

**Comment by Radrik5** [comment] 2017-02-21 09:28
Most probably this is a Git's issue because Git creates the rebase file. Maybe the issue is related to the commit message with too many "fixup!" prefixes: "fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! fixup! Create bash script."

Please try reproducing the issue with a plain git command and report it to the Git's issue tracker: https://github.com/git-for-windows/git/issues

**Comment by vbjay** [comment] 2017-02-21 12:31
Show your commits in gitextensions that you want rebased.

**Comment by webmaster33** [comment] 2017-02-21 12:44
How do you mean to show the commits?

**Comment by vbjay** [comment] 2017-02-21 12:53
Screenshot. You can paste the image as a comment here.

**Comment by webmaster33** [comment] 2017-02-21 13:04
I don't know how the screenshot does help the issue. I described the steps exactly, what I executed.

**Comment by vbjay** [comment] 2017-02-21 13:06
To see the commits you are trying to rebase. So we can make sure you are
picking the right commit to start rebasing from.

If I have commit a, b , c and d. Let's say d is a fix-up of b. I have to
rebase at least a or before a for the fix-up to apply.

**Comment by webmaster33** [comment] 2017-02-21 13:16
Ok, clear. 
Although I'm sure, that I go back enough commits behind the last fixup one, but I will post the screenshot to show it.

**Comment by webmaster33** [comment] 2017-02-21 14:07
Here are two screenshots:
![2017-02-21 14_42-git_extensions_rebase_fixup_problem](https://cloud.githubusercontent.com/assets/9215780/23167623/6ee64562-f845-11e6-87b7-04f397d4281d.png)
![2017-02-21 15_03_24-git_extensions_rebase_fixup_problem2](https://cloud.githubusercontent.com/assets/9215780/23168166/7960ebf8-f847-11e6-9a86-721d15336ef7.png)

**Comment by webmaster33** [comment] 2017-02-21 14:16
Also another one with strange errors, that the git-rebase-todo file is deleted too early, doesn't wait to edit it:
![2017-02-21 15_09_41-git_extensions_rebase_fixup_problem3](https://cloud.githubusercontent.com/assets/9215780/23168493/a66e579c-f848-11e6-83a0-a4e73043d977.png)

**Comment by webmaster33** [comment] 2017-02-21 14:31
Also a further one at 
"C:\winprg\git-sdk-64\usr\bin\git.exe" rebase  -i --no-autosquash "dc695e3a1e2080c69bbb1a31b435e268abdb7da0"
![2017-02-21 git_extensions_rebase_fixup_problem4](https://cloud.githubusercontent.com/assets/9215780/23168947/3f6352b2-f84a-11e6-88a5-ab616e4af794.png)

Dialog window:
"C:\winprg\git-sdk-64\usr\bin\git.exe" rebase  -i --no-autosquash "dc695e3a1e2080c69bbb1a31b435e268abdb7da0"
Successfully rebased and updated refs/heads/live_master.
Done
Press Enter or Esc to close console...

Result: later commits are lost (except the remote one):
![2017-02-21 git_extensions_rebase_fixup_problem5](https://cloud.githubusercontent.com/assets/9215780/23169103/c2a893d0-f84a-11e6-9299-cde0d1faa8cb.png)

**Comment by vbjay** [comment] 2017-02-21 17:14
Try it with autosquash.

**Comment by vbjay** [comment] 2017-02-21 17:18
Try installing actual git from git-scm.com and pointing gitextensions to it
instead of the SDK.

**Comment by webmaster33** [comment] 2017-02-22 10:48
Ok, Installed latest Git v2.11.1 from git-scm.com.

Now I see the rebase todo editor, but the fixup is lines are shown as pick, not fixup.
When started another rebase starting from older commit, I see noop again.
Something is not working correctly.

Screenshot attached:
![2017-02-22 git_extensions_rebase_fixup_problem6](https://cloud.githubusercontent.com/assets/9215780/23208295/be4157b4-f8f4-11e6-9e76-55fda496be36.png)

**Comment by webmaster33** [comment] 2017-02-22 13:00
Attaching the screenshot, when the rebase todo editor shows the commits correctly, but the fixup is lines are shown as pick instead fixup.
![2017-02-22 git_extensions_rebase_fixup_problem7](https://cloud.githubusercontent.com/assets/9215780/23212495/3fc193c8-f907-11e6-9223-6a413f5fc3e8.png)

**Comment by vbjay** [comment] 2017-02-22 13:49
Use autosquash.

On Wed, Feb 22, 2017, 8:00 AM webmaster33 <notifications@github.com> wrote:

Attaching the screenshot, when the rebase todo editor shows the commits
correctly, but the fixup is lines are shown as pick instead fixup.
[image: 2017-02-22 git_extensions_rebase_fixup_problem7]
<https://cloud.githubusercontent.com/assets/9215780/23212495/3fc193c8-f907-11e6-9223-6a413f5fc3e8.png>

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/3537#issuecomment-281662589>,
or mute the thread

**Comment by webmaster33** [comment] 2017-02-22 16:15
autosquash is not an option, I want to check & control the rebase process.

**Comment by vbjay** [comment] 2017-02-22 18:44
Look.  What do you think autosquash does?  It processes those commits and
alters the rebase file. Like I said, USE AUTOSQUASH!!!!!

On Wed, Feb 22, 2017, 11:16 AM webmaster33 <notifications@github.com> wrote:

autosquash is not an option, I want to check & control the rebase process.

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/3537#issuecomment-281717425>,
or mute the thread

**Comment by webmaster33** [comment] 2017-02-24 14:05
@vbjay: yes, you were right. 
autosquash option helped in getting the fixup changes into the rebase-todo file.

Altough I still get sometimes just a NOOP in the rebase-todo file.
Same case like in the following screenshot:
![I still get sometimes just a NOOP in the rebase-todo file.](https://cloud.githubusercontent.com/assets/9215780/23208295/be4157b4-f8f4-11e6-9e76-55fda496be36.png)

**Comment by vbjay** [comment] 2017-02-25 02:18
If the commits are direct ancestors you won't have any changes.
http://stackoverflow.com/questions/6485508/git-interactive-rebase-no-commits-to-pick

**Comment by webmaster33** [comment] 2017-02-27 16:31
I made a compare test:
**Test CASE 1): Started rebase from Git Extensions
RESULT: MISSING list of commits in git-rebase-todo file, just a NOOP line.** 
Executed git command:
`"C:\winprg\Git\bin\git.exe" rebase  -i --no-autosquash --preserve-merges "c255523f688e88e403e6ee79b0b7c8d26ae5fb5b"`
![2017-02-27 git_extensions_rebase_fixup_problem8](https://cloud.githubusercontent.com/assets/9215780/23369593/324e6036-fd12-11e6-8d31-635a79f44712.png)

**Test CASE 2): Started rebase from MINGW command line
RESULT: SUCCESSFUL list of commits.**
`"C:\winprg\Git\bin\git.exe" rebase  -i --no-autosquash --preserve-merges "c255523f688e88e403e6ee79b0b7c8d26ae5fb5b"`
![2017-02-27 git_extensions_rebase_fixup_problem9](https://cloud.githubusercontent.com/assets/9215780/23369602/39185f16-fd12-11e6-96e1-4e29411d1959.png)

Based on the tests above, I think it is a bug in Git Extensions v2.49.

**Comment by webmaster33** [comment] 2017-02-27 17:38
Tested the same rebase using Git Extensions v2.48.05, and the commits appears CORRECTLY into the git-rebase-todo file.
I'm convinced, that Git Extensions v2.49 has a bug with rebase, because rebase in Git Extensions v2.48.05 works fine.

**Comment by Radrik5** [comment] 2017-02-27 17:56
There is `--autosqash` option in your screenshot with Git Extensions.

**Comment by Radrik5** [comment] 2017-02-27 18:06
Could you provide the exact steps to reproduce the problem? Having that it will be much easier to find the bug and fix it.

**Comment by webmaster33** [comment] 2017-02-27 20:00
Try this test repo:
https://github.com/webmaster33/test-rebase.git

Use the following versions:
1) GitExtensions v2.48.5 (working)
2) GitExtensions v2.49 (bad rebase)

Do this rebase from the GitExtensions app:
`"C:\winprg\Git\bin\git.exe" rebase  -i --autosquash --preserve-merges "branch_foo"`
steps:
1) open GitExtensions v2.49
2) select line add bbb.txt
3) create a local branch named "branch_foo"
4) checkout master branch
5) select line add bbb.txt
6) try to rebase current branch (master) to "branch_foo"
7) Select Show options
8) Select Interactive rebase, Preserve Merges, Autosquash
9) Click Rebase button
10) Result is just NOOP

```
noop

# Rebase c43c41a..cfa3f90 onto c43c41a (1 command)
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```
Same works fine with GitExtensions v2.48.5.


**WORKAROUND:**
- In GitExtensions v2.49: Add remote tracking branch to remote repo, and rebase will work again.

**BUG DESCRIPTION:**
- In GitExtensions v2.49: if there is a local branch, and you try to rebase on it, then rebase will fail with NOOP in git-rebase-todo file. 
In GitExtensions v2.48.5 it will work fine.
- In GitExtensions v2.49: if there is a local branch and you also have a remote tracking branch, and you try to rebase on it, then rebase will be SUCCESSFUL, commits appear in git-rebase-todo file. 

I hope after this investigation, it is clearer now.

**Comment by Radrik5** [comment] 2017-02-27 20:12
For me it works:
![image](https://cloud.githubusercontent.com/assets/9339459/23377612/bf615d0a-fd41-11e6-9a01-61f6456a4b5f.png)

Git Extensions 2.49. Git 2.11.0.

**Comment by Radrik5** [comment] 2017-02-27 20:15
Are you sure Git Extensions 2.48.5 uses exact same Git ("C:\winprg\Git\bin\git.exe")?

Take a look at this question please: http://stackoverflow.com/a/7154025

**Comment by webmaster33** [comment] 2017-02-28 06:45
Git Extensions 2.48.5: C:\winprg\Git\bin\git.exe (Git 2.11.1.windows1)
Git Extensions 2.49: C:\winprg\Git\bin\git.exe (Git 2.11.1)

**Comment by webmaster33** [comment] 2017-02-28 08:00
http://stackoverflow.com/a/7154025
It is different issue as the solution was this:
"issue was caused by my .bashrc setting IFS:"

**Comment by vbjay** [comment] 2017-02-28 13:05
Great.  So close the issue.

**Comment by webmaster33** [comment] 2017-02-28 13:15
Why should I close the issue?
The issue is reproducible on my computer.
Doesn't work in Git Extensions 2.49, but works in Git Extensions 2.48.5.

It seems, it was not reproducible by @Radrik5, but it was reproducible on my computer.
There is definitely a bug, the question, what does it cause.

**Comment by vbjay** [comment] 2017-02-28 13:31
Looked like you said it was your bashrc file.

**Comment by webmaster33** [comment] 2017-02-28 13:52
@vbjay: you misunderstood.

I just replied to post of @radrik5, where he wrote:
<quote>Are you sure Git Extensions 2.48.5 uses exact same Git ("C:\winprg\Git\bin\git.exe")?

Take a look at this question please: http://stackoverflow.com/a/7154025</quote>

**Comment by vbjay** [comment] 2017-02-28 14:33
Ok.  Check the linux tools path in both gitextensions

**Comment by webmaster33** [comment] 2017-02-28 16:17
@vbjay:
Git Extensions 2.48.5: C:\winprg\Git\bin\
Git Extensions 2.49: C:\winprg\Git\bin\

**Comment by webmaster33** [comment] 2017-02-28 16:25
Here are the config files of both, but I don't see anything, which may cause the problem.
[GitExtensions.exe.config.v2.48.5.txt](https://github.com/gitextensions/gitextensions/files/807456/GitExtensions.exe.config.v2.48.5.txt)
[GitExtensions.exe.config.v2.49.txt](https://github.com/gitextensions/gitextensions/files/807458/GitExtensions.exe.config.v2.49.txt)

**Comment by webmaster33** [comment] 2017-02-28 17:23
Installed latest GIT 2.12.0, hoping that it might be a git problem.

Tested again the Git Extensions 2.48.5 & Git Extensions 2.49, but I got the same problem.
In 2.49 in get just NOOP in git-rebase-todo file. 
In 2.48.5 commits are visible correctly.

**Comment by Radrik5** [comment] 2017-02-28 20:11
Please take a look one more time: http://stackoverflow.com/a/7154025
There is good suggestion to use `set -x` to debug `git rebase`. You may compare output in Git Extensions 2.48.5 & Git Extensions 2.49 and try to find what's going wrong on your computer.
I'm pretty sure this an environment issue, not a bug in git or git extensions.

**Comment by vbjay** [comment] 2017-02-28 22:56
I agree.

**Comment by webmaster33** [comment] 2017-03-01 11:17
set -x to debug git rebase seemed to be a good idea.

I got the following log after using the set -x in c:\winprg\Git\mingw64\libexec\git-core\git-rebase--interactive:
```
"C:\winprg\Git\bin\git.exe" rebase  -i --autosquash --preserve-merges "branch_foo"
++ todo='W:/Dev/!GIT/test-rebase/.git/rebase-merge/git-rebase-todo'
++ done='W:/Dev/!GIT/test-rebase/.git/rebase-merge/done'
++ msg='W:/Dev/!GIT/test-rebase/.git/rebase-merge/message'
++ squash_msg='W:/Dev/!GIT/test-rebase/.git/rebase-merge/message-squash'
++ fixup_msg='W:/Dev/!GIT/test-rebase/.git/rebase-merge/message-fixup'
++ rewritten='W:/Dev/!GIT/test-rebase/.git/rebase-merge/rewritten'
++ dropped='W:/Dev/!GIT/test-rebase/.git/rebase-merge/dropped'
++ end='W:/Dev/!GIT/test-rebase/.git/rebase-merge/end'
++ msgnum='W:/Dev/!GIT/test-rebase/.git/rebase-merge/msgnum'
++ author_script='W:/Dev/!GIT/test-rebase/.git/rebase-merge/author-script'
++ amend='W:/Dev/!GIT/test-rebase/.git/rebase-merge/amend'
++ rewritten_list='W:/Dev/!GIT/test-rebase/.git/rebase-merge/rewritten-list'
++ rewritten_pending='W:/Dev/!GIT/test-rebase/.git/rebase-merge/rewritten-pending'
++ cr=$'\r'
++ strategy_args=
++ test -n ''
++ GIT_CHERRY_PICK_HELP='
When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
'
++ export GIT_CHERRY_PICK_HELP
++ comment_char=
++ case "$comment_char" in
++ comment_char='#'
++ orig_reflog_action=rebase
++ last_count=
++ git_rebase__interactive
++ case "$action" in
++ comment_for_reflog start
++ case "$orig_reflog_action" in
++ GIT_REFLOG_ACTION='rebase -i (start)'
++ export GIT_REFLOG_ACTION
++ test '!' -z ''
++ orig_head=817ab5b37494e86208429806e72fc83a7d6779d8
++ mkdir -p 'W:/Dev/!GIT/test-rebase/.git/rebase-merge'
++ :
++ write_basic_state
++ echo refs/heads/master
++ echo c43c41a8e0152fac6a46eaf4fc5b1cf5f8d83225
++ echo 817ab5b37494e86208429806e72fc83a7d6779d8
++ echo ''
++ test t = ''
++ test -n ''
++ test -n ''
++ test -n ''
++ test -n ''
++ test t = t
++ test -z ''
++ mkdir 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/rewritten'
+++ git merge-base --all 817ab5b37494e86208429806e72fc83a7d6779d8 c43c41a8e0152fac6a46eaf4fc5b1cf5f8d83225
                                          ++ for c in $(git merge-base --all $orig_head $upstream)
++ echo c43c41a8e0152fac6a46eaf4fc5b1cf5f8d83225
++ merges_option=
++ shorthead=817ab5b
++ shortonto=c43c41a
++ test -z ''
++ shortupstream=c43c41a
++ revisions=c43c41a8e0152fac6a46eaf4fc5b1cf5f8d83225...817ab5b37494e86208429806e72fc83a7d6779d8
++ shortrevisions=c43c41a..817ab5b
++ test t '!=' t
++ format=
++ git rev-list '--format=%m%H %s' --reverse --left-right --topo-order c43c41a8e0152fac6a46eaf4fc5b1cf5f8d83225...817ab5b37494e86208429806e72fc83a7d6779d8
                          ++ sed -n 's/^>//p'
                                             +++ git rev-parse -q --verify 'ed83219f6cc3a3de0afd8908011fe7508464efb9^^{tree}'
                                                             +++ git rev-list --parents -1 ed83219f6cc3a3de0afd8908011fe7508464efb9
   +++ git rev-list --parents -1 cfa3f90901a549b909a25aae56959216012fc968
         +++ git rev-parse -q --verify '817ab5b37494e86208429806e72fc83a7d6779d8^{tree}'
+++ git rev-list --parents -1 817ab5b37494e86208429806e72fc83a7d6779d8
      +++ cut '-d ' -s -f2-
++ test t = t
++ mkdir 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/dropped'
++ git rev-list c43c41a8e0152fac6a46eaf4fc5b1cf5f8d83225...817ab5b37494e86208429806e72fc83a7d6779d8
                                   ++ git rev-list --parents -1 817ab5b37494e86208429806e72fc83a7d6779d8
                                        ++ cut '-d ' -s -f2
++ test -s 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/git-rebase-todo'
++ echo noop
++ test -z t
++ git rebase--helper --rearrange-squash
++ test -n ''
+++ git stripspace --strip-comments
                                   ++ todocount=1
++ todocount=1
++ cat
++++ git sh-i18n--envsubst --variables 'Rebase $shortrevisions onto $shortonto ($todocount commands)'
                                     ++ append_todo_help
+++ printf %s ignore
++ test ignore = error
++ gettext '
            If you remove a line here THAT COMMIT WILL BE LOST.
                                                               '

++ printf %s '
              If you remove a line here THAT COMMIT WILL BE LOST.
 '
  ++ test -z ''
++ printf '%s\n' '# Note that empty commits are commented out'
++ has_action 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/git-rebase-todo'
++ test -n noop
++ cp 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/git-rebase-todo' 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/git-rebase-todo.backup'
++ collapse_todo_ids
++ git rebase--helper --shorten-sha1s
++ git_sequence_editor 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/git-rebase-todo'
++ test -z ''
++ GIT_SEQUENCE_EDITOR=
++ '[' -z '' ']'
+++ git var GIT_EDITOR
                      ++ GIT_SEQUENCE_EDITOR='"C:/winprg/GitExtensions v2.48.5 working/GitExtensions.exe" fileeditor'
++ eval '"C:/winprg/GitExtensions v2.48.5 working/GitExtensions.exe" fileeditor' '"$@"'
+++ 'C:/winprg/GitExtensions v2.48.5 working/GitExtensions.exe' fileeditor 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/git-rebase-todo'
```

The only strange thing I see is the "C:/winprg/GitExtensions v2.48.5 working/GitExtensions.exe" lines, where the old GitExtensions v2.48.5 is called from GitExtensions v2.49.

**Comment by webmaster33** [comment] 2017-03-01 11:29
I changed the Git Extensions path to be the same version.
However I got just NOOP again.
Do you see anything else, what can cause the problem?
```
"C:\winprg\Git\bin\git.exe" rebase  -i --autosquash --preserve-merges "branch_foo"
++ todo='W:/Dev/!GIT/test-rebase/.git/rebase-merge/git-rebase-todo'
++ done='W:/Dev/!GIT/test-rebase/.git/rebase-merge/done'
++ msg='W:/Dev/!GIT/test-rebase/.git/rebase-merge/message'
++ squash_msg='W:/Dev/!GIT/test-rebase/.git/rebase-merge/message-squash'
++ fixup_msg='W:/Dev/!GIT/test-rebase/.git/rebase-merge/message-fixup'
++ rewritten='W:/Dev/!GIT/test-rebase/.git/rebase-merge/rewritten'
++ dropped='W:/Dev/!GIT/test-rebase/.git/rebase-merge/dropped'
++ end='W:/Dev/!GIT/test-rebase/.git/rebase-merge/end'
++ msgnum='W:/Dev/!GIT/test-rebase/.git/rebase-merge/msgnum'
++ author_script='W:/Dev/!GIT/test-rebase/.git/rebase-merge/author-script'
++ amend='W:/Dev/!GIT/test-rebase/.git/rebase-merge/amend'
++ rewritten_list='W:/Dev/!GIT/test-rebase/.git/rebase-merge/rewritten-list'
++ rewritten_pending='W:/Dev/!GIT/test-rebase/.git/rebase-merge/rewritten-pending'
+++ printf '\015'
                 ++ cr=$'\r'
++ strategy_args=
++ test -n ''
++ GIT_CHERRY_PICK_HELP='
When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
'
++ export GIT_CHERRY_PICK_HELP
++ comment_char=
++ case "$comment_char" in
++ comment_char='#'
++ orig_reflog_action=rebase
++ last_count=
++ git_rebase__interactive
++ case "$action" in
++ comment_for_reflog start
++ case "$orig_reflog_action" in
++ GIT_REFLOG_ACTION='rebase -i (start)'
++ export GIT_REFLOG_ACTION
++ test '!' -z ''
++ orig_head=817ab5b37494e86208429806e72fc83a7d6779d8
++ mkdir -p 'W:/Dev/!GIT/test-rebase/.git/rebase-merge'
++ :
++ write_basic_state
++ echo refs/heads/master
++ echo c43c41a8e0152fac6a46eaf4fc5b1cf5f8d83225
++ echo 817ab5b37494e86208429806e72fc83a7d6779d8
++ echo ''
++ test t = ''
++ test -n ''
++ test -n ''
++ test -n ''
++ test -n ''
++ test t = t
++ test -z ''
++ mkdir 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/rewritten'
+++ git merge-base --all 817ab5b37494e86208429806e72fc83a7d6779d8 c43c41a8e0152fac6a46eaf4fc5b1cf5f8d83225
++ for c in $(git merge-base --all $orig_head $upstream)
++ echo c43c41a8e0152fac6a46eaf4fc5b1cf5f8d83225
++ merges_option=
+++ git rev-parse --short 817ab5b37494e86208429806e72fc83a7d6779d8
++ shorthead=817ab5b
++ shortonto=c43c41a
++ test -z ''
++ shortupstream=c43c41a
++ revisions=c43c41a8e0152fac6a46eaf4fc5b1cf5f8d83225...817ab5b37494e86208429806e72fc83a7d6779d8
++ shortrevisions=c43c41a..817ab5b
++ test t '!=' t
++ format=
++ git rev-list '--format=%m%H %s' --reverse --left-right --topo-order c43c41a8e0152fac6a46eaf4fc5b1cf5f8d83225...817ab5b37494e86208429806e72fc83a7d6779d8
                          +++ git rev-parse -q --verify 'ed83219f6cc3a3de0afd8908011fe7508464efb9^^{tree}'
++ test t = t
++ mkdir 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/dropped'
++ read rev
           ++ test -f 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/rewritten/817ab5b37494e86208429806e72fc83a7d6779d8'
                                                    ++ sane_grep 817ab5b37494e86208429806e72fc83a7d6779d8 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/not-cherry-picks'
                                      ++ GREP_OPTIONS=
                                                      ++ LC_ALL=C
 ++ grep 817ab5b37494e86208429806e72fc83a7d6779d8 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/not-cherry-picks'
                                              ++ read rev
                                                         ++ test -f 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/rewritten/cfa3f90901a549b909a25aae56959216012fc968'
                                  ++ sane_grep cfa3f90901a549b909a25aae56959216012fc968 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/not-cherry-picks'
                    ++ GREP_OPTIONS=
                                    ++ LC_ALL=C
                                               ++ grep cfa3f90901a549b909a25aae56959216012fc968 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/not-cherry-picks'
                            ++ read rev
                                       ++ test -f 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/rewritten/ed83219f6cc3a3de0afd8908011fe7508464efb9'
                ++ sane_grep ed83219f6cc3a3de0afd8908011fe7508464efb9 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/not-cherry-picks'
  ++ GREP_OPTIONS=
                  ++ LC_ALL=C
                             ++ grep ed83219f6cc3a3de0afd8908011fe7508464efb9 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/not-cherry-picks'
          ++ read rev
                     ++ test -s 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/git-rebase-todo'
++ echo noop
++ test -z t
++ git rebase--helper --rearrange-squash
++ test -n ''
++ todocount=1
++ todocount=1
++ cat
+++ eval_ngettext 'Rebase $shortrevisions onto $shortonto ($todocount command)' 'Rebase $shortrevisions onto $shortonto ($todocount commands)' 1
++++ git sh-i18n--envsubst --variables 'Rebase $shortrevisions onto $shortonto ($todocount commands)'
                                     ++ append_todo_help
++ test ignore = error
++ gettext '
            However, if you remove everything, the rebase will be aborted.

          '
           ++ printf %s '
                         However, if you remove everything, the rebase will be aborted.

                       '
                        ++ test -z ''
++ printf '%s\n' '# Note that empty commits are commented out'
++ has_action 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/git-rebase-todo'
+++ git stripspace --strip-comments
                                   ++ test -n noop
++ cp 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/git-rebase-todo' 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/git-rebase-todo.backup'
++ collapse_todo_ids
++ git rebase--helper --shorten-sha1s
++ git_sequence_editor 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/git-rebase-todo'
++ test -z ''
++ GIT_SEQUENCE_EDITOR=
++ '[' -z '' ']'
++ GIT_SEQUENCE_EDITOR='"C:/winprg/GitExtensions v2.49 bad rebase/GitExtensions.exe" fileeditor'
++ eval '"C:/winprg/GitExtensions v2.49 bad rebase/GitExtensions.exe" fileeditor' '"$@"'
+++ 'C:/winprg/GitExtensions v2.49 bad rebase/GitExtensions.exe' fileeditor 'W:/Dev/!GIT/test-rebase/.git/rebase-merge/git-rebase-todo'
```

**Comment by webmaster33** [comment] 2017-03-01 11:39
Also done the same debug log with GitExtensions v2.48.5.
Attaching the two files to be able to compare them using a visual comparison tool.
[GitExtensions v2.48.5 working.debug_log.txt](https://github.com/gitextensions/gitextensions/files/810564/GitExtensions.v2.48.5.working.debug_log.txt)
[GitExtensions v2.49 bad rebase.debug_log.txt](https://github.com/gitextensions/gitextensions/files/810565/GitExtensions.v2.49.bad.rebase.debug_log.txt)

**Comment by Radrik5** [comment] 2017-03-01 13:53
1. Don't use `--reserve-merges` along with `-i`. It's not supposed to work.
2. Disable "Use Console Emulator" in Git Extensions Settings / Advanced. Probably it ate some of `set -x` output.
3. Run `git rebase  -i --autosquash "branch_foo"` from Git Bash launched from Git Extensions.

**Comment by webmaster33** [comment] 2017-03-02 12:53
Interesting result:
I tried the following: turned off the "Use Console Emulator" in Git Extensions Settings / Advanced.
Tested only in GitExtensions v2.49.

I used in all cases the
`C:\winprg\Git\bin\git.exe rebase  -i --autosquash --preserve-merges "branch_foo"`

Case 1) "Use Console Emulator" is turned ON in GitExtensions v2.49
Result: mostly I get NOOP as result. Sometimes still showed the correct result with all commits, but mostly just NOOP.

Case 2) "Use Console Emulator" is turned OFF in GitExtensions v2.49
Result: SUCCESS. In all cases commits are displayed correctly.

Strange, isn't it?

Attaching log file of both cases to be able to compare.
[GitExtensions v2.49 bad rebase.debug_log6_works-console_emulator_OFF.txt](https://github.com/gitextensions/gitextensions/files/813811/GitExtensions.v2.49.bad.rebase.debug_log6_works-console_emulator_OFF.txt)
[GitExtensions v2.49 bad rebase.debug_log7_NOOP-console_emulator_on.txt](https://github.com/gitextensions/gitextensions/files/813812/GitExtensions.v2.49.bad.rebase.debug_log7_NOOP-console_emulator_on.txt)

**Comment by Radrik5** [comment] 2017-03-02 18:16
I just tried running `C:\winprg\Git\bin\git.exe rebase -i --autosquash --preserve-merges "branch_foo"` 10 times and all the 10 times I got correct TODO list without NOOP. Git Extensions 2.49, Console Emulator is enabled.
It still seems to be an environment issue but now we know it relates to Console Emulator somehow.

**Comment by jbialobr** [comment] 2017-05-17 10:43
@webmaster33 I can not reproduce the issue. Can you modify the git-rebase--interactive script to include more diagnostic printings. For example you could add lines like:
```
echo gitext-debug
cat "$todo"
```
after every change made to the "$todo" file. It could help to detect the lines that cause the differences.

**Comment by RussKie** [comment] 2018-02-03 09:21
Is it still an issue with 2.51?

**Comment by vbjay** [comment] 2018-02-03 14:12
I doubt it's ge. I'll bet his git setup was corrupt.

**Comment by webmaster33** [comment] 2018-02-04 09:41
All I know, that when I disabled Console Emulator the problem was solved.

I will test at my workplace the latest release, if rebase works fine when Console Emulator is enabled.

**Comment by RussKie** [comment] 2018-02-13 13:03
we have updated the ConEmu to the latest version
please try this build and see if it works for you
https://ci.appveyor.com/api/buildjobs/tb8kjpyr04sf8l4o/artifacts/GitExtensions-Portable-3.00.00.1599.zip

**Comment by RussKie** [comment] 2018-03-10 12:06
Closing due to lack of follow up.

**Closed by RussKie** 2018-03-10 12:06 UTC
Labels: bug, info needed
