### ISSUE TITLE
RevisionGrid not refreshed after resolving merge conflicts

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#9792] opened 2022-01-03 20:23 UTC
### Environment

- GitExtensions version: master 07d87634f5392dc9263f47e0cbd616334362c14d plus a few patches
- Git 2.34.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 5.0.13
- DPI 96dpi (no scaling)

### Issue description

The RevisionGrid not refreshed after resolving merge conflicts, occasionally.
The workaround is not hard (refresh the grid), but this looks bad.

![image](https://user-images.githubusercontent.com/6248932/147977372-3673fba4-7ecb-40d7-a345-ad278c77fe6b.png)

### Steps to reproduce

This is hard to reproduce, I get it relative often at work (where I cannot debug) with complex merges but then I just have to dismiss and "remember for later" (so it is fuzzy when this really started).
I have a problem reproducing at home. One in 10 times "succeeded".

Something like the following reproduced the problem. Since this is likely a timing issue all steps are likely not needed, but this was the scenario when reproducing.

* Rebase interactive of a branch with two commits on one new commit, all of the commits have done conflicting changes to the same file.
* order changed for the commits to rebase.
* Dismiss FormRebase when applying first commit fails
* Start FormResolveConflict from toolbar ![image](https://user-images.githubusercontent.com/6248932/147976368-60bad5b8-5374-49f6-a49d-cbfb9b400d59.png)
* Resolve with mergetool
* Continue in toolbar
* Start FormResolveConflict from toolbar
* Resolve with mergetool
* Continue in toolbar

grid is not refreshed as seen above.

### Did this work in previous version of GitExtensions?

This started sometime around or after .NET5 I believe, maybe some time after.
It could even be triggered by #8809.

**Comment by RussKie** [comment] 2022-01-04 03:50
Thank you for raising it, I observed this as well but never got around raising an issue or investigating.

**Comment by mstv** [comment] 2022-01-18 21:35
Duplicate of #9223?

**Closed** 2022-02-21 22:20 UTC
Labels: :eyeglasses: status: needs review, :construction: status: in progress
