### ISSUE TITLE
File Tree is empty

### ISSUE THREAD

**Issue by markpizz** [gitextensions/gitextensions#4004] opened 2017-09-17 13:53 UTC
**What is the issue kind?**
- bug report

**What is the current behavior?**
2.50.01 behaves as expected.
2.50.02 has an empty file tree

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Well, my primary desktop demonstrates this problem while my laptop does not.
I can uninstall 2.50.02 and install 2.50.01 and I get normal behavior from 2.50.01.  Installing 2.50.02 gets me back to the problem case.  Rebooting between these various installs/uninstalls does not seem to affect the results.

**What is the expected behavior?**
To see the file tree.

**Environment you encounter the issue:**
Windows 10 - 1703.

- GitExtensions version: 2.50.02
- GIT version: 2.13.2
- OS version: Microsoft Windows [Version 10.0.15063]

**Did this work in previous version of GitExtensions (which)?**
Yes.  2.50.01
![good-from-2 50 01](https://user-images.githubusercontent.com/422671/30521471-def1b828-9b74-11e7-8fd3-ade539b78d5d.png)
![bad-from-2 50 02](https://user-images.githubusercontent.com/422671/30521472-def255d0-9b74-11e7-88df-dce6580ebc84.png)

**Comment by vbjay** [comment] 2017-09-17 13:56
Duplicate of several issues. Search issues before posting yours.

**Comment by vbjay** [comment] 2017-09-17 14:00
You just need to resize the splitter.

**Comment by jbialobr** [comment] 2017-09-17 18:41
Duplicate of #3875

**Closed** 2017-09-17 18:41 UTC
