### ISSUE TITLE
Cannot install without administrator privilege

### ISSUE THREAD

**Issue by KenHung** [gitextensions/gitextensions#3328] opened 2016-09-20 07:01 UTC
I cannot install 2.48.05 to a Windows XP PC without administrator privilege.
Although the installer said that "Git Extension 2.48.05 will be installed in a per-user folder and be available just for your user account. You do not need local Administrator privileges." in the Installation Scope page, the following message was shown in the last step of installation:
![image](https://cloud.githubusercontent.com/assets/7405705/18660329/60d9c74a-7f42-11e6-80cc-49ecd017d240.png)

**Comment by KindDragon** [comment] 2016-09-20 11:10
Duplicate of #2434

**Closed by KindDragon** 2016-09-20 11:10 UTC
