### ISSUE TITLE
Main spelling dictionary choice is not used in the commit dialog

### ISSUE THREAD

**Issue by pmme** [gitextensions/gitextensions#4648] opened 2018-03-17 04:16 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In the commit message text box, the spelling dictionary remains set to "en-US" even when the dictionary is set to another choice in the main settings on the appearance tab.

This was noticed originally by @gerhardol in this comment: https://github.com/gitextensions/gitextensions/pull/4630#issuecomment-373184016

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Open Settings > Appearance.
2. Change "Dictionary for spelling checker" to anything other than "en-US".
3. Open the commit dialog.
4. Open the context menu in the commit message edit box and choose "Dictionary".
5. Observe the current dictionary choice remains on "en-US".

**What is the expected behavior?**
The dictionary choice in the commit dialog should default to the same as the main settings.

**Environment you encounter the issue:**
- GitExtensions version: master at 7e3516b241, or 2.51
- GIT version: 2.16.2.windows.1
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
I do not know.
From the code history it appears that it would have worked in 2.48 because 2.48 did not have the commit that I will mention below.

**What I have discovered so far...**
The dictionary is intended to be optionally a repo-specific setting from this commit: 35a7ecddf8, made by @jbialobr in 2014. There appear to be a series of improvements at this time for settings. Since this commit:
- RepoDistSettings::Dictionary will supply a saved value, if there is one, or the fixed default of "en-US".
- EditNetSpell.Settings will be Module.EffectiveSettings because IsUICommandsInitialized==true.
- Module.EffectiveSettings has no dictionary setting (for my repos), so it returns the default value from RepoDistSettings::Dictionary, which is "en-US".

There is no facility in this for Module.EffectiveSettings to adopt the default dictionary value from AppSettings.SettingsContainer. 
I do not understand enough about the settings caching to understand how effective settings are meant to defer to AppSettings when there is no specific setting for the current repo.

If someone can point me in the right direction from where I'm at, I'm happy to make changes, do testing, and create a PR to fix.

**Comment by GintasS** [comment] 2021-08-25 14:43
While reproducing it, the issue seems to be fixed. Closing this.

**Closed by GintasS** 2021-08-25 14:43 UTC
