### ISSUE TITLE
GitExtensions is exteremly slow on version 5

### ISSUE THREAD

**Issue by adam-bielasty-yb** [gitextensions/gitextensions#11985] opened 2024-10-15 13:58 UTC
### Environment

- GitExtensions version: 5.0.0.17897
- GIT version: Git 2.42.0.windows.2
- OS version: Microsoft Windows NT 10.0.22621.0
- .NET version: 8.0.10

# More details:
- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 8.0.10
- DPI 120dpi (125% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

### Issue description

I installed new version of GitExtensions, version 5 and it is exteremly slow in comparison to the previous versions (before 5).
It looks like everything loads slow. 

Before:
Comparing any commit to another commit was like <1s
Now:
If I select one commit with another commit it loads > 10s

Something is completely wrong with this version. It's not only compering commits but the general slowness.
Everything is ok with my machine (the same setup as it was for previous versions).

I have some guess that maybe manhatan view rendering is slow?
Please help as version 5 become very unsable. I am using GitExtensions for more than 10 years and know the dynamics in the app. There is something wrong with version 5.

### Steps to reproduce

Example:

Before:
Comparing any commit to another commit was like <1s
Now:
If I select one commit with another commit it loads > 10s

and in general, slowness.

### Did this work in previous version of GitExtensions?

Yes, everything was perfect up to version 5. It causes slowness.

**Comment by gerhardol** [comment] 2024-10-15 14:52
Please provide a repo where you see this as well as the PC specification.
There are performance improvements, for me 5.0 is faster than 4.2

**Comment by agatheSei** [comment] 2024-10-17 14:50
I agree. I just changed from the version 3.5 to 5(took me a long time to accept the update...). It is way way worse. I am thinking about changing back to 3.5.
It takes a long time to switch from a branch to another or switching between commits. Once over twice when trying to open a subfolder, it is closing the parent folder. And when it decides to open, it is taking a really long time

**Comment by adam-bielasty-yb** [comment] 2024-10-18 09:18
@gerhardol, I am using some private repo.

It's the same repo (with submodules) I am using for months and all worked fine and fast on previous GitExtensions versions.

Version 5 makes everything very slow.

I checked the machine utilization and all good. The problem is with GitExtensions v5.

E.g. clicking defferent commits with CTRL and then the differences are loading way way slower.

I don't know what else I can provide to you. I feel the dynamics of the app very well as I have been using that for 10+ years

**Comment by gerhardol** [comment] 2024-10-18 11:11
Check your virus programs, test with it deactivated. Note that GE 5.0 is installed in another path.
It could also be related to .NET (also more likely virus related than .NET8 itself).

**Comment by mstv** [comment] 2024-10-18 17:40
Just guessing:

Was takes longer ?
a) filling the file list
b) showing the diff of the selected file

Case b) might be improved by #11981. You could try the dev build: https://ci.appveyor.com/api/buildjobs/hqotrasvc6o6b1m4/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-5.1.0.17939-f9cf6069d.zip

The code for a) has not really changed since 4.x - but the .NET platform and the GE `TargetPlatform` has explicitly been set to `x64`.
Information about the processor architecture, the number of real/virtual cores and the RAM usage of GE on your machines might help to track down the cause of the slowness.

(I expect that the execution times of git calls themselves have not changed. It can be verified in the Git Command Log ['F12']).

What do you mean with "manhatan view", the "graph"? For comparison, you can deactivate the column in the `View` menu.
"everything slow" would mean .NET 8 and / or x64 has perf issues on your machine - if you really meant "everything".

**Comment by adam-bielasty-yb** [comment] 2024-10-23 14:49
@gerhardol, hmm, yeah, it might be related to .NET8 itself but the app works much slower in comparison to previous versions.

@mstv, filling the list takes more time (it's slower) than displaying diffs, so a)

Hmm, I am wondering if changing the architecture to x64 could make the app slower. I can uninstall and install x86 if you have any build like that and send you some feedback.

It's really annoying as the app is quite slow now. I even tried to downgrade to v4.X but it's also not easy to downgrade as the installation file does not allow to downgrade (and I don't want to remove things manually, so I stayded with v5).

Hmm, so if the code for a) didn't change I assume the issue is related to x64 which makes things slower? Maybe there are some missing optimisations flags in the build. Maybe it's builed for Debug not for Release? I doubt it's .NET8 fault. Maybe just some missing build flags?

Yes, git times are just normal <900ms which is just fine.

Yes, I mean "graph" by "manhatan view", I don't see the option in "View" menu to disable the graph.

According to b) it takes also more time to load the diff.

Hmm, I would bet on:
1) Some missing flags during the build which will help optimise things, Release/Debug etc.
2) x64 as another problem, I can check x64/x86 and compare if you have some build versions?

**Comment by mstv** [comment] 2024-10-23 19:48
As gerhardol and me repeatedly requested, tells us the specs of your machine, please.

portable build: https://github.com/gitextensions/gitextensions/releases/download/v4.2.1/GitExtensions-Portable-4.2.1.17611-b0c0b2848.zip (4.x is based on .NET 6)

How do v5.0 and v4.2.1 behave on a clone of the GE repo? https://github.com/gitextensions/gitextensions.git

**Comment by pmiossec** [comment] 2024-10-23 23:28
I would like to add that building GitExtensions is not that difficult if you have visual studio already installed and that, if the performance regression is flagrant, bisecting to find the commit introducing it would be of **HUGE** help!

Please think about doing it if you want to see it fixed as quick as possible....

**Comment by adam-bielasty-yb** [comment] 2024-10-24 09:05
Ohh, wow, I just disabled my **antivirus (Malwarebytes)** and it started working propery!

Thanks for that advice @gerhardol 

But how it is possible that the previous GitExtensions versions were working find with that anti-virus enabled?

It looks like the **antivirus was slowing down the GitExtensions v5** but not the previous versions. I don't know how that's possible.

Thanks guys for your help.

**Comment by gerhardol** [comment] 2024-10-24 11:26
> But how it is possible that the previous GitExtensions versions were working find with that anti-virus enabled?

If they have hardcoded whitelisted paths, that need to be updated.
Report it to them.

But the internals of virus programs (they are not anti virus, they often cause more problems than they save, they are not vaccines), are unknown. I had a virus program cause my builds to fail as they locked files while linking for instance.

**Comment by RussKie** [comment] 2024-10-25 04:41
I'm not denying the issue you're having (it's frustrating, I can understand), however given the current release has more than 100K installations (probably more), it's hard to assign the blame to git or Git Extensions implementations or blame .NET runtime (which is installed on (tens/hunderds?) millions of devices). It is very likely the issue is caused by something in your local environment - be that a corporate policy or an AV rule.
I personally had v5 installed on half a dozen of devices and I can't say I observed any degradation of performance.

> It looks like the **antivirus was slowing down the GitExtensions v5** but not the previous versions. I don't know how that's possible.

The app is now fully x64 process, so perhaps there were exclusions for Program Files (x86) paths, which no longer relevant with GE v5.

**Comment by RussKie** [comment] 2024-11-07 12:14
Closing as not enough evidence is provided to implicate the app.
Feel free to reopen, if more information emerges.

**Closed by RussKie** 2024-11-07 12:14 UTC
Labels: :eyeglasses: status: needs review, :mailbox_with_no_mail: needs: author feedback
