### ISSUE TITLE
[NBug] An unexpected internal error occurred in the Win32 call: 80...

### ISSUE THREAD

**Issue by yarharel** [gitextensions/gitextensions#9547] opened 2021-08-31 08:00 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ComponentModel.Win32Exception: An unexpected internal error occurred in the Win32 call: 80004005 ---> System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.

   --- End of inner exception stack trace ---
   at Microsoft.WindowsAPICodePack.Dialogs.NativeTaskDialog.NativeShow()
   at Microsoft.WindowsAPICodePack.Dialogs.TaskDialog.ShowCore()
   at GitUI.NBugReports.BugReportInvoker.Report(Exception exception, Boolean isTerminating)
   at GitExtensions.Program.<>c.<Main>b__1_3(Object s, ThreadExceptionEventArgs e)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()

```

## Additional information
dfg

## Environment
- Git Extensions 3.5.3.12551
- Build 00604a59a673142a3d34a22aa657466a922977f3
- Git 2.32.0.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4400.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2021-08-31 08:38
Duplicate of #9429
Seem to be related to theming, GDI objects are leaking.

**Closed by gerhardol** 2021-08-31 08:38 UTC
Labels: potential-duplicate
