### ISSUE TITLE
Can not click to file in diff tab window 11.

### ISSUE THREAD

**Issue by khoasting** [gitextensions/gitextensions#9325] opened 2021-07-02 14:44 UTC
## Current behaviour

When stay on commit point, then open diff tab and click on files change and no thing happen.
cannot pick those files change for see change in file.

## Expected behaviour

can pick any file in list files of diff tab to view change of those files

## Steps to reproduce

Pick a commit point.
Open diff tab.
Pick a file in list files change (usually happen with files in middle).
the file cannot pick.

## Screenshots

![image](https://user-images.githubusercontent.com/17832745/124345401-c3ebfc00-dc02-11eb-8181-0042a9c7d830.png)
files in red rectangle cannot pick.

## Did this work in previous version of GitExtensions

No, i have never seen it happen.

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.30.0.windows.2
- Microsoft Windows NT 10.0.22000.0
- .NET Framework 4.8.4161.0
- DPI 96dpi (no scaling)

**Comment by khoasting** [comment] 2021-07-03 06:35
@mstv i updated my comment using issues template.

**Comment by mstv** [comment] 2021-07-03 07:12
Could you compare the git command executed for a file whose diff can be displayed with an unsuccessful one?
The builtin Git Command Log can be opened using the hotkey `F12`.
You could run the commands on the command line, too.

**Comment by RussKie** [comment] 2021-07-03 10:43
I'm on W11 and I have no troubles selecting files. 
![Animation](https://user-images.githubusercontent.com/4403806/124351721-61652100-dc3f-11eb-83ec-246a72b4e2e0.gif)


Please provide steps to reproduce.

**Comment by vbjay** [comment] 2021-07-03 14:46
Those filenames seem long in the op. Maybe max path issue?

**Comment by khoasting** [comment] 2021-07-04 15:08
Thanks for the answer, I upload the gif file please take a look.
![cannotSelect3](https://user-images.githubusercontent.com/17832745/124390112-57612200-dd14-11eb-9786-0a1d441a27c5.gif)

**Comment by mstv** [comment] 2021-07-04 20:10
@khoasting, could you try 3.5.1, please. There have been changes in the `FileStatusList` and in the `FileViewer`.

The result of successful git commands are cached for the runtime of GE. So it would be of interest whether a git command is executed on the first click on these files, @khoasting,

@gerhardol, do you have a clue in which other situation neither a git command would be run nor an exception be displayed?

**Comment by gerhardol** [comment] 2021-07-04 20:29
> @gerhardol, do you have a clue in which other situation neither a git command would be run nor an exception be displayed?

No

The handling in 3.5 (but not master) is synchronous, so if there were still processing going on when selecting next file, the handling would be blocked.
If there is an error returned for the Git command, it should be displayed.

(I do not plan to update to Windows 11 in the next years or so myself.)

**Comment by mstv** [comment] 2021-07-04 20:44
This raises the question whether it works on Win 10.
I guess you cannot share your repo, @khoasting. Could you try it on Win10?

**Comment by khoasting** [comment] 2021-07-05 02:47
@mstv yes I check it on Win 10 and I can pick any file with no problem. And I tried 3.5.1 version too but cannot fix the issue.

**Comment by RussKie** [comment] 2021-07-05 02:56
Are you able to share a repro?

**Comment by khoasting** [comment] 2021-07-05 15:08
My computer just had a problem and I do clean it up. Now GitExtension work as normal in Win 11. I cannot reproduce the bug so I will close this issue. Thanks for care for me. Good luck, Your work is great.

**Comment by RussKie** [comment] 2021-07-10 11:55
Observed the same tonight, looks like ListView is lagging and failing to recalculate items rectangles... I'm not sure whether it is us or Windows...
![listview-cant-click](https://user-images.githubusercontent.com/4403806/125162103-7a367f00-e1c9-11eb-8f2c-6f47b66aa68b.gif)

**Comment by RussKie** [comment] 2021-07-10 12:06
It's probably something to do with your implementations...

**Comment by RussKie** [comment] 2021-07-11 06:03
I've spent some more time investigating this, and now I'm starting to think it is a Windows regression related to the use of tooltips. I currently don't have W10 machine to verify it only affects W11.

This is the code that is somehow causing the issue, if it is commented out - everything works as expected (modulo the tooltips):
https://github.com/gitextensions/gitextensions/blob/196c924b5344c9c0fb4640d36d0ea2899325e83d/GitUI/UserControls/FileStatusList.cs#L1495-L1541

In the screenshot above we're setting the tooltip to `""` because the items are shown in full.

Here's another example. If there a tooltip is shown it is not possible to click on 5 following items, like there's an input shield that prevents clicks...
![listview-cant-click2](https://user-images.githubusercontent.com/4403806/125184235-6e959780-e25f-11eb-971d-ebed18d0a9cd.gif)

Here's a vanilla sample (https://github.com/RussKie/Win11ListViewIssue):
```cs
this.listView1.HotTracking = true;
this.listView1.HoverSelection = true;
this.listView1.ShowItemToolTips = true;
```

![listview-cant-click-vanilla](https://user-images.githubusercontent.com/4403806/125184362-596d3880-e260-11eb-80b5-972a1cc66be4.gif)

**Comment by merriemcgaw** [comment] 2021-07-14 00:01
It could conceivably be an issue with the ListView as well. They may have made some changes to it, though I _know_ they did make changes to the ToolTips. Can you file an issue for the Vanilla problem in the WinForms repo and we can get some help from Olina to validate it doesn't happen unless Win11. Also check Win11 Feedback, something might be there.

**Comment by RussKie** [comment] 2021-07-26 09:14
The Windows team responded that this issue may have been fixed in one of the recent builds.

**Comment by tebeco** [comment] 2021-07-28 10:47
Having the exact same behavior with:
![image](https://user-images.githubusercontent.com/2266487/127309158-38ccef47-f353-4d62-bc78-a9e98ad8a058.png)
![image](https://user-images.githubusercontent.com/2266487/127309180-27180fdd-520c-480c-8c6d-2b98434d3849.png)
![image](https://user-images.githubusercontent.com/2266487/127309229-dd00fb2b-4041-47ef-8c15-69bc22704be0.png)

@RussKie can you ask your contact on the Windows team about the Build number because I think the fix it not release yet right ?

**Comment by pmiossec** [comment] 2021-07-28 11:11
I know you love screenshots @tebeco , so I will give you another one 😄 

![image](https://user-images.githubusercontent.com/460196/127312925-2a2b922f-7296-465d-bc28-a31a21025a51.png)

Easier for everyone....

**Comment by tebeco** [comment] 2021-07-28 11:11
I though the icon was not loading -_- HAHAHAH

**Comment by gerhardol** [comment] 2021-07-28 15:01
> @RussKie can you ask your contact on the Windows team about the Build number because I think the fix it not release yet right ?

This was reported on Microsoft Windows NT 10.0.22000.0

I assume the Windows team have resolved this in their internal builds

**Closed** 2021-11-07 22:39 UTC
Labels: type: bug :bug:, area: win11
