### ISSUE TITLE
Revision Links Variables per remote

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#4404] opened 2018-01-30 04:32 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Revision links are awesome.  Configuring them is a pain.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Add a variable helper that adds dynamic values per remote to revision links.  Allow a selection of remote and a dynamic list of variables, the user can create.  

## Sample Data
Origin:ghUser:vbjay
Upstream:ghUser:GitExtensions.

## Example usage

link url is https://github.com/{ghUser}/{ghRepo} and a way to set these values for each remote that exists.

**Environment you encounter the issue:**

- GitExtensions version:2.5.1
- GIT version: na
- OS version: na

**Did this work in previous version of GitExtensions (which)?**
no

**Comment by gerhardol** [comment] 2018-01-30 23:13
Related to #4280

**Comment by jbialobr** [comment] 2018-01-31 05:45
https://git-extensions-documentation.readthedocs.io/en/latest/settings.html#revision-links-remote-data

**Comment by jbialobr** [comment] 2018-01-31 09:21
Probably a duplicate of #2768

**Comment by GintasS** [comment] 2021-08-22 14:12
We should close this as per @jbialobr comment - the duplicate was also closed.

**Closed** 2021-08-22 22:46 UTC
Labels: type: feature request, status: workaround available
