### ISSUE TITLE
Double context-menu divider for FormCommit's workspace items

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#11909] opened 2024-09-12 04:37 UTC
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.45.2.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 144dpi (150% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 9.0.0-preview.7.24405.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

![image](https://github.com/user-attachments/assets/2f877291-57d4-40ac-bb3a-729e20298907)

### Steps to reproduce

In `FormCommit`, rIght-click a file in the workspace.

### Did this work in previous version of GitExtensions?

This was introduced with 5.0.

**Comment by pmiossec** [comment] 2024-09-12 08:33
Reproduced: a separator is added in some circumstances and you can end up with a lot:

![image](https://github.com/user-attachments/assets/f0fb8268-c3a8-41eb-b61c-d79caa57f106)
 
Not sure but maybe side effect of #11239 . /cc @SlugFiller

**Comment by SlugFiller** [comment] 2024-09-12 09:25
Any more details about what circumstances this appears? I can't reproduce it on `master` (5816617f59542d7180371ab161d1008a4eb69663). The closest I got was having one unnecessary separator, in the commit dialog only, if there are no scripts (It removes the `Run script` menu, but not the matching separator)

It seems to be related to 844050a9fd4a5d3a93a4888a2f6e5d424d7e1ac0 which causes the issue to not appear in the diff view, but doesn't touch the file list or commit dialog

**Comment by gerhardol** [comment] 2024-09-12 10:13
It is occasionally in RevDiff too.

**Comment by pmiossec** [comment] 2024-09-12 10:55
Steps I follow to reproduce:
1. Having changes on a text files (where I have scripts defined) and change in a submodule ( so where no scripts could be defined)
2. Open alternatively contextual menu on each changes
3. Each cycle (opening has been done on the 2 changes), a new separator is added

Changes that allows to reproduce:
![image](https://github.com/user-attachments/assets/8f38ea6e-8f78-4e71-a24e-d1bf1405cf04)

![separators_everywhere](https://github.com/user-attachments/assets/ceff4b46-35fd-42ba-a167-be3de0b07920)

![938obf](https://github.com/user-attachments/assets/de0aef6c-7c6e-4f9c-8b8f-c09a8732fd68)

**Comment by SlugFiller** [comment] 2024-09-12 23:24
Okay, I was able to reproduce the issue on `master`, on 53e31e0c94a4b5078b388b8932390b2c0df0b864, AND in 8a552ac13fa698f47674939aaebc671cf623d711 as well. So the problem has nothing to do with whether or not the `Run script` submenu appears.

My process for reproduction is also a bit more convoluted. I added a submodule, and when going to the commit window, I can safely right click it without issues. From 53e31e0c94a4b5078b388b8932390b2c0df0b864 onward a `Run script` submenu appears, as expected.

If I then stage the submodule and unstage it, and _then_ right click, the `Run script` submenu disappears. Right clicking on another unstaged file after that will cause an increase in separators. However, the increase in separators occurs even if done in a commit prior to `Run script` being added, so the two symptoms: `Run script` not appearing, and separators being added, while potentially related, are not causally linked.

Right clicking a staged submodule seems to work without issues every time. Also, right clicking a modified module in the diff tab.

I'd farther bisect, but building older commits seems to be somewhat buggy for me. I end up getting runtime exceptions for some reason, and past a certain commit, I also get failed builds due to security errors in dependencies.

**Comment by mstv** [comment] 2024-09-13 16:13
The `_sortByContextMenu` item gets removed somehow when switching between files and submodules, but not the separator which is added before it.

**Comment by mstv** [comment] 2024-09-13 22:43
STR: open the context menu for both items alternately multiple times

![image](https://github.com/user-attachments/assets/a2030d91-669f-4f97-938f-ae7181c33a62)

**Comment by drewnoakes** [comment] 2024-09-13 23:19
FYI the original screenshot is from the dotnet/aspire repo which doesn't use submodules.

**Comment by SlugFiller** [comment] 2024-09-13 23:25
Yeah, the conversation ended up mixing two different issues.
1. If no script are set, and right click is used, an extra separator can appear in some locations where it would normally separate between the `Run script` submenu and the rest of the menus. This was partially fixed in 844050a9fd4a5d3a93a4888a2f6e5d424d7e1ac0 but only in the diff tab, and needs to be extended to other areas.
2. If right clicking submodules and files interchangeably in the commit form's unstaged panel, under certain star alignments, an infinite set of separators would appear. This has nothing to do with `Run scripts`, and can be reproduced in earlier commits.

These are two very separate bugs, which need to be addressed separately.

**Comment by mstv** [comment] 2024-09-14 07:52
> If no script are set, and right click is used, an extra separator can appear in some locations where it would normally separate between the Run script submenu and the rest of the menus. This was partially fixed in https://github.com/gitextensions/gitextensions/commit/844050a9fd4a5d3a93a4888a2f6e5d424d7e1ac0 but only in the diff tab, and needs to be extended to other areas.

Thank you for repeating the first point including the git hash. I have added this to #11916.

**Comment by SlugFiller** [comment] 2024-09-14 16:00
Incidentally, does the fact that an added submodule only seems to get a different menu if I stage and unstage it count as a third issue?

**Closed** 2024-09-15 08:53 UTC
Labels: type: bug :bug:

**Comment by mstv** [comment] 2024-09-15 09:09
> Incidentally, does the fact that an added submodule only seems to get a different menu if I stage and unstage it count as a third issue?

Yes, as a separate one. Open a bug report, please.
