### ISSUE TITLE
Some layouts are unreadable

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#4194] opened 2017-12-05 23:32 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
![image](https://user-images.githubusercontent.com/3629489/33636375-d83a778c-d9e9-11e7-8415-88ae5502bc9e.png)

![image](https://user-images.githubusercontent.com/3629489/33636405-f45a6364-d9e9-11e7-85a6-a1fcb8f3377c.png)

![image](https://user-images.githubusercontent.com/3629489/33636437-1b744442-d9ea-11e7-9253-c651a7dae71e.png)

![image](https://user-images.githubusercontent.com/3629489/33636454-3380c47a-d9ea-11e7-9363-2ac903e49c20.png)

These layouts do not show the commit text.  The other layouts do.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Cycle through layouts.  Ctrl+ Shift+ L
**What is the expected behavior?**
To read the commit text of the selected commit.
**Environment you encounter the issue:**

- GitExtensions version:2.50.02
- GIT version: NA
- OS version: 

![image](https://user-images.githubusercontent.com/3629489/33636593-da43c3d4-d9ea-11e7-8f60-01278d2334cb.png)

**Did this work in previous version of GitExtensions (which)?**
Not sure

**Comment by RussKie** [comment] 2017-12-05 23:51
It looks like the text is there, it is just in light color which makes unreadable

**Comment by vbjay** [comment] 2017-12-06 00:22
Right.

**Comment by RussKie** [comment] 2017-12-13 21:55
Duplicate of #3978

**Closed by RussKie** 2017-12-13 21:55 UTC
Labels: bug, UX
