### ISSUE TITLE
Crash on file "save as"

### ISSUE THREAD

**Issue by trojanobelix** [gitextensions/gitextensions#7059] opened 2019-08-27 07:19 UTC
## Current behaviour

right mouse context menü "save as.." leads to program crash!

## Expected behaviour

right mouse context menü "save as.." should save selected file
## Steps to reproduce

stash current files
checkout old commit 
select a file in file tree of the stash
right mouse context menü "save as.."
Crash!

## Error Details
```
System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\Git_lokal\alcocontrol\90000407456\Source\alcocontrol.X\Makefile.X\Makefile" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   bei GitCommands.GitModule.SaveBlobAs(String saveAs, String blob)
   bei GitUI.CommandsDialogs.RevisionFileTreeControl.saveAsToolStripMenuItem_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei Syste

**Comment by RussKie** [comment] 2019-08-27 09:49
Which version? All environment info is missing

**Comment by trojanobelix** [comment] 2019-08-27 13:53
Sorry, I thought the "send" button in the crash report picks up all environment info 

Microsoft Windows 7 Professional
Version	6.1.7601 Service Pack 1 Build 7601

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.23.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-08-27 14:00
Cannot reproduce. Assumed FormBrowse "full" stash commit (not FormStash).
What type of file?
Virus (like Symantec) interfering?

**Comment by trojanobelix** [comment] 2019-08-28 07:04
I tested it again. Forget the stash stuff.
Just pick a file in an older commit and try to "save as" anywhere.

The file is a makefile ("Makefile", no extension) . That seems to be important. 
Than you get a _"System.IO.DirectoryNotFoundException"_
And _"A part of the path  "C:\Temp\Makefile.X\Makefile" could not be found"_

**Strange is the "Makefile.X" part. I have tried to save the file in "C:\Temp\" without changing the file name**

If you press "Speichern" (save) in this dialog, GE crashes:
![image](https://user-images.githubusercontent.com/15106425/63833117-82d59180-c972-11e9-9fa5-a204008a7a9a.png)

Crash report:
![image](https://user-images.githubusercontent.com/15106425/63832321-da72fd80-c970-11e9-9fda-d1b60289c3c6.png)

**Comment by RussKie** [comment] 2019-08-28 07:11
Try the latest dev build https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts

**Comment by RussKie** [comment] 2019-08-28 07:12
I can't replicate it - I attempted to save files from an old commit located in one of directories in that commit. All was good and worked as expected.

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.16.1.windows.4
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 144dpi (150% scaling)

**Comment by trojanobelix** [comment] 2019-08-28 07:14
**The file is a makefile ("Makefile", no extension) . That seems to be important.**

**Comment by RussKie** [comment] 2019-08-28 07:19
I just tried to save a nested makefile from git repo and it worked.

Does MakeFile.X folder exist in the working directory?

Can you share your repo? Or create a sample repo that repros the issue?

**Comment by trojanobelix** [comment] 2019-08-28 07:37
[Bugtest.zip](https://github.com/gitextensions/gitextensions/files/3549622/Bugtest.zip)

The project directory is named as "[projectname].X" by microchips IDE MplabX.
I think that's where the ".X" come from

See test project.

**Comment by gerhardol** [comment] 2019-08-28 20:33
I do not get an exception (using 3.1.1 or master), but cannot save the faile.
The suffix is incorrectly detected.

Submitted a PR. 
It is possible to make a nicer solution with tests that actually will be merged...

**Closed** 2019-09-01 15:15 UTC
Labels: status: incorrectly filled template, status: more info requested
