### ISSUE TITLE
[NBug] fatal: detected dubious ownership in repository at 'C:/work...

### ISSUE THREAD

**Issue by usmanimtiaz63** [gitextensions/gitextensions#10462] opened 2022-11-28 10:55 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: for-each-ref --sort="-taggerdate" --format="%(refname)" refs/tags/
Working directory: C:\workdir\nucleus\training\

```
GitExtUtils.ExternalOperationException: fatal: detected dubious ownership in repository at 'C:/workdir/nucleus/training'
'C:/workdir/nucleus/training' is owned by:
	'S-1-5-32-544'
but the current user is:
	'S-1-5-21-3530618289-4130249674-1136526561-408327'
To add an exception for this directory, call:

	git config --global --add safe.directory C:/workdir/nucleus/training
 ---> System.Exception: fatal: detected dubious ownership in repository at 'C:/workdir/nucleus/training'
'C:/workdir/nucleus/training' is owned by:
	'S-1-5-32-544'
but the current user is:
	'S-1-5-21-3530618289-4130249674-1136526561-408327'
To add an exception for this directory, call:

	git config --global --add safe.directory C:/workdir/nucleus/training
   --- End of inner exception stack trace ---
   at async Task<string> GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes)
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTask<T>.CompleteOnCurrentThread()
   at IDictionary<string, int> GitUI.CommitInfo.CommitInfo.GetSortedTags()
   at async Task GitUI.CommitInfo.CommitInfo.LoadSortedTagsAsync()
   at async void GitUI.CommitInfo.CommitInfo.RefreshSortedTags()+(?) => { }
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

Upgraded git extensions and now these exceptions

### Steps to reproduce

Open "GitExt Open Repository"
Switch to a different repository from  "Change working directory" from with in the Git Extensions.

### Did this work in previous version of GitExtensions?

Yes. 3.x

**Comment by RussKie** [comment] 2022-11-28 10:59
Please read the message of the dialog. This is something you have to action.

**Comment by pmiossec** [comment] 2022-11-28 11:00
> ### Did this work in previous version of GitExtensions?
> 
> Yes. 3.x

No. I don't think so. It's a behavior change introduced by git 2.35.1 
Duplicate of #9954

Run the command in the error message...

**Comment by pmiossec** [comment] 2022-11-28 11:03
Closing as already discussed previously and UX improved by #10436 (waiting for release)

**Closed by pmiossec** 2022-11-28 11:03 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate

**Comment by usmanimtiaz63** [comment] 2022-11-28 11:16
Hmm... Also updated git from 2.33.0.2 to 2.38.1; So potentially caused by git. 

Git global config needs to be updated for safe

[safe]
	directory = <c:/directory/path>
