### ISSUE TITLE
Doesn't launch on macOS

### ISSUE THREAD

**Issue by wcoder** [gitextensions/gitextensions#5945] opened 2018-12-18 19:01 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Crash

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. mono --arch=32 GitExtensions.exe
2. Crash

**What is the expected behavior?**

Run correctly

**Environment you encounter the issue:**

Mono:
```
Mono JIT compiler version 5.16.0.221 (2018-06/b63e5378e38 Mon Nov 19 18:08:09 EST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-release_60/0b3cb8ac12c)
	GC:            sgen (concurrent by default)
```

- GitExtensions version: v3.0.0
- GIT version: 2.14.0
- OS version: macOS v10.14.2 (18C54) (Mojave)
- .NET version: .Net Core 2.1.302

**Did this work in previous version of GitExtensions (which)?**

Yes, don't remember which version

Log:
```
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'GitUI.FontUtil' threw an exception. ---> System.DllNotFoundException: uxtheme.dll
  at (wrapper managed-to-native) GitUI.NativeMethods.OpenThemeData(intptr,string)
  at GitUI.FontUtil..cctor () [0x00000] in <36ab48be24cf4e0b8ce0f075bf6dcb29>:0
   --- End of inner exception stack trace ---
  at GitUI.CommandsDialogs.SettingsDialog.Pages.FormChooseTranslation..ctor () [0x0000c] in <36ab48be24cf4e0b8ce0f075bf6dcb29>:0
  at (wrapper remoting-invoke-with-check) GitUI.CommandsDialogs.SettingsDialog.Pages.FormChooseTranslation..ctor()
  at GitExtensions.Program.RunApplication () [0x00044] in <abf89b0081db49299416365187e739cc>:0
  at GitExtensions.Program.Main () [0x000a7] in <abf89b0081db49299416365187e739cc>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'GitUI.FontUtil' threw an exception. ---> System.DllNotFoundException: uxtheme.dll
  at (wrapper managed-to-native) GitUI.NativeMethods.OpenThemeData(intptr,string)
  at GitUI.FontUtil..cctor () [0x00000] in <36ab48be24cf4e0b8ce0f075bf6dcb29>:0
   --- End of inner exception stack trace ---
  at GitUI.CommandsDialogs.SettingsDialog.Pages.FormChooseTranslation..ctor () [0x0000c] in <36ab48be24cf4e0b8ce0f075bf6dcb29>:0
  at (wrapper remoting-invoke-with-check) GitUI.CommandsDialogs.SettingsDialog.Pages.FormChooseTranslation..ctor()
  at GitExtensions.Program.RunApplication () [0x00044] in <abf89b0081db49299416365187e739cc>:0
  at GitExtensions.Program.Main () [0x000a7] in <abf89b0081db49299416365187e739cc>:0
```

**Comment by gerhardol** [comment] 2018-12-18 20:15
v2.5x is x-plat, and v3 only works on Windows, please refer to the readme and the changelog

Duplicate of #5914 #5940

**Comment by RussKie** [comment] 2018-12-18 21:09
Duplicate of #5914

**Comment by RussKie** [comment] 2018-12-18 21:11
Duplicate of #5940

**Closed by RussKie** 2018-12-18 21:12 UTC

**Comment by dluc** [comment] 2019-07-30 23:15
why is v3 Windows only? change of directions? should we assume this project will be Windows only from now on?

**Comment by RussKie** [comment] 2019-07-31 20:54
This was discussed in #4308.
v2.x is still available for Mono users, if you wish to have v3 on Mono - you're welcome to get involved and contribute.
