### ISSUE TITLE
Impossible to display app after minimizing it in taskbar - Windows 10 build 22H2 19045.2364

### ISSUE THREAD

**Issue by flaubertlekhem** [gitextensions/gitextensions#10557] opened 2022-12-20 09:30 UTC
### Environment

- GitExtensions version: 2.39.0.windows.1
- GIT version: 4.0.1.15887
- OS version: Microsoft Windows NT 10.0.19045.0
- .NET version: .NET 6.0.12

### Issue description

In certains circumstances, when you minimized the window of Git extension, it is impossible to display it again. You have to close the application or open it through task manager by double clicking on the application

### Steps to reproduce

How to reproduce the issue.
1. Open Git extension
2. Maximize the window of Git extension (Optional if the issue already happen and you opened it through task manager).
3. Minimize the window of Git extension
4. Try to display the window of Git extension and it wont works.
Please let me know if you succeed to reproduce the bug.
Regards.

### Did this work in previous version of GitExtensions?

The issue never happened it the previous git extension version (3.xx)

**Comment by pmiossec** [comment] 2022-12-20 09:40
Duplicate of #9752
And you try a workaround explained in #10119 (see there the setting to set)

**Closed by pmiossec** 2022-12-20 09:40 UTC
Labels: :eyeglasses: status: needs review
