### ISSUE TITLE
Pluging delete obsolete branches not working

### ISSUE THREAD

**Issue by taipignas** [gitextensions/gitextensions#10619] opened 2023-01-06 07:47 UTC
### Environment

- GitExtensions version: 4.0.1 portable
- GIT version: 2.36
- OS version: Windows 10
- .NET version: 7.0.100

### Issue description

The plugin used to delete all the selected branches but now it freezes, it seems like 1 branch is getting deleted.

### Steps to reproduce

Have few branches merged and ready to be deleted.
Launch the plugin.
Mark the several branches
Click "delete"

**Comment by vbjay** [comment] 2023-01-06 13:05
Use help about copy button to get version info.

**Comment by gerhardol** [comment] 2023-01-06 14:09
Duplicate of #10347
Fixed in #10396.
Please try the latest portable builds for master.

**Closed by gerhardol** 2023-01-06 14:09 UTC
Labels: :eyeglasses: status: needs review

**Comment by taipignas** [comment] 2023-01-09 11:04
Like i said, i am using the latest portable version which is "4.0.1 portable". When using the plugin to delete branches(even a single branch) it freezes. I am able to click the "x" button, after which i can see that 1 branch was deleted, if i selected 5 branches 1 gets deleted.
