### ISSUE TITLE
[NBug] The system cannot find the file specified

### ISSUE THREAD

**Issue by karthikpromontory** [gitextensions/gitextensions#6687] opened 2019-05-28 19:13 UTC
## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.ExecutableExtensions.<ExecuteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, Boolean stripAnsiEscapeCodes)
   at GitUI.CommandsDialogs.FormResolveConflicts.ResolveFilesConflict(ConflictData item)
   at GitUI.CommandsDialogs.FormResolveConflicts.ResolveItemConflict(ConflictData item)
   at GitUI.CommandsDialogs.FormResolveConflicts.ConflictedFiles_DoubleClick(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.FormResolveConflicts.OpenMergetool_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-05-28 19:51
Duplicate of #6629

**Comment by mstv** [comment] 2019-05-28 20:14
@karthikpromontory, it looks like you have tried to solve a merge conflict.
Have you configured the merge tool correctly?
The installer of Git Extensions 3.x does not install KDiff3 anymore.
If this does not solve your problem, give us information how to reproduce it, please.

**Comment by karthikpromontory** [comment] 2019-06-04 16:02
Thank you. I had not installed kdiff separately. I did now. I guess I will know when I get the next merge conflict if that fixed the issue :)

**Comment by gerhardol** [comment] 2019-06-25 17:29
This should be prevented even if the number of incorrect configurations should decrease over time.

**Comment by mstv** [comment] 2019-06-25 21:58
> This should be prevented even if the number of incorrect configurations should decrease over time.

I agree. We should show a MessageBox lile "Z:\Y.exe could not be found."

Because of async, it is not easy to me to decide where to catch the Exception and to display the error message. I would prefer a `try catch` around `new Process` in the constructor of `ProcessWrapper`.
Though I'm afraid, `await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();`  cannot be called in a constructor.
`Executable.Start()` is not async, too...

**Comment by RussKie** [comment] 2019-06-26 14:01
I have a fix, will send a PR shortly

**Closed** 2019-06-27 12:35 UTC
Labels: area: user experience, status: incorrectly filled template, type: bug
