### ISSUE TITLE
[NBug] InvalidArgument=Value mit dem Wert 0 ist für index ungültig...

### ISSUE THREAD

**Issue by mklinke** [gitextensions/gitextensions#7265] opened 2019-10-08 15:46 UTC
## Current behaviour

In the (empty) branches input box in the toolbar, enter a partial remote branch name, the drop-down with suggestions is opened but empty. Then switch windows with Alt + Tab -> Crash

## Expected behaviour
Type a partial branch name in the toolbox, change windows to lookup the actual branch name and switch back to finish the input.

## Steps to reproduce

In the branches input box in the toolbar, enter a partial remote branch name.
Now, either the drop-down with suggestions is opened automatically or click on the branch input box to show the drow-down. Make sure it is empty, i.e. enter an invalid branch name.
Then switch windows with Alt + Tab -> Crash

## Error Details
```
System.ArgumentOutOfRangeException: InvalidArgument=Value mit dem Wert 0 ist für index ungültig.
Parametername: index
   bei System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   bei System.Windows.Forms.ComboBox.UpdateText()
   bei System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   bei System.Windows.Forms.ComboBox.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 144dpi (150% scaling)

**Comment by mklinke** [comment] 2019-10-09 06:31
Ping, filled the fields but really don't have any more details than that.

**Comment by gerhardol** [comment] 2019-10-11 20:55
Duplicate of #6680

PR in #7271, please try the build

**Closed** 2019-10-11 21:06 UTC
Labels: :beetle: type: bug, potential-duplicate
