### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Reactive.PlatformSe...

### ISSUE THREAD

**Issue by guywmustang** [gitextensions/gitextensions#10624] opened 2023-01-07 08:53 UTC
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.2
- Microsoft Windows NT 10.0.22623.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Reactive.PlatformServices, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The system cannot find the file specified.
File name: 'System.Reactive.PlatformServices, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'
   at BackgroundFetch.BackgroundFetchPlugin.RecreateObservable()
   at BackgroundFetch.BackgroundFetchPlugin.Register(IGitUICommands gitUiCommands)
   at GitUI.PluginRegistry.<>c__DisplayClass12_0.<Register>b__0(IGitPlugin p)
   at System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
   at GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   at GitUI.CommandsDialogs.FormBrowse.SetGitModule(Object sender, GitModuleEventArgs e)
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.Dashboard.OnModuleChanged(Object sender, GitModuleEventArgs e)
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.Dashboard.openItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Opened a folder with a git repo, got the error.

I previously had to install the windows desktop runtime 6.0.12 for win 64 because I didn't have it.

### Steps to reproduce

Open a git repo

**Comment by gerhardol** [comment] 2023-01-07 13:00
Is this a normal installation?
If it is a portable, was it extracted to a clean directory?

**Comment by mstv** [comment] 2023-01-07 13:10
Was a Windows or a .NET update pending?

**Comment by guywmustang** [comment] 2023-01-07 17:51
This was a normal installation.  I had previously uninstalled an old version (previous major version I believe). 

I had already done all necessary windows updates.

**Comment by mstv** [comment] 2023-01-07 19:07
For the duplicates, it was a temporary issue. The next start of GE worked - at least after a reboot.

**Comment by gerhardol** [comment] 2023-02-24 21:02
Duplicate of #10368
This error seem to occur related to Windows and/or .NET updates and seem to be resolved by app or possible PC restarts.
Not sure if this can be detected.

**Closed by gerhardol** 2023-02-24 21:02 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate

**Comment by klorinczi** [comment] 2023-02-26 00:25
I found, that if I deleted files in Plugins directory and copied the files from portable zip file again.

The problem was, that the Plugins directory contained dll files with old naming scheme used in Git Extensions v3.1.1.


I hope this helps.

**Comment by vbjay** [comment] 2023-02-26 02:37
Portable is not upgradable. Must be a clean copy. You can copy settings.

**Comment by klorinczi** [comment] 2023-02-26 13:44
@vbjay Portable might still contain some checking to avoid such errors.

Where is the portable version storing the settings?

**Comment by vbjay** [comment] 2023-02-26 14:04
Portable is designed to be self contained. All of it is in the folder you extractref to. 

>Portable might still contain some checking 

How do you expect that to happen when we are getting assembly load problems when you mix different version assemblies?

**Comment by klorinczi** [comment] 2023-02-26 14:14
Don't load all DLL files without checking.
Could be possible do a pre-check before load, if exactly those DLL files are in Plugins directory (having the correct CRC for each DLL file, based on an SHA1 or MD5 list)?

Just an idea.
