### ISSUE TITLE
Sometimes GitExtension can not recover when clicking minized icon from Windows status bar

### ISSUE THREAD

**Issue by renfengyue** [gitextensions/gitextensions#10651] opened 2023-01-16 08:28 UTC
### Environment

- GitExtensions version: 4.0.1.15887
- GIT version: 2.38.1.windows.1
- OS version:  Windows NT 10.0.19044.0
- .NET version: 6.0.12

![Version](https://user-images.githubusercontent.com/3722555/212631264-2cbbb003-b71f-4bdb-afbd-4c0a58e2678a.jpg)

### Issue description

Occasionally, I switch to other application, then I try to switch to GitExtension by clicking the GitExtension icon from Windows status bar, nothing happens, GitExtension main window does not activated and displayed on Windows.
The issue will not fix before I kill GitExtension and restart it.

### Steps to reproduce

No special steps needed, just switch to other application, and use them, then try to switch to GitExtension by clicking minimized icon from Windows status bar.

### Did this work in previous version of GitExtensions?

Yes, it works find in the previous version.

### Diagnostics

You can find the log from attachement below.
[GitExtension log.txt](https://github.com/gitextensions/gitextensions/files/10423825/GitExtension.log.txt)

**Comment by gerhardol** [comment] 2023-01-16 08:33
Duplicate of #10398

**Closed by gerhardol** 2023-01-16 08:33 UTC
Labels: :eyeglasses: status: needs review
