### ISSUE TITLE
Search box in recent repositories

### ISSUE THREAD

**Issue by MarvelWild** [gitextensions/gitextensions#8531] opened 2020-10-09 17:27 UTC
recent repositories list is hard to navigate with 20> projects.
would be much easier with search box

**Comment by ivangrek** [comment] 2020-10-21 22:15
Please see #8561

**Comment by gerhardol** [comment] 2020-10-23 19:30
Handle as duplicate of #8561 that has some more suggestions

**Closed by gerhardol** 2020-10-23 19:30 UTC
Labels: type: discussion
