### ISSUE TITLE
stash pop command

### ISSUE THREAD

**Issue by markuskreth** [gitextensions/gitextensions#2795] opened 2015-05-07 07:57 UTC
I can't find a direct way to do a "stash pop", which is of cause a combined "stash apply" and "stash drop".
In the stash dialog (german language), there are the three option buttons together at the left bottom corner. They are coequal one below the other with "stash drop" in the middle.
This leads to accidental clicks on drop, even pop was meant, so all stashed changes are lost.

A highlighted button "stash pop" would be highly appreciated.

**Comment by Radrik5** [comment] 2015-05-07 08:25
Probably duplicate of #2708.

And there is "Stash pop" on the toolbar:
![image](https://cloud.githubusercontent.com/assets/9339459/7511191/bcb784f8-f4ab-11e4-9407-398928c097dc.png)

**Comment by markuskreth** [comment] 2015-05-07 08:28
Oh, never saw that. 
I searched the documentation put "pop" was not mentioned here:
https://git-extensions-documentation.readthedocs.org/en/latest/

Thanks!

**Closed** 2015-05-12 14:11 UTC
