### ISSUE TITLE
[NBug] Unable to update remote pushurl for command output: origin	...

### ISSUE THREAD

**Issue by frini37** [gitextensions/gitextensions#11512] opened 2024-01-11 18:22 UTC
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.Exception: Unable to update remote pushurl for command output: origin	ssh://git@bitbucket-rh7:7999/alg/5g-nr.git (push)
   at Task<IReadOnlyList<Remote>> GitCommands.GitModule.GetRemotesAsync()+ParseRemotes(ExecutionResult result) in C:/projects/gitextensions/GitCommands/Git/GitModule.cs:line 2371
   at async Task<IReadOnlyList<Remote>> GitCommands.GitModule.GetRemotesAsync() in C:/projects/gitextensions/GitCommands/Git/GitModule.cs:line 2336
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTask<T>.CompleteOnCurrentThread()
   at Nodes GitUI.LeftPanel.RemoteBranchTree.FillTree(IReadOnlyList<IGitRef> branches, CancellationToken token) in C:/projects/gitextensions/GitUI/LeftPanel/RemoteBranchTree.cs:line 29
   at async Task<Nodes> GitUI.LeftPanel.BaseRefTree.LoadNodesAsync(CancellationToken token, Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs) in C:/projects/gitextensions/GitUI/LeftPanel/BaseRefTree.cs:line 40
   at async JoinableTask GitUI.LeftPanel.Tree.ReloadNodesDetached(Func<CancellationToken, Func<RefsFilter, IReadOnlyList<IGitRef>>, Task<Nodes>> loadNodesTask, Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs)+(?) => { } in C:/projects/gitextensions/GitUI/LeftPanel/Tree.cs:line 98
   at async Task Microsoft.VisualStudio.Threading.ThreadingTools.WithCancellationSlow(Task task, bool continueOnCapturedContext, CancellationToken cancellationToken)
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 28
```

this is the git config file in the repo
[core]
	repositoryformatversion = 1
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
	compression = -1
[submodule]
	active = .
[remote "origin"]
	url = ssh://git@------------------------
	fetch = +refs/heads/*:refs/remotes/origin/*
	promisor = true
	partialclonefilter = blob:none
[branch "master"]
	remote = origin
	merge = refs/heads/master
[submodule "aaaaa"]
	url = http://-------------------
[submodule "bbbbb"]
	url = http://---------------------
[pack]
	compression = 9
[submodule "Externals/yyyyyyyyyyyyyy"]
	url = https://-----------------
[submodule "Externals/xxxxxxxxxxxxxxx"]
	url = https://------------------------
i think the problem is the repositoryformatversion = 1

### Steps to reproduce

clone repo that causes repositoryformatversion =1 
than every action causes an exception
if pressing ignore, the sw continues ok

**Comment by gerhardol** [comment] 2024-07-07 21:12
Duplicate of #11424 
Fixed in #11429

**Closed by gerhardol** 2024-07-07 21:12 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
