### ISSUE TITLE
Hiding GitExtensions toolbar causes Visual Studio to crash on startup

### ISSUE THREAD

**Issue by spzcom** [gitextensions/gitextensions#2691] opened 2015-03-04 20:50 UTC
--- GitExtensions2.48.03, Git 1.9.4.msysgit.2, Microsoft Windows NT 6.2.9200.0

Steps:
- Right-click on blank space somewhere in Visual Studio toolbar to bring up the Toolbars enable/disable context menu
- Click on the GitExtensions item to hide/disable that toolbar
- GitExtensions toolbar is now hidden
- Restart Visual Studio

Expected result:
- Visual Studio should start without problem and GitExtensions toolbar should stay hidden

Actual result:
- At startup Visual Studio crashes

Workaround:
- The only workaround I've found is to start Visual Studio from command line using the safemode switch and then enable/show the GitExtensions toolbar again
- Command line: devenv.exe /safemode

**Comment by tomasdeml** [comment] 2015-03-05 07:35
Duplicate of #2587?

**Closed** 2016-04-18 22:51 UTC

**Comment by jmvdkolk** [comment] 2018-01-03 09:39
This may be a duplicate of #2587, but I am not sure. #2587 is supposedly solved. I still have this issue though, on Visual Studio 2015, using git extensions 2.50.02. The only solution I have found so far, is to not install the Visual Studio integration.

**Comment by RussKie** [comment] 2018-01-04 07:49
I tried it on VS 2017 with the VSIX published by Henk few months ago - I
have no dramas opening or closing the VS with the toolbar shown or hidden...
I don't have a VS 2015 readily available for me to try
