### ISSUE TITLE
VS17 support

### ISSUE THREAD

**Issue by Lord-Haji** [gitextensions/gitextensions#3702] opened 2017-05-15 18:16 UTC

**Comment by vbjay** [comment] 2017-05-15 18:47
Next time, search issues before posting issues. Also use the template provided to create issues.

**Comment by vbjay** [comment] 2017-05-15 18:49
https://github.com/gitextensions/gitextensions/issues?utf8=✓&q=is%3Aissue%20vs2017

**Comment by KindDragon** [comment] 2017-05-16 11:13
Duplicate of #3466

**Closed by KindDragon** 2017-05-16 11:13 UTC
