### ISSUE TITLE
Error on entering the commit screen

### ISSUE THREAD

**Issue by thoward333** [gitextensions/gitextensions#2721] opened 2015-03-19 19:29 UTC
I just updated to version 2.48.03. Whenever I enter the commit window, I get the following exception:
(https://cloud.githubusercontent.com/assets/4550812/6739051/9119f6f8-ce4c-11e4-9aa0-b863ef761ca4.png)

When I click OK I am able to continue into the commit window, but this is a huge nuisance.

Thanks
-Trey

**Comment by KindDragon** [comment] 2015-03-23 10:22
Duplicate of #2623

Try this:
> Removing AutoCheckForUpdates.dll from the GitExtensions\Plugins folder fixed it for me too.

**Closed by KindDragon** 2015-03-23 10:22 UTC
