### ISSUE TITLE
 always show "没有得到解决的合并冲突"

### ISSUE THREAD

**Issue by hhhaiai** [gitextensions/gitextensions#10002] opened 2022-05-18 02:42 UTC
### Environment

- GitExtensions version:  3.5.4.12724
- GIT version:  2.36.0.windows.1
- OS version: Windows NT 10.0.19044.0
- .NET version: 4.8.4510.0

### Issue description

every project open , alway show "没有得到解决的合并冲突"，reinstall  as same.

![2022-05-18_103924](https://user-images.githubusercontent.com/5738285/168945980-c5a36de4-de42-4c82-8835-7c2bc63cd160.png)

### Steps to reproduce

open every project .

### Did this work in previous version of GitExtensions?

no. not use old version

### Diagnostics

native can clear ?

**Comment by RussKie** [comment] 2022-05-18 14:46
I don't read Chinese, but this looks like a duplicate of https://github.com/gitextensions/gitextensions/issues/9954.

**Closed by RussKie** 2022-05-18 14:46 UTC
Labels: :eyeglasses: status: needs review

**Comment by hhhaiai** [comment] 2022-05-24 11:05
@RussKie  


I mean always show dialog. has not merge, I fix use this command:

```
git config --global advice.useCoreFSMonitorConfig false
```
