### ISSUE TITLE
Failed to login to Github

### ISSUE THREAD

**Issue by Egor92** [gitextensions/gitextensions#8808] opened 2021-01-30 20:57 UTC
## Current behaviour

I try to login to GitHub in via Plugin/Github menu.
I enter correct login and password
Error occurs: Fail to generate due to error Not Found

## Expected behaviour

I login successfully

## Screenshots

![Github credentials](https://user-images.githubusercontent.com/5503885/106367828-8420a000-6356-11eb-8f8e-e7b9904b2a61.jpg)

## Did this work in previous version of GitExtensions

I don't know

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.0.windows.2
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4300.0
- DPI 120dpi (125% scaling)

**Comment by glebov21** [comment] 2021-02-02 13:46
I solve this problem by using SSH:
1) generate ssh keys by puttyGen
2) paste new public key into https://github.com/settings/keys
3) Open Repository->Remote repositories...
4) Url: git@github.com:username/myrepository.git
5) Browse private ssh key and click "Load SSH key"
6) Try test connection in this window.

If you have error when fetch (unable to open connection to ssh host does not exist):
1) remove files from myproject\.git\refs\remotes\origin
2) try fetch agan.

**Comment by RussKie** [comment] 2021-02-04 13:04
Thank you for sharing

**Comment by DamitSe** [comment] 2021-02-13 00:53
This looks to be a possible duplicate of #8850

**Comment by RussKie** [comment] 2021-03-14 07:37
Closing in favour of #8850

**Closed by RussKie** 2021-03-14 07:37 UTC
Labels: :beetle: type: bug, area: plugins
