### ISSUE TITLE
hang and crash when viewing diff of big code file

### ISSUE THREAD

**Issue by AlexConwayLinea** [gitextensions/gitextensions#12086] opened 2024-12-03 11:19 UTC
### Environment

- GitExtensions version: 5.1.1.17970
- GIT version: 2.47.1.windows.1
- OS version: Microsoft Windows NT 10.0.22631.0
- .NET version: 8.0.11

### Issue description

I have a large .cpp file (442kB) that has a lot of changes. When I view the diff, GitExtensions hangs for several minutes and then disappears with no crash reporting dialog or anything.

### Steps to reproduce

open Gitextensions into the repo I've provided.
select the Diff tab to view diff
select the workng directory to view the diff on the file
Gitextensions will then hang and crash while trying to display the working directory diff

[GitExtensionsBigFileDiffCrash.zip](https://github.com/user-attachments/files/17991930/GitExtensionsBigFileDiffCrash.zip)

**Comment by mstv** [comment] 2024-12-03 19:07
The "silent" crash (is caused by a stackoverflow) and has been fixed by #12040.
So, with a recent dev build, the diff can be displayed. But if scrolled horizontally, it suffers from extreme lags.
This is caused by the `TextEditorControl` used in GE. It does not handle long lines well. 250,000 characters is way, way too much for it.

Basic recommendations:
- Large files should be managed using Git LFS (examples in https://github.com/mstv/test_lfs).
- Diffs for long lines are hard to use. So, either
  - stick with the LFS-pointer-file diff or
  - add linebreaks and use `diff=lfs-text` with `git config diff.lfs-text.textconv cat` or
  - define your own LFS-text-diff filter which truncates long lines to a few thousand characters at most

**Closed by mstv** 2024-12-03 19:07 UTC
Labels: :eyeglasses: status: needs review

**Comment by AlexConwayLinea** [comment] 2024-12-05 14:04
Thanks for the info. I've decided to change my code generator so that it doesn't generate exra long lines!
