### ISSUE TITLE
Windows not restored properly when a repository is opened

### ISSUE THREAD

**Issue by pauvt** [gitextensions/gitextensions#10782] opened 2023-03-02 16:47 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.2.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.14
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

When I have a repository opened and I minimize the GitExtensions windows it's required to click twice in order to restore it. The first try always fails. Note that this only happens with a repository opened. With the dashboard it works well.

![GitExtensionsError](https://user-images.githubusercontent.com/58662223/222495152-724e79cd-3831-42e8-af9c-2d7d26b610fb.gif)

Same behavior observed in GitExtensions Portable version.

### Steps to reproduce

Open a repository.
Minimize the windows.
Restore the windows.

### Did this work in previous version of GitExtensions?

Yes. In GitExtensions-Portable-3.5.4.12724-65f01f399.zip works good.

**Comment by pmiossec** [comment] 2023-03-02 17:26
Duplicate of #10398 (and some others) 
See https://github.com/gitextensions/gitextensions/issues/10398#issuecomment-1313378235 for a workaround

**Closed** 2023-03-02 17:40 UTC
Labels: :eyeglasses: status: needs review
