### ISSUE TITLE
No indication of local changes on the toolbar anymore (regression bug?)

### ISSUE THREAD

**Issue by Konrad-Morawski** [gitextensions/gitextensions#2624] opened 2015-01-22 09:26 UTC
--- GitExtensions2.48.03, Git 1.8.3.msysgit.0, Microsoft Windows NT 6.3.9600.0

Hi,
great software, but there seems to be a regression bug...

Previous versions would include the number of changed, uncommited files next to the "Commit" button on the toolbar. (The icon got a different color, too, in such case). 

Now it's always green and I can only see local changes when I open the Commit window.

Best regards

**Comment by ghanique** [comment] 2015-01-22 10:56
I installed Git Extensions on the machines in our desktop. Some had the
same issue you described, but this solved itself. Maybe restarting the
machine is sufficient?

**Comment by KindDragon** [comment] 2015-01-22 23:24
Duplicate of issue #2560

**Closed by KindDragon** 2015-01-22 23:24 UTC
