### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SergiiGalai** [gitextensions/gitextensions#6757] opened 2019-06-06 10:25 UTC
## Current behaviour
No pull request window or redirect to browser happened. See an exception window instead

## Expected behaviour
No exception window, create pull request dialog is opened

## Steps to reproduce
1. Do Not authenticate on Github inside Git Extensions
2. Press GitHub=>Create Pull Request ... menu item for existing branch
3. Exception occurred with an option to send bug

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Git.hub.Repository.GetBranches()
   at GitHub3.GitHubRepo.GetBranches()
   at GitUI.CommandsDialogs.RepoHosting.CreatePullRequestForm.<>c__DisplayClass22_0.<<PopulateBranchesComboAndEnableCreateButton>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by SergiiGalai** [comment] 2019-06-10 09:13
I have reviewed all potential duplicates listed above - all of them are different issues

**Comment by gerhardol** [comment] 2019-06-10 22:00
> I have reviewed all potential duplicates listed above - all of them are different issues

#6625 is a duplicate of this.

**Comment by RussKie** [comment] 2019-06-11 12:16
Let's continue on this one though as @SergiiGalai has provided information.

I couldn't repro the issue though...

**Comment by pmiossec** [comment] 2019-06-12 21:40
I have investigated a little and I have an idea (though, not 100% clear) of what happens...

It seems to be a problem of authentication when querying the github apis.
By luck on my personal computer, I don't have the OAuth token filled (probably lost due to  #6696 ).
Anyway....

When the token is not generated, some exception are thrown ( like https://github.com/gitextensions/Git.hub/blob/master/Git.hub/Client.cs#L63 ) and swallowed (so we don't know that it seems to be the problem). **So, generating a github token should solve the problem.** (not tested)

These exception has as consequence that the call to the github api is made without authentication.
That return a 403 error (not allowed due to quota exceeded).

Errors are not handled by our wrapper code ( access to `Data` throw an Exception in https://github.com/gitextensions/Git.hub/blob/master/Git.hub/Client.cs#L106 but swallowed again), so `Owner` end to be null in https://github.com/gitextensions/Git.hub/blob/master/Git.hub/Repository.cs#L83 that's why the NRE is thrown.

**Comment by pmiossec** [comment] 2019-06-12 22:24
I never used this form but I also noticed that the performance of this form is really horrible and you have to wait long seconds of freeze before being able to use it.

I think that this line ( https://github.com/gitextensions/gitextensions/blob/master/GitUI/CommandsDialogs/RepoHosting/CreatePullRequestForm.cs#L146 ) should not help (in term of performance and maybe causing the current problem) by calling the same api a lot of times in a for loop (in my case 19 times!)

**Comment by SergiiGalai** [comment] 2019-06-13 08:20
>  So, generating a github token should solve the problem. (not tested)
I did that. Generated github personal access token with full access to repo scope and admin:repo_hook - read:repo_hook. Added it to Settings=>Plugins=>Github=>Effective=>OAuth Token. 
Before your message
> you have to wait long seconds of freeze
I thought it got frozen and had closed the window. After your message I repeated and waited. Yes, it has loaded Target repository and Target branch field with the list of branches from Github. Yet Your branch field is empty (I have checked out branch now) and dropdown is empty. 
So form is useless

**Comment by pmiossec** [comment] 2019-06-13 14:01
>Added it to Settings=>Plugins=>Github=>Effective=>OAuth Token.

Great, that solve the exception.

>I thought it got frozen and had closed the window. 

the fix is here: #6791

>Your branch field is empty (I have checked out branch now) and dropdown is empty.

I don't know this feature but it seems that the branch is the one pushed to your fork. Did you pushed them?

And you also have to have the remote repository where to push in added in your remotes.
Did you do it?

**Comment by SergiiGalai** [comment] 2019-06-13 14:23
> Did you pushed them?
Yes, branch is pushed and added to remotes. 
![image](https://user-images.githubusercontent.com/5754796/59440674-049c3100-8e00-11e9-8ec8-c29735573145.png)

**Closed** 2019-06-22 11:56 UTC
Labels: area: plugins, status: needs review

**Comment by pmiossec** [comment] 2020-01-16 13:41
FYI, a similar problem when the github token is set but invalid: #7641
