### ISSUE TITLE
[NBug] ConEmuCD was not loaded.

### ISSUE THREAD

**Issue by MeetOct** [gitextensions/gitextensions#6715] opened 2019-05-31 09:13 UTC
## Error Details
```
ConEmu.WinForms.GuiMacroExecutor+GuiMacroException: ConEmuCD was not loaded.
   在 ConEmu.WinForms.GuiMacroExecutor.ExecuteInProcessAsync(Int32 nConEmuPid, String asMacro)
   在 ConEmu.WinForms.ConEmuSession.ExecuteGuiMacroTextAsync(String macrotext)
   在 ConEmu.WinForms.GuiMacroBuilder.ExecuteAsync()
   在 ConEmu.WinForms.ConEmuSession.WriteOutputTextAsync(String text)
   在 GitUI.FormStatus.Done(Boolean isSuccess)
   在 GitUI.FormProcess.<>c__DisplayClass43_0.<OnExit>b__0()
   在 GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-05-31 13:23
Duplicate of #6675

**Closed** 2019-05-31 13:23 UTC
Labels: potential-duplicate
