### ISSUE TITLE
Settings dialog frozen

### ISSUE THREAD

**Issue by maxhouck** [gitextensions/gitextensions#10410] opened 2022-11-16 04:45 UTC
### Environment

- GitExtensions version: 4.0
- GIT version: 2.38.1.windows.1
- OS version: Windows 10 x64
- .NET version: 6.0

### Issue description

The settings dialog is mostly frozen. The area on the left seems clickable andthe areas are expandable, but clicking them does nothing, the OK/cancel/apply buttons don't work, and neither does the close button. I have to use task manager to close git extensions to recoverform this.

Occasionally the settings menu will eventually close if left untouched, and sometimes when reopening I can click around to different settings menus for a bit, but the ok/cancel/apply buttons still do nothing

![git_extensions_settings](https://user-images.githubusercontent.com/17702286/202085575-a5a5116d-705c-455c-b218-98b9f5ea914c.gif)

### Steps to reproduce

Open git extensions
Open Tools->Settings
Try to change any settings, click, OK/close/apply, or cloes the settings menu

### Did this work in previous version of GitExtensions?

Yes, worked in all previous versions

**Comment by RussKie** [comment] 2022-11-16 06:40
Duplicate of #10215

**Closed by RussKie** 2022-11-16 06:40 UTC
Labels: :eyeglasses: status: needs review
