### ISSUE TITLE
[NBug] `GitExt Create new repository...` Windows Explorer context menu throws `System.IO.PathTooLongException` exception on 260+ long paths

### ISSUE THREAD

**Issue by andry81** [gitextensions/gitextensions#8681] opened 2020-12-16 17:21 UTC
## Current behaviour

Throws `System.IO.PathTooLongException` exception

## Expected behaviour

Create a repository

## Steps to reproduce

Use `GitExt Create new repository...` Windows Explorer context menu on 260+ long path to create a repository.

## Error Details
```
System.IO.PathTooLongException: Слишком длинный путь или имя файла. Полное имя файла должно содержать меньше 260 знаков, а имя каталога - меньше 248 знаков.
   в System.IO.PathHelper.TryExpandShortFileName()
   в System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   в System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   в System.IO.Path.InternalGetDirectoryName(String path)
   в GitExtensions.Program.GetWorkingDir(String[] args)
   в GitExtensions.Program.RunApplication()
   в GitExtensions.Program.Main()
```

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.24.0.windows.2 (recommended: 2.25.1 or later)
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.3801.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment] 2020-12-16 21:56
Somewhat duplicate of #2372

See discussion from comment: https://github.com/gitextensions/gitextensions/issues/2372#issuecomment-487036603

**Comment by andry81** [comment] 2020-12-17 00:08
> Somewhat duplicate of #2372
> 
> See discussion from comment: [#2372 (comment)](https://github.com/gitextensions/gitextensions/issues/2372#issuecomment-487036603)

The issue was closed w/o a fix.

**Comment by RussKie** [comment] 2020-12-17 00:18
This is a hard limit in Windows. .NET 4.6.2 onwards presumably add support for longer paths, but the app is currently on 4.6.1.

**Closed by RussKie** 2020-12-17 00:18 UTC

**Comment by andry81** [comment] 2020-12-17 00:25
> This is a hard limit in Windows. .NET 4.6.2 onwards presumably add support for longer paths, but the app is currently on 4.6.1.

Why not just to use UNC paths with `\\?\` prefix or msysgit 1.9+?
https://stackoverflow.com/questions/21123415/git-pull-aborted-with-error-filename-too-long/22831095#22831095

**Comment by RussKie** [comment] 2020-12-17 05:48
Why not clone into a shorter path?

**Comment by andry81** [comment] 2020-12-17 09:56
Because things should work as is without annoying manipulations. Especially when a thing could be fixed ages ago and still didn't.

**Comment by RussKie** [comment] 2020-12-17 10:01
Send a pull request in, then we'll talk.

**Comment by pmiossec** [comment] 2020-12-17 10:11
> Because things should work as is without annoying manipulations. Especially when a thing could be fixed ages ago and still didn't.

I think you don't really understand what (your easy to say when you're not involved) remark imply.

>Because things should work as is without annoying manipulations.

Behind this sentence, there are people and trade-offs.

GitExtensions is an opensource project, so the simple reason is that no one judged this bad behavior enough blocking to spend time to fix it. I'm pretty sure you will be the one that will fix it and do the PR.

>Why not just to use UNC paths with \\?\ prefix or msysgit 1.9+?

I'm not sure that's as simple as you say. We have to update all the place where we handle path and be sure every piece of code handle this type of paths (and probably convert in 2 directions the paths)

The other solution is to upgrade to fwk 4.6.2 but here also we have to validate all the application against regressions.

It has been decided (because no one have the time to do all this work) to wait for the migration to .net core that handle natively the long paths.

So feel free also to work on the migration of the application to  .net core.

**Comment by pmiossec** [comment] 2020-12-17 10:13
I also want to add that there are a lot of software that must work as we want and that must be bug free but often no one to work on that.

I really wonder why!?!

**Comment by andry81** [comment] 2020-12-20 17:51
So, does all these means that with the .NET 4.6.2 it can not be fixed at all?

**Comment by gerhardol** [comment] 2020-12-20 19:00
> So, does all these means that with the .NET 4.6.2 it can not be fixed at all?

It means that support will require an update to 4.6.2 and some rewrite and a lot of validation.
Such changes are normally added by someone with enough interest.

**Comment by andry81** [comment] 2020-12-21 11:08
> It means that support will require an update to 4.6.2 and some rewrite and a lot of validation.

I still don't get it. What rewrite? Add '\\?\' as prefix to all absolute paths? For that the 4.6.2 is required?

**Comment by pmiossec** [comment] 2020-12-21 11:20
@andry81 It seems that you are the one that knows more on the subject that us, that needs this fix and that is able to test it easily. 

Instead of ending in never lasting discussion, I think it is easier for us all that you do the (easy) change you think is required, test it and create a pull request.

**Comment by andry81** [comment] 2020-12-21 11:31
> @andry81 It seems that you are the one that knows more on the subject that us, that needs this fix and that is able to test it easily.
> 
> Instead of ending in never lasting discussion, I think it is easier for us all that you do the (easy) change you think is required, test it and create a pull request.

@pmiossec RussKie stated that the 4.6.2 has something what blocks a fix. I just wanted to know what is it. Because fix was existing before the .NET and quite don't get why the .NET update is required to fix things being fixed w/o .NET.

**Comment by pmiossec** [comment] 2020-12-21 12:03
> @pmiossec RussKie stated that the 4.6.2 has something what blocks a fix. I just wanted to know what is it. Because fix was existing before the .NET and quite don't get why the .NET update is required to fix things being fixed w/o .NET.

@RussKie didn't said that something was blocking but that when you upgrade to a different fwk you have a do some costly validation. We decided that it doesn't worth it. But once again you could do that upgrade, build your version. Use it during weeks and give us feedback...

>Because fix was existing before the .NET and quite don't get why the .NET update is required to fix things being fixed w/o .NET.

you're referring to which solution? The `\\?\` prefix?

A quick 5 min test that you could have done show that this prefix is not supported by .net fwk (at least by all the apis).

```cs

        [Test]
        public void TestUnc()
        {
            const string filePath = @"C:\Perso\tmp\unc_file.txt";
            var uncPath = @"\\?\" + filePath;

            File.WriteAllText(filePath, "text");
            Assert.IsTrue(File.Exists(filePath));
            Assert.IsTrue(File.Exists(uncPath)); // => Exception: file not found

            File.Delete(filePath);

            File.WriteAllText(uncPath, "text");
            Assert.IsTrue(File.Exists(uncPath)); // => Exception: Invalid
        }
```

A quick research on stackoverflow seems to confirm that: https://stackoverflow.com/questions/11009013/unc-path-does-not-work-with-net and https://stackoverflow.com/questions/6867463/is-there-a-net-api-to-return-the-equivalent-extended-path-string-of-a-given-pat )

Please, if you want something, do some check before saying it's easy and make others spend time on it....

**Comment by andry81** [comment] 2020-12-21 12:05
> Please, if you want something, do some check before saying it's easy and make others spend time on it....

Yes, it easy in C++ world. Didn't know it is a problem in .NET,
