### ISSUE TITLE
gitexe.cmd pull - always opens dialog window in do not merge, only fetch changes

### ISSUE THREAD

**Issue by dgsydau** [gitextensions/gitextensions#6060] opened 2019-01-08 05:39 UTC
## Current behaviour
Calling gitexe.cmd pull from command line 

In previous versions this would open pull window with same default values as when called from gitexetensions.exe UI. 

For example the default set in the UI is ```Merge remote banch into current branch```.

Since upgrading to v 3.00.00.4433 gitex.cmd always opens the pull window ui with ```Do not merge, only fetch remote changes```.

Even if I include ```--merge``` on the the command line the pull window only every opens with do not merge option.

## Expected behaviour

Merge options should

1.  open with default values if just pull is used on the command line - like previous versions did

2. honor other command line options like --merge

## Steps to reproduce

from the command line run ```gitexe.cmd pull```

## Screenshots

![image](https://user-images.githubusercontent.com/1653544/50811740-df445c00-1363-11e9-9b2a-793627a41a56.png)

![image](https://user-images.githubusercontent.com/1653544/50811639-7361f380-1363-11e9-9948-c6b2b7a0913b.png)

## Did this work in previous version of GitExtensions

yes, in all previous versions this work 

## Environment

- GitExtensions version: 3.00.00.4433
- GIT version: 2.20.0.windows.1
- OS version: Windows 10
- .NET version:  4.7.3260.0

**Comment by SetoKaiba** [comment] 2019-01-16 17:11
I'm not sure whether it's the same problem. The default merge option became **Do not merge, only fetch remote changes** after the upgrade in my case as well. I open the Pull window from context menu of windows explorer.

**Comment by gerhardol** [comment] 2019-01-16 22:10
> I'm not sure whether it's the same problem

Not the same, probably #5879 (fixed in next release)

**Comment by PowerAccess** [comment] 2019-01-20 22:18
This is a critical issue affecting all our team members. Now right click > GitExt Pull simply performs a Git Fetch, without actually merging changes. This affects all existing repositories as well as newly cloned ones, where previously Merge was always the default behavior. This has caused many major issues recently in development due to team members not realizing that recent changes weren't getting merged in, since that was never the case in the past.
How can I workaround this now to set Merge as the default behavior for the Pull dialog when used via shell context menu?  It only is the default now when use Pull/Fetch from Browse > Commands > Pull (however that is almost never used), resulting in very inconsistent behavior. It doesn't even remember the last selected option for these dialogs.

**Comment by PowerAccess** [comment] 2019-01-20 23:58
@vbjay, I tested v3.0.1 pre-release and can confirm it does *not* fix the issue. Right click in File Explorer > GitExt Pull still defaults always to Merge options = "Do not merge". 

Actually it seems like it may be worse now, with Local branch and Remote branch always defaulting to empty and without even a drop-down or auto-complete for Local branch (though manually checking Merge will fill it in and then disable editing of Local branch, but not Remove branch which I have to reenter or reselect every time now).
Also the title of the Pull dialog opened from shell context menu action GitExt Pull shell action is now "Fetch (<folder path>)" instead of "Pull", so seems like the shell context menu action is mapped to the wrong command entirely?

Also, the last selected for "Auto stash" doesn't seem to be preserved either. Is there an option to enable by default? I only see "Automatically stash before doing a rebase" available under Settings > Git > Advanced, which doesn't seem to  by default only available under Settings for Rebase, which fails to be used for this dialog. Shouldn't it be applied here? If not, can you add a separate setting for whether to Auto stash by default for Pull in general or rename that setting to apply to Pull (instead of just Rebase)?

Ideally all settings in this dialog could be persisted by default for the next time the dialog is shown, either globally or for the current repo, with some kind of option in the dialog to select to Remember Options Never | For Repo | Globally.

Also, though I had "Check for updates weekly" and "Check for release candidate versions" both enabled, not only did Git Extensions not show that the Pre-Release version was available, when I checked less than an hour ago before installing, but even when I performed Help > Check for Updates (with release candidate checking enabled) it showed "No updates found".

**Comment by vbjay** [comment] 2019-01-21 00:15
**Pre-Release**   It does mean that we didn't update the notification file that provides which version we have.  We JUST released it.  Holly cow.

**Comment by vbjay** [comment] 2019-01-21 00:35
We turn off autostash in the config ( the command runs git -c... to turn off autostash from config and then only adds --autostash if the checkbox is checked)  

We default it to checked for a reason.  It saves your bacon.  When you do this
![image](https://user-images.githubusercontent.com/3629489/51447244-19114d00-1cea-11e9-8aa2-893bad11ddf2.png)

You don't get the option to set it.  So we force it to be checked.  If you rebased and had changes in the working directory that got overwritten by the rebase process, you would be SOL.  So we 
![image](https://user-images.githubusercontent.com/3629489/51447287-8624e280-1cea-11e9-9a5d-13f60dced6d8.png)

**Comment by vbjay** [comment] 2019-01-21 00:47
In pull are you saying autostash defaults to unchecked?

![image](https://user-images.githubusercontent.com/3629489/51447440-2a5b5900-1cec-11e9-855b-866989ac8463.png)

**Comment by vbjay** [comment] 2019-01-21 00:49
This is what you are looking for

![image](https://user-images.githubusercontent.com/3629489/51447473-87efa580-1cec-11e9-8f39-541735092a2d.png)

**Comment by vbjay** [comment] 2019-01-21 01:01
![image](https://user-images.githubusercontent.com/3629489/51447585-af933d80-1ced-11e9-8a5e-7fe33119c52e.png)
![image](https://user-images.githubusercontent.com/3629489/51447591-be79f000-1ced-11e9-8bc5-5b3800048738.png)


___
![image](https://user-images.githubusercontent.com/3629489/51447628-16185b80-1cee-11e9-862a-00c261a12378.png)


![image](https://user-images.githubusercontent.com/3629489/51447617-ef5a2500-1ced-11e9-878c-f9825087bdce.png)

**Comment by vbjay** [comment] 2019-01-21 01:05
'''c#
 case "pull":        // [--rebase] [--merge] [--fetch] [--quiet] [--remotebranch name]
                    Pull(arguments);
                    return;
```

**Comment by vbjay** [comment] 2019-01-21 01:13
Hopefully that covers all your issues.  Let me know if it doesn't.

**Comment by vbjay** [comment] 2019-01-21 01:20
I see your problem with the autostash.  

```c#
    var commands = new GitUICommands(GetWorkingDir(args));

            if (args.Length <= 1)
            {
                commands.StartBrowseDialog();
            }
            else
            {
                // if we are here args.Length > 1
                commands.RunCommand(args);
            }

            AppSettings.SaveSettings(); // Right here.  If we run a command we shouldn't save settings.  
        }
```

**Comment by vbjay** [comment] 2019-01-21 01:36
- Close all GE processes.  
- Open up %appdata%\\GitExtensions\GitExtensions\GitExtensions.settings
- Look for 
```xml
<key>
      <string>autostash</string>
    </key>
    <value>
      <string>true</string>
    </value>
```
- Make sure it is true

Double check repo you are in for the same thing.

**Comment by PowerAccess** [comment] 2019-01-21 04:33
I was wanting autostash to be enabled by default, but it was disabled. I checked GitExtensions.settings like you suggested and saw that autostash = false there, which seems to fix so that its enabled by default again. Any idea how it ended up as false in settings? I'd never edited that config and don't recall ever disabling under settings UI etc.  

You mentioned confirm the GitExtensions.settings fix is applied for my repo as well? Where would I check for that? I have only one GitExtensions.settings file on my entire system. Where are repo-specific settings overrides saved to?

**Comment by PowerAccess** [comment] 2019-01-21 04:36
As to the "Set Default Pull button action" setting, I had previously (today, before my first comment regarding this issue) confirmed that I had "Pull - Merge" set under the Git Extension Browse dialog like shown in your screenshot, for both 3.0.0 and 3.0.1 and that clicking the Pull toolbar button correctly performed Pull - Merge.  However, despite that, the GitExt Pull performed via shell context menu (for Windows 10 Pro x64) always failed to default to anything except "Do not merge". 

I believe I tried changing to something else and then back again but still failed to work, with GitExt Pull always defaulting to "Do not merge", for both v3.0.0 and v3.0.1.  

I had just uninstalled 3.0.1 and then installed 2.51.05 again, and whatever install of 3.0.0 had broken  (and which remained broken when updated to 3.0.1) remained broken after uninstall and then installing 2.51.05, because the Pull dialog for 2.51.05 then started defaulting to "Do not merge" as well (despite previously working before update to v3.0.0). I then used "Set the next selection as default" then clicked Pull - Merge from the Git Browse dialog toolbar, and then closed that and did GitExt Pull from shell context menu and it finally restored the expected behavior of defaulting to Merge instead of Do not merge. 

Therefore it seems like the install of 3.0.0 may have broken something so that even updating from 3.0.0 to 3.0.1 failed to default to anything except Do not merge despite having Pull - Merge set in Browse dialog UI and working as expected when clicking the Pull toolbar button. Is that possible some settings file? Where is default pull button action saved to (I didn't see any related merge or pull setting in GitExtensions.settings)?

**Comment by vbjay** [comment] 2019-01-21 04:58
Did yiu notice the code that I showed when you call gitext.cmd pull?  Did
you see the arguments that are available?

On Sun, Jan 20, 2019, 11:36 PM Dan Moorehead | PowerAccess
(PowerAccess.net) | PowerGit | PowerSQL for Microsoft Access <

**Comment by PowerAccess** [comment] 2019-01-21 11:47
I did, but I'm not sure how that's relevant. I'm not using via command line, I'm using via shell context menu as I've always used it. In 3.x, right clicking on a folder > GitExt Pull is broken and incorrectly shows "Fetch" as the dialog title and defaults to "Do not merge" for behavior and there is no way to fix or workaround that, it appears, and it seems to certainly be a bug since the default Pull behavior when using via toolbar in Git Browse respects the default action selected and the shell context menu, inconsistently, fails to do so. And all of this worked fine before and is broken now since 3.x. The only workaround, which you seem to be alluding to with the code you posted, is to use command line, which defeats the whole point of Git Extensions and ensures that it makes far more sense to use it v2.x or TortoiseGit instead at that point until this critical issue is fixed.  

Even worse, is that this is entirely unexpected that right click > Pull acts like Fetch instead, and breaking behavior from 2.x and inconsistent with Pull fro within Git Browse, and therefore it had caused all team members to believe that changes were being pulled and merged when in fact they were not, without any warning otherwise or clear indication that this behavior had changed.

Therefore can you please release a fix for this ASAP? Once available, I can try upgrading back to 3.x again.

**Comment by vbjay** [comment] 2019-01-21 12:34
The shell extension starts GE passing in the right args based on the menu
chosen. It's the same thing as gitext.cmd.

**Comment by SetoKaiba** [comment] 2019-01-21 12:50
I updated 3.0.1 the pull from context menu is always do not merge, only fetch remote changes

**Comment by PowerAccess** [comment] 2019-01-21 21:55
@SetoKaiba,
Do you mean you have fixed this in recent commit but not yet available in pre-releases? If so, can you publish a release with the fix?  

@SetoKaiba and @vbjay,

Like @dgsydau and myself have both confirmed, 3.0.1 failed to fix the issue with Pull dialog shown from shell context menu always performing Do not merge, with no workaround or way to change that, and with it failing to use the last selected option (in that dialog or via Browse toolbar's Pull button menu options).

I'm not sure if related to some kind of settings, registry or file corruption caused by 3.0.0 which I installed prior to that though, because even after I uninstalled 3.0.1 and went back to last 2.x version the issue with Git Pull from shell context menu always doing "Do not merge" remained even with 2.x after that, until I manually set the Default pull action via Git Browse dialog Pull toolbar button menu to Merge, after which it worked, but, again, only for 2.x.  Even after ensuring I set the default pull action to Merge via Browse toolbar button drop-down menu for 3.0.1 it only ever worked correctly when showing the Pull dialog from that Browse toolbar button, not shell context menu.

**Comment by PowerAccess** [comment] 2019-01-21 21:57
@vbjay, you had said:
> "The shell extension starts GE passing in the right args based on the menu chose"
However, that doesn't seem to be true. 
Or, at least, whatever is happening under the hood, both myself and @dgsydau have confirmed that 3.0.1 fails to fix the issue, like detailed further above.

Like I've described several times now, in all cases Pull dialog shown via shell context menu always still results in "Do not merge". Even if I manually select Merge there and press OK, and even if I set Merge as default option in the Browse dialog's Pull toolbar button menu, the next time I launch Pull dialog from shell context menu it *always* still *only* ever defaults to *Do not merge* even with 3.0.1. Only when I click on the Pull button in Browse dialog toolbar does it work correctly, defaulting to Merge every time instead.

**Comment by vbjay** [comment] 2019-01-21 21:58
That's because the setting was changed by running 3.0. We altered default
pull logic in 3.0.

**Comment by vbjay** [comment] 2019-01-21 21:59
Did you not see the issues I created in response to what was said here?  Follow the links.

**Comment by vbjay** [comment] 2019-01-21 22:37
I'm not talking about defaults in that statement. I'm saying the dialog is open and you can change it to merge or other option. It's not like you are prevented from preforming the action desired. The discussion amongst our members will decide if if this is an issue that needs fixing. 

Another point. You are quite welcome to dig in and make it right.

**Comment by PowerAccess** [comment] 2019-01-22 03:02
Please see my reply to #6144 regarding this, together with [summary of suggested changes (at minimum) and reasons for them](https://github.com/gitextensions/gitextensions/issues/6144#issuecomment-456252272), which others, like with my suggestions and reports of this being a critical bug above, it seems agree are a priority.

**Closed** 2019-02-16 02:03 UTC
Labels: status: needs review

**Comment by dgsydau** [comment] 2019-02-16 22:01
@RussKie  - confirming, pre relase 3.02 fixes my original issue. thank you :)

**Comment by RussKie** [comment] 2019-02-17 04:23
Thank you for confirming it.
It will be official and public shortly
