### ISSUE TITLE
System.Exception "Remote URLs should appear in pairs." on startup

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6381] opened 2019-03-18 20:26 UTC
## Current behaviour

exception on startup (see title)
always reproducible on some machines (during the past few weeks)
The exception can be ignored by Alt+F4.

## Expected behaviour

no exception

## Steps to reproduce

don't know

## Did this work in previous version of GitExtensions

yes, 3.0.0.4433

## Environment

- GitExtensions version: master
- GIT version: 2.21.2
- OS version: Win 7 and Win 10
- .NET version: not checked

## Diagnostics

```
System.Collections.Generic.IReadOnlyList`1[GitCommands.Remote] <GetRemotes>g__ParseRemotes|154_0(System.Collections.Generic.IEnumerable`1[System.String]) @ GitCommands.GitModule

   at GitCommands.GitModule.<GetRemotes>g__ParseRemotes|154_0(IEnumerable`1 lines) in F:\Build\gitextensions\GitCommands\Git\GitModule.cs:line 2188
   at GitCommands.GitModule.GetRemotes() in F:\Build\gitextensions\GitCommands\Git\GitModule.cs:line 2164
   at GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync>d__4.MoveNext() in F:\Build\gitextensions\GitUI\BranchTreePanel\RepoObjectsTree.Nodes.Remotes.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__27.MoveNext() in F:\Build\gitextensions\GitUI\BranchTreePanel\RepoObjectsTree.Nodes.cs:line 220
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass69_0.<<AddTree>b__1>d.MoveNext() in F:\Build\gitextensions\GitUI\BranchTreePanel\RepoObjectsTree.cs:line 310
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext() in F:\Build\gitextensions\GitExtUtils\GitUI\ThreadHelper.cs:line 101
```

HResult -2146233088

**Comment by RussKie** [comment] 2019-03-18 21:22
The exception is originated here:
https://github.com/gitextensions/gitextensions/blob/d0ba1a57823f12cc1caec12026586bb9353d2771/GitCommands/Git/GitModule.cs#L2162-L2189

Can you post results of `git remote -v` from problematic workstations?

**Comment by RussKie** [comment] 2019-03-18 21:23
Duplicate of #6093

**Comment by RussKie** [comment] 2019-03-18 21:23
The discussion is to be continued in #6093

**Closed by RussKie** 2019-03-18 21:23 UTC

**Comment by mstv** [comment] 2019-03-18 21:34
GitHub's matching algorithm has left room for improvements as well as my searching.
