### ISSUE TITLE
View keeps switching to filtered branches

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#4486] opened 2018-02-14 17:42 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The Main repository explorer window keeps switching to only "Show filtered branches"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Not sure how to describe this properly.

When I first go to a repository, quite often, the actual selected branch isn't even shown.
So I right click and select View -> Show All Branches.
Do whatever I need to do and as soon as I do a branch operation, like switch branch, delete a branch etc, the view is back on "Show filtered branches".

This is a pretty annoying and persistent bug.

![](https://snag.gy/k3wtF9.jpg)

**What is the expected behavior?**

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.14.1
- OS version: Windows 7

**Did this work in previous version of GitExtensions (which)?**

Yes. I noticed it as soon as I upgraded from 2.50.2 to 2.51.0

**Comment by jrfnl** [comment] 2018-02-14 18:20
Additional info: the bug appears to be most notable when the repo uses a non-master branch as the default, i.e. a repo with for instance, `master` and `develop` as the main branches.

**Comment by jrfnl** [comment] 2018-02-14 18:25
Oh and I noticed some other issues to do with branch names. Just in case, this is related, most of the branches in the repos follow the following naming convention: `feature/123-description`

**Comment by gerhardol** [comment] 2018-02-14 23:07
I cannot reproduce with a similar setup.
May have to be investigated with a debugger for someone that can reproduce

**Comment by jrfnl** [comment] 2018-02-14 23:33
I'd be happy to provide as much debug info as I can, but will need some help on how to get to this info.

**Comment by vbjay** [comment] 2018-02-14 23:58
Cloan repo. Check out https://github.com/gitextensions/gitextensions/tree/release/2.51 branch. Update submodules. Debug and see if problem occurs.  Then checkout master and update submodules. Debug again. See if problem occurs. If it does then use git bisect between the release branch and a previous release branch. If not, then the problem has already been fixed.

**Comment by jrfnl** [comment] 2018-02-15 00:11
@vbjay I'm one of those users who only ever used the msi install. How do I even start up the program from a clone of the repo ?
Sorry, PHP dev, I haven't got a clue how to work with C# files.

**Comment by vbjay** [comment] 2018-02-15 00:18
Install https://www.visualstudio.com/vs/community/

https://github.com/gitextensions/gitextensions/wiki/Build-Instructions

**Comment by jrfnl** [comment] 2018-02-15 00:22
@vbjay Thanks. I'll have a try on my secondary machine tomorrow. Not looking to make my main workstation upstable.

**Comment by RussKie** [comment] 2018-02-15 00:59
Does it happen for all repos or only selected on?

I suppose you can start with removing/renaming your main gitextensions.config (C:\Users\<user name>\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings)
Also if your repo has its own GitExtensions.settings or .git\GitExtensions.settings - remove/rename them too

**Comment by RussKie** [comment] 2019-01-07 08:01
Closing due to age and lack of follow up.

**Closed by RussKie** 2019-01-07 08:01 UTC
Labels: status: more info requested
