### ISSUE TITLE
Line spacing too small on 4K screen

### ISSUE THREAD

**Issue by marktilleytlc** [gitextensions/gitextensions#4574] opened 2018-03-05 18:51 UTC
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
Lines are squashed together, cropping half of the text.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
It happens on many screens, such as the commit history and the example attached here.

**What is the expected behavior?**
Should space lines appropriately.

**Environment you encounter the issue:**
Dell XPS-15. Windows 10. 4K display.

- GitExtensions version: 2.51
- GIT version: 2.14.1.1
- OS version: Windows 10 Pro 1709

**Did this work in previous version of GitExtensions (which)?**
2.49.03

![image](https://user-images.githubusercontent.com/14178024/36993535-0408544e-20a6-11e8-8223-6b9bb6f13ce6.png)

**Comment by gerhardol** [comment] 2018-03-05 19:13
Duplicate of #4544 (and others)

**Closed by gerhardol** 2018-03-05 19:13 UTC
