### ISSUE TITLE
WSL2 repositories with context menu are not always recognized

### ISSUE THREAD

**Issue by tbennun** [gitextensions/gitextensions#10379] opened 2022-11-11 07:54 UTC
### Environment

- GitExtensions version: 4.0.0.15569
- GIT version: 2.38.1.windows.1
- OS version: Microsoft Windows NT 10.0.22000.0
- .NET version:  .NET 6.0.11

### Issue description

When using the context menu to open a WSL folder, Windows (11 I'm assuming) uses the following path:
```
\\wsl.localhost\Ubuntu-20.04\home\...
```

In this case, git is set up to use the Windows git.exe in remote mode, which fails as follows:
![image](https://user-images.githubusercontent.com/8348955/201292150-ef36d7a2-cca3-4fdc-bb72-f2dc3f921457.png)

This does not occur if I manually enter the prompt with `\\wsl$\Ubuntu-20.04\...`, but the context menu of Windows prefers the other one for some reason.

### Steps to reproduce

- Browse to WSL folder in Windows Explorer
- Right click on existing repository folder -> "Show more options" -> "GitExt Open repository"
- GitExtensions opens with a blank repo:
![image](https://user-images.githubusercontent.com/8348955/201292735-e22f0887-8db5-4d3f-b061-883c24ba595c.png)

### Did this work in previous version of GitExtensions?

GitExtensions pre-WSL-git versions (3.2-3.5?) did not have this issue, despite using the same exact path. I am not sure what happened.

**Comment by gerhardol** [comment] 2022-11-11 13:27
"\\wsl$" is using WSL git
"\\wsl.localhost" is handled as any Windows path.
So WSL Git is not related.

**Comment by tbennun** [comment] 2022-11-12 05:12
Unfortunately, on Windows 11 and WSL2, this is the default path used by Windows Explorer for WSL folders, so there should be some special case handling or it doesn't work by default.

**Comment by gerhardol** [comment] 2022-11-12 16:49
WSL Git is still somehow experimental. For instance wsl access itself raises error that cannot be handled by GE, see #10025 or #10173.
So there will be some quirks.
In addition, I do not have Win11 myself and will not implement \\wsl.localhost blindly.

Anyway, this issue was raised for "Windows Git" access to WSL paths. The issue is caused by a security change in Git 2.35, requiring you to explicitly enable access to these drives.
Run a command in the CLI (prefably the Git tab to ensure the home directory is the same) and you will see a message like:

```
$ git status                                                                                              
fatal: detected dubious ownership in repository at '//wsl$/Ubuntu-20.04/home/user/gitextensions'          
To add an exception for this directory, call:                                                             
                                                                                                          
        git config --global --add safe.directory '%(prefix)///wsl$/Ubuntu-20.04/home/user/gitextensions'  
```

In GE 4.0 Git errors generally create popups, not done here for an unknown reason, you will then get info similar to the command line.
(This should be raised here too.)
Most users quickly dismisses the first message and report this as an error on GE though, not so positive from a support perspective...

**Comment by gerhardol** [comment] 2022-11-20 10:22
Duplicate of https://github.com/gitextensions/gitextensions/issues/9954#issuecomment-1321090256

To handle `wsl.localhost` is not planned right now.

**Closed by gerhardol** 2022-11-20 10:22 UTC
Labels: type: git issue

**Comment by gerhardol** [comment] 2022-11-23 22:55
> If you'd like, I can make a PR.

Of course
There is a PR to handle the Git error differently in https://github.com/gitextensions/gitextensions/pull/10436
