### ISSUE TITLE
Transparent selection in Commit window (Window 7 not aero)

### ISSUE THREAD

**Issue by intelartificial** [gitextensions/gitextensions#6053] opened 2019-01-07 14:43 UTC
Expected behavior :
In the commit window, selecting one or more files to stage or unstage should change the background to make which files were selected.

Current behavior :
On Window 7 with basic style, the selected background color is transparent making impossible to know which files were selected. 

In the picture, the file is selected.
![sytle](https://user-images.githubusercontent.com/19225316/50774148-b5eed780-1260-11e9-8911-08b0b901632d.png)

Steps to reproduce
Opening the commit window on computer running Window 7 with the basic style (or Window Classic style). In my case, I cannot active Aero or advance style since I have to run from Virtual Computer and advance style were disabled without any way to re-enabled them.

## Did this work in previous version of GitExtensions

It use to work in [Version 2.51.01] (11 Mar 2018).

## Environment

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3221.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-01-07 19:01
Duplicate of #5499

**Closed** 2019-01-07 19:01 UTC
