### ISSUE TITLE
Select multiple branches for deletion

### ISSUE THREAD

**Issue by lucas-foreflight** [gitextensions/gitextensions#10207] opened 2022-09-26 10:28 UTC
### Feature description

When working on large projects with multiple contributors the flood of branches quickly becomes difficult to manage.
I find it lacking that I cannot select multiple branches and delete them all at once.
Request is to implement shift and ctrl select and allow deletion of multiple branches at once.

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4515.0
- DPI 120dpi (125% scaling)

**Comment by pmiossec** [comment] 2022-09-26 12:20
If it's just about the fact to be able to delete multiple branches at the same time, you could already do it from the delete form:

![image](https://user-images.githubusercontent.com/460196/192271357-53e88aad-0eb2-4ef1-91d3-09c1f9e9cf72.png)

If it's about having an easier way to selected multiple branches, an early draft PR has been done to support that #9412
But work on this PR will maybe resume after v4 is released because all the team focus is on it.
Since v3.5.4, multi-selection in the side panel has been implemented (in #9723) so maybe delete from it could be considered also...

If you want to see this feature appear quickly, a contribution to the PR could help a lot...

As a reminder, the "Delete obsolete branches" could help also to achieve what you want.

**Comment by pmiossec** [comment] 2022-09-26 12:25
Closing as duplicate of #6180 (where there is already a discussion)

**Closed by pmiossec** 2022-09-26 12:25 UTC
Labels: type: feature request

**Comment by RussKie** [comment] 2022-10-11 07:12
The branch deletion dialog provides functionality to select and delete
multiple branches.
