### ISSUE TITLE
Github Personal Access token access doesn't work

### ISSUE THREAD

**Issue by vocko** [gitextensions/gitextensions#9502] opened 2021-08-14 06:25 UTC
## Current behaviour

Doing any operation towards a private GitHub repository results in the following message:

remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: unable to access 'https://github.com/***.git/': The requested URL returned error: 403

## Expected behaviour

I'm using the GitHub plugin, generated the personal access token and saved it in the Settings/Plugins/GitHub menu. However, it doesn't seem to be used at all. Any advice how to correctly configure GitHub access will be highly appreciated.

## Did this work in previous version of GitExtensions

Not sure, I was convinced it was using the token, but doesn't seem it was.

## Environment

- Git Extensions 3.5.2.12435
- Build 77413699a9c25b160a6a622311529372b5d87f5b
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4400.0

**Comment by vbjay** [comment] 2021-08-14 11:17
So create a pat and put it in the settings of the plugin.

**Comment by vbjay** [comment] 2021-08-14 11:19
Also go to remote settings. Use ssh instead of https.

**Comment by pmiossec** [comment] 2021-08-14 11:40
> I'm using the GitHub plugin, generated the personal access token and saved it in the Settings/Plugins/GitHub menu. However, it doesn't seem to be used at all. Any advice how to correctly configure GitHub access will be highly appreciated.

The token in this setting is only used for the Apis calls that GitExtensions could do when using the github features (PRs, fork,...)

Here your problem is that github removed the access with a password to the repository (do not confuse with Apis).

So, what you have to do is to remove the entry in the 'credential manager' in windows so that git ask you for a new credential. And you will have to provide a PAT because a password, as you read in the error message, is no more accepted.

**Comment by vocko** [comment] 2021-08-14 12:16
> 
> 
> > I'm using the GitHub plugin, generated the personal access token and saved it in the Settings/Plugins/GitHub menu. However, it doesn't seem to be used at all. Any advice how to correctly configure GitHub access will be highly appreciated.
> 
> The token in this setting is only used for the Apis calls that GitExtensions could do when using the github features (PRs, fork,...)
> 
> Here your problem is that github removed the access with a password to the repository, i.e fetch, pull, push and clone commands (do not confuse with Apis calls).
> 
> So, what you have to do is to remove the entry in the 'credential manager' in windows so that git ask you for a new credential. And you will have to provide a PAT because a password, as you read in the error message, is no more accepted.

Excellent, this worked. I suggest this answer should be highlighted somewhere in the documentation as I suppose more people will now have the same problem and I could not find this explanation anywhere.

Thank you very much @pmiossec

**Comment by pmiossec** [comment] 2021-08-14 15:23
> I suggest this answer should be highlighted somewhere in the documentation as I suppose more people will now have the same problem and I could not find this explanation anywhere.

Maybe, yes. I think that is something that you could contribute as documentation is open-source.

2 others things that could help:

* adding a title line in plug-ins settings to explain what the plug-in is doing and here explaining that this token is only for Github related features (but that will make a change in the plug-in interface) 
* having a link in the 'manage remotes' form toward the 'Credential manager'

**Comment by vocko** [comment] 2021-08-16 11:37
> 
> 
> > I suggest this answer should be highlighted somewhere in the documentation as I suppose more people will now have the same problem and I could not find this explanation anywhere.
> 
> Maybe, yes. I think that is something that you could contribute as documentation is open-source.
> 
> 2 others things that could help:
> 
>     * adding a title line in plug-ins settings to explain what the plug-in is doing and here explaining that this token is only for Github related features (but that will make a change in the plug-in interface)
> 
>     * having a link in the 'manage remotes' form toward the 'Credential manager'

I'm happy to do that, just need to get my head around how to write the documentation. Don't have much experience with it and don't want to be contra-productive.

**Comment by RussKie** [comment] 2021-08-16 11:40
> Don't have much experience with it and don't want to be contra-productive.

Imagine you're writing it for yourself-3-days-ago :)
The docs live here: https://github.com/gitextensions/GitExtensionsDoc

**Comment by montoner0** [comment] 2021-09-06 21:51
My two cents: tried to use PAT today and faced that I need to restart GE to make it work. Otherwise I was getting an error `no authentication details` on `My repositories` tab.

**Comment by laurin1** [comment] 2022-03-21 14:16
@montoner0

Ok, so that helped, I was able to see my repos on the ```My repositories``` tab, but I still can't clone any of them.

![image](https://user-images.githubusercontent.com/75857/159280280-a826e739-c5b3-4b1e-a94c-28e836fc4804.png)

**Comment by MarleyDisguise** [comment] 2023-02-17 16:57
> My two cents: tried to use PAT today and faced that I need to restart GE to make it work. Otherwise I was getting an error `no authentication details` on `My repositories` tab.

This is exactly what I was missing. I just needed to restart GitExtensions.

**Comment by RussKie** [comment] 2023-04-21 02:39
Closing as I believe the issue is resolved.

**Closed by RussKie** 2023-04-21 02:39 UTC
