### ISSUE TITLE
shell extension... Creat new repository broken

### ISSUE THREAD

**Issue by keystoneclimber** [gitextensions/gitextensions#2766] opened 2015-04-03 16:35 UTC
The shell extension GitExt Creat new repository... command is broken in 2.48.03  When clicked it shows a dialog for Commandline usage and fails to initialize the repo.

![screenshot027](https://cloud.githubusercontent.com/assets/1234508/6985126/dd265444-d9fd-11e4-8ca4-d20dab9aabda.png)

**Comment by Radrik5** [comment] 2015-04-03 18:42
Duplicate of #2564

**Comment by ASalazarMX** [comment] 2015-05-06 18:27
This is a minor annoyance for people who know git on the command line, but many newcomers don't. It must be discouraging to have repository creation broken, as one usually starts with that.

I wonder how many have chosen another GUI in the 5 months this minor bug has remained.

**Comment by keystoneclimber** [comment] 2015-05-06 19:18
Seriously.  If you know command line git, why would you be installing
gitextensions in the first place?  I've been using gitextensions for a long
time and it always amazes me how many things are BROKEN with a new version
release!

**Comment by ASalazarMX** [comment] 2015-05-07 02:38
Maybe the release cycle should be shorter. There would be less breaking changes, and hopefully bugs wouldn't stay months in the stable build.

This is my second version change, and I really think GitExtensions is amazingly useful, but I was tempted to downgrade just because of this bug.

**Comment by Radrik5** [comment] 2015-05-07 08:39
I don't know why release cycle is so but you can easily build your own Git Extensions. The fix was merged to master on 15 Dec 2014. Just run BuildInstallers.VS2012.cmd or BuildInstallers.VS2013.cmd from the Setup folder and you'll get two MSI installer with the most recent version.

**Comment by ASalazarMX** [comment] 2015-05-08 02:47
I would not consider a version built from source as production-ready, that's what official releases are for.

Yes, you can clone the official release commit and just apply the patch that fixes the typo, but if we're doing workarounds, it's even easier to type git [--bare] init instead.

**Comment by keystoneclimber** [comment] 2015-05-08 16:28
"it's even easier to type git [--bare] init instead"  This kind of reply
always cracks me up.  So basically, you're saying that the workaround for
the buggy, malfunctioning git GUI is to not use the GUI?

**Comment by ASalazarMX** [comment] 2015-05-08 20:26
Now you're thinking with portals!

Seriously, I like GitExtensions a lot, so I'm willing to work around it the few times I have to.
For this particular bug, you can also open the Git Browser and create the repository from the menu, IIRC, that works fine.

**Comment by KindDragon** [comment] 2015-05-12 12:56
This should be fixed in 2.48.04

**Closed by KindDragon** 2015-05-12 12:56 UTC
