### ISSUE TITLE
Installation hyperlinks opening in Internet Explorer

### ISSUE THREAD

**Issue by davelogear** [gitextensions/gitextensions#4880] opened 2018-04-25 16:22 UTC
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** Clicking a hyperlink in any of the installation screens opens them in a minimalized Internet Explorer pop-up (meaning no menu bar as it normally has), even though my OS default browser is Chrome.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** I don't know if it's a bug or intentional, but you can see for yourself by just installing the latest Git Extensions Complete in Windows 7 and clicking any of the hyperlinks, like the symbolic links hyperlink which opens to https://github.com/git-for-windows/git/wiki/Symbolic-Links

It appears the Git Extensions install is configured to open Internet Explorer for hyperlinks... I'm not finding anything to fix in Windows yet. In the last screenshot, Internet Explorer has a .url checkbox, but Chrome does not.

**What is the expected behavior?** Open hyperlinks in the OS default browser.

**Environment you encounter the issue:**

- GitExtensions version: GitExtensions-2.51.01-SetupComplete.msi
- GIT version: whatever version of git comes with it
- OS version: Windows 7 Professional (fully up to date)

**Did this work in previous version of GitExtensions (which)?** Never noticed or clicked the hyperlinks before. I click them to try to better understand what I'm installing, and I rarely use Internet Explorer, and even then I'd like it to be on demand, not as a default.

![image](https://user-images.githubusercontent.com/32692076/39258957-7f66445e-4872-11e8-9f4f-35119558fa0e.png)

![image](https://user-images.githubusercontent.com/32692076/39259078-cdc71a92-4872-11e8-9028-683d6d7423ba.png)

![image](https://user-images.githubusercontent.com/32692076/39259164-f8d6a054-4872-11e8-8b71-aa5587a1975b.png)

**Comment by vbjay** [comment] 2018-04-25 17:25
We should use process.start(url) and not Iexplorer process with a
commandline arg of the url.

**Comment by RussKie** [comment] 2018-04-25 22:59
@davelogear Could you please clarify which hyperlinks you're referring to? Some screenshots will help

**Comment by LeonardAB** [comment] 2018-11-29 04:04
I found that this behavior causes another problem, in particular the github plugin.
When I tried to setup the github plugin in git ext (which then git ext open an IE pop-up to open github login box), github (on that pop up) says **"Please note that GitHub no longer supports Internet Explorer."**

There is a button on that login box that does not work, which I suspect is caused by being inside IE.
![git](https://user-images.githubusercontent.com/14308605/49198588-2dfeed80-f3d7-11e8-9527-9bf48ce7438e.JPG)

**Comment by vbjay** [comment] 2018-11-29 22:29
My suggestion is for internal use cefsharp which uses chromnium. For
external just make sure it's a process.start(url) and not
process.start(iexplorer.exe ...).

**Comment by gerhardol** [comment] 2018-11-29 22:34
There are no direct references to iexplore in GE, so this issue is about links that should be opened externally and not in the embedded browser. Which?

For #4800, discussion should be done there.

**Comment by vbjay** [comment] 2018-11-29 22:41
https://www.bleepingcomputer.com/news/microsoft/erratic-windows-10-bug-breaks-changing-of-default-file-associations/

**Comment by gerhardol** [comment] 2018-11-29 22:58
> https://www.bleepingcomputer.com/news/microsoft/erratic-windows-10-bug-breaks-changing-of-default-file-associations/

Could be.

However, I find no hyperlinks in the installer now. The links to Git were removed in 2.51.02.

I recommend this issue to be closed.

**Comment by vbjay** [comment] 2018-11-29 23:03
:+1 didn't notice the version. Good point. Close it.

**Closed** 2018-11-29 23:11 UTC
Labels: status: more info requested, status: needs review

**Comment by knoepdan** [comment] 2019-11-05 20:30
Closed? How can I integrate Github on Windows 10? I have the same problem as LeonardAB.

**Comment by pmiossec** [comment] 2019-11-05 20:42
@knoepdan This part is fixed in development branch and will be shipped with the next release.
