### ISSUE TITLE
[NBug] Value must not be null. - Exception when right click on "File Tree" on an empty repo

### ISSUE THREAD

**Issue by ventilator** [gitextensions/gitextensions#10773] opened 2023-02-26 12:37 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.14
- DPI 96dpi (no scaling)

### Issue description

```
System.Exception: Value must not be null.
   at Microsoft.Validates.Fail(String message)
   at GitUI.CommandsDialogs.RevisionFileTreeControl.FileTreeContextMenu_Opening(Object sender, CancelEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnOpening(CancelEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ContextMenuStrip.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Control control, Point position)
   at System.Windows.Forms.Control.WmContextMenu(Message& m, Control sourceControl)
   at System.Windows.Forms.Control.WmContextMenu(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

Clone an empty repository, switch to "File Tree" View and right click. Exception occurs
![image](https://user-images.githubusercontent.com/4276067/221410901-fbcce115-d912-4a50-9ee2-78c03fc643e1.png)

Expected result: Context Menu should appear to show various options

### Did this work in previous version of GitExtensions?

no

**Comment by gerhardol** [comment] 2023-02-26 17:07
Duplicate of #10666
Fixed in #10684

**Closed by gerhardol** 2023-02-26 17:07 UTC
Labels: :eyeglasses: status: needs review
