### ISSUE TITLE
The folder path 'My Documents' contains an invalid character

### ISSUE THREAD

**Issue by dlidstrom** [gitextensions/gitextensions#2622] opened 2015-01-19 07:36 UTC
I was upgrading when this happened.
![error](https://cloud.githubusercontent.com/assets/371713/5797212/3b6b536a-9fb6-11e4-86c6-00e31618c846.PNG)

**Comment by KindDragon** [comment] 2015-01-27 09:41
Duplicate of #2439

**Closed by KindDragon** 2015-01-27 09:41 UTC
Labels: bug, installer
