### ISSUE TITLE
[NBug] git checkout-index:  is not in the cache

### ISSUE THREAD

**Issue by LCHMetalex** [gitextensions/gitextensions#10892] opened 2023-04-18 08:19 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.16
- DPI 96dpi (no scaling)

### Issue description

```
GitExtUtils.ExternalOperationException: git checkout-index:  is not in the cache ---> System.Exception: git checkout-index:  is not in the cache

   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.ResetFile(String file)
   at GitUI.GitUICommands.StartResetChangesDialog(String fileName)
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments)
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

tried to do a reset

### Steps to reproduce

right click and reset file changes

**Comment by gerhardol** [comment] 2023-04-18 08:49
If it is a renamed file it was changed in #10853 
If it was a file with conflicts in the contents it was changed in #10423 
Both are in upcoming 4.1

If it was a conflict with added or removed it is a duplicate of #10470
stage/unstage the file before reset

**Comment by RussKie** [comment] 2023-04-18 11:39
I've been observing the same issue in (one of the latest) 4.1 today, though
I haven't captured any details. So it's quite possible we still have a real
issue.

**Comment by gerhardol** [comment] 2023-04-18 12:12
> I've been observing the same issue in (one of the latest) 4.1 today, though I haven't captured any details. So it's quite possible we still have a real issue.

Before 4.0, Git errors were silently ignored. Reset of files need special handling per type, not all cases were handled.
4.1 handles some common scenarios, some situations that require data structure changes for conflicted files with added/removed files are not handled still.

But the precise scenario need to be described to add another issue to vNext (or set this as a duplicate).

**Closed** 2023-05-09 19:00 UTC
Labels: :zzz: status: no recent activity, :mailbox_with_no_mail: needs: author feedback
