### ISSUE TITLE
Commit window missing selections of files

### ISSUE THREAD

**Issue by piccontroller** [gitextensions/gitextensions#6575] opened 2019-05-16 07:37 UTC
## Current behaviour

The list of added or changed files does not have visual selection. All items are the same view.

## Expected behaviour
Selected file is highlighted with some color.

## Steps to reproduce
Add or change some files. Press commit button.  Click to any file into list  of modufied files. No visual selection. But file is selected.

## Screenshots

![image](https://user-images.githubusercontent.com/42399666/57903210-3cfb2e80-7897-11e9-95a0-432ea52f81ce.png)
On screenshot you can see file "test1.txt" is selected but selection is missing.

## Environment

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3062.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2019-05-16 08:20
Please fill in all required information and ping back to re-open the ticket.

**Comment by piccontroller** [comment] 2019-05-17 04:36
All info provided. Please reopen issue.

**Comment by RussKie** [comment] 2019-05-17 05:32
Duplicate of #5499

**Closed by RussKie** 2019-05-17 05:32 UTC
