### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Net.Mail, Version=6...

### ISSUE THREAD

**Issue by OzBob** [gitextensions/gitextensions#10874] opened 2023-04-12 06:40 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.15
- DPI 120dpi (125% scaling)

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Mail, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Net.Mail, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at GitCommands.GitModule.GetRebasePatchFiles()
   at GitUI.PatchGrid.GetPatches()
   at GitUI.PatchGrid.Initialize()
   at GitUI.PatchGrid.OnRuntimeLoad()
   at ResourceManager.GitExtensionsControl.OnLoad(EventArgs e)
   at System.Windows.Forms.UserControl.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

check out branch X
right click main
choose rebase on current branch
Yes to re-write history
then this error
Quite GitExtensions
Repeat process, 
All OK.

I understand this was an intermitent error, but it's in the Issues history if someone else finds the same problem.

**Comment by gerhardol** [comment] 2023-04-12 19:08
Duplicate of https://github.com/gitextensions/gitextensions/issues/10368
Duplicate of https://github.com/gitextensions/gitextensions/issues/10624

This error seem to occur related to Windows and/or .NET updates and seem to be resolved by app or possible PC restarts.
Not sure if this can be detected, this has occurred a number of times.

Similar issues can occur if a portable installation is updated by overwriting the with new version.
You can copy the settings though from old to new.

**Closed by gerhardol** 2023-04-12 19:08 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
