### ISSUE TITLE
Multiple icons in toolbar VS2019

### ISSUE THREAD

**Issue by lrembecki** [gitextensions/gitextensions#6848] opened 2019-06-23 19:15 UTC
## Current behaviour
I have installed gitextensions plugin from VS2019 extensions.
After installing plugin I was informed to install gitextensions on windows.
After installing gitextensions on windows i got doubled icons on gitextensions toolbar in VS2019.
I have tried to uninstall plugin and program from system and install it aggain.
Now I have doubled it again! :)

![image](https://user-images.githubusercontent.com/22743961/59980852-9b849c80-95fb-11e9-8d60-e55f084f4d49.png)

## Environment

- GitExtensions version: 3.1.1
- GIT version: 2.22
- OS version: Windows 10
- .NET version: version: 4.7.2

**Comment by gerhardol** [comment] 2019-06-23 21:11
Duplicate of #4117

**Closed by gerhardol** 2019-06-23 21:11 UTC
Labels: area: vsix, type: bug
