### ISSUE TITLE
[NBug] git checkout-index: Source/Fable is not in the cache

### ISSUE THREAD

**Issue by wolfyangdev** [gitextensions/gitextensions#10567] opened 2022-12-21 17:16 UTC
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

```
GitExtUtils.ExternalOperationException: git checkout-index: Source/Fable is not in the cache ---> System.Exception: git checkout-index: Source/Fable is not in the cache

   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.ResetFile(String file)
   at GitUI.GitUICommands.StartResetChangesDialog(String fileName)
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments)
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

I selected a direnctory in File explorer and with right click I try to reset change.

### Steps to reproduce

From File Manage select a directory in repository, right click and select Reset Change.

**Comment by pmiossec** [comment] 2022-12-21 18:07
Duplicate of #10470

**Closed by pmiossec** 2022-12-21 18:07 UTC
Labels: :eyeglasses: status: needs review

**Comment by gerhardol** [comment] 2023-01-06 13:13
Separate issue as #10470. Solution is similar,separate code path.
Adding to 4.0.2, will likely not be included there though.
