### ISSUE TITLE
[NBug] 页面文件太小，无法完成操作。

### ISSUE THREAD

**Issue by mywand** [gitextensions/gitextensions#8691] opened 2020-12-21 08:41 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): 页面文件太小，无法完成操作。
   在 System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start()
   在 GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   在 GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   在 GitCommands.ExecutableExtensions.<GetOutputAsync>d__4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<>c__DisplayClass41_0.<<Update>b__0>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<>c__DisplayClass41_0.<<Update>b__0>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
error

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4200.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2020-12-21 08:54
Duplicate of #6692 
Upgrading while in use is not supported.
This is still changed in master, #8587 

```
This change is like allowing the user to hot swap the engine while running, as long as they do not touch any controls,
or they have changed specific addons.
```

**Closed by gerhardol** 2020-12-21 08:54 UTC
