### ISSUE TITLE
Strange Status On Commit Button

### ISSUE THREAD

**Issue by darklight3it** [gitextensions/gitextensions#5140] opened 2018-07-06 09:05 UTC
Hi all,

my commit button have a strange status.

![2018-07-06 10_59_29-gildedrose master - git extensions](https://user-images.githubusercontent.com/2910673/42369983-dd909058-810b-11e8-8965-632bad20400e.png)

Same as [#1991](https://github.com/gitextensions/gitextensions/issues/1991). Tried every proposed solution but i cannot revert it back to the green status.  I also tried to completely reinstall gitextension and git but nothing happens.

The problem affect all of my git repositories, not a specific one. Git is correctly pointing to my C:\Program Files\Git\bin\git.exe

Here is my git log

![2018-07-06 11_03_42-log](https://user-images.githubusercontent.com/2910673/42370201-6d57dcc8-810c-11e8-9dc6-27ace6988854.png)

**Comment by drewnoakes** [comment] 2018-07-06 09:10
Please search existing issues before opening new ones. This is a duplicate and has been fixed for the next release.

**Comment by drewnoakes** [comment] 2018-07-06 09:11
Duplicate of #5135
Duplicate of #5127

**Closed by drewnoakes** 2018-07-06 09:11 UTC

**Comment by darklight3it** [comment] 2018-07-06 09:18
sorry couldn't find it
