### ISSUE TITLE
Rendering/layout issue with "Remote Repositories" on hdpi

### ISSUE THREAD

**Issue by tomlogic** [gitextensions/gitextensions#4703] opened 2018-03-25 01:32 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
"Remote Repositories" window has sizing issues with tabs (too short) and Browse button for URL (too tall) on hdpi display.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
See attached screenshot.

**What is the expected behavior?**
UI should be consistent with non-hdpi displays.

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 
- OS version: Windows 7

**Did this work in previous version of GitExtensions (which)?**
No
<img width="901" alt="screenshot 2018-03-06 12 40 47" src="https://user-images.githubusercontent.com/1102448/37870739-aa7cc19e-2f91-11e8-866f-cd1589f2ebd4.png">

**Comment by RussKie** [comment] 2018-03-25 01:44
Duplicate of #4099

**Closed by RussKie** 2018-03-25 01:44 UTC
Labels: UX, bug, reproducible, visual hdpi
