### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by tkohlmeier** [gitextensions/gitextensions#10447] opened 2022-11-24 11:02 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.Blame.BlameControl.SelectedLineChanged(Object sender, SelectedLineEventArgs e)
   at GitUI.Editor.FileViewer.<.ctor>b__53_12(Object sender, SelectedLineEventArgs e)
   at GitUI.Editor.FileViewerInternal.<.ctor>b__31_10(Object s, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseDown(MouseEventArgs e)
   at ICSharpCode.TextEditor.TextArea.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

The exception occurred in Blame view after clicking on a commit info on the left side.

### Steps to reproduce

- Open Blame view from Visual Studio Code
- Click on a commit info line on the left side

### Did this work in previous version of GitExtensions?

Yes. Version < 4.

**Comment by RussKie** [comment] 2022-11-26 06:07
Duplicate of #10314

**Closed by RussKie** 2022-11-26 06:07 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
