### ISSUE TITLE
[NBug] Illegal characters in path.

### ISSUE THREAD

**Issue by oxysoft** [gitextensions/gitextensions#7722] opened 2020-02-03 19:30 UTC
## Additional information
On gitlab, create a wiki entry which results in a slug with invalid characters (for NTFS/Windows 10), then clone the directory. Of course there are other ways to accomplish this, but this is how it occured for me.

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.22.0.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2020-02-03 20:44
The stacktrace was left out, but the description is the same as for previous reports

Duplicate of #7528
You entered characters in the path that are illegal
So the workaround is to just dont do that

A check added in master #7633 (so popup instead)

**Closed** 2020-06-01 13:32 UTC
Labels: potential-duplicate
