### ISSUE TITLE
FormBrowse: Partial stage/unstage broken

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#5567] opened 2018-10-16 11:53 UTC
**Do you want to request a *feature* or report a *bug*?**
bug. regression by #5563

**What is the current behavior?**

In the Browse form, we could only do **one** partial stage/unstage and later one don't work anymore

**What is the expected behavior?**

Being able to do more than one partial stage/unstage

**Environment you encounter the issue:**

- GitExtensions version: master (up to date)
- GIT version: 2.18
- OS version: win 10

**Did this work in previous version of GitExtensions (which)?**

yes with ed3ce948ccb7ac2a27b63fbb4d67580895780e07

**Comment by RussKie** [comment] 2018-10-16 12:06
How to repro?

**Comment by pmiossec** [comment] 2018-10-16 12:31
Repro steps:
* select some lines
* stage them (with 's' shortcut or right click and "stage selected lines")
* files are staged
* select some other lines
* try to stage them the same way
* nothing is done.

**Comment by jbialobr** [comment] 2018-10-16 15:49
Duplicate of #5570

**Closed by jbialobr** 2018-10-16 15:49 UTC
