### ISSUE TITLE
2.49 RC2: Font smoothing not working at high resolutions

### ISSUE THREAD

**Issue by amaiorano** [gitextensions/gitextensions#3387] opened 2016-10-27 00:40 UTC
When Git Extensions is run in my laptop's native resolution of 3200x1800, the font rendering is not as smooth as when I run at half resolution (1600x900). I've attached a image that compares the two.

I realize that it's entirely possible that Windows 10 is doing its own smoothing at half resolution, so perhaps the real issue is simply that there is no font smoothing in general?

Edit: I also should mention that I used the non-RC2 official version for a long time on this laptop at high resolution, and the font issue was not there. If I revert back, I'll take a screenshot and share here.

![gitex-font-issue-compare](https://cloud.githubusercontent.com/assets/6893883/19750103/65a1f144-9bbc-11e6-8b08-3967531bcf9e.png)

**Comment by KindDragon** [comment] 2016-10-27 10:21
Duplicate of #2252

**Comment by drewnoakes** [comment] 2018-04-04 20:27
Looking at the text in the window title bars, it looks like GE was running without high DPI awareness. This is not the default behaviour, and the situation is much better these days. I think this issue is obsolete now. Please take a look at #4775.

**Closed by drewnoakes** 2018-04-04 20:27 UTC
