### ISSUE TITLE
Selection gets stuck on a particular commit when refreshing after current head changes

### ISSUE THREAD

**Issue by danlyons-softek** [gitextensions/gitextensions#6663] opened 2019-05-24 17:26 UTC
## Current behaviour

It seems like the app has some internal state that gets stuck on a particular commit (let's call it "foo"), such that no matter what commit I have selected at the time the grid is refreshed after the current head changes as the result of a commit operation (add, reset, merge, etc.), the selection is always changed back to "foo".

This may be related to #6057, but it is slightly different.  In my case, as long as the current head doesn't change, refreshing for me does not change selection.

## Expected behaviour
I would expect my selection to be maintained.

## Screenshots

I created an animated png that starts at the currently "stuck" commit, changes selection, commits a change, changes selection again, then resets the branch to illustrate the behavior I'm seeing.

![selection behavior](https://user-images.githubusercontent.com/3289668/58345803-ddfd6280-7e1e-11e9-9a13-6eba224604ca.png)

## Did this work in previous version of GitExtensions

I am reasonably certain this was not an issue in 3.0 and prior versions

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by crypto-rsa** [comment] 2019-05-27 05:58
I've experienced this behaviour, too.

**Comment by billhannah** [comment] 2019-09-03 00:18
I have been experiencing this as well. Only way to 'unstick' is to restart Git Extensions. For me, it continues to select the particular commit no matter what action I take - refresh, commit, push, pull, branch, etc. Even clicking on a particular branch in the left panel dose not fix it - next time the right panel refreshes, it goes back to the stuck commit. From my observations, it gets stuck on the head of master and will stay stuck on that commit even after that branch has commits added to it.

**Comment by mstv** [comment] 2019-10-12 23:29
Might be triggered by rewriting the history, e.g. `amend commit`, `rebase`.

**Comment by billhannah** [comment] 2019-11-06 22:26
Yes, this is triggered when the history is altered - can happen after any of the following actions:
* Pull (rebase)
* Rebase
* Amend commit

**Comment by jinglesthula** [comment] 2020-04-14 17:13
I am getting this as well still.

**Comment by RussKie** [comment] 2020-04-16 11:55
Duplicate of #6057

**Closed by RussKie** 2020-04-16 11:55 UTC
Labels: :eyeglasses: status: needs review
