### ISSUE TITLE
when installing Gitextension 2.49 setup_complete, I get an error saying "There is a problem with the Windows installer package, A program run as part of the setup did not finish as expected. Contact you´re support personel or package vendor

### ISSUE THREAD

**Issue by dugler1990** [gitextensions/gitextensions#3470] opened 2016-12-24 15:03 UTC

**Comment by anguiano** [comment] 2017-01-14 17:30
I have the same problem with both installer (GitExtensions-2.49-Setup, GitExtensions-2.49-SetupComplete).  My SO Windows 7 Home premium 64bits

My solution: 
I had to install the version 2.48.05-Setup

**Comment by Memnarch** [comment] 2017-04-03 09:35
Same here.
Windows 10 x64 Enterprise

**Comment by Memnarch** [comment] 2017-04-03 09:50
try disabling VisualStudio Plugins in Setup. That was the problem on my system

**Comment by dugler1990** [comment] 2017-04-03 10:16
For me, installing the previous version as Anguiano suggested worked fine. I forgot to give feedback :/
Thanks so much!

**Comment by Memnarch** [comment] 2017-04-03 13:08
But 2.48 had some problems with git 2.x as far as i have heared.

**Comment by KindDragon** [comment] 2017-04-11 18:43
Duplicate of #3470

**Closed by KindDragon** 2017-04-11 18:43 UTC

**Comment by vbjay** [comment] 2017-04-11 18:45
This is #3470

**Comment by vbjay** [comment] 2017-04-11 18:47
See 
#3634 #3469

**Comment by KindDragon** [comment] 2017-04-11 18:50
> This is #3470

3469 of course
