### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SailorMax** [gitextensions/gitextensions#7221] opened 2019-10-01 07:25 UTC
Just click on "Push" button

## Current behaviour
Crash

## Expected behaviour
Push action

## Steps to reproduce
Just click on "Push" button

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitHub3.GitHub3Plugin.GetHostedRemotesForModule()
   at GitHub3.GitHub3Plugin.GitModuleIsRelevantToMe()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at GitUI.CommandsDialogs.FormPush.FormPushLoad(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at GitUI.GitExtensionsForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.2.0.6559
- Build 52761218c6380e7efbcd5b7658c02295faa08cd7 (Dirty)
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment] 2019-10-01 08:09
Could you test the portable version provided here? https://github.com/gitextensions/gitextensions/issues/7205#issuecomment-535999827

**Comment by SailorMax** [comment] 2019-10-01 08:12
@pmiossec It not always happened. But I'll try.

**Comment by pmiossec** [comment] 2019-10-01 08:27
I know that's why I want the potential fix to be tested by as much user
that have this crash as possible to be sure that fix the problem.

**Comment by gerhardol** [comment] 2019-10-01 17:51
Duplicate of #7193

**Closed** 2019-11-16 12:00 UTC
Labels: potential-duplicate
