### ISSUE TITLE
Export/Import the settings and current configuration

### ISSUE THREAD

**Issue by g-rusev** [gitextensions/gitextensions#10552] opened 2022-12-19 07:41 UTC
### Feature description

Allow to export and import the current configuration of the GIT Extension settings dialog, found in Tools->Settings.

The format does not matter(JSON, XML, etc), it will be very handy if it is possible to export the settings configuration as a file and import it in another computer.

![image](https://user-images.githubusercontent.com/13536076/208374316-96c79edb-3dc6-4320-9d6f-ea7b02576948.png)

### Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

**Comment by RussKie** [comment] 2022-12-19 08:07
Duplicate of #3563

**Closed by RussKie** 2022-12-19 08:07 UTC
Labels: type: feature request
