### ISSUE TITLE
[NBug] Could not find a part of the path 'C:\x\y\z\Sources\TestApi\.git\GitExtensions.amend'

### ISSUE THREAD

**Issue by manuc66** [gitextensions/gitextensions#9101] opened 2021-04-23 20:20 UTC
## Current behaviour

Crash of GitExtension

## Expected behaviour
No crash

## Error Details
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\x\y\z\Sources\TestApi\.git\GitExtensions.amend'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at System.IO.Abstractions.FileWrapper.Delete(String path)
   at GitCommands.CommitMessageManager.set_AmendState(Boolean value)
   at GitUI.CommandsDialogs.FormCommit.OnFormClosed(FormClosedEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)
```

## Additional information
After removing the .git respository (intended)

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2021-04-23 21:42
Duplicate of #7751
There are some other similar stack traces when the repo supposedly was not deleted too.

If you remove the repo when in use, a lot of things may go wrong
However, there are changes in upcoming 3.5 to improve the presentation of the exceptions

**Closed by gerhardol** 2021-04-23 21:42 UTC
