### ISSUE TITLE
Plugin "Delete obsolete branches" include unmerged branches give error "fatal: 'HEAD' is not a valid branch name."

### ISSUE THREAD

**Issue by chetanbhatia** [gitextensions/gitextensions#6813] opened 2019-06-17 06:05 UTC
When trying to find unmerged branches in the plugin, get an error 
"fatal: 'HEAD' is not a valid branch name.".

I have noticed this in 3.1.1.6049. Not sure of other 3.x versions. This feature used to work in 2.51.05.

Steps to reproduce:
1) Open the plugin "Delete obsolete branches"
2) Click on "Include unmerged branches"
3) Click on on the caution dialog
4) Click on "Search branches"

Expected result:
Should be able to get unmerged branches based on settings and filters.

Actual result:
Get an error "fatal: 'HEAD' is not a valid branch name." in the Name column.

**Comment by manuelspezzani** [comment] 2019-07-27 18:30
I had a look at this and I found some more edge cases.

### search with default options 
issued command:
`$ git branch --merged HEAD`

the command succeeds (exit code: 0) and everything works as expected.

### search for a not existing branch 
issued command:
```
$ git branch --merged foobar
fatal: malformed object name foobar
```
the command FAILS (exit code: 128) , but the plugin still tries to parse the output and populate the result table (the error message is interpreted as a branch name).

### search with default options, but "include unmerged branches" checked
issued command:
```
$ git branch HEAD 
fatal: 'HEAD' is not a valid branch name.
```
again, the command fails but the plugin parses the output like it succeeded.

### search for a not existing branch AND "include unmerged branches" checked
issued command:
`$ git branch foobar `

this time the command succeeds, but we ended up creating a new branch!


From what I see, there are two separate issues here.
To fix this specific issue we should at least add a "--list" to the issued command, in order to prevent issuing the wrong command.
But, looking on a broader level, I would say it would be nice to do something about the IExecutable interface: I think it's not healty to simply ignore the process exit code...

**Comment by gerhardol** [comment] 2019-07-27 21:47
> To fix this specific issue we should at least add a "--list" to the issued command, in order to prevent issuing the wrong command.

With a very quick look at the code, it seems like a reasonable correction (listing is the default action if no other actions but must be specified in some situations. Maybe not available in the original git-branch, but supported at least since 2.4 so OK to include). (It does not seem like --list is lost in a regression at least.)

> But, looking on a broader level, I would say it would be nice to do something about the IExecutable interface: I think it's not healty to simply ignore the process exit code...

Yes, status should be checked, not done for all commands. (See ExecutableExtensions.cs for the current methods.)
The error message should be displayed to the user.

**Closed** 2019-08-08 13:27 UTC
Labels: area: plugins, type: bug, up for grabs
