### ISSUE TITLE
[Crash] Trying to drag and drop a DLL to Explorer freeze for ~10 sec then crash

### ISSUE THREAD

**Issue by tebeco** [gitextensions/gitextensions#6454] opened 2019-04-08 07:55 UTC
## Current behaviour
`Version 3.00.00.4433`

![image](https://user-images.githubusercontent.com/2266487/55707078-081bd200-59e3-11e9-9305-db9352c2559b.png)
```
---------------------------

---------------------------
System.InvalidCastException: Specified cast is not valid.

   at System.Windows.Forms.IDataObject.GetDataPresent(Type format)

   at ICSharpCode.TextEditor.TextAreaDragDropHandler.OnDragEnter(Object sender, DragEventArgs e)

   at ICSharpCode.TextEditor.TextAreaDragDropHandler.<>c__DisplayClass3_0.<MakeDragEventHandler>b__0(Object sender, DragEventArgs e)
---------------------------
OK   
---------------------------
```

## Expected behaviour
Either block the drag and drop to begin with, or `try` `catch` it

## Steps to reproduce
* Add a dll to a git repo
* Commit it
* Open an explorer where you have write access
* In the main scren, select the commit
* Go to the "File tree" panel
* Select the dll (in the tree view)
* Drag and Drop the dll from the tree view to the explorer

Nothing "seems" to happen, if you Hover `GitEx` with the mouse you'll see that the cursor is stuck to a `Forbidden sign`
After few long second a wonderfull crash happen

## Screenshots

**Please add a title**

![image](https://user-images.githubusercontent.com/2266487/55707078-081bd200-59e3-11e9-9305-db9352c2559b.png)

## Did this work in previous version of GitExtensions
No idea

## Environment

- GitExtensions version:
- GIT version: `git version 2.20.1.windows.1`
- OS version: Win 10 x64
- .NET version: `net472`  <== this question is really weird please add a powershell script for users to extract this as the RegEdit key are hard to map

**Comment by gerhardol** [comment] 2019-04-08 12:26
>this question is really weird please add a powershell script for users to extract this as the RegEdit key are hard to map

![image](https://user-images.githubusercontent.com/6248932/55723803-3660d800-5a0a-11e9-83ec-8be7262220ba.png)

**Comment by tebeco** [comment] 2019-04-08 18:16
is it worth adding this screenshot to the `.github` template for the issue ?

**Comment by gerhardol** [comment] 2019-04-08 18:24
> is it worth adding this screenshot to the .github template for the issue ?

The github template describes how to get the information, copt by pressing the button.
The screenshot cannot bu put in the template, then it would be included in all. It could be put in the wiki.
This info will be included from NBug in next release.

**Comment by vbjay** [comment] 2019-04-08 19:14
Note the comment


Use Help/About in Git Extensions to copy this information to the clipboard
automatically.

**Comment by tebeco** [comment] 2019-04-08 19:39
I understand everything you just wrote
but that simple issue that people never fully read

that's why i said `screenshot` ;)
but thanks for prooving that in a simple way ^^

**Comment by pmiossec** [comment] 2019-04-09 09:59
I can't reproduce (the dll is copied in the explorer for me)
Could you test with a dev version ( https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts )? Or verify your steps to reproduce?

Is there on your computer something that could provoke this crash (antivirus, ...)

**Comment by tebeco** [comment] 2019-04-09 16:57
will try to repro tomorrow at work
no idea about the firewall since i moved the dll all around in the previous minutes (no issue with that)

also the `InvalidCastException` is suspicious
i would have loved to see what the actual content tried to be cast to what other type

**Closed** 2019-11-03 06:00 UTC
Labels: :mailbox_with_no_mail: needs: author feedback, :zzz: status: no recent activity

**Comment by pmiossec** [comment] 2019-11-03 10:43
Should be fixed by https://github.com/gitextensions/ICSharpCode.TextEditor/pull/17

**Comment by tebeco** [comment] 2019-11-03 10:54
Thx @pmiossec for the notice

**Comment by tebeco** [comment] 2019-11-03 10:56
@RussKie 
I’m sorry I totally forgot that I had to try to repro
I just read that now

How do you usually organize yourself when you got plainty of issue over multi repo ?

**Comment by RussKie** [comment] 2019-11-03 12:40
> How do you usually organize yourself when you got plainty of issue over multi repo ?

Work issues go to work email, FOSS - to go my private email and sit there until I have time to look at them :)
I heard some people use Octobox

**Comment by pmiossec** [comment] 2019-11-03 12:57
There is also ghostly (not tested)

https://spectresystems.se/ghostly/
