### ISSUE TITLE
Unstage file not doing anything due to missing quotes when Git Reset file

### ISSUE THREAD

**Issue by protron** [gitextensions/gitextensions#7607] opened 2020-01-07 13:52 UTC
## Current behaviour

Unstage file button is not doing anything when file path contains spaces.

## Expected behaviour

The Unstage button in the commit window should remove the selected file from the staged list

## Steps to reproduce

1) Create a git repo (tested on Windows)
2) Commit a file into a folder containing spaces (probably fails also if the file contains spaces instead of the folder)
3) Modify that file inside a folder containing spaces
4) Stage the file in the Commit window
5) Try to Unstage that single file (the Unstage all button does work, but not if trying to do file by file)

## Screenshots

![2020-01-07 Git Extensions - Unstage defect - missing quotes in reset file](https://user-images.githubusercontent.com/465963/71899241-0e89d680-313a-11ea-8590-43eb8640dda4.png)

## Did this work in previous version of GitExtensions

I don't know

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

## Diagnostics

`Command log` shows that the Git Reset command is it invoking is not wrapped in quotes (so git is not considering as a single file path, and is not matching the file passed)

**Comment by mstv** [comment] 2020-01-08 18:47
In order to reproduce, the file must have been committed before -- as mentioned in the description.
It worked at least in 3.1.1.6049, build 2f872105b4eb42421d9fdafd68e90a9e27d20d96.
(At a first glance, it is _not_ related to `BuildBatchArguments`.)

**Comment by mstv** [comment] 2020-01-08 20:02
Bisected down to #7237. In the GH diff, I missed the cause `GitCommands.BatchUnstageFiles`.

**Closed** 2020-01-12 10:33 UTC
Labels: :beetle: type: bug, :construction: status: in progress, status: reproducible, type: regression
