### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by lviktorin** [gitextensions/gitextensions#6788] opened 2019-06-12 13:26 UTC
## Steps to reproduce

In the Git Extension window's menu, hit GitHub - Create pull requests...
The Create Pull Request window appears, immediately followed by this error. Fails on any of the few repositories I'm working with.

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Git.hub.Repository.GetBranches()
   at GitHub3.GitHubRepo.GetBranches()
   at GitUI.CommandsDialogs.RepoHosting.CreatePullRequestForm.<>c__DisplayClass22_0.<<PopulateBranchesComboAndEnableCreateButton>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

**Comment by pmiossec** [comment] 2019-06-12 14:07
I can't reproduce.

It seems that to be able to do a PR, you must have the remote repository as a "Remote repository".
Could you verify that it is the case?

**Comment by gerhardol** [comment] 2019-06-12 18:49
Duplicate of #6757

Someone that can reproduce need to debug

**Closed by gerhardol** 2019-06-12 18:49 UTC
Labels: potential-duplicate

**Comment by lviktorin** [comment] 2019-06-12 18:55
How do I verify that I have the remote repository as a "Remote repository"?
I do have it as "origin" in the "Remote repositories" window.

**Comment by pmiossec** [comment] 2019-06-12 21:41
Finally, it seems not to be the problem. See my answer here: https://github.com/gitextensions/gitextensions/issues/6757#issuecomment-501465182

And please continue the discussion there also...
