### ISSUE TITLE
Cannot install without administrator permissions

### ISSUE THREAD

**Issue by brunoais** [gitextensions/gitextensions#3020] opened 2015-11-11 15:46 UTC
At work, I'm only given user permissisons on the win7 machine I work on.
I've tried to change options selected, to change location installed, to change the install only to myself, to install only git extensions and none of the other stuff, etc... None of those worked, at the step before beginning the installation it asks for administrator rights.
I've been trying with the version 2.48.05's installer so far.

**Comment by vbjay** [comment] 2015-11-11 15:55
It is portable. Download msysgit portable and the zip of the current
release branch. Build ignoring the wix errors. Copy the built files to a
location of your choice.

**Comment by brunoais** [comment] 2015-11-11 16:30
How do I install git extensions without the installer, then? Any instructions?

**Comment by Fumble** [comment] 2015-11-25 13:50
Go to the release page https://github.com/gitextensions/gitextensions/releases and download GitExtensions-2.48.05-Mono.zip

**Comment by brunoais** [comment] 2015-11-26 20:02
Do I just download it and unpack it?

**Comment by Fumble** [comment] 2015-11-27 15:08
Yes. Download, unpack and launch GitExtensions.exe.

**Comment by KindDragon** [comment] 2016-04-29 18:41
Duplicate of #2434

**Closed by KindDragon** 2016-04-29 18:41 UTC
Labels: bug, installer
