### ISSUE TITLE
[NBug] ConEmuCD was not loaded.

### ISSUE THREAD

**Issue by dfev77** [gitextensions/gitextensions#7150] opened 2019-09-16 09:22 UTC
I can send links to memory dumps by email.

## Steps to reproduce

Interactive rebase through the contextual menu. 
Seems interactive rebase always cause this crash.

## Error Details
```
ConEmu.WinForms.GuiMacroExecutor+GuiMacroException: ConEmuCD was not loaded.
   at ConEmu.WinForms.GuiMacroExecutor.ExecuteInProcessAsync(Int32 nConEmuPid, String asMacro)
   at ConEmu.WinForms.ConEmuSession.ExecuteGuiMacroTextAsync(String macrotext)
   at ConEmu.WinForms.GuiMacroBuilder.ExecuteAsync()
   at ConEmu.WinForms.ConEmuSession.WriteOutputTextAsync(String text)
   at GitUI.FormStatus.Done(Boolean isSuccess)
   at GitUI.FormProcess.<>c__DisplayClass43_0.<OnExit>b__0()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Exception 0xC0000005 (Read x00CCA000) was occurred (conemu.exe, PID=3108)
ConEmu build 190310

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by dfev77** [comment] 2019-09-16 11:52
Yes, disabling the console emulator fixes the issue.

**Comment by gerhardol** [comment] 2019-09-16 18:45
Duplicate of #6675

Disable ConEmu in Settings->Advanced->"Use Console Emulator" to get rid of the problem

It may be something with timing, how quickly the popup status is clicked or.
There are no known way to reproduce, if you are in a position, please try

**Closed** 2019-09-16 18:45 UTC
Labels: potential-duplicate

**Comment by dfev77** [comment] 2019-09-17 07:48
@gerhardol you closed this as duplicate of an already closed issue, but the bug still exist and is doers not seem to be addresses.
Yes, and workaround exist, but that does not mean that the actual but if fixed, no matter what is its cause.
As long as there are so many occurrences of this issues, is there any plan to either remove the functionality or fix it ?

**Comment by gerhardol** [comment] 2019-09-17 21:53
[NBug] are specially handled, searched also if closed occasionally. Most of these issues have insufficient information.

Something should be done for this issue. The core problem with most problems is to reliable recreate the problem and setup environments where they can be reliably recreated. This does not exist for this issue. It is not rewarding to work with that part, it can take hours to just catch up on the changes for a day and most maintainers have a life too. So someone need to at least reliably recreate the issue. There may be ways to work with ConEmu and add debug etc too.

If no other change, ConEmu should be disabled by default and a warning popup is shown to the user if enabling.

GitExtensions is hiring. Resumes are preferably filed as issue reviews and pull requests. Benefits exists.
