### ISSUE TITLE
[NBug] Method not found: 'Boolean GitCommands.GitSshHelpers.Plink()'.

### ISSUE THREAD

**Issue by BBzzz** [gitextensions/gitextensions#10568] opened 2022-12-22 09:56 UTC
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

```
System.MissingMethodException: Method not found: 'Boolean GitCommands.GitSshHelpers.Plink()'.
   at GitExtensions.GerritPlugin.GerritUtil.StartAgent(IWin32Window owner, IGitModule module, String remote)
   at GitExtensions.GerritPlugin.FormGerritPublish.PublishChange(IWin32Window owner)
   at GitExtensions.GerritPlugin.FormGerritPublish.PublishClick(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Publishingv a Git Review not workking!

### Steps to reproduce

Trying to puplish a new Gerrit change, it fails!

**Comment by gerhardol** [comment] 2022-12-22 10:15
Duplicate of https://github.com/gitextensions/GitExtensions.GerritPlugin/issues/55

**Closed by gerhardol** 2022-12-22 10:15 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
