### ISSUE TITLE
NullReferenceException in BackgroundFetchPlugin

### ISSUE THREAD

**Issue by wischi-chr** [gitextensions/gitextensions#6459] opened 2019-04-10 07:35 UTC
## Current behaviour
NullReferenceException caused by BackgroundFetchPlugin

## Expected behaviour
GitExtension doesn't crash with NullReferenceException when closing Repositories.

## Steps to reproduce
1. Setup the BackgroundFetchPlugin to fetch pretty often (mine is 5 seconds)
2. Open a repository with a setup origin (doesn't matter what repository)
3. Try to close (with Ctrl+W) in the exact moment the plugin is fetching (in my case it first happend by accident and it can be reproduced by counting 5 seconds and hitting Ctrl+W - sometimes I "miss" and it doesn't crash but it happens almost 50% of the time if I try.

## Error Details
```
CLR: 4.0.30319.42000
NBug: 3.0.2.5232
Application: GitExtensions.exe [3.0.2.5232]
TargetSite: Void <RecreateObservable>b__1(Int64) @ BackgroundFetch.BackgroundFetchPlugin+<>c__DisplayClass10_0

System.NullReferenceException
   at BackgroundFetch.BackgroundFetchPlugin.<>c__DisplayClass10_0.<RecreateObservable>b__1(Int64 i)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.ScheduledObserver`1.Dispatch(ICancelable cancel)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

## Did this work in previous version of GitExtensions
Not sure (crash never happend but I only recently activated the plugin) but my guess is no it didn't work in previous versions.

## Environment
```
- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)
```

**Comment by RussKie** [comment] 2019-06-26 13:58
Duplicate of #6720

**Comment by RussKie** [comment] 2019-06-26 13:59
Even though this ticket was raised earlier, the other ticket contains a discussion related to the issue.

**Closed by RussKie** 2019-06-26 13:58 UTC
Labels: area: plugins, type: bug, up for grabs
