### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by markmario** [gitextensions/gitextensions#10500] opened 2022-12-06 23:10 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUIPluginInterfaces.NumberSetting`1.NumericUpDownBinding.LoadSetting(ISettingsSource settings, NumericUpDown control)
   at GitUIPluginInterfaces.SettingControlBinding`2.LoadSetting(ISettingsSource settings)
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.SettingsToPage()
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.LoadSettings()
   at GitUI.CommandsDialogs.SettingsDialog.RepoDistSettingsPage.SetCurrentSettings(RepoDistSettings settings)
   at GitUI.CommandsDialogs.SettingsDialog.RepoDistSettingsPage.SetGlobalSettings()
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageHeader.GlobalRB_CheckedChanged(Object sender, EventArgs e)
   at System.Windows.Forms.RadioButton.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.RadioButton.set_Checked(Boolean value)
   at System.Windows.Forms.RadioButton.OnClick(EventArgs e)
   at System.Windows.Forms.RadioButton.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

i changed the settings source on Perodic background fetch to Global for all repos

### Steps to reproduce

Open settings
Go to periodic background refresh
choose global for all repos

### Did this work in previous version of GitExtensions?

-

**Comment by gerhardol** [comment] 2022-12-06 23:56
Duplicate of #10323
Fixed in #10445

**Closed by gerhardol** 2022-12-06 23:56 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
