### ISSUE TITLE
Commit dialog: message area grows bigger every time dialog is opened

### ISSUE THREAD

**Issue by c3er** [gitextensions/gitextensions#7588] opened 2020-01-01 02:42 UTC
## Current behaviour

Every time I open the commit dialog, the area for the commit message is a little higher as before.

## Expected behaviour

The dialog and all elements, including the commit message area, shall keep their positions and sizes.

## Steps to reproduce

Open and close the commit dialog multiple times. You will see that the commit message area does not keep its original size.

## Screenshots

![Animation of the commit dialog](https://user-images.githubusercontent.com/24460532/71637618-c1909680-2c47-11ea-8c2e-8b2fedbd86c0.gif)

I made this animation with help of the following Python script:

```python
from time import sleep
from pynput.keyboard import Key, Controller


keyboard = Controller()

keyboard.press(Key.cmd)
keyboard.press("1")
sleep(0.1)
keyboard.release("1")
keyboard.release(Key.cmd)

for _ in range(50):
    keyboard.press(Key.esc)
    keyboard.release(Key.esc)

    keyboard.press(Key.ctrl)
    keyboard.press(Key.space)
    keyboard.release(Key.space)
    keyboard.release(Key.ctrl)

    sleep(0.3)
```

This script has following assumptions before it is started:

- The commit dialog is already open
- GitExtensions is the first entry in the Windows task bar

## Did this work in previous version of GitExtensions

I think in GitExt prior to version 3 but I'm unsure

## Environment

- GitExtensions version: Version 3.3.0.7719 and developer build, commit 86d233a
- GIT version: 2.24.1.windows.2
- OS version: Windows 10, version 1909
- .NET version: Framework 4.6.1

**Comment by mstv** [comment] 2020-01-01 20:05
Described in #6435, too.

**Comment by gerhardol** [comment] 2020-01-01 23:05
Duplicate of #6435

**Comment by RussKie** [comment] 2020-01-02 12:55
Let's keep this one open, as #6435 reports multiple issues (and thus makes it harder to get fixed).

**Comment by c3er** [comment] 2020-01-02 14:21
I managed to fix the positioning issues in the commit dialog thus far.

@RussKie Indeed, I can still reproduce the missing scrollbars, mentioned in #6435.

I have difficulties with the tests. That some SplitterManager tests fail is yet understandable. But the test `DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending` seems quite flaky and is more prone to fail with my changes; though it failed too from time to time on my machine without my changes.

I [did a commit to my fork](https://github.com/c3er/gitextensions/commit/6ef1a133c37d21d2974c6362e9c39250897239f2) but I want to wait with the PR until the tests are running properly again.

**Comment by gerhardol** [comment] 2020-01-02 15:10
> DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending seems quite flaky

That is a general problem (trying to open difftool or something)

**Comment by mstv** [comment] 2020-01-03 12:24
> DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending seems quite flaky
> That is a general problem (trying to open difftool or something)

Yes, you can ignore these tests. They pass at AppVeyor and locally when I deactivate my favorite clipboard manager (based on AutoHotKey).

**Closed** 2020-02-20 13:20 UTC
Labels: :beetle: type: bug, :construction: status: in progress, area: user experience
