### ISSUE TITLE
Push to multiple branches, deletes remote branch as well

### ISSUE THREAD

**Issue by nomoderator** [gitextensions/gitextensions#7077] opened 2019-08-30 05:27 UTC
## Current behaviour

Pushing to multiple branch, without selecting "Delete Remote Branch" **IS DELETING** remote branch

## Expected behaviour

Pushing to multiple branch, without selecting "Delete Remote Branch" **SHOULD NOT DELETE** any remote branch

## Steps to reproduce

Simply push to multiple branches, without selecting "Delete Remote Branch" and say bye bye to remote branch

## Screenshots

![image](https://user-images.githubusercontent.com/46629487/63994980-45106e80-cb14-11e9-988e-be7733637a72.png)

## Did this work in previous version of GitExtensions

I'm not sure because I recently started using this functionality

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 96dpi (no scaling)

**Comment by nomoderator** [comment] 2019-09-10 03:03
Hi @gerhardol , is somebody looking onto this bug? I'm new here, so not sure what is the progress on this ticket, as it's been 11 days since I posted this.

**Comment by gerhardol** [comment] 2019-09-10 20:48
> is somebody looking onto this bug?

Probably not. 
Everything cannot be investigated, bugs will split. There is a limit to much time the core maintainers can spend on GE. (I have basically stopped developing, just looking at issues.)

The Git command log is a good start to investigate.

**Comment by hieuxlu** [comment] 2019-10-19 15:05
I can't reproduce this. So probably not just "simply push to multiple branches". @nomoderator Can you verify with other repositories, or send your git log? There must be something special with your repo.

**Comment by nomoderator** [comment] 2019-10-21 05:08
@hieuxlu Apologies for the late reply.
My organization is using OracleCloud for repo management. I could reproduce the issue by creating dummy branches and pushing a commit in all of them together. Here are the steps I followed:

1. Commit a file (package.json)
2. Push to multiple branches:
![image](https://user-images.githubusercontent.com/46629487/67177978-99d2b600-f3ee-11e9-8194-07cecc718b15.png)
3. After the push, branches are automatically deleted:
![image](https://user-images.githubusercontent.com/46629487/67178016-c4bd0a00-f3ee-11e9-93c1-7a1d0d1c8078.png)

Git Command Log: 
[git push multiple branch issue.txt](https://github.com/gitextensions/gitextensions/files/3749097/git.push.multiple.branch.issue.txt)

**Comment by hieuxlu** [comment] 2019-10-21 09:53
@nomoderator I don't have Oracle Cloud account, so can you verify with Github instead? Probably a bug with Oracle Cloud git.

**Comment by RussKie** [comment] 2019-10-21 10:06
This looks sus:
```
2019-10-21T10:27:15.6681414+05:30	25608		UI	0	git	push --progress "origin" :refs/heads/rahul_t1 :refs/heads/rahul_t2 :refs/heads/rahul_t3	D:\Work\RecVue\contracts\rahul-contracts\
```

**Comment by nomoderator** [comment] 2019-10-21 12:53
@hieuxlu might be a bug with Oracle Git. I don't actively work on GitHub now to test it further.
@RussKie what can be done on my part?

**Comment by RussKie** [comment] 2019-10-21 13:02
@nomoderator not sure at this stage, it could be a bug in our code... The above line looks like we *are* deleting refs.

@hieuxlu do you think you could dig through the code and see why we may be issuing the above command?

**Comment by hieuxlu** [comment] 2019-10-21 14:36
@RussKie I would. Think I understand the bug, please assign it to me. It is somehow missing the first part before `:`, isn't it? Mine would be like this, notice the part before `:`
```
git push --progress "fork" refs/heads/test1:refs/heads/test1 refs/heads/test2:refs/heads/test2
```

**Comment by hieuxlu** [comment] 2019-10-21 14:52
@nomoderator I think I know the root cause: you haven't checked out local branch before pushing to multiple branches. So a quick work around is check out branches before you push. 
@RussKie For this case, should we disable the push check box for branches that haven't been checked out yet?

**Comment by pmiossec** [comment] 2019-10-21 14:56
@hieuxlu Interesting. I don't understand what checking out branches before pushing changes.

Could you elaborate a little more?

**Comment by mast-eu** [comment] 2019-10-21 15:07
Confirm @hieuxlu
The key is that you are pushing to remote branches, _without_ having matching local branches. 
![image](https://user-images.githubusercontent.com/46861028/67211664-69554100-f41b-11e9-8dfa-7b279f7d5226.png)
So basically you are doing `git push <empty> to origin:rahul_t1`. Which git interprets as `delete origin:rahul_t1`. This is even [a documented behaviour](https://git-scm.com/docs/git-push#Documentation/git-push.txt-ltrefspecgt82308203):
```
Pushing an empty <src> allows you to delete the <dst> ref from the remote repository. 
```

I'd argue that technically it is not really a bug, because the system acts as specified. However, the UX has room for improvement, because it doesn't do what most users would expect.
GE could disable the push checkboxes if there's no local branch. Or, at least, show a warning.

**Comment by gerhardol** [comment] 2019-10-21 15:27
> GE could disable the push checkboxes if there's no local branch

Seem reasonable to me - there is not anything to push for these branches anyway

**Comment by hieuxlu** [comment] 2019-10-21 15:28
We could even not show them at all. Imagine 1000 remote branches.

**Comment by nomoderator** [comment] 2019-10-21 15:29
@mast-eu Thank you for the insight. But now I've a related query.
I do have a local branch for **master**. But the attached screenshot is not showing it, because I'm already in **rahul** branch. Then how should I push to multiple branches without any issues. 
The day I raised this issue, I did select **master** branch as well (I already have a local for it, but it was not showing in the Local Branch column). 
It deleted all the branches, except for **master**, only because it got errored out, as it's the default branch!

**Comment by hieuxlu** [comment] 2019-10-21 15:41
> I do have a local branch for **master**. But the attached screenshot is not showing it, because I'm already in **rahul** branch, which has a separate folder.

What do you mean by folder? Can you share the folder screenshot so that I could understand? I think you checked out master branch to a different folder outside of this local git repo. And then checked out branch *rahul* in another local folder. That's why there's only 1 local *rahul* branch in this local repo.

Normally we don't do that. We only check out repo to a local folder once, and in this repo, we check out branches...

**Comment by hieuxlu** [comment] 2019-10-21 15:45
@gerhardol @mast-eu Can we remove all the checkboxes for remote branch without matching local branch, instead of disabling them? I think for the most cases, we only have < 10 local branches, while there can be >100s remote branches. So why don't we hide all the extra push checkboxes? 

What do you think?

**Comment by nomoderator** [comment] 2019-10-21 15:46
@hieuxlu Folder structure looks like this:
![image](https://user-images.githubusercontent.com/46629487/67220603-b5b67600-f447-11e9-9c99-795db19ba8e3.png)

Each having this nested structure:
![image](https://user-images.githubusercontent.com/46629487/67220799-10e86880-f448-11e9-84bf-539c6facae6b.png)

**Comment by hieuxlu** [comment] 2019-10-21 15:50
@nomoderator That's what I think. You have checked out git twice, to 2 different local repos. 
In master-contracts, you only have 1 local __master__ branch
In rahul-contracts, you only have 1 local __rahul__ branch
That's why there's no local master branch in rahul folder. You should've used check out branch instead.
![image](https://user-images.githubusercontent.com/11418231/67221136-24e69700-f455-11e9-949f-192aca4f9918.png)

**Comment by pmiossec** [comment] 2019-10-21 15:55
Or used `git worktree` feature (supported by Gitextensions) instead of
cloning twice...

**Comment by gerhardol** [comment] 2019-10-21 16:08
> @gerhardol @mast-eu Can we remove all the checkboxes for remote branch without matching local branch, instead of disabling them? I think for the most cases, we only have < 10 local branches, while there can be >100s remote branches. So why don't we hide all the extra push checkboxes?

I consider the UI be easier to understand if the control is disabled instead of removed. No question why it disappeared...

**Comment by mast-eu** [comment] 2019-10-21 16:31
> Then how should I push to multiple branches without any issues?

@nomoderator  If I understand correctly, you want to push the same changes from **1 local branch** to **multiple remote branches** at the same time. Is this correct?
If yes, I don't think you can. There's a 1:1 relation between local and remote branches in git. No way to set up a 1:n relationship.
You would need a dedicated local branch for each remote branch and merge locally as needed before pushing them.

But why all this? It feels way to complicated. What do you try to achieve?

**Comment by hieuxlu** [comment] 2019-10-22 00:44
> I consider the UI be easier to understand if the control is disabled instead of removed. No question why it disappeared...

OK, disabled it is then.

> Or used `git worktree` feature (supported by Gitextensions) instead of cloning twice...

After 4 years using GE, now I know how to use Worktree. Would have saved countless time when I have to check out different folders for develop, master, forks...

**Comment by hieuxlu** [comment] 2019-10-22 02:11
I didn't know that WinForms has no disabled style for checkbox cell. If we are going to hard-code cell style, that would be problematic with the upcoming dark theme features. Any idea how we should handle disabled checkbox style here?

Below is readonly checkbox cell, no difference to editable ones.
![image](https://user-images.githubusercontent.com/11418231/67255331-b3860300-f4ab-11e9-95a5-a26bedcd5c3c.png)

**Comment by gerhardol** [comment] 2019-10-22 11:22
> I didn't know that WinForms has no disabled style for checkbox cell

Then it seem better to delete

**Comment by hieuxlu** [comment] 2019-10-22 13:38
Delete it is then... (make it hidden)

**Comment by RussKie** [comment] 2019-10-22 23:27
@hieuxlu would this work https://stackoverflow.com/a/10356938/2338036?

**Comment by hieuxlu** [comment] 2019-10-22 23:55
As I said earlier, I dont know how hard coding color will work with upcoming dark theme feature. I consider this to be low priority compared to dark theme.

**Comment by RussKie** [comment] 2019-10-23 02:01
I think you can proceed with the fix using the SO suggestion.  @NikolayXHD can advise you on the color.

**Comment by hieuxlu** [comment] 2019-10-23 05:20
@RussKie That will trigger an infinite paint loop, so I have to modify a little bit. Anyway, here's the result, the selection state looks strange.
![image](https://user-images.githubusercontent.com/11418231/67360029-12707880-f58f-11e9-98ef-e69ca601477c.png)

For perspective, this is how it looks when hiding checkboxes. Personally I like this better.
![image](https://user-images.githubusercontent.com/11418231/67360054-1f8d6780-f58f-11e9-87ef-da4db1e0d7fb.png)

So should we go on with disabling or hiding?

**Comment by RussKie** [comment] 2019-10-23 06:00
nice! I like when the boxes are hidden

**Comment by gerhardol** [comment] 2019-10-23 07:45
I conceptually prefer disabling, but not by adding complexity. Suggest to remove
This is not an important issue, just do something

**Closed** 2019-10-25 02:33 UTC
Labels: :beetle: type: bug, :construction: status: in progress, :wave: up for grabs, hacktoberfest
