### ISSUE TITLE
version 3.02.5232

### ISSUE THREAD

**Issue by gural0112** [gitextensions/gitextensions#6282] opened 2019-02-20 10:08 UTC
jira Commit hint plugin  stop to work.
Exception on try to fetch issues from jira:
FileLoadException : located assembly's manifest definition doesn't math the assembly reference

**Comment by RussKie** [comment] 2019-02-20 10:42
Duplicate of #6154

**Closed by RussKie** 2019-02-20 10:42 UTC

**Comment by gural0112** [comment] 2019-02-20 10:53
10x
