### ISSUE TITLE
Application hangs on secondary 4k monitor

### ISSUE THREAD

**Issue by TimPaaschen** [gitextensions/gitextensions#7935] opened 2020-04-02 11:50 UTC
My setup consists of a HD monitor (internal display of the laptop) as primary display and a 4k monitor as secondary display. The laptop runs Windows 10 Pro and the two displays are configured as extendend desktop area.

## Current behaviour
Most features of Git Extensions work fine. However if the main window is placed on the 4k monitor and I press the 'Commit' button, the Commit window doesn't open but the main window is blocked as if it has shown up.
If the main window is located on the HD monitor, the Commit window is shown properly.

## Expected behaviour
The commit window is shown independent of the monitor displaying the main window.

## Did this work in previous version of GitExtensions
I don't know. This setup is new.

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.26.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2020-04-03 06:57
I don't think the app hangs, instead the commit window is opened outside
the visible area.

This is something we had observed and had reports for under specific
arrangements in multi monitor setup, when the app isn't opened on the
default screen.

Try bringing the commit window into view using WIN+left/right arrow keys.

I don't have a MM setup to debug it though.

**Comment by TimPaaschen** [comment] 2020-04-06 12:10
I agree, that this is the most plausible explanation.
Today I was not able to reproduce the issue anymore - without a SW-update inbetween.

**Comment by GintasS** [comment] 2020-10-04 10:00
Shouldn't this issue be closed then?

**Comment by RussKie** [comment] 2020-10-04 11:26
Duplicate of #6427

**Comment by RussKie** [comment] 2020-10-04 11:26
The issue is still here, tracking under #6427.

**Closed by RussKie** 2020-10-04 11:26 UTC
Labels: :nerd_face: good first issue, area: hdpi, area: user experience, up-for-grabs
