### ISSUE TITLE
Can't switch to minimised instance

### ISSUE THREAD

**Issue by CSmithGS** [gitextensions/gitextensions#10701] opened 2023-02-07 15:49 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.13
- DPI 240dpi (250% scaling)
- Microsoft.WindowsDesktop.App Versions

### Issue description

When I have more than one instance open and attempt use the taskbar to switch to a window that has been minimised, I get a Windows warning tone and the window is not activated. I have to use Alt-Tab to see the window. 

I have the 'Combine taskbar buttons' setting set to 'Always, hide labels'.

### Steps to reproduce

1. Ensure that the Taskbar settings have 'Combine taskbar buttons' set to 'Always, hide labels'.
2. Open two instances of Git Extensions.
3. Minimise one instance of Git Extensions.
4. Attempt to activate the minimised instance of Git Extension by left-clicking on the Git Extensions icon on the taskbar and selecting that instance.

### Did this work in previous version of GitExtensions?

I believe so. 3.5.3.

**Comment by gerhardol** [comment] 2023-02-07 22:34
Duplicate of #10398 

See [the i](https://github.com/gitextensions/gitextensions/issues/10398#issuecomment-1313378235) for a kind of update

**Closed by gerhardol** 2023-02-07 22:34 UTC
Labels: :eyeglasses: status: needs review
