### ISSUE TITLE
[NBug] Value must not be null.

### ISSUE THREAD

**Issue by superb0y03** [gitextensions/gitextensions#10502] opened 2022-12-07 09:06 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.35.1.windows.2 (recommended: 2.38.1 or later)
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

```
System.Exception: Value must not be null.
   at Microsoft.Validates.Fail(String message)
   at GitUI.CommandsDialogs.SettingsDialog.SettingsTreeViewUserControl.textBoxFind_KeyUp(Object sender, KeyEventArgs e)
   at System.Windows.Forms.Control.OnKeyUp(KeyEventArgs e)
   at System.Windows.Forms.TextBox.OnKeyUp(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Open the settings menu without opening a git repository

### Steps to reproduce

Open the settings menu without a repository selected

**Comment by gerhardol** [comment] 2022-12-07 09:42
Duplicate of #10377

**Closed by gerhardol** 2022-12-07 09:42 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
