### ISSUE TITLE
I can not run the the gitextensions for the secend time on the centos mono platform

### ISSUE THREAD

**Issue by fy2462** [gitextensions/gitextensions#3188] opened 2016-04-27 07:07 UTC
I install the mono on the centos7, and download the latest extensions.
I run the command "mono GitExtensions" for the first time, it's all right.
But I close the app and run it second time, it output the error as follows:

```
Unhandled Exception:
System.TypeInitializationException: The type initializer for 'GitCommands.AppSettings' threw an exception. ---> System.Xml.XmlException: Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it. Line 31, position 9.
  at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) <0x41ae6690 + 0x000a3> in <filename unknown>:0 
  at System.Xml.XmlTextReaderImpl.Throw (System.String res, System.String arg) <0x41ae6180 + 0x000ab> in <filename unknown>:0 
  at System.Xml.XmlTextReaderImpl.ParsePI (System.Text.StringBuilder piInDtdStringBuilder) <0x41ae5bc0 + 0x0013b> in <filename unknown>:0 
  at System.Xml.XmlTextReaderImpl.ParsePI () <0x41ae5ba0 + 0x0000f> in <filename unknown>:0 
  at System.Xml.XmlTextReaderImpl.ParseElementContent () <0x41a7aa30 + 0x000bb> in <filename unknown>:0 
  at System.Xml.XmlTextReaderImpl.Read () <0x41a752f0 + 0x00057> in <filename unknown>:0 
  at System.Xml.XmlTextReader.Read () <0x41a752d0 + 0x0001a> in <filename unknown>:0 
  at System.Xml.XmlWriter.WriteNode (System.Xml.XmlReader reader, Boolean defattr) <0x41a82aa0 + 0x0034c> in <filename unknown>:0 
  at System.Xml.XmlReader.ReadOuterXml () <0x41a81c30 + 0x0015a> in <filename unknown>:0 
  at System.Configuration.SectionInfo.ReadData (System.Configuration.Configuration config, System.Xml.XmlReader reader, Boolean overrideAllowed) <0x41a81740 + 0x00283> in <filename unknown>:0 
  at System.Configuration.SectionGroupInfo.ReadContent (System.Xml.XmlReader reader, System.Configuration.Configuration config, Boolean overrideAllowed, Boolean root) <0x41a80f80 + 0x0031c> in <filename unknown>:0 
  at System.Configuration.SectionGroupInfo.ReadData (System.Configuration.Configuration config, System.Xml.XmlReader reader, Boolean overrideAllowed) <0x41a85ff0 + 0x0005f> in <filename unknown>:0 
  at System.Configuration.SectionGroupInfo.ReadContent (System.Xml.XmlReader reader, System.Configuration.Configuration config, Boolean overrideAllowed, Boolean root) <0x41a80f80 + 0x0031c> in <filename unknown>:0 
  at System.Configuration.SectionGroupInfo.ReadRootData (System.Xml.XmlReader reader, System.Configuration.Configuration config, Boolean overrideAllowed) <0x41a80f20 + 0x00043> in <filename unknown>:0 
  at System.Configuration.Configuration.ReadConfigFile (System.Xml.XmlReader reader, System.String fileName) <0x41a74f10 + 0x00223> in <filename unknown>:0 
  at System.Configuration.Configuration.Load () <0x41a6fcf0 + 0x0010b> in <filename unknown>:0 
  at System.Configuration.Configuration.Init (IConfigSystem system, System.String configPath, System.Configuration.Configuration parent) <0x41a6f5c0 + 0x00227> in <filename unknown>:0 
  at System.Configuration.Configuration..ctor (System.Configuration.InternalConfigurationSystem system, System.String locationSubPath) <0x41a6eba0 + 0x00173> in <filename unknown>:0 
  at System.Configuration.InternalConfigurationFactory.Create (System.Type typeConfigHost, System.Object[] hostInitConfigurationParams) <0x41a6e020 + 0x0006f> in <filename unknown>:0 
  at System.Configuration.ConfigurationManager.OpenMappedExeConfiguration (System.Configuration.ExeConfigurationFileMap fileMap, ConfigurationUserLevel userLevel) <0x41adf3e0 + 0x000b4> in <filename unknown>:0 
  at System.Configuration.CustomizableFileSettingsProvider.LoadProperties (System.Configuration.ExeConfigurationFileMap exeMap, System.Configuration.SettingsPropertyCollection collection, ConfigurationUserLevel level, System.String sectionGroupName, Boolean allowOverwrite, System.String groupName) <0x41adeec0 + 0x0007b> in <filename unknown>:0 
  at System.Configuration.CustomizableFileSettingsProvider.GetPropertyValues (System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyCollection collection) <0x41adccc0 + 0x00193> in <filename unknown>:0 
  at System.Configuration.LocalFileSettingsProvider.GetPropertyValues (System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyCollection properties) <0x41adcc80 + 0x0002e> in <filename unknown>:0 
  at System.Configuration.ApplicationSettingsBase.CacheValuesByProvider (System.Configuration.SettingsProvider provider) <0x41adc620 + 0x0029c> in <filename unknown>:0 
  at System.Configuration.ApplicationSettingsBase.GetPropertyValue (System.String propertyName) <0x41adc310 + 0x00083> in <filename unknown>:0 
  at System.Configuration.ApplicationSettingsBase.get_Item (System.String propertyName) <0x41adc260 + 0x00053> in <filename unknown>:0 
  at GitCommands.Properties.Settings.get_IsPortable () <0x41adc1f0 + 0x0001a> in <filename unknown>:0 
  at GitCommands.AppSettings.IsPortable () <0x41ada080 + 0x00017> in <filename unknown>:0 
  at GitCommands.AppSettings.<.cctor>b__0 () <0x41ada000 + 0x0000b> in <filename unknown>:0 
  at System.Lazy`1[T].CreateValue () <0x7fa5cb95fdc0 + 0x00174> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at GitUI.Lemmings.GetPictureBoxImage (DateTime currentDate) <0x41ad9b40 + 0x0000f> in <filename unknown>:0 
  at GitUI.FormSplash..ctor () <0x41aa74c0 + 0x00117> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) GitUI.FormSplash:.ctor ()
  at GitUI.FormSplash.ShowSplash () <0x41aa7410 + 0x0001f> in <filename unknown>:0 
  at GitExtensions.Program.Main () <0x41a64de0 + 0x00253> in <filename unknown>:0 
```

What's happended, I think it is a bug, any one help me?

**Comment by KindDragon** [comment] 2016-04-27 09:35
Probably some kind of error when reading GitExt settings

**Comment by EbenZhang** [comment] 2016-04-27 09:55
It's a known issue already been fixed in master branch.

**Comment by fy2462** [comment] 2016-04-28 06:19
Thanks, @EbenZhang. What mono version I can install for working well?

**Comment by fy2462** [comment] 2016-04-28 06:24
@KindDragon , yeah, I think so.
Whether I can modify the GitExt setting file manual or not to fix the problem?
If yes, where the file is ?

**Comment by KindDragon** [comment] 2016-04-28 14:00
Duplicate of #3096
@fy2462 FYI https://github.com/gitextensions/gitextensions/pull/3052#issuecomment-203674108

**Closed by KindDragon** 2016-04-28 14:00 UTC
Labels: linux/mono

**Comment by fy2462** [comment] 2016-04-30 06:22
@KindDragon 
Thanks you very muh.
