### ISSUE TITLE
[NBug] Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by serjevski** [gitextensions/gitextensions#10563] opened 2022-12-21 12:58 UTC
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GitExtensions.Plugins.BackgroundFetch.BackgroundFetchPlugin.<>c__DisplayClass11_0.<RecreateObservable>b__1(Int64 i)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.ObserveOnObserverLongRunning`1.Drain() in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 732
   at System.Reactive.ObserveOnObserverLongRunning`1.<>c.<.cctor>b__17_0(ObserveOnObserverLongRunning`1 self, ICancelable cancelable) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 680
   at System.Reactive.Concurrency.NewThreadScheduler.<>c__DisplayClass7_0`1.<ScheduleLongRunning>b__0() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/NewThreadScheduler.cs:line 94
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Thread.StartCallback()
```

Just open repository. Some seconds later GitExtension closes.

### Steps to reproduce

I just open repository. Some seconds later it closes. 

### Did this work in previous version of GitExtensions?

4.0.0 works fine

**Comment by mstv** [comment] 2022-12-21 13:25
The configured git arguments must not consist of whitespace only.

![image](https://user-images.githubusercontent.com/36601201/208915267-8fe61867-a261-4162-808e-d8485b9030ad.png)

**Comment by mstv** [comment] 2022-12-22 10:04
Duplicate of https://github.com/gitextensions/GitExtensions.GerritPlugin/issues/55

**Closed by mstv** 2022-12-22 10:04 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
