### ISSUE TITLE
Main view select single commit

### ISSUE THREAD

**Issue by HemetsS** [gitextensions/gitextensions#6850] opened 2019-06-24 05:33 UTC
## Current behaviour

Sometimes it happens that if i select a single commit, the last selected one still be active.
I can only reset this by restart the software.

## Steps to reproduce

No procedure found yet to reproduce the error.

## Screenshots

![Error_Git](https://user-images.githubusercontent.com/48977894/59993794-d5808d80-9651-11e9-8b20-861522cbc866.jpg)

## Did this work in previous version of GitExtensions

No, the error was still the same

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment] 2019-06-24 05:55
It might be that the state of the `Ctrl` key got stuck because of the Console Emulator.
Just hit the `Ctrl` key again or disable ConEmu in the settings.

**Comment by gerhardol** [comment] 2019-07-22 23:18
Duplicate of #6420

**Closed by gerhardol** 2019-07-22 23:18 UTC
