### ISSUE TITLE
Browser: Size-change of "Commit" button is annoyingly moving "Pull", "Push" and "Shell"

### ISSUE THREAD

**Issue by imi0** [gitextensions/gitextensions#3924] opened 2017-08-23 05:49 UTC
The Commit button (that opens the Commit dialog) in the Git Browser changes its text (and color) if you have no changed files or have changed files. For example, if you don't have any changed files, it reads just "Commit". If you have - say.. 5 changed files, it reads "Commit (5)". This changes the size of the button.

Also note, that this state changes asynchronous when the dialog refreshes its state. So especially after starting the browser, it can change any time in the first couple of seconds.

Next to the button on the right is the "Pull" button, next to this one is the "Push" button and then comes the "Command Shell" button . These buttons get moved if the commit button changes size.

This is very annoying, since most of the time, my workflow is "Open Git browser", "Press Pull". Very often, I accidentally click the "Commit" button that just enlarged itself right before I could hit the "Pull" button.

I would much like to have this behavior changed, for example by just enlarging the Commit button in case of no changes to a constant size. Or by rearranging the buttons so that "Pull", "Push" and "Command Shell" are on the left of "Commit" so they don't get moved around.

My GitExtensions version: 2.50.01 which I believe to be the latest version.

**Comment by RussKie** [comment] 2017-08-23 11:54
In the interim you could disable the display of number of changed file on the button
https://git-extensions-documentation.readthedocs.io/en/latest/settings.html#git-extensions-performance-changes-no

**Comment by vbjay** [comment] 2017-08-23 12:04
My 2 cents. Resizing to hold the number would be hard to manage for all
numbers. I think rearranging the buttons is the better idea.

Or can we make it a large button with a larger height?

**Comment by RussKie** [comment] 2017-09-13 23:49
Duplicate of #3550

**Comment by gerhardol** [comment] 2018-08-25 21:45
I suggest the action here is to move the buttons and that this is closed as a duplicate of #1931

**Comment by RussKie** [comment] 2018-08-25 23:34
Duplicate of #1931

**Closed by RussKie** 2018-08-25 23:34 UTC
Labels: area: user experience
