### ISSUE TITLE
[NBug] SSH key file could not be found

### ISSUE THREAD

**Issue by kgrammer** [gitextensions/gitextensions#10569] opened 2022-12-22 22:33 UTC
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

'C:/Users/kgrammer/.ssh/kg.ppk'

```
GitUI.NBugReports.UserExternalOperationException: SSH key file could not be found
 ---> System.IO.FileNotFoundException: SSH key file could not be found
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.PuttyHelpers.ThrowIfFileNotFound(String filePath, String errorMessage, String heading)
   at GitUI.Infrastructure.PuttyHelpers.StartPageantIfConfigured(Func`1 sshKeyFileLoader)
   at GitUI.CommandsDialogs.FormPush.StartPageant(String remote)
   at GitUI.CommandsDialogs.FormPush.LoadSshKeyClick(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

This latest upload will not let me change the location of the SSH key file.  It's defaulting to a very old location from a previous laptop (I upgraded earlier this month) and now I can't change the location of the ssh key file.

### Steps to reproduce

I'm not sure how you will reproduce this other then to simply try to change your SSH key file and see if you can reproduce the error.

### Did this work in previous version of GitExtensions?

The release prior to this current on.  I don't have the exact release number because you auto-updated my system.

**Comment by kgrammer** [comment] 2022-12-22 22:48
I was able to select "Repository", then "Remote Repositories" and I can edit the name/location of the key file to point to the correct key file.  But as noted on other duplicate issues, the problem is that the original key file does not exist and the upload files page will no longer allow the key to be updated/changed when I *think* that was allowed in 4.0 and older versions.

"Premature Code Optimizations" at work for us!!!

**Comment by gerhardol** [comment] 2022-12-22 22:56
Duplicate of https://github.com/gitextensions/gitextensions/issues/10530
Please try the solution in https://github.com/gitextensions/gitextensions/pull/10545

Not exactly the same as the other, but the change should be the same.
Why cant you change the key in PageAnt?

**Closed** 2022-12-28 22:18 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate

**Comment by kgrammer** [comment] 2022-12-28 23:23
Changing the key in Pageant does not change the nature of this problem as the two are unrelated.
