### ISSUE TITLE
[NBug] Collection was modified; enumeration operation may not exec...

### ISSUE THREAD

**Issue by antonioyip** [gitextensions/gitextensions#7117] opened 2019-09-09 17:29 UTC
## Current behaviour

Crash

## Expected behaviour

No crash

## Steps to reproduce

This is roughly what I did (I didn't try to reproduce again):

Fetch code
Tried to create branch at the tip
Failed creation due to code changes
Stash code changes
Create branch at tip
Deleted old branch
Deleted unversioned files (using the commit dialog)
Pop stash
Crash

## Error Details
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.SelectRowsIfReady(Int32 rowCount)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.<BackgroundThreadEntry>g__UpdateRowCount|48_2(Int32 row)
   at GitUI.GitUIExtensions.<InvokeAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 96dpi (no scaling)

**Comment by antonioyip** [comment] 2019-09-09 17:36
I tried to record as much of the steps I performed since opening GitExtensions until it crashed. I didn't try to reproduce (sorry!) since it's not blocking me. Just thought you guys might want the report. I think I included more information than the duplicates (e.g. !6924).

**Comment by montoner0** [comment] 2019-09-09 18:09
>  I think I included more information than the duplicates (e.g. #6924).
Well, since my "steps list" was shorter it doesn't mean that it's incomplete. And by the way, the stack traces are different.

**Comment by jimbo1qaz** [comment] 2019-10-09 06:13
I got a crash after following the same procedure as #6924, with the same stack trace as that issue (not the current issue #7117).

**Comment by RussKie** [comment] 2019-10-09 12:57
> I got a crash after following the same procedure

We need more details: OS, git, GE etc etc as found on the About dialog.

**Comment by jimbo1qaz** [comment] 2019-10-09 22:38
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2020-03-04 23:25
Duplicate of #7067 

No known way to recreate

**Comment by splerp** [comment] 2020-03-15 23:27
I got the same crash and stack trace today. Details:

## Additional information
- Filter results (put text in the "Filter:" text field) and press enter
- Select a commit
- Worked in other programs for a while
- Return and open Repositories dropdown
- Close it (no change in repository)
- Delete text in the "Filter" text field and press enter

Expected: Full commit history to appear in main window
Actual: Full commit history appears in main window + error report dialog opens


## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2020-03-31 11:57
@splerp thank you for the steps, but I can't repro it.
Can you try the latest portable build and see if it repros in it? https://ci.appveyor.com/api/buildjobs/ah3r7644ff3nq175/artifacts/artifacts%2Fpublish%2FGitExtensions-Portable-4.0.0.8944-bc0fc56e1.zip

**Comment by splerp** [comment] 2020-04-02 00:35
@RussKie It happened once for me but I'm now unable to reproduce it anywhere (in my version 3.3.1.7897 and the portable version you linked)...

I'll swap to using the latest version and report back if it happens again

**Comment by RussKie** [comment] 2020-04-02 10:06
Closing, holler if you get a repro.

**Closed by RussKie** 2020-04-02 10:06 UTC
Labels: :eyeglasses: status: needs review, area: dashboard

**Comment by pmiossec** [comment] 2020-04-02 10:13
And if someone has the exception with a GitExtension >= v3.2, please post the stacktrace to have a more understandable stacktrace for developers.
