### ISSUE TITLE
Linux: gitextensions crashes every time the commit window closes.

### ISSUE THREAD

**Issue by JerryLumpkins** [gitextensions/gitextensions#2863] opened 2015-07-04 11:17 UTC
Console stderr when I include a debug flag in mono inside the gitext.sh script:
mono --debug=casts GitExtensions.exe "$@" &

```
System.InvalidCastException: Unable to cast object of type 'GitUI.SpellChecker.SpellCheckEditControl' to type 'System.Windows.Forms.Control+ControlNativeWindow'.
  at System.Windows.Forms.Control+ControlNativeWindow.ControlFromHandle (IntPtr hWnd) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Control.FromHandle (IntPtr handle) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.X11Keyboard.MoveCurrentCaretPos () [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.XplatUIX11.MoveResizeWindow (IntPtr display, IntPtr window, Int32 x, Int32 y, Int32 width, Int32 height) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.XplatUIX11.PerformNCCalc (System.Windows.Forms.Hwnd hwnd) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.XplatUIX11.GetWindowPos (IntPtr handle, Boolean is_toplevel, System.Int32& x, System.Int32& y, System.Int32& width, System.Int32& height, System.Int32& client_width, System.Int32& client_height) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.XplatUI.GetWindowPos (IntPtr handle, Boolean is_toplevel, System.Int32& x, System.Int32& y, System.Int32& width, System.Int32& height, System.Int32& client_width, System.Int32& client_height) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Control.UpdateBounds () [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Control.WmWindowPosChanged (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.ScrollableControl.WndProc (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.ContainerControl.WndProc (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Form.WmWindowPosChanged (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Form.WndProc (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
  at System.Windows.Forms.NativeWindow.WndProc (IntPtr hWnd, Msg msg, IntPtr wParam, IntPtr lParam) [0x00000] in <filename unknown>:0 
```

**Comment by JerryLumpkins** [comment] 2015-07-04 11:19
The commit is properly executed, and my repo is properly updated. But, I have to restart gitextensions every time I do anything that opens the commit window. As soon as the window is closed after hitting commit, it crashes.

**Comment by UncleVasya** [comment] 2015-08-07 13:54
Duplicate of #2566.

**Closed** 2015-11-05 12:13 UTC
Labels: bug, linux/mono, up-for-grabs
