### ISSUE TITLE
Left panel toggle state is not stored/restored in 3.5 RC 1

### ISSUE THREAD

**Issue by slaut** [gitextensions/gitextensions#9089] opened 2021-04-19 05:13 UTC
## Current behaviour

Changing toggle for left panel in main window to disabled is not stored and restored at next start

## Expected behaviour

State of left panel toggle should be restored on next start

## Steps to reproduce

- disable left panel
- restart GitExtensions
-> panel is visible again

Split view layout and Commit info position is stored correct

## Did this work in previous version of GitExtensions

Yes: latest stable release (3.4)

## Environment

- Git Extensions 3.5.0.11509
- Build 009d10c765a90aa00e043e40d5117256b793bc8c (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4300.0
- DPI 144dpi (150% scaling)

**Comment by mstv** [comment] 2021-04-19 19:06
Duplicate of #9000

**Closed by mstv** 2021-04-19 19:06 UTC
