### ISSUE TITLE
[NBug] Unable to parse object ID "".

### ISSUE THREAD

**Issue by Abutayar** [gitextensions/gitextensions#6796] opened 2019-06-13 16:50 UTC
## Current behavior

1) When I like to try to open repro from recently open repro below mention error occur
1) Same error when I try to fetch all 

## Error Details
```
System.FormatException: Unable to parse object ID "".
   at GitUIPluginInterfaces.ObjectId.Parse(String s)
   at GitCommands.GitModule.GetCurrentCheckout()
   at GitUI.RevisionGridControl.ForceRefreshRevisions()
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

Refer error SS :
![Screenshot (2)](https://user-images.githubusercontent.com/29305367/59451559-54dbb900-8e29-11e9-9905-1da9e569ea60.png)

**Comment by Abutayar** [comment] 2019-06-13 16:56
> Potential duplicates:
> 
> * [![#6602](https://camo.githubusercontent.com/e792bffa4506ef722a60a992e9a90ce7688f3614/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f253233363630322532302535424e4275672535445f556e61626c65253230746f2532307061727365253230676974253230636f6d6d616e642532306f75747075742e2d73696d696c61726974792532303632253235253230253246253230636f6d6d656e7473253230312d6c69676874677265792e737667)](6602)
> * [![#6644](https://camo.githubusercontent.com/e043fded48907c470fab34ff90b46d374eb34c90/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f253233363634342532302535424e4275672535445f556e61626c65253230746f25323070617273652532306f626a65637425323049442532302532322532322e2d73696d696c6172697479253230313030253235253230253246253230636f6d6d656e7473253230322d677265656e2e737667)](6644)
> * [![#6673](https://camo.githubusercontent.com/b7862bd20ca529e9c87f39f30a07825d6d3a4419/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f253233363637332532302535424e4275672535445f556e61626c65253230746f2532307061727365253230676974253230636f6d6d616e642532306f75747075742e2d73696d696c61726974792532303632253235253230253246253230636f6d6d656e7473253230322d677265656e2e737667)](6673)
> * [![#6745](https://camo.githubusercontent.com/d0305133b76d37f16a93209b73a0de01c29a65df/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f253233363734352532302535424e4275672535445f556e61626c65253230746f25323070617273652532306f626a65637425323049442532302532322532322e2d73696d696c6172697479253230313030253235253230253246253230636f6d6d656e7473253230352d6f72616e67652e737667)](6745)
> * [![#6764](https://camo.githubusercontent.com/fc4be800fdf3f47c948dfd241b07b43e1a8d9411/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f253233363736342532302535424e4275672535445f556e61626c65253230746f25323070617273652532306f626a65637425323049442532302532322532322e2d73696d696c6172697479253230313030253235253230253246253230636f6d6d656e7473253230322d677265656e2e737667)](6764)
> * [![#6786](https://camo.githubusercontent.com/46313f29cc518fd5d289c9f75d82815276b344e4/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f253233363738362532302535424e4275672535445f556e61626c65253230746f25323070617273652532306f626a65637425323049442532302532322532322e2d73696d696c6172697479253230313030253235253230253246253230636f6d6d656e7473253230342d677265656e2e737667)](6786)
> * [![#6787](https://camo.githubusercontent.com/a9e9087f20ba9bbc32110030041ab1b346677f62/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f253233363738372532302535424e4275672535445f556e61626c65253230746f25323070617273652532306f626a65637425323049442532302532322532322d73696d696c61726974792532303934253235253230253246253230636f6d6d656e7473253230312d6c69676874677265792e737667)](6787)

I know there are 

I just want to know if there are any system requirements to run git extension  on windows 10
because is always get crashing.

**Comment by gerhardol** [comment] 2019-06-13 19:14
Duplicate of #6512 
Corrected in #6513, included in 3.2 (just after the 3.1 fork)
It seems like the problem occurs with invalid repos

**Closed by gerhardol** 2019-06-13 19:14 UTC
Labels: potential-duplicate

**Comment by Abutayar** [comment] 2019-06-14 07:14
when will 3.2 will be available? @gerhardol

**Comment by gerhardol** [comment] 2019-06-15 17:43
Milestone is set for Sep 1
https://github.com/gitextensions/gitextensions/milestone/40

You can try the portable build for master meanwhile.

**Comment by Abutayar** [comment] 2019-06-15 18:13
Thank you!!! 😀

Will try the portable one.

Best of luck for future release.
