### ISSUE TITLE
[NBug] Illegal characters in path.

### ISSUE THREAD

**Issue by Kuinox** [gitextensions/gitextensions#6982] opened 2019-08-02 16:14 UTC
##  Current behaviour
Git Extension fail to clone a github wiki repository, and crash when trying to stage changements on this repository.

Git can clone this repository without any issue.

## Expected behaviour
Git Extension should clone without any problem the repository.

## Steps to reproduce

Clone [https://github.com/SimpleGitVersion/SGV-Net.wiki.git](https://github.com/SimpleGitVersion/SGV-Net.wiki.git)

Close the Git Extensions dialog after the failed attempt.
Open the cloned repository with Git Extensions.
Stage all the changes.

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at GitCommands.FullPathResolver.Resolve(String path)
   at GitUI.Editor.FileViewer.<ShowOrDeferAsync>g__GetFileLength|88_0(<>c__DisplayClass88_0& )
   at GitUI.Editor.FileViewer.ViewCurrentChanges(String fileName, String oldFileName, Boolean staged, Boolean isSubmodule, Func`1 getStatusAsync, Action openWithDifftool)
   at GitUI.Editor.FileViewer.ViewCurrentChanges(GitItemStatus item, Boolean isStaged, Action openWithDifftool)
   at GitUI.CommandsDialogs.FormCommit.<SetSelectedDiffAsync>d__130.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.FormCommit.<>c__DisplayClass129_0.<<ShowChanges>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment] 2019-08-02 22:29
Duplicate of #6755 
(separate exception but the same stacktrace)

This is maybe corrected in master, at least giving better information of the issue.
Please try the canary build

**Comment by Kuinox** [comment] 2019-08-02 22:52
I'm testing this on another PC.   
Tried this build: https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts   
Both issues are still here.
The stacktrace dumped is the second problem i had.   

You can easily reproduce when you clone this repo: https://github.com/SimpleGitVersion/SGV-Net.wiki.git

**Comment by RussKie** [comment] 2019-08-03 09:27
Here's the issue - the repo contians a file that contains `?` in its name - this is an invalid character on Windows.

```
"C:\Program Files\Git\bin\git.exe" clone -v --recurse-submodules --progress "https://github.com/SimpleGitVersion/SGV-Net.wiki.git" "C:/Development/SGV-Net.wiki"
Cloning into 'C:/Development/SGV-Net.wiki'...
POST git-upload-pack (175 bytes)
remote: Enumerating objects: 375, done.
Rremote: Total 375 (delta 0), reused 0 (delta 0), pack-reused 375ece
Receiving objects:  67% (252/375)
Receiving objects: 100% (375/375), 51.27 KiB | 954.00 KiB/s, done.
Resolving deltas: 100% (228/228), done.
error: unable to create file How-does-SimpleGitVersion-work?.md: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

Done

Press Enter or Esc to close console...
```

There is nothing we can do about it. You could ask the owners of the repo to rename the file.

**Comment by Kuinox** [comment] 2019-08-03 13:18
You are right, i didn't saw the errors while cloning with git:  

> error: unable to create file How-does-SimpleGitVersion-work?.md: Invalid argument
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.

**Closed** 2019-08-03 14:12 UTC
Labels: area: user experience, type: bug
