### ISSUE TITLE
[NBug] Unable to parse object ID "fatal: not a git repository (or ...

### ISSUE THREAD

**Issue by manuelspezzani** [gitextensions/gitextensions#6592] opened 2019-05-17 16:14 UTC
## Error Details
```
System.FormatException: Unable to parse object ID "fatal: not a git repository (or any of the parent directories): .git".
   at GitUIPluginInterfaces.ObjectId.Parse(String s)
   at GitCommands.GitModule.GetCurrentCheckout()
   at GitUI.RevisionGridControl.ForceRefreshRevisions()
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.14393.0
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-05-17 19:43
How to reproduce?

**Comment by manuelspezzani** [comment] 2019-05-17 20:01
This was consistently reproducing the issue on my machine:

- open a valid git repository
- delete the .git folder
- try to fetch from a remote


Definitely low priority IMHO.

Il Ven 17 Mag 2019, 21:43 Gerhard Olsson <notifications@github.com> ha
scritto:

**Comment by RussKie** [comment] 2019-05-18 06:18
A fix should be to show a user friendly error message and then close the (no longer) repo and go to the dashboard.

> - open a valid git repository 
> - delete the .git folder
> - try to fetch from a remote

May I ask why?

**Comment by manuelspezzani** [comment] 2019-05-18 07:17
You don't want to know! :)

I was working on a build script and accidentally deleted the wrong folder.
As I was saying, it's definitely a low priority: as far as I can tell, no
one should do that on purpose.

I decided to report the issue anyway just because of the crash.



Il Sab 18 Mag 2019, 08:18 Igor Velikorossov <notifications@github.com> ha
scritto:

**Comment by RussKie** [comment] 2019-05-18 07:19
🤣👍

**Comment by gerhardol** [comment] 2019-06-16 11:06
Duplicate of #6512

**Closed** 2019-07-25 22:48 UTC
Labels: area: user experience, good first issue, up for grabs
