### ISSUE TITLE
Null reference exceptions

### ISSUE THREAD

**Issue by ruperthawkes** [gitextensions/gitextensions#6070] opened 2019-01-08 16:36 UTC
## Current behaviour

When I try and create a pull request I get the following exception.

## Expected behaviour

It creates a PR on github

## Steps to reproduce

Install 3.00.00.4433 on Windows 10 and try and create a PR

## Screenshots

![image](https://user-images.githubusercontent.com/6460935/50844741-4f061700-1363-11e9-9aaf-5dc2d36ba5aa.png)

![image](https://user-images.githubusercontent.com/6460935/50844839-7eb51f00-1363-11e9-9549-e87fc27b53d3.png)

## Did this work in previous version of GitExtensions

Yes, all versions prior to v3

## Environment

- GitExtensions version:  version 3.00.00.4433
- GIT version: 2.20.0
- OS version: Windows 10
- .NET version: ?

**Comment by vbjay** [comment] 2019-01-08 16:47
Use our issue templates.  They are there for a reason.  
![image](https://user-images.githubusercontent.com/3629489/50845575-3124bc00-133b-11e9-816f-9d477c71c52f.png)

**Comment by ruperthawkes** [comment] 2019-01-09 09:22
Updated, apologies

**Comment by RussKie** [comment] 2019-01-09 10:45
The problem is with the check for the new version - please have a look at the last image posted.

Duplicate of #5928

**Closed by RussKie** 2019-01-09 10:45 UTC

**Comment by ruperthawkes** [comment] 2019-01-09 11:00
Is there a resolution?

**Comment by RussKie** [comment] 2019-01-09 11:09
I think you just need to disable the check for updates
![image](https://user-images.githubusercontent.com/4403806/50895775-28c3a280-145b-11e9-9b72-ed4a51f988f8.png)

**Comment by ruperthawkes** [comment] 2019-01-09 11:16
I have disabled and still get the error as reported in the first screen shot
