### ISSUE TITLE
[NBug] Overflow error.

### ISSUE THREAD

**Issue by daniel-beet** [gitextensions/gitextensions#6633] opened 2019-05-22 09:56 UTC
## Current behaviour

Attempting to display a diff of an UTF16LE-BOM file causes crash.

## Expected behaviour

Expect no crash and that file is displayed as text initially without forcing it.

## Steps to reproduce

Select a UTF16LE-BOM file from a commit to display diff (will not as claims is binary)
Right click and select "Treat all files as text"
See Unicode text (with double byte chars)
Change encoding dropdown to "Unicode"
Get error.

## Error Details
```
System.OverflowException: Overflow error.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.FillRectangle(Brush brush, Single x, Single y, Single width, Single height)
   at System.Drawing.Graphics.FillRectangle(Brush brush, RectangleF rect)
   at ICSharpCode.TextEditor.TextView.DrawDocumentWord(Graphics g, String word, Point position, Font font, Color foreColor, Brush backBrush)
   at ICSharpCode.TextEditor.TextView.PaintLinePart(Graphics g, Int32 lineNumber, Int32 startColumn, Int32 endColumn, Rectangle lineRectangle, Int32 physicalXPos)
   at ICSharpCode.TextEditor.TextView.PaintDocumentLine(Graphics g, Int32 lineNumber, Rectangle lineRectangle)
   at ICSharpCode.TextEditor.TextView.Paint(Graphics g, Rectangle rect)
   at ICSharpCode.TextEditor.TextArea.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-07-25 21:56
See also #6934 for reproduce info (I still cannot reproduce)

**Comment by palver123** [comment] 2019-08-16 17:48
I don't know about this issue, but I think I have found the solution of #7023 .

**Comment by RussKie** [comment] 2019-08-17 21:44
Closing in favour of  #7023.

**Closed by RussKie** 2019-08-17 21:44 UTC
Labels: status: needs review, type: bug, type: dependency bug, up for grabs
