### ISSUE TITLE
Inconsistent revision selection after repo change

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#8134] opened 2020-05-22 22:02 UTC
## Current behaviour

Occasionally, `Navigate to parent (Ctrl+P)` does not work correctly the first time after reload due to a repo change, e.g. `fetch` or `commit`.
I guess the parent of a neighbor row (one above or below the selected row) gets selected.

Occasionally, `CheckAndRepairInitialRevision` is called while `_gridView.RowCount` is `0` yet. It calls `SetSelectedIndex` with a sensible `index`, which results in an exception, which is ignored silently.
I think this causes the first issue because it hinders the call of `OnGridViewSelectionChanged`, which updates `_latestSelectedRowIndex`, which is evaluated for `Ctrl+P`.

(In addition, a multi-selection is not restored after forced refresh.)

## Expected behaviour

guess what

## Steps to reproduce

don't know

## Did this work in previous version of GitExtensions

don't know

## Environment

- Git Extensions 3.3.0
- Build 8da72f42cf02b377fbdb9ccccf1747f1b3f53e46
- Git 2.26.0.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

## Diagnostics

Code review revealed some unnecessary calls but nothing substantially wrong.
https://github.com/gitextensions/gitextensions/commit/1b65ed40b68fbba40a6b935a8c3108d2b9452bef

**Comment by gerhardol** [comment] 2020-05-23 09:03
Duplicate of #8135

**Closed by gerhardol** 2020-05-23 09:03 UTC
Labels: :beetle: type: bug
