### ISSUE TITLE
Revision graph does not draw single-commit imports that are adjacent to a branch line.

### ISSUE THREAD

**Issue by otac0n** [gitextensions/gitextensions#642] opened 2011-10-04 02:40 UTC
Revision graph does not draw single-commit imports that are adjacent to a branch line.

I'll get a screenie here soon.

**Comment by RussKie** [comment] 2018-06-22 15:38
2.51.02 and the current master at 6077fa2b92fae79394c93b7f76af0eb2f97d74ee are both showing the following:

unmerged:
![image](https://user-images.githubusercontent.com/4403806/41784805-1c3701a8-7684-11e8-854b-17e1a2e0eae1.png)
merged:
![image](https://user-images.githubusercontent.com/4403806/41784917-6c970de6-7684-11e8-8460-6ab2e742dc6e.png)

if you look closely the square for the dangling commit is there, but it is overlapped by the branch label.
@drewnoakes in your v3-ux branch at 54742a9df3cc83a5da7ca28d85c777dc6fa7e392 the square seems either missing or hidden:
![image](https://user-images.githubusercontent.com/4403806/41785239-59acf79e-7685-11e8-8af4-428904650294.png)

The issue is very old and even a medium priority, but maybe worth checking, if you tinkering with the grid.

**Comment by RussKie** [comment] 2018-06-22 15:39
2.51.02 and the current master at 6077fa2b92fae79394c93b7f76af0eb2f97d74ee are both showing the following:

unmerged:
![image](https://user-images.githubusercontent.com/4403806/41784805-1c3701a8-7684-11e8-854b-17e1a2e0eae1.png)
merged:
![image](https://user-images.githubusercontent.com/4403806/41784917-6c970de6-7684-11e8-8460-6ab2e742dc6e.png)

if you look closely the square for the dangling commit is there, but it is overlapped by the branch label.
@drewnoakes in your v3-ux branch at 54742a9df3cc83a5da7ca28d85c777dc6fa7e392 the square seems either missing or hidden:
![image](https://user-images.githubusercontent.com/4403806/41785239-59acf79e-7685-11e8-8af4-428904650294.png)

The issue is very old and not even of a medium priority, but maybe worth checking, if you are tinkering with the grid.

**Closed** 2023-10-12 08:49 UTC
Labels: area: user experience, up-for-grabs, :eyeglasses: status: needs review
