### ISSUE TITLE
Toolbar position is not saved or restored

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#8680] opened 2020-12-16 12:36 UTC
## Current behaviour

Since #8572, I [always](https://github.com/gitextensions/gitextensions/pull/8572#issuecomment-734340761) end up with this toolbar at startup:
![image](https://user-images.githubusercontent.com/460196/100364490-8127cd00-2ffe-11eb-8419-99404f78f46b.png)

Even if I move the toolbars. Even when only on instance is opened.

Even with #8679 fix (to only save the toolbar settings)

## Expected behaviour

I can configure the toolbar position and it is saved (or restored)  well.

## Steps to reproduce

1. Get a dev version of GE (portable from CI or your custom version) and launch it
2. Change toolbar setup
3. Restart
4. See toolbar position configuration is the same as initally

## Screenshots

See above.

## Did this work in previous version of GitExtensions

Never since the feature was introduced... 

## Environment

- Git Extensions 33.33.33
- Build 3245408651bd658ee636e7c3b57f3a02bbe4abf4
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4261.0
- DPI 192dpi (200% scaling)

## Diagnostics

The main goal to opening this issue is:

How can I debug it easily?
Where the configuration data are stored?

**Comment by mstv** [comment] 2020-12-16 20:04
I cannot reproduce exactly this but:
- When positioned as in the issue screenshot, the original layout is restored. So I have kind of the opposite behavior.
- Perhaps it depends on the scaling factor. (I will not touch this setting of 100% on this machine!)
- (When moving the toolbars, they jump around in an unexpected way.)
- When positioned stacked vertically (just fooling about), the lower toolbar is moving to the right with every start. After 3rd:
![grafik](https://user-images.githubusercontent.com/36601201/102400246-e9f0dc80-3fe1-11eb-9610-a43aecd6f9a8.png)

**Comment by pmiossec** [comment] 2020-12-16 21:40
>     * Perhaps it depends on the scaling factor. (I will not touch this setting of 100% on this machine!)

I will give it a try to see if that changes the behavior. 

>     * (When moving the toolbars, they jump around in an unexpected way.)

The same. And it is a pain to successfully arrange them...

**Comment by RussKie** [comment] 2020-12-17 00:47
> * When positioned stacked vertically (just fooling about), the lower toolbar is moving to the right with every start. After 3rd:
>   ![grafik](https://user-images.githubusercontent.com/36601201/102400246-e9f0dc80-3fe1-11eb-9610-a43aecd6f9a8.png)

This looks like a Windows Forms bug, I can repro it too. https://github.com/dotnet/winforms/issues/new/choose 😉

**Comment by RussKie** [comment] 2020-12-17 07:10
This is very gnarly one... I've spent several hours trying different thigs, but so far I couldn't get it working reliably. Reading and then setting the same location moves a toolbar laterally.

**Comment by RussKie** [comment] 2021-01-03 13:29
The toolbar gets pushed by something:
![image](https://user-images.githubusercontent.com/4403806/103479684-7f360280-4e23-11eb-933f-983b8d7ce371.png)

It is wild, and requires a deeper investigation. It's plausible there's something in our codebase that's causing it, similar to the weird behaviours observed in https://github.com/gitextensions/gitextensions/issues/8698#issuecomment-753476283.

**Closed** 2021-01-18 12:57 UTC
Labels: :beetle: type: bug, :construction: status: in progress, area: user experience

**Comment by RussKie** [comment] 2021-09-20 10:26
I've debugged the Windows Forms source, and it looks like the implementation isn't working correctly when a toolstrip panel has non-zero padding.

The following workaround appears to yield the expected results:
```cs
        public override void OnLoad(EventArgs e)
        {
            // Restore the toolbars layout
            ToolStripManager.LoadSettings(this, "toolsettings");

            // Apply the padding
            this.toolPanel.TopToolStripPanel.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
        }

        protected override void OnFormClosing(FormClosingEventArgs e)
        {
            // Reset padding to zero before saving
            this.toolPanel.TopToolStripPanel.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);

            // Persist the toolbars layout
            ToolStripManager.SaveSettings(this, "toolsettings");
        }
```
