### ISSUE TITLE
[NBug] Value must not be null.

### ISSUE THREAD

**Issue by zmaten** [gitextensions/gitextensions#11542] opened 2024-01-23 13:46 UTC
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.26
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.Exception: Value must not be null.
   at void Microsoft.Validates.Fail(string message) in C:/projects/gitextensions/GitExtUtils/Validates.cs:line 35
   at async void GitUI.CommandsDialogs.FormCheckoutBranch.Branches_SelectedIndexChanged(object sender, EventArgs e)+(?) => { } in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCheckoutBranch.cs:line 489
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

This was on a freshly cloned repo with just "develop" and "master" branches on my local. I was trying to checkout out a remote branch called "release/5.114"

### Steps to reproduce

Right click branch in origin.
Click 'Checkout remote branch'

### Did this work in previous version of GitExtensions?

Yes

**Comment by gerhardol** [comment] 2024-01-23 15:06
Duplicate of #11498 
Fixed in #11500

**Closed by gerhardol** 2024-01-23 15:06 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
