### ISSUE TITLE
Every time I tryied to click on a source file via tab "File tree", GitExtensions stops responding

### ISSUE THREAD

**Issue by renfengyue** [gitextensions/gitextensions#10509] opened 2022-12-12 06:04 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

Every time I tryied to click on a source file via tab "File tree", GitExtensions stops responding.

### Steps to reproduce

1. Open GitExtensions.
2. Switch to "File tree"
3. Click one source file.

### Did this work in previous version of GitExtensions?

It does not happen on GitExtensions v3.x version.

### Diagnostics

![Uploading image.png…]()

**Comment by renfengyue** [comment] 2022-12-12 06:04
![screenshot](https://user-images.githubusercontent.com/3722555/206971879-5e3700f8-9b30-4656-9d81-afe4a8c77330.jpg)

**Comment by RussKie** [comment] 2022-12-12 07:15
Is it loading blame by any chance?

**Comment by pmiossec** [comment] 2022-12-12 08:42
> Is it loading blame by any chance?

It's a really good question.
Is it the filtree that is slow to open? or the content of the selected file which is slow to display (because it blames the file)?

An animated image to show the problem taken with a tool like https://www.screentogif.com/ would be of great help...

**Comment by mstv** [comment] 2022-12-12 22:01
@renfengyue, do you see one or two panes right of the file tree?
Or even none? Then the contents panel right of the splitter might be collapsed.
The application did not even manage to select the clicked file in the TreeView.
(For folders, nothing is displayed.)

**Comment by RussKie** [comment] 2022-12-20 05:15
Duplicate of #10511

**Closed** 2022-12-20 05:16 UTC
