### ISSUE TITLE
[NBug] `The directory name is invalid` crash creating paths that are too long during new worktree creation

### ISSUE THREAD

**Issue by vijaysitaram** [gitextensions/gitextensions#8481] opened 2020-09-26 18:26 UTC
## Current behaviour
I attempted to create a worktree against a branch which had some long paths that were close to exceeding max length in my current repo location. With the new worktree folder location, these paths were too long, and at least one target file could not be created. It said there was a fatal error resetting index to head, and after dismissing the worktree creation dialog's error, I got the crash report dialog

## Expected behaviour
If it cannot create the new worktree, delete the partially created worktree folder and revert back to the state I was in before trying to create it.

## Steps to reproduce
1. Create a local branch that contains some long folder + file path names that get close to, but don't exceed the max length for Windows paths in your current repo
1. Create a new worktree for this branch at a base location that's much longer than the previous location, such that the paths mentioned exceed the max allowable length, and allow the process to continue and then fail.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.ExecutableExtensions.<ExecuteAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.get_GitCommonDirectory()
   at GitCommands.Settings.ConfigFileSettings.CreateLocal(GitModule module, ConfigFileSettings lowerPriority, SettingLevel settingLevel, Boolean allowCache)
   at GitCommands.Settings.ConfigFileSettings.CreateEffective(GitModule module)
   at GitCommands.GitModule.get_EffectiveConfigFile()
   at GitCommands.GitModule.get_FilesEncoding()
   at GitUI.Editor.FileViewer.encodingToolStripComboBox_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ToolStripComboBox.HandleSelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at System.Windows.Forms.ToolStripComboBox.set_SelectedIndex(Int32 value)
   at GitUI.Editor.FileViewer.<set_Encoding>b__58_0()
   at GitUI.GitUIExtensions.<InvokeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
None

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4220.0
- DPI 96dpi (no scaling)

**Comment by vijaysitaram** [comment] 2020-09-26 20:01
Sadly, it appears some important information telling me what you think is missing, is missing from the auto-close. Can I re-open this, or will it cause it to just auto-close again?

**Comment by pmiossec** [comment] 2020-09-26 20:09
Your report is good and that's a new issue. So everything is OK and the issue deserves to be reopened.

That's just the normal workflow where the bot is closing automatically the new issues..

**Comment by vijaysitaram** [comment] 2020-09-26 20:23
Thanks, @pmiossec. It would be nice if the wording of the message were changed to indicate it is expected to auto-close until it is reviewed by a curator. I'm very new to GitHub and the open source community, and the current language from the bot is extremely dismissive and discouraging of my contribution in this case.

**Comment by vijaysitaram** [comment] 2020-09-26 20:25
It's a bit similar to another worktree creation crashI reported a couple months ago or may have the same root fix, even if the symptoms are slightly different: #8251

**Comment by RussKie** [comment] 2020-09-27 08:07
> It would be nice if the wording of the message were changed to indicate it is expected to auto-close until it is reviewed by a curator.

Thank you for the feedback. How would you reword it?

**Comment by mstv** [comment] 2020-09-27 08:36
`⚠️ The sections below must be filled in and this text must be removed or the issue will be closed.`

I have missed to remove this myself a few times.

**Comment by mstv** [comment] 2020-09-27 08:39
The UX should improve with #8278.

**Comment by RussKie** [comment] 2020-09-27 09:38
...or #8358 <https://github.com/gitextensions/gitextensions/pull/8358> :)

**Comment by vijaysitaram** [comment] 2020-09-28 14:27
> 
> 
> > It would be nice if the wording of the message were changed to indicate it is expected to auto-close until it is reviewed by a curator.
> 
> Thank you for the feedback. How would you reword it?
It depends -- do you have more specific info/heuristics on how the bot either works now, or the ideal state of how it should work? I'd say the message returned should probably vary depending on whether the submission really is lacking the requisite field information, or if it's just part of auto-close workflow even when the fields are seemingly filled out correctly. If the answer there is that we don't want to get that fancy, I could probably suggest some wording that works for either case and covers all the bases.

> 
> 
> `⚠️ The sections below must be filled in and this text must be removed or the issue will be closed.`
> 
> I have missed to remove this myself a few times.
I definitely did that this time too, and had to go back and edit my post to remove it. I thought maybe it was still mad about that for some reason.

**Comment by RussKie** [comment] 2020-10-09 07:46
Thank you for feedback.

I disabled the bot for now.

**Comment by gerhardol** [comment] 2021-04-19 21:38
Duplicate of #9091 Forward duplicate, continue discussion there.
Please try 3.5 RC1 where the error is displayed with more details

**Closed by gerhardol** 2021-04-19 21:38 UTC
Labels: area: worktree
