### ISSUE TITLE
After opening the project and minimizing it, clicking on the toolbar cannot restore

### ISSUE THREAD

**Issue by kanyways** [gitextensions/gitextensions#10598] opened 2023-01-03 07:15 UTC
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

After opening the project and minimizing it, clicking on the toolbar cannot restore

### Steps to reproduce

Open GitExtensions, select the project, and click Minimize.
Cannot revert to previous window state when clicking again from toolbar.
But just don't open the project. You can open and restore the size of the software in the toolbar.

**Comment by gerhardol** [comment] 2023-01-06 14:23
Duplicate of #10398 
See https://github.com/gitextensions/gitextensions/issues/10398#issuecomment-1313378235 for a workaround

**Closed by gerhardol** 2023-01-06 14:23 UTC
Labels: :eyeglasses: status: needs review
