### ISSUE TITLE
Alt+C in main window has a conflict between menu and commit button

### ISSUE THREAD

**Issue by johndog** [gitextensions/gitextensions#6368] opened 2019-03-12 06:54 UTC
## Current behaviour

Tapping the alt key shows some of the accelerators:

![image](https://user-images.githubusercontent.com/22213780/54180292-7d35cf00-4458-11e9-9dca-f49115b9e241.png)

The command menu gets and underlined C.  However, Alt+C brings up the Commit dialog, even though the commit button showed no accelerators.

## Expected behaviour

If C is underlined in the Commands menu, then Alt+C should raise the command-menu.  If Alt+C brings up the commit dialog, then the C on the commit dialog should be underlined when holding down Alt.

## Did this work in previous version of GitExtensions

Unknown

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.vfs.1.1.97.g8af1f39
- Microsoft Windows NT 10.0.18353.0
- .NET Framework 4.8.3749.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-03-14 22:31
The default hotkey for Commit is Ctrl-Commit.
Have you changed the setup?

Also if I set the hotkey manually, the command menu drops down.

**Comment by johndog** [comment] 2019-03-14 22:54
I have not changed the setup.  In fact, it is mapped to Ctrl+Space (which may be what you meant to type, since I can't find a commit key on my keyboard :-P ).  Ctrl+Space _also_ brings up the Commit dialog.

This is bizarre.

**Comment by gerhardol** [comment] 2019-03-14 23:16
> since I can't find a commit key on my keyboard

I should maybe stop commenting when I need to sleep?

There is something else here too then.

**Comment by illfated** [comment] 2019-03-15 00:19
Confirmed, both Ctrl+Space and Alt+C opens up the commit window.
(Alt+C also opens the Command menu just before commit window opens.)

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)

**Comment by ignacioerrico** [comment] 2019-03-15 10:44
I confirm too that both `CTRL`+`Space` and `ALT`+`C` open up the commit window. However, the *Command* menu is not displayed. (I tried it in a dual monitor system, where the commit window opens up in another screen. There is no visible effect on the *Command* menu being displayed.)

And since we're at it, I see that **not all menu items have an underlined letter when pressing `ALT`**. For example, the *View* menu is displayed with when I press `ALT`+`V`, but the letter V is not underlined when I press the `ALT` key.

![image](https://user-images.githubusercontent.com/3200214/54426006-0ed26480-4717-11e9-960d-86033de0518b.png)

**Comment by gerhardol** [comment] 2019-03-17 15:59
Can someone that see this behavior debug the problem?

> And since we're at it, I see that not all menu items have an underlined letter when pressing ALT. 

Same for me

**Comment by mstv** [comment] 2019-03-17 23:51
Cannot reproduce Alt+C opening the Commit dialog neither on Win7 nor on Win10.

**Comment by DmitryZhelnin** [comment] 2019-03-18 22:38
> Can someone that see this behavior debug the problem?

Reproducible in Git Extensions 3.0.2.5232 Build 23b6f51.
Somehow `_toolStripGitStatus` of `FormBrowse` responds to Alt+C.

Not reproducible in the latest master.

**Comment by gerhardol** [comment] 2019-03-23 00:20
Closing, as this seem to be closed in master

**Closed by gerhardol** 2019-03-23 00:20 UTC
Labels: status: more info requested
