### ISSUE TITLE
I get exception when try to open repository using Mono

### ISSUE THREAD

**Issue by Dr-klo** [gitextensions/gitextensions#4090] opened 2017-10-23 13:03 UTC
Steps: run GitExtensions on mac OS using mono.
open dialog "Open" , type path to existing repository
click "Open"
Result:  
```
System.IO.IOException: Too many open files
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <ac812cae460544af83bd6cf54c5eee87>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean isAsync, System.Boolean anonymous) [0x00000] in <ac812cae460544af83bd6cf54c5eee87>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access) [0x00000] in <ac812cae460544af83bd6cf54c5eee87>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess)
  at System.Configuration.InternalConfigurationHost.OpenStreamForWrite (System.String streamName, System.String templateStreamName, System.Object& writeContext) [0x0001e] in <3414a9f4d8fa4e5aaf6f3732ead4a289>:0 
  at System.Configuration.Configuration.Save (System.Configuration.ConfigurationSaveMode saveMode, System.Boolean forceSaveAll) [0x00032] in <3414a9f4d8fa4e5aaf6f3732ead4a289>:0 
  at System.Configuration.CustomizableFileSettingsProvider.SaveProperties (System.Configuration.ExeConfigurationFileMap exeMap, System.Configuration.SettingsPropertyValueCollection collection, System.Configuration.ConfigurationUserLevel level, System.Configuration.SettingsContext context, System.Boolean checkUserLevel) [0x00231] in <ead0603699f14fb4bc97df2618539636>:0 
  at System.Configuration.CustomizableFileSettingsProvider.SetPropertyValues (System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyValueCollection collection) [0x0003a] in <ead0603699f14fb4bc97df2618539636>:0 
  at System.Configuration.LocalFileSettingsProvider.SetPropertyValues (System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyValueCollection values) [0x00000] in <ead0603699f14fb4bc97df2618539636>:0 
  at System.Configuration.ApplicationSettingsBase.Save () [0x0008c] in <ead0603699f14fb4bc97df2618539636>:0 
  at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.Dashboard.SaveSplitterPositions () [0x0003f] in <c387cdaf9bb74ffa906fd23129b41844>:0 
  at (wrapper remoting-invoke-with-check) GitUI.CommandsDialogs.BrowseDialog.DashboardControl.Dashboard:SaveSplitterPositions ()
  at GitUI.CommandsDialogs.FormBrowse.HideDashboard () [0x00015] in <c387cdaf9bb74ffa906fd23129b41844>:0 
  at GitUI.CommandsDialogs.FormBrowse.SetGitModule (System.Object sender, GitCommands.GitModuleEventArgs e) [0x00058] in <c387cdaf9bb74ffa906fd23129b41844>:0 
  at GitUI.CommandsDialogs.FormBrowse.OpenToolStripMenuItemClick (System.Object sender, System.EventArgs e) [0x00018] in <c387cdaf9bb74ffa906fd23129b41844>:0 
  at System.Windows.Forms.ToolStripItem.OnClick (System.EventArgs e) [0x00019] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.ToolStripMenuItem.OnClick (System.EventArgs e) [0x00090] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.ToolStripMenuItem.HandleClick (System.Int32 mouse_clicks, System.EventArgs e) [0x00000] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.ToolStripItem.FireEvent (System.EventArgs e, System.Windows.Forms.ToolStripItemEventType met) [0x00054] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripItem:FireEvent (System.EventArgs,System.Windows.Forms.ToolStripItemEventType)
  at System.Windows.Forms.ToolStrip.OnMouseUp (System.Windows.Forms.MouseEventArgs mea) [0x00048] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.ToolStripDropDown.OnMouseUp (System.Windows.Forms.MouseEventArgs mea) [0x00000] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.Control.WmLButtonUp (System.Windows.Forms.Message& m) [0x00078] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x001b4] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.ScrollableControl.WndProc (System.Windows.Forms.Message& m) [0x00000] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.ToolStrip.WndProc (System.Windows.Forms.Message& m) [0x00000] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.ToolStripDropDown.WndProc (System.Windows.Forms.Message& m) [0x00017] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x00085] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 

Unhandled Exception:
System.IO.IOException: Too many open files
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <ac812cae460544af83bd6cf54c5eee87>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean isAsync, System.Boolean anonymous) [0x00000] in <ac812cae460544af83bd6cf54c5eee87>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access) [0x00000] in <ac812cae460544af83bd6cf54c5eee87>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess)
  at System.Configuration.InternalConfigurationHost.OpenStreamForWrite (System.String streamName, System.String templateStreamName, System.Object& writeContext) [0x0001e] in <3414a9f4d8fa4e5aaf6f3732ead4a289>:0 
  at System.Configuration.Configuration.Save (System.Configuration.ConfigurationSaveMode saveMode, System.Boolean forceSaveAll) [0x00032] in <3414a9f4d8fa4e5aaf6f3732ead4a289>:0 
  at System.Configuration.CustomizableFileSettingsProvider.SaveProperties (System.Configuration.ExeConfigurationFileMap exeMap, System.Configuration.SettingsPropertyValueCollection collection, System.Configuration.ConfigurationUserLevel level, System.Configuration.SettingsContext context, System.Boolean checkUserLevel) [0x00231] in <ead0603699f14fb4bc97df2618539636>:0 
  at System.Configuration.CustomizableFileSettingsProvider.SetPropertyValues (System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyValueCollection collection) [0x0003a] in <ead0603699f14fb4bc97df2618539636>:0 
  at System.Configuration.LocalFileSettingsProvider.SetPropertyValues (System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyValueCollection values) [0x00000] in <ead0603699f14fb4bc97df2618539636>:0 
  at System.Configuration.ApplicationSettingsBase.Save () [0x0008c] in <ead0603699f14fb4bc97df2618539636>:0 
  at GitUI.CommandsDialogs.FormBrowse.SaveSplitterPositions () [0x00069] in <c387cdaf9bb74ffa906fd23129b41844>:0 
  at GitUI.CommandsDialogs.FormBrowse.OnClosing (System.ComponentModel.CancelEventArgs e) [0x00007] in <c387cdaf9bb74ffa906fd23129b41844>:0 
  at System.Windows.Forms.Form.FireClosingEvents (System.Windows.Forms.CloseReason reason, System.Boolean cancel) [0x00007] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.Form:FireClosingEvents (System.Windows.Forms.CloseReason,bool)
  at System.Windows.Forms.Application.Exit (System.ComponentModel.CancelEventArgs e) [0x0002e] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.Application.Exit () [0x00005] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.Application.OnThreadException (System.Exception t) [0x0005e] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.NativeWindow.OnThreadException (System.Exception e) [0x00000] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x00196] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.XplatUICarbon.DispatchMessage (System.Windows.Forms.MSG& msg) [0x00000] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.XplatUI.DispatchMessage (System.Windows.Forms.MSG& msg) [0x00000] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.Application.RunLoop (System.Boolean Modal, System.Windows.Forms.ApplicationContext context) [0x002e2] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.Application.Run (System.Windows.Forms.ApplicationContext context) [0x00011] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.Application.Run (System.Windows.Forms.Form mainForm) [0x00006] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at GitUI.GitUICommands.StartBrowseDialog (System.Windows.Forms.IWin32Window owner, System.String filter, System.String selectedCommit) [0x00029] in <c387cdaf9bb74ffa906fd23129b41844>:0 
  at GitUI.GitUICommands.StartBrowseDialog (System.String filter) [0x00000] in <c387cdaf9bb74ffa906fd23129b41844>:0 
  at GitUI.GitUICommands.StartBrowseDialog () [0x00000] in <c387cdaf9bb74ffa906fd23129b41844>:0 
  at GitExtensions.Program.Main () [0x001e1] in <e2c646776d654bb2869a4f685d5e9c01>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.IOException: Too many open files
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <ac812cae460544af83bd6cf54c5eee87>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean isAsync, System.Boolean anonymous) [0x00000] in <ac812cae460544af83bd6cf54c5eee87>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access) [0x00000] in <ac812cae460544af83bd6cf54c5eee87>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess)
  at System.Configuration.InternalConfigurationHost.OpenStreamForWrite (System.String streamName, System.String templateStreamName, System.Object& writeContext) [0x0001e] in <3414a9f4d8fa4e5aaf6f3732ead4a289>:0 
  at System.Configuration.Configuration.Save (System.Configuration.ConfigurationSaveMode saveMode, System.Boolean forceSaveAll) [0x00032] in <3414a9f4d8fa4e5aaf6f3732ead4a289>:0 
  at System.Configuration.CustomizableFileSettingsProvider.SaveProperties (System.Configuration.ExeConfigurationFileMap exeMap, System.Configuration.SettingsPropertyValueCollection collection, System.Configuration.ConfigurationUserLevel level, System.Configuration.SettingsContext context, System.Boolean checkUserLevel) [0x00231] in <ead0603699f14fb4bc97df2618539636>:0 
  at System.Configuration.CustomizableFileSettingsProvider.SetPropertyValues (System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyValueCollection collection) [0x0003a] in <ead0603699f14fb4bc97df2618539636>:0 
  at System.Configuration.LocalFileSettingsProvider.SetPropertyValues (System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyValueCollection values) [0x00000] in <ead0603699f14fb4bc97df2618539636>:0 
  at System.Configuration.ApplicationSettingsBase.Save () [0x0008c] in <ead0603699f14fb4bc97df2618539636>:0 
  at GitUI.CommandsDialogs.FormBrowse.SaveSplitterPositions () [0x00069] in <c387cdaf9bb74ffa906fd23129b41844>:0 
  at GitUI.CommandsDialogs.FormBrowse.OnClosing (System.ComponentModel.CancelEventArgs e) [0x00007] in <c387cdaf9bb74ffa906fd23129b41844>:0 
  at System.Windows.Forms.Form.FireClosingEvents (System.Windows.Forms.CloseReason reason, System.Boolean cancel) [0x00007] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.Form:FireClosingEvents (System.Windows.Forms.CloseReason,bool)
  at System.Windows.Forms.Application.Exit (System.ComponentModel.CancelEventArgs e) [0x0002e] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.Application.Exit () [0x00005] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.Application.OnThreadException (System.Exception t) [0x0005e] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.NativeWindow.OnThreadException (System.Exception e) [0x00000] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x00196] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.XplatUICarbon.DispatchMessage (System.Windows.Forms.MSG& msg) [0x00000] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.XplatUI.DispatchMessage (System.Windows.Forms.MSG& msg) [0x00000] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.Application.RunLoop (System.Boolean Modal, System.Windows.Forms.ApplicationContext context) [0x002e2] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.Application.Run (System.Windows.Forms.ApplicationContext context) [0x00011] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at System.Windows.Forms.Application.Run (System.Windows.Forms.Form mainForm) [0x00006] in <919c0e29d1ee4130aa56b0f95d0b6c84>:0 
  at GitUI.GitUICommands.StartBrowseDialog (System.Windows.Forms.IWin32Window owner, System.String filter, System.String selectedCommit) [0x00029] in <c387cdaf9bb74ffa906fd23129b41844>:0 
  at GitUI.GitUICommands.StartBrowseDialog (System.String filter) [0x00000] in <c387cdaf9bb74ffa906fd23129b41844>:0 
  at GitUI.GitUICommands.StartBrowseDialog () [0x00000] in <c387cdaf9bb74ffa906fd23129b41844>:0 
  at GitExtensions.Program.Main () [0x001e1] in <e2c646776d654bb2869a4f685d5e9c01>:0 
```
Mono version
`Mono JIT compiler version 5.4.0.201 (2017-06/71277e78f6e Thu Sep 21 19:22:55 EDT 2017)`
OS version:
`OS Version: Mac OS X 10.12.1 (16B2657)`

**Comment by RussKie** [comment] 2017-10-23 22:49
Duplicate of #3287 
Duplicate of #3351

Please have a look at #3287, specifically at https://github.com/gitextensions/gitextensions/issues/3287#issuecomment-238470593

**Closed by RussKie** 2017-10-23 22:49 UTC
