### ISSUE TITLE
[NBug] fatal: bad object refs/heads/PopTail

### ISSUE THREAD

**Issue by DigDyn** [gitextensions/gitextensions#11115] opened 2023-07-28 02:03 UTC
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.20
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" --max-count=100000 --exclude=refs/notes/commits --all --
Working directory: C:\$DigDyn\SAS\CommonBaseCode\

```
GitExtUtils.ExternalOperationException: fatal: bad object refs/heads/PopTail
 ---> System.Exception: fatal: bad object refs/heads/PopTail
   --- End of inner exception stack trace ---
   at void GitUI.RevisionGridControl.PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs, bool forceRefresh)+() => { } in C:/projects/gitextensions/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:line 1309
   at async Task GitUI.GitUIExtensions.InvokeAsync(Control control, Action action, CancellationToken token) in C:/projects/gitextensions/GitUI/GitUIExtensions.cs:line 239
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { } in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 41
```

Trying to open a repo that I copied from my work machine. Got this error.
I have done this procedure 100 times before. So I know it works.
All my repos give this error.   I am scared.

### Steps to reproduce

Open an existing repo that I copied from my work machine.

### Did this work in previous version of GitExtensions?

Yes.

**Comment by pmiossec** [comment] 2023-07-28 06:24
Even if I don't recognize the stack trace, the fact that you said that it's copied from another computer make me think that's due to git dubious ownership security warning. 

You could run the command line given in the link below and confirm that you have the git warning message in the output :
https://github.com/gitextensions/gitextensions/issues/9954#issuecomment-1098375030

It has been better handled in the version waiting to be released.

There is a command line to set a security exception on a repo or on all but for me the best option is to change the owner of the folder and subfiles to your current user from the file explorer.

**Comment by gerhardol** [comment] 2023-07-28 17:26
It is Git that reports the error for the repo, GE behaves correctly here.

Before GE 4.0, GE swallowed most Git errors like this silently, they are reported now (there has been numerous tweaking to the errors shown to the user in 4.1 and some more in master, some were GE improved, some were just Git errors that could be ignored).
In this case there is something wrong with the repo, you should the same message with command line git log --all

No universal way to fix this what I see, for example a similar a issue.
https://stackoverflow.com/questions/72515916/git-fatal-bad-object-refs-heads-2-master

**Comment by gerhardol** [comment] 2023-08-06 19:38
Duplicate of #11128

**Closed by gerhardol** 2023-08-06 19:38 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
