### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Reactive.PlatformSe...

### ISSUE THREAD

**Issue by klorinczi** [gitextensions/gitextensions#10771] opened 2023-02-25 22:50 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.10.1.windows.1 (minimum: 2.25.0, please update!)
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET 6.0.14
- DPI 96dpi (no scaling)

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Reactive.PlatformServices, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. A rendszer nem találja a megadott fájlt.
File name: 'System.Reactive.PlatformServices, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'
   at BackgroundFetch.BackgroundFetchPlugin.RecreateObservable()
   at BackgroundFetch.BackgroundFetchPlugin.Register(IGitUICommands gitUiCommands)
   at GitUI.PluginRegistry.<>c__DisplayClass12_0.<Register>b__0(IGitPlugin p)
   at System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
   at GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   at GitUI.CommandsDialogs.FormBrowse.SetGitModule(Object sender, GitModuleEventArgs e)
   at GitUI.CommandsDialogs.FormBrowse.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.

### Steps to reproduce

Used GitExtensions v3.1.1.6049.
Downloaded GitExtensions-Portable-4.0.2.16100-25100ec1f.zip, overwritten.
After start I got this error.

### Did this work in previous version of GitExtensions?

Yes

### Diagnostics

_No response_

**Comment by gerhardol** [comment] 2023-02-25 23:01
Duplicate of #10368
Duplicate of #10624

This error seem to occur related to Windows and/or .NET updates and seem to be resolved by app or possible PC restarts.
Not sure if this can be detected.

**Closed by gerhardol** 2023-02-25 23:01 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
