### ISSUE TITLE
[NBug] Specified method is not supported.

### ISSUE THREAD

**Issue by brianjlacy** [gitextensions/gitextensions#7511] opened 2019-12-13 22:30 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.NotSupportedException: Specified method is not supported.
   at GitCommands.UserRepositoryHistory.RemoteRepositoryManager.<AddAsMostRecentAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitUI.CommandsDialogs.FormPull.PullChanges(IWin32Window owner)
   at GitUI.CommandsDialogs.FormPull.PullClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Tried to pull from another copy of the same Repo on local hard drive.

## Environment
- Git Extensions 3.2.0.6586
- Build abac1b4564a5166f0453fa3ee459769e8a199b6f
- Git 2.20.1.windows.1 (recommended: 2.22.0 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4042.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment] 2019-12-13 22:52
Duplicate of #6717

Corrected in #7260 
Please try 3.3 RC

**Closed by gerhardol** 2019-12-13 22:52 UTC
Labels: potential-duplicate
