### ISSUE TITLE
Rebase dialog is very slow on confict during big rebase

### ISSUE THREAD

**Issue by dosercz** [gitextensions/gitextensions#11196] opened 2023-09-06 15:34 UTC
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.21
- DPI 144dpi (150% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

I'm making interactive rebase of a lot of commits (approx 1000) and if there is a conflict and Rebase dialog is opened whole GUI is frozen for 1+ minute.
It depends on number of rebased commits. If there are only few commits, it's not a problem. But with increasing number of commits it takes more time to open dialog.

### Steps to reproduce

1. Make interactive rebase of branch with a lot of commits (1000)
2. Wait for conflict
3. Click to OK button in Process dialog
4. Wait few minutes before Rebase dialog is opened and respond to user interaction

### Did this work in previous version of GitExtensions?

No

**Comment by gerhardol** [comment] 2023-09-06 18:58
This need to be directed to Git, the GUI cannot speed up Git itself.

**Comment by mstv** [comment] 2023-09-06 20:07
More or less a duplicate of #10698

**Comment by pmiossec** [comment] 2023-09-06 21:26
@dosercz Is it for a rebase or an interactive rebase? or both?

**Comment by dosercz** [comment] 2023-09-07 07:59
It happens to me during an interactive rebase. I'm using it in most cases...

**Comment by pmiossec** [comment] 2023-09-07 09:47
> More or less a duplicate of #10698

Indeed, duplicate of this one. Let's close this one and continue the discussion on the other one (as I have a PoC giving interesting results)

**Closed by pmiossec** 2023-09-07 09:47 UTC
Labels: type: git issue
