### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by shirayuki** [gitextensions/gitextensions#10384] opened 2022-11-11 22:09 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22000.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

Every time I start Git Extensions, I get the following error message:
> Object reference not set to an instance of an object.

![image](https://user-images.githubusercontent.com/18039/201437088-9fbf4980-4c12-45c7-a68d-8afa256f145b.png)

### Steps to reproduce

1. Start Git Extensions

### Did this work in previous version of GitExtensions?

No.
It was occurring with Git Extensions v3.5 on a particular PC.
I installed v4.0 but it does not resolve the issue.

**Comment by mstv** [comment] 2022-11-12 10:50
Our new exception dialog looks different and provides the option to invoke the BugReporter with details.
But this is just a MessageBox. A run with debugger attached would help to identify and analyze the issue very much.

**Comment by RussKie** [comment] 2022-11-27 06:33
Unfortunately, information you provided is not enough to provide any meaningful help. 

- How did you install the app? 
- Did you try completely uninstalling the app + removing the app's settings files from `C:\Users\<user>\AppData\Roaming\GitExtensions` before reinstalling it back?

**Comment by shirayuki** [comment] 2022-11-27 06:49
> * How did you install the app?

I used GitExtensions-4.0.0-cba315df5.msi

> * Did you try completely uninstalling the app + removing the app's settings files from `C:\Users\<user>\AppData\Roaming\GitExtensions` before reinstalling it back?

I just tried this and it did not solve the problem.
To be precise, the above "Object reference not set..." error is followed by "Cannot find main menu" error.

![image](https://user-images.githubusercontent.com/18039/204122945-818d05c3-b0b3-4c9d-ae07-a40bde85b09e.png)

**Comment by vbjay** [comment] 2022-11-27 07:00
Run ```dotnet --list-runtimes``` and respond with the results.

**Comment by shirayuki** [comment] 2022-11-27 07:05
> Run `dotnet --list-runtimes` and respond with the results.

```
Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by vbjay** [comment] 2022-11-27 07:13
Install matching desktop runtime version. You have 6.0.9 desktop but 6.0.11 of the base runtume.

**Comment by shirayuki** [comment] 2022-11-27 07:37
I have installed .NET 6.0 Desktop Runtime (v6.0.11) and the problem persists.
```
Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mstv** [comment] 2022-11-27 07:52
You could uninstall Git Extensions and check that the installation folder is empty. Perhaps there are leftovers, which should be removed.

---

How does the portable build work on this machine?

**Comment by RussKie** [comment] 2022-11-27 09:44
> o be precise, the above "Object reference not set..." error is followed by "Cannot find main menu" error.
> 
> ![image](https://user-images.githubusercontent.com/18039/204122945-818d05c3-b0b3-4c9d-ae07-a40bde85b09e.png)

We don't have error messages like this in the app. Do you have 3rd party plugins installed?

**Comment by mstv** [comment] 2022-11-27 10:26
Duplicate of #9375?

**Comment by shirayuki** [comment] 2022-11-27 10:29
> How does the portable build work on this machine?

Portable build works without errors.

**Comment by shirayuki** [comment] 2022-11-27 10:39
> Duplicate of #9375?

Finally, after updating the Gerrit plugin, it now works without errors.
Thank you for your time.
![image](https://user-images.githubusercontent.com/18039/204130672-fc57a849-2570-41e5-9b12-6c5e1c7f3a58.png)

**Closed** 2022-11-27 10:44 UTC
Labels: potential-duplicate
