### ISSUE TITLE
Changelog is out of date (3.0.2 rather than 3.1)

### ISSUE THREAD

**Issue by phillijw** [gitextensions/gitextensions#6617] opened 2019-05-20 13:53 UTC
## Current behaviour

When GitExt checks for an update it suggests that 3.1 is available. When I click "Show ChangeLog" it shows the changes for 3.0.2

## Expected behaviour

Show changes for 3.1

## Steps to reproduce

See above

## Screenshots

![image](https://user-images.githubusercontent.com/467889/58026718-b3d53900-7adc-11e9-9294-ef53b637989f.png)

## Did this work in previous version of GitExtensions

3.0.2 apparently

## Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

**Comment by mnoreen** [comment] 2019-05-20 17:31
Also... when I click the Download Now button, it pops up a browser window, but with no URL, it's just a blank window, nothing to download.

**Comment by mast-eu** [comment] 2019-05-20 21:45
> When GitExt checks for an update it suggests that 3.1 is available. When I click "Show ChangeLog" it shows the changes for 3.0.2.

True. This shows the ChangeLog.md on master branch: https://github.com/gitextensions/gitextensions/blob/master/GitUI/Resources/ChangeLog.md
Which is currently still at version 3.0.2.

The correct changelog is on a different branch: https://github.com/gitextensions/gitextensions/blob/release/3.1/GitUI/Resources/ChangeLog.md
Which is not yet merged into master.

> when I click the Download Now button, it pops up a browser window, but with no URL, it's just a blank window, nothing to download.

I'm afraid I miss an important piece of information as I cannot reproduce. I just manually downgraded to 3.0.2 and then upgraded to 3.1 through `Help` > `Check for updates` > `Download now`. This brings up  the "Save file as " dialog from my web browser, just as expected.
Do you have some firewall, antivirus or other software that might block downloads?

**Comment by vbjay** [comment] 2019-05-20 22:03
Prob just blocked a pop up.

**Comment by RussKie** [comment] 2019-05-20 22:19
> > When GitExt checks for an update it suggests that 3.1 is available. When I click "Show ChangeLog" it shows the changes for 3.0.2.
> 
> True. This shows the ChangeLog.md on master branch: [/GitUI/Resources/ChangeLog.md@`master`](https://github.com/gitextensions/gitextensions/blob/master/GitUI/Resources/ChangeLog.md) [](/gitextensions/gitextensions/blob/HEAD@{2019-05-20T21:45:30Z}/GitUI/Resources/ChangeLog.md)
> Which is currently still at version 3.0.2.
> 
> The correct changelog is on a different branch: [/3.1/GitUI/Resources/ChangeLog.md@`release`](https://github.com/gitextensions/gitextensions/blob/release/3.1/GitUI/Resources/ChangeLog.md) [](/gitextensions/gitextensions/blob/HEAD@{2019-05-20T21:45:30Z}/3.1/GitUI/Resources/ChangeLog.md)
> Which is not yet merged into master.

Thank you, fixed



> when I click the Download Now button, it pops up a browser window, but with no URL, it's just a blank window, nothing to download.

Please provide information about your system including your default system browser.

**Closed** 2019-05-29 12:48 UTC
