### ISSUE TITLE
Using custom fields in "Jira Comment Hint" plugin in GitExtensions

### ISSUE THREAD

**Issue by zroytman** [gitextensions/gitextensions#6819] opened 2019-06-18 07:18 UTC
Hi,
I'm using a plugin [Jira Comment Hint](https://git-extensions-documentation.readthedocs.io/en/latest/plugins.html#jira-commit-hint) in **GitExtensions** in order to get my Jira issues queried automatically for commit message. The plugin makes me able to format the message using the predefined placeholders based on the built-in Jira fields.
In addition, there is a placeholder named CustomFields in order to query Jira custom fields.
Using the built-in Jira fields is very simple, like {Key} or {Summary}.
When i choose {CustomFields}, the plugin returns me the message that this is a collection.
I cannot find the way to display specific field from this collection, like for example "Application" (or by its custom field id).
Tried several ways like {CustomFields["Application"]}, {CustomFields("Application")}. {CustomFields.Application}, etc... getting error messages.
Has anyone tried to use this?
Thanks!

**Comment by RussKie** [comment] 2019-06-18 13:05
@ierof @stivx0 @peterkneale any ideas?

**Comment by RussKie** [comment] 2019-06-18 13:10
You have posted the same question into the existing issue.

**Comment by RussKie** [comment] 2019-06-18 13:10
Duplicate of #6294

**Closed by RussKie** 2019-06-18 13:10 UTC
Labels: potential-duplicate

**Comment by zroytman** [comment] 2019-06-18 13:13
> You have posted the same question into the existing issue.

The other issues aren't mine, so to be on the safe side i've opened another one, new, my issue.
