### ISSUE TITLE
Commit message cleared out when fixing up commit to another commit which starts from "#"

### ISSUE THREAD

**Issue by Mikilll94** [gitextensions/gitextensions#7861] opened 2020-03-10 21:57 UTC
## Current behaviour

The commit message is cleared out when doing "fixup" for a commit which is getting merged into another commit whose commit message starts with "#".

This bug is shown on the GIF below:

![git_extensions_rebase_fixup_hash](https://user-images.githubusercontent.com/17653648/76362626-9f8b5280-6321-11ea-86c1-2774b2e2efa0.gif)

## Expected behaviour
As you can see I want to fixup "Commit three" into "Commit two" but this operation results in the empty commit message for "Commit two".

This is because "Commit two" message starts with a "#".

## Steps to reproduce
1. Start the interactive rebase.
2. Fixup a commit to another commit which starts from "#".
3. Finish rebase.
4. As you can see, now there is an empty commit message.

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4121.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment] 2020-03-10 22:02
Duplicate of #7859 

fixup is using interactive rebase
This is handled by Git, not GE

**Comment by pmiossec** [comment] 2020-03-10 22:06
That's how git works and not a Gitextensions problem. Git use the # as a line comment.

Your workaround : https://www.kevinkuszyk.com/2016/03/09/git-tips-3-changing-the-git-rebase-comment-character/

**Comment by RussKie** [comment] 2020-03-13 00:40
@Mikilll94 what result do you get if you do it via command line?

**Comment by gerhardol** [comment] 2020-03-14 00:58
> what result do you get if you do it via command line?

Must be the same, as this is how Git is working
The change in GE would be to implement the rebase with own code

Closing as this is a duplicate

**Closed by gerhardol** 2020-03-14 00:58 UTC
Labels: :mailbox_with_no_mail: needs: author feedback, type: git issue
