### ISSUE TITLE
[NBug] Unable to parse git command output.

### ISSUE THREAD

**Issue by vfofanov** [gitextensions/gitextensions#7182] opened 2019-09-21 07:44 UTC
## Current behaviour

Exception raises only on specific repo when I open it or make pull operation

## Expected behaviour

No exception

## Steps to reproduce

I think problem with remote branches' names on Russian
See attachment picture

## Error Details
```
System.Exception: Unable to parse git command output.
   at GitCommands.GitModule.<GetRemotesAsync>g__ParseRemotes|153_0(IEnumerable`1 lines)
   at GitCommands.GitModule.<GetRemotesAsync>d__153.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<<UICommands_PostRepositoryChanged>b__6_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Just open repo anf got this error. I suppose the problem is with comments in Russian
I got this exception few last releases and workaround just close Error Report window

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4010.0
- DPI 120dpi (125% scaling)

**Comment by vfofanov** [comment] 2019-09-21 07:45
![image](https://user-images.githubusercontent.com/5789590/65369997-e181e880-dc5c-11e9-9f8a-e8be38ba7762.png)

**Comment by drewnoakes** [comment] 2019-09-21 08:45
Based on this line:

```text
at GitCommands.GitModule.<GetRemotesAsync>g__ParseRemotes|153_0(IEnumerable`1 lines)
```

Could you include the output of `git remote -v` here?

**Comment by drewnoakes** [comment] 2019-09-21 08:48
That exception is being thrown from here:

https://github.com/gitextensions/gitextensions/blob/a4a3568e8225f7b5c47bb1901bd8a40c724f2ce5/GitCommands/Git/GitModule.cs#L2173

This means the Regex isn't finding a match. We should understand why and fix it. It may be necessary to get the exact output of that command on your machine. Can you pipe it to a file and attach it here?

```text
git remote -v > output.txt
```

**Comment by gerhardol** [comment] 2019-09-21 10:11
Duplicate of #6673

This should be that two remotes are pushed for one remote, which is not supported in GE (probably was in 2.x).
I do not think any of the issues have supplied the requested information.

**Comment by drewnoakes** [comment] 2019-09-21 11:25
@vfofanov it would be great if you could let us know what's causing this by providing the requested info when you get the chance. Thanks!

**Comment by gerhardol** [comment] 2019-09-29 12:12
This is likely the same as #6922, both exceptions can occur with multiple push url
Awaiting confirmation

**Comment by gerhardol** [comment] 2019-09-29 16:52
Duplicate of #6922

**Closed by gerhardol** 2019-09-29 16:52 UTC
Labels: :mailbox_with_no_mail: needs: author feedback, potential-duplicate

**Comment by vfofanov** [comment] 2019-10-02 07:55
Hi, sorry for long response

I run original command from GE

`git pull --rebase --progress "origin" > /p/output.txt`

And got next output
> Already up to date.
Current branch develop is up to date. 

Your command `git remote -v` returns next
> git@github.com:NuGet/NuGet.PackageManagement.git	
git@github.com:StackExchange/dapper-dot-net.git	
origin	git@git.assembla.com:smartcodegen.git (fetch)
origin	git@git.assembla.com:smartcodegen.git (push)

**Comment by gerhardol** [comment] 2019-10-02 22:18
@vfofanov 
The listing has two remotes without names or fetch/push. I have tried to recreate that info but not succeeded.
Do you have any information why?
(The planned correction will not include this setup)

Can you please provide the contents of the command below, to get the "raw" data?

```
git config -l|grep ^remote
```

**Comment by vfofanov** [comment] 2019-10-03 17:59
![image](https://user-images.githubusercontent.com/5789590/66151765-a5696300-e620-11e9-94a4-76dd5f26dd18.png)

**Comment by vfofanov** [comment] 2019-10-03 18:04
`remote.origin.url=git@git.assembla.com:smartcodegen.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.puttykeyfile=R:/storage/git_keys/keys/abc.ppk
remote.git@github.com:StackExchange/dapper-dot-net.git.puttykeyfile=R:/git/Key/github.ppk
remote.git@github.com:NuGet/NuGet.PackageManagement.git.puttykeyfile=R:/git/Key/github.ppk`

**Comment by gerhardol** [comment] 2019-10-03 19:15
> remote.git@github.com:StackExchange/dapper-dot-net.git.puttykeyfile=R:/git/Key/github.ppk

That is a weird remote.
Thanks, I will suggest the parsing is changed to just ignore illformed remotes.

**Comment by vfofanov** [comment] 2019-10-04 19:55
Great, thanks! I just remove this remote and problem is gone))
