### ISSUE TITLE
Can't open repo on WSL directory

### ISSUE THREAD

**Issue by makomweb** [gitextensions/gitextensions#9972] opened 2022-04-20 17:03 UTC
### Environment

- Git Extensions 3.5.4.12724 (Portable App)
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.36.0.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4420.0
- DPI 144dpi (150% scaling)

### Issue description

Opening a repo which is on a WSL directory does not work.

It shows the message that there are unresolved merge conflicts.

![image](https://user-images.githubusercontent.com/1567373/164281358-cb9ead73-2480-4e29-ac46-8888bd8ba5f4.png)

Though, there are no merge conflicts when I am checking the repo via `git status` on the command line.

![image](https://user-images.githubusercontent.com/1567373/164281513-bcb55181-7e1d-4467-b1d0-0226f4ba4449.png)

When I open the commit dialog to commit changes the following error is shown:

![image](https://user-images.githubusercontent.com/1567373/164283994-12ea9bfb-2ac6-44d4-95a7-9c1b775bd87d.png)

The same error is shown when starting to `fetch`:

![image](https://user-images.githubusercontent.com/1567373/164281689-131c8093-5d60-4f0c-929a-d8cdc76fc14d.png)

I tried to work around this issue by executing the suggested command from the dialog but this did not solve it.

### Steps to reproduce

- open an Ubuntu shell on a WSL
- create a folder `/opt/develop`
- cd into that folder
- run `git init` inside this folder
- open GitExtensions
- open the repo on `\\wsl$\Ubunut\opt\develop`

### Did this work in previous version of GitExtensions?

- not sure about that

**Comment by pmiossec** [comment] 2022-04-20 17:27
On the subject: https://github.com/gitextensions/gitextensions/issues/9954#issuecomment-1104212187
There is a workaround...

**Comment by gerhardol** [comment] 2022-04-20 19:09
Duplicate of #9954

**Closed by gerhardol** 2022-04-20 19:09 UTC
Labels: :eyeglasses: status: needs review
