### ISSUE TITLE
[NBug] git checkout-index:  is not in the cache

### ISSUE THREAD

**Issue by afonsoft** [gitextensions/gitextensions#10973] opened 2023-05-17 18:02 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.2.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.16
- DPI 96dpi (no scaling)

### Issue description

```
GitExtUtils.ExternalOperationException: git checkout-index:  is not in the cache ---> System.Exception: git checkout-index:  is not in the cache

   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.ResetFile(String file)
   at GitUI.GitUICommands.StartResetChangesDialog(String fileName)
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments)
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

Reservet

### Steps to reproduce

I Reservet a change

**Comment by gerhardol** [comment] 2023-05-17 18:34
Duplicate of #10950
stage/unstage the file to remove conflict before reset

Before 4.0, Git errors were silently ignored. Reset of files need special handling per type, not all cases were handled.
4.1 handles some common scenarios, some situations that require data structure changes for conflicted files with added/removed files are not handled still.

Related changes in 4.1 for reset in Commit and Diff tab
renamed file changed in #10853
conflicts in the contents changed in #10423

#10960 will handle most scenarios, not finished yet

**Closed by gerhardol** 2023-05-17 18:34 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
