### ISSUE TITLE
[NBug] Unable to parse object ID "gelöscht".

### ISSUE THREAD

**Issue by SIRprise** [gitextensions/gitextensions#7466] opened 2019-11-28 15:48 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.FormatException: Unable to parse object ID "gelöscht".
   bei GitUIPluginInterfaces.ObjectId.Parse(String s)
   bei GitUI.CommandsDialogs.FormMergeSubmodule.btCheckoutBranch_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Error occured while merging a newer branch into this (older) branch. Current branch doesn't know submodule, but shows merge-conflict between "deleted" and {hash}

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-11-28 16:21
This is likely a duplicate of #6512
Corrected in #6513, included in 3.2

**Comment by mstv** [comment] 2021-05-22 22:18
> GetConflictsAsync() will likely have to be handled explicitly in #9056 @mstv

> The Exception could be avoided (but #9056 must handle this too).

I do not grasp how these are related at first glance.
The intention of #9056 is to present errors from git (and to reduce silent failures).
In case of git commands for display purposes, I agree, exceptions must be avoided and - if feasible - an error displayed.
The exception of this issue can be handled independently of #9056.
What have I missed?

**Comment by gerhardol** [comment] 2021-05-22 23:02
> What have I missed?

`ls-files` in `GetConflictsAsync()` will exit with error in this situation, which must be allowed

**Comment by mstv** [comment] 2021-05-23 20:52
> `ls-files` in `GetConflictsAsync()` will exit with error in this situation, which must be allowed

Handled with 8d166324dfeb6799aba865212adba9094dd4f6df

**Closed** 2024-10-12 03:10 UTC
Labels: type: bug :bug:, status: incorrectly filled template
