### ISSUE TITLE
[NBug] Invalid diff/merge tool requestedParameter name: toolName

### ISSUE THREAD

**Issue by pomeara** [gitextensions/gitextensions#8255] opened 2020-06-21 11:08 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Invalid diff/merge tool requested
Parameter name: toolName
   at GitCommands.DiffMergeTools.DiffMergeToolConfigurationManager.LoadDiffMergeToolConfig(String toolName, String userSuppliedPath)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.GitConfigSettingsPage.BrowseDiffMergeTool(String toolName, String path)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.GitConfigSettingsPage.btnMergeToolBrowse_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
I just updated to the latest version and now it's crashing!

## Environment
- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2020-06-21 11:25
What diff tool do you have configured? Steps to reproduce?

**Comment by pomeara** [comment] 2020-06-21 12:14
Hi @RussKie, I had previously re-installed my system and had installed git extensions, initially it did not have a diff tool selected as I normally use visual studio however I had attempted to configure kdiff as I do use this somethimes also.

So the application was in this 'settings dialog' and then the prompt to update to the new version appeared so I clicked the update and let that happen.

Then upon the next restart it crashed, after that I do not experience the crash (it was only just after the upgrade)

![image](https://user-images.githubusercontent.com/8163710/85224253-4b0d6e00-b40c-11ea-973c-0b3bb3a737b2.png)

**Comment by pomeara** [comment] 2020-06-21 12:18
Actually it just happened again when I pressed the "Browse button"

![image](https://user-images.githubusercontent.com/8163710/85224339-ff0ef900-b40c-11ea-8e2e-824f0a3f666b.png)

Here is the dialog so you can see all populated fields with-out the crash dialog 
![image](https://user-images.githubusercontent.com/8163710/85224350-22d23f00-b40d-11ea-8d3a-b994da5ae2af.png)

**Comment by gerhardol** [comment] 2020-06-21 12:37
Select mergetool first, or set difftool to something where there is no mergetool

It should not be possible to click Browse without setting a name of the tool first
(the crash occurs due to kdiff3 is set as a difftool and such a mergetool exists and wrong list is checked, but this is not the core problem).

**Comment by RussKie** [comment] 2020-06-21 12:37
Thank you.
You need to select a merge tool from the dropdown just above the where the Browse button is

**Comment by RussKie** [comment] 2020-06-21 12:39
> It should not be possible to click Browse without setting a name of the tool first

Aye, it should look like this
![image](https://user-images.githubusercontent.com/4403806/85224792-14d1ed80-b410-11ea-915a-71d582a3bbee.png)

**Comment by RussKie** [comment] 2020-06-21 12:44
Can you please share you .gitconfig entries for your diff tools, so I can repro the issue?

**Comment by gerhardol** [comment] 2020-06-21 12:44
Fix the crash only:

```
        private string BrowseDiffMergeTool(string toolName, string path, DiffMergeToolType toolType)
        {
            DiffMergeToolConfiguration diffMergeToolConfig = default;
            var index = toolType == DiffMergeToolType.Diff ? _NO_TRANSLATE_cboDiffTool.SelectedIndex : _NO_TRANSLATE_cboMergeTool.SelectedIndex;
            if (index > -1)
            {
                diffMergeToolConfig = _diffMergeToolConfigurationManager.LoadDiffMergeToolConfig(toolName, null);
            }
```

**Comment by RussKie** [comment] 2020-06-21 12:45
@gerhardol can you send a fix to 3.4.2 please? I've cut a release, but I can add this quick fix

**Comment by RussKie** [comment] 2020-06-21 12:46
I'd like to replicate the problem though

**Comment by gerhardol** [comment] 2020-06-21 12:46
@RussKie yes

**Comment by gerhardol** [comment] 2020-06-21 12:49
Reproduce:
Make sure mergetool is empty null. I patched ConfiguredMergeTool to return "".
Make sure the difftool exists as a mergetool, like kdiff3 (I had a custom difftool and could not reproduce at first)

**Comment by RussKie** [comment] 2020-06-21 12:49
Maybe we should just do this?
```diff
diff --git a/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs b/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs
index c8c80dfa1..3b0264f64 100644
--- a/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs
+++ b/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs
@@ -20,6 +20,16 @@ public GitConfigSettingsPage()
             InitializeComponent();
             Text = "Config";
 
+            txtDiffToolPath.Enabled =
+                btnDiffToolBrowse.Enabled =
+                    txtDiffToolCommand.Enabled =
+                        btnDiffToolCommandSuggest.Enabled = false;
+
+            txtMergeToolPath.Enabled =
+                btnMergeToolBrowse.Enabled =
+                    txtMergeToolCommand.Enabled =
+                        btnMergeToolCommandSuggest.Enabled = false;
+
             _NO_TRANSLATE_cboMergeTool.Items.AddRange(RegisteredDiffMergeTools.All(DiffMergeToolType.Merge).ToArray());
             _NO_TRANSLATE_cboDiffTool.Items.AddRange(RegisteredDiffMergeTools.All(DiffMergeToolType.Diff).ToArray());
```

**Comment by RussKie** [comment] 2020-06-21 12:52
> Reproduce:
> Make sure mergetool is empty null. I patched ConfiguredMergeTool to return "".
> Make sure the difftool exists as a mergetool, like kdiff3 (I had a custom difftool and could not reproduce at first)

Got it! Thank you

**Comment by RussKie** [comment] 2020-06-21 12:53
@gerhardol I repro'd it, the fix I posted above resolves it - a user won't be able to click "Browse" until the dropdown has some value in it

**Comment by RussKie** [comment] 2020-06-21 12:59
Fixed in 33da5fdc238c73119c070452d70b7879b29086bc

**Closed by RussKie** 2020-06-21 12:59 UTC
Labels: :construction: status: in progress, potential-duplicate

**Comment by gerhardol** [comment] 2020-06-21 13:01
@RussKie 
> I repro'd it, the fix I posted above resolves it - a user won't be able to click "Browse" until the dropdown has some value in it

That is the core fix, my change is for something that should not happen anyway. (Should probably be done, or remove the index check and parameter check)

**Comment by gerhardol** [comment] 2020-06-21 13:15
A consequence of the core fix is that you cannot edit the current diff/merge tool as Browse/Suggest is disabled.
You have to select another tool, then the current tool to edit the current tool.

**Comment by RussKie** [comment] 2020-06-21 13:27
Aye, thanks, fixing

**Comment by gerhardol** [comment] 2020-06-21 14:01
> Aye, thanks, fixing

Works for me

(existing bug: if selecting mergetool kdiff3 the path part of the command is not filled in)
![image](https://user-images.githubusercontent.com/6248932/85226579-842beb00-b3d8-11ea-8db2-c02ebda55b15.png)
