### ISSUE TITLE
v4 asks for dotNET even if it's installed

### ISSUE THREAD

**Issue by escherstair** [gitextensions/gitextensions#10319] opened 2022-11-03 08:21 UTC
### Environment

- GitExtensions version: v4
- GIT version: 2.36.1.windows.1
- OS version: Windows 10
- .NET version: 6.0.10 x86

### Issue description

I've unsistalled v 3.5.4 and installed v4.
It doesn't start because it asks for .NET 6.0.9 (as per documentation).
If I press Yes, to download automatically, the latest x64 release of .NET is downloaded (now it's 6.0.10), because my OS is x64.
But v4 cannot start becasue is asks for .NET.
I noticed that GE is x86 application and so I downloaded and installed ([.NET 6.0.10 x86 Core runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.10-windows-x86-installer)).
But GE v4 cannot start.
It always asks for .NET 6.0.9

### Steps to reproduce

Launch GE v4

### Did this work in previous version of GitExtensions?

v3.5.4 worked perfectly

**Comment by oba2cat3** [comment] 2022-11-03 09:18
Even installing the 6.0.9 runtime version does not help:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.9-windows-x64-installer

**Comment by djkwas86** [comment] 2022-11-03 09:29
I have the same problem

**Comment by TheYggdrazil** [comment] 2022-11-03 09:36
Same issue here, on 2 machines

**Comment by djkwas86** [comment] 2022-11-03 10:12
> Seems like the 2nd warning leads to a 2nd installer: windowsdesktop runtime. After installing the second, it works

indeed, it fix the problem, there are two different package to download

**Comment by Memo654** [comment] 2022-11-03 10:21
> 我有同样的问题，即使安装了 6.0.9 也同样无法解决

解决了，安装.NET Desktop Runtime和.NET Runtime两个包后可以正常启动

**Comment by vbjay** [comment] 2022-11-03 11:11
This is correct. .net runtime is required along with the desktop runtime. I do see a potential toake this easier. 

From .net download page. 

.NET Desktop Runtime 6.0.10

The .NET Desktop Runtime enables you to run existing Windows desktop applications. This release includes the .NET Runtime; you don't need to install it separately.

So instead of bootstraping runtime and desktop we can just bootstrap desktop.

**Comment by escherstair** [comment] 2022-11-03 14:22
I confirm that installing .NET Desktop Runtime 6.0.10 x64 (even if GE is 32-bit application) fixes thbe issue.
Installing .NET Desktop Runtime 6.0.10 x86 doesn't work.

**Comment by Pickysaurus** [comment] 2022-11-03 16:40
Can confirm there a two .NET installs needed but the errors look very similar.

**Comment by gerhardol** [comment] 2022-11-03 19:35
Desktop Runtime (x86) is what is needed, 6.0.9 or later. Maybe x64 will work too.
I do not believe the bootstrapper used allows specifying Desktop and x86 to download. Maybe someone can work with the creator to implement this?
https://github.com/Tyrrrz/DotnetRuntimeBootstrapper

**Comment by vbjay** [comment] 2022-11-03 22:01
Looks like he isn't taking feature requests. Might have to fork.

**Comment by lorenzogatti** [comment] 2022-11-04 08:52
Confirmed on Windows 10 x64, including the solution of installing version 6.0.10 x64 of both dependencies.

Suggestion: a custom message that makes it clear that there are two dependencies to install, not one.

**Comment by vbjay** [comment] 2022-11-04 09:09
Install only desktop runtime and it will include the plain old runtime.

**Comment by gerhardol** [comment] 2022-11-05 19:15
Duplicate of #10337

This issue was opened first, but #10337 has a better description of the issue and the direct links.

**Closed by gerhardol** 2022-11-05 19:15 UTC
