### ISSUE TITLE
Hide sub-modules from the recent repositories menu and the start screen

### ISSUE THREAD

**Issue by jfontsaballs** [gitextensions/gitextensions#11189] opened 2023-08-31 12:42 UTC
### Feature description

Hide sub-modules from the recent repositories menu, the start screen and other places where they may appear, either through an option or as the default behavior.

**Reasoning:** 

Usually when you open Git Extensions you want to navigate to the top project. Then, if necessary, you may navigate to a sub-module of that project. I've never had the need to navigate to a sub-module directly when opening Git Extensions.

However, having the sub-modules in the start screen creates a lot of clutter and unnecessary entries, thus making it much more difficult and time-consuming to find the project that you want to open. 

In my case it is especially burdensome as I'm working most of the time with 3-4 different projects but each has from 4 to 8 sub-modules. So most of my start screen is cluttered with sub-modules that I don't want.

### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.39.0.windows.2 (recommended: 2.40.1 or later)
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.21
- DPI 96dpi (no scaling)
- Portable: True
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by gerhardol** [comment] 2023-08-31 15:19
Duplicate of #4942

To never add submodules to the recent list would be a loss for others so this need to be a setting.
Personally I often go from from one submodule to another, but I rather skip submodules anyway to keep the superprojects I work with in the recent list longer time.

The knowledge about submodule or not is several layers away from handling the storing of info, so it is not trivial to implement.
Also, this would be a setting that few users would find and use.

**Comment by RussKie** [comment] 2023-09-01 01:33
Duplicate of #4942

**Closed by RussKie** 2023-09-01 01:33 UTC
Labels: type: feature request
