### ISSUE TITLE
[NBug] Could not load file or assembly 'System.DirectoryServices, ...

### ISSUE THREAD

**Issue by velteyn** [gitextensions/gitextensions#11100] opened 2023-07-13 09:53 UTC
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.18
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.DirectoryServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Impossibile trovare il file specificato.
File name: 'System.DirectoryServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at GitUI.CommandsDialogs.FormSettings.InitializeComponent()
   at GitUI.CommandsDialogs.FormSettings..ctor(GitUICommands commands, SettingsPageReference initialPage) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormSettings.cs:line 40
   at GitUI.CommandsDialogs.FormSettings.ShowSettingsDialog(GitUICommands uiCommands, IWin32Window owner, SettingsPageReference initialPage) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormSettings.cs:line 100
   at GitUI.GitUICommands.<>c__DisplayClass117_0.<StartSettingsDialog>g__Action|0() in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 943
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 318
   at GitUI.GitUICommands.StartSettingsDialog(IWin32Window owner, SettingsPageReference initialPage) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 947
   at GitUI.CommandsDialogs.Menus.ToolsToolStripMenuItem.OnShowSettingsClick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\Menus\ToolsToolStripMenuItem.cs:line 75
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Tools - Settings menu gives this error

### Steps to reproduce

go to tools - settings menù and I have this...

**Comment by gerhardol** [comment] 2023-08-08 21:19
Duplicate of https://github.com/gitextensions/gitextensions/issues/10368
This error seem to occur related to Windows and/or .NET updates and seem to be resolved by app or possible PC restarts.
Updated message in #11074

**Closed by gerhardol** 2023-08-08 21:19 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
