### ISSUE TITLE
wsl2 fatal error on windows 11

### ISSUE THREAD

**Issue by Triasmus** [gitextensions/gitextensions#10025] opened 2022-06-05 03:34 UTC
### Environment

- Git Extensions 4.1.0.13845 (latest dev stream. downloaded earlier today)
- Build 54e6bf95e67d0ea80052d3030c923fad73f4633a (Dirty)
- Git 2.36.1.windows.1
- Microsoft Windows NT 10.0.22000.0
- .NET 6.0.4
- DPI 96dpi (no scaling)

### Issue description

Windows 11 is liable to change `\\wsl$` to `\\wsl.localhost` when navigating from the network dir to the wsl root dir, causing a fatal error when attempting to open a wsl repo when the path is `wsl.localhost`:
![image](https://user-images.githubusercontent.com/14927087/172033355-8784e828-b503-4c3f-9a18-5c64aa42ed69.png)

### Steps to reproduce

`Browse...` to open a local repo
Navigate into the wsl filesystem through the folder structure all the way from `\\wsl$` when attempting to open the repo.

This gif shows when `\\wsl$` changes to `\\wsl.localhost`
![wsl-path](https://user-images.githubusercontent.com/14927087/172033315-3e79320f-53eb-4015-9e32-f24e04cd17b0.gif)

opening a repo under the `wsl.localhost` path results in this:
![open-repo-faulty-path](https://user-images.githubusercontent.com/14927087/172033835-2983b8a6-099f-42f9-98cc-627ecca2e945.gif)

Workaround:
typing in a longer path and then browsing from there seems to keep `\\wsl$` (most of the time), which allows GitExtensions to properly load the repo:
![wsl-longer-path](https://user-images.githubusercontent.com/14927087/172033603-6fb6066e-95d5-4c8f-be38-de83b6ef8d12.gif)

### Did this work in previous version of GitExtensions?

I never ran into this when using previous dev streams on Windows 10, but I also have no idea how I originally created the pin I surely used when browsing for the repo, so it's possible this also happens on windows 10 🤷‍♂️. I have not tested this on Windows 11 on previous dev streams.

**Comment by gerhardol** [comment] 2022-06-05 18:29
Duplicate of #9954
Git change, approve the "disk" directory.

For WSL2, you may want to  try the WSL mode in the upcoming release (try master, an alpha is planned soon).
For repos with \\wsl$ paths the WSL git is used instead, improves performance.
Added in #9702

**Comment by Triasmus** [comment] 2022-06-05 18:40
> For WSL2, you may want to try the WSL mode in the upcoming release (try master, an alpha is planned soon).

I am already using the latest dev stream because of the added wsl compatibility.
This is a bug from #9702, likely because #9702 wasn't tested thoroughly on windows 11.

Sorry I didn't make that clear in the issue title.

**Comment by gerhardol** [comment] 2022-06-05 19:55
If you access with wsl.localhost, you are using Windows Git, you must use \\wsl$ to use WSL git.

The problem here is still that Windows Git need to be configured to allow access to this repo as described in #9954. 
Windows Git is still required in some situations though, so the command may still be needed.
(I am considering to hide some popups for WSL, WSL often times out for me.)

I have no access to Win11 and have not tested Win11 at all, you may be the first.  
To support wsl.localhost for Windows Git can be seen as a feature: A way to choose between WSL/Windows Git, if there is an issue with #9702 (you can map drives too fo force Windows Git).
To support wsl.localhost for WSL Git will make the path manipulations more complex, I would like to keep it as is (and will obviously not implement something myself until I upgrade my PC, which could take years).
I will not vote against reasonable patches to support wsl.localhost.

**Closed** 2023-04-23 09:24 UTC
Labels: type: git issue, area: wsl
