### ISSUE TITLE
Plugin Manager installation and usage

### ISSUE THREAD

**Issue by thimmy687** [gitextensions/gitextensions#8794] opened 2021-01-22 14:50 UTC
It seems that the plugin manager is no longer part of the installation, since the last release.
We have now issues to use the GE with the gerrit plugin.
Can you provide a better guide how to install and use the new approach?
In best case we don't want use or install additional tools to use or install the plugin.

**Comment by RussKie** [comment] 2021-01-24 10:29
I have installed the [latest official release](https://github.com/gitextensions/gitextensions/releases/tag/v3.4.3) on a VM, and the plugin manager is installed, and working.
![image](https://user-images.githubusercontent.com/4403806/105627404-f55de000-5e8a-11eb-8b92-f54be940f05b.png)



> but I seems to noticed that with someone of my team that didn't get the plugin manager after a clean install of the last release on a new computer.

Is the app installed by the user or via a corporate install package that is run under a different user?

@maraf we may need to consider this scenario where a user isn't the one who installs the app, and thus the plugin manager may not be readily available to the said user.

**Comment by pmiossec** [comment] 2021-01-24 10:46
> I have installed the [latest official release](https://github.com/gitextensions/gitextensions/releases/tag/v3.4.3) on a VM, and the plugin manager is installed, and working.


Yes, I also checked yesterday and it was working fine for me too. 

>Is the app installed by the user or via a corporate install package that is run under a different user?

In the case where I noticed that the plugin manager was not there in the AppData folder, the colleague installed it in front of me with the setup just downloaded from github.  But I don't know if it's corporate computer is configured a specific way... 

So there is a case, that I don't understand, where the files that must be installed in AppData are either not installed or installed somewhere else. Is it possible, for a specific case/windows configuration, that the AppData variable used in the setup could  have a different path?

**Comment by maraf** [comment] 2021-01-24 10:58
That is a good point. Unfortunately the only idea I have is to pack Plugin Manager as a resource inside Git Extensions and extract it on the first run when it's not present on disk.

**Comment by RussKie** [comment] 2021-01-24 11:48
Can we use the "default user account"?

**Comment by RussKie** [comment] 2021-01-25 01:29
> In the case where I noticed that the plugin manager was not there in the AppData folder, the colleague installed it in front of me with the setup just downloaded from github. But I don't know if it's corporate computer is configured a specific way...

It would be great to get an installation log, and run something like procmon during the installation, to better understand the issue.

**Comment by vbjay** [comment] 2021-01-25 13:17
How about just making it a nuget package that all we do is pull down the
referenced version. So we can pull down v1.1 or whatever because that's the
version ge points to. Could use configdata branch to update version map.
This way you can have an up to date version of the manager by doing an
update check.

**Comment by maraf** [comment] 2021-01-25 13:37
> Can we use the "default user account"?

This is interesting idea. We could allow to specify if a plugin should be installed "for everyone" or "just me" and default to everyone for PM.

**Comment by thimmy687** [comment] 2021-01-26 07:42
At the moment if we start the plugin manager from the appdata folder we get the following error

![image](https://user-images.githubusercontent.com/7715216/105814937-719f1300-5fb2-11eb-9fb3-e6b16661a6c7.png)

**Comment by RussKie** [comment] 2021-01-26 09:58
The Plugin Manager can't be just run on its own, it requires parameters to get bootstrapped.
https://github.com/gitextensions/gitextensions.pluginmanager/blob/274c1e3aa4d282826db8c0029af473c5381eca65/src/PackageManager.Cli/Program.cs#L28

**Comment by RussKie** [comment] 2021-01-26 10:00
> We could allow to specify if a plugin should be installed "for everyone" or "just me"

I think the PM is the only one that could go into the default user folder to be available to every user on a workstation. All other plugins can be installed by individual users.

**Comment by SamuelSandvik** [comment] 2021-11-05 08:08
Some newer versions seems to be missing Plugin Manager. Manual workaround to open it:
1) Go to C:\Users\<user>\AppData\Local\GitExtensions\UserPlugins\GitExtensions.PluginManager\PackageManager>

2) From there start Plugin Manager via cmd or similar e.g. with:
PackageManager.UI.exe --path "C:\Users\<user>\AppData\Local\GitExtensions\UserPlugins"

or use relative path

**Comment by ADTC** [comment] 2021-11-05 08:45
I also don't see such an option in the Plugins menu. It's my first time to install and I didn't add any new plugins beyond what the setup offers.

It looks like it is installed, and I can run it by following the instructions from @SamuelSandvik but the Installed tab is empty. Maybe the global plugins are in a different path? (I installed GE globally for all users. Not sure why the Plugin Manager is in the local folder of my primary user account).

Windows 10 x64 btw.

**Comment by Kasim2021** [comment] 2021-12-15 13:57
This has worked in my case for the PluginManager and also for the Gerrit Plugin:

Copy the existing "GitExtensions.PluginManager.dll" / "GitExtensions.GerritPlugin.dll" from
   "c:\Users\User_Name\AppData\Local\GitExtensions\UserPlugins\GitExtensions.PluginManager\" 
   "c:\Users\User_Name\AppData\Local\GitExtensions\UserPlugins\GitExtensions.GerritPlugin\"
to
   "c:\Program Files (x86)\GitExtensions\Plugins\"

Then the PluginManager and also the Gerrit Plugin were available in the newest Git Extensions 3.5.4.12724
   
Windows 10 x64

**Comment by 011V32** [comment] 2022-09-12 11:50
Today we had the same problem after an Update of GE.
Workaround of @Kasim2021 worked for us.

**Comment by 011V32** [comment] 2022-12-20 06:24
After the update to v4.0.1 (from v4.0.0) the plugin manager is again missing.
Following files exist:
%LOCALAPPDATA%\GitExtensions\UserPlugins\GitExtensions.PluginManager\GitExtensions.PluginManager.dll
%LOCALAPPDATA%\GitExtensions\UserPlugins\GitExtensions.PluginManager\PackageManager\PackageManager.UI.exe
What to do, to get it work again?

**Comment by maraf** [comment] 2022-12-20 17:50
There is a bug in Plugin Manager included in 4.0.1 release. 
Resolved in https://github.com/gitextensions/gitextensions.pluginmanager/pull/69 (will be part of 4.0.2)

**Comment by 011V32** [comment] 2022-12-20 19:26
And what can I do to get it work again now?

**Comment by mstv** [comment] 2022-12-20 19:39
You could install one of the recent builds of the release branch, e.g.
https://ci.appveyor.com/api/buildjobs/4lrefbxmky8u3ee1/artifacts/combined.4.0.2.15956-unsigned.zip

**Comment by maraf** [comment] 2022-12-20 22:44
Or you can download fixed release of Plugin Manager from https://github.com/gitextensions/gitextensions.pluginmanager/releases/tag/v2.0.1 and extract it in `UserPlugins\GitExtensions.PluginManager`

**Comment by dfev77** [comment] 2023-01-10 15:58
Took the portable version from the above link and now I have Plugin Manager under "Plugins" menu.
However, something is not working as after installing the Gerrit plugin (tried both 1.x and 2.x), it is not displayed in neither "plugin setting" nor the toolbar.

**Comment by maraf** [comment] 2023-01-11 09:07
From the release notes of Gerrit plugin, you probably want 2.0.1 or 2.0.2. It states that 2.0.3 is for Git Extensions 4.1 and I can confirm that it doesn't load in the Git Extensions from the link above.

**Comment by RussKie** [comment] 2023-01-13 01:19
Please direct Gerrit related issues to https://github.com/gitextensions/GitExtensions.GerritPlugin/issues.

**Closed by RussKie** 2023-01-13 01:19 UTC
Labels: area: installer, area: plugins
