### ISSUE TITLE
Context menu hides window

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#4859] opened 2018-04-18 20:21 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Some dialogs like the commit window will hide when you right click on items.  I right clicked on an unstaged file and the commit window hides.  The window doesn't always come back.  Have to try clicking on button in taskbar to bring it back.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Right click should show menu over current window and not cause the window to hide.  
**Environment you encounter the issue:**

- GitExtensions version:2.50.01
- GIT version: it version 2.16.1.windows.1
- OS version: Microsoft Windows [Version 6.3.9600]

**Did this work in previous version of GitExtensions (which)?**

**Comment by gerhardol** [comment] 2018-04-18 21:03
I have seen this in master too, not consistently reproducible though

**Comment by RussKie** [comment] 2018-04-18 21:43
We have few open reports similar to this. They were related to conemu

On 19 Apr 2018 7:03 am, "Gerhard Olsson" <notifications@github.com> wrote:

I have seen this in master too, not consistently reproducible though

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/4859#issuecomment-382528528>,
or mute the thread

**Comment by gerhardol** [comment] 2018-04-18 21:53
ConEmu update may have improved the behavior slightly. I feel like it has occurred more often the last week though.
FormCommit seem to be the most common still

**Comment by RussKie** [comment] 2018-10-11 07:13
Duplicate of #3570

**Closed by RussKie** 2018-10-11 07:13 UTC
Labels: type: bug
