### ISSUE TITLE
Unable to pull-merge and pull-rebase

### ISSUE THREAD

**Issue by EbenZhang** [gitextensions/gitextensions#4513] opened 2018-02-23 01:12 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Not very sure the expected behavior as I don't usually use pull. But I guess it should allow me to select a remote branch??

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Make sure you have two Remotes configured
- Press the `down arrow` button and select `pull - merge` or the `pull - rebase`

![image](https://user-images.githubusercontent.com/596334/36572859-f2258614-1878-11e8-85a6-83ea582bac92.png)
- It gives an error

```
You asked to pull from the remote 'origin', but did not specify
a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line.
Done
```
the error says `origin` is not my default remote, but when pushing the `origin` is shown as my default remote.

**What is the expected behavior?**
I guess should allow me to select a branch to pull from, but it's just my guess, need some expert to define the expected behavior

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.13
- OS version: Windows10 64 bits

**Did this work in previous version of GitExtensions (which)?**
Didn't check but I feel this is a new feature in 2.51.

**Comment by RussKie** [comment] 2018-02-23 02:14
Likewise I never use pull, I always fetch

**Comment by GintasS** [comment] 2021-08-25 14:17
I couldn't reproduce this issue in 3.5.3. Closing this one.

**Closed by GintasS** 2021-08-25 14:17 UTC
Labels: :bug: type: bug, :eyeglasses: status: needs review
