### ISSUE TITLE
[NBug] git checkout-index: LogicTests/MappingUtilityTests.cs.orig ...

### ISSUE THREAD

**Issue by Notten02** [gitextensions/gitextensions#10486] opened 2022-12-02 15:23 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: checkout-index --index --force -- "LogicTests/MappingUtilityTests.cs.orig"
Working directory: C:\git\voortman.twincatprovider\

```
GitExtUtils.ExternalOperationException: git checkout-index: LogicTests/MappingUtilityTests.cs.orig is not in the cache
 ---> System.Exception: git checkout-index: LogicTests/MappingUtilityTests.cs.orig is not in the cache
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetBatchOutput(IExecutable executable, ICollection`1 batchArguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.ResetFiles(IReadOnlyList`1 files)
   at GitUI.CommandsDialogs.FormCommit.ResetSoftClick(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.FormCommit.ResetSelectedFiles()
   at GitUI.CommandsDialogs.FormCommit.ExecuteCommand(Int32 cmd)
   at ResourceManager.GitExtensionsFormBase.ProcessHotkey(Keys keyData)
   at GitUI.CommandsDialogs.FormCommit.ProcessHotkey(Keys keyData)
   at ResourceManager.GitExtensionsFormBase.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

I tried to reset a orig file from my index left from a merge conflict. (I forgot to include it with the .gitignore). When resetting the file from the commit window gitext crashed.

### Steps to reproduce

* forget to exclude `*.orig` files left from merge tools
* Cause a merge conflict and use a tool such as kdiff3 to resolve it
* Open the commit window in gitext and select the orig file
* Hit 'R' to reset it
* Notice the crash

### Did this work in previous version of GitExtensions?

Yes, it worked with the latest version of 3

**Comment by Notten02** [comment] 2022-12-02 15:45
Additional information: I know that the crash happened because the file was not in the git cache (I had wiped the orig file already). However in previous versions gitext would refresh what was in the commit windows as you open it. It appears the current version is not doing this (properly). Confusing me into doubting if I had removed the file (and therefor trying to reset and bumping into this issue).

**Comment by gerhardol** [comment] 2022-12-02 16:57
Similar to https://github.com/gitextensions/gitextensions/issues/10423, could be set as a duplicate.
git-checkout-index cannot be used for files with certain statuses.
Before 4.0 the Git error was just hidden, the popup is added in 4.0. Just ignore it for now.

**Comment by RussKie** [comment] 2022-12-03 07:22
Duplicate of https://github.com/gitextensions/gitextensions/issues/10423

**Closed by RussKie** 2022-12-03 07:22 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
