### ISSUE TITLE
First word in commit window diff doesn't have monospaced font

### ISSUE THREAD

**Issue by carl-di-ortus** [gitextensions/gitextensions#3090] opened 2016-01-12 10:36 UTC
Inside commit window preview of changes (diff), when difference happens from the start of the file - first word inside diff doesn't get monospaced font. It happens with different kind of files (see attached picture). No issue if difference is not from the start of file.

![git-collage](https://cloud.githubusercontent.com/assets/1598063/12261229/6ca0bcae-b928-11e5-8e0e-118c7646ea39.png)

**Comment by MpDzik** [comment] 2016-01-12 10:56
I've seen this too. I think this might be caused by the BOM in text files encoded using UTF.

**Comment by RussKie** [comment] 2017-08-18 13:55
Yes, VS in particular is quite guilty of BOM...
It is a minor cosmetic issue, we won't be fixing this.

**Closed by RussKie** 2017-08-18 13:55 UTC
