### ISSUE TITLE
Diff Contains Filter to Highlight/Show where Filter Matches in Diff

### ISSUE THREAD

**Issue by snelltheta** [gitextensions/gitextensions#11496] opened 2024-01-03 22:38 UTC
### Feature description

Intended use: I want to find the exact files with the lines of code where the diff contains the filter term, perhaps across files. 

Current behavior: just filters which commits have a diff that contains the filter term. Doesn't thin down which file, nor which line.

### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by pmiossec** [comment] 2024-01-03 22:58
Is it #11350 feature?

**Comment by snelltheta** [comment] 2024-01-03 23:21
Very very close! If that functionality in #11350 is implemented, this would be a feature that would make use of it. 
Essentially, it would do the usual Diff Contains filtering, but when a commit is selected, populate the search box mentioned in #11350 with the same string as the filter.

**Comment by gerhardol** [comment] 2024-01-03 23:28
To search many revisions for all matches would be very slow. There is no direct Git functionality for that either.
So I would like to keep this as separate steps, where you search with Diff contains or some bisect to find a revision, then git-grep.
You can try the PR, but the UI is not ready.

Duplicate of #4912

**Closed by gerhardol** 2024-01-03 23:28 UTC
Labels: type: feature request

**Comment by snelltheta** [comment] 2024-01-03 23:55
You do good work! I'm looking forward to spending some time with the function once implemented fully.
