### ISSUE TITLE
GE in background after rebase

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6148] opened 2019-01-21 23:43 UTC
## Current behaviour

When a rebase finishes, the GE window is moved behind other applications.

## Expected behaviour

The Browse window gets the focus.

## Steps to reproduce

Trigger a rebase (regardless whether interactive or not).

## Did this work in previous version of GitExtensions

Yes, though I don't know when, maybe before 3.0.0.

## Environment

- Git Extensions 3.01.00.0
- Build 087f23afc7288b7ded1bcafa0d8eec319ac0c52a
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment] 2019-01-21 23:44
Do a search for conemu in issues.

**Comment by RussKie** [comment] 2019-01-22 03:42
Confirming the issue, I've been observing it a lot lately.
Perhaps it is worth starting discussions about us using the ConEmu given all issues it causes

**Comment by vbjay** [comment] 2019-01-22 03:52
I would love for @Maximus5 to help make it work better.  Maybe he could point us to a setting or some way to keep it.  I like how we support the console.  I like conemu.

**Comment by vbjay** [comment] 2019-01-22 03:56
1. Click in console
1.   Hit <kbd>Alt</kbd>+<kbd>Spc</kbd>

**Comment by vbjay** [comment] 2019-01-22 03:59
Maybe?  https://conemu.github.io/en/SettingsChildGui.html

**Comment by Maximus5** [comment] 2019-01-22 07:50
I see that ConEmu build (180131) is rather old. Try to update?

**Comment by gerhardol** [comment] 2019-01-22 22:18
@Maximus5 There has not been any changes to conemu-inside since GE last synced. There has been changes to the GE fork in v3, for instance due to threading. From what I experience, there has been no changes in conemu behavior in v2.51 vs v3.0.
How can we investigate these problems?

**Comment by RussKie** [comment] 2019-01-23 13:10
The latest version available is https://www.nuget.org/packages/ConEmu.Core/18.6.26, which is 5 month newer...

Is there any way we can disable ConEmu gaining the focus?

**Comment by gerhardol** [comment] 2019-07-22 23:19
Duplicate of #6220

**Closed by gerhardol** 2019-07-22 23:19 UTC
Labels: area: user experience, type: dependency bug
