### ISSUE TITLE
[NBug] Value must not be null.

### ISSUE THREAD

**Issue by BHaarman** [gitextensions/gitextensions#11568] opened 2024-02-06 07:18 UTC
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.26
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.Exception: Value must not be null.
   at void Microsoft.Validates.Fail(string message) in C:/projects/gitextensions/GitExtUtils/Validates.cs:line 35
   at async void GitUI.CommandsDialogs.FormCheckoutBranch.Branches_SelectedIndexChanged(object sender, EventArgs e)+(?) => { } in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCheckoutBranch.cs:line 489
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

when choosing checkout remote branch first this error pops up, when choosing ignore the checkout branch window is active

### Steps to reproduce

when clicking 'checkout remote branch' in the right click menu of a remote branch (in the treeview) the error pops up.
when clicking ignore the 'checkout branch' window is active.

this behaviour is not showing in another remote repository so my guess is some setting are not set properly but if this is the case I would not expect an error message like this..

**Comment by gerhardol** [comment] 2024-02-06 08:12
Duplicate of #11498
Fixed in #11500

Also related to #11562/#11564

**Closed by gerhardol** 2024-02-06 08:12 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
