### ISSUE TITLE
[NBug] The specified path, file name, or both are too long. The fu...

### ISSUE THREAD

**Issue by ostorj** [gitextensions/gitextensions#6685] opened 2019-05-28 14:21 UTC
## Error Details
```
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at GitCommands.FullPathResolver.Resolve(String path)
   at GitUI.Editor.FileViewer.<ShowOrDeferAsync>g__GetFileLength|88_0(<>c__DisplayClass88_0& )
   at GitUI.Editor.FileViewer.ViewCurrentChanges(String fileName, String oldFileName, Boolean staged, Boolean isSubmodule, Func`1 getStatusAsync, Action openWithDifftool)
   at GitUI.Editor.FileViewer.ViewCurrentChanges(GitItemStatus item, Boolean isStaged, Action openWithDifftool)
   at GitUI.CommandsDialogs.FormCommit.<SetSelectedDiffAsync>d__129.MoveNext()
--- End of stack trace from previous location where exception was thrown -

**Comment by mstv** [comment] 2019-05-28 20:57
@ostorj, give as much as information as possible to help the developers solve this issue, please.
Otherwise, your issue may be closed without any follow-up from the developers.
Because of this, please make sure to fill in all the fields in the report template, especially **"steps to reproduce" and version information**.

**Comment by mstv** [comment] 2019-05-28 21:21
Could be a duplicate of #6665.

**Comment by gerhardol** [comment] 2019-05-28 22:33
Duplicate of #6665 

If not enough information, it is better to close and link and approach the grouped issues together

**Closed** 2019-05-28 22:33 UTC

**Comment by mstv** [comment] 2019-05-30 00:17
@ostorj, could you test the [canary build 3.2.0.6014](https://ci.appveyor.com/api/buildjobs/iqqocv9lt59t3mv6/artifacts/Setup%2FGitExtensions-Portable-3.2.0.6014.zip), please?
