### ISSUE TITLE
Top merge commit has no line to parent

### ISSUE THREAD

**Issue by zlolik** [gitextensions/gitextensions#12011] opened 2024-10-31 13:50 UTC
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.47.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Top commit has no line to parent, just compare gitextensions and gitk:
![Image](https://github.com/user-attachments/assets/cf720756-e922-4666-90cf-66afe51a1ebb)
![Image](https://github.com/user-attachments/assets/a225cbb5-ead0-41a9-93c5-05048b3abca9)

### Steps to reproduce

Use minimal test repo at https://github.com/zlolik/top-merge

**Comment by pmiossec** [comment] 2024-10-31 14:18
Is it a transient state that disappear if you refresh?
Because I cloned your repo and the graph is displayed as expected... (With the exact same version: - Git Extensions 5.0.0.17897 )

![Image](https://github.com/user-attachments/assets/c8df2aad-a9f7-4856-b246-216740afec6b)

**Comment by zlolik** [comment] 2024-10-31 14:40
No it is stable at my computer. Cloned repo has the same behaviour.
![Image](https://github.com/user-attachments/assets/6e9ad83c-b3c0-46cd-9c72-a1413ca2782b)

**Comment by pmiossec** [comment] 2024-10-31 14:42
Pretty sure you switched on "Show only first parent" option...
![Image](https://github.com/user-attachments/assets/f4bc0085-5a2a-4a41-93be-3028586c1957)

**Comment by zlolik** [comment] 2024-10-31 14:56
And you were absolutely right about "Show only first parent" option. So, is this a feature?

**Comment by pmiossec** [comment] 2024-10-31 15:06
>So, is this a feature?

I'm not an expert of this feature as I never use it but it seems yes that it is the expected behavior where only the 1st parent is followed and displayed. Other parents "connections" are not added to the graph and so displayed.

Even if I admit that you are in the edge case where the parent commit is in the graph because handled by another ref and so not displaying the connection feels odd...

So i think yes, it's a feature... (and I can close the issue)

**Closed by pmiossec** 2024-10-31 15:06 UTC
Labels: :eyeglasses: status: needs review
