### ISSUE TITLE
Closing multiple instances at once breaks the configuration

### ISSUE THREAD

**Issue by shirayuki** [gitextensions/gitextensions#10016] opened 2022-05-28 21:42 UTC
### Environment

- GitExtensions version: master branch
- GIT version: 
- OS version: Windows 10 Professional
- .NET version: 

### Issue description

Closing multiple GitExtensions instances at once breaks the configuration

### Steps to reproduce

1. Open multiple GitExtensions instances.
2. Right click GitExtensions icon in the taskbar.
3. Click "Close all windows" menu item.

### Did this work in previous version of GitExtensions?

Unknown

**Comment by RussKie** [comment] 2022-06-02 11:01
Can you please elaborate on what exactly you mean by "breaks the configuration"?

Possible duplicate of https://github.com/gitextensions/gitextensions/issues/8006.

**Comment by shirayuki** [comment] 2022-06-02 11:17
> Can you please elaborate on what exactly you mean by "breaks the configuration"?
> Possible duplicate of #8006.

I opened 3 or 4 instances. They were closed silently and I did not see the "Cannot save settings" dialog.

**Comment by Frettman** [comment] 2022-08-21 06:13
I have it on occasion that Git Extensions has forgotten its settings when I start it. Usually after a forced restart by a Windows Update, I think (I don't restart my computer otherwise). And since I always have multiple instances open, this might explain why that happens. But it doesn't happen every time.

**Closed** 2022-10-05 20:43 UTC
Labels: :construction: status: in progress
