### ISSUE TITLE
Gitbash toolbar icon doesn't work with git for windows.

### ISSUE THREAD

**Issue by fanfan-huang** [gitextensions/gitextensions#9399] opened 2021-07-20 12:54 UTC
## Current behaviour

It seems to launch a command line that is in bash but is missing the environment vars for git.

example:
$ git
bash: git: command not found

## Expected behaviour

As in the previous versions it's able to launch a gitbash session in the directory of the repo.

## Steps to reproduce

Click gitbash 

## Did this work in previous version of GitExtensions

Yes this worked in 3.4.3 and 3.5

## Environment

- GitExtensions version: 3.5.1
- GIT version: 2.32.0.windows.2
- OS version: Windows 10 x64 21H1
- .NET version:  (Not using the plugin)

**Comment by pmiossec** [comment] 2021-07-20 12:59
Duplicate of #9353, so closing...
Please @fanfan-huang have a look and contribute to the discussion in it...

**Closed by pmiossec** 2021-07-20 12:59 UTC
