### ISSUE TITLE
After window is minimized, unable to show the window back except using Alt+Tab

### ISSUE THREAD

**Issue by Teuxe** [gitextensions/gitextensions#10711] opened 2023-02-10 14:23 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.13
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

The window cannot be easily displayed after being minimized using only the taskbar.
Using Alt+Tab is necessary to show the window again.

### Steps to reproduce

1. Mimimize window explicitly (or all windows using Windows+M).
2. Click on taskbar icon to show up the window back.

### Did this work in previous version of GitExtensions?

Yes, seems like it happens since .NET Runtime 6.0.13 has been required.

**Comment by gerhardol** [comment] 2023-02-10 22:43
Duplicate of https://github.com/gitextensions/gitextensions/issues/10398

See https://github.com/gitextensions/gitextensions/issues/10398#issuecomment-1313378235 for a kind of workaround

**Closed by gerhardol** 2023-02-10 22:43 UTC
Labels: :eyeglasses: status: needs review
