### ISSUE TITLE
Recent Repositories list should be scrollable.

### ISSUE THREAD

**Issue by jakesays** [gitextensions/gitextensions#2987] opened 2015-10-19 21:24 UTC
Would it be possible to get a scrollbar on the recent repositories list? 

--- GitExtensions2.48.05, Git 1.9.5.msysgit.0, Microsoft Windows NT 6.3.9600.0

**Comment by KindDragon** [comment] 2016-04-29 21:55
I don't think so

**Comment by cristianst85** [comment] 2017-04-12 21:23
Duplicate of #2228.

**Closed** 2017-04-13 10:24 UTC
