### ISSUE TITLE
gerrit plugin throwing exceptions in v3.3.1.7897

### ISSUE THREAD

**Issue by Fredyy90** [gitextensions/gitextensions#7697] opened 2020-01-28 13:18 UTC
Hey,

Since updating to 3.3.1.7897 I can't use the gerrit plugin anymore. every gerrit-plugin-related button I press throws an exception like this.

## Error Details
```
System.ArgumentException: Der Versionszeichenfolgeteil war entweder zu kurz oder zu lang.
   bei System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   bei System.Version.TryParseVersion(String version, VersionResult& result)
   bei System.Version.Parse(String input)
   bei Gerrit.FormGerritBase.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
When clicking any gerrit plugin related buttons (push/pull/etc) i get this exception.

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2020-01-28 16:39
Duplicate of #7521

Updated in master

**Closed by gerhardol** 2020-01-28 16:39 UTC
