### ISSUE TITLE
[NBug] Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by leandrowilliam** [gitextensions/gitextensions#6709] opened 2019-05-30 18:40 UTC
## Error Details
```
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at GitCommands.PathUtil.NormalizePath(String path)
   at GitCommands.GitModule..ctor(String workingDir)
   at GitUI.CommandsDialogs.BrowseDialog.FormOpenDirectory.LoadClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3801.0
- DPI 192dpi (200% scaling)

**Comment by leandrowilliam** [comment] 2019-05-30 18:41
Trying open from `\\wsl$\....`

**Comment by mstv** [comment] 2019-05-30 21:23
I cannot reproduce it.
v3.1.0.5877 shows a messagebox saying "Directory does not exist".
In the current master, the text was changed to "The selected directory is not a valid git repository."

Could you try again with the [latest build](https://ci.appveyor.com/api/buildjobs/lk2vjv2xilgrtwa9/artifacts/Setup%2FGitExtensions-Portable-3.2.0.6018.zip), please?

**Comment by RussKie** [comment] 2019-06-02 11:14
Steps to reproduce?

**Comment by leandrowilliam** [comment] 2019-06-03 21:42
I was trying to open a git repository from WSL file system... using: `\\wsl$\<path-to-dir>`

**Comment by RussKie** [comment] 2019-06-03 23:46
For someone to look at the issue, we need steps to reproduce.
E.g.
* mount WSL: <command>
* create folder: <command>
* etc etc etc

**Comment by gerhardol** [comment] 2019-06-04 05:13
Win10 1903 will be needed and there are still limitations
https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/

Quite specific use case. For now to be fixed by someone that needs use wsl and cannot store files in win file system.

**Closed** 2019-10-04 04:50 UTC
Labels: :mailbox_with_no_mail: needs: author feedback, :neckbeard: status: pull request only, :zzz: status: no recent activity, area: w10, potential-duplicate
