### ISSUE TITLE
Always new branch when remote branches differ in upper/lower case only

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5405] opened 2018-09-06 21:19 UTC
**Do you want to request a *feature* or report a *bug*?**
discussion how to deal with Git on Windows issue

**What is the current behavior?**
On each pull/fetch git reports a new branch if there are remote branches whose names differ in upper/lower case only.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. git.exe fetch --progress "russkie"
Fetching russkie
From https://github.com/russkie/gitextensions
 `*` [new branch]          **U**pdate_readme -> russkie/**U**pdate_readme
 `*` [new branch]          **u**pdate_readme -> russkie/**u**pdate_readme
1. git.exe fetch --progress "russkie"
Fetching russkie
From https://github.com/russkie/gitextensions
 `*` [new branch]          **U**pdate_readme -> russkie/**U**pdate_readme
1. git.exe fetch --progress "russkie"
Fetching russkie
From https://github.com/russkie/gitextensions
 `*` [new branch]          **u**pdate_readme -> russkie/**u**pdate_readme

**What is the expected behavior?**
Display a warning that branch names differ in character case only?
Deny to create/push such branches?

**Environment you encounter the issue:**

- GitExtensions version: master *and* 2.51
- GIT version: 2.18.0.w.x64 and 2.13.0.w.1-x86
- OS version: Windows 7
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**
at least not with 2.51.02

**Comment by gerhardol** [comment] 2018-09-06 21:50
GE do not parse internal message texts like this, just the status
Processed status uses "porcelain" output that can be parsed.

I do not think GE should do anything else here.

**Comment by mstv** [comment] 2018-09-07 21:38
@RussKie, could you delete one of these two branches, please?

**Comment by vbjay** [comment] 2018-09-07 21:52
Git is case sensitive. It is completely valid but goofy to have 2 branches
with different cases like dev and DEV. The issue is when you are on windows
and the ref name is part of the filename.
https://stackoverflow.com/questions/38493543/git-branch-name-case-sensitive-or-insensitive

Try running git gc --aggresive or git repack -d -a -b

**Comment by vbjay** [comment] 2018-09-07 21:54
git pack-refs --all is actually the right command.

**Comment by RussKie** [comment] 2018-09-08 04:08
I don't get any complaints from git:
![image](https://user-images.githubusercontent.com/4403806/45250138-9017fb80-b370-11e8-99ad-fbfd38e52113.png)

Am I missing something?

**Comment by vbjay** [comment] 2018-09-08 06:56
That's because your refs are packed. When they are files in the .git folder
you get
...Update_readme... and ...update_readme. As you know windows is not case
sensitive. So both files are the same.

**Comment by RussKie** [comment] 2018-09-08 21:51
I'm not sure what we can do here, or whether anyone is planning to do anything...
If no actions planned, should we close this?

**Comment by vbjay** [comment] 2018-09-08 21:54
About the only thing I could suggest is running git pack-refs --all either
as a menu option under git maintenance or automatically after x number of
pulls/fetches.

**Comment by gerhardol** [comment] 2018-09-08 21:57
> I'm not sure what we can do here, or whether anyone is planning to do anything... If no actions planned, should we close this?

Git issue I cannot see that anything could be done in GE -> closing issue

**Closed by gerhardol** 2018-09-08 21:57 UTC
Labels: type: git issue

**Comment by vbjay** [comment] 2018-09-08 22:05
We can run git pack-refs --all.  It moves all refs into .git\packed-refs.

**Comment by vbjay** [comment] 2018-09-08 22:17
Do you see the problem now?

![image](https://user-images.githubusercontent.com/3629489/45259069-56f08300-b392-11e8-8279-37e60c3f1305.png)
![image](https://user-images.githubusercontent.com/3629489/45259116-47be0500-b393-11e8-93b4-7a036ec40ba7.png)


Do you see how a windows folder would create a Master and a master file which are the same file in windows?

**Comment by vbjay** [comment] 2018-09-08 22:36
WOW!.  I merged master with upstream/master then checked out Master and reset it to a different commit.

Merge:
![image](https://user-images.githubusercontent.com/3629489/45259224-97053500-b395-11e8-9203-7a6a0245c4ba.png)

After checkout Master and reset to a different commit.  

![image](https://user-images.githubusercontent.com/3629489/45259246-f7947200-b395-11e8-8697-96d9f71de05f.png)


Yep don't use branches with different cases.
