### ISSUE TITLE
Tree view gets scrambled when scrolling

### ISSUE THREAD

**Issue by mmbit-hub** [gitextensions/gitextensions#10703] opened 2023-02-08 08:31 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.13
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

The commit tree view get scrambled when scrolling up and down with mouse wheel.
![2023-02-08 10_30_28-Git Extensions-view-scrambled](https://user-images.githubusercontent.com/122875627/217476132-5b8ddef9-406b-48c9-8343-ba44960dbfcb.png)

### Steps to reproduce

Scroll commit tree view up and down.

### Did this work in previous version of GitExtensions?

3.x (maybe 3.9?)

**Comment by pmiossec** [comment] 2023-02-08 08:50
It seems a duplicate of  #10672, fixed by  #10679.

Can you check the portable build to verify? Available here:
https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts

**Comment by mmbit-hub** [comment] 2023-02-08 09:02
Yes, it seems to fix the problem. Sorry about the duplicate. I tried to search before submitting, but couldn’t find. You can close the ticket.

**Comment by pmiossec** [comment] 2023-02-08 09:21
Great! Thanks.

**Closed by pmiossec** 2023-02-08 09:21 UTC
Labels: :eyeglasses: status: needs review
