### ISSUE TITLE
Delete remote branch

### ISSUE THREAD

**Issue by NOYB** [gitextensions/gitextensions#3027] opened 2015-11-15 02:24 UTC
--- GitExtensions2.48.05, Git 1.9.5.msysgit.0, Microsoft Windows NT 6.3.9600.0
 
Don't see how to delete a branch from origin.
(git push origin --delete <branch name>)
 
Online help only covers deleting a local branch.

**Comment by ghanique** [comment] 2015-11-15 07:05
Click Push. This opens a new window.
In new window go to the right most tab ("push multiple branches")
This gives a list of local and remote branches. If you want to delete a
remote branch check the Delete check box for the branch you want to delete
and click Push.

**Comment by NOYB** [comment] 2016-03-12 11:28
@ghanique 
Very cumbersome process you have there.  May almost be practical if there was a way to toggle the entire column instead of having to click each row individually.

**Comment by vbjay** [comment] 2016-03-12 20:20
So think of it this way.  Would you want it to be easy to delete a tracking branch from the repo?  Clicking each one is an extra verification step of are you sue you want to remove this branch.

**Comment by NOYB** [comment] 2016-03-12 21:06
It's more about having to un-check all the ones I don't want to push.  That's where it would be nice to select a bunch of them and hit the space bar to un-select a group of them.

**Comment by ghanique** [comment] 2016-03-14 08:08
I recently downloaded a pre-release version of Git Extensions that has a
pane with branches. I'm loving it! It also allows you to delete remote
branches very conveniently.

[image: Inline image 1]

**Comment by ido-ran** [comment] 2016-08-10 08:56
I think it can be useful to extend the delete branch dialog to allow also delete the remote branch in the same action. Since deleting a local branch (without force) is restricted to only branches that merge back to HEAD that will protect aginst accidental deletes.
Adding a checkbox for "delete remote branch" can run the remote "delete-push" after deleting the local branch.

**Comment by vbjay** [comment] 2016-08-10 13:38
There is a plugin that handles that.

**Comment by vbjay** [comment] 2016-08-10 13:44
https://github.com/gitextensions/gitextensions/tree/master/Plugins/DeleteUnusedBranches

**Comment by KindDragon** [comment] 2016-10-15 12:02
Duplicate of #1583

**Closed by KindDragon** 2016-10-15 12:02 UTC
Labels: feature-request

**Comment by vbjay** [comment] 2016-10-15 12:29
Just a point. Don't you think we don't want it easy to delete remote
branches?

**Comment by KindDragon** [comment] 2016-10-15 12:43
I think it easy to fix if someone deletes wrong remote branch, so that no great harm if it is easy to do

**Comment by ghanique** [comment] 2016-10-15 16:34
I like the sidebar thing with the branches and tags. It shows the local
branches and remote branches separately and gives a clear warning when you
try to delete a remote branch.
