### ISSUE TITLE
[NBug] Value must not be null.

### ISSUE THREAD

**Issue by Thieum** [gitextensions/gitextensions#11778] opened 2024-06-03 21:11 UTC
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.44.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.31
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.Exception: Value must not be null.
   at void Microsoft.Validates.Fail(string message) in C:/projects/gitextensions/GitExtUtils/Validates.cs:line 35
   at async void GitUI.CommandsDialogs.FormCheckoutBranch.Branches_SelectedIndexChanged(object sender, EventArgs e)+(?) => { } in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCheckoutBranch.cs:line 489
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

checkout branch after hg conversion

### Steps to reproduce

- Convert an hg repository with the following procedure: https://helgeklein.com/blog/converting-mercurial-repositories-to-git-on-windows/

- Trying to open the repository in gitextensions, and switch branch to the branch created with the tool

**Comment by pmiossec** [comment] 2024-06-03 21:18
Duplicate of https://github.com/gitextensions/gitextensions/issues/11498
Fixed in https://github.com/gitextensions/gitextensions/pull/11500

Also related to https://github.com/gitextensions/gitextensions/issues/11562

**Closed by pmiossec** 2024-06-03 21:18 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
