### ISSUE TITLE
[NBug] WaitForInputIdle failed.  This could be because the process...

### ISSUE THREAD

**Issue by e-monsters** [gitextensions/gitextensions#11117] opened 2023-07-29 10:10 UTC
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.20
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.InvalidOperationException: WaitForInputIdle failed.  This could be because the process does not have a graphical interface.
   at System.Diagnostics.Process.WaitForInputIdleCore(Int32 milliseconds)
   at System.Diagnostics.Process.WaitForInputIdle()
   at GitCommands.Executable.ProcessWrapper.WaitForInputIdle() in C:\projects\gitextensions\GitCommands\Git\Executable.cs:line 218
   at GitUI.Infrastructure.PuttyHelpers.StartPageantIfConfigured(Func`1 sshKeyFileLoader) in C:\projects\gitextensions\GitUI\Infrastructure\PuttyHelpers.cs:line 77
   at GitUI.CommandsDialogs.FormPush.StartPageant(String remote) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormPush.cs:line 902
   at GitUI.CommandsDialogs.FormPush.PushChanges(IWin32Window owner) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormPush.cs:line 333
   at GitUI.CommandsDialogs.FormPush.PushClick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormPush.cs:line 204
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

I have this error when I am trying to push commits (from main app window or from commit window).

### Steps to reproduce

First scenario
1. create and add a commit without pushing it into remote repo
2. click push button in the main window app

Second scenario - It doesn't show up every time
1. create a commit and click "Commit & push" button

### Did this work in previous version of GitExtensions?

yes

**Comment by gerhardol** [comment] 2023-07-29 22:31
Duplicate of #9840 
See https://github.com/gitextensions/gitextensions/discussions/9840#discussioncomment-2061447, make sure putty paths are set

**Closed** 2023-07-30 02:13 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
