### ISSUE TITLE
'Windows-1252' is not a supported encoding name error while opening Forms Design

### ISSUE THREAD

**Issue by MrJithil** [gitextensions/gitextensions#9183] opened 2021-05-08 13:04 UTC
## Current behaviour
While we open any Forms File from GitExtensions latest source code using VS2019 instance, an error is popping out with the below message
"'Windows-1252' is not a supported encoding name. For defining a ....... (please see the below screenshot for the complete error"

## Expected behaviour

The form design should be opened and we should be able code our changes there.

## Steps to reproduce
* Take the latest master
* Open any forms dialogue
* See the error

## Screenshots
![image](https://user-images.githubusercontent.com/26359740/117540158-5d47c900-b02b-11eb-8e26-41c622ab153d.png)

## Did this work in the previous version of GitExtensions
It was worked till 2 days back. I added changes 4 days back. I think the issue stated from the latest code.

## Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 5.0

**Comment by RussKie** [comment] 2021-05-08 13:48
What VS version do you use?

**Comment by mstv** [comment] 2021-05-08 17:13
I am afraid this is caused by .NET 5.0, which does not support this encoding anymore.

**Comment by MrJithil** [comment] 2021-05-08 17:24
HotFix needed. My next few ideas on UI side.

**Comment by MrJithil** [comment] 2021-05-09 07:36
@RussKie could you please verify once you are free? I added the VS version details above.

**Comment by RussKie** [comment] 2021-05-09 08:25
I won't have time until mid next week when I'm back at work.

**Comment by pmiossec** [comment] 2021-05-09 21:48
Same for me (with VS 16.9.3)
It seems we are not alone but with no solution: https://developercommunity.visualstudio.com/t/preview-windows-forms-designer-for-net-core-broken/1395090

**Comment by RussKie** [comment] 2021-05-10 23:58
It is a known issue, https://github.com/dotnet/winforms-designer/issues/2916. Fixed in VS 16.10 Preview2.

**Closed by RussKie** 2021-05-10 23:58 UTC

**Comment by pmiossec** [comment] 2021-05-11 10:28
@MrJithil I imagine that it is a private repository and not a bad link...

**Comment by RussKie** [comment] 2021-05-11 12:12
Correct, it is a private repo.
