### ISSUE TITLE
[NBug] fatal: bad revision 'HEAD'

### ISSUE THREAD

**Issue by Madan-Appiah** [gitextensions/gitextensions#10792] opened 2023-03-08 01:43 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.14
- DPI 144dpi (150% scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" --max-count=100000 --glob=refs/stas[h] HEAD --
Working directory: C:\Git\sources\DhaanProjects\

```
GitExtUtils.ExternalOperationException: fatal: bad revision 'HEAD'
 ---> System.Exception: fatal: bad revision 'HEAD'
   --- End of inner exception stack trace ---
   at void GitUI.RevisionGridControl.PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs, bool forceRefresh)+() => { }
   at async Task GitUI.GitUIExtensions.InvokeAsync(Control control, Action action, CancellationToken token)
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

After Update.

### Steps to reproduce

After upgrading to GitExtensions-4.0.2.16100-25100ec1f.

### Did this work in previous version of GitExtensions?

yes

**Comment by RussKie** [comment] 2023-03-10 23:19
What are steps to reproduce this?

**Comment by gerhardol** [comment] 2023-03-12 12:46
Duplicate of #10740

**Closed by gerhardol** 2023-03-12 12:46 UTC
Labels: potential-duplicate, :mailbox_with_no_mail: needs: author feedback
