### ISSUE TITLE
Stage selected line(s) with "Ignore whitespace changes" :: error: patch failed ... patch does not apply

### ISSUE THREAD

**Issue by Muhammad-Hassaan** [gitextensions/gitextensions#5155] opened 2018-07-10 05:05 UTC
**What is the current behavior?**
- "Ignore whitespace changes" is enabled in the Commit Dialog
- some lines are selected
- right-click and "Stage selected line(s)"

**Output:** error: patch failed ... patch does not apply

Have tried with various different file encoding settings, but same issue. Disabling the "Ignore whitespace changes" option fixes the issue.

**What is the expected behavior?**
The selected lines should be staged.

**Environment you encounter the issue:**
- GitExtensions version: 2.50.02
- GIT version: git version 2.12.1.windows.1
- OS version: Windows 7
- .NET version: 4.7.02053

**Comment by gerhardol** [comment] 2018-07-10 09:37
Duplicate of #4496

**Closed by gerhardol** 2018-07-10 09:37 UTC
