### ISSUE TITLE
After clicking on "Created new branch here..." application hangs forever

### ISSUE THREAD

**Issue by AlexKarpiak** [gitextensions/gitextensions#12055] opened 2024-11-22 13:48 UTC
### Environment

- GitExtensions version: 5.1.1.17970
- GIT version:  2.47.0.windows.2
- OS version:  Windows 11
- .NET version:  .NET 8.0.11

### Issue description

After clicking on "Created new brunch here..." application hangs forever

Appeared after update to latest version.

### Steps to reproduce

- Right click on a brunch
- Clicking on "Created new brunch here"

### Did this work in previous version of GitExtensions?

Yes

**Comment by RussKie** [comment] 2024-11-22 23:24
I can't repro, the dialog opens and without any visible delay.

Can you please provide more information which could help triage the issue, the information provided is insufficient.

**Comment by Hatyme** [comment] 2024-11-25 09:02
Same Problem here. The command (F12) causing the hang up seems to be the following.

![Image](https://github.com/user-attachments/assets/c129f2dd-cc1f-4835-aa44-73f5652f3c59)

**Comment by Hatyme** [comment] 2024-11-25 09:11
The problem seems to be contained to a specific repository, but on every instance of that repository. On first look i can't see anything special about the repository.

**Comment by RussKie** [comment] 2024-11-25 09:21
What do you get running this command from the cli?

**Comment by Hatyme** [comment] 2024-11-25 09:41
```
$ git log -z -1 --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" 542a79de19bdbc45bb32b67afd888f2511064558       
542a79de19bdbc45bb32b67afd888f2511064558b4f78accab540b4f4b686451d14237f72f4ee08d2635f7c80ef0e94dbd683b7bad79387b39b01f3d  
1732266682                                                                                                                
1732266682                                                                                                                
semantic-release-bot                                                                                                      
semantic-release-bot@email.com
semantic-release-bot                                                                                                      
semantic-release-bot@email.com
chore(release): 1.0.0 [skip ci]                                                                                           
                                                                                                                          
# 1.0.0 (22.11.2024)    

... several lines of commit message                                                                                                   

```

It seems to be too long and hangs in a less-like command. I don't know if this is relevant for the usage of GitExtensions.

**Comment by Hatyme** [comment] 2024-11-25 09:46
> The font make it difficult to read but the log command contains `-1`. We ask git the logs for only one commit and so the command should be finish pretty quickly and that's not the kind of command that could be long to run or have performance issue.
> 
> I see 2 probable reasons for this command to be long:
> 
> * the command is blocked by another git command run in the repository. Do you see a tool that could cause the issue? Maybe use the task manager to find git running processes.
> * git is doing some maintenance while running this command. It is doing `gc`. Is your repo big and have not been `gc` since a long time?

As far as i can see there should be no other blocking operations run in parallel.  `gc` runs in a second.

**Comment by Hatyme** [comment] 2024-11-25 10:04
Disabling Pager in Git does not help, so this does not seem to be the problem

**Comment by mstv** [comment] 2024-11-25 20:32
Reproducible with a long commit body (1000 lines Lorem Ipsum): https://github.com/mstv/test_lfs/tree/test_long_commit_body.
It hangs in the library call `process.StandardError.ReadToEnd()` at the callstack below.
I have inserted a `process.WaitForExit()`. Then it hangs in that call.
I am turning it into an async call.

```
 	[External Code]	
>	GitCommands.dll!GitCommands.RevisionReader.GetRevision(string commitHash, bool hasNotes, bool throwOnError, System.Threading.CancellationToken cancellationToken) Line 187	C#
 	GitCommands.dll!GitCommands.GitModule.GetRevision(GitExtensions.Extensibility.Git.ObjectId objectId, bool shortFormat, bool loadRefs) Line 980	C#
 	GitUI.dll!GitUI.CommandsDialogs.FormCreateBranch.commitPickerSmallControl1_SelectedObjectIdChanged(object sender, System.EventArgs e) Line 169	C#
 	GitUI.dll!GitUI.UserControls.CommitPickerSmallControl.SetSelectedCommitHash(string commitHash) Line 40	C#
 	GitUI.dll!GitUI.CommandsDialogs.FormCreateBranch.FormCreateBranch(GitExtensions.Extensibility.Git.IGitUICommands commands, GitExtensions.Extensibility.Git.ObjectId objectId, string newBranchNamePrefix) Line 49	C#
 	GitUI.dll!GitUI.GitUICommands.StartCreateBranchDialog.__Action|0() Line 453	C#
 	GitUI.dll!GitUI.GitUICommands.DoActionOnRepo(System.Windows.Forms.IWin32Window owner, System.Func<bool> action, bool requiresValidWorkingDir, bool changesRepo, System.EventHandler<GitExtensions.Extensibility.Git.GitUIEventArgs> preEvent, System.EventHandler<GitExtensions.Extensibility.Git.GitUIPostActionEventArgs> postEvent) Line 322	C#
 	GitUI.dll!GitUI.GitUICommands.StartCreateBranchDialog(System.Windows.Forms.IWin32Window owner, GitExtensions.Extensibility.Git.ObjectId objectId, string newBranchNamePrefix) Line 457	C#
 	GitUI.dll!GitUI.CommandsDialogs.FormBrowse.ExecuteCommand(int cmd) Line 2124	C#
 	ResourceManager.dll!ResourceManager.GitExtensionsFormBase.ProcessHotkey(System.Windows.Forms.Keys keyData) Line 60	C#
 	GitUI.dll!GitUI.CommandsDialogs.FormBrowse.ProcessHotkeyImpl(System.Windows.Forms.Keys keyData) Line 2057	C#
 	GitUI.dll!GitUI.CommandsDialogs.FormBrowse.ProcessHotkey(System.Windows.Forms.Keys keyData) Line 2041	C#
 	ResourceManager.dll!ResourceManager.GitExtensionsFormBase.ProcessCmdKey(ref System.Windows.Forms.Message msg, System.Windows.Forms.Keys keyData) Line 109	C#
 	[External Code]	
 	ResourceManager.dll!ResourceManager.GitExtensionsControl.ProcessCmdKey(ref System.Windows.Forms.Message msg, System.Windows.Forms.Keys keyData) Line 131	C#
 	[External Code]	
 	GitUI.dll!GitUI.GitUICommands.StartBrowseDialog(System.Windows.Forms.IWin32Window owner, GitExtensions.Extensibility.BrowseArguments args) Line 1158	C#
 	GitUI.dll!GitUI.GitUICommands.RunBrowseCommand(System.Collections.Generic.IReadOnlyList<string> args) Line 1595	C#
 	GitUI.dll!GitUI.GitUICommands.RunCommandBasedOnArgument(System.Collections.Generic.IReadOnlyList<string> args, System.Collections.Generic.IReadOnlyDictionary<string, string> arguments) Line 1440	C#
 	GitUI.dll!GitUI.GitUICommands.RunCommand(System.Collections.Generic.IReadOnlyList<string> args) Line 1412	C#
 	GitExtensions.dll!GitExtensions.Program.RunApplication() Line 207	C#
 	GitExtensions.dll!GitExtensions.Program.Main() Line 110	C#
```

**Comment by AlexKarpiak** [comment] 2024-11-27 16:19
> I can't repro, the dialog opens and without any visible delay.
> 
> Can you please provide more information which could help triage the issue, the information provided is insufficient.

Actually, everything is working fine if I am trying to created new brunch from 'main' if there is no pending/uncommitted changes.
Once I have not committed files and trying to created new brunch the app hangs.

**Comment by mstv** [comment] 2024-11-27 22:22
As pointed out by @Hatyme, the hang was caused by a very long commit message.
Fixed in https://ci.appveyor.com/api/buildjobs/rohu1da3rysv20sv/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-5.2.0.17985-87f7f90a2.zip

> brunch

Enjoy your meal! :)

**Closed** 2024-12-03 22:53 UTC
Labels: status: reproducible, :construction: status: in progress
