### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by vittoso** [gitextensions/gitextensions#10523] opened 2022-12-14 14:53 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.39.0.windows.1
- Microsoft Windows NT 10.0.22000.0
- .NET 6.0.12
- DPI 120dpi (125% scaling)

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUIPluginInterfaces.NumberSetting`1.NumericUpDownBinding.LoadSetting(ISettingsSource settings, NumericUpDown control)
   at GitUIPluginInterfaces.SettingControlBinding`2.LoadSetting(ISettingsSource settings)
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.SettingsToPage()
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.LoadSettings()
   at GitUI.CommandsDialogs.SettingsDialog.RepoDistSettingsPage.SetCurrentSettings(RepoDistSettings settings)
   at GitUI.CommandsDialogs.SettingsDialog.RepoDistSettingsPage.SetLocalSettings()
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageHeader.<>c__DisplayClass2_0.<ConfigureHeader>b__0(Object a, EventArgs b)
   at System.Windows.Forms.RadioButton.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.RadioButton.set_Checked(Boolean value)
   at System.Windows.Forms.RadioButton.OnClick(EventArgs e)
   at System.Windows.Forms.RadioButton.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Settings -> Plugins -> Periodic background fetch -> clicking on different "Setting soure"

### Steps to reproduce

Open Settings. Go to Plugins -> Periodic background fetch.
Click on different "Setting source" on the radiobutton on the top.

### Did this work in previous version of GitExtensions?

it worked on last 3.5 version

**Comment by gerhardol** [comment] 2022-12-14 18:43
Duplicate of https://github.com/gitextensions/gitextensions/issues/10323
Fixed in https://github.com/gitextensions/gitextensions/pull/10445

**Closed by gerhardol** 2022-12-14 18:43 UTC
Labels: :eyeglasses: status: needs review
