### ISSUE TITLE
When solving merge conflicts, conflicted files get left in a "deleted" state making it impossible to continue rebase

### ISSUE THREAD

**Issue by forbjok** [gitextensions/gitextensions#2469] opened 2014-09-30 13:34 UTC
Attempting to continue rebase always results in the "You must edit all merge conflicts and then
mark them as resolved using git add" even after solving all conflicts in the resolve conflicts window.

This bug is present in the current release/2.48 branch, but not in 2.48 release.

**Comment by itsho** [comment] 2020-07-22 08:40
1. Quite old issue :-(
2. I've checked and this is definitely **not** always happening. (at least with current version - Git Extensions 3.4.2.9737 - Build 082cfd97d09c47346638b1873f5c8cf6ed139382)
3. I think that it's happening when you have unstaged file that you need to stage.
I suspect that it caused when you have diff in binary files.

**Comment by gerhardol** [comment] 2020-07-22 19:23
Could also occur due to whitespace changes and .gitattributes changes

A better description on how to reproduce is needed anyway

**Comment by RussKie** [comment] 2020-07-24 02:59
Closing due to the age.

**Closed by RussKie** 2020-07-24 02:59 UTC
