### ISSUE TITLE
Update installs new version of gitextensions in default folder C:\Program Files (x86) instead of the folder where old version of Git Extensions was installed 

### ISSUE THREAD

**Issue by seab4ss** [gitextensions/gitextensions#7952] opened 2020-04-06 14:56 UTC
Old version ( 3.2.1) of GixExtensions was installed in D:\Dev\Utils\GitExtensions.
Update process uninstalled old version from D:\Dev\Utils\GitExtensions and installed new version 3.3.1 to C:\Program Files (x86)\GitExtensions 
Instead update process should have installed new version to D:\Dev\Utils\GitExtensions

System info  - Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4150.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment] 2020-04-07 08:56
Duplicate of #7575

**Closed** 2020-04-07 08:57 UTC
Labels: area: installer
