### ISSUE TITLE
Search causes errer

### ISSUE THREAD

**Issue by Ticalie** [gitextensions/gitextensions#2646] opened 2015-02-10 12:46 UTC
![image](https://cloud.githubusercontent.com/assets/1857720/6127445/3836eba6-b12b-11e4-9b9b-f7569a90d360.png)

--- GitExtensions2.48.03, Git 1.9.4.msysgit.2, Microsoft Windows NT 6.3.9600.0

**Comment by KindDragon** [comment] 2015-02-10 12:51
Duplicate of #2597

**Closed by KindDragon** 2015-02-10 12:51 UTC
