### ISSUE TITLE
[NBug] Value must not be null.

### ISSUE THREAD

**Issue by Schweigst** [gitextensions/gitextensions#10507] opened 2022-12-08 21:16 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

```
System.Exception: Value must not be null.
   at Microsoft.Validates.Fail(String message)
   at Microsoft.Validates.NotNull[T](T value)
   at GitUI.CommandsDialogs.SettingsDialog.SettingsTreeViewUserControl.textBoxFind_KeyUp(Object sender, KeyEventArgs e)
   at System.Windows.Forms.Control.OnKeyUp(KeyEventArgs e)
   at System.Windows.Forms.TextBox.OnKeyUp(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Open Git Extensions and then open Settings dialog

### Steps to reproduce

1 - Uninstall previous version 3.5.4.12724
2 - Install 4.0.0
3 - Start Git Extension
4 - Open settings dialog

### Did this work in previous version of GitExtensions?

Yes, worked with 3.5.4.12724

**Comment by gerhardol** [comment] 2022-12-08 23:28
Duplicate of #10377

**Closed** 2022-12-08 23:36 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
