### ISSUE TITLE
[NBug] Az objektumhivatkozás nincs beállítva semmilyen objektumpél...

### ISSUE THREAD

**Issue by szarkab123** [gitextensions/gitextensions#6724] opened 2019-05-31 22:38 UTC
## Error Details
```
System.NullReferenceException: Az objektumhivatkozás nincs beállítva semmilyen objektumpéldányra.
   a következő helyen: Git.hub.Repository.GetBranches()
   a következő helyen: GitHub3.GitHubRepo.GetBranches()
   a következő helyen: GitUI.CommandsDialogs.RepoHosting.CreatePullRequestForm.<>c__DisplayClass22_0.<<PopulateBranchesComboAndEnableCreateButton>b__0>d.MoveNext()
--- Verem vége nyomkövetés a kivétel előző előfordulási helyétől kezdve ---
   a következő helyen: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   a következő helyen: GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
create pull request, private git hub project

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a

**Comment by mstv** [comment] 2019-06-01 00:35
@szarkab123, could you try, please, whether the bugfix #6515 [build](https://ci.appveyor.com/api/buildjobs/a0y02dkj2smrxxt9/artifacts/Setup%2FGitExtensions-Portable-3.2.0.6029.zip) solves your problem?

**Comment by gerhardol** [comment] 2019-06-05 23:13
Duplicate of #6625

**Closed by gerhardol** 2019-06-05 23:13 UTC
Labels: status: incorrectly filled template, status: more info requested
