### ISSUE TITLE
Autoupdate installs GitExtensions in the default folder rather than the previously installed location

### ISSUE THREAD

**Issue by Qrox** [gitextensions/gitextensions#9626] opened 2021-10-08 07:22 UTC
## Current behaviour
When a new version is out, GitExtensions asks if you want to update, and if you choose to update automatically (as opposed to downloading the installer), the installer is automatically downloaded and executed. However, the installer then installs the new version in the default folder (`C:\Program Files (x86)`) rather than the previously installed location.

## Expected behaviour
The installer installs GitExtensions to whereever GitExtension was originally located.

## Steps to reproduce
1. Install GitExtensions in a custom folder
2. Wait for new update
3. Choose autoupdate
4. Wait and see that GitExtensions is installed in `C:\Program Files (x86)`

## Screenshots
N/A

## Did this work in previous version of GitExtensions
No, AFAIK.

## Environment
Git Extensions v3.5.3

## Diagnostics
N/A

**Comment by pmiossec** [comment] 2021-10-08 07:25
Duplicate of #7575. We are looking for a contribution of someone knowing Wix installer.
If you could contribute a PR, please do it...

**Closed by pmiossec** 2021-10-08 07:25 UTC
