### ISSUE TITLE
Stealing focus from other apps when long running operation finishes

### ISSUE THREAD

**Issue by tomasfejfar** [gitextensions/gitextensions#7272] opened 2019-10-09 17:50 UTC
## Current behaviour

Stealing focus from other apps when long running operation finishes

## Expected behaviour

Does not :)

## Steps to reproduce

* make some changes and do "Commit & Push" (make sure it takes some time to do the push)
* switch to PhpStorm (or maybe any other app)
* after a while GitEx steals focus and is brought to foreground
* it does not really have focus - if you Alt+Tab you get "again" to GitEx (it's still in foreground), you need to do 2x Alt+Tab to get back to the program you were previously (only now is GitEx back in background)

## Version
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

**Comment by tomasfejfar** [comment] 2019-10-09 17:53
Oh, sorry. It's actually when the commit progress window is closed and push progress window is opened when the focus is stolen.

**Comment by kbilsted** [comment] 2019-10-10 17:54
I can reproduce on main branch. 

Initially I thought it was a simple replace
`Ok.Focus();` with `Ok.Select();`  in `GitUI.FormStatus.Done(bool)` but it's something else stealing the focus. Need some pointers to be able to continue.

**Comment by pmiossec** [comment] 2019-10-10 18:21
Duplicate of #6220?

An issue with the external dependency Conemu.
We think that we don't have the possibility of fixing that, except by disabling the use of this lib in the settings.

**Comment by mycroes** [comment] 2021-07-13 12:44
I don't think this is ConEmu related, but a duplicate of #6220 seems logical though. I just updated #6220 with a reliable way to trigger this behavior, without ConEmu. I have had ConEmu disabled for years because of this issue, but since 3.5.1 it bugs non-ConEmu as well.

**Closed** 2021-11-07 22:40 UTC
