### ISSUE TITLE
[NBug] fatal: bad revision '5726'

### ISSUE THREAD

**Issue by Rarta** [gitextensions/gitextensions#10896] opened 2023-04-19 07:29 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.40.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.14
- DPI 96dpi (no scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" --max-count=100000 --glob=refs/stas[h] 5726 --
Working directory: C:\Users\Arturas\Desktop\Einpix_work_files\com.einpix.android\

```
GitExtUtils.ExternalOperationException: fatal: bad revision '5726'
 ---> System.Exception: fatal: bad revision '5726'
   --- End of inner exception stack trace ---
   at void GitUI.RevisionGridControl.PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs, bool forceRefresh)+() => { }
   at async Task GitUI.GitUIExtensions.InvokeAsync(Control control, Action action, CancellationToken token)
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

I was searching the branch by text: "5726"

### Steps to reproduce

![image](https://user-images.githubusercontent.com/41193096/233001027-15ccea04-9b50-4927-9134-5274ed21eacf.png)

**Comment by gerhardol** [comment] 2023-04-19 07:34
Duplicate of #10740

Changed in upcoming 4.1

**Comment by pmiossec** [comment] 2023-04-19 07:34
GitExtensions let the git error be displayed to the user to inform him that the value entered is not good (an improvement done in v4.0)
So it's not a GitExtension issue.
But as it is not really user friednly, it has been improved in #10832 that will be part of v4.1.

**Closed by gerhardol** 2023-04-19 07:34 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
