### ISSUE TITLE
Commit hangs, when checking in only icons

### ISSUE THREAD

**Issue by GitUser21345** [gitextensions/gitextensions#6493] opened 2019-04-21 04:22 UTC
## Issue
Adding plenty of new *.png files for icons, after pressing the commit button to apply the commit changes to a local repository nothing happens and the blue wait cursor spins forever. Trying to interact with the application, the windows message "... app not responding ..." occurs. I could even re-start the application and the same issue occured. 

## Expected
is, that GitExtensions shows the message "There are no files staged ..." or "Please enter commit message" or is doing the commit. 

By changing the contents of a single *.cpp file inside the same repository the issue was gone and everything is working as expected. 

## Steps to reproduce

The issue is **not reproducible**. When trying to do the same now everything works even with the same repository.
 

## Screenshots

Unfortunately not anymore available

## Did this work in previous version of GitExtensions

Happend like this for the very first time

## Environment
 
- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by mast-eu** [comment] 2019-04-21 12:11
Sounds somehow similar to #6225.

**Comment by RussKie** [comment] 2019-04-21 12:15
> The issue is **not reproducible**. When trying to do the same now everything works even with the same repository.

If this issue is not reproducible, how can  we fix it?

**Comment by gerhardol** [comment] 2019-04-21 19:36
Duplicate of #6225 
An improvement in #6366, an updated correction in #6492

**Closed by gerhardol** 2019-04-21 19:36 UTC
Labels: status: more info requested, status: needs review

**Comment by GitUser21345** [comment] 2019-04-23 05:48
@RussKie: Funny response. I don#T know, but I am jsut reporting. 
@gerhardol: No it is not a duplicate, as I was checking in 145 files, and adding one more the issue was gone. 
The issue was reproducible several times until I check in the additional c file. I guess the issue has to do something with the treatment of binary files!

Please re-open, as it is not solved.

**Comment by RussKie** [comment] 2019-04-23 07:05
No, there is nothing funny about submitting a report about an issue that can't be reproduced.
It is pretty simple, if we can't reproduce it - we can't fix it.

**Comment by gerhardol** [comment] 2019-04-23 07:22
Issue #6225 could appear 'randomly', everything in the description points to that issue.
If you can reproduce in master, please open a new issue.

**Comment by GitUser21345** [comment] 2019-04-25 05:45
@RussKie: I accept, that you might not be able to fix it right now, but my decription might lead to find the origin of the bug. A bug is still a bug, even if not reproducible. Very likely somewhen it will happen again.
