### ISSUE TITLE
Keep git output

### ISSUE THREAD

**Issue by PeterMinin** [gitextensions/gitextensions#10206] opened 2022-09-21 22:05 UTC
### Feature description

Currently we have 2 options regarding the output printed by potentially long-running git commands, such as `fetch`, `checkout`, etc.:

1. Keep the dialog open after completion of every such command. This may show some useful extra info, or a warning, but it slows you down when you need to do many little things and can get annoying.
2. Dismiss the output right away. This speeds up routine operations, but it deprives the user from information that git developers thought could be useful to show.

There is a "Git command log" window, but it can't show the commands' output, as far as I can tell.

I think a middle ground would be good here: save the output _for later_ and don't require the user to read and acknowledge it before proceeding. The log could be integrated into the existing "Git command log", but maybe it even deserves a tab of its own next to "Console" to make it easy to keep an eye on.

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.0.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4515.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment] 2022-09-21 22:39
Related to #7244

**Comment by RussKie** [comment] 2022-09-22 02:05
Duplicate of #7244

**Comment by PeterMinin** [comment] 2022-09-22 18:09
@RussKie @gerhardol Thanks for taking a look. I agree the issue you referred to is relevant, i.e. implementing it _would_ cover this issue, but not necessarily in the best way. I believe the focus of that request is largely on troubleshooting and thus mainly on _persistence_ of the logs. Here, on the other hand, the focus is on normal operation, so I'd like to point out some specifics, in case you want to reconsider:

- Persistence is not a requirement: the logs could exist only in the current session, like console output does. (I guess the title of the issue may be confusing, an edit would be welcome.)
- The main scope is the long-running commands, ones that open a progress window. Maybe other "explicit" user commands too, but that's a second priority.
- The UI for the user commands' logs should be at least somewhat separate from the existing log of background operations. At a minimum, I would say, a filter in the log. At a maximum, if the feature is expected to be popular enough, a tab in the main window, near the Console.

**Comment by mstv** [comment] 2022-09-22 21:21
Occasionally, I close the progress dialog too quickly (my click finger is quicker than I think).
It would be good to keep that *last* output. Then I could activate `Close Process dialog when process succeeds`.

> a tab in the main window, near the Console.

That would be the best compromise IMO.

**Comment by vbjay** [comment] 2022-10-22 17:39
> Occasionally, I close the progress dialog too quickly (my click finger is quicker than I think). It would be good to keep that _last_ output. Then I could activate `Close Process dialog when process succeeds`.
> 
> > a tab in the main window, near the Console.
> 
> That would be the best compromise IMO.

I would make sure some limit was set.  Make this log a tail like command that does not crash the app because you left app running for days and the log has grown and eating working set of process.

**Closed** 2024-10-25 22:31 UTC
Labels: type: feature request, :construction: status: in progress
