### ISSUE TITLE
Crash when several push repository for the same remote.

### ISSUE THREAD

**Issue by teyssieuman** [gitextensions/gitextensions#6976] opened 2019-08-01 08:30 UTC
## Current behaviour

The GitExtention browser do not support remotes with several push URL. It crash as soon as I open the interface on such a depot.

## Expected behaviour

The GitExtension browser do not crashes and allow me to push on several remotes in one action.

## Steps to reproduce

A it is avised here : 
    https://stackoverflow.com/questions/14290113/git-pushing-code-to-two-remotes

I added two push repository to the same remote :
> git remote set-url --add --push origin git://original/repo.git
> git remote set-url --add --push origin git://another/repo.git

Then the GitExtensions browser crashes as soon as I open it on this repository.

## Did this work in previous version of GitExtensions

This is the firs time I use this feature ...

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.3801.0
- DPI 96dpi (no scaling)

## Error Details
```
System.Exception: Remote URLs should appear in pairs.
   à GitCommands.GitModule.<GetRemotesAsync>g__ParseRemotes|154_0(IEnumerable`1 lines)
   à GitCommands.GitModule.<GetRemotesAsync>d__154.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync>d__4.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__27.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à GitUI.BranchTreePanel.RepoObjectsTree.Tree.<<UICommands_PostRepositoryChanged>b__6_0>d.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()

**Comment by gerhardol** [comment] 2019-08-01 09:08
Duplicate of #6922 
This issue has a more informative description, but the first has the exception message most users see

Multiple push urls are not supported right now

**Comment by teyssieuman** [comment] 2019-08-01 12:36
I just added the Error details ...

**Comment by gerhardol** [comment] 2019-08-01 13:17
> Shall I Close this issue ?

I can do it.

Thanks for the report, supports the point that users want support for multiple push repos.
Contributions are welcome.

**Closed by gerhardol** 2019-08-01 13:17 UTC

**Comment by teyssieuman** [comment] 2019-08-05 07:37
Thank you. Unfortunately, my c# abilities are not sufficient to think about contribute. Thanks for your job...
