### ISSUE TITLE
During interactive rebase user cannot reword a commit message to something starting with "#"

### ISSUE THREAD

**Issue by Mikilll94** [gitextensions/gitextensions#7859] opened 2020-03-10 20:45 UTC
## Current behaviour

I want to do an interactive rebase and change the commit message to something different which starts from "#". Right now it is not possible. The hash in the commit message is always deleted.

 This bug is shown on the GIF below:
![git_extensions_rebase_reword_hash](https://user-images.githubusercontent.com/17653648/76357537-2e936d00-6318-11ea-83eb-45f1bd072d3d.gif)

As you can I want to change the commit message from "Commit three" to "#Commit three" but it is not possible.

## Expected behaviour

I should be able to change the commit message during an interactive rebase to something starting with "#".

## Steps to reproduce

1. Start the interactive rebase.
2. Change "pick" to "r" in the selected commit.
3. In the next screen, you are not able to change the commit message to something starting from "#".

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4121.0
- DPI 120dpi (125% scaling)

**Comment by pmiossec** [comment] 2020-03-10 21:13
First, it seems that you are not doing your commit rewrite well.

The first text editor that Git opens should be only used to let the user choose its actions. The first lines of commits message are just here to help the user.

That's in the 2nd text editor opening that you should update the commit message.

Second, indeed, starting a commit line with a # won't have the effect you want and will make the line be removed by git because it sees it as a comment.

So the problem is not with Gitextensions but with git.

There is a way to work around this problem by using another comment char but you will have to use the command line.

This issue has already been discussed (but I can't find it from my smartphone).

**Comment by RussKie** [comment] 2020-03-31 11:36
Thank you @pmiossec for the the explanation. Closing.

**Closed by RussKie** 2020-03-31 11:36 UTC
Labels: type: git issue
