### ISSUE TITLE
[NBug] 路径中具有非法字符。

### ISSUE THREAD

**Issue by wuchang** [gitextensions/gitextensions#8733] opened 2021-01-09 10:04 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: 路径中具有非法字符。
   在 System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   在 System.IO.Path.Combine(String path1, String path2, String path3, String path4)
   在 GitCommands.Settings.ConfigFileSettings.CreateSystemWide(Boolean allowCache)
   在 GitCommands.Settings.ConfigFileSettings.CreateEffective(GitModule module)
   在 GitCommands.GitModule.get_EffectiveConfigFile()
   在 GitCommands.GitModule.get_LocalConfigFile()
   在 GitCommands.GitModule.GitUIPluginInterfaces.IGitModule.get_LocalConfigFile()
   在 GitCommands.Remotes.ConfigFileRemoteSettingsManager.GetDisabledRemotes()
   在 GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync>d__4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__28.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass42_0.<<AddTree>b__1>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information

:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: 路径中具有非法字符。
   在 System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   在 System.IO.Path.Combine(String path1, String path2, String path3, String path4)
   在 GitCommands.Settings.ConfigFileSettings.CreateSystemWide(Boolean allowCache)
   在 GitCommands.Settings.ConfigFileSettings.CreateEffective(GitModule module)
   在 GitCommands.GitModule.get_EffectiveConfigFile()
   在 GitCommands.GitModule.get_LocalConfigFile()
   在 GitCommands.GitModule.GitUIPluginInterfaces.IGitModule.get_LocalConfigFile()
   在 GitCommands.Remotes.ConfigFileRemoteSettingsManager.GetDisabledRemotes()
   在 GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync>d__4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__28.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass42_0.<<AddTree>b__1>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.2.windows.2
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.2.windows.2
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2021-01-09 21:15
Duplicate of #8618 

The Win directory CommonApplicationData (normally C:\ProgramData, to get the Git global config file pointed: \Git\config) contains illegal characters. 
Does the file exist?

**Closed** 2021-01-24 06:12 UTC
Labels: :mailbox_with_no_mail: needs: author feedback, :zzz: status: no recent activity
