### ISSUE TITLE
Windows/Super key toggles "Show revision graph" setting in Git Extensions

### ISSUE THREAD

**Issue by eitland** [gitextensions/gitextensions#4455] opened 2018-02-10 15:05 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In Linux Neon (KDE) when I press the Windows key while the revision graph is focused it toggles the "Show revision graph" setting. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open a repository
2. Click in the revision graph to focus it
3. Press the Windows/Super key 
4. Note that the "Show revision graph" setting has been toggled

**What is the expected behavior?**

The menu shows up in my desktop environment without toggling anything inside Git Extensions

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version:  2.7.4
- OS version: KDE 5.42.2, Linux 4.4.0-112-generic #135-Ubuntu SMP 

**Did this work in previous version of GitExtensions (which)?**

Not sure, I also reported this #3428 a while ago but haven't tested since then.

**Comment by eitland** [comment] 2018-02-12 10:57
Hi @RussKie !

I saw you added the pull request only tag to this as well as my other issue.

What does that mean? I searched the repo but couldn't find any docs that explained the meaning of this tag.

**Comment by RussKie** [comment] 2018-02-12 12:08
This means that the issue isn't likely to be addressed by the core team. If
any of the users, like yourself, wish to have it fixed - they will need to
send a pull request with a fix.

The main reason - none of the core members use or develop on Linux.
The other reason - Linux isn't on our future roadmap. For details please
see #4308.

**Comment by eitland** [comment] 2018-02-12 17:41
I see, thanks for the quick reply.

I really loved that Git Extensions was available on Linux but as has already been pointed out the current releases works pretty well on Linux so I'm just going to say thanks a lot for making it available and giving it a chance.

Good luck with the work going forward!

**Closed** 2021-08-21 05:53 UTC
Labels: :bug: type: bug, area: linux/mono, :neckbeard: status: pull request only
