### ISSUE TITLE
[NBug] Invoke or BeginInvoke cannot be called on a control until t...

### ISSUE THREAD

**Issue by hyzcan** [gitextensions/gitextensions#12027] opened 2024-11-07 17:37 UTC
### Environment

- Git Extensions 5.1.0.17965
- Build f9e558c2f1645008b4c426f847cadbf10c92fcd0
- Git 2.46.2.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.10
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at GitUI.FileStatusList.<OnUICommandsSourceSet>g__UICommands_PostSettings|50_1(Object sender, GitUIPostActionEventArgs e) in C:\projects\gitextensions\src\app\GitUI\UserControls\FileStatusList.cs:line 266
   at GitUI.GitUICommands.InvokePostEvent(IWin32Window ownerForm, Boolean actionDone, EventHandler`1 gitUIEventHandler) in C:\projects\gitextensions\src\app\GitUI\GitUICommands.cs:line 1274
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent) in C:\projects\gitextensions\src\app\GitUI\GitUICommands.cs:line 326
   at GitUI.GitUICommands.StartSettingsDialog(IWin32Window owner, SettingsPageReference initialPage) in C:\projects\gitextensions\src\app\GitUI\GitUICommands.cs:line 942
   at GitUI.CommandsDialogs.Menus.ToolsToolStripMenuItem.OnShowSettingsClick(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\Menus\ToolsToolStripMenuItem.cs:line 76
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

### Steps to reproduce

- open a repo
- double-click any line in the revision graph
- used to bring up a separate commit details dialog but now an error window pops up
- or try to open the settings dialog and close
- same error window pops up

**Comment by pmiossec** [comment] 2024-11-07 17:53
Duplicate of #12026. Closing as we will continue the discussion there.

**Closed by pmiossec** 2024-11-07 17:53 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
