### ISSUE TITLE
Commit dialog blocks other dialogs

### ISSUE THREAD

**Issue by TamaHobbit** [gitextensions/gitextensions#5810] opened 2018-11-26 10:03 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The commit dialog blocks other dialogs from being opened, such as opening a commit from a file history window.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open a repository in gitextensions. Open file history for any file. Observe that double clicking on any commit opens that commit in a new window. From the main window, open the commit window (cntr+space). From the file history window, double click a commit. It no longer works. In fact, selecting other commits also no longer works.

**What is the expected behavior?**
Double clicking a commit from the history window should always open a window to view that commit, even when you have the commit window open. The file history window should also still respond to selecting other commits.

**Environment you encounter the issue:**
- GitExtensions version: 2.52
- GIT version: 1.9.4.msysgit.0
- OS version: Windows 7 Enterprise
- .NET version: 4.0

**Did this work in previous version of GitExtensions (which)?**
No.

**Comment by vbjay** [comment] 2018-11-26 13:11
Commit dialog has been modal for a long time.  We don't have a version 2.52.  2.51 only gets bug fixes per our [ReadMe](https://github.com/gitextensions/gitextensions/blob/master/README.md)  V 3.0 is being worked on and released soon.

**Comment by TamaHobbit** [comment] 2018-11-26 13:21
Correct about the version; I was using GitExtensionsMod, but I have now updated to the latest RC2 and get the same issue. This is now my version:

- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.19.2.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3130.0
- DPI X:100,00 % Y:100,00 %

When you say "Commit dialog has been modal for a long time", are you saying the same thing as I put in the final line of the bug report, that this bug has always been here, or are you saying that you do not consider this a bug? The history window just doesn't respond at all to the mouse. It seems pretty clearly a bug to me.

**Comment by vbjay** [comment] 2018-11-26 13:45
It's a [MODAL](https://en.wikipedia.org/wiki/Modal_window) dialog.  You can view history on files in the commit dialog.  

![image](https://user-images.githubusercontent.com/3629489/49017521-0b5ea180-f157-11e8-8e16-ca714a359ed9.png)

It was designed that way.  It is modal for a reason.  Close the dialog.  Do whatever, bring it back up when needed.

Did stuff in commit dialog.  
![image](https://user-images.githubusercontent.com/3629489/49017649-5c6e9580-f157-11e8-91ad-0a6b1f0ac1ca.png)

Closed it and then reopened.

![image](https://user-images.githubusercontent.com/3629489/49017739-93dd4200-f157-11e8-809d-182abffad7fb.png)

**Comment by gerhardol** [comment] 2018-11-26 22:57
This has been discussed a number of times. It is possible to for instance stage/unstage files from Browse, but the Commit dialouge is modal

Duplicate of #5535

**Closed by gerhardol** 2018-11-26 22:57 UTC
