### ISSUE TITLE
Blame previous revision without function

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6605] opened 2019-05-19 20:52 UTC
## Current behaviour

try to show the blame for a previous revision
nothing happens

## Expected behaviour

blame of previous revision is shown

## Steps to reproduce

- open blame for GitUI/CommandsDialogs/SubmodulesDialog/FormAddSubmodule.cs
- goto line 75
- chose `Blame previous revision` from the context menu

## Screenshots

![grafik](https://user-images.githubusercontent.com/36601201/57987843-945ff100-7a87-11e9-8e64-31049f13298e.png)

## Did this work in previous version of GitExtensions

at least not in 3.00.00.4433

## Environment

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment] 2019-05-19 22:26
I had to blame absolutely a file this friday so I played a little with it and I think I understood what it is doing (and that I find strange)...

I propose you to test this version: https://github.com/pmiossec/gitextensions/tree/improve_blame

Now, do the same thing and it will do something 😉 
In the version you have, it is doing nothing because you don't have all the history ( always this problem of rename -- that is quick fixed in my branch--).

And that's where I personnaly find that it is doing a strange thing.
I would expect that this feature select the first commit in the list before the one introducing the lines.
In fact, it tries to select the commit introducing the lines before the one introduced by the commit. In your case a commit of 2009, not in the commit listed by the broken actual version.

For me the behavior is not the one expected because:
- it does not match to the label of the feature
- I don't understand the logic that make GE to go to the commit of the first line replaced even if that replace 3 lines from different commits.

I think the selected commit should be either the one in the list just before the one corresponding to this lines (easier to do and to use, I think).
Or the newest among all the lines replaced (but that's hard to determine).

**Comment by pmiossec** [comment] 2019-05-19 22:41
>nothing happens

To be clearer, I think that in your version, it is looking in the list for a commit that is not present, so it does nothing...

**Comment by mstv** [comment] 2019-05-27 20:39
> I would expect that this feature selects the first commit in the list before the one introducing the lines.

Exactly! Thank you for the analysis.

Regarding your commit 095d915 "Blame: Display avatars":
* The height of the avatars seems to be less than the texts's.
* The avatars should be displayed only if they are enabled for the revision grid.

![grafik](https://user-images.githubusercontent.com/36601201/58438354-bcc29d80-80ce-11e9-8078-dcda155f9cf7.png)  my settings: ![grafik](https://user-images.githubusercontent.com/36601201/58438510-833e6200-80cf-11e9-913b-ee3295f44d7c.png)

**Comment by pmiossec** [comment] 2019-05-27 21:27
Thanks for the quick review.

>The height of the avatars seems to be less than the texts's.

That's a big blocking problem. I spent a lot of time trying to solve it,
without success 😕

I didn't find a way to get the real height of a line which seems not to be
an integer value...
If I get the height from the font, the images are slightly too small and if
I add 1 pixel, they are too big!

So, I don't know how to be pixel perfect.

>

**Comment by mstv** [comment] 2019-05-27 22:23
I would try to access `TextView.FontHeight` etc. or if these properties cannot be accessed easily (because it is a submodule), the same calculation could be used (it works!):
```C#
        private static int GetFontHeight(Font font)
        {
            var max = Math.Max(
                TextRenderer.MeasureText("_", font).Height,
                (int)Math.Ceiling(font.GetHeight()));

            return max + 1;
        }
```

**Comment by RussKie** [comment] 2019-05-27 23:07
Do we _really_ want avatars in the blame window?

**Comment by gerhardol** [comment] 2019-05-28 04:50
Avatars use less space than names so probably better

**Comment by mstv** [comment] 2019-05-30 00:32
> WIP: try to solve "Blame to previous revision"

🎉 👍 In a short test, this seems to work as I expect it.

**Comment by RussKie** [comment] 2019-05-30 06:59
Do we need to patch 3.1.1 with the fix?

**Comment by pmiossec** [comment] 2019-05-30 08:13
>Do we need to patch 3.1.1 with the fix?

No, for 2 reasons...

That is a not a bug but a strange behavior, there from the beginning, so for more than 6 years.

That is a quick try and it is far from being finished.
only the normal case is managed and commits with no parents (easy) or more than one (I don't know how to handle it at the moment) are not handled.

Also trying to display the blame at the good line (like done before) is not still done.

**Comment by RussKie** [comment] 2019-05-30 08:15
Thank you 👍

**Comment by mstv** [comment] 2019-06-04 21:11
> only the normal case is managed and commits with no parents (easy) or more than one (I don't know how to handle it at the moment) are not handled.

I suggest to use the first parent. IMO each choice is correct. One can see in the revision tree that it is a parent of a merge. If one wants to see the other(s), it's only a click away.

(Hint: Don't try to rely too much on the sequential order of the parent branches. Henk Westhuis has prepared some improved variants of the revision graph #5782, #5783, unfortunately unfinished yet.)

**Comment by pmiossec** [comment] 2019-06-04 22:20
>I suggest to use the first parent.

That's what I already did as a quick fix.
But,you're right, it's probably enough as a first step.

>Don't try to rely too much on the sequential order of the parent branches.

I don't 😁

There is still the fact to better select the good lines to display to do...

**Comment by mstv** [comment] 2019-06-19 22:36
Short feedback: The tabs `Diff` and `Blame` are empty yet for merge revisions.

**Closed** 2019-07-06 12:07 UTC
