### ISSUE TITLE
request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by impunkj** [gitextensions/gitextensions#4533] opened 2018-02-26 11:01 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a Bug
**What is the current behavior?**
Getting error 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
When pulling i got the error 
 System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.

**What is the expected behavior?**
Must be pulled from origin
**Environment you encounter the issue:**
Window 10
- GitExtensions version:
2.5.1
- GIT version: 
- OS version: 

**Did this work in previous version of GitExtensions (which)?**
Yes in this version working last day

**Comment by EbenZhang** [comment] 2018-02-26 11:18
try upgrade you git to 2.16.2, during setup tick the option to use its credential manager.  remove the credential section(if any) from .gitconfig before you run the git installer.

**Comment by RussKie** [comment] 2018-02-26 21:09
Duplicate of #4523

**Closed by RussKie** 2018-02-26 21:09 UTC
