### ISSUE TITLE
Keyboard shortcuts stop working after commiting with Alt+C

### ISSUE THREAD

**Issue by TamaHobbit** [gitextensions/gitextensions#7347] opened 2019-10-22 09:58 UTC
## Current behaviour

After committing by pressing Alt+C, hotkeys stop working until you have transferred focus away and back to GitExtensions.

## Expected behaviour

Hotkeys always work.

## Steps to reproduce

(1. Start GitExtensions on a repository. Restarting is not required to re-trigger the bug)
2. Stage files.
3. Press Cntrl+4 or click to focus the commit message window, if it is not already focused.
4. Type some text as the commit message
5. Commit by pressing Alt+C. If you press the commit button with the mouse, the bug does not occur.
6. Try any shortcut, e.g. F12, Cntrl+space, Cntrl+b. It does not respond.
7. To fix the bug, either (1) transfer focus to some other application and back to GitExtensions - Clicking GitExtensions without having focused some other application first is not sufficient, or (2) right-click the previous commit and do a rebase --mixed; this spawns a seperate window which takes focus, and then GitExtensions is refocused after it is closed.

Out of the 100 times or so that I have done these steps, a few times the bug did not occur. In those cases, repeating steps 2-6 as many times as I want will not make the bug occur. But switching focus to some other application and then back to GitExtensions makes it happen again.

## Did this work in previous version of GitExtensions

I don't remember which versions I had tried before, but I had the same issue in all of them.

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment] 2019-10-26 21:32
@TamaHobbit, I followed your detailed "steps to reproduce". But the hotkeys still work correctly for me.

How are your console settings? I.e. do you use the console emulator? Do you let auto-close the git process window?

BTW: You can also commit by hitting `Ctrl+Enter`. There's a known issue #6420 that the `Ctrl` key can get stuck if the Console Emulator is used.

Do the hotkeys work if you commit using `Ctrl+Enter`?
Do the hotkeys work if you commit using `Alt+C` when you do not use the ConEmu?
![grafik](https://user-images.githubusercontent.com/36601201/67626238-e54eef00-f848-11e9-8469-cb8bbe8d68ea.png)

**Comment by TamaHobbit** [comment] 2019-10-29 13:15
Unticking 'Use Console Emulator ...' as you suggested fixes the problem for me. And then, ticking the box again, I get the problem again. So it is definitely another issue related to the Console Emulator.

**Comment by mstv** [comment] 2019-10-29 18:02
Thank you for your follow-up.

I guess the `Alt` key is still considered "pressed". Hitting `Alt` twice should unlock it.

Closing as duplicate of #6420.

**Closed** 2019-10-29 18:02 UTC
Labels: area: user experience, status: workaround available, type: dependency bug
