### ISSUE TITLE
Disappearing scrollbar in diff control

### ISSUE THREAD

**Issue by mdonatas** [gitextensions/gitextensions#5781] opened 2018-11-15 12:50 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Horizontal scrollbar disappears even though there is hidden content
![image](http://spurgius.com/interwebs/img/20181115144001_disappearing-scrollbar.gif)

or
(notice that you can't scroll to the right in diff)
![image](https://user-images.githubusercontent.com/483659/48553690-e8292c00-e8e4-11e8-9f88-3f2b228951fc.png)

The most annoying cases are where no amount of vertical scrolling reveals horizontal scrollbar. Then the only way to view a diff is with an external tool.

**Environment you encounter the issue:**

- GitExtensions version: master @ 61b97e7d71f9ae067774674afe451c109ea8851d

**Did this work in previous version of GitExtensions (which)?**
Yes, 2.5 or probably before the diff/text viewer control was refactored to show scrollbars on per-need basis

**Comment by spdr870** [comment] 2018-11-15 12:51
I get this a lot. Not sure how to simulate it. I did notice that the scroll bar uses the current visible text to determine the scrollbar and not the entire text.

A very annoying big

**Comment by drewnoakes** [comment] 2018-11-15 13:42
@mdonatas are you using UI scaling?

**Comment by mdonatas** [comment] 2018-11-15 13:53
> @mdonatas are you using UI scaling?

Not on the main or on the monitor where this was recorded. But third (laptop) monitor is at 1.25% scaling. Although this doesn't seems to have any effect since I think main monitor decides the scaling factor.

**Comment by drewnoakes** [comment] 2018-11-15 14:13
Was wondering if the text editor was not using the whole vertical height to compute text width due to UI scaling. Doesn't seem that's the case though.

**Comment by pmiossec** [comment] 2018-11-15 21:46
Just for information/tracking, duplicate of #5612

**Comment by mdonatas** [comment] 2018-11-15 21:54
Closing since it's a duplicate of #5612

**Comment by pmiossec** [comment] 2018-11-15 22:00
I think we should close the other one because the discussion is here and the description is better...

**Comment by RussKie** [comment] 2018-11-15 23:14
Duplicate of #5612

**Comment by jbialobr** [comment] 2018-12-06 07:58
@RussKie I know you want to ship the v3 but it should be fixed first. I would even consider reverting the commit that caused this.

**Comment by RussKie** [comment] 2018-12-06 08:00
Do you know which one?

**Comment by spdr870** [comment] 2018-12-06 09:34
I might have found some more info on this issue. If the issue occurs, I noticed that I can do strange things when I move the splitter between the diff viewer and the filelist. Maybe the cause is not the diff viewer, but the resizing of the splitter that is now saved. Notice the screenshot below. You can also make the filelist bigger, and move the scrollbar out of the screen:
![image](https://user-images.githubusercontent.com/38675/49575166-5a1fee80-f942-11e8-8506-a8c15c621db1.png)

**Comment by jbialobr** [comment] 2018-12-06 09:44
> Do you know which one?

@drewnoakes Isn't it related to scrollbars hiding, I think you did?

**Comment by spdr870** [comment] 2018-12-06 09:46
I didn't have the time to create a proper pr, but #5856 helps for me. I am going to run this in release for a while.

**Comment by jbialobr** [comment] 2018-12-06 10:12
@spdr870 Thank you! That fixes the problem.

**Comment by spdr870** [comment] 2018-12-06 10:15
@jbialobr I had to... I want v3 to ship...

**Comment by RussKie** [comment] 2018-12-06 10:20
> The changes has been introduced in this commit [9be4214](https://github.com/gitextensions/gitextensions/commit/9be4214e9a3f873e45acc0c64da4367305b9df04). The change itself seems like an optimalization that might caused this issue.

omg, this guy!

**Comment by spdr870** [comment] 2018-12-06 12:56
Fixed in #5857

**Closed by spdr870** 2018-12-06 12:56 UTC
Labels: status: ready, type: bug, type: regression
