### ISSUE TITLE
View Layout UI Bug with missing Dock Panel following Git Extension update.

### ISSUE THREAD

**Issue by brcaswell** [gitextensions/gitextensions#10963] opened 2023-05-15 14:43 UTC
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

I updated Git Extensions to latest version (from prompt) last week, after launching it -- it showed empty/missing panel on right side.

![image](https://github.com/gitextensions/gitextensions/assets/967010/7e8b0c3b-f46d-4765-9a7d-fa02e974460f)

---

Note: 
  - Couldn't determine if this was a new feature -- and some panel/window was not displaying. 
  - windows/panels/layouts are not in the 'View' nav menu. 

---

To clear, I eventually changed info panel to appear on right, then back to bottom.
![image](https://github.com/gitextensions/gitextensions/assets/967010/22df3669-5a25-4381-a062-ce95d8c05f6a)

### Steps to reproduce

I haven't attempted to reproduce, but I suppose it would be:

set 'Commit Info' graph to bottom in a previous version of Git Extensions.

Update Git Extensions using prompted dialog workflow,
Launch Git Extensions following update
observe whether an empty panel exist in Layout.

**Comment by mstv** [comment] 2023-05-15 17:22
Thank you for the details, particularly for the original state. 
Duplicate of https://github.com/gitextensions/gitextensions/issues/10959
You have found the workaround yourself.

**Closed** 2023-05-15 17:22 UTC
Labels: :eyeglasses: status: needs review

**Comment by RussKie** [comment] 2023-05-16 02:27
Added a known issue in https://github.com/gitextensions/gitextensions/discussions/10958.
