### ISSUE TITLE
Crash in 3.4 RC

### ISSUE THREAD

**Issue by NN---** [gitextensions/gitextensions#8098] opened 2020-05-12 13:38 UTC
Found crash dump.
Not sure how it is reproduced

```
System.InvalidOperationException: 'Invoke or BeginInvoke cannot be called on a control until the window handle has been created.'
```

![image](https://user-images.githubusercontent.com/580536/81698590-e6efa580-946e-11ea-9960-8e0ad9bd6fa3.png)

```
 	KERNELBASE.dll!_RaiseException@16()	Unknown
 	[Managed to Native Transition]	
 	System.Windows.Forms.dll!System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control caller, System.Delegate method, object[] args, bool synchronous)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.BeginInvoke(System.Delegate method, object[] args)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.WindowsFormsSynchronizationContext.Post(System.Threading.SendOrPostCallback d, object state)	Unknown
 	System.Reactive.dll!System.Reactive.Concurrency.SynchronizationContextExtensions.PostWithStartComplete(System.Threading.SynchronizationContext context, System.Action action) Line 49	C#
 	System.Reactive.dll!System.Reactive.Concurrency.SynchronizationContextScheduler.Schedule<(System.Action<System.Reactive.Disposables.SingleAssignmentDisposable>, System.Reactive.Disposables.SingleAssignmentDisposable)>((System.Action<System.Reactive.Disposables.SingleAssignmentDisposable>, System.Reactive.Disposables.SingleAssignmentDisposable) state, System.Func<System.Reactive.Concurrency.IScheduler, (System.Action<System.Reactive.Disposables.SingleAssignmentDisposable>, System.Reactive.Disposables.SingleAssignmentDisposable), System.IDisposable> action) Line 71	C#
 	System.Reactive.dll!System.Reactive.Concurrency.Scheduler.ScheduleAction<System.Reactive.Disposables.SingleAssignmentDisposable>(System.Reactive.Concurrency.IScheduler scheduler, System.Reactive.Disposables.SingleAssignmentDisposable state, System.Action<System.Reactive.Disposables.SingleAssignmentDisposable> action) Line 61	C#
 	System.Reactive.dll!System.Reactive.Linq.ObservableImpl.EventProducer<System.Windows.Forms.ContentsResizedEventHandler, System.Reactive.EventPattern<System.Windows.Forms.ContentsResizedEventArgs>>.Session.Connect.AnonymousMethod__5_0((System.Reactive.Linq.ObservableImpl.EventProducer<System.Windows.Forms.ContentsResizedEventHandler, System.Reactive.EventPattern<System.Windows.Forms.ContentsResizedEventArgs>>.Session, System.Reactive.Linq.ObservableImpl.EventProducer<System.Windows.Forms.ContentsResizedEventHandler, System.Reactive.EventPattern<System.Windows.Forms.ContentsResizedEventArgs>> _parent, System.IDisposable connection) tuple) Line 294	C#
 	System.Reactive.dll!System.Reactive.Disposables.AnonymousDisposable<(System.Reactive.Linq.ObservableImpl.EventProducer<System.Windows.Forms.ContentsResizedEventHandler, System.Reactive.EventPattern<System.Windows.Forms.ContentsResizedEventArgs>>.Session, System.Reactive.Linq.ObservableImpl.EventProducer<System.Windows.Forms.ContentsResizedEventHandler, System.Reactive.EventPattern<System.Windows.Forms.ContentsResizedEventArgs>>, System.IDisposable)>.Dispose() Line 73	C#
 	System.Reactive.dll!System.Reactive.Disposables.Disposable.TryDispose(ref System.IDisposable fieldRef) Line 238	C#
 	System.Reactive.dll!System.Reactive.Linq.ObservableImpl.Throttle<System.__Canon>._.Dispose(bool disposing) Line 53	C#
 	System.Reactive.dll!System.Reactive.Sink<System.Reactive.EventPattern<System.Windows.Forms.ContentsResizedEventArgs>>.Dispose() Line 31	C#
 	System.Reactive.dll!System.Reactive.Disposables.Disposable.TryDispose(ref System.IDisposable fieldRef) Line 238	C#
 	System.Reactive.dll!System.Reactive.ObserveOnObserverNew<System.Reactive.EventPattern<System.Windows.Forms.ContentsResizedEventArgs>>.Dispose(bool disposing) Line 424	C#
 	System.Reactive.dll!System.Reactive.Sink<System.Reactive.EventPattern<System.Windows.Forms.ContentsResizedEventArgs>>.Dispose() Line 31	C#
 	GitUI.dll!GitUI.CommitInfo.CommitInfoHeader.DisposeCustomResources() Line 156	C#
>	GitUI.dll!GitUI.GitModuleControl.Dispose(bool disposing) Line 132	C#
 	GitUI.dll!GitUI.CommitInfo.CommitInfoHeader.Dispose(bool disposing) Line 21	C#
 	System.dll!System.ComponentModel.Component.~Component() Line 35	C#
 	[Native to Managed Transition]	
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown
 	ntdll.dll!__RtlUserThreadStart()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown
```

## Environment

- GitExtensions version: 3.04.9381
- GIT version: git version 2.26.0.windows.1
- OS version: Windows 10
- .NET version: 4.8

**Comment by RussKie** [comment] 2020-05-13 11:46
Duplicate of #8096

**Closed by RussKie** 2020-05-13 11:46 UTC
