### ISSUE TITLE
[NBug] Exception `Value must not be null.` occurs when creating a branch.

### ISSUE THREAD

**Issue by ksuzuki-rits** [gitextensions/gitextensions#11800] opened 2024-07-05 05:19 UTC
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.42.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.28
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

When I try to create a branch, I get the NBug bug report window.
The exception I get is this:

```
System.Exception: Value must not be null.
   at void Microsoft.Validates.Fail(string message) in C:/projects/gitextensions/GitExtUtils/Validates.cs:line 35
   at async void GitUI.UserControls.CommitPickerSmallControl.SetSelectedCommitHash(string commitHash)+(?) => { } in C:/projects/gitextensions/GitUI/UserControls/CommitPickerSmallControl.cs:line 59
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

### Steps to reproduce

1) Prepare an empty directory and initialize the repository with the `git init` command

2) Open the directory from step 1 with GitExtensions

3) Use the GitExtensions function to set the remote repository (origin)

4) Create a branch using the GitExtensions function (Ctrl+B) -> crash occurs

If skip step 3, there will be no crash even if do 4.

In a directory where steps 1 to 3 have been performed, a crash will occur no matter how many times do 4.

### Did this work in previous version of GitExtensions?

I haven't tried it.

**Comment by gerhardol** [comment] 2024-07-05 21:30
Duplicate of #11609 
Fixed in #11610

**Closed by gerhardol** 2024-07-05 21:30 UTC
Labels: :eyeglasses: status: needs review
