### ISSUE TITLE
file history will highlight wrong revision

### ISSUE THREAD

**Issue by kimitop** [gitextensions/gitextensions#4440] opened 2018-02-07 08:47 UTC
There are two branch to modify 1 file and merged. then double click the file in file history. 
file history will highlight wrong revision.
git log -1 --filename,the result is different from highlighted revision.
highlighted revision seems the latest commit.
- GitExtensions version: 2.50.02
- GIT version: 1.9.5
- OS version: WIN7

**Comment by RussKie** [comment] 2018-02-07 10:18
Please provide steps to reproduce and/or screenshots.
Also the latest version is 2.51

**Comment by RussKie** [comment] 2018-02-08 21:32
Also please update git to the current version.
At least to 2.15

**Comment by RussKie** [comment] 2018-03-10 12:03
Closing due to lack of follow up

**Closed by RussKie** 2018-03-10 12:03 UTC
Labels: info needed

**Comment by qianyilan** [comment] 2018-03-15 03:09
i met the same bug too, modified '1.txt' in two different branches,and then merged them.

![image 1](https://user-images.githubusercontent.com/26076536/37442292-70f85fd0-2840-11e8-9a8d-93d1d6792272.jpeg)

when double click the file in file history,file history will highlight wrong revision.

![image](https://user-images.githubusercontent.com/26076536/37442404-204aa09c-2841-11e8-8ba3-a3ba44d49cfb.jpeg)

git log -1 --filename,the result is different from highlighted revision.

![image 2](https://user-images.githubusercontent.com/26076536/37442424-3dbbed20-2841-11e8-8e14-f33af978fd20.jpeg)

GitExtensions version: 2.51
GIT version: 2.13.2
OS version: WIN7
