### ISSUE TITLE
FormCommit: Overlapping labels if file list is empty

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6827] opened 2019-06-19 22:27 UTC
## Current behaviour

The label "There are no unstaged changes" does not cover the label "Filter files using a regular expression..." completely:

![grafik](https://user-images.githubusercontent.com/36601201/59805390-750bec00-92f1-11e9-8173-d56a86353d24.png)

## Expected behaviour

"Filter files using a regular expression..." not visible if there is no unstaged file.

## Steps to reproduce

Open FormCommit without modified files or stage them all.

## Did this work in previous version of GitExtensions

3.1.0.5627

## Environment

- Git Extensions 3.2.0
- Build e7688f6fd82614979d964cf69233b951ad521970
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2019-06-21 12:27
Duplicate of #6532

**Closed by RussKie** 2019-06-21 12:27 UTC
Labels: status: reproducible
