### ISSUE TITLE
bug: commit message line character limit moves

### ISSUE THREAD

**Issue by Holo-Viktor** [gitextensions/gitextensions#8970] opened 2021-03-11 10:57 UTC
## Current behaviour

![11BDSw2eYo](https://user-images.githubusercontent.com/43336921/110775858-b2e83b00-825f-11eb-9be3-0f07a4665c14.gif)

## Expected behaviour
colored text stays at the set character limit

## Steps to reproduce

* open the commit validation settings from the commit dialog
* enable "Maximum number of characters in first line" by setting any value other than 0
* enable "Maximum number of characters per line" by setting any value other than 0
* type a commit message until you reach set limit
* click anywhere in the line
* type some more
* see colored text (the limit) to move right
* this behavior applies to all lines (both settings are affected)

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.2.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

**Comment by bansan85** [comment] 2021-03-13 09:13
I was able to reproduce it. I tried to debug it (function FormatAllText in FormCommit.cs) and now, I can't reproduce it anymore...

Note: before this bug vanished, I noticed that the bug does not appears if you write character one by one. It appears here because he pressed one touch and keep it pressed.

**Comment by Holo-Viktor** [comment] 2021-03-13 13:47
why is FormatAllText called recursively?

**Comment by bansan85** [comment] 2021-03-13 14:58
@Holo-Viktor no idea. I just quote FormatAllText because it's probably this function that fails but I didn't fully understand it.

**Comment by RussKie** [comment] 2021-03-14 07:03
Looks like it was changed 8 years ago in https://github.com/gitextensions/gitextensions/commit/01585f940ade0f243f99bc4b1e5d5aa3ef83a8d5
@jbialobr can you recall the reasons why you made it recursive?

**Comment by bansan85** [comment] 2021-03-14 21:24
The function `FormatAllText` in `FormCommit.cs` looks redundant with `MarkLines` in `EditNetSpell.cs` ?
One change color in red, the other change background color in yellow but they both do the same.

Do you think these two functions should be merged in flavor of `MarkLines` (simpler function and don't have "selection text" glitch to change color) ?

**Comment by jbialobr** [comment] 2021-03-15 06:04
>@jbialobr can you recall the reasons why you made it recursive?

It was recursive from the begining https://github.com/gitextensions/gitextensions/blob/948c2319b5ab7f532c991f7753e8fa034dd4831e/GitUI/FormCommit.cs#L1790
I just tried to optimize it to not reformat all the llines in case of a changede line. Now I see there is a missing `return`  in the `if` body. Of course it does not have to be recursive - it is enough to recompute the loop's stop condition after each iteration.

**Comment by jbialobr** [comment] 2021-03-15 06:11
>Do you think these two functions should be merged in flavor of MarkLines (simpler function and don't have "selection text" glitch to change color) ?

`FormatAllText` - inserts line breaks if necessary while `MarkLines` does not.
`MarkLines` looks like missplaced. It should be located in FormComit IMO, because EditNetSpell is a general purpose control and should know nothing about formatig commit messages.

**Comment by Holo-Viktor** [comment] 2021-03-16 13:48
I would definitely prefer a version which doesn't insert line breaks or at least the option to turn it off, marking & maybe a warning popup (also with an option to disable) would be neat

**Comment by Holo-Viktor** [comment] 2021-03-16 13:52
it also looks like enforcing the 50/70 rule is implemented separately, which could be merged with this, having 50/70 as the default values for settings "Maximum number of characters in first line" & "Maximum number of characters per line"

**Comment by Holo-Viktor** [comment] 2021-03-16 13:59
A potentially related issue #8969

**Closed** 2024-10-12 03:10 UTC
Labels: type: bug :bug:
