### ISSUE TITLE
Very slow ui on Windows 7

### ISSUE THREAD

**Issue by primgate** [gitextensions/gitextensions#2438] opened 2014-09-01 08:56 UTC
I am using GitExtensions V2.48 on Windows 7 Enterprise 64bit.

Git version 1.8.5.5(Tried git 1.9.4)

Cygwin 32 bit.

The UI of the application seems to hang on every action I take while using it. Sometimes it freezes for 10-15 seconds, and then it works for 1-2 seconds and then on another click following that time, it freezes again.

There is no network IO hogging the threads, the computer is using and SSD drive. Running the git commands on the console, they execute almost instantly. I have tried to clean the repositories, recreate them, create others from github, using random OS projects, the problem still persists.

I have tried to install Windows upgrades to the latest one and also reinstalled .NET Framework.

I have tried different versions of GitExtensions, different git versions, different shells(cygwin/msysgit). On similar machines and networking configuration, GitExtensions works fine on the machines of my coworkers.

**Comment by distinctdan** [comment] 2015-02-02 15:20
+1 on this one.

Takes around 1 min to update the main view after doing anything that adds/changes a commit. The repo has a couple thousand commits, and I'm running a decent i7 with 8Gb of ram, however, it's not eating cpu or ram while it's spinning. Gitextensions is version 2.48.03.

**Comment by laplantb** [comment] 2015-02-23 17:05
+1

**Comment by alxbrd** [comment] 2015-02-23 20:39
I found this to be because of a certain version of Git installed through either cygwin or chocolatey. On the same machine after reinstalling the OS it worked fine. So if you guys could post some details about git versions and configs maybe we can find a pattern.

**Comment by distinctdan** [comment] 2015-02-24 14:44
Hmm, could be. When I run "git --version", I get 1.9.5.msysgit.0. I installed it through the .msi installer off of the git website.

**Comment by distinctdan** [comment] 2015-02-24 19:28
You know, in fairness to git extensions, I really think this is just a git on windows problem. When I use git through the command line shell, it's just as slow. It may also be aggravated by me having visual studio running in the background.

**Comment by laplantb** [comment] 2015-02-24 22:28
I'm using 1.9.4.msysgit .2 and putty for ssh.

**Comment by distinctdan** [comment] 2015-03-26 16:37
Found the cause of my slowness and thought I'd share: I had some troubles with Comodo antivirus and uninstalled it, after which git extensions returned to being lighting fast.

**Comment by sergei-kalashnikov** [comment] 2015-07-20 10:21
Had the same issue. Stopping Avast monitor worked for me

**Comment by arenaq** [comment] 2015-09-02 07:40
Had the same issue (version 2.48). Upgrade to 2.48.5 is working for me so far.

**Comment by MLourensMoog** [comment] 2015-10-01 09:13
I have the same issue, with McAffee running. SmartGit and SourceTree don't seem to have this problem on my system, so it's not git on Windows related.

**Comment by MarcoWilliamsPF** [comment] 2016-04-01 17:04
@sergei-kalashnikov  this was exactly my issue,  I had to make an exclusion rule in Avast to not scan Git or GitExtensions  when  Reading, Writing & Executing.

The result was Instant, and now GitExtensions is lightning fast.

Here are the steps that I took to exclude for Avast.

-  Right Click Avast Tray Icon and click Open Avast User Interface
-  Click the Settings Cog in the top right Corner
-  Click on Active Protection 
-  Click on Customize under the File System Shield
-  Click on Exclusions from the left side menu bar
-  Click Add, and browse to include both the  Git folder & Git Extensions folder  under the Program Files(x86) ..  Example: C:\Program Files (x86)\GitExtensions\*  & C:\Program Files (x86)\Git\*
- Click Okay, 
- Click Okay

**Comment by neal1991** [comment] 2017-03-31 05:08
+1
I have not installed avast. When I open the git extension, the cpu will quickly increases almost to 100%.  The version is 2.48.05, and the OS is windows 7 64 bit professional.

**Comment by arenaq** [comment] 2017-03-31 06:57
Is there a progress on this?

I can confirm that its not happening on my new machine. Difference from previous computer: PC instead of laptop, Win 10, SSD, much stronger CPU (3x).

**Comment by ghanique** [comment] 2017-03-31 17:45
Some virus scanners can be the bottleneck. Try to disable it and check if
it makes a difference.

**Comment by RussKie** [comment] 2017-08-22 14:23
From the reports it doesn't seem to be the GE-specific issue.
Closing due to age.

**Closed by RussKie** 2017-08-22 14:23 UTC
Labels: needs-review

**Comment by arenaq** [comment] 2017-09-12 10:19
@MarcoWilliamsPF I found out this is caused by Avast's Behavioral Shield. I tried to place an exception for folders you mentioned, but it doesn't help. I even tried the whole partition, no luck. When I turn the shield down, the problem is gone :) any ideas?
