### ISSUE TITLE
Amend Commit doesn't ask to stage changes, if none staged.

### ISSUE THREAD

**Issue by jamesli3397** [gitextensions/gitextensions#4522] opened 2018-02-24 12:00 UTC
**Do you want to request a *feature* or report a *bug*?**
Behavior inconsistency.

**What is the current behavior?**
If you try committing without staging files, you get the dialog "There are no files staged for this commit. Stage and commit all unstaged files?".

If you try amending a commit without staging files, you get the dialog "You are about to rewrite history.
Only use amend if the commit is not published yet! \n Do you want to continue?". The "stage all files" dialog doesn't show up at all.

I was confused when I tried amending commits, assuming they would be automatically staged and committed, but nothing happened no matter how many times I tried. I assumed this was a bug.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
The "stage all files" dialog appears, or is automatically performed when amending.

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: git version 2.14.1.windows.1
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Not sure.

**Comment by pmiossec** [comment] 2018-02-24 12:20
>I assumed this was a bug.

I think it's not one.

The alert when you commit is a convenient one because we could be pretty sure that if there is no files staged, the user forgot to add them.

 But in the case of an amend, you can't be sure because the user could only have changed the commit message and don't want to add other changes. We can't always bother him with 2 alert messages (that are also boring to read when you know what you are doing) for something that is perfectly normal...

**Comment by jamesli3397** [comment] 2018-02-25 00:33
I think that omitting/clicking through the "amend warning" dialog is consistent with non-amends, while omitting the "stage and commit" dialog is inconsistent with skipping the dialog.

Is there an option to "always stage and commit if nothing staged"? It would be convenient.

**Comment by drewnoakes** [comment] 2018-06-18 19:22
I don't feel like this is a bug or that there is any action to take here. Can we close this?

**Comment by jamesli3397** [comment] 2018-06-18 19:23
at least you should warn if you and without committing files or changing
the commit name.

On Jun 18, 2018 12:22 PM, "Drew Noakes" <notifications@github.com> wrote:

I don't feel like this is a bug or that there is any action to take here.
Can we close this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/4522#issuecomment-398166459>,
or mute the thread

**Comment by drewnoakes** [comment] 2018-06-18 19:28
`git commit --amend` doesn't give any warning if you don't change the message.

However it does prohibit you from making an empty commit (unless you override with `--allow-empty`).

**Comment by NN---** [comment] 2019-07-11 11:18
Amend commit without staging doesn't commit anything but asks whether you want to stage.
For me this sounds as a bug.
GE should either not support such scenario or do it right.

**Comment by RussKie** [comment] 2019-07-11 13:11
@NN what version of GE are you running?

**Comment by NN---** [comment] 2019-07-11 13:13
- Git Extensions 3.2.0.6171
- Build de3fbd5d59b0329e56d419f32a5a33322e3688bb (Dirty)
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 96dpi (no scaling)

**Comment by NN---** [comment] 2019-07-11 13:19
Installed 3.1.1.6049
When I press 'commit' with 'Amend Commit' selected without staging, GE asks to commit all, then opens log window and in the end does nothing.

**Comment by RussKie** [comment] 2019-07-11 13:23
I have no dramas with amending a previous commit without staging any files and then pushing the update.
Please provide a test repo and steps to reproduce.

**Comment by NN---** [comment] 2019-07-11 14:10
Do you think it is repository related?
I'll try with the GE repo and tell whether it works.

**Comment by mstv** [comment] 2019-07-11 21:26
That's a feature: I use it for rewording commits.
If you forgot files, you can amend again.

**Comment by gusarov** [comment] 2020-07-09 17:10
But the thing is - we are triggering this from GitExtensions and this one can see that Staging is empty while Working is not. In case of Commit there is a small confirmation to stage all and done, we are good. But in case of Amend - there is nothing happens, windows closes successfully. You can only notice that something went wrong if you notice that Working directory still have some files. I'm facing this issue almost every day now, decided to create a bug here, but found that this one is already created. I would consider making pretty UX no matter what instead of relying on warnings that git outputs.

**Comment by pmiossec** [comment] 2020-07-09 17:23
Amending a commit to update just the commit message is a normal workflow.

Should we annoy those that use the software well with a new message box? I personally don't share this point of view... 

Some proposition :
* add a new setting to enable the message (but not by default)
* find another very visible but not blocking way to warn the user as soon as the option is checked. I let you find a creative way to do it ( warning sign and tool tip just next the commit button, warning in the stage file list,...)

And after the consensus reached, do a PR 😉

**Comment by vbjay** [comment] 2020-07-09 18:28
Correct. An amend can just be a reword commit.

**Comment by mstv** [comment] 2020-07-09 20:36
A volunteer could implement such a warning for `amend` with unstaged file(s) using a TaskDialog with a checkbox "Do not show in the future".

BTW: The commit dialog has an option to not close if there are uncommitted files:

![grafik](https://user-images.githubusercontent.com/36601201/87088092-7974b100-c234-11ea-87b8-129c14cde0d4.png)

**Comment by RussKie** [comment] 2020-07-10 10:39
The current behaviour is by design. 

We will not be adding any prompts to stage because these will be disruptive and annoying. 
We can however consider proposals that make users aware of the fact nothing is staged. 
**Before doing any implementation start with mock ups that show the UI and UX.**

**Comment by gusarov** [comment] 2020-07-21 13:08
Ok good... but what if the user did not changed the commit message? So, no staging, some unstaged, checking "amend" - commit message is filled from previous commit automatically and it remains the same, user have not changed it. Guess what? The window will be closed upon clicking 'commit' button. Nothing will happen.
Those who use this dialog for amending the message will not be annoyed if the warning is displayed only when message is not changed.

**Comment by vbjay** [comment] 2020-07-21 22:04
Wrong. The time is a other variable. It will create a new commit. Do it and
look at the Sha.

**Comment by pmiossec** [comment] 2020-07-21 23:09
@vbjay You're right, that will create a new commit with nothing changed except the dates (and eventually the commiter).
But that don't make impossible to do what @gusarov ask i.e. verify if the commit message is the same and nothing is added to the staging area, it is possible to add a control and display a message like "nothing changed, did you forgot to do something?"

**Comment by RussKie** [comment] 2020-07-24 02:13
> verify if the commit message is the same and nothing is added to the staging area, it is possible to add a control and display a message like "nothing changed, did you forgot to do something?"

I suppose we could entertain this is a valid use case for displaying a warning. 

...or should `Commit` and `Commit & push` buttons be disabled by default, and enabled only if the state changes, i.e. 
1. there's a commit message + staged files, or 
2. "amend" is ticked and either a commit message is changed or files staged.

**Comment by drewnoakes** [comment] 2020-07-24 10:41
Let me play devil's advocate here, just to make sure this idea stands up.

This would need to be based off the repo state, not the UI state. Consider:

1. Open FormCommit, with nothing staged
2. Type a commit message
3. Close FormCommit
4. Open FormCommit (message from step 2 still there)
5. Check "amend"
6. Commit must not be blocked, even though message is unchanged in the UI

On large repos querying the last commit message would introduce latency to the opening of the form (when amend is pre-selected), and reduce the UI responsiveness when checking the "amend" box. It could be async, but then there's a race condition, and the UI is not consistent/flickers.

Personally while I don't think adding this restriction is harmful, I don't know that it's useful. There's little harm in letting the user take a no-op action. There may be valid use cases that haven't been considered here. For example, imagine I change my GPG settings and want to amend the signature of the last commit without changing the message.

---

The original problem here was lack of visibility into what "amend" actually does, namely that it works without having to stage additional files. There are other ways to show the user that amend is fundamentally different:

- Show the previous commit's items in a third file list, readonly
- Merge the previous commits items in the stages file list, and allow them to be unstaged (a Git client I used on Linux does this, though I can't remember which one. It was a great feature.)

**Comment by gerhardol** [comment] 2020-07-24 11:47
There is a use case for amend commit without without changes for neither files nor the message; to get a new commit to retrigger server builds.
If there is a popup, just check if there are no changes at all for simplicity. It should be off by default, there are too many checks already.
(I get complaints that there are too many popups in GE even if it is just to tick a checkbox.)

Instead of amend showing the previous commit, a new button could populate the commit and message (i.e. a reset).

**Closed** 2021-04-27 14:32 UTC
Labels: :neckbeard: status: pull request only, type: discussion
