### ISSUE TITLE
Two console tabs if UI is not english

### ISSUE THREAD

**Issue by deathaxe** [gitextensions/gitextensions#5916] opened 2018-12-15 11:08 UTC
**What is the current behavior?**

GitExtensions displays a "Console" tab next to the "Konsole" tab if the UI language is set to German. "Konsole" is empty while the real conemu is displayed under "Console"

![grafik](https://user-images.githubusercontent.com/16542113/50042327-e11b4800-0061-11e9-9918-8a89f79ecae0.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Set UI language to German
2. Restart GitExtensions
3. Start working with a repos

**What is the expected behavior?**

Only one "Konsole" tab.

**Environment you encounter the issue:**

- GitExtensions version: 3.0.0
- GIT version: 2.20
- OS version: Win10 x64 1803
- .NET version: 4.7.2

**Did this work in previous version of GitExtensions (which)?**

2.51

**Comment by gerhardol** [comment] 2018-12-15 13:03
Cannot reproduce
![image](https://user-images.githubusercontent.com/6248932/50043322-1fb8fe80-0072-11e9-9365-903e33041f56.png)

**Comment by drewnoakes** [comment] 2018-12-15 16:45
@deathaxe are you using the option that shows the commit info tab elsewhere? Do the rest of your tabs look the same as @gerhardol's?

**Comment by gerhardol** [comment] 2018-12-15 16:57
Can reproduce if showing the Commit in the revision graph

**Comment by drewnoakes** [comment] 2018-12-15 17:35
Thanks for verifying @gerhardol. Doesn't happen for me in English language.

This code looks interesting:

https://github.com/gitextensions/gitextensions/blob/3c2ac977b342f925f740a74957a5570afc58a20d/GitUI/CommandsDialogs/FormBrowse.cs#L2745-L2759

`_consoleTabCaption` is a `TranslationString`. The code might be deciding `tabPageCreated` is `false` and then creating a second console (with the English name?). Is it possible that the translation string changes its value over time? This doesn't directly explain why it would be related to Commit Info position.

**Comment by mstv** [comment] 2018-12-15 17:53
I guess there must be some timing issue in FormBrowse. Maybe `FillTerminalTab()` is called by the constructor before the translations are loaded. This creates a not yet translated tab "Console" using the field `TranslationString _consoleTabCaption`. Later, e.g. by the hotkey command `FocusGitConsole`, the translated text from this field is used. I don't know when and how the translations are loaded.

**Comment by deathaxe** [comment] 2018-12-15 17:53
The tabs normally look the same way as @gerhardol's screenshot shows. This is the normal state after opening a repo. At some point the "Konsole" tab is created, while working at the repo. Just retried to reproduce, but haven't been able to find the trigger for the tab to be created. 

My feeling says, there is a translated text being used to identify the tab at some point while an untranslated one is used normally.

**Comment by deathaxe** [comment] 2018-12-15 17:55
In general I'd expect the tab's caption to be translated as the others are as well. Hence "Konsole" would be the correct caption in german language.

**Comment by deathaxe** [comment] 2018-12-15 20:16
It seems to be triggered by interactive rebase operations at some point. After heavy git activity the second tab suddenly appears without me even to navigate to the console tab at all.

![grafik](https://user-images.githubusercontent.com/16542113/50047049-9f64be80-00ae-11e9-9bdb-3b3403f1acc6.png)

**Comment by RussKie** [comment] 2018-12-17 05:48
One of the first questions here - why your "Console" tab isn't in German to start with. I think once it is fixed, everything else will fall in place

**Comment by drewnoakes** [comment] 2018-12-19 09:19
I believe this to be fixed by #5951.

**Closed** 2018-12-20 10:00 UTC
Labels: status: ready, type: bug
