### ISSUE TITLE
[NBug] Not Found

### ISSUE THREAD

**Issue by neelamtopno-tal** [gitextensions/gitextensions#9431] opened 2021-08-02 06:17 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.Exception: Not Found
   at Git.hub.Client.DoRequest[T](IRestRequest request, Boolean throwOnError)
   at Git.hub.Client.getRepository(String username, String repositoryName)
   at GitHub3.GitHubHostedRemote.GetHostedRepository()
   at GitUI.CommandsDialogs.RepoHosting.CreatePullRequestForm.<>c__DisplayClass21_0.<<PopulateBranchesComboAndEnableCreateButton>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
while creating a Pull request not able to see the source branch and target branch

## Environment
- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.22.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4250.0
- DPI 144dpi (150% scaling)

**Comment by gerhardol** [comment] 2021-08-12 17:37
Duplicate of #9147

**Closed by gerhardol** 2021-08-12 17:37 UTC
Labels: potential-duplicate
