### ISSUE TITLE
Initial screen is blank on Linux

### ISSUE THREAD

**Issue by DiThi** [gitextensions/gitextensions#3912] opened 2017-08-17 11:36 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Initial screen is blank on Linux. Everything else seems to work fine.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open Git extensions on Linux.
![image](https://user-images.githubusercontent.com/1127198/29410460-d1ca2efa-8350-11e7-9fe7-a56ede0f9966.png)

**What is the expected behavior?**
To show my recent repositories (there's many) and links for opening existing repo, etc.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.01
- GIT version: 2.7.4
- OS version: Ubuntu 16.04 64 bit, Mono 4.6.2

**Did this work in previous version of GitExtensions (which)?**
Worked fine with 2.49, same Mono version.

**Comment by RussKie** [comment] 2017-08-17 11:47
Duplicate of #3725

**Closed by RussKie** 2017-08-17 11:47 UTC
Labels: linux/mono
