### ISSUE TITLE
File history popup causes exception on closing window

### ISSUE THREAD

**Issue by SergiiGalai** [gitextensions/gitextensions#7432] opened 2019-11-20 10:07 UTC
## Current behaviour
Exception occurred on closing file history window. Reproducible in File explorer as well as Total commander. 

## Expected behaviour
No exception window on file history window closing

## Steps to reproduce

1. Right click on some file under git and choose File History
2. Close opened history window
3. Observe popup with exception

## Screenshots

![image](https://user-images.githubusercontent.com/5754796/69229096-75086480-0b8d-11ea-8258-40c8581ba5c6.png)

![image](https://user-images.githubusercontent.com/5754796/69229203-b1d45b80-0b8d-11ea-8aa0-ab51e6e89376.png)

![image](https://user-images.githubusercontent.com/5754796/69229336-ed6f2580-0b8d-11ea-9cf3-8f7c47bafcae.png)

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

## Diagnostics
I have tried to debug and got this from Visual Studio
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
  Source=System.Windows.Forms
  StackTrace:
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Post(SendOrPostCallback d, Object state)
   at System.Reactive.Concurrency.SynchronizationContextScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Linq.ObservableImpl.EventProducer`2.Session.<>c__DisplayClass5_0.<Connect>b__0()
   at System.Reactive.Disposables.AnonymousDisposable.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.ObserveOnObserver`1.Dispose(Boolean disposing)
   at System.Reactive.ObserverBase`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at GitUI.CommitInfo.CommitInfoHeader.DisposeCustomResources()
   at GitUI.GitModuleControl.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Finalize()
```

**Comment by pmiossec** [comment] 2019-11-20 10:15
Duplicate of #7385.
It should already fixed in the development version.

Could you please test the development [portable version](https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts) and tell us if the fix works for you?

**Closed** 2019-11-20 10:15 UTC
