### ISSUE TITLE
New GE instance with filehistory no longer displays history

### ISSUE THREAD

**Issue by robin-o** [gitextensions/gitextensions#10626] opened 2023-01-10 00:20 UTC
### Environment

- Git Extensions 4.0.1.15887
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0 (Windows 10 21H2)
- .NET 6.0.12

### Issue description

Running "GitExtensions.exe filehistory path/to/filename.ext" does not load the history of the given file. Hitting "H" within a running instance of GitExtensions _does_ work. Comparing the two instances I noticed that under View > Advanced filter, the Path filter in the non-working instance had the path enclosed in `\"` symbols. Removing these quotes fixed the issue until the next time. I suspect that this is related to the `QuoteNE()` calls added in PR #10303.
Reverting to the previous version of GE (Git Extensions 4.0.0.15569) resolved the issue, which corresponds with the above commit.

### Steps to reproduce

From a command line, run `GitExtensions.exe filehistory path/to/filename.ext`. Alternativey, in Windows Explorer, choose `File history` from the Git Extensions context menu.

### Did this work in previous version of GitExtensions?

Yes, Git Extensions 4.0.0.15569

**Comment by gerhardol** [comment] 2023-01-10 07:08
Duplicate of #10537
Fixed in #10546, included in upcoming 4.0.2

**Closed by gerhardol** 2023-01-10 07:08 UTC
Labels: :eyeglasses: status: needs review
