### ISSUE TITLE
Add "Squash" as a Command

### ISSUE THREAD

**Issue by BUInvent** [gitextensions/gitextensions#4378] opened 2018-01-19 20:44 UTC
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
There is currently no "squash" command.

**What is the expected behavior?**
Under "Commands" in the UI there would be an option to "Squash". After clicking it, a window would popup saying:
Squash the last: "6" commits
commit message: "added a button"

It would then run a command much like this:
git reset --soft HEAD~6 && git commit -m "added a button"

**Comment by vbjay** [comment] 2018-01-19 20:48
Recommend closing.  See #3376

**Comment by vbjay** [comment] 2018-01-19 20:55
Squash does not = git reset --soft HEAD~6 && git commit -m "added a button"

Squash = one of two methods.  

1.  Right click commit and ![image](https://user-images.githubusercontent.com/3629489/35171106-9348f0b2-fd30-11e7-8f08-6c0b1655b9c3.png)  Repeat as needed.  Do a rebase with autosquash 1 commit down from where you want the rebased commits to be written. 
2.   Right click commit one commit bellow the list of commits you want rebased.  Tell it to rebase on (pick menu option).  Check interactive rebase and optionally autostash.    Alter file in editor that shows marking commits to be squashed or other actions.  Close the editor and save.

Watch rebase run.

**Comment by BUInvent** [comment] 2018-01-19 21:51
It just seems like too many steps to remember. As someone who likes to smash (we'll call it smash since I guess it is technically not "squashing") my last X commits a lot, I think my solution would b e a lot cooler. however, I digress. I am assuming you know much more about this than I do.

**Comment by vbjay** [comment] 2018-01-19 21:56
It's by design.  This prevents people from messing up.  They have to actually go through the rebase process to actually rewrite.

**Comment by BUInvent** [comment] 2018-01-19 22:00
I think a better way to do it is to right click the commit right below the last one you want and do git rebase soft then commit all your changes.

**Comment by BUInvent** [comment] 2018-01-19 22:01
Sorry, I mean right click that commit , then "reset current branch to here", then select soft reset. then commit

**Closed** 2018-01-19 22:04 UTC

**Comment by vbjay** [comment] 2018-01-19 22:17
The issue is you may not want the end commits to be squashed.  

You may want "new work" to go into "Done with work"

![image](https://user-images.githubusercontent.com/3629489/35174218-8f9036f4-fd3c-11e7-9fcf-b024b440b00b.png)

**Comment by BUInvent** [comment] 2018-01-19 22:18
gotya

**Comment by RussKie** [comment] 2018-01-20 04:34
When I squash - I click on a target commit, do **mixed** reset and commit. This way you smash all the commits together.
I'm not sure why you doing soft reset...
