### ISSUE TITLE
[NBug] 'C:\Program Files\Git\bin\git.exe config --includes --get user.name' returned non-zero exit code.

### ISSUE THREAD

**Issue by dsplaisted** [gitextensions/gitextensions#11392] opened 2023-11-25 18:52 UTC
### Environment

- Git Extensions 4.2.0.17591
- Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.25
- DPI 240dpi (250% scaling)
- Portable: False

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: config --includes --get user.name
Working directory: c:\git\HandbellHero.App\

```
GitExtUtils.ExternalOperationException: External program returned non-zero exit code.
 ---> System.Exception: External program returned non-zero exit code.
   --- End of inner exception stack trace ---
   at async Task<string> GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 129
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTask<T>.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<T>(Func<Task<T>> asyncMethod, JoinableTaskCreationOptions creationOptions) x 2
   at string GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 43
   at string GitCommands.GitModule.GetEffectiveGitSetting(string setting, bool cache) in C:/projects/gitextensions/GitCommands/Git/GitModule.cs:line 2421
   at async void GitUI.CommandsDialogs.FormCommit.UpdateAuthorInfo()+(?) => { } in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCommit.cs:line 2726
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

### Steps to reproduce

Go to commit dialog without setting up a user name / email in git config.

### Did this work in previous version of GitExtensions?

In some earlier versions, it would not crash when you brought up the commit dialog.  If you tried to commit it would give an error saying you needed to set up a username and email address.

**Comment by gerhardol** [comment] 2023-11-25 19:05
Duplicate of #11366 
Just set email/name - you cannot commit anyway
Changed in #11369 (you get the Git error when committing)

**Closed by gerhardol** 2023-11-25 19:05 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate

**Comment by sharwell** [comment] 2023-12-20 20:53
Duplicate of #11364
