### ISSUE TITLE
save selected as... - breaks files, 100%

### ISSUE THREAD

**Issue by denis-art-hg** [gitextensions/gitextensions#12041] opened 2024-11-14 14:17 UTC
### Issue description

I've been facing this problem for a long time, everything was fine in earlier versions.
This happens 100% of the time with all file types except scripts.
We have to use other Git clients for these measures.

### Steps to reproduce

Diff -> Save selected as...-> select file (.prefab, .png,..) -> Save -> file (broken)

### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.2.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

### Did this work in previous version of GitExtensions?

a few versions ago, in 2023 it is possible

**Comment by mstv** [comment] 2024-11-14 20:50
`Save selected as...` (Diff tab) and `Save as` (Form Diff) work well for me with code files and images in the GE repo.
Can you share an example repo?
Do you use Git LFS?
What does broken mean? I.e. what is the difference / the contents?

**Comment by denis-art-hg** [comment] 2024-11-15 00:39
I'm sorry, I clarified it. 
the file is not broken, it is empty, i.e. it contains 130 bytes of detailed text regardless of the file :
version https://git-lfs.github.com/spec/v1
oid sha256:292008bd578be6c66b3822ab89d172d95cf9df37e198ff47c85514c24d8516c4
size 34727

any repository.
the file size does not matter, for example, only 30 K. In this case.

**Comment by denis-art-hg** [comment] 2024-11-15 00:44
that is, for example, fork saves the file normally )
But I like him less.

I was hoping that they would fix it, but they haven't fixed it for a long time.
such a function is not often needed, therefore it is tolerable.

**Comment by gerhardol** [comment] 2024-11-15 09:54
> Hi! I'm sorry, I clarified it. the file is not broken, it is empty, i.e. it contains 130 bytes of detailed text regardless of the file : version https://git-lfs.github.com/spec/v1 oid sha256:292008bd578be6c66b3822ab89d172d95cf9df37e198ff47c85514c24d8516c4 size 34727
> 
> any repository. the file size does not matter, for example, only 30 K. In this case.

So this is LFS, that has never been implemented. 
There was a PR in https://github.com/gitextensions/gitextensions/pull/6189 but it is not obvious how to find how a file is handled by lfs in a specific commit.

**Comment by pmiossec** [comment] 2024-11-15 11:16
> I've been facing this problem for a long time, everything was fine in earlier versions.

> ### Did this work in previous version of GitExtensions?
> a few versions ago, in 2023 it is possible

> any repository.
> the file size does not matter, for example, only 30 K. In this case.

To sum up, it is due to git lfs feature that you use and it has never been supported by GitExtensions.

I would like to add that I hope that maybe your use case is only to save the type of files that are tracked by git-lfs  (that normally should only be binaries or big files) but if it's not the case, maybe git-lfs filters are not well configured in the repositories you use and git-lfs is handling too many files (all!?!).

Closing as duplicate of #6146.
We can reopen if you think it's not the same case ( in this case, update title and description to add more information).

**Closed by pmiossec** 2024-11-15 11:16 UTC
Labels: :mailbox_with_no_mail: needs: author feedback

**Comment by denis-art-hg** [comment] 2024-11-15 22:45
I highlighted it, you can leave it )
But the problem remains. It doesn't matter how different the repository is or filter.
Other clients save without problems. (TortoiseGit, Fork)

**Comment by mstv** [comment] 2024-11-15 22:58
Workaround until someone finds the appropriate git command which automatically applies the LFS filter:

If you just want to restore a previous revision, you could "reset" the file:

![Image](https://github.com/user-attachments/assets/57d9e686-9e50-4dc1-b3ca-529010e59bd1)

**Comment by denis-art-hg** [comment] 2024-11-16 00:08
Apparently, I somehow didn't pay attention, but, yes, this method works normally. 
Thank You @mstv )
