### ISSUE TITLE
Issues with High-DPI scaling [$15]

### ISSUE THREAD

**Issue by Ark42** [gitextensions/gitextensions#2252] opened 2014-02-19 04:29 UTC
Brand new laptop with 2880x1620 comes set to 192 dpi (scales everything 200%) because otherwise things would be TINY and unreadable. Most apps are either not DPI-aware and Windows will render them to a virtual 96dpi offscreen buffer, and then enlarge that onto the screen. Git Extensions apparently CLAIMS to be DPI-aware though via its manifest, but it is just horribly NOT DPI-aware at all. Every text is cut off on the bottom of the font in the options and buttons to the point where the program is just unusable. There is no work-around since the app claims DPI-awareness either.

--- GitExtensions2.47.3, Git 1.8.3.msysgit.0, Microsoft Windows NT 6.3.9600.0

**Comment by FallenGameR** [comment] 2015-09-22 19:34
+1

**Comment by rrymar** [comment] 2016-04-25 15:27
+1

**Comment by KindDragon** [comment] 2016-04-25 18:08
Use GitHub reactions instead https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by hypersw** [comment] 2016-04-25 19:37
Actually, fresh GitExt works acceptably on my 192 DPI box.
Not nicely, because it's bluntly stretched by DWM, but naturally enough to be workable.

**Comment by KindDragon** [comment] 2016-04-25 19:59
@hypersw Try revert this commit and see what happens :) https://github.com/gitextensions/gitextensions/commit/7dfc553e4ba3b16913a3474b60e18ec052f57427

**Comment by hypersw** [comment] 2016-04-25 20:12
Or "`true/pm`" for maximum lulz, yep.
But the commit is 2013 and the issue is 2014, that's what looked strange to me. Maybe it had a long way getting into RTM.

**Comment by cppguru** [comment] 2016-04-27 12:55
I was trying to use it on a Windows VM running in native resolution on a
retina MBP, and it was useless.  The rest of Windows and other programs
worked fine, displaying with larger fonts to be readable etc., but not Git
Extensions.  (I must confess that I do not a lot of programs in that VM,
just what is needed to program on Windows.)

**Comment by KindDragon** [comment] 2016-04-27 13:55
What you mean by "useless"

**Comment by cppguru** [comment] 2016-04-28 13:59
I mean tiny, unreadable text

**Comment by tobiaszuercher** [comment] 2016-06-27 12:40
what is the state? it's either blurry (if scaling is enabled) or too small. my res: 3840x2160

shall i provide some screenshots?

**Comment by FireEmerald** [comment] 2016-11-03 09:19
As an example how gitextensions looks like on a high resolution display:
<img width="463" alt="2016-11-03 10_14_07-klonen" src="https://cloud.githubusercontent.com/assets/1107939/19960683/8b5aa0a0-a1ae-11e6-96a7-f9053024500b.png">
In comparison with the editor.

**Comment by KindDragon** [comment] 2016-11-03 11:14
You can disable scaling for version 2.49 http://static.ccm2.net/ccm.net/pictures/bHFYSm8d-appl-s-.png and report here bugs that you found. It should work almost for all features

**Comment by FireEmerald** [comment] 2016-11-03 11:26
I'm using 2.49RC2 and indeed this option works very well expect of:
<img width="488" alt="2016-11-03 12_23_42-program manager" src="https://cloud.githubusercontent.com/assets/1107939/19964156/724b710e-a1c0-11e6-86d5-9637a395e134.png">

**Comment by cppguru** [comment] 2016-11-03 18:06
Where is that AIX Properties?  I cannot find it in the Git Extensions
settings.

**Comment by FireEmerald** [comment] 2016-11-03 18:37
@cppguru The shown window can be found for gitextensions if you do a right click onto the GitExtensions.exe and then select Settings. AIX was just an example application.
![example](https://cloud.githubusercontent.com/assets/1107939/19980027/de98efee-a1fc-11e6-8357-891f3d84b004.gif)

**Comment by cppguru** [comment] 2016-11-03 18:40
Cool, thanks.  Now I just need to figure out how to do that on the Mac.

**Comment by KindDragon** [comment] 2016-11-03 18:44
> Cool, thanks.  Now I just need to figure out how to do that on the Mac.

Mono doesn't support this on Mac https://bugzilla.novell.com/show_bug.cgi?id=828584

**Comment by cppguru** [comment] 2016-11-03 21:34
Well that sux. It says: wontfix 

Attila aka WW

**Comment by KindDragon** [comment] 2016-11-03 23:32
@cppguru Do you use GitExt on MacOS? Can you tell us what version of Mono and MacOS you using?

**Comment by cppguru** [comment] 2016-11-04 15:15
I am not using it right now, because the screen was unreadable on the
retina display and so I have not reinstalled it when my laptop was replaced
by Apple.  I could install stuff on my work laptop (where I actually use
git nowadays), if you tell me what to install from where.  I have Homebrew
installed, I wonder if that can install the Mono version that is best.

**Comment by KindDragon** [comment] 2016-11-04 15:21
> I wonder if that can install the Mono version that is best

We too, because of that I am asking :) We don't have many users on macOs

**Comment by cppguru** [comment] 2016-11-04 15:31
Well, Homebrew has mono-4.6.1.5-sierra, I have installed it.  How do I
install Git Extensions on Mac?  The download gives me an MSI file, that is
for Windows.

**Comment by KindDragon** [comment] 2016-11-04 15:33
@cppguru https://git-extensions-documentation.readthedocs.io/en/latest/getting_started.html#installation-macos

You can download GitExt as zip archive here https://github.com/gitextensions/gitextensions/releases/tag/v2.49RC2

**Comment by cppguru** [comment] 2016-11-04 15:39
Which file do I use to start it up?  Mac wants to open the .exe with
Unarchiver, the .sh with XCode...

**Comment by cppguru** [comment] 2016-11-04 15:40
OK, I managed to run the .sh from the terminal, it complains about not
finding GitExtensions.,exe, which is in the same directory.

**Comment by KindDragon** [comment] 2016-11-04 15:42
Try manually call from terminal `mono GitExtensions.exe`

**Comment by cppguru** [comment] 2016-11-04 15:43
Managed to start it.  It starts with a warning message that Windows Forms
have not been ported to 64 bits and then an exception is thrown and it dies
a horrible death.

**Comment by ChadNedzlek** [comment] 2017-11-13 21:21
Is there some previous version I can run before this bug?  Git Extensions is really useful, but it's unusable in my current set up because of this issue.  I can't read any of the UI because it's so small, and as far as I can find, there is no workaround.

**Comment by RussKie** [comment] 2017-11-13 21:34
Unlikely.
The original issue was opened several years ago and, to my knowledge, it
has not been resolved to date.
I don't think any of the core contributors have hi-dpi monitors....

**Comment by RussKie** [comment] 2018-02-13 09:50
Here's a workaround which helps with some of the issues https://github.com/gitextensions/gitextensions/issues/4099#issuecomment-349899698

**Closed as completed** 2018-04-04 20:23 UTC
Labels: type: feature request, up-for-grabs, area: hdpi
