### ISSUE TITLE
After major version update dark theme does not work anymore

### ISSUE THREAD

**Issue by samibeyoglu** [gitextensions/gitextensions#10373] opened 2022-11-10 07:49 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

Hi,

I upgraded from version 3.5.4.12724 to 4.0.0.15569 and dark theme does not work anymore.

### Steps to reproduce

- Remove version 3.5.4.12724
- Install version  4.0.0.15569 
- Select 'dark' theme 
![image](https://user-images.githubusercontent.com/3684502/201030179-05d6e2a8-eef0-4e6b-a316-939ee89d8f0e.png)
- Restart Git Extensions
- Observe the UI is partially in dark theme
![image](https://user-images.githubusercontent.com/3684502/201031296-0ddedb74-31d2-4ca5-b18a-b7145e5e0965.png)

### Did this work in previous version of GitExtensions?

Version 3.5.4.12724

**Comment by pmiossec** [comment] 2022-11-10 08:26
Closing as duplicate of #10312, #10331, #10361, #10369 (and maybe some others...)

**Closed** 2022-11-10 08:26 UTC
Labels: :eyeglasses: status: needs review
