### ISSUE TITLE
[NBug] Remote URLs should appear in pairs.

### ISSUE THREAD

**Issue by ifflanb** [gitextensions/gitextensions#6628] opened 2019-05-21 22:25 UTC
## Error Details
```
System.Exception: Remote URLs should appear in pairs.
   at GitCommands.GitModule.<GetRemotesAsync>g__ParseRemotes|155_0(IEnumerable`1 lines)
   at GitCommands.GitModule.<GetRemotesAsync>d__155.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass69_0.<<AddTree>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.9.3.windows.2
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2019-05-21 22:37
Duplicate of #6562

**Comment by RussKie** [comment] 2019-05-21 22:37
You git version is too old

**Closed by RussKie** 2019-05-21 22:37 UTC

**Comment by illfated** [comment] 2019-05-22 19:31
@ifflanb : if you upgrade your Git software package to 2.20 or newer, this issue will probably stop happening.

**Comment by ifflanb** [comment] 2019-05-22 19:38
Hi. Are you meaning just the Git part as opposed to Git Extensions?
Just to explain what happened, I just had the usual update message from Git Extensions which I opted to go ahead with. I have downgraded my Git Extensions back to 3.0.2.5232 atm whihc has fixed it.

**Comment by illfated** [comment] 2019-05-22 19:43
**Git 2.9.3.windows.2** is too old for Git Extensions 3.1 -- hence the error.
Follow the Git Extensions development to see what the new requirements will be.

**Comment by pmiossec** [comment] 2019-05-22 19:47
That's explained in #6562 but there is problem of compatibility of error message between the old versions of git and the new version of gitextensions. That is already fixed in a bug fix version that still is waiting to be released.

But because your version of git is really old, the good action is surely to upgrade git than downgrade gitextensions.

**Comment by ifflanb** [comment] 2019-05-22 19:50
Ok thanks for your help. I'll give that a go.

**Comment by ifflanb** [comment] 2019-05-22 19:54
Yep updated my Git and then my Git Extensions and all seems to be working fine. thanks again.
