### ISSUE TITLE
Commit button doesn't show commit's status correctly

### ISSUE THREAD

**Issue by vzabavnov** [gitextensions/gitextensions#2626] opened 2015-01-23 21:03 UTC
I have build based on 0397051a3269ea10176c0655a97b7708298202e2.
The "Commit" button does not reflect status of changes, it always shows "Green" checkbox even some modifications exist

**Comment by KindDragon** [comment] 2015-01-23 22:54
Duplicate of issue #2560

**Closed by KindDragon** 2015-01-23 22:54 UTC
