### ISSUE TITLE
Right Click->Delete file on file in commit diff view does not work

### ISSUE THREAD

**Issue by johndog** [gitextensions/gitextensions#6517] opened 2019-04-29 18:35 UTC
## Steps to reproduce
(See picture below)

In the main window, look at a commit diff, right-click a file and choose "delete file".

Result:  Nothing happens.

Expect:  Should delete the file

## Screenshots
![image](https://user-images.githubusercontent.com/22213780/56918337-99c2b080-6a72-11e9-8775-a6893bbd3a45.png)

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.vfs.1.1.104.g2ab7360
- Microsoft Windows NT 10.0.18875.0
- .NET Framework 4.8.3752.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-04-29 19:26
Fixed in upcoming GE 3.1
Delete file should only be available for Working tree, not normal commits or the index

**Closed by gerhardol** 2019-04-29 19:26 UTC

**Comment by johndog** [comment] 2019-04-29 20:03
:(   I actually wanted to use this feature...  Diff shows precisely the files I needed to delete, so I wound up using "copy path" and pasting to the command-line.

I guess I can add a script.

**Comment by gerhardol** [comment] 2019-04-29 20:13
The problem is how to visualize that it is the working directory file that is deleted, not affecting the commit.

You can use Show in folder, then press Delete.

**Comment by RussKie** [comment] 2019-04-29 22:01
It is a common misconception to think what you see in "File tree" or in "Diff" views is what you have on your file system.
The HEAD commit (i.e. the working directory) is the only true presentation of your file system.

**Comment by johndog** [comment] 2019-05-02 10:15
Show in Folder works well, I didn't realize it selected the specific file.
