### ISSUE TITLE
Wrong behavior on display with high DPI

### ISSUE THREAD

**Issue by oleg-oleinik** [gitextensions/gitextensions#3514] opened 2017-01-31 13:35 UTC
I have a resolution of 3200 * 1800 and scale everything 200%. Because of this GitExtensions incorrectly displays the information in the console window when run git commands. First, in the window is not visible executed command (first screenshot), but while scrolling can be seen that some of the information is shifted relative to the left edge (second screen). Сhanging the console window size has no effect on the outcome

PS: Some extra character on last line appears.

--- GitExtensions2.49, Git 2.10.1.windows.1, Microsoft Windows NT 6.3.9600.0
![1](https://cloud.githubusercontent.com/assets/8359303/22466780/df27766c-e7d2-11e6-8c18-db4456e92bb2.png)
![default](https://cloud.githubusercontent.com/assets/8359303/22466519/b44dfdc2-e7d1-11e6-9b37-9ef59bfa008d.png)

**Comment by KindDragon** [comment] 2017-02-01 17:58
We have that bug without High DPI too

**Comment by RussKie** [comment] 2018-02-03 09:25
Duplicate of #3282

**Closed by RussKie** 2018-02-03 09:25 UTC
Labels: dependency bug
