### ISSUE TITLE
[NBug] Value cannot be null.Parameter name: path3

### ISSUE THREAD

**Issue by alexgavru** [gitextensions/gitextensions#7234] opened 2019-10-03 06:23 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentNullException: Value cannot be null.
Parameter name: path3
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at GitUI.CommandsDialogs.SettingsDialog.MergeToolsHelper.FindFileInFolders(String fileName, String[] locations)
   at GitUI.CommandsDialogs.SettingsDialog.MergeToolsHelper.FindMergeToolFullPath(ConfigFileSettingsSet settings, String mergeToolText, String& exeName)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.GitConfigSettingsPage.MergeToolCmdSuggest_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.OnTextChanged(EventArgs e)
   at System.Windows.Forms.Control.set_Text(String value)
   at System.Windows.Forms.ComboBox.set_Text(String value)
   at System.Windows.Forms.ComboBox.UpdateText()
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Open Settings and change merge tool to TortoiseMerge.

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-10-03 22:38
Duplicate of #7169
Corrected in master
(No real workaround, you can use the portable version to set TortoiseMerge as mergetool or install without plugins.)

**Closed** 2019-11-15 12:34 UTC
Labels: potential-duplicate, status: incorrectly filled template
