### ISSUE TITLE
[NBug] fatal: unrecognized argument in the plugin "Delete Obsolete Branches

### ISSUE THREAD

**Issue by kool79** [gitextensions/gitextensions#11825] opened 2024-08-03 20:10 UTC
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.45.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.26
- DPI 144dpi (150% scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c log.showSignature=false log --pretty=%ci
%an
%s --max-count=1 origin/HEAD -> origin/master --
Working directory: D:\Dropbox\dev\AC\git\capri\sfcc-alta-qa-automation\

```
GitExtUtils.ExternalOperationException: fatal: unrecognized argument: ->
 ---> System.Exception: fatal: unrecognized argument: ->
   --- End of inner exception stack trace ---
   at async Task<string> GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 147
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at IEnumerable<Branch> GitExtensions.Plugins.DeleteUnusedBranches.DeleteUnusedBranchesForm.GetObsoleteBranches(RefreshContext context, string curBranch)+MoveNext() in C:/projects/gitextensions/Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs:line 106
   at void System.Collections.Generic.List<T>.InsertRange(int index, IEnumerable<T> collection)
   at void GitUI.SortableBindingList<T>.AddRange(IEnumerable<T> items) in C:/projects/gitextensions/GitUI/SortableBindingList.cs:line 20
   at async Task GitExtensions.Plugins.DeleteUnusedBranches.DeleteUnusedBranchesForm.RefreshObsoleteBranchesAsync() in C:/projects/gitextensions/Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs:line 350
   at async void GitUI.TaskManager.InvokeAndForget(Control control, Func<Task> asyncAction, CancellationToken cancellationToken)+(?) => { } [1] in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 111
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

Program failed with "Unrecognized argument" when I try to search for branches with 'Delete Obsolate Branches' plugin. My seettings are: Delete older than: 30 days; Delete fully merged into:  "origin/master"; [x] delete remote branches from: 'origin'; [ ] use regex (unchecked);
[x] Include unmerged branches -- checked,
  Program display the message:
fatal: unrecognized argument: -> 
Exit cde: 128 Command:
C:\program files\Git\bin\git.exe 
Arguments:
-c log.showSignature=false log --pretty=%ci %an %s --max-count=1 origin/HEAD -> origin/master --

It seems there is some missed argument

### Steps to reproduce

see description above

**Comment by gerhardol** [comment] 2024-08-03 21:00
Duplicate of #11375 
Fixed in #11376

**Closed by gerhardol** 2024-08-03 21:00 UTC
Labels: :eyeglasses: status: needs review
