### ISSUE TITLE
commit showing unresolved merge conflicts when there is none

### ISSUE THREAD

**Issue by slymz** [gitextensions/gitextensions#9979] opened 2022-04-28 14:22 UTC
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.36.0.vfs.0.0
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4470.0
- DPI 96dpi (no scaling)

### Issue description

Commit dialog is showing merge conflicts that do not exists. Here is a screenshot from a clean worktree:

![image](https://user-images.githubusercontent.com/613314/165773486-44ba82a6-a350-407a-ab8f-93b7258de4d6.png)

A dirty worktree without any conflict is showing this as well, and commit operations fail with perceived unaccounted merge issues.

This started after upgrading to the latest https://github.com/microsoft/VFSForGit (see new version under Environment).  

### Steps to reproduce

1. get Microsoft VFSforGit 2.36.0.vfs.0.0
2. gitextension commit

### Did this work in previous version of GitExtensions?

GitExtensions  3.5.4.12724 with Git-2.33.0.vfs.0.2-64-bit was working fine.

**Comment by pmiossec** [comment] 2022-04-28 14:31
Duplicate of #9977 (the workaround is there)

**Closed** 2022-04-28 17:59 UTC
Labels: type: git issue

**Comment by slymz** [comment] 2022-04-28 22:30
ah nice! just adding an extra bit of config-specific gotcha ftr for others:

The fix is to set "core.fsmonitor" globally.  But that refused to work!  The bash command-line was silent (no more "hint"s), but gitex wasn't.

I have my .gitconfig under mingw-bash $HOME that is in a directory shared with other linux, vm etc.  Turns out there is another .gitconfig in the system, under default windows %USERPROFILE% which I never really use and GitExtensions were using that all along.   So GitExtensions never saw the new core.fsmonitor option. 

GitEx>Settings>Git>Path>Change HOME did the trick.
