### ISSUE TITLE
Git log for renamed files not working

### ISSUE THREAD

**Issue by sbocskai** [gitextensions/gitextensions#6251] opened 2019-02-15 10:50 UTC
## Current behaviour

When a file was renamed on git, the history log on that file cannot be seen.
git log --follow   command will correctly shows changes.

## Expected behaviour

Git extension logs on a file should be similar to git log --follow   command results.

## Did this work in previous version of GitExtensions

yes: version < 3.0

## Environment

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2019-02-17 05:17
Please provide steps to reproduce or an example git repo

**Comment by vbjay** [comment] 2019-02-17 05:22
#5944

**Comment by gerhardol** [comment] 2019-02-17 09:41
Duplicate of #5944

**Closed by gerhardol** 2019-02-17 09:41 UTC
Labels: status: more info requested, status: needs review

**Comment by sbocskai** [comment] 2019-02-17 17:26
> Please provide steps to reproduce or an example git repo

Hi

here is how I reproduced the issue:
1. Check out the repo: https://github.com/sbocskai/GitExtIssue6251.git
2. Added a README.md file: commited with "Initial commit"
3. Rename the file to README2.md, commited https://github.com/sbocskai/GitExtIssue6251/commit/351fe210f8147018db5b6145c70f856b50c0f3d3
4. Git extension: "File history" on README2.md shows only last commit
in the previous versions ( < 3.0) "File history" shows commit before file was renamed, as you can have with `git log --follow`

**Comment by illfated** [comment] 2019-02-18 19:17
@sbocskai : You may want to post your how-to-reproduce steps in the open issue ticket #5944 , now that this ticket is closed (or just keep reading ticket #5944 ).
