### ISSUE TITLE
Update installation not adhering to configured telemetry setting

### ISSUE THREAD

**Issue by raulsrule** [gitextensions/gitextensions#8377] opened 2020-08-04 13:47 UTC
## Current behaviour

I have disabled telemetry option. | Settings > General > ` []  Yes, I allow telemetry`
Whenever an update is released, I simply install it by downloading the update `.msi` (I don't uninstall the existing version)
All the previous settings which were configured stays as is, but the telemetry option reverts back to checked state.

## Expected behaviour

All the previous settings which were configured should stay as is, including the telemetry option.

## Steps to reproduce

Install an older version. Change some settings followed by disabling telemetry option and then install an update over it. Telemetry would be toggled back to check state.

## Did this work in previous version of GitExtensions

This never worked in any previous version. I always manually uncheck the option after installing a new update. Raising an issue  now as it seems nobody has encountered this issue yet.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4200.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment] 2020-08-04 14:27
Duplicate of #8228

**Closed** 2020-08-04 21:55 UTC
