### ISSUE TITLE
Annoying graphical bug

### ISSUE THREAD

**Issue by GermanAizek** [gitextensions/gitextensions#11658] opened 2024-03-26 11:01 UTC
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.42.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.26
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Annoying graphical bug when commits do not stretch to full width and there is no way to stretch it all the way to right side, there will still be gray stripe.
RDP client selects resolution itself depending on computer display, I have 1920x1080

![image](https://github.com/gitextensions/gitextensions/assets/21138600/c14d8510-7a4e-42c3-823f-1dfed4cc8ac6)

![image](https://github.com/gitextensions/gitextensions/assets/21138600/defec1ef-1c9d-4b56-8846-97595bee094b)

### Steps to reproduce

Unknown how to reproduce, most likely this behavior is only in RDP.

**Comment by pmiossec** [comment] 2024-03-26 11:08
Duplicate of #10959 See https://github.com/gitextensions/gitextensions/issues/10959#issuecomment-1546030705 to make it disappear.

**Closed by pmiossec** 2024-03-26 11:08 UTC
Labels: :eyeglasses: status: needs review
