### ISSUE TITLE
[NBug] Version string portion was too short or too long.

### ISSUE THREAD

**Issue by atedesco87** [gitextensions/gitextensions#8069] opened 2020-05-05 13:52 UTC
#7562  Current behaviour

Cannot publish change to Gerrit.

## Expected behaviour
Should be able to publish change to Gerrit.

## Steps to reproduce
Try to publish change to Gerrit.  This error occurs.

## Error Details
```
System.ArgumentException: Version string portion was too short or too long.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at Gerrit.FormGerritBase.OnLoad(EventArgs e)
   at Gerrit.FormGerritPublish.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
RestClient cannot get version from Gerrit Server using Git Extensions.  Same code outside of Git Extensions is able to get the version.

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3610.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2020-05-05 14:53
Duplicate of #7521

Updated in 3.4

**Closed** 2020-05-09 10:54 UTC
Labels: potential-duplicate
