### ISSUE TITLE
Splitter Positions are not stored/restored in 3.5 RC 1

### ISSUE THREAD

**Issue by slaut** [gitextensions/gitextensions#9088] opened 2021-04-19 05:10 UTC
## Current behaviour

Splitter positions across the application are not stored/restored.

## Expected behaviour

Changing splitter positions should store and restore on next restart

## Steps to reproduce

- Open main window
- Change splitter positions
- restart GitExtensions
-> Splitter positions are default

Same for example: 
- commit window.
- Diff View in main window
- File-Tree in main window
- and many more...

## Did this work in previous version of GitExtensions

Last stable release (3.4)

## Environment

- Git Extensions 3.5.0.11509
- Build 009d10c765a90aa00e043e40d5117256b793bc8c (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4300.0
- DPI 144dpi (150% scaling)

**Comment by mstv** [comment] 2021-04-19 19:02
Yes, this is a duplicate of the unfortunately still open #8745.

**Closed by mstv** 2021-04-19 19:02 UTC
