### ISSUE TITLE
Author information incorrect when using multiple GitHub accounts (via conditional includes)

### ISSUE THREAD

**Issue by razzp** [gitextensions/gitextensions#8374] opened 2020-08-03 13:42 UTC
## Current behaviour

I currently use two GitHub accounts - work and personal. The latter is the default on my system and I conditionally include an override in my global `.gitconfig` to instead use my work credentials when I'm in a specific directory:

```
[includeIf "gitdir/i:**/work/[COMPANY]/"]
    path = ~/.gitconfig.[COMPANY]
```

This works fine. Commits are made using the correct credentials and I can run `git config --list` in my work directories and see the overrides taking place. The only place I don't see these overrides being honoured is in the commit window; the author information at the bottom of the UI still shows my default account information.

This isn't the end of the world as the commits themselves are correct, however it is quite misleading and had me scratching my head for a while until I created a dummy repository to test who I was _actually_ committing as.

Note: I am an absolute novice when it comes to Git, so I could be going about this in completely the wrong way!

## Expected behaviour

GitExtensions' UI to honour override settings (namely author information) in the global `.gitconfig`.

## Steps to reproduce

Providing you have two or more GitHub accounts:

1. Use [conditional includes](https://git-scm.com/docs/git-config#_conditional_includes) to override the default account information
2. Open a repository that would be affected by these overrides and confirm by running `git config --list`
3. Open the commit window in GitExtensions and check the author information at the bottom of the UI

## Environment

- GitExtensions version: 3.4.2.9737
- GIT version: 2.27.0
- OS version: Win 10 (64)
- .NET version:  4.0

**Comment by gerhardol** [comment] 2020-08-03 20:56
Duplicate of #5492 

It is the same in most GE forms like Settings-Git-Config, Commit info for artificial commits, Patch form etc.
GE does not support custom includes (also non-conditional) when displaying info. Instead the expected files is read from the config file.
As Git commands are done by native Git, the functionality is mostly OK.

**Closed by gerhardol** 2020-08-03 20:56 UTC
