### ISSUE TITLE
Menu bar arrow-key navigation is backwards

### ISSUE THREAD

**Issue by nyanpasu64** [gitextensions/gitextensions#5970] opened 2018-12-21 01:51 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I open a menu, the left arrow key moves to the rightwards menu (and vice versa).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Either:
a. Press Alt, followed by Down arrow.
b. Click a menu.

Then press Right arrow.

Pressing Alt without opening a menu does not lead to backwards navigation.

**What is the expected behavior?**
Pressing Right arrow moves to rightwards menu (not left).

**Environment you encounter the issue:**

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3221.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
Not sure, I may have encountered this issue months/years ago.

**Comment by mstv** [comment] 2018-12-21 10:17
Is it always reproducible? Which language settings and input method settings do you use?
Do you use keypress handling tools like AutoHotkey or AutoIt?
I cannot reproduce it with 3.00.00.4433.

**Comment by jimbo1qaz** [comment] 2019-01-05 01:22
Always reproducible, including Safe Mode with Networking. The only program in my system tray is Malwarebytes Tray (my usual Autohotkey apps are not running).

I've previously used SharpKeys to remap Caps Lock, but the rule is no longer active.

I have English (United States) language pack installed/enabled, and China (PRC) installed.

ChsIme.exe is running and I have several input languages via Win+Space, but I'm using English input. Other inputs:

- Google Pinyin 2
- Microsoft pinyin simplified
- Japanese (Microsoft IME)
- French, German, Croatian layouts

My non-Unicode locale is English (United States). I may have used a mod of AppLocale (per-app locales) before, but not on Git Extensions.

My date format is yyyy-MM-dd (altered from before).

**Comment by Liturgist** [comment] 2019-12-31 23:32
Still happens under recent version.

- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3468.0
- DPI 144dpi (150% scaling)

**Comment by mstv** [comment] 2020-01-01 19:59
Thank you both for the detailed information. But I cannot reproduce.

**Comment by RussKie** [comment] 2020-01-09 11:08
I can repro this, and it is weird - click on [Start] menu, then use left/right arrows and the menu navigation goes in the opposite direction...

**Comment by grleachman** [comment] 2020-04-15 10:03
LOL I cracked up.. when I experienced this.. I thought "someone has a great sense of humor"

3.3.1.7897
Build 5a9767

Please don't fix this bug 👍

**Comment by pmiossec** [comment] 2020-04-15 13:55
That's a bug in `MenuStrip` that is used for the menu. See https://stackoverflow.com/a/16306598/717372

Thoose that don't have the problem are the ones that have their system configured as "left handed" (in `Control Panel` -> `Tablet PC Settings` -> `Other` -> `Handedness`

**Comment by RussKie** [comment] 2020-04-16 10:26
Nice one, @pmiossec!
More reasons to move to .NET Core, so we can fix it (I think we can 🤔)

**Comment by kirsan31** [comment] 2020-05-13 09:30
> Nice one, @pmiossec! More reasons to move to .NET Core, so we can fix it (I think we can )

Still not on  .NET Core??? :smirk:
Seriously, we need more big WinForms projects at least tried to move to core, to achive more real life feedback...

**Comment by RussKie** [comment] 2020-05-13 11:44
That's the next stage after we release v3.4.
I had a test conversion to .NET Core in https://github.com/gitextensions/gitextensions/pull/7162, and it worked by far and large.

**Comment by gerhardol** [comment] 2020-05-13 20:46
I am sure @RussKie would appreciate some help here, he has not infinite time to spend on .NET Core conversion and other cleanup tasks.
Other members spend more on adding features...

**Comment by weltkante** [comment] 2020-05-13 21:29
> That's a bug in `MenuStrip` that is used for the menu. See https://stackoverflow.com/a/16306598/717372
> 
> Thoose that don't have the problem are the ones that have their system configured as "left handed" (in `Control Panel` -> `Tablet PC Settings` -> `Other` -> `Handedness`

This is also affected on whether you ever had a touch device connected to the machine. If you never had one connected this setting is ignored. The point is that touch users want menus to open to the opposite side of their hand when they use a pen (otherwise the menu would open under their hand and they can't read anything).

**Comment by pmiossec** [comment] 2020-05-13 22:22
>This is also affected on whether you ever had a touch device connected to the machine. 

If you're right, I imagine that I have the problem because I have a touch screen...

**Comment by jeremy-visionaid** [comment] 2020-05-21 07:45
I have a touch screen currently connected and still see the issue on Windows 10.

**Comment by weltkante** [comment] 2020-05-21 10:17
Yes, apparently Windows 10 has change its behavior, its unclear of whether thats a regression or intentional change.  As far as WinForms is concerned there is dotnet/winforms#3272 looking into it.

WPF shouldn't have changed behavior as far as people can tell.

**Comment by RussKie** [comment] 2020-05-26 01:14
Fixed in .NET 5.0 P6 https://github.com/dotnet/winforms/pull/3274

**Closed by RussKie** 2020-05-26 01:14 UTC
Labels: :beetle: type: bug, area: user experience, status: reproducible
