### ISSUE TITLE
[NBug] Error when clicking a script button in menu bar "Value cannot be null. (Parameter 'input')"

### ISSUE THREAD

**Issue by sjonesstmn** [gitextensions/gitextensions#11914] opened 2024-09-13 13:08 UTC
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Match(String input)
   at GitUI.ScriptsEngine.ScriptsManager.ScriptRunner.ParseUserInputs(String scriptName, String arguments, IGitUICommands uiCommands, IWin32Window owner, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.ScriptRunner.cs:line 46
   at GitUI.ScriptsEngine.ScriptsManager.ScriptRunner.RunScriptInternal(ScriptInfo script, IWin32Window owner, IGitUICommands uiCommands, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.ScriptRunner.cs:line 133
   at GitUI.ScriptsEngine.ScriptsManager.ScriptRunner.RunScript(ScriptInfo script, IWin32Window owner, IGitUICommands commands, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.ScriptRunner.cs:line 32
   at GitUI.ScriptsEngine.ScriptsManager.RunScript(ScriptInfo scriptInfo, IWin32Window owner, IGitUICommands commands, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.cs:line 71
   at GitUI.GitModuleForm.<ExecuteCommand>g__ExecuteScriptCommand|24_0(<>c__DisplayClass24_0&) in C:\projects\gitextensions\src\app\GitUI\GitModuleForm.cs:line 119
   at GitUI.GitModuleForm.ExecuteCommand(Int32 command) in C:\projects\gitextensions\src\app\GitUI\GitModuleForm.cs:line 107
   at GitUI.CommandsDialogs.FormBrowse.ExecuteCommand(Int32 cmd) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormBrowse.cs:line 2062
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass76_1.<InternalInitialize>b__3(Object s, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormBrowse.cs:line 1083
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m) in C:\projects\gitextensions\src\app\GitUI\UserControls\ToolStripEx.cs:line 89
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

Using script functionality to add a button to call powershell script in menu bar

### Steps to reproduce

Powershell Script was like this:
![image](https://github.com/user-attachments/assets/0a33d854-5450-4860-ae1a-ef7962bd4b6e)

### Did this work in previous version of GitExtensions?

Yes it worked in 4.X

**Comment by gerhardol** [comment] 2024-09-13 13:19
Looks like a duplicate of https://github.com/gitextensions/gitextensions/issues/11892. Fixed by https://github.com/gitextensions/gitextensions/pull/11893

You could test the portable version to confirm if issue is fixed: [ci.appveyor.com/project/gitextensions/gitextensions/builds/50564009/artifacts](https://ci.appveyor.com/project/gitextensions/gitextensions/builds/50564009/artifacts)

Ask for reopen if it's not the case.

**Closed by gerhardol** 2024-09-13 13:19 UTC
Labels: :eyeglasses: status: needs review

**Comment by pmiossec** [comment] 2024-09-13 13:21
A workaround that maybe works: put something like "foo" in "Arguments" field
