### ISSUE TITLE
[NBug] Application not found

### ISSUE THREAD

**Issue by allsorts46** [gitextensions/gitextensions#8917] opened 2021-03-04 11:51 UTC
Right-clicked on a file in the Diff tab, chose "Open this revision (temp file)". Got crash handler dialog.

## Current behaviour

GitExtensions showed crash handler dialog and closed.

## Expected behaviour

Was expecting to see the file opened for viewing, but worst case should be a graceful error dialog.

## Steps to reproduce

1. Don't have whatever GitExtensions is trying to use to view the file installed on your system
2. Try to view a file using "Open this revision (temp file)" menu item.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): Application not found
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at GitUI.CommandsDialogs.RevisionDiffControl.<>c.<diffOpenRevisionFileToolStripMenuItem_Click>b__54_0(String fileName)
   at GitUI.CommandsDialogs.RevisionDiffControl.<>c__DisplayClass56_0.<<SaveSelectedItemToTempFile>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Chose 'Show this revision' (can't remember exact naming) on a file in the Diff tab. Evidently it's trying to launch a viewer process but the viewer doesn't exist.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2021-03-04 22:29
Duplicate of #7156 

Can you reproduce?

**Comment by allsorts46** [comment] 2021-03-04 23:48
Yes, it happens every time, for any .cs file in any commit. I tried a few other file types: .csproj launches visual studio, .cshtml opens Window standard 'choose a program' dialog, .xml opens in Notepad++. Seems to be just .cs files with the problem.

Double-clicking a .cs file in explorer brings up the Windows dialog to choose a program.

I have both current *and* preview versions of Visual Studio installed, if that provides any clue.

**Comment by RussKie** [comment] 2021-03-05 03:27
I can't repro it locally
![image](https://user-images.githubusercontent.com/4403806/110063192-c65a5880-7dbe-11eb-905a-0c0682b07eae.png)

Can you debug in and see what app it is trying to launch?

**Comment by gerhardol** [comment] 2021-03-19 20:59
Please try the buildfor #8961, the exception is caught

**Comment by allsorts46** [comment] 2021-03-20 18:06
Thanks. I just wanted to check that the issue is still happening before trying the new suggested build, and... it's not. I can now successfully open .cs files from every diff that I tried.

Here is my current version info:

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

You can see the only thing that has changed since my report is that .NET version has gone from 4.8.4300.0 to 4.8.4341.0. I didn't do this deliberately so I'm guessing Windows Update. Could that have resolved it?

Sorry that's not particularly helpful now. I'll comment back if this happens again, and try the new build as well. The time that I reported this is not the first time I've seen it so it may happen again.

**Comment by RussKie** [comment] 2021-03-21 00:12
Presume fixed. If it repros in 3.5 or 3.6 please holler back.

**Closed** 2021-03-21 00:12 UTC
