### ISSUE TITLE
Git ext hangs when we create new branch and open in v3.00.000.4433

### ISSUE THREAD

**Issue by alam-manjur** [gitextensions/gitextensions#6046] opened 2019-01-07 06:25 UTC
UI becomes unresponsive in win10

**Comment by RussKie** [comment] 2019-01-07 07:54
In the future please fill in the issue template provided, and also search the existing issues before opening a new one.

I suspect this is a duplicate of #5884

**Closed by RussKie** 2019-01-07 07:54 UTC
