### ISSUE TITLE
GitExtensions does not work, however bash works properly

### ISSUE THREAD

**Issue by very-cool-name** [gitextensions/gitextensions#2630] opened 2015-01-27 10:23 UTC
Hello. I've happily used git extensions until reinstalled windows. I've installed latest version of git extensions, and now when i try pull, push or clone i receive error "fatal: could not read from remote repository". However, when I use git bash it works OK.

**Comment by ghanique** [comment] 2015-01-27 10:33
This may have to do with one using openssl, the other using putty and putty
not being configured correctly... Perhaps the putty agent doesn't have the
private key. Look for something along those lines.

**Comment by very-cool-name** [comment] 2015-01-27 10:39
Sorry, if my answer misses point, I have quite poor understaning of ssh working, but our server does not use private and public keys. You just have to type key every time.

**Comment by very-cool-name** [comment] 2015-01-27 10:43
Oh, thank you, I still does not understand what is going on, but I switched gitextensions to openssh and everything is ok.

**Comment by ghanique** [comment] 2015-01-27 12:18
Glad you got your issue resolved :)

BTW: assuming you are on Windows, if you install the Credential Winstore
thingy you may not have to type your password over and over again.

**Comment by KindDragon** [comment] 2016-04-19 19:54
Duplicate of #85

**Closed by KindDragon** 2016-04-19 19:54 UTC
