### ISSUE TITLE
[NBug] fatal: bad revision 'HEAD'

### ISSUE THREAD

**Issue by vandreiradu** [gitextensions/gitextensions#10720] opened 2023-02-13 09:59 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.13
- DPI 96dpi (no scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" --max-count=100000 --glob=refs/stas[h] HEAD --
Working directory: C:\work\repos\Activities\

```
GitExtUtils.ExternalOperationException: fatal: bad revision 'HEAD'
 ---> System.Exception: fatal: bad revision 'HEAD'
   --- End of inner exception stack trace ---
   at void GitUI.RevisionGridControl.PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs, bool forceRefresh)+() => { }
   at async Task GitUI.GitUIExtensions.InvokeAsync(Control control, Action action, CancellationToken token)
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

fetch -> abort -> error

### Steps to reproduce

fetch origin
fetch taking too long -> abort
error appears

**Comment by RussKie** [comment] 2023-03-11 11:31
Is this something you can repro consistently?

**Comment by gerhardol** [comment] 2023-03-12 12:46
Duplicate of #10740

**Closed** 2023-03-20 21:13 UTC
Labels: :construction: status: in progress, potential-duplicate, :mailbox_with_no_mail: needs: author feedback
