### ISSUE TITLE
[NBug] An item with the same key has already been added.

### ISSUE THREAD

**Issue by calielc** [gitextensions/gitextensions#6737] opened 2019-06-03 12:17 UTC
## Current behaviour
When I open the application, or several other usages, I got this error. 
If I just ignore it, this system still works.

## Expected behaviour
No Exception 

## Steps to reproduce
Just open the application,
Open a repository

## Error Details
```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at GitUI.CommitInfo.CommitInfo.<LoadSortedRefsAsync>g__ToDictionary|55_0(IReadOnlyList`1 list)
   at GitUI.CommitInfo.CommitInfo.<LoadSortedRefsAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommitInfo.CommitInfo.<<RefreshSortedRefs>b__49_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.Hand

**Comment by calielc** [comment] 2019-06-03 12:18
Fixed template

**Comment by RussKie** [comment] 2019-06-03 12:27
Duplicate of #6616

**Comment by gerhardol** [comment] 2019-06-05 23:19
Duplicate, fixed in master. Please try the latest build to make sure your issue is fixed.

**Closed by gerhardol** 2019-06-05 23:19 UTC
Labels: potential-duplicate, status: incorrectly filled template
