### ISSUE TITLE
[NBug] No application is associated with the specified file for th...

### ISSUE THREAD

**Issue by eLefTrick6** [gitextensions/gitextensions#8664] opened 2020-12-08 16:12 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Expected behaviour
open the revision of the file in default text editor

## Steps to reproduce

in diff view, right click file, open this revision of the file, error. my default editor in the settings is vim.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): No application is associated with the specified file for this operation
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at GitUI.CommandsDialogs.RevisionDiffControl.<>c.<diffOpenRevisionFileToolStripMenuItem_Click>b__54_0(String fileName)
   at GitUI.CommandsDialogs.RevisionDiffControl.<>c__DisplayClass56_0.<<SaveSelectedItemToTempFile>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
rightlclick on file in diff, open this revision.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.2.windows.2
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4250.0
- DPI 144dpi (150% scaling)

**Comment by gerhardol** [comment] 2020-12-19 23:42
Duplicate of #7156

GE uses core windows handling here, should be the same as doubleclicking

The error message is less in your face with #8358 or #8278
Could also be handled with try-catch

**Closed by gerhardol** 2020-12-19 23:42 UTC
Labels: potential-duplicate
