### ISSUE TITLE
System.Xml.XmlException

### ISSUE THREAD

**Issue by TamaHobbit** [gitextensions/gitextensions#3064] opened 2015-12-16 08:35 UTC
I tried to do a push last night, the whole computer froze (not even task manager would open), so I had to hard-reboot. After rebooting, I found .git/index was an empty file, and my git status was invalid. After resetting that to my last commit, I now get a System.Xml.XmlException every time I try to start gitextensions, with this message:

'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.

I'm going to re-install gitextensions.

**Comment by TamaHobbit** [comment] 2015-12-16 09:16
Found the problem; %APPDATA%/Roaming/GitExtensions/GitExtensions/GitExtensions.settings contains only NUL characters. There is a GitExtensions.settings.backup file beside it which I was able to use as a replacement.

Presumably, the fix would be a try catch around the "parsing settings"-code, which then tries the backup file. If the backup file succeeds, replace the original with the backup file so that we continue with 2 copies of the backed up version.

**Comment by alastairtree** [comment] 2016-01-17 14:15
I just had this issue too, and reinstall did not fix but restoring the backup of the settings file did.

**Comment by vbjay** [comment] 2016-01-17 15:06
Why don't we crate an auto restore functionality.  If the settings loading
fails, try to read the backup.  If that fails let the user know.

**Comment by ghanique** [comment] 2016-01-18 06:11
If you do *ask* the user if he wants to restore. Sometimes that content is
recoverable and by restoring you would lose information.

**Comment by vbjay** [comment] 2016-01-18 14:36
Better to have what was before the last save than no settings at all.

**Comment by vbjay** [comment] 2016-01-18 14:38
The other thought is to add another backup after successful settings load.
This way he good settings don't get overwritten on 2 saves.

**Comment by lggomez** [comment] 2016-01-29 17:59
This looks like a duplicate of #2933

**Closed** 2016-04-18 22:54 UTC
Labels: bug

**Comment by hrai** [comment] 2018-08-31 04:57
I got rid of the whole temp folder and it worked. Except that you lose your settings.
