### ISSUE TITLE
Broken dark mode

### ISSUE THREAD

**Issue by kelteseth** [gitextensions/gitextensions#10485] opened 2022-12-02 09:32 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0 -> Latest Windows 11
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

Dark mode is not working. Yes, I did restart Git Extensions.

![image](https://user-images.githubusercontent.com/1071536/205261349-37d48fac-bf60-4f6f-9e5f-2cb395000ee3.png)

### Steps to reproduce

Settings -> Colors -> Theme -> Dark -> Restart app

### Did this work in previous version of GitExtensions?

Yes.

**Comment by gerhardol** [comment] 2022-12-02 09:49
Duplicate of #10312

Dark theme is no more supported in v4.0 because no technical solution has been found working with .net core/5.0 (like announced in the release notes: https://github.com/gitextensions/gitextensions/discussions/10310#discussion-4525909 )
Also discussed in https://github.com/gitextensions/gitextensions/discussions/10310#discussioncomment-4068052

**Closed by gerhardol** 2022-12-02 09:49 UTC
Labels: :eyeglasses: status: needs review
