### ISSUE TITLE
ConEmu missing

### ISSUE THREAD

**Issue by mleenhardt** [gitextensions/gitextensions#5931] opened 2018-12-17 02:55 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
ConEmu executables files don't exist in GitExtensions/bin/<Config>/ConEmu

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Clone the repo at latest master
- Run GitExtensions
- Select any commit
- Click the console tab
- The following exception is thrown
```
System.InvalidOperationException: Could not run the console emulator. The path to ConEmu.exe could not be detected.
   at ConEmu.WinForms.ConEmuSession.Init_StartConEmu(ConEmuStartInfo startinfo, CommandLineBuilder cmdl) in C:\dev\GitExtensions\Externals\conemu-inside\ConEmuWinForms\ConEmuSession.cs:line 718
   at ConEmu.WinForms.ConEmuSession..ctor(ConEmuStartInfo startinfo, HostContext hostcontext, JoinableTaskFactory joinableTaskFactory) in C:\dev\GitExtensions\Externals\conemu-inside\ConEmuWinForms\ConEmuSession.cs:line 136
   at ConEmu.WinForms.ConEmuControl.Start(ConEmuStartInfo startinfo, JoinableTaskFactory joinableTaskFactory) in C:\dev\GitExtensions\Externals\conemu-inside\ConEmuWinForms\ConEmuControl.cs:line 128
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass206_0.<FillTerminalTab>b__0(Object sender, TabControlCancelEventArgs args) in C:\dev\GitExtensions\GitUI\CommandsDialogs\FormBrowse.cs:line 2866
   at System.Windows.Forms.TabControl.OnSelecting(TabControlCancelEventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at GitUI.CommandsDialogs.FullBleedTabControl.WndProc(Message& m) in C:\dev\GitExtensions\GitUI\CommandsDialogs\FullBleedTabControl.cs:line 24
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**What is the expected behavior?**
No exception is thrown

**Environment you encounter the issue:**
Win 10 - VS 2017 - rev 7563efc37fc

I'm not sure where the ConEmu executable files (ConEmu.exe, ConEmu64.exe, etc) are supposed to be copied from since they don't seem to exist anywhere in the repo?

**Comment by vbjay** [comment] 2018-12-17 02:57
You need to update all submodules.

**Comment by vbjay** [comment] 2018-12-17 02:59
https://github.com/gitextensions/gitextensions/wiki/How-To:-build-instructions

**Comment by vbjay** [comment] 2018-12-17 03:00
Help-> about let's you copy full environment info.

**Comment by vbjay** [comment] 2018-12-17 03:36
Go ahead and close the issue since the issue is resolved.

**Closed** 2018-12-17 03:45 UTC

**Comment by RussKie** [comment] 2018-12-17 05:50
Under certain circumstances when building locally the conemu folder gets cleared. 
I've observed it on  numerous occasions but have never had sufficient time (or inclination) to investigate it.
