### ISSUE TITLE
Bug in "Effective" setting value displayed

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#3458] opened 2016-12-07 00:41 UTC
Context: Only the "global for all repositories" settings has been set.

If the default value of the setting is different from the value set, the "effective" setting displayed value is good when the setting dialog is opened.

But once we navigate between, "local for current repository" and "Distributed with current repository" which don't have a value set (and consequently that display the default value), then the "Effective" value display the wrong value.

Here in image (in this example "Powershell" is the value set globally and "Solarized" is the dafult value"):

![bug_settings_gitextensions](https://cloud.githubusercontent.com/assets/460196/20950102/d9cfb05c-bc1d-11e6-9104-66644e704d29.gif)

I've not investigated the consequences (if the bad value could overwrite the one set) at the moment...

PS: Even if the demo was done with a work in progress, the bug should not be introduced by it....

**Comment by jbialobr** [comment] 2016-12-09 10:15
The problem is when you visit the Distributed settings then the value for the Console style is empty, but the control is populated with the default value. When you leave the Distributed settings the values from the controls are assigned to the Settings object and the empyt value for Console style is replaced with the default value from the combobox. Now, effective value computation takes into account the new non empty value assigned at the Distributed level which overrides the value from the Global level.

I created a PR https://github.com/pmiossec/gitextensions/pull/1 that addresses this issue.

**Closed** 2017-04-11 06:53 UTC
Labels: bug
