### ISSUE TITLE
'', hexadecimal value 0x1A, is an invalid character. Line 1, position 1.

### ISSUE THREAD

**Issue by NA7KR** [gitextensions/gitextensions#2933] opened 2015-08-28 14:38 UTC
Crash on start.
![capture](https://cloud.githubusercontent.com/assets/6289433/9549024/af14edda-4d58-11e5-8e06-327ca0108671.PNG)

Has been working OK, but today get this.
Uninstalled and reinstalled and still same error

**Comment by lggomez** [comment] 2015-09-05 04:59
I never had this happen to me before, does it happen only when loading a repo or always?
There must be an xml or config file somewhere which is corrupt, or contains an invalid character which won't serialize/deserialize

Try deleting the gitextensions folder in appdata and any remnants (if any) before reinstalling

**Comment by lreading** [comment] 2015-11-09 20:31
I had the same issue today.  My computer had crashed in the middle of a commit/push, and then I could not open or close git extensions, even after uninstalling and re-installing.  Iggomez hit the nail on the head:

%user%\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings 

Even when attempting to open that file with NotePad++ I get the same error.

Deleting the entire folder after uninstalling then re-installing resolved the issue.

**Comment by TamaHobbit** [comment] 2016-01-29 19:27
NA7KR, examine this file: %APPDATA%/Roaming/GitExtensions/GitExtensions/GitExtensions.settings
If your text editor indicates it is all NUL characters, perhaps you should try the fix that worked for me; overwriting that file with GitExtensions.settings.backup, which is in the same folder.

**Comment by KindDragon** [comment] 2016-04-19 09:13
Duplicate of #2595

**Closed by KindDragon** 2016-04-19 09:13 UTC
Labels: bug

**Comment by RussKie** [comment] 2018-11-15 21:44
@Snehal-blinds which version have you been having issues with?
