### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Reactive.PlatformSe...

### ISSUE THREAD

**Issue by klorinczi** [gitextensions/gitextensions#10392] opened 2022-11-13 10:22 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.22.0.windows.1 (minimum: 2.25.0, please update!)
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.11
- DPI 144dpi (150% scaling)

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Reactive.PlatformServices, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. A rendszer nem találja a megadott fájlt.
File name: 'System.Reactive.PlatformServices, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'
   at BackgroundFetch.BackgroundFetchPlugin.RecreateObservable()
   at BackgroundFetch.BackgroundFetchPlugin.Register(IGitUICommands gitUiCommands)
   at GitUI.PluginRegistry.<>c__DisplayClass12_0.<Register>b__0(IGitPlugin p)
   at System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
   at GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   at GitUI.CommandsDialogs.FormBrowse.SetGitModule(Object sender, GitModuleEventArgs e)
   at GitUI.CommandsDialogs.FormBrowse.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Just installed Git Extensions v4.0.0 portable + .NET6 x64

### Steps to reproduce

Installed Git Extensions v4.0.0 portable + .NET6 x64 over Git Extensions v3.1.1

**Comment by mstv** [comment] 2022-11-13 10:37
Perhaps a duplicate of #10368.
Have you installed the .NET desktop runtime and / or Windows updates while running .NET applications?
Does it work when you restart Git Extensions and / or the PC?

**Comment by gerhardol** [comment] 2022-11-13 10:37
> Installed Git Extensions v4.0.0 portable + .NET6 x64 over Git Extensions v3.1.1

Portable must always be installed in a new directory, then migrating the changes.
Especially to 4.0, there are many changes due to .NET6.

**Closed by gerhardol** 2022-11-13 10:37 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
