### ISSUE TITLE
"Recent branch sorting" no longer available in v3

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#6395] opened 2019-03-22 03:15 UTC
## Current behaviour

The "Recent branches" drop-down is sorted by last used with no way to change it to sort alphabetically.

## Expected behaviour
That the option which was added in #4124 in response to issue #3907 would still be available and respected.

I may be looking in the wrong place, but I can't find it anymore and the previously set preference from 2.x is no longer respected.

## Did this work in previous version of GitExtensions

Yes, 2.5.x

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)

## Additional info

Yes, I'm aware of the branch list panel which is sorted alphabetically, but I find it takes up too much screen estate + is too fiddly.

What I mean by fiddly:
* As described previously in #3907, all my branches are namespaced, so it often takes four, five fold-out clicks to get to the actual branch.
* I've seen the `Expand All` option, but that, as the name says, expands **all** branches, not just the ones in the node you have selected.
* No keyboard shortcuts (at least none I'm aware of) to expand/collapse selected branch folder.

**Comment by gerhardol** [comment] 2019-03-23 00:14
Duplicate of #6310

**Closed by gerhardol** 2019-03-23 00:14 UTC

**Comment by jrfnl** [comment] 2019-03-23 00:28
@gerhardol Thanks for finding that, my search was clearly not good enough ;-)
