### ISSUE TITLE
[NBug] Clicked Settings and got System.ArgumentNullException

### ISSUE THREAD

**Issue by Danand** [gitextensions/gitextensions#7168] opened 2019-09-18 07:57 UTC
## Current behaviour
I just tried to click **Settings** and got this exception.

## Steps to reproduce
Click `Tools -> Settings`
It was reproduced once. Did not noticed any connection with my other experience in this session.

## Additional Information
It could be more handy for you at bug reports, if exception messages will output in English. Currently I see exceptions in Russian (OS language), despite choosen English as GitExtensions' appearance language.

## Error Details
```
System.ArgumentNullException: Значение не может быть неопределенным.
Имя параметра: source
   в System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   в System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   в System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   в System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   в GitUI.CommandsDialogs.FormSettings..ctor(GitUICommands commands, SettingsPageReference initialPage)
   в GitUI.CommandsDialogs.FormSettings.ShowSettingsDialog(GitUICommands uiCommands, IWin32Window owner, SettingsPageReference initialPage)
   в GitUI.GitUICommands.<>c__DisplayClass109_0.<StartSettingsDialog>g__Action|0()
   в GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent, Func`1 action)
   в GitUI.GitUICommands.StartSettingsDialog(IWin32Window owner, SettingsPageReference initialPage)
   в GitUI.CommandsDialogs.FormBrowse.OnShowSettingsClick(Object sender, EventArgs e)
   в System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   в System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   в System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ToolStrip.WndProc(Message& m)
   в System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-09-18 11:25
Duplicate of #7154 

A PR exists in #7164, maybe replaced by #7060 so this will be addressed in GE 3.3
Please try the portable build for #7164

**Closed by gerhardol** 2019-09-18 11:25 UTC
