### ISSUE TITLE
[NBug] Value cannot be null. (Parameter 'targetName')

### ISSUE THREAD

**Issue by Tim098b** [gitextensions/gitextensions#11932] opened 2024-09-21 20:44 UTC
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.ArgumentNullException: Value cannot be null. (Parameter 'targetName')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at GitExtensions.Extensibility.Settings.CredentialsManager.SetCredentials(SettingLevel settingLevel, String name, NetworkCredential value) in C:\projects\gitextensions\src\app\GitExtensions.Extensibility\Settings\CredentialsManager.cs:line 69
   at GitExtensions.Extensibility.Settings.CredentialsSetting.SaveValue(SettingsSource settings, String userName, String password) in C:\projects\gitextensions\src\app\GitExtensions.Extensibility\Settings\CredentialsSetting.cs:line 42
   at GitExtensions.Extensibility.Settings.CredentialsSetting.CredentialsControlBinding.SaveSetting(SettingsSource settings, CredentialsControl control) in C:\projects\gitextensions\src\app\GitExtensions.Extensibility\Settings\CredentialsSetting.cs:line 86
   at GitExtensions.Extensibility.Settings.SettingControlBinding`2.SaveSetting(SettingsSource settings) in C:\projects\gitextensions\src\app\GitExtensions.Extensibility\Settings\SettingControlBinding.cs:line 42
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.PageToSettings() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\SettingsPageBase.cs:line 123
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.SaveSettings() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\SettingsPageBase.cs:line 110
   at GitUI.CommandsDialogs.FormSettings.Save() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 233
   at GitUI.CommandsDialogs.FormSettings.buttonApply_Click(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 324
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

When I add a Personal access token for the Jira Commit Hint plugin I get this error (we also use our own domain for Jira)

### Steps to reproduce

When I add a Personal access token for the Jira Commit Hint plugin I get this error (we also use our own domain for Jira)

**Comment by gerhardol** [comment] 2024-09-21 21:34
Duplicate of #11907 
No info what is causing this

**Closed by gerhardol** 2024-09-21 21:34 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
