### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by alexeykuptsov** [gitextensions/gitextensions#11274] opened 2023-10-15 20:03 UTC
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.42.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.23
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.CommandsDialogs.Menus.CopyPathsToolStripMenuItem.CopyFullPathsNativeToolStripMenuItem_Click(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\Menus\CopyPathsToolStripMenuItem.cs:line 45
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

Hi,

I just did the steps to reproduce and got this NRE. I tried to copy a list of paths the second time and the NRE appeared again.

### Steps to reproduce

1. Open a diff tool (KDiff3 in my case) with Ctrl+L and Ctrl+R.
2. Select a few paths with Ctrl+MouseClick in the left panel
3. Press Ctrl+C

**Comment by alexeykuptsov** [comment] 2023-10-15 20:08
Guys hi again,

[duplicates-detector-bot](https://github.com/apps/duplicates-detector-bot) shows too many false positive. Can I help with this somehow?

**Comment by gerhardol** [comment] 2023-10-15 20:23
Duplicate of #10969 
Please try 4.2 rc1 where #10977 adresses this

**Closed** 2023-10-24 23:19 UTC
Labels: potential-duplicate, :mailbox_with_no_mail: needs: author feedback
