### ISSUE TITLE
Please show commit hash in Browse window

### ISSUE THREAD

**Issue by asherber** [gitextensions/gitextensions#2981] opened 2015-10-13 16:54 UTC
Hi,

It would be very helpful if the commit hash (or an appropriate substring of it) were visible in the Browse window list, along with the message, author, and date. Currently it shows only in the bottom part of the window, and only for the selected commit.

**Comment by ghanique** [comment] 2015-10-13 18:36
+1

**Comment by Radrik5** [comment] 2015-10-13 19:09
Probably duplicate of #2659 with linked PR.

**Comment by asherber** [comment] 2015-10-13 20:40
Yes, thanks -- same issue. Should I close this one?

**Comment by vbjay** [comment] 2015-10-13 20:49
When are you going to need to know the hash?  When you want to refer to the commit.  Which means you can use navigate to find it.  Or you select it and you see the commit info.  I could see selecting multiple commits and copying all the hashes as a comma separated list.  I think that info isn't needed in the current view.

**Comment by asherber** [comment] 2015-10-13 21:41
I have had situations recently where it would have been useful to see the hash here. Also, `git log` includes the hash, as do other apps like SourceTree.

**Comment by Radrik5** [comment] 2015-10-14 06:28
@vbjay proposed PR makes visibility of the hash column configurable. The column is hidden by default.

**Comment by VivienRuizFei** [comment] 2016-01-20 15:57
@vbjay I've been helping a colleague working on a remote site. He shared his screen through Skype, not giving me the ability to point or select. So we used a software capable of displaying SHA ID in the log window instead.

**Comment by vbjay** [comment] 2016-01-20 16:18
Try TeamViewer instead.https://www.teamviewer.com/en-us/

**Comment by VivienRuizFei** [comment] 2016-01-20 16:38
Old habits die hard, and it's not always possible to use a software such as teamviewer (free for personal use only in this case)

I just wanted to point out that I've been in a situation where I needed the SHA. Sometimes I do a screen capture and describe what's going on in an email using SHA of commits.

SHA ID is the only way to identify a commit, so I think that's an information that may have value for some people, hence I like the configuration suggestion.

**Comment by MpDzik** [comment] 2016-01-21 10:13
+1

**Comment by gregerc** [comment] 2016-06-21 07:36
@vbjay Another use case: Look at the diff of a merge commit. Git Extensions then shows "Diff with parent  badc0ffee" and "Diff with parent deadbeef". It would be really nice to be able to locate these parent commits easily in the log.

**Comment by vbjay** [comment] 2016-06-21 13:11
![image](https://cloud.githubusercontent.com/assets/3629489/16230576/2ae9f212-3790-11e6-9b6f-20a59b393be1.png)

**Comment by gregerc** [comment] 2016-06-21 14:44
@vbjay Absolutely! But... When I'm looking at the left view I like to see which parent comes from which branch. And since the parents are referenced by hash it's not easy to match them to the commits in the log. It can be done by clicking around a lot, but that really slows things down.

**Comment by vbjay** [comment] 2016-06-21 16:18
It is a whole lot faster to go to the commit tab and click the link instead
of search a column for the right hash.

**Comment by jbialobr** [comment] 2016-06-21 18:43
Implemented as an option in #2660.

**Closed by jbialobr** 2016-06-21 18:43 UTC
Labels: feature-request

**Comment by mccreeker** [comment] 2017-12-01 01:31
I and others on many teams have passed around the short-hash in chat or whatever and it would be super easy to quick-spot which recent hash (or at least within the time block visible) it is, like in Bitbucket's or GitHub's commit view... not seeing why Git Extensions can't have the short-hashes (or an option for long-hashes) simply in a column for easy spotting or scrolling through or searching for or ordering by or filtering by or copying...

Right now if someone mentions a hash I have to go to the remote repo (like in Bitbucket or GitHub) to see which one they're talking about or paste it into the Branch field in Git Extensions and hit Enter which for some reason is super laggy and much slower than searching on the remote repo webpage either with a Ctrl+F search on the page or in the website's search/filter.

**Comment by vbjay** [comment] 2017-12-01 01:35
http://git-extensions-documentation.readthedocs.io/en/latest/browse_repository.html

**Comment by asherber** [comment] 2017-12-01 01:37
This feature (show commit hash in browse window) is currently implemented in GitExtensions. If you don't see the hash column, click on View | Show SHA1.
