### ISSUE TITLE
Cherry-pick from stash shows an error modal even if OK

### ISSUE THREAD

**Issue by PhiLhoSoft** [gitextensions/gitextensions#9712] opened 2021-11-09 08:50 UTC
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4340.0
- DPI 96dpi (no scaling)

### Issue description

Each time I do a cherry-pick from a stash (often because there are conflicts and I am not allowed to resolve them), I get an "error modal" telling me that the operation was OK, which is confusing.
![image](https://user-images.githubusercontent.com/1087902/140888171-2e780ee8-7743-413b-a29d-ba6e6b5f0bd6.png)
Followed by a diff of the applied changes, which can be longer than the screen height!

Is there a way to avoid this?
And if it is a "feature", perhaps you should change the modal type to a information one, instead of an error one.

Actually, we can get a real error, but we can miss them when we do multiple cherry-picks and have to routinely discard these "information" modals…
![image](https://user-images.githubusercontent.com/1087902/140889483-3b900581-a77a-49e4-8793-5d35d9929e17.png)

### Steps to reproduce

Stash some code.
Do changes.
Open the stash modal.
Right-click on a file without conflicts with the changes, choose Cherry pick file changes.
The above mentioned first modal opens, stating the change was made cleanly.
Right-click on a file with conflicts with the changes, choose Cherry pick file changes.
The above mentioned second modal opens, indicating there are conflicts, without proposing to resolve them.

### Did this work in previous version of GitExtensions?

I don't know. Perhaps in quite old versions.

**Comment by gerhardol** [comment] 2021-11-09 10:05
Duplicate of #9319
Changed in master
GE no longer reports the Git messages if conversion was reported as successful, also if Git had to perform alternative strategies, which can be seen as hiding info

**Comment by RussKie** [comment] 2021-11-09 10:55
You can download the latest dev build and try it out.

**Comment by RussKie** [comment] 2021-11-09 10:55
https://github.com/gitextensions/gitextensions#downloads

**Closed by RussKie** 2021-11-09 10:55 UTC

**Comment by PhiLhoSoft** [comment] 2021-11-09 12:32
OK, I suppose I should not limit my search to open issues… 😁
Thanks.
