### ISSUE TITLE
 System.ComponentModel.Win32Exception (0x80004005)

### ISSUE THREAD

**Issue by giobaxx** [gitextensions/gitextensions#3281] opened 2016-07-27 09:11 UTC
After Installing Visual Studio we have GIT Crashes. We Unistall and reistall but we receive this error again. Wha we can do? 
 
"C:\Program Files (x86)\Git\bin\git.exe" clone -v --recurse-submodules --progress "C:/Users/........................./Desktop/2016-ieee-big-data" "C:/Users/................/Desktop/2016-ieee-big-data/2016-ieee-big-data"

System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GitCommands.GitCommandsInstance.CmdStartProcess(String cmd, String arguments)
   at GitUI.FormProcess.processStart(FormStatus form)

command = C:\Program Files (x86)\Git\bin\git.exe
arguments = clone -v --recurse-submodules --progress "C:/Users/.................../Desktop/2016-ieee-big-data" "C:/Users/.............../Desktop/2016-ieee-big-data/2016-ieee-big-data"

Done

**Comment by KindDragon** [comment] 2016-07-27 09:19
Duplicate of #2934

**Closed by KindDragon** 2016-07-27 09:19 UTC
