### ISSUE TITLE
v4 does not start

### ISSUE THREAD

**Issue by sylvain-bougnoux** [gitextensions/gitextensions#10318] opened 2022-11-03 08:12 UTC
### Environment

- GitExtensions version: v4
- GIT version: 2.33.0
- OS version: win10
- .NET version: install 6.0.402 manually

### Issue description

v3.5.4 worked like a charm. I've uninstalled it and replaced by v4, installation went fine, but nothing start. In a console, it does not say anything.
Nothing happen, dotnet is not asked, no process in the background.

### Steps to reproduce

double click on gitextensions.exe, or from a console.

### Did this work in previous version of GitExtensions?

yes, v3.5.4

**Comment by sylvain-bougnoux** [comment] 2022-11-03 16:27
As proposed by @escherstair, I confirm that installing [.NET Desktop Runtime 6.0.10 x64](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.10-windows-x64-installer) (even if GE is 32-bit application) fixes the issue.

**Comment by gerhardol** [comment] 2022-11-03 19:44
The bootstrapper should display the prompt to install.
If this occurs again (for someone else I assume), Windows logs and current .NET installs would be interesting.

**Comment by gerhardol** [comment] 2022-11-05 19:15
Duplicate of #10337

This issue was opened first, but #10337 has a better description of the issue and the direct links.

**Closed by gerhardol** 2022-11-05 19:15 UTC
Labels: :eyeglasses: status: needs review

**Comment by sylvain-bougnoux** [comment] 2022-11-07 08:29
Do whatever you want, but the issues are a bit different. In my case, there is no popup for downloading dotnet, just nothing, and not in #10337. I guess these are different issues, though the solution (manual install) is the same. Please amend the title or whatever if you want.

**Comment by sylvain-bougnoux** [comment] 2022-11-08 08:32
@RussKie no the msi (installation) went fine. After adding manually dotnet everything was OK, so the installation (not supposed to install dotnet) was correct I guess.
