### ISSUE TITLE
gitextensions freezes

### ISSUE THREAD

**Issue by ghost** [gitextensions/gitextensions#3869] opened 2017-07-24 08:48 UTC
**Do you want to request a *feature* or report a *bug*?**

I want report a bug

**What is the current behavior?**

Currently gitextensions freezes for a long time when reverting a not committed huge merge. (15k files) 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Create a repo and put 15k files in the folder, all about 2kb.
 (A macro/script should do that)

Then in the commit window, select all and click revert/discard

**What is the expected behavior?**

gitextensions freezes

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**

newest 2.50.01

**Comment by RussKie** [comment] 2017-07-24 09:18
Is it faster if you do it via the command line?

**Comment by miterosan** [comment] 2017-07-24 10:23
No, but the window isn't unuseable while git does its work.
gitextensions stays stuck even after git is done,
sooo you need to kill the program with the taskmanager

**Comment by RussKie** [comment] 2017-07-24 13:36
I am unable to replicate the problem.
I generated 15K and 20K files with 2.23K size. I can stage, unstage and reset them without problems. It takes a few seconds and the the app becomes unresponsive but it does come back.
I've tried it on W10 under Parallels on a Mac. I'll try it on another computer later as well.

* Have you experienced the same issue in an earlier version of GE?
* When you think GE is truly hung but before you killed it, can you run `git status | grep 'new file:' | wc -l` command and see where you're at?
* Is there some magic number of files when it starts exhibiting the problem? E.g. works for 10K files, but completely locks up for 12K files...

**Comment by pmiossec** [comment] 2017-07-24 19:36
I never experienced such behavior. It takes time but always end after some wait. 

But I learned that, in the special case where **All** the changes should be reseted, it is much faster to do a 'Reset hard' on the actual commit. 

That way, gitextensions is telling git to reset all the files instead of doing it file by file...

**Comment by phillijw** [comment] 2017-08-08 14:18
This has been a bug for years, definitely not new. The issue is that it's looping through each file, I think. If you select all files, right-click, and do a regular Reset, this is definitely an issue. It might not be an issue if you "Reset all changes" though. We should clarify which one (or both) it is in this case.

**Comment by miterosan** [comment] 2017-08-08 19:35
@KussKie
1. didn't try with a older version
2. well, it is a private at my company, so I' not allowed to share that info
3. no

@phillijw
it is a regular reset

**Comment by phillijw** [comment] 2017-08-08 19:40
I don't know what "a regular reset" is. Please identify the exact steps to reproduce in your case

**Comment by miterosan** [comment] 2017-08-08 19:45
@phillijw 
refering to your answer:
"If you select all files, right-click, and do a regular Reset, this is definitely an issue."

strg + a 
rightclick one file
reset file (the first option in the selection )

**Comment by phillijw** [comment] 2017-08-08 19:55
Does the same thing happen if you simply use the "Reset all" button on that screen? It's effectively the same as selecting all and right-click resetting except it may be more performant

**Comment by miterosan** [comment] 2017-08-08 19:58
Did not try yet.
I'll try that tommorow, I'm currently at my mobile

2017-08-08 21:56 GMT+02:00 Joe Phillips <notifications@github.com>:

**Comment by RussKie** [comment] 2017-08-08 23:21
On 09/08/2017 5:35 AM, "miterosan" <notifications@github.com> wrote:
>
> @kusskie
>
> 1. didn't try with a older version
> 2. well, it is a private at my company, so I' not allowed to share that
info
> 3. no

2. I didn't ask to share anything, I asked to check
3. So does it lock up for 1,000 files too?

**Comment by RussKie** [comment] 2017-08-10 10:59
I wonder if it is related to #2478

**Comment by RussKie** [comment] 2017-08-18 13:38
Possibly a duplicate of #3280

**Comment by RussKie** [comment] 2017-12-13 22:06
Closing due to lack of follow up

**Closed by RussKie** 2017-12-13 22:06 UTC
Labels: info needed
