### ISSUE TITLE
AppSetting.DefaultPullAction must not be set by FormPush and GitUICommands

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5407] opened 2018-09-07 21:32 UTC
**Do you want to request a *feature* or report a *bug*?**
regression bug, code review

**What is the current behavior?**
`AppSetting.DefaultPullAction` is modified at least by `FormPush.HandlePushOnExit()` and `GitUICommands.UpdateSettingsBasedOnArguments()` as well.
`FormPull`'s behavior depends on `AppSetting.DefaultPullAction`.

This is the more important regression reported in #5374 which is not addressed by the appreciated replacement #5401 of `Set the next selection as default`.

The common handler `PullToolStripMenuItemClick` is not used for all of the pull menu items -- looks like unfinished refactoring, especially for `fetchAll` and `fetchPruneAll`.

Should all these handlers be kept which just call the generic handler?
```C#
private void ToolStripButtonPullClick(object sender, EventArgs e)
{
    PullToolStripMenuItemClick(sender, e);
}
```

`FormPull` has lost its default selection:
![grafik](https://user-images.githubusercontent.com/36601201/45243980-21965780-b2f6-11e8-95a2-59983ccd92a4.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Set `AppSetting.DefaultPullAction = AppSettings.PullAction.FetchAll`.
Then `Fetch` will run
`git.exe pull --progress "origin"`.
Instead it must be
`git.exe fetch --progress "origin"`.

**What is the expected behavior?**
Only the new submenu `default Pull button action` introduced by #5401 shall set `AppSetting.DefaultPullAction`.
Only the `click` handler of the `Pull` toolbar button shall evaluate `AppSetting.DefaultPullAction`.
`AppSetting.DefaultPullAction` shall only affect what will happen when this toolbar button is pushed.

`FormPull`, `FormPush` (sic!) and `GitUICommands` should neither evaluate nor even set `AppSetting.DefaultPullAction`.
Maybe another `AppSetting` should be added to remember the default in `FormPull`.

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 2.17.1.w.2-x64
- OS version: Windows 7
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**
2.51

**Comment by RussKie** [comment] 2018-09-08 21:31
I disagree that the dialog's option should be linked with the dropdown selection.
It makes it confusing from the UX and complex from the implementation perspective. 
The form should be remembering user's choices though.

**Comment by gerhardol** [comment] 2018-09-08 21:33
> I disagree that the dialog's option should be linked with the dropdown selection.

Then we should have changed that in #5412 ...
(right now that should be to always set Fetch)

**Comment by RussKie** [comment] 2018-09-08 21:35
Hence my point of confusion 🤣 I am confused

**Comment by vbjay** [comment] 2018-09-08 21:38
I think having to click a radio button to get a pull is fine.  It does a
fetch if I just hit pull.  I am opting in to the actual merge/rebase.

**Comment by vbjay** [comment] 2018-09-08 21:39
I do think think the other options besides what type of action(pull/merge,
pull/rebase, fetch) should be remembered.  If I check auto stash, it should
be checked next time.

**Comment by gerhardol** [comment] 2018-12-31 18:33
Duplicate of #5420

**Closed by gerhardol** 2018-12-31 18:33 UTC
Labels: type: regression
