### ISSUE TITLE
Feature: Right click to delete Remote Branch from server

### ISSUE THREAD

**Issue by XopherThomas** [gitextensions/gitextensions#3890] opened 2017-08-08 16:50 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current behavior?**
In our current workflow we regularly push integration/jira-nnn branches to the server for an automated build server to validate, before rebasing onto master.  Deleting a remote branch from the server is cumbersome in the UI, requiring:
1. open the Push dialog
2. select Push Multiple Branches tab
3. uncheck any selected Push check boxes
4. search the (potentially very) long list for the right branch
5. check Delete Remote Branch checkbox for the right branch
6. Push

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Feature request not a bug.

**What is the expected behavior?**
The desired behavior is to right click on a commit with server side remote branch and select "Delete Remote Branch.  A selection dialog should be popped up if multiple remote branches exist to select one.
I currently implement this with a script as:
Name: Delete Remote Branch
Add to revision grid context menu: Checked
Command: `bash`
Arguments: `-c "git push origin --delete $(echo {sRemoteBranch} | sed 's/origin\///')"`

**Environment you encounter the issue:**

- GitExtensions version: Git Extension 2.50.01
- GIT version: Git 2.13.2.windows.1
- OS version: Windows 7

**Did this work in previous version of GitExtensions (which)?**
N/A

**Comment by vbjay** [comment] 2017-08-08 21:03
Did you not see the delete branch dialog?

**Comment by XopherThomas** [comment] 2017-08-08 21:29
@vbjay If this is already available somewhere I have missed it.  The generic Delete branch dialog I have seen only allows deleting local branches and shows on knowledge of remote serve side branches.

**Comment by vbjay** [comment] 2017-08-08 21:41
Sorry.  I recently used the delete ta window and confused the two in my mind.  

![image](https://user-images.githubusercontent.com/3629489/29095969-cb5f7e54-7c60-11e7-9450-81a1f4b8ca41.png)

**Comment by RussKie** [comment] 2017-08-08 23:27
This would be useful, its absence annoys me too.
I tend to resort to bash to delete `git push fork :branchname`

**Comment by XopherThomas** [comment] 2017-08-09 15:04
@RussKie Yes, a useful option which I resorted to when my script was failing with the new Console Emulator functionality, but even that gets tedious when our branch names are integration/nn.nn/username/feature_name_description_jira_nnn.

**Comment by MattLichter** [comment] 2017-08-30 13:23
👍

I also use the custom scripts feature to implement this (`git push --delete {cDefaultRemote} {sLocalBranch}`).  Works for most basic situations but is still limited (e.g. doesn't work if I don't check the branch out locally).  I'm not a bash power user so I never would have came up with the command in the original post.  A built-in button/menu item would be great.

**Comment by vbjay** [comment] 2017-08-30 13:29
I frankly think it shouldn't be easy. I think the push dialog and delete
branch dialog are fine. It shouldn't be super easy to delete a remote
branch.

**Comment by MattLichter** [comment] 2017-08-30 13:45
Thanks for the quick response.

I guessed that it might be a safety philosophy, which I understand.  Just one question then - why is the option available when deleting remote tags?  It would seem the same philosophy applies there...

Oh, and awesome piece of software.  Been using it since 2012 and recommend to all my colleagues.  I can practically navigate the menus in my sleep :).  Thank you for the great work!

**Comment by vbjay** [comment] 2017-08-30 13:51
Branches are more fluid than tags.  Tags tend to only be deleted if moving
from one commit to another.  Branches move all the time.  Tags are used for
things like version releases.  They can be deleted without much worry.
Delete a branch and lose the commits in it over time is not a fun
experience.  Git does clean up dangling commits over time.

**Comment by MattLichter** [comment] 2017-08-30 13:54
Gotcha, makes sense.  Thanks again :)

**Comment by XopherThomas** [comment] 2017-08-30 17:51
I do agree that it shouldn't be Too easy, but even a confirmation dialog might be a slight mitigation.  With the bash script approach, I do not have the option of a confirmation though.  The 6 step manual process originally described in the feature request is cumbersome though for using the UI only.  It does appear that not every git user uses branches in the same way though.  Our branches are much more volatile, since we use them as a simple integration method.

**Comment by XopherThomas** [comment] 2017-08-30 17:52
If this feature is implemented, an explicit block for deleting the remote master branch might be useful.

**Comment by KindDragon** [comment] 2017-08-31 19:57
Duplicate of #1583

**Closed by KindDragon** 2017-08-31 19:57 UTC
Labels: feature-request
