### ISSUE TITLE
[NBug] Illegal characters in path.

### ISSUE THREAD

**Issue by SBulatovaite** [gitextensions/gitextensions#8364] opened 2020-07-30 09:51 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at GitCommands.FullPathResolver.Resolve(String path)
   at GitUI.FileStatusList.FileStatusListView_MouseMove(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at GitUI.UserControls.ExListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
In the commit window click Assume Unchanged on files then Open the commit window again, select Working directory changes -> Show Assumed Unchanged files. Select or right click any of the files.

## Environment
- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2020-07-30 10:35
Probably duplicate of #6946 
There are changes here since that report though

**Comment by RussKie** [comment] 2020-10-04 12:35
@SBulatovaite is this reproducible?

Overall I don't expect this specific error to remain an issue once we migrated to .NET 5.0 due to underlying changes in System.IO API.

**Closed** 2020-11-08 16:58 UTC
Labels: :construction: status: in progress, :mailbox_with_no_mail: needs: author feedback, :zzz: status: no recent activity, potential-duplicate
