### ISSUE TITLE
Build report tab unusable

### ISSUE THREAD

**Issue by QuAzI** [gitextensions/gitextensions#10080] opened 2022-07-22 11:33 UTC
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.37.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.9035.0
- DPI 120dpi (125% scaling)

### Issue description

Build Report tab requires login to GitLab through IE but always refreshes page before you can input credentials

### Steps to reproduce

- enable build server integration with GitLab Pipeline
- open Build Report tab

![image](https://user-images.githubusercontent.com/1897605/180430215-c77e0fc4-4385-40b6-a354-c0e278520190.png)

**Comment by QuAzI** [comment] 2022-07-22 13:20
IE used even if default browser is different. And IE11 absolutely can't show GitLab pages now.

**Comment by pmiossec** [comment] 2022-07-22 15:14
Not sure to fully understand your wish, so I will ask some questions...

GitExtensions doesn't support GitLab pipeline. Did you developed it?

Because there is a property on the `BuildInfo` named `ShowInBuildReportTab` to set to `false` when the embedded browser is not able to display the report (for multiple reasons).

And it will display a link to open in the webbrowser:

![image](https://user-images.githubusercontent.com/460196/180467835-c14c10d9-ad6c-46df-a65b-76a228121de9.png)

If your request is to update the embedded web browser, it's a duplicate of #8328

But as said [here](https://github.com/gitextensions/gitextensions/issues/9423#issuecomment-888342638):

> Could be reevaluated now that switch to dotnet core is in progress.
> But as said, IE component is not used a lot so not high priority....
> 
> You could hide the report and instead use the contextual menu item to open the report:
> ![image](https://user-images.githubusercontent.com/460196/127337324-dabb3086-c2bb-4e2c-ba2d-06dda2d90323.png)

It needs to be done by someone interested and shipping the browser display engine will increase a lot the size of the setup...

**Comment by QuAzI** [comment] 2022-07-25 05:15
> GitExtensions doesn't support GitLab pipeline

Sorry?
![image](https://user-images.githubusercontent.com/1897605/180702987-945a9041-1fa2-4e88-bfc7-f0c8f9615a7c.png)

> If your request is to update the embedded web browser

Looks like yes. But `GitLab commit hint` and `Jira commit hint` also broken. I am not sure is it still about browser integration. Looks like no one integration works properly
![image](https://user-images.githubusercontent.com/1897605/180703224-0a2af869-fc80-4dba-869d-5399682c87db.png)
![image](https://user-images.githubusercontent.com/1897605/180703236-19004fd6-3618-4b0d-8298-6725f4f547e1.png)

**Comment by gerhardol** [comment] 2022-07-25 09:28
> > GitExtensions doesn't support GitLab pipeline
> 
> Sorry?

Separate plugin with a separate repo (and issue list), available in plugin manager:

https://github.com/martin211/GitExtensions.GitLabPipelinesPlugin
or
https://github.com/ahmeturun/GitExtensions.GitLab

> > If your request is to update the embedded web browser
> 
> Looks like yes. But `GitLab commit hint` and `Jira commit hint` also broken. I am not sure is it still about browser integration. Looks like no one integration works properly 

GitLab commit hint likely:
https://github.com/martin211/GitExtensions.GitLabCommitHintPlugin

Jira Commit hint is not in next version (maybe not working in 3.5 either, cannot test to Jira).

**Comment by QuAzI** [comment] 2022-07-25 11:56
@martin211 @ahmeturun

**Comment by RussKie** [comment] 2022-07-25 12:26
@QuAzI please raise issues directly with the plugin authors. Thank you.

**Closed by RussKie** 2022-07-25 12:26 UTC
Labels: type: feature request, :neckbeard: status: pull request only
