### ISSUE TITLE
JiraCommitHint Plugin is throwing assembly loading error

### ISSUE THREAD

**Issue by namtab00** [gitextensions/gitextensions#6291] opened 2019-02-21 19:13 UTC
## Current behaviour

JiraCommitHint Plugin is throwing assembly loading error:
```
System.TypeInitializationException: The type initializer for 'NString.StringTemplate' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at NString.Internal.Cache`2..ctor()
   at NString.StringTemplate..cctor()
   --- End of inner exception stack trace ---
   at NString.StringTemplate.GetTemplate(String template)
   at JiraCommitHintPlugin.JiraCommitHintPlugin.<>c__DisplayClass40_0.<GetMessageToCommitAsync>b__0(Issue issue)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at JiraCommitHintPlugin.JiraCommitHintPlugin.<GetMessageToCommitAsync>d__40.MoveNext()
```

## Expected behaviour
commit hint should load correctly

## Screenshots

![image](https://user-images.githubusercontent.com/995900/53194995-fc33a680-3614-11e9-8f93-22b5def72e63.png)

## Did this work in previous version of GitExtensions

Yes: previous official release

## Environment
- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2019-02-21 20:57
Duplicate of #6154

**Closed by RussKie** 2019-02-21 20:57 UTC
