### ISSUE TITLE
Commit window displays file from other repository

### ISSUE THREAD

**Issue by mrkanaly** [gitextensions/gitextensions#5105] opened 2018-06-21 19:53 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When opening the commit window, a file that is new in the opened repository is listed, but the contents are from a file in a different repository on the PC file system.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

It appears to be dependent on the path of the file in the repo. modifications to the subdirectory name or removing it correct the behavior. 

![image](https://user-images.githubusercontent.com/1037119/41741739-cc316eca-7550-11e8-85e0-d2db8468f302.png)
Possibly related, handles are being held by git extensions in a repository that is not open.
![image](https://user-images.githubusercontent.com/1037119/41741817-0360f596-7551-11e8-8b35-45e136d012d2.png)

**What is the expected behavior?**
The contents of the file in the repository should be displayed
**Environment you encounter the issue:**
- GitExtensions version: 2.51.02
- GIT version: git version 2.12.2.windows.2
- OS version: Windows 7
- .NET version: 
![image](https://user-images.githubusercontent.com/1037119/41741876-341e6b1e-7551-11e8-9d33-4365e86ee4b2.png)

**Did this work in previous version of GitExtensions (which)?**
One case reports correct behavior with 2.51.01, and other with the same bad behavior on 2.51.01

**Comment by RussKie** [comment] 2018-06-23 14:58
Any steps to reliably reproduce the behaviour?

**Comment by vbjay** [comment] 2018-06-23 15:00
Work trees maybe?

**Comment by mrkanaly** [comment] 2018-06-23 19:57
When observed, the steps were just to open git extensions and it was occurring. If I created the exact repo structure, opened one, then switched to the other (in some order), it would happen for me. 

I have been attempting to make it occur in other test scenarios, with only some marginal success. It had seemed that the repository path itself was irrelevant, but it would occur if the filename and path inside the repo matched as shown. When it was occurring, it would always be that there some other handles being held on previously opened repositories. Maybe there was some leftover part of GE that was stuck looking at another repo's contents because of a resource contention or something. 

Will continue to report if something more reliable comes up to recreate.

**Comment by RussKie** [comment] 2018-11-14 10:23
Any news on this? Is this still happening?

**Comment by mrkanaly** [comment] 2018-11-20 04:33
I don't have any particular updates, other than I can try to reproduce the exact scenario as reported again.

**Comment by RussKie** [comment] 2019-01-07 08:00
Closing due to age and lack of follow up.

**Closed by RussKie** 2019-01-07 08:00 UTC
Labels: status: more info requested
