### ISSUE TITLE
System.NullReferenceException on Push

### ISSUE THREAD

**Issue by pgarbo** [gitextensions/gitextensions#7205] opened 2019-09-27 13:20 UTC
## Current behaviour

Clicking Push button on main toolbar causes System.NullReferenceException (approx 50% times). Previous version worked fine.

## Expected behaviour

Push button should open Push Dialog

## Steps to reproduce

Click Push button on main toolbar

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitHub3.GitHub3Plugin.GetHostedRemotesForModule()
   at GitHub3.GitHub3Plugin.GitModuleIsRelevantToMe()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at GitUI.CommandsDialogs.FormPush.FormPushLoad(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at GitUI.GitExtensionsForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3460.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-09-27 15:20
Duplicate of #7193

**Comment by pmiossec** [comment] 2019-09-27 15:36
I was trying to fix it but I don't reproduce :(
And looking at the code, I don't understand what object is null...

>Clicking Push button on main toolbar causes System.NullReferenceException (approx 50% times). 

Could you tell me how do you open the push form:
1. from the main window of GitExtensions?
2. from the explorer?

**Comment by pmiossec** [comment] 2019-09-27 16:01
Could you test the result of  #7206.

The package to test will be [here](https://ci.appveyor.com/project/gitextensions/gitextensions/builds/27720719/artifacts) when the build will be finished...

**Comment by pgarbo** [comment] 2019-09-27 16:08
> I was trying to fix it but I don't reproduce :(
> And looking at the code, I don't understand what object is null...
> 
> > Clicking Push button on main toolbar causes System.NullReferenceException (approx 50% times).
> 
> Could you tell me how do you open the push form:
> 
> 1. from the main window of GitExtensions?
> 2. from the explorer?

from the main window of GitExtensions

**Comment by pmiossec** [comment] 2019-09-27 18:35
If you could take the time to unzip the archive file **in a new folder** (because that's a portable version) and test it, it will really help.

**Comment by RussKie** [comment] 2019-09-28 09:06
Is it happening consistently?
Is it happening to all repos or only in a specific repo?

If you could provide more info on your configurations, e.g. remotes etc, that could help us in debugging the issue - it would be great.

**Comment by pgarbo** [comment] 2019-09-30 08:43
> Is it happening consistently?
> Is it happening to all repos or only in a specific repo?
> 
> If you could provide more info on your configurations, e.g. remotes etc, that could help us in debugging the issue - it would be great.

No, it is not consistent. I was using 2 repos - one Github one internal on TFS and it happened on both. Today so far it did not happen, once it starts to happen it is happening more frequently. I will try to replicate again and then will try to check on a 3.3.0.6698 build.

**Comment by pgarbo** [comment] 2019-09-30 09:03
Update:
I managed to replicate the issue - it started to happen on tfs repository, while working fine on github repo. I'm able to replicate the issue consistently now. I've ran version 3.3.0.6698 and I was not able to replicate, everything seems to be working fine.

**Comment by RussKie** [comment] 2019-10-01 13:14
> I've ran version 3.3.0.6698 and I was not able to replicate, everything seems to be working fine.

Thank you for the follow up. I'm going to close this issue then.
Please let us know if the issue comes back.

**Comment by pmiossec** [comment] 2019-10-01 13:29
>Thank you for the follow up. I'm going to close this issue then.

@RussKie So, what do we do. I rewrite my commit message of #7206 and we merge? It couldn't be bad, anyway...

**Comment by RussKie** [comment] 2019-10-01 13:36
Ah sorry, my bad. I didn't realise there was an open PR (it's almost midnight here).

**Closed** 2019-10-01 13:37 UTC
Labels: :beetle: type: bug, area: plugins, potential-duplicate
