### ISSUE TITLE
GitExtensions doesn't start when git is not installed

### ISSUE THREAD

**Issue by sascfuel** [gitextensions/gitextensions#5751] opened 2018-11-12 14:34 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If I start GitExtensions without Git installed I get the following exception.
> System.TypeInitializationException
The type initializer for 'GitCommands.ExecutableExtensions' threw an exception.

After closing the exception dialog GitExtensions gets closed too.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
As I tried to check the msi installation for #5750 I installed GitExtension on a clean Win10 image with nothing except NET Framework installed.
I started GitExtensions selected the language and got the exception. 

After I installed git-scm GitExtensions is working.

**What is the expected behavior?**
GitExtensions starts and tells me in the settings window that git can not be found, as it did in version 2.51

**Environment you encounter the issue:**

- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3190.0
- DPI X:100.00% Y:100.00%

**Did this work in previous version of GitExtensions (which)?**
Yes, 2.51.05

**Comment by gerhardol** [comment] 2018-11-12 15:51
duplicate of #5562

**Closed by gerhardol** 2018-11-12 15:51 UTC
