### ISSUE TITLE
Commit selection jumping unpredictable

### ISSUE THREAD

**Issue by smollgreymouse** [gitextensions/gitextensions#7122] opened 2019-09-11 11:22 UTC
## Current behaviour

After any branch switching or pull, selected commit is changed unpredictable.

## Expected behaviour

After any operation, selection must stay at the same commit, except of the case when selected commit is deleted (squash, etc)

## Steps to reproduce

After checkout branch or pull operation, randomly, the commit selection is changed to the random commit that is many commits ago from the head that was selected before operation.

## Did this work in previous version of GitExtensions

Several releases ago, don't remember exactly.

## Environment

- GitExtensions version: 3.1.1.6049
- GIT version: 2.23.0.windows.1
- OS version: Microsoft Windows NT 10.0.17763.0
- .NET version:  4.7.3416.0

**Comment by mstv** [comment] 2019-09-11 20:20
duplicate of #6663

**Closed by mstv** 2019-09-11 20:20 UTC
