### ISSUE TITLE
Push form: advanced options UI broken

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#9402] opened 2021-07-21 21:18 UTC
## Current behaviour

UI broken when trying to display advanced options of Push form.

## Expected behaviour

The options are well displayed

## Steps to reproduce

1. Open Push form
2. Click on "Options" link
3. See that options are not displayed.

## Screenshots

![GE_broken_push_options](https://user-images.githubusercontent.com/460196/126561301-8d587f46-00f7-41cf-b1bd-25138517d48f.gif)

## Did this work in previous version of GitExtensions

Yes. Last commit before dotnet 5 migration.
Broken in last `master` (Broken in portable version downloaded and custom version built).
Not tested in between.

## Environment

- Git Extensions 3.6.0.12349
- Build cd34d45c6a1d56e4497257898e2095dea70425a6 (Dirty)
- Git 2.28.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET 5.0.8
- DPI 192dpi (200% scaling)

## Diagnostics

dotnet 5?

**Comment by mstv** [comment] 2021-07-21 21:36
I guess it is caused by scaling - works for me at 100%.
The dialog is resizeable.
😉 And:
![image](https://user-images.githubusercontent.com/36601201/126563291-249f909f-ff9f-4ebc-bb0a-8815cec626d1.png)

**Comment by pmiossec** [comment] 2021-07-21 21:43
>I guess it is caused by scaling - works for me at 100%.

I try to fix it but after quite some tries no success :(

>The dialog is resizeable.

I know but does not help. The controls seems to be moved in top left.

> And:

I have this option enabled but that doesn't change the problem, the form is directly displayed blank.
Screenshot was made with portable version that's why I get the link and it is better to show the problem.

**Comment by mdonatas** [comment] 2021-08-03 08:45
Few observations
- This happens with both a 125% scaling and a 200% scaling (and I would assume any other scaling)
- `Location` seems to be the culprit
Changes in `/GitUI/CommandsDialogs/FormCreateBranch.Designer.cs`
```diff
- this.tableLayoutPanel1.Location = new System.Drawing.Point(9, 9);
+ //this.tableLayoutPanel1.Location = new System.Drawing.Point(9, 9);
```
and `/GitUI/CommandsDialogs/FormPush.Designer.cs`
```diff
- this.PushOptionsPanel.Location = new System.Drawing.Point(8, 40);
+ this.PushOptionsPanel.Location = new System.Drawing.Point(8, 37);
```
either fix the problem or at least make these forms more usable

**Comment by mdonatas** [comment] 2021-09-14 16:10
Anyone has any clues what could be causing this? I sure hope it's not caused by WinForms on .net core as I've tried running GE on current 6.0 preview and the problem is still there and prod release is soon.

**Comment by RussKie** [comment] 2021-09-15 07:12
This is likely an underlying Windows Forms runtime issue.

**Comment by mdonatas** [comment] 2021-09-15 08:04
> 
> 
> This is likely an underlying Windows Forms runtime issue.

Thanks a million for putting in the work to investigate and even create the issue in winform repo! 💪

**Comment by RussKie** [comment] 2021-09-15 13:50
That's my job 😉 Not the area of my expertise though, so my colleague will have to dig in.

**Comment by gerhardol** [comment] 2022-01-02 01:31
@RussKie What is the status on this, seem to be what is left that blocks 4.0

**Comment by RussKie** [comment] 2022-01-02 02:09
This still hasn't been fixed in either .NET 5, 6 or 7 AFAIK.

**Comment by pmiossec** [comment] 2022-01-28 16:33
I don't know if it's for the same reason but pull form (that I never use) is also broken in `master` (The 2 buttons are not visible):

![image](https://user-images.githubusercontent.com/460196/151585286-5067c0c3-c407-4af6-a507-08f5fd1fb65f.png)

**Comment by mstv** [comment] 2022-01-28 18:41
At 100%, I can see all the button. But I must resize the window once. The size is persisted.

**Comment by RussKie** [comment] 2022-04-03 11:00
> Delete branch form is also impacted:
> 
> ![image](https://user-images.githubusercontent.com/460196/139021987-6b2d2de2-d940-4c07-b7b0-1d0b710fc376.png)

I'm not seeing this in .NET 6 branch, here's how it looks at 125%:
![image](https://user-images.githubusercontent.com/4403806/161424511-82c6f2cc-f737-4b9c-9650-b11c3214e661.png)

**Comment by RussKie** [comment] 2022-04-03 11:07
> ## Screenshots
> ![GE_broken_push_options](https://user-images.githubusercontent.com/460196/126561301-8d587f46-00f7-41cf-b1bd-25138517d48f.gif)

I'm also not seeing the original issue either in .NET 6 branch (125% or 200%):
![image](https://user-images.githubusercontent.com/4403806/161424631-bb57513e-8e59-472b-9474-adc155572fc0.png)
![image](https://user-images.githubusercontent.com/4403806/161424798-79529de2-10ef-4671-a0a9-3a2ed3fe4a07.png)

There are some artifacts that need to be fixed, but I think the underlying issue may have been fixed (or greatly mitigated).

**Closed** 2022-04-19 08:41 UTC
Labels: type: dependency bug, area: hdpi, type: regression, :construction: status: in progress, .NET migration
