### ISSUE TITLE
Problem with new right click - "Delete Remote Branch" on non existent remote banches

### ISSUE THREAD

**Issue by erikleo** [gitextensions/gitextensions#4847] opened 2018-04-16 20:44 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If you try to delete a remote branch that is in Git Extensiton but is non existent on remote, you will get the error:
"C:\Program Files\Git\bin\git.exe" push origin  :"branchName"
error: unable to delete 'branchName': remote ref does not exist
error: failed to push some refs to 'https://*******s.git'
Done

and the non existent remote repo will remain in GE

This is inconsistent with the behavior of "Push Multiple Branches"  when you check the  "Delete Remote Branch" option

"C:\Program Files\Git\bin\git.exe" push --progress  "origin" :refs/heads/branchName
remote: warning: Deleting a non-existent ref.
To https://bbgithub.dev.bloomberg.com/eleo7/bof-excel-options.git
 - [deleted]         branchName
Done

Which will actually delete the branch from GE

**What is the expected behavior?**
In this case the non existant remote should be removed from GE

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 
- OS version: 

**Did this work in previous version of GitExtensions (which)?**
no, this is a recent feature

**Comment by RussKie** [comment] 2018-04-16 22:08
Duplicate of #4356

**Closed by RussKie** 2018-04-16 22:08 UTC
