### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by JerkerPihl** [gitextensions/gitextensions#10904] opened 2023-04-21 18:41 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.40.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.14
- DPI 96dpi (no scaling)

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at int GitUI.FileStatusList.GetNextIndex(bool searchBackward, bool loop)+ContainsSearchableItem(ListViewGroup group)
   at int GitUI.FileStatusList.GetNextIndex(bool searchBackward, bool loop)+FindNextItemInGroups()
   at int GitUI.FileStatusList.GetNextIndex(bool searchBackward, bool loop)
   at bool GitUI.CommandsDialogs.RevisionDiffControl.GetNextPatchFile(bool searchBackward, bool loop, out int fileIndex, out Task loadFileContent)
   at async Task<TextRange> GitUI.FindAndReplaceForm.FindNextAsync(bool viaF3, bool searchBackward, string messageIfNotFound)
   at async void GitUI.FindAndReplaceForm.btnFindNext_Click(object sender, EventArgs e)+(?) => { }
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

search for a word that didnt exist

### Steps to reproduce

Search for a word in code window for a word that dont exist

**Comment by gerhardol** [comment] 2023-04-21 20:42
Duplicate of #10694 
Fixed in #10716 in upcoming 4.1

**Closed by gerhardol** 2023-04-21 20:42 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
