### ISSUE TITLE
[NBug] Unable to parse object ID "a".

### ISSUE THREAD

**Issue by argorain** [gitextensions/gitextensions#8848] opened 2021-02-12 10:40 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Current behaviour

Crash

## Steps to reproduce

I just returned from submodule after Fetch and Prune all, then checkout to origin/master.

## Error Details
```
System.FormatException: Unable to parse object ID "a".
   at GitUIPluginInterfaces.ObjectId.Parse(String s)
   at GitCommands.GitModule.GetFileBlobHash(String fileName, ObjectId objectId)
   at GitUI.Editor.FileViewer.ViewGitItemRevisionAsync(GitItemStatus file, ObjectId revision, Action openWithDifftool)
   at GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, String defaultText, Action openWithDiffTool)
   at GitUI.CommandsDialogs.RevisionDiffControl.<ShowSelectedFileDiffAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.RevisionDiffControl.<<DiffFiles_SelectedIndexChanged>b__36_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
I just returned from submodule after Fetch and Prune all, then checkout to origin/master.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.2.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2021-02-13 23:30
Duplicate of #8583

**Closed by gerhardol** 2021-02-13 23:30 UTC
