### ISSUE TITLE
[NBug] Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by cforbin1** [gitextensions/gitextensions#8607] opened 2020-11-09 18:46 UTC
## Current behaviour
[Commit] button results in exception thrown when reviewing an uncommitted "conflicts resolved" merge from an origin branch to a subordinate branch.

(By "origin" branch, I mean a branch that the subordinate came from.  For example, if you have the main trunk, then a release branch off of it, and a feature branch off of that, then then "release" branch is the origin for the subordinate "feature" branch.)

I had a merge pending from the release branch to the feature branch and wanted to review before commiting.
(Following the commit I planned to make more feature changes and then merge back to the release.)

## Expected behaviour
After performing the merge (without commit), the [Commit] button should allow me to review the commit normally, before, er... "committing" to doing it.

## Steps to reproduce

0. Start with master or a branch off of it.  Ensure there's some files with some code.
1. Create a release branch off of there.
2. Make some revisions.  Note where you left off.  (Maybe tag it... though my case did NOT involve a tag.)
3. Throw a feature branch off of your release branch.
4. Make some revisions.
5. Switch back to the release branch and make some revisions there.
6. "Upmerge" the tip of the release branch to the feature branch;resolve conflicts; DO NOT COMMIT.
7. Observe you have an outstanding commit with several elements.
8. Click the [Commit] button to review before committing.
9. BOOM!  Receive Exception.

## Error Details
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GitUI.SpellChecker.EditNetSpell.Line(Int32 line)
   at GitUI.CommandsDialogs.FormCommit.<FormatAllText>g__SetFormattedLine|208_3(Int32 lineNumber, <>c__DisplayClass208_0& )
   at GitUI.CommandsDialogs.FormCommit.FormatAllText(Int32 startLine)
   at GitUI.CommandsDialogs.FormCommit.FormatAllText(Int32 startLine)
   at GitUI.CommandsDialogs.FormCommit.Message_TextChanged(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   at GitUI.SpellChecker.EditNetSpell.TextBoxTextChanged(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   at System.Windows.Forms.TextBoxBase.OnTextChanged(EventArgs e)
   at System.Windows.Forms.TextBoxBase.WmReflectCommand(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.RichTextBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.RichTextBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Please message me if more information is needed.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.2.windows.2
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3690.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2020-11-15 19:07
Duplicate of #7614 

The exception is due to the formatting of the commit message.
There are checks already for the size, so it is not clear how this occurs.
The actual commit message could be interesting, but it is likely something else that causes the exception (I cannot reproduce).

**Closed by gerhardol** 2020-11-15 19:07 UTC
