### ISSUE TITLE
[NBug] Using username "git".^C

### ISSUE THREAD

**Issue by gsenginerd** [gitextensions/gitextensions#10687] opened 2023-01-29 15:57 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.13
- DPI 96dpi (no scaling)

### Issue description

Exit code: -1073741510
Command: cmd.exe
Arguments: /k ""C:\Program Files\PuTTY\plink.exe" -T "git@ssh.dev.azure.com:v3/HL-Applications/HCG/hcg-hl_data-snowflake-db""

```
GitExtUtils.ExternalOperationException: Using username "git".
^C
 ---> System.Exception: Using username "git".
^C
   --- End of inner exception stack trace ---
   at async Task<bool> GitUI.Infrastructure.Plink.ConnectAsync(string host)
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

I am getting this error when ever I try to any do a fetch.

### Steps to reproduce

Clone a repo using SSH
Do a pull or a fetch

### Did this work in previous version of GitExtensions?

It did, a recent upgrade broke it

**Comment by mstv** [comment] 2023-01-29 16:20
Do you hit `Ctrl+C` or kill the console window?
Rather press `Enter`.
`cmd.exe /k` is gracefully exited by typing "exit" and `Enter`.

Duplicate of #10543

**Closed by mstv** 2023-01-29 16:20 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
