### ISSUE TITLE
Fetch all remotes does not work!

### ISSUE THREAD

**Issue by mrezabayat** [gitextensions/gitextensions#10520] opened 2022-12-13 16:50 UTC
### Environment

- GitExtensions version: 4.0.0.15569
- GIT version: 2.39.0.windows.1
- OS version: Windows 10 - version 21H2 - Build 19044.2251
- .NET version: 4.5.51641

### Issue description

When I try to do "Fetch all remotes" I get this error:

"C:\Program Files\Git\bin\git.exe" fetch --progress --jobs=0 "--all"

BUG: run-command.c:1521: you must provide a non-zero number of processes!
Done

### Steps to reproduce

Try to Fetch a remote repository.

### Did this work in previous version of GitExtensions?

It was working with the previous version of git, this is happening since I updated the git.

**Comment by gerhardol** [comment] 2022-12-13 16:55
Duplicate of #10514

**Closed by gerhardol** 2022-12-13 16:55 UTC
Labels: :eyeglasses: status: needs review
