### ISSUE TITLE
Windows 10 Error

### ISSUE THREAD

**Issue by testboarder** [gitextensions/gitextensions#6581] opened 2019-05-16 13:03 UTC
## Current behaviour

When I launch portable version 3.1.0.5877 on Windows 10 I get an error. The screenshot of the error can be viewed here: https://monosnap.com/file/R2xm8Mc1DtuKMtITVmin29Hw1smArf

Portable version 3.00.00.4433 works fine on the same computer.

## Expected behaviour

No error when the portable version is launched.

## Steps to reproduce

Install version 3.1.0.5877 (https://github.com/gitextensions/gitextensions/releases/download/v3.1/GitExtensions-Portable-3.1.0.5877.zip) on Windows 10.

## Screenshots

https://monosnap.com/file/R2xm8Mc1DtuKMtITVmin29Hw1smArf

## Did this work in previous version of GitExtensions

I have portable version 3.00.00.4433 running on the same computer without any problems.

## Environment

- GitExtensions version:
- GIT version: 2.14.2..3
- OS version: Windows 10
- .NET version: .NET Core SDK 2.1.104 (x64), .NET Framework 4.5.1 SDK, .NET Framework 4.5.2 Multi-Targeting Pack (ENU)

**Comment by pmiossec** [comment] 2019-05-16 13:13
It is better if you could include the screenshot directly in the issue (by copy/paste or drag & drop).
That way, that's easier to read (and I don't want to click on link toward site I don't know)

**Comment by RussKie** [comment] 2019-05-16 13:49
Duplicate of #6562

**Comment by RussKie** [comment] 2019-05-16 13:50
Your git is too old.
You can also try the test build from #6562.

**Closed by RussKie** 2019-05-16 13:49 UTC
