### ISSUE TITLE
[NBug] Sequence contains no matching element

### ISSUE THREAD

**Issue by daejungkim** [gitextensions/gitextensions#10427] opened 2022-11-21 05:11 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at GitUI.UserControls.RevisionGrid.RevisionGridMenuCommands.<CreateOrUpdateMenuCommands>g__UpdateMenuCommandShortcutKeyDisplayString|14_0(IReadOnlyList`1 targetList, IEnumerable`1 sourceList)
   at GitUI.UserControls.RevisionGrid.RevisionGridMenuCommands.CreateOrUpdateMenuCommands()
   at GitUI.RevisionGridControl.ReloadHotkeys()
   at GitUI.CommandsDialogs.FormBrowse.OnShowSettingsClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

After applying language from English to Korean, the Error Report dialog has popped up.

### Steps to reproduce

In the menu of Toos > Settings > Appearance > Language, 
the error reporting dialog has popped up after changing English to Korean or vice versa.

**Comment by pmiossec** [comment] 2022-11-21 11:12
Duplicate of #10332. Fixed in #10335. Normally will be deployed in bugfix release of v4.0

**Closed by pmiossec** 2022-11-21 11:12 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
