### ISSUE TITLE
"Stash pop" does not delete the stash

### ISSUE THREAD

**Issue by sylvain-bougnoux** [gitextensions/gitextensions#9258] opened 2021-06-04 08:40 UTC
## Current behaviour

When doing "stash pop", the stash does apply, but it is not dropped as it used to be. Maybe it is a feature, but as only the last stash is showed (and reversely to the doc, reflog does not help seeing all), the stashes may keep accumulating making it tedious to select the right one when you have several.

I understand it could be dangerous to delete, and maybe some complained about it ? But at least I think it should be an option.

Thanks

## Expected behaviour

Usually pop means apply & drop as well

## Did this work in previous version of GitExtensions

Yes

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4341.0
- DPI 106dpi (110% scaling)

**Comment by pmiossec** [comment] 2021-06-04 08:51
>When doing "stash pop", the stash does apply, but it is not dropped as it used to be. 

Could you confirm that you are talking about when the stash applied without conflicts?

Because for me it's git that handle the pop behavior and not GitExtensions.
And, from what I understand, when there is a merge conflict when the stash is applied, git keep the stash. I imagine that it is a security to be able to apply it again if you did the merge wrongly and want to reset everything and do it again...

So if you had a merge conflict and the stash is kept, that's a normal behavior.

FWIW, I have tested with a on development version of GitExtensions more recent than v3.5 and I don't reproduce: the stash is deleted.

**Comment by sylvain-bougnoux** [comment] 2021-06-04 08:54
Yes without conflict.
Yes in case of conflict the stash was kept in the previous version, and I do think it is normal behavior.

Maybe you have a different git version? I have the last one.

**Comment by pmiossec** [comment] 2021-06-04 09:02
Yes still in an older version: 

- Git 2.28.0.windows.1 (recommended: 2.30.0 or later)

**Comment by RussKie** [comment] 2021-06-05 12:27
Please try with a different version of git.

**Comment by RussKie** [comment] 2021-06-05 12:28
If you run the command form the cli line does it work as expected?

Also maybe try with a different version of git.

**Comment by sylvain-bougnoux** [comment] 2021-06-07 08:34
Hum maybe it is more subtle/simple than that ?
After the WE I reboot my machine, now I cannot exactly reproduced the issue ! Maybe the reboot helped, maybe I was wrong ?
On the console `git stash pop` works... and from the menu as well... good.

But today I only see a **refresh issue**. I have 2 branches, let's say A & B, both with a stash. GE shows only one stash, let's say B. On branch B, when I 'stash pop', the stash is applied, but GE still shows B's stash. After clicking refresh explicitly, GE shows A's stash as it should. Therefore it seems a simply refresh is missing. And as expected B's stash is no longer in 'manage stashed'.
I don't think I could make such a big confusion ? maybe the reboot helped. Anyway...

What about showing only the last stash, I think previous version were better?
Thanks for your answers.

**Comment by pmiossec** [comment] 2021-06-07 08:45
So duplicate of #9121 (fixed in #9145)?

@gerhardol in #9145, I see:

>Regression, to be cherry-picked for 3.5

but it seems not having been back-ported in 3.5. Do I miss something?

**Comment by mstv** [comment] 2021-06-07 19:13
> but it seems not having been back-ported in 3.5. Do I miss something?

I have cherry-picked 3f4ed21 and pushed it right now.

**Closed by mstv** 2021-06-07 19:13 UTC

**Comment by gerhardol** [comment] 2021-06-07 20:06
> but it seems not having been back-ported in 3.5. Do I miss something?

Lost in the flow of other updates...
Thanks @mstv
