### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by tom-huguenard** [gitextensions/gitextensions#6625] opened 2019-05-21 18:28 UTC
## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Git.hub.Repository.GetBranches()
   at GitHub3.GitHubRepo.GetBranches()
   at GitUI.CommandsDialogs.RepoHosting.CreatePullRequestForm.<>c__DisplayClass22_0.<<PopulateBranchesComboAndEnableCreateButton>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment] 2019-05-21 21:42
How to reproduce?

**Comment by illfated** [comment] 2019-05-25 13:43
https://github.com/gitextensions/gitextensions/search?q=Object+reference+not+set+to+an+instance+of+an+object&state=open&type=Issues

#3997, #6387, #6579, #6583

**Comment by gerhardol** [comment] 2019-05-25 15:18
The stacktrace is different from previous issues, so no duplicate what I see.
Do you have Github token?
https://github.com/gitextensions/gitextensions/issues/3712#issuecomment-313185605

**Comment by gerhardol** [comment] 2019-06-09 22:02
Duplicate of #6757

**Closed by gerhardol** 2019-06-09 22:02 UTC
Labels: area: plugins, status: more info requested
