### ISSUE TITLE
[NBug] Version string portion was too short or too long.

### ISSUE THREAD

**Issue by SeanSoraghan** [gitextensions/gitextensions#7693] opened 2020-01-27 15:55 UTC
## Current behaviour

When trying to submit a gerrit review using the UI button, the UI crashes with the invalid argument exception detailed below

## Expected behaviour
The UI should not crash.

## Steps to reproduce

Have an existing gerrit review with change id ID.
Rebase branch X on commit Y with advanced options, where commit Y has change id ID.
Squash all commits into one.
Replace the change id of the latest commit on branch X with ID from commit Y.
Once rebased, click the 'publish gerrit change' UI button.

## Error Details
```
System.ArgumentException: Version string portion was too short or too long.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at Gerrit.FormGerritBase.OnLoad(EventArgs e)
   at Gerrit.FormGerritPublish.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Tried to submit a gerrit review using the UI button.
Also experienced this in release 3.3.0.7719
Bug not present in release 3.2.1.6628 - have reverted to this version for now.

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.22.0.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4075.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment] 2020-01-27 17:02
Duplicate of #7521

Updated in master

**Closed by gerhardol** 2020-01-27 17:02 UTC
Labels: potential-duplicate
