### ISSUE TITLE
.NET 5.0: `FileStatusList` group headings enlarged

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9163] opened 2021-05-05 20:18 UTC
`FileStatusList` group headings consume (too) much additional space

![FileStatusList](https://user-images.githubusercontent.com/36601201/116617079-c2b9fc80-a93d-11eb-8b82-5122de7ad98a.png)

**Comment by RussKie** [comment] 2021-06-13 14:10
Caused by https://github.com/dotnet/winforms/issues/5087

**Comment by GintasS** [comment] 2021-07-11 11:11
This going to be fixed in .NET 6, but I guess we need a temporary fix until then?
https://github.com/dotnet/winforms/issues/5087#issuecomment-866635668

**Comment by RussKie** [comment] 2021-07-11 14:14
It's getting fixed in 5.0.9 https://github.com/dotnet/winforms/pull/5094

**Closed by RussKie** 2021-07-11 14:14 UTC
Labels: .NET migration, area: user experience
