### ISSUE TITLE
Avoid gitconfig flags - ```git merge --no-edit```

### ISSUE THREAD

**Issue by MobaLinux** [gitextensions/gitextensions#11763] opened 2024-05-29 07:53 UTC
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.45.1.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.28

### Issue description

When I'm updating master branch with any file, and then want to merge the change to dev branch (both are synced with my local branch), I am getting an message saying to specify a commit for this merge, although my global .gitconfig states:
```mergeoptions = --no-edit```.
according to git official documentation it does suppose to work and on git cli it does works [Official documetnation](https://git-scm.com/docs/git-merge#Documentation/git-merge.txt---no-edit)
> --no-edit
Invoke an editor before committing successful mechanical merge to further edit the auto-generated merge message, so that the user can explain and justify the merge. The --no-edit option can be used to accept the auto-generated message (this is generally discouraged). The --edit (or -e) option is still useful if you are giving a draft message with the -m option from the command line and want to edit it in the editor.

I don't quite understand why on GitExtensions it does not work.

**Important note** 
I'm using the ```merge branches``` under Commands, and specify branch master into dev 
All the testing that I did worked fine on the git bash cli via the GitExtensions, only the GUI features does not work.

I tried to work around that and do an alias of git merge to git merge --no-edit and it still doesn't work, and on git cli it works fine.

### Steps to reproduce

- Create branch out of master (for instance dev).
- Update a file for whatever to be updated
- Git commit & push to remote
- Merge branch from master into dev
- And the commit window will appear

**Comment by mstv** [comment] 2024-05-30 20:15
I cannot reproduce what you complain about - as far as I understood.
The merge message editor opens only opens if there were merge conflicts.

> mergeoptions = --no-edit.
> according to git official documentation it does suppose to work and on git cli it does works [Official documetnation](https://git-scm.com/docs/git-merge#Documentation/git-merge.txt---no-edit)

As I read https://git-scm.com/docs/git-merge#Documentation/git-merge.txt-branchltnamegtmergeOptions, the option is to be set per branch.

Anyway, it would become clearer with a screen recording or a few screenshots.
You should check (and perhaps share) the output of `git config -l`.

**Comment by taipignas** [comment] 2024-06-05 06:48
message editor started opening for me too. im not sure what caused it. maybe git update to version 2.45.1.windows.1

**Comment by MobaLinux** [comment] 2024-06-05 08:24
@mstv I've checked with ```git config -l``` and its written under the right area, perhaps its because of git executable? because its started to happen when I upgraded the git version as well.

**Comment by KevinHeick** [comment] 2024-07-08 09:28
This is very interesting, the same happened to me after i upgraded the git version.
I couldnt find anything online about this, only after i stumbled upon this.
Do you have a fix for this already?

**Comment by MobaLinux** [comment] 2024-07-08 13:38
No, unfortunately not, waiting for some ping from the gitextension team

**Comment by AeroDev101** [comment] 2024-07-09 10:27
I dont use gitextensions and i get the same exact problem.
Thats why i think it actually is a bug with git itself, so i guess the gitextension cant do much about this then.

**Comment by MobaLinux** [comment] 2024-07-09 10:41
@AeroDev101, When I'm using git commandline to reproduce it, I get the same result but when I apply the mergeoption flag, it works as it should, which means it comes for some reason the gitconfig flags

**Comment by FireEmerald** [comment] 2024-07-22 07:10
Im also prompted to verify the auto-generated merge messages, each time, since a couple of weeks now. Really annoying. As a workaround you can set the env variable:
```
   If you have a script that runs "git merge" and if you do not
   want the user to explain the resulting merge commits, you can
   export GIT_MERGE_AUTOEDIT environment variable set to "no", like
   this:

GIT_MERGE_AUTOEDIT=no

   to disable this behavior (if you want your users to explain their
   merge commits, you do not have to do anything).  Alternatively, you
   can give the "--no-edit" option to individual invocations of the
   "git merge" command if you know everybody who uses your script has
   Git v1.7.8 or newer.
```

As result you are no longer prompted to verify merge messages for successful merges.

**Closed** 2024-10-31 22:17 UTC
Labels: type: git issue
