### ISSUE TITLE
Commit message containing DLE shows as empty

### ISSUE THREAD

**Issue by sharwell** [gitextensions/gitextensions#2718] opened 2015-03-17 18:53 UTC
If a commit message contains the [DLE](http://en.wikipedia.org/wiki/C0_and_C1_control_codes#DLE) control character (0x10), Git Extensions log window shows the commit message but the Commit pane shows no text at all for the message.

![image](https://cloud.githubusercontent.com/assets/1408396/6695141/f4d07ac4-ccac-11e4-991d-3912105ca05d.png)

**Comment by Radrik5** [comment] 2015-03-17 19:25
Probably duplicate of #2525

**Closed** 2015-03-17 20:25 UTC
