### ISSUE TITLE
inverted diffs after refresh

### ISSUE THREAD

**Issue by mast-eu** [gitextensions/gitextensions#6147] opened 2019-01-21 22:06 UTC
## Current behaviour

Under certain circumstances, the diffs shown in the Diff tab can be inverted just by refreshing the GUI.
I.e. when showing the differences from _<some_old_commit>_ to _<some_new_commit>_ and refreshing the GUI, the Diff tab shows the differences from _<some_new_commit>_ to _<some_old_commit>_ instead.

## Expected behaviour

Diffs shall not be shown as inverted, no matter whether the GUI is refreshed or not.

## Steps to reproduce

1. Load any repository in GitExtensions and click on the Diff tab.

2. Select any commit, except the latest one in your revision graph.
![bugdiffrefresh1](https://user-images.githubusercontent.com/46861028/51501075-c9598100-1dd0-11e9-9629-0c85050edf0d.png)

3. Hold the CTRL key and select another commit, which is **after** the first one (i.e. more top-wards in the revision graph). It doesn't have to be on the same branch and it doesn't have to be a direct child commit. It may also be one of the artificial commits (if enabled).
It is important, however, that the second commit is shown above the first one in the revision graph.
![bugdiffrefresh2](https://user-images.githubusercontent.com/46861028/51501099-deceab00-1dd0-11e9-91f1-9f0f6c87beea.png)

4. Press F5 or click on the Refresh icon.
![bugdiffrefresh3](https://user-images.githubusercontent.com/46861028/51501111-e9894000-1dd0-11e9-923b-694dd797d116.png)

## Did this work in previous version of GitExtensions

Yes, GitExtensions 2.51.05 is not inverting the diffs.

## Environment

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by ignacioerrico** [comment] 2019-03-04 00:28
This is caused by the fact that, when refreshing, revisions are added to the revision graph in order. Consequently, the revisions to be selected will always be in this order: newer revision first, and oldest revision second. If the oldest revision had previously been selected first, as is the case in the example reported in this ticket, the diff will be inverted after a refresh.

That can be seen in `RevisionDataGridView`, in the `Add()` method.

I would like to attempt a fix. :-)

**Comment by mast-eu** [comment] 2019-03-04 06:00
>This is caused by the fact that, when refreshing, revisions are added
>to the revision graph in order. Consequently, the revisions to be
>selected will always be in this order: newer revision first, and oldest
>revision second. If the oldest revision had previously been selected
>first, as is the case in the example reported in this ticket, the diff
>will be inverted after a refresh.

Yes, I have seen this too while debugging.

>I would like to attempt a fix. :-)

Please go for it. I'm not working on this issue, due to lack of time.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gerhardol** [comment] 2019-03-04 21:22
@ignacioerrico Assigned to you

**Comment by ignacioerrico** [comment] 2019-03-16 01:20
I spent some of my (alas, somewhat limited) free time to _read_ the code. Fascinating stuff! I'm glad I got to work on this issue! :-)

### Issue

For anyone interested, here's a summary of what I learned.

Part of refreshing is refreshing the revisions, which refreshes the _revision grid_. Once the grid has been cleared, these two things happen **concurrently**:
1. Revisions are read in order, and are added to the grid. If the revision that has just been read is in the (hash)set of revisions to be selected, then the corresponding index of that revision is added to a (concurrent) queue.
2. The queue is _peeked_. That is, if there are elements in the queue, they are _dequeued_ and the corresponding row is selected.

In other words, **the grid attempts to select a commit as soon as it is loaded**.

(A consequence of that, as I mentioned in my previous comment, is that rows are selected in the order in which revisions are read, not in the order in which they had originally been selected.)

### Solution

The solution that makes sense to me is to wait till all rows to be selected have been added to the grid _before_ attempting to select them. With the current implementation, that's the best that can be done if we don't want to wait till _all_ commits have been loaded before attempting to select the rows, as [I read](https://github.com/gitextensions/gitextensions/issues/6057#issuecomment-452601388) was done in `2.5x`.

The `HashSet` I mentioned above should be a `List`, because order matters.
There is not need for a `ConcurrentQueue`, since we want to wait till we have all the rows to be selected and, when we have them, we select them. The list of indices can thus be stored in a `List` that includes order information.

I've implemented that solution, and I'll submit a pull request shortly.

**Comment by ignacioerrico** [comment] 2019-03-22 22:54
@gerhardol, please note that you only merged the branch where I signed the _developer certificate of origin_. The [branch with the actual changes](https://github.com/gitextensions/gitextensions/pull/6394) has not been merged yet. This issue should be closed when that second merge request is accepted.

**Comment by gerhardol** [comment] 2019-03-22 23:32
The issue was closed automatically by GitHub as you had written "fix #issue_no" in the PR

**Closed** 2019-04-02 20:58 UTC
Labels: status: reproducible, type: bug
