### ISSUE TITLE
"Find" file content does not work in non selected files

### ISSUE THREAD

**Issue by DamirCiganovic-Jankovic** [gitextensions/gitextensions#4782] opened 2018-04-05 08:03 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug 
**What is the current behavior?**
When searching the diff files I could search through files by clicking into right tab where difference is shown and ctrl+F with the word I am searching for, and it will search through files that were changed in selected commit and find the word I am asking for if the word is present. Also, it will highlight the file where my word was found and show me the exact place in file. 
NOTE: Find still works if I search a word that is present in currently selected file, but if the word is present in other files, it will not find my word.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![first](https://user-images.githubusercontent.com/8416358/38353743-b81c4282-38b7-11e8-8263-723de7881c1e.gif)

**What is the expected behavior?**
In previous versions it worked. It search through all the files that were changed in the code and showed me which file has it and where is that word exactly. I combine this with "Diff contains (SLOW)" filter feature where I first find the commits I am looking for, and then search for specific word in files.
**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.13.2.windows.1
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
It worked in 2.48.05 for sure because my friend has it. I don't know for versions after that one

**Comment by jbialobr** [comment] 2018-04-05 08:12
Duplicate of #4485

**Closed by jbialobr** 2018-04-05 08:12 UTC
