### ISSUE TITLE
[NBug] The system cannot find the file specified

### ISSUE THREAD

**Issue by derrickpsleungico** [gitextensions/gitextensions#8210] opened 2020-06-11 00:22 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at bool System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at bool System.Diagnostics.Process.Start()
   at new GitCommands.Executable+ProcessWrapper(string fileName, string arguments, string workDir, bool createWindow, bool redirectInput, bool redirectOutput, Encoding outputEncoding)
   at IProcess GitCommands.Executable.Start(ArgumentString arguments, bool createWindow, bool redirectInput, bool redirectOutput, Encoding outputEncoding)
   at async Task<ExecutionResult> GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action<StreamWriter> writeInput, Encoding outputEncoding, bool stripAnsiEscapeCodes)
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTask<T>.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<T>(Func<Task<T>> asyncMethod, JoinableTaskCreationOptions creationOptions)
   at ExecutionResult GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action<StreamWriter> writeInput, Encoding outputEncoding, bool stripAnsiEscapeCodes)
   at string GitCommands.GitModule.get_GitCommonDirectory()
   at RepoDistSettings GitCommands.Settings.RepoDistSettings.CreateLocal(GitModule module, RepoDistSettings lowerPriority, SettingLevel settingLevel, bool allowCache)
   at RepoDistSettings GitCommands.Settings.RepoDistSettings.CreateEffective(GitModule module)
   at RepoDistSettings GitCommands.GitModule.get_EffectiveSettings()
   at ISettingsSource GitCommands.GitModule.GetEffectiveSettings()
   at void ResourceManager.GitPluginBase.Register(IGitUICommands gitUiCommands)
   at void GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)+(IGitPlugin p) => { }
   at void System.Linq.LinqExtensions.ForEach<T>(IEnumerable<T> enumerable, Action<T> action)
   at void GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
   at void GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   at async GitUI.CommandsDialogs.FormBrowse(GitUICommands commands, string filter, ObjectId selectCommit)+(?) => { }
   at void GitUI.ThreadHelper+<>c__DisplayClass13_0+<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
double click the GitExtension.exe
only error report window opened, git extension window cannot open

## Environment
- Git Extensions 3.4.0.9608
- Build a4f5744118651776ec26d570b462e5ba8fc18afc
- Git - (minimum: 2.11.0, recommended: 2.25.1)
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2020-06-11 02:59
You don't appear to have git installed or available on %PATH%.

**Comment by RussKie** [comment] 2020-06-11 03:00
Duplicate of #8208

**Closed by RussKie** 2020-06-11 03:00 UTC
Labels: potential-duplicate
