### ISSUE TITLE
[NBug] fatal: bad revision 'feature'

### ISSUE THREAD

**Issue by adamshakhabov** [gitextensions/gitextensions#10797] opened 2023-03-11 22:04 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.13
- DPI 96dpi (no scaling)

### Issue description

Exit code: 128
Command: C:\Users\Adam.Shakhabov\AppData\Local\Programs\Git\bin\git.exe
Arguments: -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" --max-count=100000 --glob=refs/stas[h] feature --
Working directory: C:\Repos\ShapeCrawler\

```
GitExtUtils.ExternalOperationException: fatal: bad revision 'feature'
 ---> System.Exception: fatal: bad revision 'feature'
   --- End of inner exception stack trace ---
   at void GitUI.RevisionGridControl.PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs, bool forceRefresh)+() => { }
   at async Task GitUI.GitUIExtensions.InvokeAsync(Control control, Action action, CancellationToken token)
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

1. Create a new feature1 branch from master.
2. Add changes and commit them.
3. Apply "Filter for selected" for feature1.
4. Check `master` out.
5. Delete feature1 =>  the issue appears.

### Steps to reproduce

1. Create a new feature1 branch from master.
2. Add changes and commit them.
3. Apply "Filter for selected" for feature1.
4. Check `master` out.
5. Delete feature1 =>  the issue appears.

### Did this work in previous version of GitExtensions?

Yes. v3.5.4

**Comment by gerhardol** [comment] 2023-03-12 12:45
Duplicate of #10740

**Closed by gerhardol** 2023-03-12 12:45 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
