### ISSUE TITLE
Format patch for multiple commits fails

### ISSUE THREAD

**Issue by deathaxe** [gitextensions/gitextensions#5934] opened 2018-12-17 17:26 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

It is not possible to create a set of patches from the checked out branch via _Main Menu > Commands > Format Patch..._ dialog at the moment. The command fails with the error dialog displayed in the screenshot.

![grafik](https://user-images.githubusercontent.com/16542113/50103459-ef1ac580-0227-11e9-820a-b17fdf38af05.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open a repository
2. Open the _Format patch_ dialog via _Main Menu > Commands > Format patch ..._
3. Select 2 or more commits from the checked out branch
4. Select a destination directory within or outside of the working directory.
5. Click the _Create patch(es)_ button

**What is the expected behavior?**

No matter whether the _Save patches in directory_ is set to a path within or outside of the working directory of the repo and no matter whether one or multiple patches are selected, all of them should be exported as numbered *.patch file into the specified destination directory.

The result should look like

![grafik](https://user-images.githubusercontent.com/16542113/50103969-32c1ff00-0229-11e9-9f5b-8bf700c37624.png)

**Environment you encounter the issue:**

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**

If I recall correctly it used to work in 2.51 but it was a while ago, when I used that function the last time.

**Comment by gerhardol** [comment] 2018-12-17 17:32
duplicate of #5923

**Closed by gerhardol** 2018-12-17 17:32 UTC

**Comment by vbjay** [comment] 2019-03-09 19:45
https://github.com/gitextensions/gitextensions/issues/6355#issuecomment-471215388

**Comment by vbjay** [comment] 2019-03-09 20:01
https://github.com/gitextensions/gitextensions/blob/d0ba1a57823f12cc1caec12026586bb9353d2771/GitCommands/Git/GitModule.cs#L1414
