### ISSUE TITLE
App crashes after file history window closing

### ISSUE THREAD

**Issue by RasheR666** [gitextensions/gitextensions#7793] opened 2020-02-20 15:18 UTC
## Current behaviour

Sometimes git extensions crashes in different ways, but i found only one stable place

## Steps to reproduce

1. Browse repository
2. Select commit
3. Open some file history at Diff panel
4. Close file history window
5. Git Extensions crashes

## Did this work in previous version of GitExtensions

From 2 to the last

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.1.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

## Diagnostics

If you tell how i can get log file with error, then i will try to give you it

**Comment by gerhardol** [comment] 2020-02-20 16:13
You should get the NBug popup with stack trace etc
F12 to get git commands

I have not seen this, a repo where this can be reliably recreated is needed too

**Comment by RasheR666** [comment] 2020-02-20 18:55
After closing file history git extensions crashes and log using F12 cleaned up.
After new launch i see new log. Maybe has git extensions any log file that persist exceptions before crash?

Or i didn't understood your answer correctly (about NBug and so on)?

About repo - is on each repo at my machine, but on another machine i don't have any problem... hmm... That means that it is problem of my system configuration or installation.
I need to get log file with exception to understand the reason, do git extensions write this type of log?

**Comment by RasheR666** [comment] 2020-02-20 19:04
I found this at system lo
[system.logs.txt](https://github.com/gitextensions/gitextensions/files/4232515/system.logs.txt)
[Report.zip](https://github.com/gitextensions/gitextensions/files/4232520/Report.zip)

**Comment by RasheR666** [comment] 2020-02-20 19:17
I found that this error is similar with https://github.com/gitextensions/gitextensions/issues/5936
But this bug marked as closed, but i didn't found the cure to fix this problem at those issue.

**Comment by mstv** [comment] 2020-02-20 19:20
@sharwell, could you have a look at this `FailFast` in `RevisionDataGridView.BackgroundThreadEntry`, please?
```
platform version: v4.0.30319
stack
   в System.Environment.FailFast(System.String, System.Exception)
   в Microsoft.VisualStudio.Threading.JoinableTaskFactory+MainThreadAwaiter.OnCompleted(System.Action, Boolean)
   в System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AwaitOnCompleted[[GitUI.ControlThreadingExtensions+ControlMainThreadAwaiter, GitExtUtils, Version=3.3.1.7897, Culture=neutral, PublicKeyToken=null],[GitUI.GitUIExtensions+<InvokeAsync>d__11, GitUI, Version=3.3.1.7897, Culture=neutral, PublicKeyToken=null]](ControlMainThreadAwaiter ByRef, <InvokeAsync>d__11 ByRef)
   в GitUI.GitUIExtensions+<InvokeAsync>d__11.MoveNext()
   в System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[GitUI.GitUIExtensions+<InvokeAsync>d__11, GitUI, Version=3.3.1.7897, Culture=neutral, PublicKeyToken=null]](<InvokeAsync>d__11 ByRef)
   в GitUI.GitUIExtensions.InvokeAsync(System.Windows.Forms.Control, System.Action, System.Threading.CancellationToken)
   в GitUI.UserControls.RevisionGrid.RevisionDataGridView.BackgroundThreadEntry()
   в System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   в System.Threading.ThreadHelper.ThreadStart()
```

**Comment by mstv** [comment] 2020-02-20 19:31
#5936 with the same exception but from `CommitInfo` was closed because it did not occur after the installation of .Net 4.8.
It was not reopened because no feedback on the question regarding the registry keys
```
HKLM\SOFTWARE\Microsoft\.NETFramework\AppContext
HKLM\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\AppContext
```

**Comment by RasheR666** [comment] 2020-02-20 20:01
AppContext as registry folder and registry key doesn't help.
I have .net 4.8 as I write at first message.
I found out that the same error events at windows system logs appered after git extensions usual closing (application exit)

**Comment by RussKie** [comment] 2020-02-20 20:45
Are there any errors in EventViewer under Applications?

**Comment by RasheR666** [comment] 2020-02-21 04:30
Sorry i didn't know how it's on English
errors in EventViewer under Applications == error events at windows system logs == system logs when i write it in previous commentaries

**Comment by RasheR666** [comment] 2020-02-25 07:29
@mstv @RussKie @sharwell is need something else or is it enough information?
I did not found anymore errors other than those that i attached at system.logs.txt (errors from EventViewer under Applications)? But maybe you know some other special places that can be helpful.

**Comment by RussKie** [comment] 2020-02-25 07:43
This may be an environmental issue specific to your workstation.
Try building the latest master, and see if it behaves any different.

**Comment by DmitryZhelnin** [comment] 2020-03-18 07:13
I have a similar issue. But the app crashes on the form closing only when it was launched with `filehistory` argument.
In the system events log I have:

> Сведения об исключении: System.InvalidOperationException
   в System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   в System.Windows.Forms.Control.BeginInvoke(System.Delegate, System.Object[])
   в System.Windows.Forms.WindowsFormsSynchronizationContext.Post(System.Threading.SendOrPostCallback, System.Object)
   в System.Reactive.Concurrency.SynchronizationContextScheduler.Schedule[[System.ValueTuple`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]](System.ValueTuple`2<System.__Canon,System.__Canon>, System.Func`3<System.Reactive.Concurrency.IScheduler,System.ValueTuple`2<System.__Canon,System.__Canon>,System.IDisposable>)
   в System.Reactive.Concurrency.Scheduler.ScheduleAction[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Reactive.Concurrency.IScheduler, System.__Canon, System.Action`1<System.__Canon>)
   в System.Reactive.Linq.ObservableImpl.EventProducer`2+Session+<>c[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Connect>b__5_0(System.ValueTuple`3<Session<System.__Canon,System.__Canon>,System.Reactive.Linq.ObservableImpl.EventProducer`2<System.__Canon,System.__Canon>,System.IDisposable>)
   в System.Reactive.Disposables.AnonymousDisposable`1[[System.ValueTuple`3[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].Dispose()
   в System.Reactive.Disposables.Disposable.TryDispose(System.IDisposable ByRef)
   в System.Reactive.Linq.ObservableImpl.Throttle`1+_[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Dispose(Boolean)
   в System.Reactive.Sink`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Dispose()
   в System.Reactive.Disposables.Disposable.TryDispose(System.IDisposable ByRef)
   в System.Reactive.ObserveOnObserverNew`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Dispose(Boolean)
   в System.Reactive.Sink`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Dispose()
   в GitUI.CommitInfo.CommitInfoHeader.DisposeCustomResources()
   в GitUI.GitModuleControl.Dispose(Boolean)
   в System.ComponentModel.Component.Finalize()

**Comment by DmitryZhelnin** [comment] 2020-03-25 07:56
I can't reproduce the issue with the latest master build.

**Comment by RussKie** [comment] 2020-03-31 11:50
@DmitryZhelnin your issue is a duplicate of #7385, that was fixed in #7421.

**Comment by RussKie** [comment] 2020-03-31 11:52
@RasheR666 are you still getting the issue? 
Try the latest portable build, and see if it repros your issue: https://ci.appveyor.com/api/buildjobs/ah3r7644ff3nq175/artifacts/artifacts%2Fpublish%2FGitExtensions-Portable-4.0.0.8944-bc0fc56e1.zip

**Comment by RasheR666** [comment] 2020-03-31 13:34
This one is stable. 
Tested 3.3.1 portable, 3.3.1 installed and 4.0.0 portable

**Comment by RussKie** [comment] 2020-04-02 10:10
Closing. Holler if it reappears.

**Closed by RussKie** 2020-04-02 10:10 UTC
