### ISSUE TITLE
Creating new branch locks up GitExtensions

### ISSUE THREAD

**Issue by hkoster** [gitextensions/gitextensions#6657] opened 2019-05-24 07:56 UTC
## Current behaviour
In the Create branch dialog when specifiying a new branch and than pressing the button "Create branch" GitExtentions freezes and stops working.

## Expected behaviour
It should create a new branch and return to the main screen.

## Steps to reproduce
Commands -> Create branch -> enter new branch name -> press button

## Did this work in previous version of GitExtensions
No, same behaviour.

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.20.0.windows.1
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment] 2019-05-24 09:25
We need more information.

Because that's a very used feature and I never had such a problem.
Is that happening every times?
Did you tried in another git repository?
Did you tried to reinstall Git Extensions? or git?
Could you provide a screenshot when it's freezed?

**Comment by hkoster** [comment] 2019-05-24 11:41
Hi Philippe,

This is happening everytime when using GitExtentions. When using Visual Studio 2017/2019, SourceTree and commandline (and PowerShell) prompt or even the Console option in GitExtentions it works.

Still happens after reinstalling Git and GitExtentions. Even after a reboot.

Note: After killing the proces via the TaskManager i could (for a short moment) a bash console. I could not see what it said because the letters where very small and the console disappered very quickly.

**Comment by pmiossec** [comment] 2019-05-24 12:02
Strange....

Could you try 2 things?

First, uncheck option "Use Console Emulator [....]"

![image](https://user-images.githubusercontent.com/460196/58326089-12c3e680-7e2c-11e9-865e-435431826520.png)

Tel us if it solves your problem.

If not, open "Git Command log" (F12) and do a print screen of the commands just after it freezed (to see which commands has been run)

**Comment by hkoster** [comment] 2019-05-24 15:18
Hi Philippe,

Unchecking the option did not work.

Tried on an other PC, other repo. All (git and gitextentions) are uptodate. No issues there.

Will check work PC (virtual) again for issue. Could have something to do with credentials.... During reproducing the issue and checking solutions i needed to use my credentials for the TFS (onpremise) git repo.

Have a nice weekend

**Comment by pmiossec** [comment] 2019-05-24 15:21
So I will close the issue and you could reopen it when you found out what was the cause....

**Closed by pmiossec** 2019-05-24 15:21 UTC
Labels: status: more info requested

**Comment by hkoster** [comment] 2019-05-24 16:00
Unckecking the option did nothing. And i am unable to the log, after killing the process there is no log of the previous session.

I currently need to login to get to the repo (not needed before after certificate installation) so probably this is related.

Signing of for the weekend. Will see if problem still occurs next monday.

Regards and have a nice weekend.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: Philippe Miossec <notifications@github.com>
Verzonden: vrijdag, mei 24, 2019 2:02 PM
Aan: gitextensions/gitextensions
CC: Harry Koster; Author
Onderwerp: Re: [gitextensions/gitextensions] Creating new branch locks up GitExtensions (#6657)


Strange....

Could you try 2 things?

First, uncheck option "Use Console Emulator [....]"

[image]<https://user-images.githubusercontent.com/460196/58326089-12c3e680-7e2c-11e9-865e-435431826520.png>

Tel us if it solves your problem.

If not, open "Git Command log" (F12) and do a print screen of the commands just after it freezed (to see which commands has been run)

**Comment by RussKie** [comment] 2019-05-24 22:40
This looks suspiciously similar to #6518
