### ISSUE TITLE
Cannot find revision error with Show current branch only selected

### ISSUE THREAD

**Issue by SergiiGalai** [gitextensions/gitextensions#11796] opened 2024-06-28 16:43 UTC
### Environment

- GitExtensions version: - Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.45.2.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.31
- DPI 168dpi (175% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

The following error appears each time when `Show current branch only` is selected. 
There is no problem when `Show all branches` is selected
It is annoying to see this error every time I want to do some operation with other branches.
I have a submodule and it takes some time to automatically refresh submodules, I haven't check the behavior without submodules

### Steps to reproduce

- select View->Show current branch only
- have at least 2 branches on the left.
- double click on branch1 (branch2 will be in gray)
- right click on branch2
- popup appears
![image](https://github.com/gitextensions/gitextensions/assets/5754796/e34fdd13-eb90-4bb9-959e-352413712f18)

click ok and right-click again
now one can merge it into branch1 for example

### Did this work in previous version of GitExtensions?

no

**Comment by gerhardol** [comment] 2024-06-28 21:17
The issue is that the branches (local and remote, tags and stashes are OK) that are not visible in the grid are only handled as visible when loading the first time. When selecting another branch (or just refreshing) there seem to be some race condition, so the status of the branches are not updated correctly. The status is set correctly, then it goes back to Visible.

**Comment by pmiossec** [comment] 2024-06-28 21:58
Can you test the development version? I have the feeling that an improvement has been made to better handle this case but I can't find the issue or the PR...

**Comment by gerhardol** [comment] 2024-06-28 22:38
Please try the portable build in the PR.

**Comment by SergiiGalai** [comment] 2024-07-01 17:39
> Please try the portable build in the PR.

@gerhardol  Sorry, are you asking me?
If yes: I haven't found any builds in the PR. Do you mean to build it on my machine from the sources and run it?

**Comment by gerhardol** [comment] 2024-07-01 20:33
> > Please try the portable build in the PR.
> 
> @gerhardol Sorry, are you asking me? If yes: I haven't found any builds in the PR. Do you mean to build it on my machine from the sources and run it?

You can build it but there is a link to the artifacts in the build, for the portable build:
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/50115828/artifacts

**Comment by SergiiGalai** [comment] 2024-07-02 17:10
After testing the portable build it looks to me like the issue is less reproducible but still exists.
If one after switching to the branch quite quickly does smt with another branch while having Show current branch only enabled then the issue might still occur but more rarely. 
In version 4.2 the popup with the error occurred right after the right button click on the branch name.
In version 4.3 IMO I see the error less.
But still exists, it allows doing the right click, then it thinks and then shows the right-click popup and the error popup
![image](https://github.com/gitextensions/gitextensions/assets/5754796/48445f36-0de6-4f2e-a3f6-5cc01cfc298e)

**Comment by gerhardol** [comment] 2024-07-02 17:25
What I can see:
The status is updated after the grid is loaded (the ref is set to gray, as in your example), that is when we know if the ref is accessible or not. So if you are quick and rightclick before it is grey, you will see the popup. 
Not much to do about that than to delaying showing left sidepanel until is grid is shown, which would be limiting for me.

**Comment by gerhardol** [comment] 2024-07-05 21:44
I do not see a better solution than the PR, plan to merge that in the coming days, closing this issue.

**Comment by RussKie** [comment] 2024-07-05 22:46
👍

**Closed** 2024-07-07 21:09 UTC
