### ISSUE TITLE
Made up diff coloring (with low contrast)

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#11843] opened 2024-08-19 11:03 UTC
### Environment

- Git Extensions 33.33.33
- Build d99188960d576a8858a7fec66a32181d0a3b4dea
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

A large diff (> 3000 lines) is displayed with made up in-line coloring.
Lines 222-3 have been moved to lines 318-319:
![grafik](https://github.com/user-attachments/assets/bfa20f2c-e2e8-4bc2-b61c-52725a7df5fe)  ![grafik](https://github.com/user-attachments/assets/e3149397-0a84-42dd-86ef-529be261cf64)

The git output seems to be OK (copied from git command cache):

![grafik](https://github.com/user-attachments/assets/3d3dd153-c8f7-4530-a526-56ba62098d1a)

It occurs both with and without syntax highlighting.

### Steps to reproduce

view a large diff with lots of moved lines

### Did this work in previous version of GitExtensions?

N/A

### Diagnostics

Might this be caused by the unnecessary reset sequence and the repeated identical color codes?

```
[7;31m-P____ =  (int8) 100[m
[1;7;34m+[m[1;7;34mT____ =  (boolean) 1[m
[1;7;33m+[m[1;7;33mE____ = {0,0,0,0,0,0,0,0,0,0,0}[m
[2;7;33m+[m[2;7;33mG____ = 50[m
 T____ =  (boolean) 1[m
```

**Comment by mstv** [comment] 2024-08-19 11:22
I guess GE's patch processor needs to detect that git marks moved lines, and should not touch those lines.

**Comment by gerhardol** [comment] 2024-08-19 11:32
Is this something else than the white foreground mentioned in https://github.com/gitextensions/gitextensions/pull/11830#issuecomment-2294379349

There are diff in https://github.com/gerhardol/tmp_tests that uses the affected colors so you do not have to mask the contents

When reverse colors are set without foreground colors, GE tries to find a better one. This code was added with the theming, not sure what the theory behind it is.
The algorithm finds the percepted lightness to be closer to "white" foreground for some reason for bold yellow/blue/magnenta. yellow appeared previously more often with white foreground, still some work to do

I tried to investigate but could not reproduce.
I can maybe push some debug printout.
The black foreground colors are preferred with 1.25 over white foregrounds, that could maybe be increased (as we really just want white foreground for black backgrounds).
The color palette you see is still interesting, same as what I saw?

**Comment by mstv** [comment] 2024-08-19 21:09
> There are diff in https://github.com/gerhardol/tmp_tests that uses the affected colors so you do not have to mask the contents

Thank you!

> Is this something else than the white foreground mentioned in https://github.com/gitextensions/gitextensions/pull/11830#issuecomment-2294379349

(To be honest, I have not really tried to understand the meaning of all these unnamed screenshots in this PR.)
I guess you mean the one in the red frame, aren't you?

![image](https://github.com/user-attachments/assets/bf46d4ad-06b0-48c6-aafc-fab556a61bda)

As far as I understand, git chooses this escape code for the line "+random2" from [commit f8aaf40](https://github.com/gerhardol/tmp_tests/commit/f8aaf40e04e5f66527822ea948a997e0eb3cbef1).
The color combination assigned by GE is hard to read. But as you wrote, it occurs rare enough. I agree that this does not need to be improved for the release.

The file mentioned in the ticket description is more complex.
Git does not chose this escape code. It must be GE's in-line-change detector (`DiffHighlightService.AddExtraPatchHighlighting`), which adds highlights to unchanged but moved lines by mistake.
The resulting diff display is too weird IMO.

In [commit ae4948e](https://github.com/gerhardol/tmp_tests/commit/ae4948e45e5cff6b41f8149dcd291a4a9f2c7216) GE's algorithm works correctly for the line with appended spaces.
First, I wondered why git colors the added spaces red. Though it is just complaining about the trailing spaces.
```
"[7;32m+[m[7;32mAdded space after this line to show coloring[m[41m  "
```
![image](https://github.com/user-attachments/assets/2758ceb6-74d7-419b-87dc-edeb70c6fd59)

This commit could be used for finding out how `PatchHighlightService.GetRemovedLines` / `.GetAddedLines`  could be prevented from returning moved lines like 17 / 15.
Since Extra Patch Highlighting is done very late (the escape sequences have already been turned into `IDocument` markers), it needs detailed knowledge of `IDocument`...

**Comment by gerhardol** [comment] 2024-08-19 21:54
In the same as the the existing red/green backgrounds are chosen, it is only background colors that are set. (Git sets the foreground color by default.)
GE adds the "word diff" with a custom algorithm, like "changes in this" in the example.
The problem with whitte forground color appeared with yellow background in other situations too before.

The GE algorithm to detect the not configured foreground color is incorrect, alternatively tune the colors to work better. The colors are so bright that this is difficult.
Another way to fix this could be to force the forecolor to be black (colors are overridden anyway).
Yet another is to not configure bold for the "border" colors, then there are no known usage of the colors with problems.

This can be adjusted after an initial beta too, should not be critical regardless.

**Comment by mstv** [comment] 2024-08-19 23:29
My point is that `PatchHighlightService.GetRemovedLines` / `.GetAddedLines` must not return _just moved_ lines.

**Comment by gerhardol** [comment] 2024-08-20 08:19
So it is the green on blue/yellow you report on?
The white-on-yellow is an issue if so but separate.

Highlighting with Git is done as following:
* Git output is parsed. If there is no foreground set for background, fore is calculated. The named terminal colors are translated to ARGB and positions/colors are stored.
* Highlighting from searches etc are applied.
* GE word diff (extra patch) is applied (for normal diff only, not git-word-diff).
* Git colors applied
* GE highlighting

The first area changing default is used. So GE word diff is applied before Git coloring.

Do you want to ignore GE word diff for moved lines? This would be a hack as the use is unknown, just the colors. GE could guess that normal red/green background are changed lines (like done for difftastic), but the user could override the colors from Git and the exclusion will fail.

**Comment by mstv** [comment] 2024-08-20 19:01
> So it is the green on blue/yellow you report on?
> Do you want to ignore GE word diff for moved lines?

Yes! Because it is very confusing to display made-up word-diffs in _just moved_ lines, i.e. which have not changed but their position.
(The green highlight is so distracting - up to the entire line - that it took very long to get that this is the section which does not make sense.)

key:
green arrows = good git coloring
orange arrows = unlucky translation of git coloring (not a big deal)
red frames = confusing word diff

![image](https://github.com/user-attachments/assets/250c5334-c48e-47ad-813d-610f55f0551c)

Git seems to not specify a foreground color for the "+" / "-" in front of added / removed lines.
Thus `PatchHighlightService.GetRemovedLines` / `.GetAddedLines` should return only lines without set foreground color - somehow.
This approach should also work if users configure their own colors - at least to a certain degree. 

![real change](https://github.com/user-attachments/assets/c35c01cf-cb74-49bd-b74d-2a63825b0cd8)

**Comment by gerhardol** [comment] 2024-08-20 19:54
> Git seems to not specify a foreground color for the "+" / "-" in front of added / removed lines. Thus `PatchHighlightService.GetRemovedLines` / `.GetAddedLines` should return only lines without set foreground color - somehow. This approach should also work if users configure their own colors - at least to a certain degree.

The color is set and you do not know the reason for a color.

A setting could be added to assume the GE-word-diff is only set for normal red/green.
This is even less secure than the difftastic manipulation, the colors are hardcoded in difftastic but can be configured in git-config. It is a "fragile" function. Worth it?
But it is a guess. Default on or off.

**Comment by mstv** [comment] 2024-08-21 18:04
> > Git seems to not specify a foreground color for the "+" / "-" in front of added / removed lines. Thus `PatchHighlightService.GetRemovedLines` / `.GetAddedLines` should return only lines without set foreground color - somehow. This approach should also work if users configure their own colors - at least to a certain degree.
> 
> The color is set and you do not know the reason for a color.

One *can* know it: 
If the git output matches `^.\[\d+;\d+m[+-]`, it is a changed line.
Moved lines match `^.\[\d+;\d+;\d+m[+-]`.
This information (absence of first number) needs to be forwarded to the `PatchHighlightService` - "somehow".
The colors themselves do no matter.

> A setting could be added to assume the GE-word-diff is only set for normal red/green. This is even less secure than the difftastic manipulation, the colors are hardcoded in difftastic but can be configured in git-config. It is a "fragile" function. Worth it? But it is a guess. Default on or off.

Since it is and will be really confusing to me although I know the background, I strongly vote for having it active by default. A hidden setting should suffice.

**Comment by gerhardol** [comment] 2024-08-21 22:20
> One can know it:

No, it is just that "dimmed-zebra" uses bold/dim for the moved lines, normal diff uses normal colors. Could be configured.
So color is still a better detector or rather only apply to normal red/green background.

**Comment by mstv** [comment] 2024-08-22 17:03
OK, then red/green background, please.

**Comment by gerhardol** [comment] 2024-08-23 21:02
@mstv Any hints how to create diff with this issue?

**Comment by mstv** [comment] 2024-08-24 15:31
> Any hints how to create diff with this issue?

https://github.com/mstv/gitextensions/commit/f8b20b6fc34bca47217187bec47c1bf825dcc24f

![image](https://github.com/user-attachments/assets/7e6e4843-df20-4635-bd10-100a14a71448)

**Comment by gerhardol** [comment] 2024-09-04 21:55
I have pushed an implementation to tmp/difflineinfo-coloring, on top of #11862 There is one todo, not really used it myself and I have no example to test the core issue (the diff algoritm is smarter now). This simplifies and makes the highlighting more efficient (hardly noticable except for really large files). The context used to find modified lines could maybe be increased though. But @mstv you may have some opinion?

**Comment by mstv** [comment] 2024-09-05 18:02
> I have pushed an implementation to tmp/difflineinfo-coloring, on top of #11862 There is one todo, not really used it myself and I have no example to test the core issue (the diff algoritm is smarter now). This simplifies and makes the highlighting more efficient (hardly noticable except for really large files). The context used to find modified lines could maybe be increased though. But @mstv you may have some opinion?

You have provided another example commit with commit 1e5d99ac23f47cce95ff7cbcbf0d1f3d963a053a, file `src/app/GitUI/Editor/Diff/DiffHighlightService.cs`, lines 210 / 180 ff.
The intention of this issue is to not change the git highlight for _moved_ lines at all.
Moved lines have become less noticeable.

It seems that the algorithm tries to match lines also in non-contiguous blocks now. This can cause annoying performance issues for large patches - _while scrolling_ through the changes, which is very surprising to me because the highlighting is done _before_ displaying the patch.
(Affected files had trailing whitespace removed and lots of `"@variants: var1"` changed to `"@variants: var1, var2"`.)

#### Before

![image](https://github.com/user-attachments/assets/d70fe5a9-e06f-4a06-9752-64cb8c53ab54)

#### After

![image](https://github.com/user-attachments/assets/153ab179-a4bf-4d07-b671-d2a7590329b4)

**Comment by gerhardol** [comment] 2024-09-05 21:43
Fixed to actually exclude the lines not expected to be normal diff now
Maybe more lines are used when comparing, have not investigated.
Disabled part of a test too.
My diff looks different, have you made changes?

![image](https://github.com/user-attachments/assets/a6a3c835-4023-494f-a226-a244f70e74f0)

**Comment by mstv** [comment] 2024-09-06 10:16
> (Affected files had trailing whitespace removed and lots of "@variants: var1" changed to "@variants: var1, var2".)

Still 2 seconds for a single `PageDown` on a workstation.
Just a guess: Could it be caused by silently caught exceptions thrown on invalid TextMarkers? (No output seen in DbgView.)

Displaying the diff of CANoe configuration files (with their randomized internal sequence on each save) can block the UI for 30 seconds.

These delays do not occur with the base commit.

> My diff looks different, have you made changes?

not at all

- Git Extensions 33.33.33
- Build 04f44d48ccc80712a6f6c526d4d6612069429593
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

**Comment by gerhardol** [comment] 2024-09-06 12:13
I do not see slowdowns, it feels quicker also on files with 20K lines diff. But that is slow.

My branch has no parsing when applying highlighting (currently the text is parsed many times when applying the highlighting). So it should be a bigger context, I am to check that.

The number of TextMarkers can be decreased. Git generates separate sections for the initial char and the rest, we can even merge subsequent lines (if lineendings can be handled smoothly).
MarkInLineDiffs could remove the "base" coloring as well as store the result (only calculate once).
That is hopefully a separate improvement, if it is the size of the context that is the issue.

Thanks for the feedback regardless.

> not at all

I do not see the same diff, maybe your rebase is different.

**Comment by mstv** [comment] 2024-09-07 16:02
Thank you, the performance issues have been solved with b367ebc10975e63f303f206d8e4803777162a91c.

Less severe examples were `src/app/GitUI/Translation/French.xlf` (and `src/app/GitUI/Translation/Traditional Chinese.xlf`) from c749d782ba4159fd6edca965ac1e9e9798f199cb.
The other language files were not affected.

---

Though moved lines are not highlighted correctly:

![image](https://github.com/user-attachments/assets/ce8187e5-ac2b-4b2c-90be-b9b04233d050)

```
·\x1b[m\n
\x1b[7;31m-········text·=·sb.ToString();\x1b[m\n
\x1b[30;104m+········//·Process·the·next·blocks·of·removed·/·added·lines·and·mark·in-line·differences\x1b[m\n
\x1b[30;103m+········while·(line·<·document.TotalNumberOfLines)\x1b[m\n
\x1b[2;7;33m+········{\x1b[m\n
\x1b[7;32m+············List<ISegment>·linesRemoved·=·GetLines(document,·ref·line,·DiffLineType.Minus);\x1b[m\n
```

**Comment by gerhardol** [comment] 2024-09-07 20:28
Some more updates in tmp/difflineinfo-coloring:
* The "context" when searching for highlights was the rest of the file, which caused the too many matches and slowdown (my big test file was probably having more additions than removals, so less compare)
* merge adjacent textmarkers, to limit the amount of textmarkers
* Cache the GE diff highlighting, to make the legacy handling similar to git-coloring
* Cache mark inline difference calculations, to not recalculate evry time a marking is changed (forinstance search). The calculation is always done anyway
* Fixed one incorrect handling of combined diff (testcase updated)

I have pushed a feature branch that will be based on #11862/#11851
A few open items:
* Not double checked that the original reason to not mark inline on moved lines is fixed in the final patch - need a better example
* I do not want coloring of the file names in the header, not implemented
* Performance when scrolling may be improved by merging areas, also over newlines. In addition, "standard" coloring that are hidden by marked inline should be removed. Needed?
* This has removed a lot more code than what was added, but there should be a few expanded test cases.

**Comment by mstv** [comment] 2024-09-07 20:40
1158a2212901a58d7207ca697ac887b66b9e1d62 has
* lost the in-line dimming
* solved the perf issues with e.g. `French.xlf`
* not managed to not touch moved lines

**Comment by mstv** [comment] 2024-09-07 20:46
> I do not want coloring of the file names in the header, not implemented

I will not miss it very much. We have not noticed for several months that it got lost.

**Comment by gerhardol** [comment] 2024-09-07 21:52
> ost the in-line dimming
not managed to not touch moved lines

Should be fixed, sorry

**Comment by mstv** [comment] 2024-09-08 08:25
Works well for the small examples in the GE repo.

The ICSharpCode.TextEditor needs a push.

Rename `IsAddedRemoved` to `IsMovedLine`?

**Comment by gerhardol** [comment] 2024-09-08 11:06
> The ICSharpCode.TextEditor needs a push.

Pushed to my fork, I opened https://github.com/gitextensions/ICSharpCode.TextEditor/pull/40

> Rename `IsAddedRemoved` to `IsMovedLine`?

The check really tries to find added/removed, but that is not the usage. I will expand on the description and change names.

No PR yet as I would like to get #11862/#11851 merged first.
I could separate the issue raised in this issue, to not mark inline for moved lines and separate the "only parse once" part. This could also be done before #11862/#11851 but it will make reviews more complicated. (And to optimize markers and remove hidden overlays is separate too.)

**Comment by mstv** [comment] 2024-09-09 22:21
The line matching is incomplete somehow: e.g. 55e74d4a1d119dd79ccd3222b681fe6f890e721e in branch `repro/unmatched_diff_lines` of my repo.
actual | expected
-|-
![image](https://github.com/user-attachments/assets/b60f30e1-a88c-4a9b-8ff7-cb7482eb033e) | ![image](https://github.com/user-attachments/assets/3ec5d7b5-764e-46d6-a2f2-299ebff45c4a)

**Comment by mstv** [comment] 2024-09-09 22:30
In order to easily be able to test the latest commits, it would help to finish and merge https://github.com/gitextensions/ICSharpCode.TextEditor/pull/40.

**Comment by gerhardol** [comment] 2024-09-10 11:09
> The line matching is incomplete somehow: e.g. [55e74d4](https://github.com/gitextensions/gitextensions/commit/55e74d4a1d119dd79ccd3222b681fe6f890e721e) in branch `repro/unmatched_diff_lines` of my repo.

Thanks.
I saw that myself yesterday at work but could not reproduce at home.

> In order to easily be able to test the latest commits, it would help to finish and merge [gitextensions/ICSharpCode.TextEditor#40](https://github.com/gitextensions/ICSharpCode.TextEditor/pull/40).

Will follow your suggestion, so I will have to rewrite the test feature branches.
But #11862 would enable me to create PRs too, to have proper discussions about code. (I believe I have cleaned up most, a few testcases to add.)

**Comment by gerhardol** [comment] 2024-09-10 20:36
> The line matching is incomplete somehow: e.g. [55e74d4](https://github.com/gitextensions/gitextensions/commit/55e74d4a1d119dd79ccd3222b681fe6f890e721e) in branch repro/unmatched_diff_lines of my repo.

Pushed an update, max lineno was incorrect
Pushing a cleanup

**Comment by mstv** [comment] 2024-09-11 20:12
Commitd 234ae1f366858f6236d47a2482918a084f180a4 "Avoid coloring moved lines" does not do what is promises:
Line 133 is a moved line and shall not be dimmed (`src/app/GitUI/Editor/Diff/DiffHighlightService.cs` of commit 1e5d99ac23f47cce95ff7cbcbf0d1f3d963a053a).

![image](https://github.com/user-attachments/assets/0978120a-e41a-4170-b0d2-f032f73bfc0c)

This works better with the branch head 846658c3e0411c4ee9e433f4f4b9f5da3d2d2340.
But it still fails to match lines in several simple diffs at work. That's why I switched back to the earlier commit.
Some files differ in one line with an updated timestamp (near the top of the file) only. I have not been able to reproduce it with an artificial sample file yet.

**Comment by gerhardol** [comment] 2024-09-11 22:08
The algorithm for finding gaps were too greedy, and I updated. But mark inline of moved lines should be something separate. 
Repros are hard...

There need to be some stability here, the dependent PR need to be merged to avoid this chaos.
I believe the code is fine, has not thought about tests yet.Simple examples for some scenarios are needed.

**Comment by mstv** [comment] 2024-09-12 10:52
Git tries to highlight the line endings!!!
I guess we just need to replace all `"(\x1b\[[^m]*m)*\r\x1b\[m\n"` with `"\r\n"` as the very first step.
But why does it affect the detection of the line type ("moved" / "removed - changed or deleted" / "added - changed or new")?
(In addition, git often issues redundant escape sequences after the '+' of added lines - regardless of leading whitepace.
Git's different handling of leading tabs in all kinds of added lines is very special, too.)
```
\x1b[7;31m-················elif·name·!=·'foo':\x1b[m\r\n
\x1b[7;32m+\x1b[m\x1b[7;32m················elif·name·!=·'foo'·or·type·==·'bar':\x1b[m\x1b[41m\r\x1b[m\n
```
```
\x1b[7;31m-const·char·id[]·=·"abc1-1234";\x1b[m\r\n
\x1b[7;32m+\x1b[m\x1b[7;32mconst·char·id[]·=·"abc2-5678";\x1b[m\x1b[41m\r\x1b[m\n
```
```
\x1b[2;7;35m-»»EXPECT(bla);\x1b[m\n
\x1b[2;7;34m+\x1b[m»»\x1b[2;7;34mEXPECT(blubb);\x1b[m\n
```

**Comment by gerhardol** [comment] 2024-09-12 12:12
> Git tries to highlight the line endings!!! I guess we just need to replace all `"(\x1b\[[^m]*m)*\r\x1b\[m\n"` with `"\r\n"` as the very first step. But why does it affect the detection of the line type ("moved" / "removed - changed or deleted" / "added - changed or new")? (In addition, git often issues redundant escape sequences after the '+' of added lines - regardless of leading whitepace. Git's different handling of leading tabs in all kinds of added lines is very special, too.)
> 
> ```
> \x1b[7;31m-················elif·name·!=·'foo':\x1b[m\r\n
> \x1b[7;32m+\x1b[m\x1b[7;32m················elif·name·!=·'foo'·or·type·==·'bar':\x1b[m\x1b[41m\r\x1b[m\n
> ```
> 
> ```
> \x1b[7;31m-const·char·id[]·=·"abc1-1234";\x1b[m\r\n
> \x1b[7;32m+\x1b[m\x1b[7;32mconst·char·id[]·=·"abc2-5678";\x1b[m\x1b[41m\r\x1b[m\n
> ```
> 
> ```
> \x1b[2;7;35m-»»EXPECT(bla);\x1b[m\n
> \x1b[2;7;34m+\x1b[m»»\x1b[2;7;34mEXPECT(blubb);\x1b[m\n
> ```



> Git tries to highlight the line endings!!! I guess we just need to replace all `"(\x1b\[[^m]*m)*\r\x1b\[m\n"` with `"\r\n"` as the very first step. But why does it affect the detection of the line type ("moved" / "removed - changed or deleted" / "added - changed or new")? 

Because the check is that all markers are (likely) added/removed:

```c#
meta.IsMovedLine = textMarkers.Value.Count > 0 && !textMarkers.Value.All(i => MarkerColorMatch(i, meta.LineType));
```

it is `\x1b[41m\r\x1b[m` that is the problem, ok to not color all.
But coloring of newlines could be ignored, not a too weird fix.

Will have to look at the Git code too.

**Comment by gerhardol** [comment] 2024-09-12 13:57
> ```
> \x1b[7;31m-················elif·name·!=·'foo':\x1b[m\r\n
> \x1b[7;32m+\x1b[m\x1b[7;32m················elif·name·!=·'foo'·or·type·==·'bar':\x1b[m\x1b[41m\r\x1b[m\n
> ```
> 
> ```
> \x1b[7;31m-const·char·id[]·=·"abc1-1234";\x1b[m\r\n
> \x1b[7;32m+\x1b[m\x1b[7;32mconst·char·id[]·=·"abc2-5678";\x1b[m\x1b[41m\r\x1b[m\n
> ```

Git marks \r as whitespace error: https://git-scm.com/docs/git-config#Documentation/git-config.txt-colordiffltslotgt

Fix to ignore single \r or to ignore when checking IsMoved?
The first option will not exclude this line for other types of whitespace errors.

Have you overridden diff.colorMovedWS?

**Comment by mstv** [comment] 2024-09-12 20:51
> Fix to ignore single \r or to ignore when checking IsMoved?

Line endings should be "as is" in their normal form, i.e. without escape sequences in-between. I give hope that this will solve #11831, too.

> Have you overridden diff.colorMovedWS?

No. I will need to check at work but I should not have set this. Though I see trailing whitespace marked red there (due to obstinate people).

I use:
```
$ git config -l | grep color
color.grep.matchselected=yellow reverse
color.diff.func=white reverse
color.diff.frag=white reverse
```

> The first option will not exclude this line for other types of whitespace errors.

I am going to also check whether whitespace errors are marked in moved lines, too.

**Comment by gerhardol** [comment] 2024-09-12 21:45
diff.wserrorhighlight, diff.colorMovedWS is ignored is ignored for moved lines, at least for \r
I do not see what the issue is though https://github.com/git/git/blob/master/diff.c#L1442

#11831 is separate, see my latest comment

I am pushing my changes, but have not tested them on any good data (tried to update the tests)

**Comment by mstv** [comment] 2024-09-13 10:48
> I am pushing my changes, but have not tested them on any good data (tried to update the tests)

Thank you! It works like a charm.

>> I give hope that this will solve https://github.com/gitextensions/gitextensions/issues/11831, too.

> #11831 is separate, see my latest comment

Note that I am referring to the main issue "1. Diff viewer shows EOL as LF although files have CRLF".
The hope was unfounded. It _is_ a git issue. The display of EOL in GE is not affected by the injected escape sequence.

> Have you overridden diff.colorMovedWS?

I have not set neither "ws" nor "whitespace" settings anywhere.

>> The first option will not exclude this line for other types of whitespace errors.

> I am going to also check whether whitespace errors are marked in moved lines, too.

(They _are_ marked. Though this does not matter because you did not mean moved lines but the detection of changed lines.)
Added lines with marked whitespace errors at eol _are_ detected as changed - good.

**Comment by gerhardol** [comment] 2024-09-15 22:50
Pushed a change that merges segments over lineending and add tests for that.

Tests are missing for "feat: skip gaps in blocks for mark inline".
Plan to open a separate PR for "fix: Merge git-diff textmarkers separated by newlines", it is not strictly required, just performance.

**Closed** 2024-10-19 19:33 UTC
Labels: type: bug :bug:
