### ISSUE TITLE
[2.50.01] Interactive Rebase: Illegal characters in path instead of the edit commit message window during reword/squash.

### ISSUE THREAD

**Issue by GraionDilach** [gitextensions/gitextensions#3848] opened 2017-07-13 10:19 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/1136302/28161676-ab292c1c-67c4-11e7-9b90-bd401a3d2e2a.png)
The program assumes the commit was reworded however, so it passes the rebase with keeping the original commit message in case of reword and the automerged commit message incase of squash.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Do an interactive rebase and select a commit to reword. Alternatively, squash a commit.

**What is the expected behavior?**
The text window appears and you can reword the commit.

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
IIRC 2.48 was the last version I used the reword commit option. I can't pinpoint where this regressed.

**Comment by RussKie** [comment] 2017-07-14 11:50
I couldn't reproduce it in W10 / GE 2.50.01

**Reword:**
1. Create two consecutive commits
![image](https://user-images.githubusercontent.com/4403806/28210936-5ff46a26-68dd-11e7-85b2-524a8e2f31cc.png)
2. Interactive rebase
![image](https://user-images.githubusercontent.com/4403806/28210975-924b8306-68dd-11e7-8bf3-dcbd3960b022.png)
3. Reword
![image](https://user-images.githubusercontent.com/4403806/28210995-a3c763d4-68dd-11e7-9756-a7ea0f3f5d07.png)
4. All good
![image](https://user-images.githubusercontent.com/4403806/28211017-c3e45d20-68dd-11e7-8c36-d031e15100f1.png)

**Squash:**
2. Set to squash
![image](https://user-images.githubusercontent.com/4403806/28211076-201a61a2-68de-11e7-9fe6-ffdb02ff49e2.png)
3. Squashing
![image](https://user-images.githubusercontent.com/4403806/28211106-3fdd9072-68de-11e7-991a-0dc1e0c4aa12.png)
4. All good
![image](https://user-images.githubusercontent.com/4403806/28211118-4dfe9796-68de-11e7-8de6-f45bce810472.png)


Is there something I am missing?

**Comment by vbjay** [comment] 2017-07-14 11:54
Well we actually have a rebase dialog.

**Comment by RussKie** [comment] 2017-07-14 12:10
I find it much simpler and faster to type this... 😊

**Comment by RussKie** [comment] 2017-07-14 12:13
Tried via the dialog as well:

![image](https://user-images.githubusercontent.com/4403806/28211716-7d117d20-68e1-11e7-873c-cdd4f28edfc1.png)
![image](https://user-images.githubusercontent.com/4403806/28211733-89fe7de4-68e1-11e7-9d3d-870b2adcd302.png)
![image](https://user-images.githubusercontent.com/4403806/28211745-9c314ee2-68e1-11e7-9810-95fc2d960906.png)

Still no probs

**Comment by vbjay** [comment] 2017-07-14 12:20
The dialog gives you a lot more help on merge conflicts and gives you more
detail on which step you are on. It also allows you to not worry about
commandline args.

**Comment by vbjay** [comment] 2017-07-14 12:24
@russkie Sounds like he might have had a weird path for the commit message
file.

**Comment by RussKie** [comment] 2017-07-14 12:41
@vbjay  It does...

@GraionDilach could you please provide more info? E.g. screenshots of what you do, repo paths etc...

**Comment by GraionDilach** [comment] 2017-07-14 22:26
Will record a video tomorrow. The repo path is D:\OpenRA-AS-dev. Notsure where the commit message file itself lies - I never learnt to do Git CLT properly.

**Comment by vbjay** [comment] 2017-07-14 22:36
What is the folder named that holds your user profile?

**Comment by GraionDilach** [comment] 2017-07-14 22:40
C:\Users\graio\.

**Comment by RussKie** [comment] 2017-07-15 05:01
The COMMITMESSAGE and COMMIT_EDITMSG are under &lt;your folder&gt;\\.git path

![image](https://user-images.githubusercontent.com/4403806/28236647-45771536-696e-11e7-9eab-9ace7f30b96a.png)

![image](https://user-images.githubusercontent.com/4403806/28236649-5f0971b0-696e-11e7-9b5e-6cb04896ece0.png)

**Comment by GraionDilach** [comment] 2017-07-15 13:51
https://www.youtube.com/watch?v=FImsATE351E

I don't know what am I doing wrong - since I've doing this for years now. Will try older versions to see where this regressed.

**Comment by RussKie** [comment] 2017-07-17 10:09
I shadowed your actions locally and I am not getting any exceptions.... I even re-created commits and commit messages. Very weird.

Can you post the full exception stack trace?

**Comment by GraionDilach** [comment] 2017-07-19 19:59
```
System.ArgumentException: Illegal characters in path.
at Void CheckInvalidPathChars(System.String, Boolean) @ System.IO.Path   
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at GitExtensions.Program.GetWorkingDir(String[] args)
   at GitExtensions.Program.Main()
```

**Comment by RussKie** [comment] 2017-07-20 07:20
I'm running out of ideas...

* Are you able to rebase via the command line without GE?
* Can you rename the folder removing dashes (e.g. d:\OpenRaAsDev) and try again?

**Comment by GraionDilach** [comment] 2017-07-26 14:29
Sorry, was camping last week at a place without any telecommunications service. Apparently using the command prompt within GE works (and gives me the proper GE windows).

On the other hand, I managed to get a note within GE by not closing the console.

```
"C:\Program Files (x86)\Git\bin\git.exe" rebase  -i --autosquash "master"
error: There was a problem with the editor '"C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor'.
Please supply the message using either -m or -F option.
You can amend the commit now, with

  git commit --amend

Once you are satisfied with your changes, run

  git rebase --continue
Done

Press Enter or Esc to close console...
```

**Comment by RussKie** [comment] 2017-07-27 21:46
This looks like a git error.
Does this `C:/Program Files (x86)/GitExtensions/GitExtensions.exe` path exist?

**Comment by GraionDilach** [comment] 2017-07-28 04:55
Now that you mention, I guess the problem lies in the fact that it uses Linux path dashes within the quote-mark, however I can't fix the dashes within GE's Git config window (clicking (Apply then) OK closes the window but doesn't save the change).

**Comment by GraionDilach** [comment] 2017-07-28 05:08
Changing the path manually to the correct dashes throws the same error though. I don't understand why the path works from the Git bash but not through the GE GUI.

**Comment by RussKie** [comment] 2017-07-28 05:45
The slashes don't make any difference, you need `/` for bash
Is the path to GitExtensions.exe correct?

**Comment by RussKie** [comment] 2017-07-28 05:47
To confirm, do you get this problem universally or is it localised to this repo only?

**Comment by GraionDilach** [comment] 2017-07-28 05:53
The path is correct and apparently this happens only with this repo. O_o

**Comment by RussKie** [comment] 2017-07-28 06:01
Ok, at least we localised the problem.
I wonder whether because the repo name contains `-`

**Comment by RussKie** [comment] 2017-10-19 04:32
@GraionDilach are you still having issues with the repo?

**Comment by GraionDilach** [comment] 2017-10-19 05:00
Sorry, forgot your last post. Haven't had to interactive rebase for a good while though. Gonna test it. Although I can't confirm - is causing it, because every repo folder of mine has a suffix which i tend to attach with `-`.

**Comment by RussKie** [comment] 2017-10-19 05:10
could you check whether the issue is affecting a single repo or all of them?
if it is only a single repo, then there is something peculiar about that repo and it would be good if we could establish what that is

**Comment by GraionDilach** [comment] 2017-10-19 05:33
I just found out what caused my issue.

This particular repo of mine is in a hardlinked junction folder and so far I used the junction path within GitExt. Doing the interactive rebase in it's original (non-junctioned) path works. It's still weird how this wasn't an issue until now though.

**Comment by RussKie** [comment] 2017-10-19 12:44
I'm not sure whether the app could do anything to help with that...
Closing now, reopen if you think we need to do anything.

**Closed by RussKie** 2017-10-19 12:44 UTC
Labels: bug, info needed
