### ISSUE TITLE
[NBug] An unexpected internal error occurred in the Win32 call: 80...

### ISSUE THREAD

**Issue by Kableado** [gitextensions/gitextensions#9381] opened 2021-07-15 14:54 UTC
## Error Details
```
System.ComponentModel.Win32Exception: An unexpected internal error occurred in the Win32 call: 8007007E ---> System.IO.FileNotFoundException: No se puede encontrar el módulo especificado. (Excepción de HRESULT: 0x8007007E)

   --- End of inner exception stack trace ---
   at Microsoft.WindowsAPICodePack.Dialogs.NativeTaskDialog.NativeShow()
   at Microsoft.WindowsAPICodePack.Dialogs.TaskDialog.ShowCore()
   at GitUI.NBugReports.BugReportInvoker.Report(Exception exception, Boolean isTerminating)
   at GitExtensions.Program.<>c.<Main>b__1_3(Object s, ThreadExceptionEventArgs e)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, String filter, ObjectId selectedId, ObjectId firstId)
   at GitUI.GitUICommands.RunBrowseCommand(IReadOnlyList`1 args)
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments)
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()

```

## Additional information
After mergin a local branch. While clicking the commit button.

## Environment
- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.32.0.windows.2
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4360.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2021-07-17 11:41
This looks similar to
https://github.com/gitextensions/gitextensions/issues/9166

**Comment by gerhardol** [comment] 2021-08-20 07:27
The beginning of the stack trace is similar to #9429 (and a few others)
Are they the same?

**Comment by gerhardol** [comment] 2021-08-30 20:22
No more info received, assumed to be duplicate of #9429

**Closed by gerhardol** 2021-08-30 20:22 UTC

**Comment by gerhardol** [comment] 2021-09-13 20:50
Please test the portable build in #9566 (currently latest build is https://ci.appveyor.com/project/gitextensions/gitextensions/builds/40747903/artifacts, there may be updates though).
This fixes an issue seen with themes as seen here, if you also could check the GDI object count it would be great.
