### ISSUE TITLE
[v3.0.0-beta001] toolbar FETCH run a git PULL instead of FETCH, and break because ... well it should be a fetch

### ISSUE THREAD

**Issue by tebeco** [gitextensions/gitextensions#5609] opened 2018-10-22 14:07 UTC
## Error for a "fetch"
* Open a repo (2 branch on the remote)
* In the tool bar click the Drop down for "pull"
* `Fetch` is KO
### **why is it generating a `git pull` ? :**
```
"git" pull --progress "origin"
You asked to pull from the remote 'origin', but did not specify a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line.
Done

Press Enter or Esc to close console...
```
v2.51.5 did generate : `"git" fetch --progress "origin"`

`Fetch all` and `Fetch all and prune` seems to work
`"git" fetch --progress "--all" --prune`

## **What is the expected behavior?**
Please run `Fetch` and not `pull` when i click `fetch`

## **Environment you encounter the issue:**
- GitExtensions version: v3.0.0-beta001
- GIT version: 2.18.0.windows.1
- OS version:  Win10
- .NET version: net472

## **Did this work in previous version of GitExtensions (which)?**
Yes (2.51.5 is ok)

**Comment by vbjay** [comment] 2018-10-22 16:16
Duplicate #5420

**Comment by pmiossec** [comment] 2018-10-22 18:34
Yes, that has already been fixed in master.

**Comment by pmiossec** [comment] 2018-10-22 18:48
Mais c'est gentil d'être passé ;-)

**Comment by tebeco** [comment] 2018-10-22 18:53
@pmiossec for once it was for a good feedback ^^

see i even wanted to already used the beta

**Comment by tebeco** [comment] 2018-10-22 18:53
@vbjay thx for the info did not looked for duplicate my bad

**Comment by gerhardol** [comment] 2018-10-22 20:30
Duplicate of #5420

**Closed by gerhardol** 2018-10-22 20:30 UTC
