### ISSUE TITLE
Wrong destination folder shown in Git Clone dialog

### ISSUE THREAD

**Issue by asherber** [gitextensions/gitextensions#4920] opened 2018-05-04 21:12 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug - regression

**What is the current behavior?**

If I right-click in a folder and choose Git Clone, the destination folder shown is the parent of the current folder.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

Destination folder should be the folder I right-clicked in.

**Environment you encounter the issue:**

- GitExtensions version:  2.51.01
- GIT version: 
- OS version:   Windows 10

**Did this work in previous version of GitExtensions (which)?**

Yes -- worked in 2.51. IIRC, this was a bug in some previous version which was fixed, but it appears to have come back.

**Comment by RussKie** [comment] 2018-05-04 22:58
Duplicate of #4855

**Closed by RussKie** 2018-05-04 22:58 UTC

**Comment by asherber** [comment] 2018-05-04 23:34
Sorry, I did search but did not see the other issue.

**Comment by RussKie** [comment] 2018-05-04 23:47
That's ok, please check the test build published in #4855 to confirm the problem is addressed.
