### ISSUE TITLE
File History is not working

### ISSUE THREAD

**Issue by andresaldovega** [gitextensions/gitextensions#10588] opened 2022-12-30 13:39 UTC
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

If you go inside a git repository, right click on a file and try to get the file history:

![image](https://user-images.githubusercontent.com/489969/210075161-e25ca3cf-4525-40ee-8d06-bd0b9f8be6ca.png)

I'm getting this empty screen:
![image](https://user-images.githubusercontent.com/489969/210075381-955e5e57-9422-4ff5-9304-c2807da0bc2e.png)

### Steps to reproduce

Inside a git repository
Right mouse click in any file
Go to Git Extensions
Go to File History
The file history does not show up

**Comment by mstv** [comment] 2022-12-30 13:54
Duplicate of #10537
Resolved by #10546

**Closed by mstv** 2022-12-30 13:54 UTC
Labels: :eyeglasses: status: needs review
