### ISSUE TITLE
[NBug] An unexpected internal error occurred in the Win32 call: 80...

### ISSUE THREAD

**Issue by dallf44** [gitextensions/gitextensions#9394] opened 2021-07-19 00:12 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ComponentModel.Win32Exception: An unexpected internal error occurred in the Win32 call: 8007007E ---> System.IO.FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)

   --- End of inner exception stack trace ---
   at Microsoft.WindowsAPICodePack.Dialogs.NativeTaskDialog.NativeShow()
   at Microsoft.WindowsAPICodePack.Dialogs.TaskDialog.ShowCore()
   at GitUI.NBugReports.BugReportInvoker.Report(Exception exception, Boolean isTerminating)
   at GitExtensions.Program.<>c.<Main>b__1_3(Object s, ThreadExceptionEventArgs e)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

## Additional information
Just pulling data

## Environment
- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.31.1.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4390.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2021-08-20 07:23
Duplicate of #9429

**Closed by gerhardol** 2021-08-20 07:23 UTC
Labels: potential-duplicate
