### ISSUE TITLE
Dark theme partially works in v4

### ISSUE THREAD

**Issue by maxx27** [gitextensions/gitextensions#10361] opened 2022-11-09 03:02 UTC
### Environment

- GitExtensions version: 4.0.0.15569
- GIT version: Git 2.37.3.windows.1
- OS version: Microsoft Windows NT 10.0.19045.0
- .NET version: 6.0.11

### Issue description

1) Starting screen is in _light_ theme completely:

![image](https://user-images.githubusercontent.com/5478638/200726753-6a41c6d8-a71b-4f0f-9f1b-33aa9584c6f3.png)

2) Main screen is in dark theme _partially_:

![image](https://user-images.githubusercontent.com/5478638/200727278-859562e1-866d-43ab-9370-98b51c2dd8f0.png)

### Steps to reproduce

1. Uninstall v3.5.4 (optional?)
2. Install v4.0
3. Change color theme via `Settings > Appearance > Colors > Theme = Dark`. `Colorblind` and `Use system-defined...` are unchecked.
4. Restart Git Extensions
5. Take a look on main window

### Did this work in previous version of GitExtensions?

Dark theme works perfectly in v3.x

**Comment by RussKie** [comment] 2022-11-09 03:26
https://github.com/gitextensions/gitextensions/releases/tag/v4

* Theming is not supported - v3.x relied on EasyHook library to facilitate hooks into Windows API necessary for theming. However, .NET 6 does not support remoting and multiple AppDomain required for those hooks. To date no viable alternative has been found. https://github.com/gitextensions/gitextensions/issues/9191

**Comment by RussKie** [comment] 2022-11-09 03:26
Duplicate of #10312

**Closed by RussKie** 2022-11-09 03:26 UTC
Labels: :eyeglasses: status: needs review

**Comment by maxx27** [comment] 2022-11-09 10:40
It's pity.
Sorry for the inattention.
Thank you for information!
