### ISSUE TITLE
Selected file in commit window is not highlighted

### ISSUE THREAD

**Issue by escherstair** [gitextensions/gitextensions#5877] opened 2018-12-10 09:22 UTC
Report a bug/regression.

When you select a file in commit window, you see the preview in the right pane, but the file name in left pane is not highlighted.

The file name should be highlighted as in version 2.51.05.

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.6.1055.0
- DPI 96dpi (no scaling)

This worked in previous versions (up to 2.51.05).

**Comment by escherstair** [comment] 2018-12-10 09:38
I've just found that the issue happens only if Windows 7 is configured as "Adjust for best performance"

- Click Windows Start button.
- Right-click on Computer and select Properties.
- On the left side of the window, click Advanced System Settings.
- Under the Advanced tab, in the Performance section click Settings.
- Under Visual Effects tab, select “Adjust for best performance”

If you configure "Adjust for best appearance" everything is ok.

**Comment by gerhardol** [comment] 2018-12-10 21:54
In v3 the shading was changed to Windows native format. If that setting is removed, the selection will be lost.
Not sure which setting is is, but this should be documented.

**Comment by RussKie** [comment] 2018-12-11 06:21
I suspect this is a duplicate of #5499

**Comment by escherstair** [comment] 2018-12-11 06:46
Yes. It's a duplicate

**Comment by escherstair** [comment] 2018-12-11 08:09
The Win7 setting that affects this behavior is "Use visual styles on windows and buttons".
If it's enabled, the behavior is ok.

**Comment by RussKie** [comment] 2018-12-11 09:20
Duplicate of #5499

**Closed by RussKie** 2018-12-11 09:20 UTC
Labels: area: user experience, help wanted, status: pull request only

**Comment by tha2015** [comment] 2019-01-17 18:43
> The Win7 setting that affects this behavior is "Use visual styles on windows and buttons".
> If it's enabled, the behavior is ok.

The setting is checked, but I still have the issue on WIndows 7.

**Comment by tha2015** [comment] 2019-01-18 04:59
> @tha2015 have you checked #5499?

I'm sorry but I'm not sure what to look for? I cannot find any workaround in issue #5499 
BTW I'm using GitExtensions 3.00.00.4433 (latest)

**Comment by illfated** [comment] 2019-01-18 05:52
@tha2015 : Did you try different methods of enabling the Windows 7 setting "Use visual styles on windows and buttons"?
- enable the setting "Adjust for best appearance" (which turns on all visual settings)
- enable "Adjust for best performance", then enable "Use visual styles on windows and buttons" (manual setting)
- enable Windows 7 "Aero" theme / Windows 7 default theme

**Comment by tha2015** [comment] 2019-01-24 00:41
Thanks @illfated . It works. 
Note: I used the option 2 ( "Adjust for best performance", then enable "Use visual styles on windows and buttons"). Although I don't really like the new styles, but I guess I will have to live with it.
