### ISSUE TITLE
Message saying This repository does not yet contain any commits.

### ISSUE THREAD

**Issue by rossmd** [gitextensions/gitextensions#10037] opened 2022-06-27 16:18 UTC
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.36.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4510.0
- DPI 96dpi (no scaling)

### Issue description

I cloned a new repo at my work to my local machine. The repo has 5+ years of commits. When I open the repo in Git Extensions, I get an error message that says:
This repository does not yet contain any commits.

There is also a banner saying "There are unresolved merge conflicts". This is also false, as it is a newly cloned repo and I have not made any changes
![2022-06-27 11_16_53-Window](https://user-images.githubusercontent.com/655914/175987943-f14f5d84-240a-4aed-b513-0cd1af39be6a.png)

### Steps to reproduce

Clone repo
Open Git Extensions
Open repo in application

**Comment by pmiossec** [comment] 2022-06-27 17:19
Duplicate of #9977 I think (the workaround is there)

**Closed by pmiossec** 2022-06-27 17:19 UTC
Labels: type: git issue

**Comment by rossmd** [comment] 2022-06-27 18:03
Not sure why this was closed so fast. It is not a duplicate of #9977. I ran this command:

git config --global --unset core.usebuiltinfsmonitor

closed and re-opened Git Extensions and still get the same error. #9977 is just about merge conflicts. This issue is about Git Extensions not even seeing the commits in the repo

**Comment by gerhardol** [comment] 2022-06-27 18:22
This should be a duplicate of #9954

**Comment by rossmd** [comment] 2022-06-27 18:52
Confirmed. Duplicate of #9954. Adding another safe.directory fixed this issues for me
