### ISSUE TITLE
Close button can be bypassed

### ISSUE THREAD

**Issue by taipignas** [gitextensions/gitextensions#10708] opened 2023-02-10 11:01 UTC
### Environment

- GitExtensions version: 4.0.2
- OS version: Windows 10

### Issue description

When clicking outmost right top place sometimes the click goes through and the application in the background get closed instead.

### Steps to reproduce

0. have another application in the background. lets say visual studio
1. move the mouse cursor to the top right corner, maybe move it slightly for few pixels by the edge of the screen
2. the mouse should be on the edge of the close button and the close button dehighlighted
3. click left mouse button
4. visual studio gets closed instead

in this gif i couldn do it because the recorder was in the way, but the principle is visible
![git](https://user-images.githubusercontent.com/55182635/218076000-7c4c9b34-9baa-417c-b1cf-a245981c23a5.gif)

**Comment by pmiossec** [comment] 2023-02-10 11:11
We already discussed about that in the past (I don't remember if it was an issue or just a comment) but that is a windows bug that happen with all the applications with a normal title bar when behind you have an application maximized with a 'new style' title bar containing application defined controls.

So no much that GitExtensions could fix 😕

**Comment by pmiossec** [comment] 2023-02-10 11:14
So duplicate of #7180. See comment https://github.com/gitextensions/gitextensions/issues/7180#issuecomment-533668127

**Closed by pmiossec** 2023-02-10 11:14 UTC
Labels: :eyeglasses: status: needs review
