### ISSUE TITLE
If branch and tag with same name exist, clicking the branch explorer tree will navigate to the tag

### ISSUE THREAD

**Issue by diaconesq** [gitextensions/gitextensions#7403] opened 2019-11-11 15:54 UTC
## Current behaviour

Create a branch named "X". Create a tag also named "X", pointing to a different commit. 

Click branch 'X' in the left panel (the "branch explorer" panel). 

=> In the main window, the _tag_ will be selected.

## Expected behaviour
In the main window, the _branch_ should be selected. 

## Steps to reproduce

See 'current behaviour' above

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-11-11 22:53
https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt-emltrefnamegtemegemmasterememheadsmasterememrefsheadsmasterem

The reference is not fully qualified internally, why the tag is selected before the branch. (See link for the ambiguity priority).

The name should be fully qualified (i.e. "heads/" prefixed to the branch name).
See GitUI\BranchTreePanel\RepoObjectsTree.Nodes.Branches.cs SelectRevision() or FullPath
This code is shared Branches/Remotes so it is not trivial to correct this.

**Comment by RussKie** [comment] 2019-11-18 13:28
I'm going to close it as "by design" as we won't be fixing it any time soon.

**Closed by RussKie** 2019-11-18 13:28 UTC
