### ISSUE TITLE
[NBug] fatal: this operation must be run in a work tree

### ISSUE THREAD

**Issue by tigrom** [gitextensions/gitextensions#11526] opened 2024-01-17 06:49 UTC
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.25
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Users\[username]\AppData\Local\Programs\Git\bin\git.exe
Arguments: --no-optional-locks stash list
Working directory: C:\dev\repo.git\

```
GitExtUtils.ExternalOperationException: fatal: this operation must be run in a work tree
 ---> System.Exception: fatal: this operation must be run in a work tree
   --- End of inner exception stack trace ---
   at async Task<string> GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 129
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTask<T>.CompleteOnCurrentThread()
   at IReadOnlyList<GitStash> GitCommands.GitModule.GetStashes(bool noLocks) in C:/projects/gitextensions/GitCommands/Git/GitModule.cs:line 2464
   at async void GitUI.CommandsDialogs.FormBrowse.UpdateStashCount()+(?) => { } in C:/projects/gitextensions/GitUI/CommandsDialogs/FormBrowse.cs:line 1086
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 28
```

Not sure exactly what is the root cause of this but here's the steps i've made prior to this:
context: https://[bit-bucket-server]/repo.git  trying to mirror on local gitea server based under 192.168.1.2:3000

steps:
1. git clone --mirror https://[bit-bucket-server]/repo.git  -> this will make a local folder repo.git with the whole repo -> "C:\dev\repo.git\" 
2. cd repo.git
3. git remote add giteaRepo http://192.168.1.2:3000/[username]/repo.git
optional:
4. git push giteaRepo --mirror

gitea server is very easy to install. I've installed it under Ubuntu 22.04.3 LTS

### Steps to reproduce

steps:
1. git clone --mirror https://[bit-bucket-server]/repo.git  -> this will make a local with the whole repo "C:\dev\br\repo.git\" 
2. cd repo.git
3. git remote add giteaRepo http://192.168.1.2:3000/[username]/repo.git
optional:
4. git push giteaRepo --mirror

### Did this work in previous version of GitExtensions?

never tested --mirror option with previous versions

**Comment by gerhardol** [comment] 2024-01-17 13:28
Duplicate of #11467 
Fixed in master. Deactivate stash count for now.

--mirror implies --bare that disables most repo operations, not sure if something more is needed.

**Closed by gerhardol** 2024-01-17 13:28 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
