### ISSUE TITLE
"Install just for you" still requires Administrator privilege through UAC on Windows 7

### ISSUE THREAD

**Issue by furiousd** [gitextensions/gitextensions#3105] opened 2016-01-22 14:47 UTC
Using GitExtensions-2.48.05-SetupComplete.msi to setup GitExtensions on a highly-locked Windows 7 computer.  Although the "just for you" installation says it does not need local admin privileges, the installer still invokes Windows UAC when it begins the installation process.

This happens even with the following alterations:
1) full installation (GitExtensions + Msysgit + KDiff3) or minimal (GitExtensions only)
2) Installation path points to default %PROGRAMFILES(X86)%\GitExtensions\ or to user-controlled directory
3) default setup or only GitExtensions enabled (all sub-options like Plugins, etc. disabled)

This issue also appears when using the base installer GitExtensions-2.48.05-Setup.msi and default install parameters; I have not tried any different configurations for this.

**Comment by kyanha** [comment] 2016-04-07 18:37
This also occurs on Windows 10.  Additionally, on my machine there is a policy in place preventing the elevation of unsigned installation packages, which makes this packaging useless to me.

**Comment by KindDragon** [comment] 2016-04-07 21:20
Duplicate of #2434

**Closed by KindDragon** 2016-04-07 21:20 UTC
