### ISSUE TITLE
when do search, the we have the record, but many time will got the exception now.

### ISSUE THREAD

**Issue by szjfhb** [gitextensions/gitextensions#2608] opened 2015-01-13 07:11 UTC
Capture as below:
![image](https://cloud.githubusercontent.com/assets/6204704/5717119/e4e2c728-9b35-11e4-8539-432980443fad.png)
the record really not exist, but even if i check "all branches", and other include the item, still can't show.
below show work right status.
![image](https://cloud.githubusercontent.com/assets/6204704/5717124/111f9aa0-9b36-11e4-901a-552f9c7ba177.png)

dono, why, but please fix it ASAP. old version have no this issue.

I have tried to reinstall it, but can't fix the issue.

**Comment by KindDragon** [comment] 2015-01-22 23:16
Duplicate of #2597

**Closed by KindDragon** 2015-01-22 23:16 UTC
