### ISSUE TITLE
Refreshing remote repository information

### ISSUE THREAD

**Issue by MarkusAnthony** [gitextensions/gitextensions#7070] opened 2019-08-28 16:55 UTC
It appears that some functionality was removed.

I am using Git Extensions with VSTS/Azure Devops. The view/data in Git Extensions is not always up to date. I used to go to Repository | Remote Repositories | "default pull behavior"  -> "Update all remote branch Info" button. But this button has disappeared. 

When I use the pull dialog and drop down "Remote branch" the items in the drop down are not up to date. I need a way (or I need to know how) to update the remote information.

**Comment by pmiossec** [comment] 2019-08-28 18:26
>But this button has disappeared.

The feature has been moved.

You still have 3 ways to achieve that:

- in the left panel, right click on the 'remotes' node and 'Update all'
- on the icon bar, in the fetch / pull, you have a 'fetch all' or 'fetch all and prune'.
- in the plugins, you could enable the 'auto fetch' and you will have just to refresh the revision grid (but that could introduce a risk if you use push with force with lease)

**Comment by gerhardol** [comment] 2019-08-28 19:13
Documentation is not updated:
https://git-extensions-documentation.readthedocs.io/en/master/remote_feature.html#manage-remote-repositories

**Comment by MarkusAnthony** [comment] 2019-08-28 20:02
I do not see how to refresh my repository. If I have co-workers creating new branches, how do I update my view to show the new branches?

    On Wednesday, August 28, 2019, 12:14:11 PM PDT, Gerhard Olsson <notifications@github.com> wrote:  
 
 
Documentation is not updated:
https://git-extensions-documentation.readthedocs.io/en/master/remote_feature.html#manage-remote-repositories

**Comment by gerhardol** [comment] 2019-08-28 20:37
> I have the latest windows version and do not see "Update All".

Fetch all

**Comment by pmiossec** [comment] 2019-08-28 21:19
>I have the latest windows version and do not see "Update All".

Look at #6301

>I could not find this

In the plugin menu. 

>This worked, although not fast.

That is the exactly same feature than the one in the remote form (just moved in a better place). And if that's slow, that's mostly a git problem, I think...

**Comment by gerhardol** [comment] 2019-08-30 20:01
Closing, this is as intended
But the documentation should be updated

**Closed by gerhardol** 2019-08-30 20:01 UTC
