### ISSUE TITLE
[NBug] Out of memory.

### ISSUE THREAD

**Issue by TheItalianJojo** [gitextensions/gitextensions#11077] opened 2023-06-26 18:17 UTC
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.19
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.OutOfMemoryException: Out of memory.
   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.FormChooseTranslation.OnLoad(EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\SettingsDialog\Pages\FormChooseTranslation.cs:line 35
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 106
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Tried to clone a repository, this error message popped up. Before, after installing git, gitext and kdiff3, I had a bsod reporting a system server exception with logs saying it was ID 41.

### Steps to reproduce

Not sure if the BSOD mattered or not, but I'll describe it anyway:

- After installing gitext, have a SYSTEM_SERVER_EXCEPTION BSOD with the windows logs saying the issue's ID is #41;
- Open a folder, try to clone a repository;
- Nothing happens, open gitext on desktop;
- Error pops up.

### Did this work in previous version of GitExtensions?

No idea, this is my first time running gitext on the new machine.

**Comment by TheItalianJojo** [comment] 2023-06-26 18:18
Update, just retrying to open gitext did open gitext in the end.

**Comment by gerhardol** [comment] 2023-06-26 20:00
Duplicate of #10372 
Duplicate of #9633
Check sizes of GitExtensions\Translation\*.gif

**Closed** 2023-07-18 19:00 UTC
Labels: potential-duplicate, :zzz: status: no recent activity, :mailbox_with_no_mail: needs: author feedback
