### ISSUE TITLE
GITExt Repo Browser crashes when Filter search string returns no results

### ISSUE THREAD

**Issue by BraveNewMath** [gitextensions/gitextensions#2640] opened 2015-02-03 18:20 UTC
--- GitExtensions2.48.03, Git 1.9.5.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by KindDragon** [comment] 2015-02-04 08:16
Duplicate of #2582

**Closed by KindDragon** 2015-02-04 08:16 UTC
