### ISSUE TITLE
[bug linux GUI] Browse button does not appear

### ISSUE THREAD

**Issue by gpongelli** [gitextensions/gitextensions#4181] opened 2017-11-29 13:20 UTC
**Do you want to request a *feature* or report a *bug*?**
It's a bug.

**What is the current behavior?**
"Browse" button is not present in "Open local repository" dialog.

![image](https://user-images.githubusercontent.com/842026/33376888-bd634026-d50f-11e7-8e49-5659a576dbd7.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Download release [GitExtensions-2.50.02-Mono.zip](https://github.com/gitextensions/gitextensions/releases/download/v2.50.02/GitExtensions-2.50.02-Mono.zip)
- Follow setup as explained [here](https://github.com/gitextensions/gitextensions/wiki/Git-Extensions-on-Linux-Mono)
- Run GitExtensions
- Choose "Open" from "Start" menu

**What is the expected behavior?**
"Browse" button appears, as it does in windows release.

**Environment you encounter the issue:**
- GitExtensions version: 2.50.02 Mono
- GIT version:  2.7.4 Ubuntu package
- OS version:  Ubuntu 16.04

**Comment by RussKie** [comment] 2017-11-29 20:53
Duplicate of #4132

**Closed by RussKie** 2017-11-29 20:53 UTC
