### ISSUE TITLE
GE start hangs and non-responding after long time

### ISSUE THREAD

**Issue by arisliang** [gitextensions/gitextensions#8337] opened 2020-07-18 06:40 UTC
## Current behaviour

GE start hangs and non-responding after long time

## Expected behaviour
GE should start immediately.

## Steps to reproduce

Suspect this may have to do with previous repositories (using network drive) if they're no longer available.

## Screenshots

![image](https://user-images.githubusercontent.com/1115503/87846673-32598080-c904-11ea-96e5-918cedd697f9.png)

## Environment

![image](https://user-images.githubusercontent.com/1115503/87846720-89f7ec00-c904-11ea-8dc3-1287b1a6381b.png)

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

**Comment by gerhardol** [comment] 2020-07-18 21:31
Can you debug this?

I do not see the problem when testing with an USB drive

If a repo is not accessible, it shows up like:
![image](https://user-images.githubusercontent.com/6248932/87862285-93a64180-c94e-11ea-8f56-20a510b2861b.png)

If you select it:
![image](https://user-images.githubusercontent.com/6248932/87862287-a3be2100-c94e-11ea-90b7-2fb77f9a2676.png)

**Comment by mstv** [comment] 2020-07-18 21:47
Attempts to access network drives might take long to timeout if there is a working network connection but e.g. no ICMP feedback "host unreachable".
Perhaps these checks must be parallized.

**Comment by arisliang** [comment] 2020-07-20 03:51
>Perhaps these checks must be parallized

Yes, please make it parallel. They shouldn't block the ui if they're not available. And they're not "invalid" repository, just not available under some network, so they shouldn't be removed.

**Comment by digitalcoyote** [comment] 2020-10-02 03:08
I'd like to take a shot at this. Just to confirm, the problem is that Network timeouts can take some time to complete and it's currently checking them synchronously meaning that a 30 second timeout for a network share could be multiplied 10, 20, X times causing it to appear the application itself has frozen?

**Comment by RussKie** [comment] 2020-10-02 06:15
> I'd like to take a shot at this.

Thank you @digitalcoyote, assigning to you.



> Feedback welcome.

Please raise a draft PR, so everyone interested can provide feedback.
Thank you.

**Closed** 2020-10-21 09:50 UTC
Labels: :beetle: type: bug, :construction: status: in progress, type: feature request, up-for-grabs
