### ISSUE TITLE
NPE on closing settings dialog

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#4160] opened 2017-11-17 06:29 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
NPE

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Commit some changes
2. Close commit dialog
3. Open settings dialog
4. Close settings dialog

- GitExtensions version: bf8c2ffa0af5369ba8ba38544727f0cc87134aef

**Comment by RussKie** [comment] 2017-11-17 10:51
Is that for `VRulerPosition`?
I've been getting it for some commits but not the others. I even started looking at getting it fixed and got distracted with something else...

**Comment by jbialobr** [comment] 2017-11-17 11:34
Yes, it is it.

**Comment by RussKie** [comment] 2017-12-17 10:59
It looks like this change caused other regressions. I am constantly getting `InvalidOperationException` when closing the app under VS. I am also unable to run the translation app...

![image](https://user-images.githubusercontent.com/4403806/34078784-3269a8ec-e375-11e7-8510-84f971fbfac6.png)
![image](https://user-images.githubusercontent.com/4403806/34078787-4a1c0214-e375-11e7-8750-1844afff57e2.png)

**Comment by jbialobr** [comment] 2017-12-17 13:22
InvalidOperationException is caught and interpreted as false in IsUICommandsInitialized.
Does the translationApp crashes due this change.
Perhpas your issue should be reported as a request for design change - this issue should remain closed.

**Comment by RussKie** [comment] 2017-12-17 13:29
ok
i'll raise a new one tomorrow

On 18 December 2017 at 00:22, Janusz Białobrzewski <notifications@github.com

**Closed** 2017-12-18 09:44 UTC
Labels: bug
