### ISSUE TITLE
Git Extension keeping CPU utilization about 30% after Commit dialog opened

### ISSUE THREAD

**Issue by lalberto8085** [gitextensions/gitextensions#3836] opened 2017-07-11 17:12 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug  

**What is the current behavior?**
The CPU utilization is at around 30% for Git Extensions even when idle on the background doing nothing, I don't have auto-fetch nor Build Server Integration enabled 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

My repository has been active for well over 3 years now, and even though I don't know the exact number, there are a few thousand commits on it. I opened a local repo, with about 10 commits on it and utilization was as expected.

**What is the expected behavior?**

After finishing loading a repo or doing whatever operation needed performing the CPU utilization will drop to (or near) `0` 

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**

I have been working with GitExtensions for about 5 years now,  I'm in the latest version: `2.50.00` 

``` bash
$ git version
git version 2.12.2.windows.2
``` 
   
Windows 10 build 15063

I  started noticing the high CPU usage about two versions ago, but I thought it would get picked up by somebody else and fixed on upcoming versions, hope this is helpful.

Thank you

**Comment by vbjay** [comment] 2017-07-11 17:32
Show the command log during a time it is doing this.

**Comment by vbjay** [comment] 2017-07-11 17:39
A shot in the dark. I think the build server checks might be updating on
each commit.

**Comment by lalberto8085** [comment] 2017-07-11 18:39
Here is a screen shot of the log, I don't know how to export it as text:

![image](https://user-images.githubusercontent.com/4626669/28084477-b9302ccc-6646-11e7-926f-d6d5e3bedf1a.png)

**Comment by lalberto8085** [comment] 2017-07-11 18:48
How can I figure out about the build server?

**Comment by vbjay** [comment] 2017-07-11 19:06
It is listing the files over and over. That is the problem.

**Comment by lalberto8085** [comment] 2017-07-11 19:21
So what can I do to prevent this?

**Comment by vbjay** [comment] 2017-07-11 19:22
Do you have the option to show working directory changes set?

**Comment by lalberto8085** [comment] 2017-07-11 19:27
Nope:

![image](https://user-images.githubusercontent.com/4626669/28086532-5af7bcf4-664d-11e7-96fd-687bb7fcd406.png)

And I halved the # of commits to be loaded at startup

**Comment by RussKie** [comment] 2017-07-13 09:32
I get the same all the time. I think it generally happens to the large repos.
Perhaps we need to make how often `git status --porcelain` command is run.

**Comment by jbialobr** [comment] 2017-07-17 11:17
Please update git to 2.13.x version as 2.12 has broken the `git status` command.
Let us know if that helped.

**Comment by lalberto8085** [comment] 2017-07-17 12:04
Updating it worked just fine, I have opened the issue-causing repo and CPU utilization is down to 0 since it’s inactive

 

Thank you very much

**Comment by lalberto8085** [comment] 2017-07-18 16:14
I hate to be this insistent, but after I updated to the latest version of Git for windows everything seemed to be working fine, but then I also updated to a new version of GitExtensions and it all went back to the same high CPU usage. Should I rollback to the older version of GitExtensions?

**Comment by lalberto8085** [comment] 2017-11-07 18:59
@RussKie could you please tell me about the workaround I read the issue linked to this one by you, and I still couldn't find it

**Comment by RussKie** [comment] 2017-11-07 21:07
The workaround was to update git from 2.12 version, as per your report it worked.
In my case I have formed an opinion McAfee is to blame for my ongoing performance issues on my work laptop. On my home computer and laptops (even virtualised) everything flies.

In essence GE is a a automation tool which executes git command on users behalf. There is little to no magic to how GE works, most likely external factors to are to blame.

**Comment by lalberto8085** [comment] 2017-11-07 21:11
It worked right after I installed the new GIT, however after I closed and opened GE the same thing kept on happening, I continued on the issue later on but since it was already closed, there wasn't much else I could do. To this day I still have to deal with this issue. I thought there was something else I could do 😞

**Comment by RussKie** [comment] 2017-11-07 21:30
See if unchecking all of these make any difference:

![image](https://user-images.githubusercontent.com/4403806/32518870-0246b16c-c45f-11e7-80b9-841fcdbe7fae.png)

**Comment by lalberto8085** [comment] 2017-11-08 00:52
I unchecked them all and it seemed to work but after opening the commit dialog it went back to gobble up CPU as usual

**Comment by RussKie** [comment] 2017-11-08 01:05
So it it happening only when the commit dialog is open?

**Comment by lalberto8085** [comment] 2017-11-08 01:57
Nope, when GE starts it behaves as usual, uses a lot of CPU on startup (as expected) and then goes idle, until the commit dialog is open, after that it goes back to about 30% CPU usage

**Comment by vbjay** [comment] 2017-11-08 02:07
After you close the dialog, does it go back down?

**Comment by lalberto8085** [comment] 2017-11-08 02:10
Once the dialog is opened, CPU usage it stays up until GE is closed and opened again, as if it triggered something

**Comment by lalberto8085** [comment] 2017-11-08 02:14
Just to be clear, the CPU usage goes down ONLY if I deselect all options as suggested by @RussKie above, otherwise it stays up from the start

**Comment by RussKie** [comment] 2017-11-08 02:16
is it happening for a specific repo or all repos?

**Comment by lalberto8085** [comment] 2017-11-08 02:17
For one large repo, about 4 years old

**Comment by RussKie** [comment] 2017-11-08 02:32
so there is probably something peculiar about this repo.

may be try:
* a new clone of the repo to a differ location
* the repo on a different workstation

Also run something like procmon.exe and see what it happening behind the scene

**Comment by lalberto8085** [comment] 2017-11-08 15:51
I just tried an old repo from work which I haven't work on for a while but it's still active, and its about 1 year old, and still the same behavior. My guess is that once the repo grows large enough, the CPU usage starts, the ones that didn't use that much CPU were fairly small ones, less than 100 commits, so maybe it has something to do with it

**Comment by RussKie** [comment] 2018-09-25 11:13
Please try the beta of v3 and see if the issue is fixed.

**Comment by RussKie** [comment] 2019-01-07 07:55
Closing due to age and lack of follow up.

**Closed by RussKie** 2019-01-07 07:55 UTC
Labels: status: more info requested
