### ISSUE TITLE
'Show remote branches' does not toggle remote branches to be displayed after click

### ISSUE THREAD

**Issue by imnickvaughn** [gitextensions/gitextensions#7328] opened 2019-10-18 14:48 UTC
![Annotation 2019-10-18 104943](https://user-images.githubusercontent.com/24948723/67104487-0a7e9600-f195-11e9-9ffc-f3b57a6323ef.png)
![Annotation 2019-10-18 104943](https://user-images.githubusercontent.com/24948723/67104552-25510a80-f195-11e9-8113-12cb6fb6e798.png)
![Annotation 2019-10-18 104943](https://user-images.githubusercontent.com/24948723/67104660-55001280-f195-11e9-9584-aa93fd7c030b.png)

**Do you want to request a feature or report a bug?**
bug

**What is the current behavior?**
checking the 'Show remote branches' does not toggle all remote branches

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
View --> 'Show remote branches'

**What is the expected behavior?**
In case the 'Show remote branches' is false --> After clicking 'Show remote branches' I expect the remote branches to be displayed
In case where the 'Show remote branches' is true--> After clicking 'Commands' > 'Push...' I expect that remote branch to be displayed

**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3460.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment] 2019-10-18 20:35
Looking at your screenshots, I see nothing shocking.

On every images, I see the 'remote branches' (in green).

Can you give us more details of what is wrong because I never encountered the problems in years of use. Even better, create a gif with screen2gif, please.

**Comment by imnickvaughn** [comment] 2019-10-22 21:32
Yea kind of ambiguous.  Thanks for the tip.  Here is a Gif.
![gitExtPossibleBug1](https://user-images.githubusercontent.com/24948723/67335550-e226cc80-f4f1-11e9-849e-1ab140573ff7.gif)

**Comment by gerhardol** [comment] 2019-10-22 22:08
The green remote label immediately is visible to me.
Without looking at the code, the remote tracking and thereby the remote branch should not be stored unless the Git command is successful

**Comment by pmiossec** [comment] 2019-10-22 22:14
I wonder if it's not the name of your branch which is too long and so Gitextensions is unable to display the 2 ref, local and remote, on the revision line.

Try to verify that the remote is well created. Things you could try:
- look at the tool tip when hovering the line to see if the remote is displayed at the bottom
- look in the left panel if the remote is there
- rename the local branch to a temporary very short name (like 'a') to see if that gave some place to display the remote.

**Comment by RussKie** [comment] 2019-10-22 23:22
> I wonder if it's not the name of your branch which is too long and so Gitextensions is unable to display the 2 ref, local and remote, on the revision line.

That isn't a problem
![image](https://user-images.githubusercontent.com/4403806/67342691-979f6180-f57e-11e9-8344-b89413d5f7cc.png)


@imnickvaughn are you able to verify the branch is pushed to the remote? E.g. via a web UI, or do a clone of the repo to another folder and see if the branch you pushed is there.

Can you also push via git bash, and then refresh GE to see whether the branch is there?

**Comment by imnickvaughn** [comment] 2019-10-23 14:03
Thank you for all the helpful suggestions.

@gerhardol So are you saying you do not know why this is failing?

@pmiossec @RussKie  let me know if the tests below are what you had in mind.  Thanks. 

"look at the tool tip when hovering the line to see if the remote is displayed at the bottom
look in the left panel if the remote is there"
![image](https://user-images.githubusercontent.com/24948723/67399543-66249700-f57a-11e9-81e5-dbafbdfc486a.png)

"rename the local branch to a temporary very short name (like 'a') to see if that gave some place to display the remote."
![gitExtPossibleBug2](https://user-images.githubusercontent.com/24948723/67400078-27dba780-f57b-11e9-92ea-094e75a7b104.gif)

"Can you also push via git bash, and then refresh GE to see whether the branch is there?"
![gitExtPossibleBug3](https://user-images.githubusercontent.com/24948723/67400088-2ad69800-f57b-11e9-881f-aa3956e43c57.gif)
It says everything is up to date, pretty sure that confirms it is actually pushed.  Also, I can confirm it is pushed in Gitlab because I can see it only when I push and only then it will let me merge.

**Comment by gerhardol** [comment] 2019-10-24 22:14
> So are you saying you do not know why this is failing?

I have not looked at this specific case, but the revision grid is refreshed after all data is added.
Please check if a remote tracking branch is added in the push dialog
Git Command Log is required too.

What if you pull after push?

**Comment by mstv** [comment] 2019-11-08 21:52
I cannot reproduce this issue, also not with an untracked branch.
The pushed branch appears in the left panel, regardless of `View | Show remote branches`.

**Comment by imnickvaughn** [comment] 2019-12-04 17:48
Sorry for no reply just hoping to show something here, but no progress. I tried reinstalling with no success.

> What if you pull after push?

Same behavior it seems. See below:
![GitExtIssue1](https://user-images.githubusercontent.com/24948723/70165365-cc7bf980-1690-11ea-9a40-0aa648320af1.gif)

My initial hunch was some security-related issue...
Wondering, when you go to the left panel, right-click on Remotes, and click on Manage within the context menu, then finally click "Test Connection" what happens for you?
Thinking I need to provide Auth details
![image](https://user-images.githubusercontent.com/24948723/70167222-406bd100-1694-11ea-8be0-1a1061365002.png)

**Comment by RussKie** [comment] 2019-12-04 23:11
Try using OpenSSH?

**Comment by imnickvaughn** [comment] 2019-12-17 22:14
This is happening in other repos, but a clone of the same repo is showing correctly...  So problem solved right. I don't know how this is as both were cloned in the same way but if I figure out the differences between the two I will list them here.  Thanks for trying to help me.
![image](https://user-images.githubusercontent.com/24948723/71037427-9fe2cb80-20ed-11ea-8aff-a2213a300348.png)

**Comment by RussKie** [comment] 2019-12-18 09:54
I'm going to close it, please ping back if you get more info, and we'll re-open it.

**Closed by RussKie** 2019-12-18 09:54 UTC

**Comment by johannestophoj** [comment] 2022-08-18 09:13
I had this problem, searched high and wide coming across this issue several times and gave up for a while. I just found out that my problem was that I had clicked the 'Show first parent' button which significantly prunes the branch tree. Hope this helps someone
