### ISSUE TITLE
As of commit 613335552, commit dialog eats CPU (and periodically locks up)

### ISSUE THREAD

**Issue by wplpgr** [gitextensions/gitextensions#3430] opened 2016-11-22 05:59 UTC
I've just updated to the latest master and noticed that whenever the commit dialog is open one CPU core goes to 100% usage. There is also a certain amount of flickering of text. Performance seems to be laggy, and after commits I've been getting a complete lock-up of the user interface perhaps 1-in-4 times.

The problem doesn't occur at the v2.49 tag, and git bisecting indicates that the problem started in commit 613335552 ("refactor: Management of remote repositories"), and in particular this change to GitUI/CommandsDialogs/FormCommit.Designer.cs:

        protected override CreateParams CreateParams
        {
            get
            {
                var cp = base.CreateParams;
                cp.ExStyle |= 0x02000000;    // Turn on WS_EX_COMPOSITED
                return cp;
            }
        }

Reverting just this back to its original (i.e., removing it), makes the CPU usage problem go away.

**Comment by ghanique** [comment] 2016-11-22 06:49
I found the following (
https://social.msdn.microsoft.com/Forums/vstudio/en-US/ca0e6cc1-8e03-4dfc-832d-0a7a6ae38d56/can-someone-explain-wsexcomposited?forum=vcgeneral
):

"WS_EX_COMPOSITED works by forcing child windows to draw back to front and
by double buffering them; however, the double buffering used by
WS_EX_COMPOSITED for the child windows conflicts with the double buffering
used by WS_EX_LAYERED windows and DWM so it does not remove the flicker in
those contexts."

Does Git Extensions also use WS_EX_LAYERED?

**Comment by wplpgr** [comment] 2016-11-22 06:52
The other part of the commit to the same file was to add the following to GitExtensionsFormBase():

            this.SetStyle(
                ControlStyles.AllPaintingInWmPaint |
                ControlStyles.UserPaint |
                ControlStyles.DoubleBuffer |
                ControlStyles.OptimizedDoubleBuffer,
                true);

So, yes, it looks like that may well be what is happening.

**Comment by jbialobr** [comment] 2016-11-22 09:03
The locks are fixed in https://github.com/gitextensions/conemu-inside/commit/b5a3d51777c85a9aeee534c382b5ccbb86b485d3, but the high cpu usage remains unsolved.

/cc @RussKie

**Comment by wplpgr** [comment] 2016-11-22 09:14
(Damn. Must have accidentally hit "close and comment" rather than "comment"! Sorry about that.)

The high CPU usage disappears if you turn off the WS_EX_COMPOSITED flag.

Whether that is the correct fix is a different matter. ghanique's linked article gives a fairly convincing explanation as to why turning on COMPOSITED and double buffering elsewhere does the  wrong thing. I'm just not sure what the conclusion is in terms of which approach to double buffering should be used: the SetStyle or the compositing.

**Comment by RussKie** [comment] 2016-11-22 10:47
Wow... Unintentional on my part. Haven't observed the issue personally
despite running multiple instances on several machines all around the
clock.

I have no dramas for my change to be rolled back if it causes issues. In my
tests it have seemed to make a positive difference, but "works on my
machine" is not an excuse.

**Comment by pmiossec** [comment] 2016-11-23 01:24
Just to tell that I have the regression too, that I spend nearly 2 hours to find the code introducing it and just saw this issue just before wanting to create a new issue :(
(I didn't see the issue in the issue list before investigating. 2 hours of sleep lost..... 😫 👎 )

**Closed** 2016-11-23 03:59 UTC
Labels: bug

**Comment by RussKie** [comment] 2016-11-26 12:52
`SetStyle(...)` call isn't needed, but without the `WS_EX_COMPOSITED` the remotes management form is badly flickering...

Can any of your guys affected by the problem restore just `CreateParams` bit and see if the problem remains?

        protected override CreateParams CreateParams
        {
            get
            {
                var cp = base.CreateParams;
                cp.ExStyle |= 0x02000000;    // Turn on WS_EX_COMPOSITED
                return cp;
            }
        }

I'm really bewildered by the problem, I've used `WS_EX_COMPOSITED` in countless projects and never experienced the described issue...

**Comment by wplpgr** [comment] 2016-11-27 09:18
Doing the WS_EX_COMPOSITED (with or without the SetStyle double buffering) causes high CPU usage.

Doing just the SetStyle (w/ double buffering) is fine.

This is on WIndows 10.0.10586, compiled with VS2015 Express (update 3), .NET Framework 4,6,01038 (probably - that's what Visual Studio claims, anyway).

**Comment by wplpgr** [comment] 2016-11-27 13:46
The main comment I can find about high CPU usage and WS_EX_COMPOSITED is about the compositing interacting with the WM_PAINT event and triggering a repaint loop. The "obvious" candidate on the commit form seems to be GitUI.SpellChecker.SpellCheckEditControl, which does some custom paint event handling in WndProc - could it be interacting badly with the compositing mechanism?

This is a complete guess - I'm really not a C#/.NET person :smile:

**Comment by RussKie** [comment] 2016-11-28 13:13
Thank you for the tests... It's more a Win32/Winforms issue than C# per se... I haven't touched Win32/Winforms in ages myself.
It is hard for me to try to debug/suggest a fix without experiencing the high cpu bug...

**Comment by vbjay** [comment] 2016-11-28 16:19
Why use express when community is free?

**Comment by drauch** [comment] 2016-11-28 17:43
@vbjay :
> Why use express when community is free?
To my understanding, you are only allowed to use the community edition if you do not sell your software.

**Comment by vbjay** [comment] 2016-11-29 01:28
Dead wrong. Read usage section. https://www.visualstudio.com/vs/community/

**Comment by wplpgr** [comment] 2016-11-29 06:02
Much as I would love to join in a discussion about the toolset I use (answer: I'm not a student, my day job is not working on open source, and I'm not an individual developer), it is irrelevant to this issue. Please stay on topic.

**Comment by pmiossec** [comment] 2016-11-29 23:14
I confirm @wplpgr diagnostic. The problem is with `WS_EX_COMPOSITED`. I've got it with Win7 and VS2015 Community.

>SetStyle(...) call isn't needed, but without the WS_EX_COMPOSITED the remotes management form is badly flickering...

@RussKie I don't see such a flickering...

**Comment by vbjay** [comment] 2016-11-29 23:20
Forms have a double buffered property. Unless we have some crazy painting
going on in the remotes we shouldn't need it.

**Comment by vbjay** [comment] 2016-11-29 23:37
https://msdn.microsoft.com/en-us/library/system.windows.forms.control.doublebuffered(v=vs.110).aspx

**Comment by vbjay** [comment] 2016-11-29 23:41
Composted implies double buffering

WS_EX_COMPOSITED0x02000000L

Paints all descendants of a window in bottom-to-top painting order using
double-buffering. For more information, see Remarks. This cannot be used if
the window has a class style of either CS_OWNDC or CS_CLASSDC.

Windows 2000:  This style is not supported.

**Comment by KindDragon** [comment] 2016-11-29 23:43
Double buffered is set because of flickering https://github.com/gitextensions/gitextensions/commit/77bf3b610138824b5f02d55e6f3ed7f0425847d1

**Comment by vbjay** [comment] 2016-11-29 23:50
Then get rid of composting.

**Comment by wplpgr** [comment] 2016-11-30 05:57
The original commit that introduced the problem on my platform did turn double-buffering on for GitExtensionsFormBase (along with the compositing).

Like @pmiossec I don't see any flickering on the remotes management dialog (or, in fact, any other), so I can't test whether the double-buffering change alone fixes the flickering problem - I'm guessing that it doesn't otherwise there would have been no need to turn on compositing.

@RussKie Can you confirm that just the double-buffering change you made (without the compositing) didn't stop the flickering?

**Comment by RussKie** [comment] 2016-12-03 04:42
I've done a few screencasts:

* As it is at the latest master - the listview on the remotes form is flickering when the form is resized: http://webm.land/media/EvJl.webm
* With SetStyles only - they don't help, flicker remains: http://webm.land/media/B6NU.webm
* With WS_EX_COMPOSITED only - flicker is gone: http://webm.land/media/JqCY.webm
