### ISSUE TITLE
Commit button changes width (after you changed a file the number of changes will be displayed)

### ISSUE THREAD

**Issue by bernd-herzog** [gitextensions/gitextensions#3550] opened 2017-02-24 14:51 UTC
This always happens a moment before you want to click on the pull button on the right and the commit button gets misclicked.

Solution: Place the commit button to the right.

Also: The buttons in the pull menu strip could easily fit into the menu bar for increased productivity.

**Comment by gerhardol** [comment] 2018-08-25 21:44
I suggest this is closed as a duplicate of #1931

**Comment by RussKie** [comment] 2018-08-25 23:32
Duplicate of #1931

**Closed by RussKie** 2018-08-25 23:32 UTC
Labels: area: user experience, type: feature request
