### ISSUE TITLE
Opening context menu (right-click) in commit window hides it

### ISSUE THREAD

**Issue by Venom31** [gitextensions/gitextensions#3951] opened 2017-08-29 10:28 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
In GitExtensions v2.50.01, right-clicking while commit window is open displays the correct context menu for the commit window area that was clicked on but hides the commit window itself.

After that, left-clicking elsewhere makes commit window show up again without closing the context menu. Also, choosing any option from the context menu while commit window is hidden works, but you have to left-click anyway to make it reappear and see the result.

**What is the expected behavior?**
Expected behavior is not hiding the commit window in the first place.

Environment:
- GitExtensions version: 2.50.01
- GIT version: 1.9.4-preview20140929
- OS version: Windows 7 Pro SP1

**Did this work in previous version of GitExtensions (which)?**
The previous version of GitExtensions I used was 2.48.03 (I believe), this behavior worked as expected then.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Step-by-step demonstration
Right-click to open context menu:
![2017-08-29_13-04-06 1](https://user-images.githubusercontent.com/22825288/29816632-7bd9c66a-8cbd-11e7-94ff-0fc0fe94bd07.png)

Result:
![2017-08-29_13-05-48 2](https://user-images.githubusercontent.com/22825288/29816857-7edea7e4-8cbe-11e7-9b8f-704888b5099b.png)

Left-click - goes back to normal:
![2017-08-29_13-06-05 3](https://user-images.githubusercontent.com/22825288/29816633-7bf2f388-8cbd-11e7-9928-216defe5a1ce.png)

**Comment by RussKie** [comment] 2017-08-29 10:36
Please search before raising a new issue.
Duplicate of #3593 

Please [disable the ConEmu](https://git-extensions-documentation.readthedocs.io/en/latest/settings.html#detailed-browse-repository-window-console-emulator-show-the-console-tab) and restart the GE.

**Closed by RussKie** 2017-08-29 10:36 UTC

**Comment by Venom31** [comment] 2017-08-29 12:30
Wasn't able to find it, sorry.
