### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by tombresson** [gitextensions/gitextensions#6720] opened 2019-05-31 15:23 UTC
## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BackgroundFetch.BackgroundFetchPlugin.<>c__DisplayClass10_0.<RecreateObservable>b__1(Int64 i)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.ScheduledObserver`1.Dispatch(ICancelable cancel)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by tombresson** [comment] 2019-05-31 15:24
Looks like others have already reported this. 

The function I was performing when GitExt crashed was just switching repos with the Recent Repo drop-down menu in the main GUI.

**Comment by sharwell** [comment] 2019-05-31 15:27
Duplicate of #6579

**Comment by RussKie** [comment] 2019-06-10 13:22
I can't repro it.
I enabled the background fetch plugin, set it to fetch everything every 2sec and kept on switching repos for good 10 minutes... No crashes.

I can speculate that under some strange conditions `_currentGitUiCommands.GitModule` is `null`...

**Comment by gerhardol** [comment] 2019-06-10 21:57
Investigated briefly: https://github.com/gitextensions/gitextensions/issues/6579#issuecomment-500249601

To reproduce, you likely need to switch repo when fetching, maybe by adding a delay to the fetch command.

**Comment by RussKie** [comment] 2019-06-26 13:43
Just happened to me, though it was pretty random:
![image](https://user-images.githubusercontent.com/4403806/60184630-beb58300-986b-11e9-9ca7-496d9479bdf4.png)

**Comment by RussKie** [comment] 2019-06-26 13:57
Curiously enough we use a captured `gitModule` variable in some places, but not others...
![image](https://user-images.githubusercontent.com/4403806/60185854-fd4c3d00-986d-11e9-9fc0-ae0320c69bba.png)

**Closed** 2021-08-08 06:18 UTC
Labels: :bug: type: bug, area: plugins, :eyeglasses: status: needs review, :question: status: incorrectly filled template
