### ISSUE TITLE
[NBug] Input string was not in a correct format.

### ISSUE THREAD

**Issue by splerp** [gitextensions/gitextensions#8367] opened 2020-07-31 04:21 UTC
I had a quick look for existing issues, and while a couple have matching exceptions, the steps to reproduce seem to be very different.

## Current behaviour
Selecting Unicode (UTF-7) as the encoding for the diff viewer results in a crash

## Expected behaviour
No crash

## Steps to reproduce
1. Open repo
1. Select a commit to view details in Commit tab
1. Swap to Diff tab
1. Mouse over diff window to reveal diff viewer controls
1. Open text encoding dropdown (currently selected: Unicode (UTF-8)
1. Select Unicode (UTF-7)

![image](https://user-images.githubusercontent.com/6793910/88999838-080eb680-d339-11ea-841e-e3a542d2620f.png)

## Error Details
```
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at GitUI.Editor.Diff.DiffLineNumAnalyzer.Analyze(String diffContent)
   at GitUI.Editor.Diff.DiffViewerLineNumberControl.DisplayLineNumFor(String diff)
   at GitUI.Editor.FileViewerInternal.SetText(String text, Action openWithDifftool, Boolean isDiff)
   at GitUI.Editor.FileViewer.<>c__DisplayClass103_0.<ViewPatchAsync>b__0()
   at GitUI.Editor.FileViewer.ShowOrDeferAsync(Int64 contentLength, Func`1 showFunc)
   at GitUI.Editor.FileViewer.<ViewPatchAsync>d__103.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.RevisionDiffControl.<ShowSelectedFileDiffAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.RevisionDiffControl.<<DiffText_ExtraDiffArgumentsChanged>b__39_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
In the Diff changes window, opened the encoding dropdown and changed from Unicode (UTF-8) to Unicode (UTF-7)

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.23.0.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2020-07-31 04:23
It's worth noting that UTF7 is made obsolete in Windows and .NET Core, so
it is recommended not to use it.

**Comment by RussKie** [comment] 2020-07-31 15:02
https://github.com/dotnet/docs/issues/19274

**Comment by gerhardol** [comment] 2020-08-29 11:16
Duplicate of #7146

**Closed** 2020-12-08 04:18 UTC
Labels: :construction: status: in progress, potential-duplicate
