### ISSUE TITLE
Dark theme is not working for latest version

### ISSUE THREAD

**Issue by nugo-cell** [gitextensions/gitextensions#10496] opened 2022-12-06 07:35 UTC
### Environment

- GitExtensions version: latest v.4.0
- GIT version: 2.35.1.2
- OS version: Windows 11
- .NET version: 6

I tried the latest version very briefly. The dark theme was not working as it did before, so now I have downgraded again to v.3.5

### Issue description

Download latest version

### Steps to reproduce

Set the dark theme

**Comment by pmiossec** [comment] 2022-12-06 08:31
For technical reasons, dark themes are no more supported in GitExtensions v4. Duplicate of #10312

**Closed by pmiossec** 2022-12-06 08:31 UTC
Labels: :eyeglasses: status: needs review
