### ISSUE TITLE
Cannot clone repository in WSL

### ISSUE THREAD

**Issue by MatthieuHernandez** [gitextensions/gitextensions#7438] opened 2019-11-21 15:32 UTC
## Current behaviour
I cannot open anything from `\\wsl$\Ubuntu\` with gitextensions but I can open folder or file with other windows applications like Visual Studio Code.

## Expected behaviour
Open `\\wsl$\Ubuntu\` like any other windows folder.

## Steps to reproduce
Use WSL (Windows Subsystem for Linux) with Ubuntu and try to clone repository inside.

## Screenshots
![image](https://user-images.githubusercontent.com/25429726/69350973-d5c19b00-0c7a-11ea-92d2-c642fdcd24ad.png)

## Environment

- GitExtensions version: 3.2.1.6628
- GIT version: 2.23.0.windows.1
- OS version: Microsoft Windows NT 10.0.18362.0
- .NET version: 4.8.4018.0

**Comment by RussKie** [comment] 2019-11-21 23:14
We had few reports about issues configuring WSL - #4307 and #6164.
I don't think anyone on the core team uses WSL, so our experience with it is probably non existent...

**Comment by mast-eu** [comment] 2019-11-28 23:03
I occasionally use WSL and can reproduce the issue.
The problem is that WSL exposes Linux paths like `/home/matthieu` as network resources `\\wsl$\Ubuntu\home\matthieu`. Note the dollar sign in `wsl$`. This is [on purpose](https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-windows-10-version-1903/) an invalid machine name, in order to avoid naming collisions with any potentially existing network resource.

GE is validating paths (e.g. before cloning) and this validation fails - as it should - because the machine name `\\wsl$` is invalid for "normal" network resources:
https://github.com/gitextensions/gitextensions/blob/54a4b38663f8a0386133f12c500c5ee9c8a4b4a0/GitUI/CommandsDialogs/FormClone.cs#L220-L223.

A quick workaround is to map a network drive U: to `\\wsl$\Ubuntu`. This way you can access your home directory in WSL as `U:\home\matthieu`.

A fix for GE would require to find all places where paths are validated and add special handling for `\\wsl$\` everywhere.
The same problem applies also to other use cases. I specifically checked opening an existing repo and accessing a file`s history from shell extensions. Probably there are much more functionalities impacted.

**Comment by MatthieuHernandez** [comment] 2019-12-11 15:39
A simple solution is to use ln command to create a link between Windows and Linux and use Git Extetions on the Windows directory.
```
ln -s  /mnt/c/projects/web-project  /var/www/web-project
```

**Comment by mast-eu** [comment] 2019-12-12 14:15
Yes, this will work too.

**Comment by mast-eu** [comment] 2019-12-12 14:23
Closing issue, because GE is actually doing "the right thing".

The problem is rather caused by a WSL design decision to use a invalid hostname `wsl$`. I don't think GE should implement some special handling for this, especially since easy workarounds exist.

For future reference, I've contacted the WSL team about this: https://github.com/microsoft/WSL/issues/4722.

**Comment by miloshavlicek** [comment] 2019-12-12 23:26
I think that `wsl$` hostname should be handled as a special case. It is very unlikely that Microsoft will change it, it is an intension to not collide with eventually existing hostnames.

**Comment by RussKie** [comment] 2019-12-13 00:46
I think we can consider this an exception.

**Closed** 2020-04-22 22:37 UTC
Labels: :construction: status: in progress, :nerd_face: good first issue, type: feature request, up-for-grabs

**Comment by RussKie** [comment] 2021-03-30 06:20
FWIW, [Windows 10 20175](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20175) they added support for `\\wsl\` instead of `\\wsl$` with the dollar sign version being a legacy fallback.
![image](https://user-images.githubusercontent.com/4403806/112942646-294fcd00-917c-11eb-989e-c1a484e92844.png)
