### ISSUE TITLE
source tree view -> show all branches, shows only current branch history

### ISSUE THREAD

**Issue by kkargareteli** [gitextensions/gitextensions#5906] opened 2018-12-13 13:26 UTC
when I want to filter source tree view to see all branches(which is default view) as it used to be in 2.5x releases, shows only the current branch.

current git version: 3.0.0
OS version: windows 10.0.17134 Build 17134
Git version: 2.20.0
.NET framework version: 4.7.2

**Comment by vbjay** [comment] 2018-12-13 14:53
We have an issue template for a reason.  Use it.  

```
<!--
IMPORTANT

Before creating an issue, be sure to search existing issues, both open AND closed,
to see whether someone else has already reported your issue.

Please also read CONTRIBUTING.md.
-->

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Environment you encounter the issue:**

<!--
Help->About Copy button or Help->Report an issue link will put this info in the clipboard.
-->
- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**

<!-- Love gitextensions? Please consider supporting our collective:
👉  https://opencollective.com/gitextensions/donate -->
```

How it will look 



**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Environment you encounter the issue:**


- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**

**Comment by delarocka** [comment] 2018-12-14 09:45
@kkargareteli I've unchecked _View -> Show first parents_ option and I can see whole tree now.

But i don't what's real purpose of this option.

**Comment by kkargareteli** [comment] 2018-12-14 11:10
> @kkargareteli I've unchecked _View -> Show first parents_ option and I can see whole tree now.
> 
> But i don't know what's real purpose of this option.

yeah, that worked... thanks a lot :)

**Comment by kkargareteli** [comment] 2018-12-14 11:11
> We have an issue template for a reason. Use it.
> 
> ```
> 
> 
> **Do you want to request a *feature* or report a *bug*?**
> 
> **What is the current behavior?**
> 
> **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
> 
> **What is the expected behavior?**
> 
> **Environment you encounter the issue:**
> 
> 
> - GitExtensions version:
> - GIT version: 
> - OS version: 
> - .NET version: 
> 
> **Did this work in previous version of GitExtensions (which)?**
> 
> 
> ```
> How it will look
> 
> **Do you want to request a _feature_ or report a _bug_?**
> 
> **What is the current behavior?**
> 
> **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
> 
> **What is the expected behavior?**
> 
> **Environment you encounter the issue:**
> 
> * GitExtensions version:
> * GIT version:
> * OS version:
> * .NET version:
> 
> **Did this work in previous version of GitExtensions (which)?**
> 
> ![image](https://user-images.githubusercontent.com/3629489/49946483-1470a200-febd-11e8-82b3-f945daf6287e.png)
> 
> Also screenshots can be pasted in the issues. Showing us what you mean would be a bit more helpful.

Sorry, will keep in mind next time :)

**Comment by vbjay** [comment] 2018-12-14 11:43
👍 First parents only shows the first parent in the history.  Merge commits have 2 parents.  So it hides the fluff of what commits were merged ad just the merge commit

![image](https://user-images.githubusercontent.com/3629489/50001566-4c362300-ff6b-11e8-9d64-93fb67246ef3.png)

Notice the merge commits. First parents on.
![image](https://user-images.githubusercontent.com/3629489/50001640-7a1b6780-ff6b-11e8-8748-4460f221ed35.png)

**Comment by Toudahl** [comment] 2018-12-14 11:47
Hiding the branches and their relation to each other should not be the default behaviour.

**Comment by vbjay** [comment] 2018-12-14 11:56
Do you see how the commits are not shown?  First parents HIDES the commits that are being merged in.  What branches would you like to see when the associated commits ARE NOT visible.  Do you get it now?

**Comment by vbjay** [comment] 2018-12-14 11:59
Merge commit Notice how many parents
![image](https://user-images.githubusercontent.com/3629489/50002276-97e9cc00-ff6d-11e8-8b54-3a6267402f36.png)

Show first parents does exactly what you think it does.  A side effect is that non merged branches are also hidden.

**Comment by vbjay** [comment] 2018-12-14 12:01
Turned off
![image](https://user-images.githubusercontent.com/3629489/50002399-ffa01700-ff6d-11e8-8120-c2d334614f30.png)

Turned on
![image](https://user-images.githubusercontent.com/3629489/50002415-1181ba00-ff6e-11e8-9354-49082875e971.png)

**Comment by Toudahl** [comment] 2018-12-14 12:13
> 
> 
> Do you see how the commits are not shown? First parents HIDES the commits that are being merged in. What branches would you like to see when the associated commits ARE NOT visible. Do you get it now?

I dont see how that addresses what i said.

**Comment by vbjay** [comment] 2018-12-14 12:18
We are talking about show first parents.  He had it turned on. Show first parents changes the view.  If you don't want to show first parents ONLY then turn it off.  It's that simple.  Why are you making this hard?

**Comment by vbjay** [comment] 2018-12-14 12:34
It isn't.  I have no idea what you are talking about.  Show first parents is remembered.  What old behavior.  Be specific.  I renamed my settings folder and started the app.  These are the default settings.  
![image](https://user-images.githubusercontent.com/3629489/50003605-324c0e80-ff72-11e8-88b1-925f7ea9ad52.png)

WHAT default behavior are you talking about?  Show first parents is a special view.  You will NEVER see all commits when it is turned on.

**Comment by kkargareteli** [comment] 2018-12-14 12:39
In the previous version of git extensions, to be specific 2.5x, when you install the program and run it, then open repository, you are seeing no all branches.

In the current version of git extensions, when you install the program and run it, 'Show first parents' is checked by default, and I think the issue is whether it should be or not, and I agree with @Toudahl that it shouldn't be.

**Comment by vbjay** [comment] 2018-12-14 12:44
No it isn't.  I will do it again.  I am going to rename my settings folder and the settings file in the repo.  Notice first parent was NOT on.  Notice the default view settings.  
![image](https://user-images.githubusercontent.com/3629489/50004076-f3b75380-ff73-11e8-9f34-77ae76f9e2bf.png)  

![image](https://user-images.githubusercontent.com/3629489/50004102-06ca2380-ff74-11e8-9dd8-a299129e2c70.png)

First parent is remembered between runs of the program.

**Comment by kkargareteli** [comment] 2018-12-14 12:48
Talk is about the first run.

**Comment by vbjay** [comment] 2018-12-14 12:49
Why do you think I renamed my settings folder?  It makes it so GE can't find the settings file.  That means 1st run.

**Comment by vbjay** [comment] 2018-12-14 12:57
If you had 1st parents on in previous version, then it will read those settings.  
![image](https://user-images.githubusercontent.com/3629489/50004529-67a62b80-ff75-11e8-8ea6-7b9b44cb25a2.png)

Renamed this folder to make it so it can't find the settings file it reads on startup.  As you can see, it is asking for which language

![image](https://user-images.githubusercontent.com/3629489/50004574-915f5280-ff75-11e8-867b-fdb834c14a39.png)

Then I opened GE repo.  
![image](https://user-images.githubusercontent.com/3629489/50004620-bb187980-ff75-11e8-960c-42f77a6c76f1.png)

![image](https://user-images.githubusercontent.com/3629489/50004655-d84d4800-ff75-11e8-83c1-26621baa51e9.png)

**Comment by Toudahl** [comment] 2018-12-14 13:04
Then either there was a bug where the setting did not work in pre 3.0 versions, or there is a bug when you upgrade.

I have always been able to see all my branches, aka default behaviour, but after updating i was only able to see one branch at the time, because "show first parent" was turned on.
Just like @kkargareteli experienced

**Comment by kkargareteli** [comment] 2018-12-14 13:05
I didn't know that feature, I used to look at all branches while using.
After upgrading to 3.0, when I opened the repo, show first parent was turned on and got completely different view, which was quite weird :)

**Comment by vbjay** [comment] 2018-12-14 13:06
Ok.  I will try 2.51.05 and run it.  Then run 3.0.  Both first parents
turned off.

**Comment by vbjay** [comment] 2018-12-14 13:17
2.51.05 and default settings for view.
![image](https://user-images.githubusercontent.com/3629489/50005270-c7053b00-ff77-11e8-87de-3698dc173fb6.png)
![image](https://user-images.githubusercontent.com/3629489/50005318-fb78f700-ff77-11e8-888e-1078156d69a3.png)

Closed 2.51.05 and opened 3.0
![image](https://user-images.githubusercontent.com/3629489/50005401-3c710b80-ff78-11e8-97c8-355af86d8f22.png)
![image](https://user-images.githubusercontent.com/3629489/50005417-45fa7380-ff78-11e8-9bf7-5a9891abab4c.png)

As you can see first parents turned off.  Repeating with 2.51.05 first parents turned on.  

![image](https://user-images.githubusercontent.com/3629489/50005498-9376e080-ff78-11e8-8882-30097a921a28.png)
![image](https://user-images.githubusercontent.com/3629489/50005517-a7224700-ff78-11e8-8964-19b22334886d.png)


Like I said.  It remembered what was in the 2.51.05 settings.

**Comment by amaiorano** [comment] 2018-12-14 13:31
2.51 had a bug where Show First Parents only really worked properly if Show Current Branch was also selected. This was fixed a month ago (after I reported it in Gitter): https://github.com/gitextensions/gitextensions/commit/2fcf603670dddbd6e3ed572f6838e7cf0c15210c

It's possible that 2.51 users would have Show First Parents checked, but with Show All Branches, which would basically do nothing, then upon upgrading to 3, be confused as to why it's suddenly rendering only the first parents.

**Comment by Toudahl** [comment] 2018-12-14 14:48
> 
> 
> 2.51 had a bug where Show First Parents only really worked properly if Show Current Branch was also selected. This was fixed a month ago (after I reported it in Gitter): [2fcf603](https://github.com/gitextensions/gitextensions/commit/2fcf603670dddbd6e3ed572f6838e7cf0c15210c)
> 
> It's possible that 2.51 users would have Show First Parents checked, but with Show All Branches, which would basically do nothing, then upon upgrading to 3, be confused as to why it's suddenly rendering only the first parents.

I dont know how this could have happened, but it definitely answers whats going on here.

**Closed** 2018-12-14 23:50 UTC
Labels: status: incorrectly filled template

**Comment by asmwarrior** [comment] 2022-06-30 08:01
> 

This method solved the issue today. Sometimes, people just randomly select this option in the menu, and suddenly they found only one branch is shown.
