### ISSUE TITLE
[NBug] ConEmuCD was not loaded.

### ISSUE THREAD

**Issue by Maurice-Miklis** [gitextensions/gitextensions#7380] opened 2019-11-04 14:45 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

I Just tried to clone a New Project, Nothing fancy 

## Error Details
```
ConEmu.WinForms.GuiMacroExecutor+GuiMacroException: ConEmuCD was not loaded.
   bei ConEmu.WinForms.GuiMacroExecutor.ExecuteInProcessAsync(Int32 nConEmuPid, String asMacro)
   bei ConEmu.WinForms.ConEmuSession.ExecuteGuiMacroTextAsync(String macrotext)
   bei ConEmu.WinForms.GuiMacroBuilder.ExecuteAsync()
   bei ConEmu.WinForms.ConEmuSession.WriteOutputTextAsync(String text)
   bei GitUI.FormStatus.Done(Boolean isSuccess)
   bei GitUI.FormProcess.<>c__DisplayClass43_0.<OnExit>b__0()
   bei GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Just tried to clone a Project

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.3928.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-11-05 23:24
Duplicate of #6675

Disable ConEmu in Settings->Advanced->"Use Console Emulator" to get rid of the problem, or just dismiss the popup

No longer a popup in master

**Closed by gerhardol** 2019-11-05 23:24 UTC
