### ISSUE TITLE
Format patch command fatal error

### ISSUE THREAD

**Issue by NOYB** [gitextensions/gitextensions#6355] opened 2019-03-09 04:28 UTC
## Current behaviour
fatal: C:/Users/<user_id>/Desktop/Patch: 'C:/Users/<user_id>/Desktop/Patch' is outside repository
Affects all repositories and branches.

## Expected behaviour
Successful formatting of patches.

## Steps to reproduce
1. Commands -> Format patch...
2. Save patches in directory C:\Users\<user_id>\Desktop\Patch
3. Select 3 or more commits (it works if 2 or less are selected)
4. Click the Create patch(es) button

## Did this work in previous version of GitExtensions
Yes.  Works in:
Git Extensions 2.51.04
Git Extensions 2.51.05

Does NOT Work in:
Git Extensions 3.00.00.4433
Git Extensions 3.0.2.5232

## Environment
- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment] 2019-03-09 04:30
You must create patches in the repo path.

**Comment by NOYB** [comment] 2019-03-09 05:01
Why?
That seems to be an unnecessary requirement and is apparently not completely accurate as it works when selecting only 1 or 2 commits.

> You must create patches in the repo path.

**Comment by vbjay** [comment] 2019-03-09 11:22
Ask git.

**Comment by gerhardol** [comment] 2019-03-09 13:32
Duplicate of #5923

**Closed by gerhardol** 2019-03-09 13:32 UTC

**Comment by illfated** [comment] 2019-03-09 15:27
The issue looks better described in #5923 as well.

**Comment by vbjay** [comment] 2019-03-09 18:20
The point is that error comes from git.

**Comment by NOYB** [comment] 2019-03-09 19:29
The error may come from git.  But the latest versions of Git Extensions are the cause.

Works with latest version of git: Git 2.21.0.windows.1
Only fails with the new 3.x versions of Git Extensions

**Comment by vbjay** [comment] 2019-03-09 19:39
Wrong.  When outputting a selected list of patches git does not allow output path to be outside of repo path.  Got it?   

When selecting a range like AAA..BBB it allows it to work.  
![image](https://user-images.githubusercontent.com/3629489/54076338-a992f500-4278-11e9-8873-d585ced05f9e.png)
Blue success, red fail

![image](https://user-images.githubusercontent.com/3629489/54076365-f5459e80-4278-11e9-97e4-b4aebfd3adc5.png)


![image](https://user-images.githubusercontent.com/3629489/54076375-1c03d500-4279-11e9-8d8e-e5e3f661575d.png)


Select the most recent commit then the earliest commit and then generate your patch.  It isn't hard.

**Comment by vbjay** [comment] 2019-03-09 19:42
I think I see the problem.  Space between -- and start-number.

**Comment by vbjay** [comment] 2019-03-09 19:55
@NOYB you are welcome to send in a pull request fixing the argument.  

https://github.com/gitextensions/gitextensions/blob/d0ba1a57823f12cc1caec12026586bb9353d2771/GitCommands/Git/GitModule.cs#L1414

**Comment by NOYB** [comment] 2019-03-09 20:54
Thanks vbjay but I don't have a GitExtensions dev environment setup.  No way to test.
Would appreciate if you or someone else would make the commit.
Thanks.

**Comment by vbjay** [comment] 2019-03-09 20:57
You can just edit in GitHub and create the pull request. This is a quick
one line change.

**Comment by NOYB** [comment] 2019-03-09 21:38
You okay with that without me testing it?

**Comment by vbjay** [comment] 2019-03-09 21:40
You can test with the ci build result. It is a pretty straightforward
change. It is pretty clear. -- means something in git commands. It should
be --ag and not -- arg.
