### ISSUE TITLE
Windows7: Copy/Paste is broken in commit message box

### ISSUE THREAD

**Issue by seoriy** [gitextensions/gitextensions#3750] opened 2017-06-07 17:24 UTC
Sometimes I can't paste a text:
1. Win+R
2. type something
3. select and Ctrl+C
4. open commit window
5. set focus in "commit message" textbox
6. try Ctrl+V - no text pasted and standard Windows "Default Beep" sound is heard instead

--- GitExtensions2.49.03, Git 2.11.1.windows.1, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by RussKie** [comment] 2017-06-18 12:01
Have a look at #3593 and #3706, they may be somehow related.
Please try to disable the console tab and/or the console emulation and see if that makes a difference

**Comment by seoriy** [comment] 2017-06-18 13:25
Thanks for advice. But unfortunately, it didn't help. I turn off one by one "Show the Console tab" and "Use Console Emulator..." options with restarting on each try, but it copy/paste functionality is still broken.

PS: I add a little bit more details to issue description.

**Comment by RussKie** [comment] 2017-06-18 14:15
bugger... thanks for trying

you're saying the bug is intermittent. is there a reliable way of reproducing it? 
if not, is there anything significant about the commit/text/window mode/other running programs/etc when the problem occurs?

**Comment by jbialobr** [comment] 2017-06-19 06:58
Possibly a duplicate of #2926.

**Comment by jrfnl** [comment] 2017-07-02 02:23
Keeping my fingers crossed that the fix for #2926 has fixed this too :crossed_fingers: . I've been having the same issue for quite a while on Windows 7 (though without the beep sound). Normally trying to paste two, three times and clicking the commit msg dialog in between each try, eventually let the paste go through.

**Comment by seoriy** [comment] 2017-07-03 09:07
Yep. It not reproducible in 2.50 Thanks!

**Closed** 2017-07-03 10:25 UTC
