### ISSUE TITLE
[NBug] Unable to parse object ID "gelöscht".

### ISSUE THREAD

**Issue by ebaur** [gitextensions/gitextensions#9224] opened 2021-05-20 08:37 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.FormatException: Unable to parse object ID "gelöscht".
   bei GitUIPluginInterfaces.ObjectId.Parse(String s)
   bei GitUI.CommandsDialogs.FormMergeSubmodule.btCheckoutBranch_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Clicked the merge button in conflict window at merging added new submodule from remote to local branch without the submodule. 

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2021-05-20 21:17
Duplicate of #7466
Merge is attempted when one of the submodules is deleted
The Git command ls-files fails. Can you check the output of the command, you see it in the Git Command Log?

GetConflictsAsync() will likely have to be handled explicitly in #9056 @mstv 

The Exception could be avoided (but #9056 must handle this too).

**Closed by gerhardol** 2021-05-20 21:17 UTC
