### ISSUE TITLE
scaling issues on highdpi for repositories window

### ISSUE THREAD

**Issue by drakelovesbarbie** [gitextensions/gitextensions#4285] opened 2017-12-28 17:08 UTC
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Scaling is wrong, UI elements are out of place

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open the repositories form using any high dpi screen 
screenshot: 
![image](https://user-images.githubusercontent.com/4403806/34426964-618a8fb4-ec90-11e7-9617-a37154849802.png)

**What is the expected behavior?**
UI elements at their correct place

**Environment you encounter the issue:**
Windows 10 / Surface Book
Windows 10 / 4K tv screen

- GitExtensions version: 2.5
- GIT version:  2.5
- OS version:  Windows 10

**Did this work in previous version of GitExtensions (which)?**
when there was no highdpi awareness

**Comment by vbjay** [comment] 2017-12-28 17:47
https://github.com/gitextensions/gitextensions/issues?utf8=%E2%9C%93&q=is%3Aissue+dpi

**Comment by RussKie** [comment] 2017-12-29 01:09
Duplicate of #4099

Please refer to #4099 for a workaround

**Closed by RussKie** 2017-12-29 01:09 UTC
