### ISSUE TITLE
git difftool --dir-diff

### ISSUE THREAD

**Issue by jamesford42** [gitextensions/gitextensions#1647] opened 2013-02-21 21:55 UTC
I would like the explorer context menu options "view changes" and "open with diff tool", when a folder is selected, to launch the selected dif tool if that tool supports folder comparision. I want to use Beyond Compare's folder comparison in conjunction with git's "--dir-diff" option but there is no way to integrate that currently in GitExtensions.

**Comment by Sendaran** [comment] 2016-10-06 12:31
This is what I miss the most in the GitExtensions GUI, directory diff support, either from the diff panel or directly from the main view via right click. It's the single most used command that forces me to open Git bash. My eternal thanks go to whoever can add this. I would attempt to add it myself, but I haven't touched anything C# related in a decade.

**Comment by ghanique** [comment] 2016-10-06 13:01
It has commit-diff support, where it shows all the differences of all the
files that changed between two commits. So if you HAD a directory structure
and you HAVE a different one now, Git Extensions can show you what is
different between the two revisions.

For plain directory diff support I can highly recommend WinMerge. It's
cheap (that is: free), fast, simple and configurable.

**Comment by vbjay** [comment] 2016-10-06 15:10
Try p4 merge instead. A lot better than winmerge and it supports 3 way
merging.

**Comment by Sendaran** [comment] 2016-10-07 07:44
Any diff tool worth its salt has directory diff support these days, I use WinMerge and Meld, but that's past the point. The part missing in GitExtensions is the option for laundhing git difftool --dir-diff from the GUI, as indicated by topic. Sure, all the changes between two commits are available in the diff panel, but you can only pass them to an external diff tool one by one, which is cumbersome for a lengthier code review or when you are investigating a longer batch of history to look for the root cause of a weird regression bug. Personally, I'd be happy with just a "View all changes in diff tool" context menu option invoking "git difftool -d commit1 commit2" in either main view or diff panel. Others might want something more fine tuned.

**Comment by aabdelfattah** [comment] 2017-08-24 14:49
Any updates on this ?

**Comment by RussKie** [comment] 2017-08-25 05:10
no, pull requests are welcome.

**Comment by vbjay** [comment] 2017-08-25 12:19
Lol. That’s Not My Job

This is a story about four people named Everybody, Somebody, Anybody and
Nobody.  There was an important job to be done and Everybody was sure that
Somebody would do it.  Anybody could have done it, but Nobody did it.
Somebody got angry about that, because it was Everybody’s job.  Everybody
thought Anybody could do it, but Nobody realized that Everybody wouldn’t do
it.  It ended up that Everybody blamed Somebody when Nobody did what
Anybody could have.

**Comment by jhenkens** [comment] 2018-06-04 22:09
I guess I'm Anybody? I've started a revision for the 3.x release, here. Definitely needs further testing, and design thoughts in general, as well as localization.

https://github.com/jhenkens/gitextensions/tree/difftool-support-and-additional-compare-options

**Comment by RussKie** [comment] 2018-06-04 22:54
Please raise a PR so everyone interested can review it.

**Comment by mstv** [comment] 2019-04-17 21:52
I guess this issue can be closed, the PR has been merged.

**Comment by gerhardol** [comment] 2019-04-17 21:55
Should have been included in the 3.0 milestone

**Closed** 2019-04-17 21:54 UTC
Labels: type: feature request, up for grabs
