### ISSUE TITLE
Crash when pull from networked git repo folder

### ISSUE THREAD

**Issue by angelivan-spartan** [gitextensions/gitextensions#10419] opened 2022-11-17 20:08 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.11
- DPI 96dpi (no scaling)
- Same Behavior on 2 different machines running windows 11 one on 22H2 and the other on 22H1

### Issue description

```
GitExtUtils.ExternalOperationException:  ---> System.Exception: 

   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.GitModule.GetRemoteNames()
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.<>c__DisplayClass15_0.<PopulateRemotes>b__0()
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.PopulateRemotes(List`1 allRemotes, Boolean enabled)
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.LoadRemotes(Boolean loadDisabled)
   at GitUI.CommandsDialogs.FormPull.BindRemotesDropDown(String selectedRemoteName)
   at GitUI.CommandsDialogs.FormPull..ctor(GitUICommands commands, String defaultRemoteBranch, String defaultRemote, PullAction pullAction)
   at GitUI.GitUICommands.<>c__DisplayClass95_0.<StartPullDialogInternal>g__Action|0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent)
   at GitUI.GitUICommands.StartPullDialogInternal(IWin32Window owner, Boolean pullOnShow, Boolean& pullCompleted, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.GitUICommands.StartPullDialog(IWin32Window owner, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.GitUICommands.Pull(IReadOnlyDictionary`2 arguments)
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments)
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

Pull a repo located on a networked shared location
ie:
//YourFileServer/YourPersonalRepo/    GitExtensions->Pull

On Git Extensions v.3.xx worked, the bug is on v.4

cheers.

### Steps to reproduce

Pull a repo located on a networked shared location
ie:
//YourFileServer/YourPersonalRepo/    GitExtensions->Pull

### Did this work in previous version of GitExtensions?

Yes, On Git Extensions v.3.xx worked, the bug is on v.4

**Comment by gerhardol** [comment] 2022-11-17 21:19
Is this same as #10349 ?
You should get a popup with a failed Git command. Check Git Command Log.
Also see https://github.com/gitextensions/gitextensions/issues/9954#issuecomment-1098375030

**Comment by RussKie** [comment] 2022-11-18 07:53
Can you please share a screenshot of the error message?

**Comment by angelivan-spartan** [comment] 2022-11-21 04:51
![screenshot](https://user-images.githubusercontent.com/90977259/202967563-4502294f-8ba9-4cb6-b8fe-3a4284b89494.png)

You are right, its a duplicate of [#10349](https://github.com/gitextensions/gitextensions/issues/10349) **BUT** Git Extensions didn't show the error message, it goes directly to the crash/error report as seen on the screenshot.

**Comment by RussKie** [comment] 2022-11-21 06:23
That's odd. Are you able to share an animation of that?

**Comment by RussKie** [comment] 2022-11-21 06:24
Duplicate of #10349

**Closed by RussKie** 2022-11-21 06:24 UTC

**Comment by mstv** [comment] 2022-11-21 17:58
It looks like `BugReportInvoker.Report()` has been called with `isTerminating: true` - most likely because `UnhandledExceptionEventArgs.IsTerminating` was `true`.
Is this flag set by something behind `JoinableTaskFactory.Run()`?

**Comment by angelivan-spartan** [comment] 2022-11-22 04:11
> Can you please share a screenshot of the error message?

There you go...
![no_error_message](https://user-images.githubusercontent.com/90977259/203219436-4da3d01c-3818-432e-9c87-56388bd89c79.gif)

**Comment by RussKie** [comment] 2022-11-22 04:42
Thank you.


IsTerminating=true is when yhe exception is thrown from a background
thread, which leads to terminating the app.
