### ISSUE TITLE
FileDiff: Line numbers clipped

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6568] opened 2019-05-15 12:43 UTC
## Current behaviour

Line numbers from 10000 are clipped:

![grafik](https://user-images.githubusercontent.com/36601201/57775842-41500c00-771e-11e9-8c09-235a3bb46dd4.png)

Line numbers from 1000 overlap with the diff markers:
![grafik](https://user-images.githubusercontent.com/36601201/57776288-62652c80-771f-11e9-8362-4d5a8cf2f1cc.png)

## Expected behaviour

The width of the section with the line numbers is calculated correctly.

## Did this work in previous version of GitExtensions

I don't know.

## Environment

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by ignacioerrico** [comment] 2019-05-16 14:43
Duplicate of #6031.

**Closed** 2019-05-16 16:34 UTC
