### ISSUE TITLE
Stay at viewed fragment of code after increasing/decreasing amount of code visible

### ISSUE THREAD

**Issue by kr10n1** [gitextensions/gitextensions#2276] opened 2014-03-07 10:39 UTC
Reviewing code is made very unconmfortable because of this 'feature'. It would be much better if editor stayed in the same fragment of code.

**Comment by RussKie** [comment] 2018-03-17 07:21
Closing because the wording of the issue is unclear and time passed

**Closed by RussKie** 2018-03-17 07:21 UTC
