### ISSUE TITLE
[NBug] Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by j2ghz** [gitextensions/gitextensions#9569] opened 2021-09-14 08:47 UTC
## Current behaviour
Sometimes reports a crash, but keeps working fine.

## Expected behaviour
No crashes.

## Steps to reproduce

1. Have GitExtensions open in the background
2. From time to time it will report 'System.OutOfMemoryException', but keep working without any noticeable problem.

## Error Details
```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.Add(T item)
   at System.AggregateException.Flatten()
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()

```

## Additional information
This time I wasn't editing any files, nor doing anything in Visual Studio, both were in the background. It happens regularly, and I can't see any pattern.

## Environment
- Git Extensions 3.5.3.12551
- Build 00604a59a673142a3d34a22aa657466a922977f3
- Git 2.32.0.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by j2ghz** [comment] 2021-09-14 08:53
All of these "duplicates" seem to be about having a huge file in the repo, and/or using git-lfs. Also the stack trace is different. Mine looks to me to be a separate issue.

**Comment by j2ghz** [comment] 2021-09-14 14:39
It happened again, again while in background. This time I took notice of the error report dialog, I'm not sure if that's intended, but clicking Send and Quit, or just Quit does not exit the application, only the dialog.

**Comment by j2ghz** [comment] 2021-09-15 07:55
> but keeps working fine.

That's not accurate, I've been having issues with my PC, that I thought were completely unrelated. Turns out they are related, all **caused by port exhaustion by git extensions**. `netstat -anob` shows a lot of entries for GitExtensions.exe:
```
 [GitExtensions.exe]
  TCP    localhost:61216     buildserver:443      CLOSE_WAIT      23564
 [GitExtensions.exe]
  TCP    localhost:61217     buildserver:443      CLOSE_WAIT      23564
 [GitExtensions.exe]
  TCP    localhost:61218     buildserver:443      CLOSE_WAIT      23564
 [GitExtensions.exe]
  TCP    localhost:61219     buildserver:443      CLOSE_WAIT      23564
 [GitExtensions.exe]
  TCP    localhost:61220     buildserver:443      CLOSE_WAIT      23564
 [GitExtensions.exe]
  TCP    localhost:61221     buildserver:443      CLOSE_WAIT      23564
 [GitExtensions.exe]
  TCP    localhost:61222     buildserver:443      CLOSE_WAIT      23564
 [GitExtensions.exe]
  TCP    localhost:61223     buildserver:443      CLOSE_WAIT      23564
 [GitExtensions.exe]
  TCP    localhost:61224     buildserver:443      CLOSE_WAIT      23564
 [GitExtensions.exe]
  TCP    localhost:61225     buildserver:443      CLOSE_WAIT      23564
 [GitExtensions.exe]
  TCP    localhost:61226     buildserver:443      CLOSE_WAIT      23564
 [GitExtensions.exe]
  TCP    localhost:61227     buildserver:443      CLOSE_WAIT      23564
 [GitExtensions.exe]
  TCP    localhost:61228     buildserver:443      CLOSE_WAIT      23564
 [GitExtensions.exe]
  TCP    localhost:61229     buildserver:443      CLOSE_WAIT      23564
 [GitExtensions.exe]
  TCP    localhost:61230     buildserver:443      CLOSE_WAIT      23564
 [GitExtensions.exe]
  TCP    localhost:61347     buildserver:443      ESTABLISHED     23564
 [GitExtensions.exe]
  TCP    localhost:61415     buildserver:443      ESTABLISHED     23564
 [GitExtensions.exe]
  TCP    localhost:61725     buildserver:443      ESTABLISHED     23564

... and many more
```

I'll try turning off TeamCity build server integration, and see if it helps.

**Comment by pmiossec** [comment] 2021-09-15 08:02
So maybe same than #3646

**Comment by mkiszka** [comment] 2021-10-21 14:07
I have the same problem. I have so many connections marked as "CLOSE_WAIT" that even a web browser can't connect to another web page.

Problems:

- OutOfMemmoryExceptions
- a lot of connections to TeamCity build server

Enviroment parameters:
- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4420.0
- DPI 96dpi (no scaling)

- Build server integration - enabled


Bests

**Comment by RussKie** [comment] 2021-11-07 13:15
Duplicate of #3646

I don't believe anyone from the Core team is using TC, and we look up to the community members who's using TC to help with a fix.

**Closed by RussKie** 2021-11-07 13:15 UTC
Labels: potential-duplicate
