### ISSUE TITLE
Setup can't keep "Other ssh client" setting

### ISSUE THREAD

**Issue by Boddlnagg** [gitextensions/gitextensions#6286] opened 2019-02-21 07:13 UTC
In the setup dialog I'm asked whether I want to choose OpenSSH or PuTTY. But I want to use the new built-in OpenSSH for Windows (`C:\Windows\System32\OpenSSH\ssh.exe`), which I have set up as "Other ssh client".

Whenever I update to a newer version, the setup asks me again, and whichever of the two options I select, my current setting is not kept.

There should either be an option to just keep the current setting, or (even better) that particular dialog page should just not be shown for upgrade installations, because it worked fine before the upgrade and there's no reason to change that setting during an upgrade.

**Comment by gerhardol** [comment] 2019-02-22 23:16
Related to #5121 , #5823
The setting is always set to PuTTY in the installer, also if Git OpenSSH is set

#5121 requires some migration, maybe it is sufficient as a first step to remove the option from the installer and set Git OpenSSH as the default.

**Comment by vbjay** [comment] 2019-02-22 23:44
No. The default should not be openssh.

**Comment by RussKie** [comment] 2019-02-22 23:57
> No. The default should not be openssh.

Could you please provide reasons. 
I suspect there may be some historic knowledge involved.

**Comment by vbjay** [comment] 2019-02-23 01:40
Putty provides a quick and easy management.  It makes it easier to set up ssh. The tooling in GE provides for git ssh key settings per repo. With the putty agent it makes it so you can unlock the ssh key and use and unlock. Openssh tends to be a pain to use when the key is secured. Let the user start with putty and let them chose to use openssh.

**Comment by gerhardol** [comment] 2019-02-24 00:28
@vbjay 
I know your view, that is why I have not submitted a PR, will be too tired from the discussion that would occur.
Here a user poll like you proposed would be good, to find how many that prefer PuTTY and how many that considered the current handling a bug.

**Comment by Galgemaennle** [comment] 2019-04-05 13:23
Not even the setup can't keep the configuration, even the tool itself will reset to putty after restarting the program. This is quite annoying  as openSSH fixes following issue: https://stackoverflow.com/a/52586001/426386

**Comment by vbjay** [comment] 2019-04-05 16:06
Why I use chocolatey to keep putty installed and updated. Putty just needs
to stay current.

**Comment by RussKie** [comment] 2019-04-06 05:21
> Why I use chocolatey to keep putty installed and updated. Putty just needs to stay current.

This requires extra maintenance a lot of users don't need.
We need telemetry data to make better decisions.

**Comment by vbjay** [comment] 2019-04-06 06:37
My point is I'm not stuck with the version ge provides. My ge points to
installed version. My whole thing is that installing chocolatey with ge
(powershell script) and then run chocolatey upgrade putty.install -y to
upgrade or install. Do you understand it. The users should not be stuck
with our update cadence.

**Comment by matyasbach** [comment] 2019-12-19 10:23
With automatic GE update (introduced in 3.2.1 so first happened on update to 3.3) it's not even asking and sets Putty. You then have to go to Settings/SSH to set back your preferred option.

**Comment by gerhardol** [comment] 2019-12-19 20:59
> With automatic GE update (introduced in 3.2.1 so first happened on update to 3.3) it's not even asking and sets Putty. 

The silent installer have the same problem as just clicking the steps in the updater, SSH settings is not retained in the dialog. I have helped three persons this week and got two nudges that this should be changed. I agree this is a  pain.

However, the installer is difficult to maintain. I tried to fix this in #6363  by removing the SSH page from the installer. It may be that we replace the wix installer for these reasons. Someone with knowledge about the wix installer may help.

**Comment by RussKie** [comment] 2019-12-20 13:02
@Johno-ACSLive I suspect this is caused by the silent execution of the installer...

**Comment by Johno-ACSLive** [comment] 2019-12-20 23:22
@RussKie it's caused because of the installer bug where it does not remember previous settings. Because the upgrade is called with basic progress users can't re-select what they have. If you have a default install then this isn't a problem.

If you don't have default install then the workaround would be to download the upgrade using the original mechanism and run the upgrade interactively until I get the project moved to Advanced Installer where I'm hoping all installer issues will be resolved.

Apologies for not actively working on it, I did start but was then caught up on other work. Now that Dark theme has merged into master and I'll have time shortly to resume work, I'll get to it! :)

**Comment by RussKie** [comment] 2019-12-20 23:26
I'll see if I can fix it over the weekend

**Comment by RussKie** [comment] 2019-12-23 06:37
Can I get you to verify a fix? This installer should retain the configured SSH
https://ci.appveyor.com/api/buildjobs/vgsecayjmjmhpn8h/artifacts/combined.3.3.0.7791-unsigned.zip

**Closed** 2020-01-09 10:49 UTC
Labels: area: installer, area: user experience
