### ISSUE TITLE
[NBug] Method not found: 'Boolean GitCommands.GitSshHelpers.Plink()'.

### ISSUE THREAD

**Issue by alexagr** [gitextensions/gitextensions#10566] opened 2022-12-21 16:33 UTC
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.37.0.windows.1.1.g00795d2b7c (recommended: 2.38.1 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

```
System.MissingMethodException: Method not found: 'Boolean GitCommands.GitSshHelpers.Plink()'.
   at GitExtensions.GerritPlugin.GerritUtil.StartAgent(IWin32Window owner, IGitModule module, String remote)
   at GitExtensions.GerritPlugin.FormGerritPublish.PublishChange(IWin32Window owner)
   at GitExtensions.GerritPlugin.FormGerritPublish.PublishClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

push to Gerrit stopped working after latest Git Extensions update

### Steps to reproduce

Click on "Publish Gerrit Change" button from Gerrit Code Review plugin - an error is produced.

### Did this work in previous version of GitExtensions?

yes - in 4.0.0 all worked just fine

**Comment by pmiossec** [comment] 2022-12-21 17:40
Duplicate of https://github.com/gitextensions/GitExtensions.GerritPlugin/issues/55

**Closed by pmiossec** 2022-12-21 17:40 UTC
Labels: :eyeglasses: status: needs review
