### ISSUE TITLE
[NBug] Error reading the [filepath] (while deleting current directory)

### ISSUE THREAD

**Issue by KoscheyScrag** [gitextensions/gitextensions#6855] opened 2019-06-25 11:28 UTC
## Current behaviour

![image](https://user-images.githubusercontent.com/7176953/60094591-2d53ed00-9755-11e9-87a1-392b4645f27e.png)

## Expected behaviour

The application does not crash

## Steps to reproduce

1. Open repository
2. Delete folder with opened repository

## Error Details
```
System.IO.FileNotFoundException: Error reading the "filepath" directory.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.Update()
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-06-25 14:46
Duplicate of #6812 
Corrected in #6834 (to be included in 3.2)

**Closed** 2019-09-29 21:21 UTC
Labels: potential-duplicate
