### ISSUE TITLE
[NBug] fatal: bad revision 'NXP/10.4.12'

### ISSUE THREAD

**Issue by dima1308** [gitextensions/gitextensions#10798] opened 2023-03-12 11:32 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET 6.0.13
- DPI 120dpi (125% scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" --max-count=100000 --glob=refs/stas[h] NXP/10.4.12 --
Working directory: C:\git\portfolio\

```
GitExtUtils.ExternalOperationException: fatal: bad revision 'NXP/10.4.12'
 ---> System.Exception: fatal: bad revision 'NXP/10.4.12'
   --- End of inner exception stack trace ---
   at void GitUI.RevisionGridControl.PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs, bool forceRefresh)+() => { }
   at async Task GitUI.GitUIExtensions.InvokeAsync(Control control, Action action, CancellationToken token)
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

the branch NXP/10.4.12 exists. However, it is not possible to checkout this branch on Windows (because of files like con.c/aux.c in the branch)

### Steps to reproduce

I tried to access the `NXP/10.4.12` branch and GitExtension crashed.
the branch NXP/10.4.12 exists. However, it is not possible to checkout this branch on Windows (because of files like con.c/aux.c in the branch)
I expect that the GitExtension will not crash and the right error message will be displayed

**Comment by gerhardol** [comment] 2023-03-12 12:44
Duplicate of #10740

The Git fatal error is due to the branch is not a valid revision. Can you see the branch in the grid without filtering?

**Closed by gerhardol** 2023-03-12 12:44 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate

**Comment by dima1308** [comment] 2023-03-12 13:11
> Can you see the branch in the grid without filtering?

Yes, I see

**Comment by RussKie** [comment] 2023-03-12 20:07
> and GitExtension crashed.

Did it?

**Comment by dima1308** [comment] 2023-03-12 20:30
> Did it?

No, with no filtering GitExtension did not crash

**Comment by dima1308** [comment] 2023-03-12 20:30
> Did it?

No, with no filtering GitExtension did not crash

**Comment by mstv** [comment] 2023-03-12 20:44
> > Did it?
> 
> No, with no filtering GitExtension did not crash

I think the question meant: "Did Git Extensions _really crash_".

I think you have got a popup like:

![image](https://user-images.githubusercontent.com/36601201/224572222-b969e249-5441-4171-b31d-3290322e5b95.png)

This is not a crash. A crash dialog has a "Report bug" button.
This is a popup that a git command triggered by your input, has failed.

"fatal: bad revision '...'" is the error output from git.
