### ISSUE TITLE
Missing graph lines for the last visible row.

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#5204] opened 2018-07-24 16:11 UTC
**Do you want to request a *feature* or report a *bug*?**
:bug:
**What is the current behavior?**
![gitext](https://user-images.githubusercontent.com/1003909/43151712-dadf4a2e-8f6c-11e8-962d-07997e1d6f9e.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open a repo.

**Environment you encounter the issue:**

- GitExtensions version: 0776ec902ca743811a7e75d92a02e52fb31090a0

**Comment by drewnoakes** [comment] 2018-07-24 16:17
Duplicate of #5168.

**Closed** 2018-07-24 16:22 UTC
Labels: type: regression
