### ISSUE TITLE
[NBug] 

### ISSUE THREAD

**Issue by ksmith1787** [gitextensions/gitextensions#10584] opened 2022-12-27 16:37 UTC
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: config --get gitflow.branch.master
Working directory: C:\Users\Keith\Documents\IIQ83\

```
GitExtUtils.ExternalOperationException
 ---> System.Exception
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitExtensions.Plugins.GitFlow.GitFlowForm.get_IsGitFlowInitialised()
   at GitExtensions.Plugins.GitFlow.GitFlowForm.Init()
   at GitExtensions.Plugins.GitFlow.GitFlowForm..ctor(GitUIEventArgs gitUiCommands)
   at GitExtensions.Plugins.GitFlow.GitFlowPlugin.Execute(GitUIEventArgs args)
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass70_0.<RegisterPlugins>b__2(Object <p0>, EventArgs <p1>)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Running git flow

### Steps to reproduce

I just started git flow plugin

### Did this work in previous version of GitExtensions?

Yes but on other computers

**Comment by gerhardol** [comment] 2022-12-27 17:28
Duplicate of #10550 
Fixed in https://github.com/gitextensions/gitextensions/pull/10341, to be included in 4.0.2
Just init Git flow from the command line for now

**Closed by gerhardol** 2022-12-27 17:28 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
