### ISSUE TITLE
Version 2.51.02 Do not remember the size of the window.

### ISSUE THREAD

**Issue by KSemenenko** [gitextensions/gitextensions#5072] opened 2018-06-13 07:41 UTC
Version 2.51.02 Do not remember the size of the window.
This means that when you restart or open a window with commit, I need to change the size of the window every time.
The previous version remembered the size of the window.

**Comment by RussKie** [comment] 2018-06-13 07:49
Duplicate of #5021

**Closed by RussKie** 2018-06-13 07:49 UTC
