### ISSUE TITLE
Diff of patches

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7909] opened 2020-03-27 23:04 UTC
## Feature description

Another extension idea came up finally while reviewing the PR #7899.
We rebase and/or squash often. It is not easy to check whether the resulting commit is the same patch.

So for a two-commit selection we could have another diff group comparing the patches of these commits. Though this diff group is not very meaningful for unrelated commits. Perhaps it should appear only if the commit subjects are identical.

More general for a suiting four-commit selection, the pair of patches could be diffed.
A special case of this is a three-commit selection of `first`, `selected` and `squashed`.

This does not necessarily need to be displayed a as an additional diff group.
A context menu item / hotkey could suffice. It could open a diff of the two patch files in a FileView or the difftool or even a directory diff as in #7687,

## Environment

#7899

**Comment by gerhardol** [comment] 2020-03-27 23:35
I have considered the same but in a separate form.
But an explicit 4 commit selection could be used, adding other groups. (This would eliminate the 4 commit multi selection, but this what I use the 4 commit selection for anyway). (The 'squashed' scenario is handled either with #7899 if BASE is the same or 4 way selection, I want that 3-way multi select)

**Comment by gerhardol** [comment] 2020-09-12 21:00
Duplicate of #8448 
#8448 is actually a specific implementation of the problem, but it is Git standard functionality, which is preferred to something homegrown

**Closed by gerhardol** 2020-09-12 21:00 UTC
Labels: type: discussion, type: feature request
