### ISSUE TITLE
[NBug] Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by lholbert** [gitextensions/gitextensions#6595] opened 2019-05-17 22:13 UTC
## Error Details
```
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at GitCommands.FullPathResolver.Resolve(String path)
   at GitUI.Editor.FileViewer.<ShowOrDeferAsync>g__GetFileLength|88_0(<>c__DisplayClass88_0& )
   at GitUI.Editor.FileViewer.ViewFileAsync(String fileName, Action openWithDifftool)
   at GitUI.CommandsDialogs.FormCommit.<SetSelectedDiffAsync>d__129.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.FormCommit.<>c__DisplayClass128_0.<<ShowChanges>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2019-05-17 22:53
Steps to reproduce?

**Comment by illfated** [comment] 2019-05-18 03:12
Would definitely be interesting to try to reproduce, seeing how similar my environment is:
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by lholbert** [comment] 2019-05-18 17:54
I hear ya, I was shocked when this popped up, I've used this program for years and had nary an issue.

Had just recently updated to the latest 3.1 (from 3.0), just that day.

That said, here we go, from the best of my recollection (I know, I know, terrible user ).  If time permits, I will reinstall 3.1 at some point, and see if this can be reproduced.

Just had large xaml refactoring session (mostly renaming), fired up the program, selected my project, the commit button, applied a filter for .xaml (to include .xaml.cs), staged all the files (around 35 if I recall), entered my commit message, hit Commit & Push, and was presented with that error.  Tried it a couple of times, took the filters off, unstaged, etc, etc .. but it was stuck on this error (even exited and restarted the program).

I just wanted to get my work checked in, so I uninstalled 3.1, went back to 3.0, and it worked without a problem.

I am using bitbucket as my remote.

**Comment by vbjay** [comment] 2019-05-18 17:59
Show git remote -v output.

**Comment by RussKie** [comment] 2019-05-18 21:44
Try grabbing the portable 3.1 version and see if you can reproduce the
problem and get more information.

**Comment by gerhardol** [comment] 2019-06-16 11:14
Duplicate of #6755 
Not the same exception but similar stacktrace

**Closed** 2019-10-04 04:50 UTC
Labels: :mailbox_with_no_mail: needs: author feedback, :zzz: status: no recent activity, potential-duplicate
