### ISSUE TITLE
[NBug] Unable to parse object ID "fatal: Invalid path '/c': No suc...

### ISSUE THREAD

**Issue by kaklakariada** [gitextensions/gitextensions#7083] opened 2019-09-01 14:05 UTC
## Current behaviour

Opening a new git repo without any commits fails

## Expected behaviour

Opening the git repo works and allows you to do an initial commit

## Steps to reproduce

Using Win10 and msysgit
1. Create a new project with `gradle init`
1. Use git bash from msysgit: `git init`
1. Open repo with GitExtensions

## Error Details
```
System.FormatException: Unable to parse object ID "fatal: Invalid path '/c': No such file or directory".
   at GitUIPluginInterfaces.ObjectId.Parse(String s)
   at GitCommands.GitModule.GetCurrentCheckout()
   at GitUI.RevisionGridControl.ForceRefreshRevisions()
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Creating a commit using the command line (`git add` and `git commit`) does not help, the same error occurs.

### Workaround:
File `rep/.git/config` contains line `worktree = /c/<path-to-project>`. After changing this to `worktree = c:/<path-to-project>` opening in GitExtensions works as expected.

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-09-01 21:18
Duplicate of #6512
Included in master, 3.2 RC soon

**Closed** 2019-09-02 21:04 UTC
Labels: potential-duplicate
