### ISSUE TITLE
GitExtensions breaks Visual Studio 2013

### ISSUE THREAD

**Issue by hhubschle** [gitextensions/gitextensions#2641] opened 2015-02-04 15:17 UTC
Install version 2.48.03 with VS2013 integration
Start VS2013
Disable the GitExtensions toolbar
Close VS2013 and restart it: 
->"Microsoft Visual Studio 2013 has stopped working"
VS2013 is dead.

You can recover by removing VS2013 integration.

**Comment by KindDragon** [comment] 2015-02-04 15:37
Duplicate of #2587

**Closed** 2016-04-18 22:51 UTC
