### ISSUE TITLE
[NBug] "Object reference not set to an instance of an object." on creating pull request

### ISSUE THREAD

**Issue by SergiiGalai** [gitextensions/gitextensions#6758] opened 2019-06-06 10:35 UTC
## Current behaviour

No pull request window or redirect to browser happened. 
I can see an exception window instead

## Expected behaviour
No exception window, create pull request dialog is opened

## Steps to reproduce

1. I have a branch on github in private repository
2. Pressed GitHub=>Create Pull Request ... menu item for existing branch
3. Exception occurred with an option to send bug

![image](https://user-images.githubusercontent.com/5754796/59027158-f29b1b00-8860-11e9-936b-682764cd69ff.png)

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Git.hub.Repository.GetBranches()
   at GitHub3.GitHubRepo.GetBranches()
   at GitUI.CommandsDialogs.RepoHosting.CreatePullRequestForm.<>c__DisplayClass22_0.<<PopulateBranchesComboAndEnableCreateButton>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-06-15 22:03
Duplicate of #6757

**Closed by gerhardol** 2019-06-15 22:03 UTC
Labels: potential-duplicate
