### ISSUE TITLE
[NBug] Не удалось найти часть пути "C:\Users\igori.WIZ\AppData\Roa...

### ISSUE THREAD

**Issue by pincher1519** [gitextensions/gitextensions#7493] opened 2019-12-10 06:43 UTC
## Steps to reproduce

1. To launch the application for the first time under a new user profile.
2. Select Russian in the proposed dialogue
3. Refuse Telemetry
4. Go to application settings
5. Click OK or Apply

## Error Details
```
System.IO.DirectoryNotFoundException: Не удалось найти часть пути "C:\Users\igori.WIZ\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings".
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   в GitCommands.Settings.FileSettingsCache.SaveImpl()
   в GitCommands.SettingsCache.<>c__DisplayClass3_0.<LockedAction>b__0()
   в GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   в GitCommands.Settings.SettingsContainer`2.Save()
   в GitUI.CommandsDialogs.FormSettings.Save()
   в GitUI.CommandsDialogs.FormSettings.Ok_Click(Object sender, EventArgs e)
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ButtonBase.WndProc(Message& m)
   в System.Windows.Forms.Button.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.24.0.windows.2
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4042.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2019-12-10 07:44
I can't replicate this in 3.3
![startup](https://user-images.githubusercontent.com/4403806/70505753-e16af800-1b7c-11ea-8c87-04f516180f5e.gif)

Can you please try [3.3 RC1](https://github.com/gitextensions/gitextensions/releases/tag/v3.3-RC1) and see if you still experience the issue?

**Comment by pmiossec** [comment] 2019-12-10 08:16
Duplicate of #7376
Solved by someone called @RussKie 😉 with #7398

**Comment by RussKie** [comment] 2019-12-10 08:22
😂 thank you
glad someone is keeping track of what's being fixed.

**Comment by pmiossec** [comment] 2019-12-10 08:29
>glad someone is keeping track of what's being fixed.

I'm not. I'm completely lost in all the bug reports. I don't have a very good memory.
But this one still reminds me something... (a bug talking about administrator)

**Closed by pmiossec** 2019-12-10 08:29 UTC
Labels: :mailbox_with_no_mail: needs: author feedback, status: incorrectly filled template
