### ISSUE TITLE
The commit button does not change color if there are modified files (2.51.RC1 Windows )

### ISSUE THREAD

**Issue by fabvit** [gitextensions/gitextensions#4336] opened 2018-01-08 11:36 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
The commit button does not change color if there are modified files in the working dir. Furthermore, changing the GitExtensions setting "Show number of changed files on commit button (restart required)" do not shows any numbers of files to be committed on the commit button.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Important Note**
The problem only happens if I open a repository by first launching GitExtensions and then clicking on a Recent Repository. Instead, opening a repository via the Explorer context menu GitEx Browse, behaves correctly: I can see the commit button both with changed color and with the number of files to commit.

**What is the expected behavior?**
The commit button should change the color  from green to red if there are modified files in the working dir.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.RC1 Windows 
- GIT version: git version 2.15.1.windows.2
- OS version: Windows 7 Pro 64 bit English SP1

**Did this work in previous version of GitExtensions (which)?**
Yes, in current stable version (aka 2.50.02 windows) everything works as expected.

**Comment by RussKie** [comment] 2018-01-08 13:36
Duplicate of #4295

**Comment by RussKie** [comment] 2018-01-08 13:37
This has been fixed and will come out in the next round of release

**Closed by RussKie** 2018-01-08 13:37 UTC

**Comment by fabvit** [comment] 2018-01-08 14:21
Fantastic! Thank you!
