### ISSUE TITLE
[NBug] FileNotFoundException when SMB share connection is interrupted

### ISSUE THREAD

**Issue by mm201** [gitextensions/gitextensions#6937] opened 2019-07-22 17:46 UTC
## Current behaviour
A System.IO.FileNotFoundException is raised.

## Expected behaviour
Program should be more resilient against brief interruptions.

## Steps to reproduce
Open a repo hosted on a mounted network drive.
Simulate some connection problems, e.g. unplug and replug your ethernet cable.

## Error Details
```
System.IO.FileNotFoundException: Error reading the H:\ctf-fce-sharepoint\ directory.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.Update()
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Repo is in an SMB share.

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 192dpi (200% scaling)

**Comment by gerhardol** [comment] 2019-07-22 21:02
Duplicate of #6812
Corrected in #6834 (to be included in 3.2)

**Closed** 2019-07-22 21:02 UTC
