### ISSUE TITLE
[NBug] fatal: unrecognized argument: ->

### ISSUE THREAD

**Issue by bartkdm** [gitextensions/gitextensions#11357] opened 2023-11-15 09:35 UTC
### Environment

- Git Extensions 4.2.0.17591
- Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c log.showSignature=false log --pretty=%ci
%an
%s origin/HEAD -> origin/master^1..origin/HEAD -> origin/master

```
GitExtUtils.ExternalOperationException: fatal: unrecognized argument: ->
 ---> System.Exception: fatal: unrecognized argument: ->
   --- End of inner exception stack trace ---
   at async Task<string> GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 147
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at IEnumerable<Branch> GitExtensions.Plugins.DeleteUnusedBranches.DeleteUnusedBranchesForm.GetObsoleteBranches(RefreshContext context, string curBranch)+MoveNext() in C:/projects/gitextensions/Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs:line 103
   at void System.Collections.Generic.List<T>.InsertRange(int index, IEnumerable<T> collection)
   at void GitUI.SortableBindingList<T>.AddRange(IEnumerable<T> items) in C:/projects/gitextensions/GitUI/SortableBindingList.cs:line 20
   at async Task GitExtensions.Plugins.DeleteUnusedBranches.DeleteUnusedBranchesForm.RefreshObsoleteBranchesAsync() in C:/projects/gitextensions/Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs:line 347
   at async void GitUI.TaskManager.InvokeAndForget(Control control, Func<Task> asyncAction, CancellationToken cancellationToken)+(?) => { } [1] in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 111
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

I opened "Delete obsolute branches" and clicked "Delete remote branches from" and then this error appeared

### Steps to reproduce

I opened "Delete obsolute branches" and clicked "Delete remote branches from" and then "Search branches" and this error appeared

### Did this work in previous version of GitExtensions?

yes

**Comment by blaise-braye** [comment] 2023-12-26 13:20
attempted with same build --> same symptom, an error window appears complaining about invalid arguments
attempted with version 4.1.0 --> no more error, instead infinite loading spinner...
attempted with version 4.0.2 ---> idem: no error, instead infinite loading spinner...
attempted with version 3.5.4.12724 --> succeeded.

conclusion: this appears to be broken since the major upgrade from 3 to 4

**Comment by gerhardol** [comment] 2023-12-26 13:36
Try the build in #11470 

Since 4.0, GE uses the wsl git executable by default
To use the Windows Git executable, map \\wsl$ to a Windows drive

**Comment by ZzzZeta** [comment] 2023-12-26 15:55
I'm not sure if it should be like this:

https://github.com/gitextensions/gitextensions/blob/9f594eef482be216b06347d559d8e60eb5430e04/Plugins/DeleteUnusedBranches/GitBranchOutputCommandParser.cs#L12

```diff
-            foreach (string line in commandOutput.Split('\n').Where(line => !string.IsNullOrWhiteSpace(line) && line.Length > 2)))
+            foreach (string line in commandOutput.Split('\n').Where(line => !string.IsNullOrWhiteSpace(line) && line.Length > 2).Where(line => !line.Contains(" -> ")))

```

**Comment by gerhardol** [comment] 2023-12-26 17:49
#11470 is merged, probably not related to this.

> I'm not sure if it should be like this:

The traceback indicates that the output contains `->` but that is not described in the Git doc, I have not seen this.

What is your configuration? (Screenshot is fine)
What command is used (see GE Git command log)? (Default `git branch --list --merged HEAD` )
What is the output of the command? If wsl related, also with Windows Git.

**Comment by ZzzZeta** [comment] 2023-12-26 17:58
> #11470 is merged, probably not related to this.
>
> > I'm not sure if it should be like this:
>
> The traceback indicates that the output contains `->` but that is not described in the Git doc, I have not seen this.
>
> What is your configuration? (Screenshot is fine) What command is used (see GE Git command log)? (Default `git branch --list --merged HEAD` ) What is the output of the command? If wsl related, also with Windows Git.

https://github.com/gitextensions/gitextensions/blob/9f594eef482be216b06347d559d8e60eb5430e04/Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs#L120

It's actually `git branch -r --list --merged HEAD`, and the output is:

```console
  origin/HEAD -> origin/master
  origin/master
```

**Comment by gerhardol** [comment] 2023-12-26 19:37
I get the same output for https://gitlab.kitware.com/cmake/cmake.git
But I cannot get it for GH repos. .git/refs/remotes/origin/HEAD has a symbolic reference for GitLab (contents "ref: branchname" instead of sha), not included for GitHub.

If symbolic refs should be excluded,  something like https://github.com/gitextensions/gitextensions/issues/11357#issuecomment-1869630928 could be used.
An alternative is to just split at first space to list refs too, they will not have "Last activity" etc but can be deleted.
Will submit a PR based on the latter. (To delete refs/remote/origin/HEAD should not be possible and refs/heads/HEAD is actually just HEAD, so not included.) Not sure how to create such refs with commands? (

Tried to get this from Git source as not described in git-branch man page, but some info in https://git-scm.com/book/en/v2/Git-Internals-Git-References.

**Comment by ZzzZeta** [comment] 2023-12-26 20:32
> I get the same output for https://gitlab.kitware.com/cmake/cmake.git But I cannot get it for GH repos. .git/refs/remotes/origin/HEAD has a symbolic reference for GitLab (contents "ref: branchname" instead of sha), not included for GitHub.

I'm pretty certain it does show a similar result for Github repos. I can reproduce it in a fresh Windows Sandbox.

Output for gitextensions/gitextensions:

```console
> git branch -r --list
  origin/HEAD -> origin/master
  origin/LibGit2Sharp
  origin/configdata
  origin/experimental/setup
  origin/feature/5673
  origin/feature/LibGit2SharpPerformance
  origin/feature/graphperformance
  origin/feature/graphperformance_3.00.00
  origin/feature/graphperformance_3.00.00_locks
  origin/feature/spellchecker
  origin/master
  origin/mono
  origin/msi
  origin/net7.0
  origin/release/2.48
  origin/release/2.49
  origin/release/2.50
  origin/release/2.51
  origin/release/3.0.2
  origin/release/3.00
  origin/release/3.1
  origin/release/3.2
  origin/release/3.3
  origin/release/3.4
  origin/release/3.5
  origin/release/4.0
  origin/release/4.1
```

> If symbolic refs should be excluded, something like [#11357 (comment)](https://github.com/gitextensions/gitextensions/issues/11357#issuecomment-1869630928) could be used. An alternative is to just split at first space to list refs too, they will not have "Last activity" etc but can be deleted. Will submit a PR based on the latter. (To delete refs/remote/origin/HEAD should not be possible and refs/heads/HEAD is actually just HEAD, so not included.) Not sure how to create such refs with commands? (

I think only HEAD would show the branch it points to, but I'm not sure.

> Tried to get this from Git source as not described in git-branch man page, but some info in https://git-scm.com/book/en/v2/Git-Internals-Git-References.

There are some hints here: https://git-scm.com/docs/git-log#Documentation/git-log.txt-emdecorateltoptionsgtem

**Comment by gerhardol** [comment] 2023-12-26 21:21
> I'm pretty certain it does show a similar result for Github repos. I can reproduce it in a fresh Windows Sandbox.

I do not get the symbolic refs when cloning GH, but the point was rather that you get it with GitLab.
It is easier to create a ref manually, like `cp .git/HEAD  .git/refs/heads/h2`

PR exists, to exclude refs completely can be discussed

**Closed** 2023-12-27 18:57 UTC
Labels: area: plugins, :eyeglasses: status: needs review, :construction: status: in progress
