### ISSUE TITLE
GitHub fork repository should have https option

### ISSUE THREAD

**Issue by NN---** [gitextensions/gitextensions#5875] opened 2018-12-09 12:46 UTC
**Do you want to request a *feature* or report a *bug*?**
Depends how you see this.

**What is the current behavior?**
When I use GitHub->Fork/Clone I get my fork with URL git@github.com/...  and the original repository with URL git://github.com/....
The problem is that I don't have write permissions to the original repository and then git:// protocol doesn't work.
I change it manually to https:// and then it works well.
I would like to have an option for deciding whether to use git:// or https:// for the original repository.

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.2.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 120dpi (125% scaling)

**Comment by vbjay** [comment] 2018-12-09 17:31
Duplicate of #5418

**Closed** 2018-12-09 20:49 UTC
