### ISSUE TITLE
Pressing [Ctrl]+[R] crashes the app 

### ISSUE THREAD

**Issue by tomasfejfar** [gitextensions/gitextensions#3683] opened 2017-04-28 15:04 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* open any repository
* Press <kbd>Ctrl</kbd>+<kbd>R</kbd>

**What is the current behavior?**
App crashes (I chose `Send and Quit` moments ago). 
![image](https://cloud.githubusercontent.com/assets/642928/25534589/83f169f0-2c34-11e7-9e42-e6dbed9786a6.png)

**What is the expected behavior?**
Nothing particular. It's shortcut for reverse search in git bash. So, it's common to press <kbd>Ctrl</kbd>+<kbd>G</kbd> to run Git Bash and then <kbd>Ctrl</kbd>+<kbd>R</kbd> to search for command. 

**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
Not sure :(

**Comment by rbares** [comment] 2017-05-01 11:45
Duplicate of #3534

**Closed** 2017-05-04 10:41 UTC
