### ISSUE TITLE
Submodule failure #5087

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5194] opened 2018-07-24 08:27 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Occasional failures when switching commits and/or repos quickly after startup
This is probably introduced or occurring more often due to  #5087

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
See below

**What is the expected behavior?**
No exception

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
pre #5087

**Comment by drewnoakes** [comment] 2018-07-25 17:13
I think this was fixed in #5203. I created a duplicate of this issue in #5200. Reopen if you disagree.

**Closed by drewnoakes** 2018-07-25 17:13 UTC
Labels: high priority, type: bug, type: regression
