### ISSUE TITLE
Commit Dialogue no longer remembers the window position and size from previous time

### ISSUE THREAD

**Issue by AdamSturtridge** [gitextensions/gitextensions#5063] opened 2018-06-12 10:56 UTC
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?** Open commit dialogue, change its size and position by dragging the corner, close the dialog and then reopen. It is back to its default size again!

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** Open commit dialogue, change its size and position by dragging the corner, close the dialog and then reopen. It is back to its default size again!

**What is the expected behavior?** Expect the commit dialogue to open with the position and size on previous time it was open

**Environment you encounter the issue:**

- GitExtensions version: 2.51.02
- GIT version:   2.16.2.windows.1
- OS version:  Windows 10

**Did this work in previous version of GitExtensions (which)?** 2.51.01

**Comment by RussKie** [comment] 2018-06-12 13:06
Duplicate of #5041

**Closed by RussKie** 2018-06-12 13:06 UTC
