### ISSUE TITLE
"Reset all changes" button deletes ignored files

### ISSUE THREAD

**Issue by Danand** [gitextensions/gitextensions#6263] opened 2019-02-18 08:33 UTC
## Current behaviour
Since 3.0 It looks like button "Reset all changes" in commit window does:
```git reset --hard && git clean -fdx```
instead of:
```git reset --hard && git clean -fd```

E.g. I had ignored path `Library/` in project, so it's gone – folder with content was deleted.

## Expected behaviour
Button "Reset all changes" resets current changes (both staged and unstaged) only:
- modifications
- additions
- deletions

Not touching ignored paths.

## Steps to reproduce
1. Add some files or non-empty directories to `.gitignore`
2. Press "Reset all changes" in commit window.
3. Notice ignored files was deleted.

## Did this work in previous version of GitExtensions
It works fine before 3.0.

## Environment
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-02-18 08:54
Duplicate of #5849 
Corrected in #6002 (#6001)
Included in 3.0.1

**Closed by gerhardol** 2019-02-18 08:54 UTC
