### ISSUE TITLE
[NBug] InvalidArgument=Value of '0' is not valid for 'index'.Par...

### ISSUE THREAD

**Issue by TonySullivan** [gitextensions/gitextensions#6698] opened 2019-05-29 14:04 UTC
## Error Details
```
System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   at System.Windows.Forms.ComboBox.get_Text()
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.17.1.windows.2
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.3801.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-05-29 18:19
Duplicate of #6680

**Closed by gerhardol** 2019-05-29 18:19 UTC
Labels: potential-duplicate
