### ISSUE TITLE
Can't type commands in bash shell

### ISSUE THREAD

**Issue by brianharwell** [gitextensions/gitextensions#4061] opened 2017-10-13 20:08 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I do a `git log` and then hit `CTRL+C` to cancel the log command I can no longer type in the shell window. Enter works but that's it. I have to close and reopen git extensions.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Type `git log` in a repository with a long history
2. Type `CTRL+C`
3. Try typing another git command

**What is the expected behavior?**
I can type other commands without needing to restart git extension

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version:  2.14.2.windows.3
- OS version: Windows 10 64bit

**Did this work in previous version of GitExtensions (which)?**
No it has always behaved this way for me

**Comment by vbjay** [comment] 2017-10-13 22:30
Switch from the console tab to another and back to console.

**Comment by RussKie** [comment] 2017-10-14 00:20
Duplicate of #4054

**Closed by RussKie** 2017-10-14 00:20 UTC

**Comment by brianharwell** [comment] 2017-10-14 13:13
My apologies for the duplicate.

@vbjay Switching tabs does not resolve the issue.

**Comment by vbjay** [comment] 2017-10-14 13:25
Hit ctrl c again and do it. It will force bash to quit and then switching
back will spin up a new bash.

**Comment by brianharwell** [comment] 2017-10-14 13:30
Negative, hitting `CTRL+C` gives me a new line and switching tabs does not fix the issue.

**Comment by vbjay** [comment] 2017-10-14 13:32
Keep hitting it till you see bash logout.

**Comment by MingLeo** [comment] 2019-09-26 18:59
https://stackoverflow.com/questions/28073577/git-bash-wont-let-me-type-anything-just-shows-a-blinking-cursor

Soln:  Type the word 'reset' without the  enclosing brackets ' '  then press< Enter > button. Works for me.

**Comment by RussKie** [comment] 2019-09-28 11:18
Thank you @MingLeo
