### ISSUE TITLE
[NBug] 'The directory name is invalid' crash when new worktree path has trailing backslash

### ISSUE THREAD

**Issue by vijaysitaram** [gitextensions/gitextensions#8251] opened 2020-06-19 21:28 UTC
## Current behaviour

My current git workspace path was at `P:\Dev\nicentral`
I tried to create a new worktree with the name `P:\Dev\nicentral_xnet20.1release\` in the **Repository»Worktrees»Create Worktree** dialog, but didn't realize I had the trailing backslash in there at the time. This led to a crash, probably because the backslash didn't get trimmed off, and thus got badly escaped:

```
"C:\Program Files\Git\bin\git.exe" worktree add "P:\Dev\ni-central_xnet20.1release\" users/vsitaram/xnet_20.1_relock
Preparing worktree (new branch 'xnet_20.1_relock')
fatal: could not create leading directories of 'P:/Dev/ni-central_xnet20.1release" users/vsitaram/xnet_20.1_relock/.git': Invalid argument
Done

Press Enter or Esc to close console...
```

## Expected behaviour
I would expect the new tree to be created at the path given, with redundant trailing backslashes having been stripped off.

I was able to get it to work by going back through the steps with the same path, but without the trailing backslash

## Steps to reproduce

See Current behavior section

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.ExecutableExtensions.<ExecuteAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.get_GitCommonDirectory()
   at GitCommands.Settings.ConfigFileSettings.CreateLocal(GitModule module, ConfigFileSettings lowerPriority, SettingLevel settingLevel, Boolean allowCache)
   at GitCommands.Settings.ConfigFileSettings.CreateEffective(GitModule module)
   at GitCommands.GitModule.get_EffectiveConfigFile()
   at GitCommands.GitModule.get_FilesEncoding()
   at GitUI.Editor.FileViewer.encodingToolStripComboBox_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ToolStripComboBox.HandleSelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at System.Windows.Forms.ToolStripComboBox.set_SelectedIndex(Int32 value)
   at GitUI.Editor.FileViewer.<set_Encoding>b__58_0()
   at GitUI.GitUIExtensions.<InvokeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment] 2020-06-20 22:14
Could not reproduce the crash neither with git 2.26.0 nor with 2.27.0. Git prints different errors depending on wether the branch contains a slash or not. GE opens the dashboard because the new worktree has not been created.

**Comment by gerhardol** [comment] 2020-06-20 22:30
Should be changed to create the worktree correctly.
Similar to #8237 
Same potential issue for a number of submodule commands

The effort is not to do the patch, it will be to refactor, add tests and discuss the PR...
Until then, just not add a trailing separator...

```
 GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs b/GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs
index 87730..c28aa 100644
--- a/GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs
+++ b/GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs
@@ -108,7 +108,7 @@ private void CreateWorktree()
             var args = new GitArgumentBuilder("worktree")
             {
                 "add",
-                WorktreeDirectory.Quote(),
+                WorktreeDirectory.RemoveTrailingPathSeparator().Quote(),
                 {
                     radioButtonCreateNewBranch.Checked,
                     $"-b {textBoxNewBranchName.Text}",
```

**Comment by gerhardol** [comment] 2021-04-19 21:39
Duplicate of #9091 Forward duplicate, continue discussion there.
Please try 3.5 RC1 where the error is displayed with more details

**Closed by gerhardol** 2021-04-19 21:39 UTC
Labels: :beetle: type: bug, area: worktree
