### ISSUE TITLE
[NBug] Impossible de trouver une partie du chemin d'accès

### ISSUE THREAD

**Issue by kev-in-shu** [gitextensions/gitextensions#8637] opened 2020-11-25 08:57 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Current behaviour

Trying to close gitextensions by right clicking on the icon in the Windows Task bar, while a commit window is still open.
It did not work, but rendered git extension unstable, and made it crash when I closed the commit window.

## Expected behaviour

No crash.

## Steps to reproduce
- Open commit window.
- Right click on gitextension icon in Windows Task bar
- Choose "Close window" (nothing happens)
- Close the commit window
- Git extension crashed

## Error Details
```
System.IO.DirectoryNotFoundException: Impossible de trouver une partie du chemin d'accès 'C:\path\to\local\repo\GitExtensions.amend'.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.File.InternalDelete(String path, Boolean checkHost)
   à System.IO.File.Delete(String path)
   à System.IO.Abstractions.FileWrapper.Delete(String path)
   à GitCommands.CommitMessageManager.set_AmendState(Boolean value)
   à GitUI.CommandsDialogs.FormCommit.OnFormClosed(FormClosedEventArgs e)
   à System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)
```

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.8.4261.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2020-11-25 22:13
Duplicate of #7751

In the other occurrences the Git repo was deleted too. Was that done here?
Should be the same problem regardless.

**Comment by kev-in-shu** [comment] 2020-11-26 21:00
No, git repo was not deleted in my case.

Tried to reproduce again today, but did not manage to make it happen again.

**Comment by RussKie** [comment] 2021-04-27 14:19
Duplicate of #7751
There are some other similar stack traces when the repo supposedly was not deleted too.

If you remove the repo when in use, a lot of things may go wrong
However, there are changes in upcoming 3.5 to improve the presentation of the exceptions

**Closed by RussKie** 2021-04-27 14:19 UTC
