### ISSUE TITLE
User manual borken

### ISSUE THREAD

**Issue by chris-findlay** [gitextensions/gitextensions#5948] opened 2018-12-18 22:56 UTC
**Bug**

**What is the current behavior?**
Search on user manual pages doesn't work, likely due to the JS error I get on every page:
```
TypeError: $(...).on is not a function[Learn More] readthedocs-doc-embed.js:1:34551
init
https://assets.readthedocs.org/static/javascript/readthedocs-doc-embed.js:1:34551
[21]</<
https://assets.readthedocs.org/static/javascript/readthedocs-doc-embed.js:1:41618
ready
https://git-extensions-documentation.readthedocs.io/en/release-3.00/_static/jquery.js:26:287
L
https://git-extensions-documentation.readthedocs.io/en/release-3.00/_static/jquery.js:33:149
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Help > User Manual; attempt to search.

**What is the expected behavior?**
Search works.

**Environment you encounter the issue:**
Note that this affects the 2.51 docs as well as the 3.00 docs.

**Did this work in previous version of GitExtensions (which)?**
Worked a few days ago.

**Comment by RussKie** [comment] 2018-12-19 06:54
Hmm...
According to this [SO](https://stackoverflow.com/a/21625346/2338036) - jQuery `on` method was introduced in v1.7.
[We're using 1.4.2](https://git-extensions-documentation.readthedocs.io/en/latest/_static/jquery.js)

**Comment by gerhardol** [comment] 2018-12-19 07:50
The problem is on the server build. The version switcher in the right hand corner is also not responding.
2.51 has not been changed but fails after a rebuild. (2.50 should work.)
So something is changed in the server build.
The Sphinx configuration does not specify versions on the jQuery level.

**Comment by gerhardol** [comment] 2018-12-22 20:37
This seem to be a problem with the readthedocs extensions to Sphinx, I can now reproduce locally too.
I have not found how to get around this. GE has a very basic use of readthedocs, so I do not see what occurs.
Issue opened to readthedocs.

**Comment by gerhardol** [comment] 2018-12-23 12:31
I have implemented a workaround, search work again now.

The workaround should be reverted when readthedocs fixes the bug.

**Comment by RussKie** [comment] 2018-12-30 12:14
Closing as the docs are now unborked 😎

**Closed by RussKie** 2018-12-30 12:14 UTC
Labels: area: documentation, type: bug
