### ISSUE TITLE
Warning on rewriting git history that's already 'pushed'

### ISSUE THREAD

**Issue by palver123** [gitextensions/gitextensions#3797] opened 2017-06-30 13:05 UTC
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
The user can freely use _amend_ commits and _rebase_ them.

**What is the expected behavior?**
If the user tries to amend a commit that's already been pushed, or rebase such commits, a warning message could pop up to warn him. Good for users not familiar with these features.

I am not an advanced git user myself, but according to the [git book (2nd Ed.)](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History), one should only rewrite local history and never alter it after it's been published. Other contributors might have already pulled those changes and appended commits to those revisions.

If the feature is approved I may implement it when I find the time! What's your thoughts?

**Comment by vbjay** [comment] 2017-06-30 22:00
Read up on force-with-lease git push option.

**Comment by karyon** [comment] 2017-08-27 05:53
at least when amending i get the exact warning you are proposing, if i understand you correctly.

**Comment by RussKie** [comment] 2017-08-27 07:32
I venture to say that you are likely using git correctly, if you are worried about overwriting someone else's commits with force push... 
You should not be working off main branches (i.e. master etc) directly, instead you should be merging via pull requests and do you work either on forks or feature branches. 
You should also look into securing your main branches from direct writes.

**Comment by RussKie** [comment] 2017-08-27 11:03
Duplicate of #1732

**Comment by RussKie** [comment] 2018-11-12 05:04
Closing due to age.

**Closed by RussKie** 2018-11-12 05:04 UTC
Labels: type: discussion
