### ISSUE TITLE
[NBug] Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by AllieZZ** [gitextensions/gitextensions#11299] opened 2023-10-24 16:16 UTC
### Environment

- Git Extensions 4.2.0.17539
- Build d3b383c77a3cda85b835c7e6325c0ebb146a8be9
- Git 2.39.1.windows.1 (recommended: 2.41.0 or later)
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.23
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at void GitUI.RevisionGridControl.PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs, bool forceRefresh)+() => { } in C:/projects/gitextensions/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:line 1333
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 28
```

Open repository and log view crash

### Steps to reproduce

open big repository

**Comment by mstv** [comment] 2023-10-24 22:07
For technical reasons, it is not clear where the error occurred.
Could you share the affected repo? If not, does it work for publicly available repos?
Do you use special encodings?

---

This error was reported through `OnRevisionReaderError`.
Due to the limitations of `System.Reactive.Subjects.Subject<>`, the exception lacks the internal callstack, and `ArgumentOutOfRangeException` is not specific either.

**Comment by gerhardol** [comment] 2023-10-24 22:54
You may get information from the trace output, use e.g. https://learn.microsoft.com/en-us/sysinternals/downloads/debugview

If you debug yourself, the throw should be in RevisionReader.cs:GetLog()

**Comment by mstv** [comment] 2023-10-25 18:53
Duplicate of #11260. Because of the comments added here, continue in this one.

**Comment by IEVin** [comment] 2023-10-30 21:01
I found WTR for that. Commit graph throws an exception when one of commits messages (unwrapped subject) starts with a new line.
```
git init
git commit --allow-empty --cleanup=verbatim -m "
test"
```

In our repo commits like that can be created with git-as-svn. But in previous GE version it worked success.

Problem that currentOffset [here](https://github.com/gitextensions/gitextensions/blob/04c7dae18856ac65ff1a64ab833344c3d2f9d245/GitCommands/RevisionReader.cs#L462C50-L462C50) = -1 because lengthSubject = 0 in that case.

**Closed** 2023-10-31 11:59 UTC
