### ISSUE TITLE
Retrieve Github Pull Request Template

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#3628] opened 2017-04-02 23:55 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
![image](https://cloud.githubusercontent.com/assets/3629489/24592081/f9c401c6-17dd-11e7-982a-e73780ff52a1.png)
Body field is always empty.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
**What is the expected behavior?**
The body field to have the the pull request template filled in if the template exists.  Look in root and .github folder.
**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
N/A

**Comment by RussKie** [comment] 2018-09-17 11:06
Duplicate of #5223

**Closed by RussKie** 2018-09-17 11:06 UTC
Labels: area: plugins, good first issue, type: feature request
