### ISSUE TITLE
No refresh after stash pop

### ISSUE THREAD

**Issue by 011V32** [gitextensions/gitextensions#9290] opened 2021-06-17 07:40 UTC
## Current behaviour

If you do a stash, it will be displayed correctly in the tree. If you fetch this stash with stash pop, the stash will continue to be displayed in the tree and will continue to do so until the tree is updated.

## Expected behaviour

After the stash pop, the tree should also be updated, so that the stash is no longer visible in the tree. This was also the case in the previous versions.

## Steps to reproduce

Make a stash and then fetch it again using stash pop.

## Did this work in previous version of GitExtensions

< V3.5

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.32.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment] 2021-06-17 07:43
Duplicate of #9121. Already fixed. Waiting for release of v3.5.1

**Closed by pmiossec** 2021-06-17 07:43 UTC

**Comment by 011V32** [comment] 2021-06-17 07:51
Sry, my fault. I just figured out that I was only looking at the open issues. :(
I will try to avoid this in the future.
Thx, for your time.
Regards
