### ISSUE TITLE
[NBug] Value cannot be null. (Parameter 'input') - when executing AfterPull script

### ISSUE THREAD

**Issue by KarolStosik** [gitextensions/gitextensions#11905] opened 2024-09-11 07:03 UTC
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Match(String input)
   at GitUI.ScriptsEngine.ScriptsManager.ScriptRunner.ParseUserInputs(String scriptName, String arguments, IGitUICommands uiCommands, IWin32Window owner, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.ScriptRunner.cs:line 46
   at GitUI.ScriptsEngine.ScriptsManager.ScriptRunner.RunScriptInternal(ScriptInfo script, IWin32Window owner, IGitUICommands uiCommands, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.ScriptRunner.cs:line 133
   at GitUI.ScriptsEngine.ScriptsManager.ScriptRunner.RunScript(ScriptInfo script, IWin32Window owner, IGitUICommands commands, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.ScriptRunner.cs:line 32
   at GitUI.ScriptsEngine.ScriptsManager.RunEventScripts[THostForm](ScriptEvent scriptEvent, THostForm form) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.cs:line 57
   at GitUI.CommandsDialogs.FormPull.<>c__DisplayClass45_0.<PullChanges>g__executeAfterScripts|6() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormPull.cs:line 623
   at GitUI.CommandsDialogs.FormPull.PullChanges(IWin32Window owner) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormPull.cs:line 472
   at GitUI.CommandsDialogs.FormPull.PullAndShowDialogWhenFailed(IWin32Window owner, String remote, GitPullAction pullAction) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormPull.cs:line 276
   at GitUI.GitUICommands.<>c__DisplayClass96_0.<StartPullDialogInternal>g__Action|0() in C:\projects\gitextensions\src\app\GitUI\GitUICommands.cs:line 627
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent) in C:\projects\gitextensions\src\app\GitUI\GitUICommands.cs:line 322
   at GitUI.GitUICommands.StartPullDialogInternal(IWin32Window owner, Boolean pullOnShow, Boolean& pullCompleted, String remoteBranch, String remote, GitPullAction pullAction) in C:\projects\gitextensions\src\app\GitUI\GitUICommands.cs:line 639
   at GitUI.GitUICommands.StartPullDialogAndPullImmediately(Boolean& pullCompleted, IWin32Window owner, String remoteBranch, String remote, GitPullAction pullAction) in C:\projects\gitextensions\src\app\GitUI\GitUICommands.cs:line 612
   at GitUI.GitUICommands.StartPullDialogAndPullImmediately(IWin32Window owner, String remoteBranch, String remote, GitPullAction pullAction) in C:\projects\gitextensions\src\app\GitUI\GitUICommands.cs:line 605
   at GitUI.CommandsDialogs.FormBrowse.DoPull(GitPullAction pullAction, Boolean isSilent) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormBrowse.cs:line 2320
   at GitUI.CommandsDialogs.FormBrowse.ToolStripButtonPullClick(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormBrowse.cs:line 2282
   at System.Windows.Forms.ToolStripSplitButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m) in C:\projects\gitextensions\src\app\GitUI\UserControls\ToolStripEx.cs:line 89
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

Script executed on `AfterPull` throws ArgumentNullException. The script is: `git fetch origin refs/tags/*:refs/tags/* --prune`. It worked fine in 4.0

### Steps to reproduce

Add script `AfterPull` that does the following: `git fetch origin refs/tags/*:refs/tags/* --prune`. Then pull

### Did this work in previous version of GitExtensions?

4.0

**Comment by RussKie** [comment] 2024-09-11 07:14
Looks like a duplicate of https://github.com/gitextensions/gitextensions/issues/11892. Fixed by https://github.com/gitextensions/gitextensions/pull/11893

You could test the portable version to confirm if issue is fixed: [ci.appveyor.com/project/gitextensions/gitextensions/builds/50564009/artifacts](https://ci.appveyor.com/project/gitextensions/gitextensions/builds/50564009/artifacts)

Ask for reopen if it's not the case.

**Closed by RussKie** 2024-09-11 07:14 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
