### ISSUE TITLE
Can't restore any minimized window

### ISSUE THREAD

**Issue by zyplay** [gitextensions/gitextensions#10841] opened 2023-03-28 01:08 UTC
### Environment

- GitExtensions version: since 3.5
- GIT version: 
- OS version: win10
- .NET version: 

### Issue description

In win10 OS, I open 2 or more app instances, and then minimize them,  and I found that I can't restore anyone from taskbar，unless I right click it and choice ‘restore’.

![2023-03-28_090014](https://user-images.githubusercontent.com/10429891/228100356-40db7800-47e4-4816-acff-dcaa54fdf5d5.png)

### Steps to reproduce

just like what i say in Issue description

**Comment by gerhardol** [comment] 2023-03-28 07:22
Duplicate of #10398 See the issue for a kond of configuration workaround
Mostlt fixed in #10802 to be included in next release

**Closed by gerhardol** 2023-03-28 07:22 UTC
Labels: :eyeglasses: status: needs review

**Comment by Brouilles** [comment] 2023-03-29 13:37
Same on my side.
