### ISSUE TITLE
After update to 3.5.1 PuTTY key based authentication broken

### ISSUE THREAD

**Issue by andrew-adamson** [gitextensions/gitextensions#9360] opened 2021-07-11 08:52 UTC
## Current behaviour

I had working ssh key auth in version 3.5.0.11713 (3.5.0 release) but then it broke upon upgrading to 3.5.1.12196 (3.5.1 release). Instead of authenticating to the remote repo with the key it would ask me for a password, which I do not have.

Rolling back to 3.5.0 corrected the issue. 

## Expected behaviour
Working key based auth to a remote repository.

## Steps to reproduce

I have putty+pageant fully installed separately to Git Extensions, so have the path to pageant set as C:\Program Files\PuTTY\pageant.exe (and the other binaries also set to the same directory). "Automatically start authentication client when a private key is configured for a remote" is also ticked. On the remote repository settings I have the same private key file path set as the key loaded in pageant, and the "test connection" function passes the test in 3.5.1.

To reproduce, simply try and push changes to a remote repo, where it will prompt for a password instead of authenticating with the key.

## Did this work in previous version of GitExtensions

Yes, was working in the 3.5.0 release.

## Environment

- Git Extensions 3.5.0.11713 (was 3.5.1.12196 before rollback)
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4390.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2021-07-11 22:51
For explanations to changes in SSH in 3.5.1 see https://github.com/gitextensions/gitextensions/issues/9355#issuecomment-877706848
Please check the contents in the registry
Also check if any environment variables like GITEXT_PLINK are set, that overrides the ssh setting.
It may also be similar to the other reports that GE cannot access the plink path, then the fallback is to use an empty GIT_SSH setting, so Git tries to use OpenSSH.

This works for me.
(If pageant path is incorrect, I get a popup that pageant cannot be started, but some compatibility code tries to find pageant so it is not necessary normally.)

**Comment by gerhardol** [comment] 2021-07-12 22:57
Test build available, see https://github.com/gitextensions/gitextensions/issues/9355#issuecomment-878650413

**Comment by andrew-adamson** [comment] 2021-07-13 05:26
After several upgrade-downgrade cycles, and knowing where to look in the registry, I think I've found the issue. Prior to the upgrade, my gitssh entry in the registry was C:\Program Files\PuTTY\plink.exe. After upgrading to 3.5.1 the entry was changed to C:\Program Files (x86)\PuTTY\plink.exe, which doesn't exist. Going through tools->settings and checking the plink path still showed C:\Program Files\PuTTY\plink.exe. Hitting "apply" on the settings page was sufficient to correct the registry entry and make key-based pushing work again. I do not have any of GIT_SSH or GITEXT_PLINK set and I think this issue is unrelated to #9355

**Comment by albinsunnanbo** [comment] 2021-07-14 10:45
> After several upgrade-downgrade cycles, and knowing where to look in the registry, I think I've found the issue. Prior to the upgrade, my gitssh entry in the registry was C:\Program Files\PuTTY\plink.exe. After upgrading to 3.5.1 the entry was changed to C:\Program Files (x86)\PuTTY\plink.exe, which doesn't exist. Going through tools->settings and checking the plink path still showed C:\Program Files\PuTTY\plink.exe. Hitting "apply" on the settings page was sufficient to correct the registry entry and make key-based pushing work again. I do not have any of GIT_SSH or GITEXT_PLINK set and I think this issue is unrelated to #9355

Nice finding about hitting the "apply" button. That worked well for me too!

**Comment by CookiePLMonster** [comment] 2021-10-03 20:14
> After several upgrade-downgrade cycles, and knowing where to look in the registry, I think I've found the issue. Prior to the upgrade, my gitssh entry in the registry was C:\Program Files\PuTTY\plink.exe. After upgrading to 3.5.1 the entry was changed to C:\Program Files (x86)\PuTTY\plink.exe, which doesn't exist. Going through tools->settings and checking the plink path still showed C:\Program Files\PuTTY\plink.exe. Hitting "apply" on the settings page was sufficient to correct the registry entry and make key-based pushing work again. I do not have any of GIT_SSH or GITEXT_PLINK set and I think this issue is unrelated to #9355

The fact this helped makes it a duplicate of #4011 😁

**Closed** 2024-10-12 03:08 UTC
Labels: type: bug :bug:, area: ssh/putty
