### ISSUE TITLE
[NBug] An unexpected internal error occurred in the Win32 call: 80004005 COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.

### ISSUE THREAD

**Issue by ddimkovikj** [gitextensions/gitextensions#9523] opened 2021-08-19 22:35 UTC
## Current behaviour

Randomly crashes after running for few days.

## Expected behaviour

Not crash.

## Steps to reproduce

Unsure, it randomly crashed after being opened for few days.

## Error Details
```
System.ComponentModel.Win32Exception: An unexpected internal error occurred in the Win32 call: 80004005 ---> System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.

   --- End of inner exception stack trace ---
   at Microsoft.WindowsAPICodePack.Dialogs.NativeTaskDialog.NativeShow()
   at Microsoft.WindowsAPICodePack.Dialogs.TaskDialog.ShowCore()
   at GitUI.NBugReports.BugReportInvoker.Report(Exception exception, Boolean isTerminating)
   at GitExtensions.Program.<>c.<Main>b__1_3(Object s, ThreadExceptionEventArgs e)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

## Additional information
GE was open and running in the background when it crashed.

## Environment
- Git Extensions 3.5.2.12435
- Build 77413699a9c25b160a6a622311529372b5d87f5b
- Git 2.33.0.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4400.0
- DPI 96dpi (no scaling)

**Comment by ddimkovikj** [comment] 2021-08-19 22:38
I searched for this bug in issues prior to reporting and found only #8154(closed) and a mention in #9166 which should be fixed in 3.5.1.

**Comment by gerhardol** [comment] 2021-08-20 07:22
Duplicate of #9429

**Closed by gerhardol** 2021-08-20 07:22 UTC

**Comment by gerhardol** [comment] 2021-09-13 20:50
Please test the portable build in #9566 (currently latest build is https://ci.appveyor.com/project/gitextensions/gitextensions/builds/40747903/artifacts, there may be updates though).
This fixes an issue seen with themes as seen here, if you also could check the GDI object count it would be great.
