### ISSUE TITLE
Revision graph broken (regression)

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#11700] opened 2024-04-23 08:37 UTC
### Environment

- GitExtensions version: master ( 0b74e26ef4239e99822483eb59ed1c00ab8228fa )

### Issue description

At least on repository opening (I don't know if it could happen during a refresh)
it seems only when the repo has unrelated histories (but not sure)
the graph is broken:

![image](https://github.com/gitextensions/gitextensions/assets/460196/815a7089-76e5-43c3-87a4-57b2fb296db1)

instead of expected:

![image](https://github.com/gitextensions/gitextensions/assets/460196/bd812819-61b4-4193-883d-7982946feee4)

Refreshing the repository seems to make the bug disappear...

### Steps to reproduce

No clear steps:
1. switching from repos with unrelated histories increase the probability to get the bug

### Did this work in previous version of GitExtensions?

Bisected to 609e03d074ce312c036761ce39028a8ef70902f4, so yes, before

### Diagnostics

Handling of `e.Handled` is too aggressive?

**Comment by pmiossec** [comment] 2024-04-23 08:43
@mstv I can make a PR to revert to my previous version of the optimization that don't introduce the regression.
Or you would like to investigate?

**Comment by mstv** [comment] 2024-04-23 17:24
I have seen similar artifacts, too, mostly after rebase operations. I had two suspects: the commit identified by you or #11205.

> I can make a PR to revert to my previous version of the optimization that don't introduce the regression. Or you would like to investigate?

That variant had other issues.

I think this will be resolved by the planned graph rendering in the background. Give me a few weeks for this rewrite, please.
If you think, the issue is too severe, just revert the commit.

**Comment by mstv** [comment] 2024-05-01 20:02
Try it with #11718 and #11719, please.

**Comment by pmiossec** [comment] 2024-05-02 11:05
> Try it with #11718 and #11719, please.

I think it fixes the issue. Well done.

**Closed** 2024-05-12 19:57 UTC
Labels: :eyeglasses: status: needs review
