### ISSUE TITLE
[NBug] Value must not be null.

### ISSUE THREAD

**Issue by MaheshVcsoft** [gitextensions/gitextensions#11547] opened 2024-01-26 15:12 UTC
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.26
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.Exception: Value must not be null.
   at void Microsoft.Validates.Fail(string message) in C:/projects/gitextensions/GitExtUtils/Validates.cs:line 35
   at async void GitUI.CommandsDialogs.FormCheckoutBranch.Branches_SelectedIndexChanged(object sender, EventArgs e)+(?) => { } in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCheckoutBranch.cs:line 489
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

Created empty repo. Added remote and tried to checkout a remote branch. This is when I got the error

### Steps to reproduce

1. Create disk directory
2. Create a new personal repo
3. Add remote (use private key for authentication. & Test Connection)
4. Try to check out any remote branch

**Comment by gerhardol** [comment] 2024-01-26 17:27
Duplicate of #11498
Fixed in #11500

**Closed by gerhardol** 2024-01-26 17:27 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
