### ISSUE TITLE
Illegal character in path exception when opening clone dialog

### ISSUE THREAD

**Issue by knolleCC** [gitextensions/gitextensions#7807] opened 2020-02-25 15:10 UTC
## Current behaviour

1. Copy a clone command from a gerrit server (with download-links-plugin): 
   `git clone "ssh://user@gerrit:123/project"`
2. Open Git Extensions clone dialog
3. Exception window opens:

    System.ArgumentException
    Void CheckInvalidPathChars(System.String, Boolean) @ System.IO.Path

The problem is the "-sign which is not a valid file path.
GitExt tries to generate the directory name to be created from the clone adress and includes the ".

## Expected behaviour

GitExt should not throw an exception but open the dialog and mark the directory and/or the clone text box as invalid to force the user to correct the input.

Additonal Options:
1. GitExt should normalize or erase forbidden characters when generating the directory path to be created.
2. GitExt should remove prepended "git clone" commands (as e.g. TortoiseGit does).

## Error Details
```
System.ArgumentException: Illegal character in path.
   bei System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   bei System.IO.Path.Combine(String path1, String path2)
   bei GitUI.CommandsDialogs.FormClone.ToTextUpdate(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   bei System.Windows.Forms.Control.set_Text(String value)
   bei System.Windows.Forms.TextBoxBase.set_Text(String value)
   bei System.Windows.Forms.TextBox.set_Text(String value)
   bei GitUI.CommandsDialogs.FormClone.FromTextUpdate(Object sender, EventArgs e)
   bei GitUI.CommandsDialogs.FormClone.OnRuntimeLoad(EventArgs e)
   bei GitUI.GitExtensionsForm.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment] 2020-02-25 15:37
Did you mean `gitext clone "ssh://user@gerrit:123/project"`?

**Comment by knolleCC** [comment] 2020-02-25 17:38
> Did you mean `gitext clone "ssh://user@gerrit:123/project"`?

No. Gerrit gives you the ordinary git clone command for the cmd line.

**Comment by knolleCC** [comment] 2020-02-25 17:41
> Did you mean `gitext clone "ssh://user@gerrit:123/project"`?

No. Gerrit gives you the ordinary git clone command for the cmd line. 
Of course, you have to manually remove the "git clone" part to clone with GitExt. But due to the reported bug you dont even get to the dialog to do this.

**Comment by gerhardol** [comment] 2020-02-25 21:25
Removing quotes are done in other forms. There are a lot of special cases and extra support when quotes (like #7796) need special handling.
Removing the special string "git clone" is another special.
I am not positive about it, but if gerrit users go in, make the change and do the maintenance I believe it is OK.

**Comment by RussKie** [comment] 2020-02-25 22:43
> 2\. GitExt should remove prepended "git clone" commands (as e.g. TortoiseGit does).

A user may put an arbitrary string, how can we know what is a valid string is, and what's an invalid?

**Comment by RussKie** [comment] 2020-02-25 22:44
Maybe it is the Gerrit server must change to not enclose the url in `"`, because a url can't contain spaces, and as such does not require quoting.

**Comment by gerhardol** [comment] 2020-02-25 22:46
Both 'git clone' and '"' removal would gerrit specific adaptions.

**Comment by knolleCC** [comment] 2020-02-26 07:40
Thanks for the many replies so far. I understand that what I listed under additional options does not convince you and that is totally ok. 
However, these are just *additional* proposals. The key issue here is, that GitExt just fails with an exception when all I do is having something *bad* in my clipboard. The program should instead just mark the input text field as invalid (red or something) and tell me there are illegal chars so I have the chance to remove them. I think just throwing an exception is not an acceptable option for a user interface. 

Furthermore, the 1. Option, to remove illegal chars in the *generated directory path* (which is the actual problem - not the clone path) should be reconsidered to gain some more robustness. There is a similar feature when normalising branch names with '_'.

**Comment by gerhardol** [comment] 2020-02-26 12:55
For the actual exception, this is already handled:

Duplicate of #7528
You entered characters in the path that are illegal
So the workaround is to just dont do that

A check added in master #7633 (so popup instead)

**Comment by pmiossec** [comment] 2020-02-27 15:54
>For the actual exception, this is already handled:

I confirm. You end up with:
* `Repository to clone` value at `git clone "ssh://user@gerrit:123/project"`
*  `Subdirectory to create` value at `project"`.

Not great but definitely not a crash...

**Comment by knolleCC** [comment] 2020-02-28 13:57
Ok, so #7633 fixes the exception, thank you for pointing out.
As I understand this will go in 4.0, right?

As for the the proposed features: I guess "git clone [url]" is quite a common string and thus maybe worth to be handled, but that is up to you developers.
Gerrit users would probably appreciate it :-)

**Comment by RussKie** [comment] 2020-06-01 13:15
Duplicate of #7633

**Closed** 2020-06-01 13:14 UTC
Labels: :beetle: type: bug
