### ISSUE TITLE
Stash operations directly from revision grid

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5785] opened 2018-11-16 11:07 UTC
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

Right-clicking a stash in the revision grid shows:

![image](https://user-images.githubusercontent.com/350947/48617851-735efc00-e98f-11e8-9fc8-da9cae5aeedf.png)

**What is the expected behavior?**

User should have option of dropping, applying and viewing a stash from here.

Current workaround is to go to the stashes UI, try to find the corresponding stash (this correlation can be hard if you have many stashes) and operate on it from there. It's error prone and inconvenient.

**Environment you encounter the issue:**

- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0
- DPI X:150.00% Y:150.00%

**Did this work in previous version of GitExtensions (which)?**

I don't believe so.

**Comment by mstv** [comment] 2018-12-31 14:53
GE shows only the latest stash in the Revision Grid, refer to [Gerhard's comment](https://github.com/gitextensions/gitextensions/issues/5371#issuecomment-417574124).

**Comment by vbjay** [comment] 2018-12-31 15:53
> GE shows only the latest stash in the Revision Grid, refer to Gerhard's comment.

That is a bug.  We should show all stashes like we did before.  

![image](https://user-images.githubusercontent.com/3629489/50563346-1d99a580-0cea-11e9-9686-9ca0e55c32cc.png)

**Comment by gerhardol** [comment] 2018-12-31 16:33
No change for stashes in 2.x and 3.0: By default only latest stash shown. That stash is shown at all is due to that it is in refs/. This should probably be removed.

All stashes are shown if reflogs are shown in revision grid. You cannot manipulate stashes directly but compare files, reset etc.

**Comment by vbjay** [comment] 2018-12-31 17:05
Actual it is a change.  Stashes would show up on top of the commit they were based on before.

**Comment by gerhardol** [comment] 2018-12-31 17:09
>Actually it is a change. Stashes would show up on top of the commit they were based on before.

Not compared to 2.51

No reflogs

![image](https://user-images.githubusercontent.com/6248932/50564658-01682980-0d27-11e9-96bc-bf40dd98e310.png)

reflogs

![image](https://user-images.githubusercontent.com/6248932/50564666-19d84400-0d27-11e9-99e8-7ce1c6a7ab6c.png)

**Comment by vbjay** [comment] 2018-12-31 17:14
Think it is a git change.  Because I remember stashes being in the commit
history and not on top like it is now.

**Comment by vbjay** [comment] 2018-12-31 17:20
I see the issue.  Ok it is based on time.  What I meant was the first
commit in the stash would link straight to the commit it was based to.
Like in your picture.

**Comment by vbjay** [comment] 2018-12-31 17:41
No stash from the selected commit
![image](https://user-images.githubusercontent.com/3629489/50565035-acadba00-0cf8-11e9-82aa-6fa9ec4fd33b.png)


When I turn on reflogs, it shows on top.  

![image](https://user-images.githubusercontent.com/3629489/50565052-f8f8fa00-0cf8-11e9-8b97-81082c42ae3f.png)


I did create the stashes today.  So I would expect the stashes to act like another branch and be directly linked to the commit.  So I would expect the Update nuget.exe 4.71 -> 4.9.2 commit to have the stash right above it.

**Comment by vbjay** [comment] 2018-12-31 17:54
My view menu.

![image](https://user-images.githubusercontent.com/3629489/50565270-247ce400-0cfb-11e9-9455-c9e66a3ec448.png)

**Comment by vbjay** [comment] 2018-12-31 19:30
Show reflog shouldn't be a part of this equation.  If I checkout commit A and alter files and then stash them, the stash should be right above Commit A in the grid.  If I do so again on Commit A, I should have 2 stashes linked to A.  

Let's say I created commit A 2 weeks ago.  When I create the stash on A.  The stash should not be on top of all other commits and instead should be linked to A just like a branch is.

**Comment by gerhardol** [comment] 2022-07-29 20:06
Closing this as a duplicate of #5371, to handle this in one issue

(This also includes some more discussion of ordering of stashes).

**Closed by gerhardol** 2022-07-29 20:06 UTC
Labels: type: feature request, area: user experience

**Comment by drewnoakes** [comment] 2022-08-01 01:48
@gerhardol the idea behind this issue is to allow interaction directly with stashes in the revision grid. Actually I'd like the same kind of logic for branches and tags. Prior art for this is gitk, for example, which lets you interact directly with the rectangular markers for branches and tags, with context menu commands already scoped for operations such as check out / delete / etc.

**Comment by gerhardol** [comment] 2022-08-01 09:50
> the idea behind this issue is to allow interaction directly with stashes in the revision grid. 

Clear to me, but the stashes must be added to the grid in a way they can be identified as stashes. The discussions were overlapping too.

> Actually I'd like the same kind of logic for branches and tags. Prior art for this is gitk, for example, which lets you interact directly with the rectangular markers for branches and tags, with context menu commands already scoped for operations such as check out / delete / etc.

A separate issue
