### ISSUE TITLE
Remember untracked files option in commit dialog

### ISSUE THREAD

**Issue by sapien2** [gitextensions/gitextensions#1640] opened 2013-02-21 06:46 UTC
Commit dialog always shows up untracked files even if I have turned this off during last invocation of this dialog. Or maybe there should be an option to not to show untracked files by default.

**Comment by mcoolidge** [comment] 2015-03-19 17:16
+1

**Comment by RussKie** [comment] 2017-12-14 21:34
Duplicate of #1872

**Closed by RussKie** 2017-12-14 21:34 UTC
Labels: feature request
