### ISSUE TITLE
Memorize last pull mode option in pull dialog

### ISSUE THREAD

**Issue by osevoso** [gitextensions/gitextensions#6194] opened 2019-01-31 11:13 UTC
**Feature request**

Add programm option for memorize last options state in pull-dialog. As least for pull-modes.

In main window, starting with v3.00.00, pull-actions may to run immediatly, without possibility to customize it, but it is not covering all needs for usage in all cases. 

Setting default behavior for Pull-button (in main window) for opening pull-dialog does correcting the situation, but always impose "fetch mode" for pulling.

I mean that "checking and running" instead of "checking, correct and running" are more usability, when immediate runs of predefined pull-mode's is not suitable.

- Git Extensions 3.0.1.4933
- Build a269358b22a5dc1ea36928bb87f9e535de76a058
- Git 2.20.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2019-01-31 11:48
I think this is duplicate of #6144
Please have a look at #6153 and #6155.

**Comment by osevoso** [comment] 2019-02-01 01:37
Yes, this is close to a duplicate, the pull mechanics became very uncomfortable and not intuitive in 3.x compare to 2.51 Workaround, which i found for me - always to open pull-dialog. 
Therefore, the proposal - without changing what is now, add a global software option to remember the last pull-action in this dialog to restore the expected behavior close to was at 2.51.

**Comment by RussKie** [comment] 2019-02-01 11:38
Would you like to try this build https://ci.appveyor.com/api/buildjobs/iona492quavhndbg/artifacts/GitExtensions-Portable-3.0.2.5120.zip and see if it is fixed

**Comment by osevoso** [comment] 2019-02-04 01:36
This build have a other extreme - no one pull-mode option are pre-selected when pull-dialog is openining every time.

**Comment by RussKie** [comment] 2019-02-04 09:01
Please elaborate and provide more info.

I tested a brand new installation (v3.0.2.5120) on a brand new VM, invoked "Pull" from a Windows Explorer context menu:
![image](https://user-images.githubusercontent.com/4403806/52198643-9971a980-28b7-11e9-8e00-c4d7fbed8763.png)

**Comment by vbjay** [comment] 2019-02-04 11:12
No. It uses the set default in the pull menu in toolbar.

**Comment by osevoso** [comment] 2019-02-05 04:54
> No. It uses the set default in the pull menu in toolbar.

vbjay, you are right. And it too complex for use.

Why not separate opening of pull dialog by corresponding button from influence of other buttons?
The next behavior may be well: 

- Main pull-button on toolbar do action depending from user-selected default action;
- "Open pull dialog ... " button do opening pull dialog with restored pull-option which selected sometime before. 
- Other pull-buttons, with predefined behavior, do it action immediate (as it is now).

**Comment by vbjay** [comment] 2019-02-05 10:40
Please do explain how clicking a menu is too complex. We are trying to be
consistent. So I seriously doubt we will be changing this behaviour. I set
my default to fetch all. If I want to do a pull merge I either right click
a remote branch in left panel or ooen pull dialog and change options.

**Comment by vbjay** [comment] 2019-02-05 10:46
It does say pull**...**. Which means a dialog will open with options. Also if you are going to default it to a pull option, notice the git config options

- pull.rebase
- branch.<name>.rebase

**Comment by vbjay** [comment] 2019-02-05 10:53
I for one, say we just use the default menu option throughout. It is declarative by the user and users should be able to read the dialog and change if other action is desired.

**Comment by RussKie** [comment] 2019-02-05 11:00
Then it would be good to align the visuals across the board, i.e. show the
default pull behaviour icon in the WE context menu.
As well as fix the tooltip for the W Jumplist.

I had a brief look at the shell extensions and my C++ isn't good to make
the change.

**Comment by vbjay** [comment] 2019-02-05 11:07
https://docs.microsoft.com/en-us/windows/desktop/uxguide/cmd-menus.

**Comment by vbjay** [comment] 2019-02-05 11:13
I think the pull icon is fine. It is signifying a pull action with a dialog will open. Pull is just a fetch +merge or rebase. They declare the default pull action is rebase then rebase will be selected. They declare merge then merge.

**Comment by osevoso** [comment] 2019-02-06 04:08
@RussKie, @vbjay 
> > * Main pull-button on toolbar do action depending from user-selected default action;
> 
> Are you proposing that only the toolbar button obeys the user-configured pull behaviour?
> And other buttons do something different?
> 
> > * "Open pull dialog ... " button do opening pull dialog with restored pull-option which selected sometime before.
> 
> The dialog does not remember a user selection other than the configured default, if one is available.

Exactly. I see the meaning in the other buttons just so for not to open the dialog, to speed up working. If I want directly "rebase" or "merge" or "fetch", sure, I will use the "other buttons" - opening dropdown menu it is not a problem. And, since it not a problem, exactly I do not want for me that one from it buttons do affect to main toolbar button as "default" button. That I mean as "too complex". But since it is fact, I accept it, and to avoid it - this request for memorize pulling options in pull-dialog (sure, this global memorize option must be disabled as default - and end-users, who uses existing mechanic, will not confused with it). 

"Pull-button" on main window toolbar preffered for me for opening pull-dialog. To immediate run pull-action quite enough buttons in dropdown menu. It just my option, and I not expand it for all. From here, I would like to can using pull-dialog independently from default modes, suchwise to pull-dialog may be another one "default mode".

**Comment by RussKie** [comment] 2019-02-10 13:11
> Exactly. I see the meaning in the other buttons just so for not to open the dialog, to speed up working. If I want directly "rebase" or "merge" or "fetch", sure, I will use the "other buttons" - opening dropdown menu it is not a problem. And, since it not a problem, exactly I do not want for me that one from it buttons do affect to main toolbar button as "default" button. That I mean as "too complex".

The pull button's default behaviour is configurable, the default behaviour is "pull-merge":
![image](https://user-images.githubusercontent.com/4403806/52534017-068daf00-2d90-11e9-9f3d-af7bf1e4e251.png)

For instance, I always fetch I don't want open the pull dialog nor go through the dropdown every time I wish to execute the command.

The pull dialog is user-configuration aware, and if a user has configured a default, the dialog honours the user's preferences.

**Comment by RussKie** [comment] 2019-02-10 13:16
The original issue is a duplicate of #6144 and will be resolved in 3.0.2

**Closed by RussKie** 2019-02-10 13:16 UTC
Labels: status: more info requested

**Comment by yulObraz** [comment] 2019-04-03 13:57
What a strange place to choose defaults for context menu in Windows Explorer!  I had searched settings several times. I could understand if it was an option in the text menu. But it is a tiny arrow in icon menu without text header! I'l never found it without the picture in the issue.

**Comment by RussKie** [comment] 2019-04-06 05:57
Agree, the usability aspect for setting the default is not particular great.


> I could understand if it was an option in the text menu.

How would you present it?
