### ISSUE TITLE
"Stage and commit all unstaged files" may not stage all unstaged files

### ISSUE THREAD

**Issue by manuelspezzani** [gitextensions/gitextensions#8596] opened 2020-11-04 12:27 UTC
## Current behaviour

When no files are staged, a "There are no files staged for this commit. Stage and commit all unstaged files?" dialog is opened.
If the user select "yes", only the files matching the currently specified filters are actually staged.

## Expected behaviour

All files are staged, or the message is changed to better describe what is about to happen.
Personally I would prefer the first option. 

## Steps to reproduce

- Start from a repo in a "clean state" (aka no pending changes and no files staged)
- Edit two files (let's say "foo.txt" and "bar.txt") and open the commit dialog
- type "foo" in the filter textbox, on the top left corner of the commit dialog: the list of changes now shows only "foo.txt"
- enter a commit message and click on the commit button (make sure no files has been staged)
- the "There are no staged changes" dialog is shown, answer "yes"

A new commit is created containing only the changes to "foo.txt, while "bar.txt" has not been staged/committed.

## Did this work in previous version of GitExtensions

I didn't tried.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3661.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2020-11-04 23:03
I suggest changing the text:
_There are no files staged for this commit. Stage and commit all (filtered) unstaged files?_

**Comment by RussKie** [comment] 2020-11-05 02:48
May be just stage all files?

**Comment by keco2** [comment] 2021-01-06 22:17
Hi. I've analyzed this and it seems to me that the behaviour might be quasi by design (as the method is called _StageAllAccordingToFilter_ so it was the intention to stage only filtered files).

So there are 2 texts misleading:
- the **ToolTipText** on StageAll button ("Stage All" instead of e.g. "Stage Filtered" ... but then the "Filtered" would be improper if the filter was not active)
- the **MessageBox** text at a Commit ("There are no files staged for this commit. Stage and commit all unstaged files?" instead of ".... Stage and commit all (filtered) unstaged files?" -- but again, in that case the "(filtered)" would be kind of improper if the filter was not active)


My suggestion: fix both misleading texts and display either "All" or "Filtered" words based on the filter:
- if the Filter is empty, use the "All" word
- otherwise use the "Filtered" word


I've prepared this accordingly:
- **ToolTipText** on StageAll button --> https://github.com/keco2/gitextensions/commit/4efc5e1eafe033691125daa708d51d5273346b5c
- **MessageBox** at Commit --> https://github.com/keco2/gitextensions/commit/1dd5397592bb58d2c550994ddd351dbd841fda0d

If that's not ok for you, I can update the fix based on the final decision. Thx!

**Comment by pmiossec** [comment] 2021-01-06 23:57
It seems good for me so doing a pull request would be a great idea to continue the discussion and be able to do the review...

Updating the icons would have been great also (by having one displaying a small funnel --the best-- or changing the color) but I understand that it could be difficult to design ones...

**Comment by keco2** [comment] 2021-01-07 17:56
Thanks @pmiossec ! The idea with the icon is not bad - I have included that change too and created the PR.

**Comment by keco2** [comment] 2021-01-19 13:09
I'm not sure what is the procedure (who and when can close an issue).  I just want to say: this one is quasi resolved.

**Comment by keco2** [comment] 2021-01-19 13:14
I'm not sure what is the procedure (who and when can close an issue). I just want to say: this one here is quasi resolved.

Should I update the screenshots here with the final version from the PR or it's better to keep it as is? Or maybe just remove the screenshots from here?

**Comment by gerhardol** [comment] 2021-01-19 14:55
Normally, issues are closed automatically when the PR is merged if the word "Resolves #8596" had appeared in the PR
Closing this manually now
Thanks

**Closed by gerhardol** 2021-01-19 14:55 UTC
Labels: :nerd_face: good first issue, up-for-grabs

**Comment by vbjay** [comment] 2021-01-19 15:14
*https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
<https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue>*

**Comment by keco2** [comment] 2021-01-19 19:05
Oops! Sorry and thanks!
