### ISSUE TITLE
GitExtension doesn't start at all

### ISSUE THREAD

**Issue by sgallou** [gitextensions/gitextensions#10370] opened 2022-11-09 19:13 UTC
### Environment

- GitExtensions version: GitExtensions-4.0.0-cba315df5 and GitExtensions-4.0.0.15291-beta-8b80e54f1
- GIT version: 2.33.0.windows.2
- OS version: Windows 10 Professionnel N 21H1 (64 bits) build 19043.2130
- .NET version: 4.8

### Issue description

I just installed the 4.x version (need to manually uninstall previous installed 3.x version), but I'm unable to start git extension.
I tried GitExtensions-4.0.0-cba315df5 and GitExtensions-4.0.0.15291-beta-8b80e54f1 versions.
Nothing happens at all when clicking on GitExtensions.exe. No error message, no log.
I also tried to start from command line, and no more message.

### Steps to reproduce

Just install gitextension from installer, and try to start GitExtension.

### Did this work in previous version of GitExtensions?

Yes, version 3.4 worked well.

### Diagnostics

I don't know how to send you more information. I found no log file, and no message in console (I'm under Windows 10).

**Comment by sgallou** [comment] 2022-11-09 21:52
I just reinstall v3.5 (can not live without GitExtension !), and works well.

**Comment by mstv** [comment] 2022-11-09 22:16
Perhaps duplicate of #10351 or similar to #10337 and others.
Have you installed a recent .NET _desktop_ runtime 6.0.9 or later?
https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Closed** 2022-11-11 09:05 UTC
