### ISSUE TITLE
Failed to publish gerrit change by the button.

### ISSUE THREAD

**Issue by ldd200888** [gitextensions/gitextensions#7802] opened 2020-02-24 07:43 UTC
Failed to publish gerrit change by the button.

![image](https://user-images.githubusercontent.com/5476907/75134830-714f2580-571a-11ea-9991-c8625a1aafe3.png)

## Current behaviour

1. change something
2. commit it.
3. publish gerrit change.
4. Crush.

## Expected behaviour

Success.

## Steps to reproduce

1. change something
2. commit it.
3. publish gerrit change.
4. Crush.

## Error Details
```
System.ArgumentException: 版本字符串部分太短或太长。
   在 System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   在 System.Version.TryParseVersion(String version, VersionResult& result)
   在 System.Version.Parse(String input)
   在 Gerrit.FormGerritBase.OnLoad(EventArgs e)
   在 Gerrit.FormGerritPublish.OnLoad(EventArgs e)
   在 System.Windows.Forms.Form.OnCreateControl()
   在 System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   在 System.Windows.Forms.Control.CreateControl()
   在 System.Windows.Forms.Control.WmShowWindow(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.Form.WmShowWindow(Message& m)
   在 ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0
- DPI 96dpi (no scaling)

**Comment by ldd200888** [comment] 2020-02-24 07:43
why use C# System.Version.Parse to parse the version?
Now our branch is HD_8.0.0, not the stric format like: major.minor[.build[.revision]].

I think it is not fit to use it.

**Comment by mast-eu** [comment] 2020-02-25 22:48
Closing as duplicate of #7604 . The issue is probably already solved in the current development version, but not yet available in a release.

We are working towards moving the Gerrit plugin into an own repo: https://github.com/gitextensions/GitExtensions.GerritPlugin. As soon as this is completed, you can install a fixed version of the Gerrit plugin from there.

**Closed by mast-eu** 2020-02-25 22:48 UTC

**Comment by ldd200888** [comment] 2020-02-26 07:56
ok，thanks
