### ISSUE TITLE
Plugin "Delete obsolete branches" - handle not fully merged branches

### ISSUE THREAD

**Issue by fairking** [gitextensions/gitextensions#3871] opened 2017-07-25 08:40 UTC
v. 2.50.01

When I try to remove obsolete branches it does nothing. It was working with previous versions.

**Edited:**
The plugin does not remove branches that are not fully merged. These branches are listed by the `git branch --merged` command despite of they are not fully merged (merged to HEAD, but not merged to the remote tracking branch).

GitExt should have an option to delete also not fully merged branches. Not fully merged branches have to be deleted with `-D` option.

**Comment by jbialobr** [comment] 2017-08-04 07:01
Can you run the `git branch -d <branch name>` command replacing <branch name> with a branch name that was not deleted by the plugin? Does it delete the branch?

**Comment by denis-pujdak** [comment] 2017-08-08 09:42
Hi @jbialobr 

Sorry for the delay. Following screenshot shows how it looks like on my machine
![2017-08-08 2](https://user-images.githubusercontent.com/12826797/29066142-45aac55a-7c26-11e7-8925-60fc9944bbc1.png)

Thanks for your help.

**Comment by vbjay** [comment] 2017-08-08 11:34
Your problem isn't a problem. Your branch has not been merged into another
branch like master. That makes it not obsolete.

**Comment by denis-pujdak** [comment] 2017-08-08 11:54
But I checked the option "Include unmerged branches". Also all my branches I wanted to delete was merged on GitHub and removed. I don't see `origin` branches on Git Extensions but I still cannot remove them.

![2017-08-08 4](https://user-images.githubusercontent.com/12826797/29070819-bf3536fa-7c38-11e7-93b7-3070c5ed5782.png)

**Comment by jbialobr** [comment] 2017-08-08 11:59
@vbjay 
It is a real problem, I edited the original description with the problem description.

**Comment by vbjay** [comment] 2017-08-08 12:07
To see origin, you have to have a remote with that name.

**Comment by minuz** [comment] 2018-10-16 00:42
Hi All, any updates on this?

Just to justify my use case, over time I always end up with heaps of local branches I need to manually delete. 

A common scenario for me is that I often do small POCs that won't move forward and end up with unmerged branches when I forget to delete at the end of the tests I'm doing.

**Comment by denis-pujdak-adm-it** [comment] 2018-11-28 23:32
Hi. If anybody still has that problem I think I found the solution. Some of my branch names were containing coma or single quote. I copied the command from the git command log when I clicked Delete,
before it was like:
`branch -d master1 master2`
and I changed to
`branch -d 'master1', 'master2'`
it was abount 100 branches and some of them names were like `#BlaBla_Can'tSaveARecord_BlaBla`

**Comment by vbjay** [comment] 2018-11-28 23:39
Need to escape branch names that contains a '.

BranchName.replace("'",@"\'")

**Comment by drewnoakes** [comment] 2018-12-03 14:08
Is GE not quoting branch names when creating the command line arguments? This can be confirmed in the Git Command Log.

**Comment by LukeOwlclaw** [comment] 2020-02-13 10:09
If I understood this discussion correctly: When checking option "Include unmerged branches" `git branch -d <branch name>` should become `git branch -D <branch name>`. Correct?

Then there is only a single change necessary in `DeleteUnusedBranchesForm.cs` line 205:

    -d,

must become

    includeUnmergedBranches.Checked ? "-D" : "-d",

Wouldn't it be nice if this issue could be closed? Could anyone with a CLA send an according PR?

Thanks!

**Comment by pmiossec** [comment] 2020-02-13 13:49
@LukeOwlclaw 

>Wouldn't it be nice if this issue could be closed?

If you want to see it fixed, now that you have the fix, do the PR.

> Could anyone with a CLA send an according PR?

I'm not sure that writing one line of text in a text file ([contributors.txt](https://github.com/gitextensions/gitextensions/blob/master/contributors.txt)) is something that is too hard for you and that prevent you to do the PR...

**Comment by lechu445** [comment] 2023-05-26 08:04
@pmiossec revealing name and email address exposes contributors to phishing attacks. Both name & email address are personal data and are under GDPR protection. 
That's the reason why adding a line in contributors.txt may prevent people doing the PR.

**Comment by RussKie** [comment] 2023-05-31 00:34
> @pmiossec revealing name and email address exposes contributors to phishing attacks. Both name & email address are personal data and are under GDPR protection. That's the reason why adding a line in contributors.txt may prevent people doing the PR.

True, at the same time the privacy in internet is a myth. Sadly.
Participation in any kind of public activity is, by definition, is public. So, if a someone wishes to participate in an OSS project must be prepared to present his/her identity.

**Comment by RussKie** [comment] 2023-05-31 00:35
Closing this issue as stale since it didn't attract any interest in 6 years.

**Closed by RussKie** 2023-05-31 00:35 UTC
Labels: area: plugins

**Comment by lechu445** [comment] 2023-05-31 18:47
> True, at the same time the privacy in internet is a myth. Sadly.
Participation in any kind of public activity is, by definition, is public. So, if a someone wishes to participate in an OSS project must be prepared to present his/her identity.

Many open source projects does not require putting down name and email in some contributors file. As far as I understand the current license, GPL v3 does not require to use such document. It's official page only suggests to use something similar in case of employees or students. https://www.gnu.org/licenses/gpl-howto.en.html#copyright-disclaimer
 
I really like how simple it's done in https://github.com/JamesNK/Newtonsoft.Json/blob/master/CONTRIBUTING.md#-contributor-license-agreement

**Comment by georg138** [comment] 2024-09-26 08:11
I just stumbled upon this issue when trying to delete unmerged branches so I decided to create the PR.

**Comment by georg138** [comment] 2024-09-27 03:51
I just tested the current behavior and it deletes branches with single quote without any issues, e.g. 
![image](https://github.com/user-attachments/assets/6949234d-ff7e-4e85-9daf-7b1d1f846b1a)
Escaping is only required when running from a shell. Its the shell itself which interprets some of the characters and provides the escaping (which may be different for different shells).
bash:
![image](https://github.com/user-attachments/assets/f5b81212-f889-457f-a44d-ca8ecbd58f78)
![image](https://github.com/user-attachments/assets/ff60f3db-5ab8-446e-ab88-ee0a85cb2b90)
powershell:
![image](https://github.com/user-attachments/assets/d8fe2fce-dec4-4bf5-94fa-2364c38ac2f2)

Quoting the branch name does not help when using a shell.
