### ISSUE TITLE
Unable to restore window after clearing to desktop

### ISSUE THREAD

**Issue by simonantonio** [gitextensions/gitextensions#2797] opened 2015-05-08 02:33 UTC
--- GitExtensions2.48.03, Git 1.8.5.2.msysgit.0, Microsoft Windows NT 6.3.9600.0

To reproduce.
Open 2 different repositories in 2 instances of Git Ext. 
Open another application. Clear to desktop (Win-D) or Lower Right Corner
Try and get your original Git Ext window back. (cannot restore via alt tab or clicking task bar)

I've not got any other machines to test it on.

See here for recording of issue
http://youtu.be/89_y-hZDbes
excuse the terrible quality video.

**Comment by Radrik5** [comment] 2015-05-08 09:39
Probably duplicate of #2570 but it adds working steps to reproduce. On my computer with Windows 7 only the first attempt to restore Git Extensions doesn't work. The second click to the same instance or click to the second instance restores Git Extensions successfully.

**Closed** 2016-01-06 20:46 UTC
Labels: bug
