### ISSUE TITLE
[NBug] SSH key file could not be found

### ISSUE THREAD

**Issue by MarkPaxton** [gitextensions/gitextensions#10565] opened 2022-12-21 14:11 UTC
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22623.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

```
GitUI.NBugReports.UserExternalOperationException: SSH key file could not be found
 ---> System.IO.FileNotFoundException: SSH key file could not be found
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.PuttyHelpers.ThrowIfFileNotFound(String filePath, String errorMessage, String heading)
   at GitUI.Infrastructure.PuttyHelpers.StartPageantIfConfigured(Func`1 sshKeyFileLoader)
   at GitUI.CommandsDialogs.FormPush.StartPageant(String remote)
   at GitUI.CommandsDialogs.FormPush.PushChanges(IWin32Window owner)
   at GitUI.CommandsDialogs.FormPush.PushClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Ssh key is loaded with pagent. Trying to push to a branch that worked in previous version

Works is ssh key is manually specified in remotes config.

### Steps to reproduce

Create a remote using ssh. load public key via pagent. Try to push to remote.

### Did this work in previous version of GitExtensions?

Worked in previous 4.0 release

**Comment by gerhardol** [comment] 2022-12-21 14:38
Duplicate of https://github.com/gitextensions/gitextensions/issues/10530
Please try the solution in https://github.com/gitextensions/gitextensions/pull/10545

**Closed by gerhardol** 2022-12-21 14:38 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
