### ISSUE TITLE
Malwarebytes marked 3 files as trojan droppers 

### ISSUE THREAD

**Issue by MikaelPorttila** [gitextensions/gitextensions#8145] opened 2020-05-26 05:38 UTC
## Current behaviour

Malwarebytes blocked the following files after I updated to the latest version:
- GITEXTENSIONS-3.4.0.9381-096B4D567.MSI
- GITEXTSSHASKPASS.EXE
- 89389C4.MSI

## Steps to reproduce
Install the latest version and run Malwarebytes scan.

## Screenshots

![image](https://user-images.githubusercontent.com/903468/82863718-29ab8600-9f23-11ea-805a-089245d8e091.png)

## Did this work in previous version of GitExtensions

No warning in previous version, not sure what version I used before (Installed the previous version during November 2019)

## Environment

- GitExtensions version: 3.4
- GIT version: 2.26.2
- OS version: Windows 10 LTSC
- .NET version: 8.x

**Comment by RussKie** [comment] 2020-06-01 13:06
There must be some changes in VC++ packages and/or Malwarebytes sample base. Either way there's nothing we can do.

**Comment by RussKie** [comment] 2020-06-01 13:06
Duplicate of #8109

**Closed by RussKie** 2020-06-01 13:06 UTC
