### ISSUE TITLE
Wrong commit is selected when when rebasing or changing branches

### ISSUE THREAD

**Issue by billhannah** [gitextensions/gitextensions#7386] opened 2019-11-05 21:36 UTC
# Current behavior
After performing an action where the commit history of the current head commit changes (such as rebasing or pulling), after the new graph is loaded,the previous head commit is the selected commit. Once this happens, after all actions that causes a reload of the commit graph (switching branches, rebasing, pulling, fetching, etc), this `stuck` commit will be the selected commit

# Expected behavior
After an action that changes the current head commit, that commit will be the selected commit after the commit graph reloads

# Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.21.0.windows.1 (recommended: 2.22.0 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by billhannah** [comment] 2019-11-05 21:38
*NOTE:* this has been happening for quite a while (since early this year), it's not a new bug. Uninstalling and reinstalling does not resolve the issue on my machine.

**Comment by gerhardol** [comment] 2019-11-05 22:33
I believe this is an intentional change: GE tries to keep the selected _commit_ not the selected _HEAD_.
Previously, the selection was changed at most commands refreshing the grid.

**Comment by RussKie** [comment] 2019-11-05 22:58
I observed the same, and I think it is a bug.
Because the original head is no longer available GE is selecting an
arbitrary commit. I think we should be selecting the HEAD in this instance

**Comment by mstv** [comment] 2019-11-05 23:03
Yes, this is a bug. Duplicate of #6663.

**Closed by mstv** 2019-11-05 23:03 UTC
