### ISSUE TITLE
[NBug] Input string was not in a correct format.

### ISSUE THREAD

**Issue by lyricaljourney** [gitextensions/gitextensions#8747] opened 2021-01-12 01:15 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at GitUI.Editor.Diff.DiffLineNumAnalyzer.Analyze(String diffContent)
   at GitUI.Editor.Diff.DiffViewerLineNumberControl.DisplayLineNumFor(String diff)
   at GitUI.Editor.FileViewerInternal.SetText(String text, Action openWithDifftool, Boolean isDiff)
   at GitUI.Editor.FileViewer.<>c__DisplayClass103_0.<ViewPatchAsync>b__0()
   at GitUI.Editor.FileViewer.ShowOrDeferAsync(Int64 contentLength, Func`1 showFunc)
   at GitUI.Editor.FileViewer.<ViewPatchAsync>d__103.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.RevisionDiffControl.<ShowSelectedFileDiffAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.RevisionDiffControl.<<DiffFiles_SelectedIndexChanged>b__36_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Clicking on files in a commit to see the diff.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2021-01-12 09:03
Were you using UTF-7?

**Comment by lyricaljourney** [comment] 2021-01-12 19:50
The crash is definitely associate with trying to diff the history of a particular file. It may even be just that particular diff. Beyond Compare can display the diff okay.

As to whether the the file is in UTF-7, it is difficult to tell. The file does not contain any kind of header or BOM. Notepad++ and Android Studio both report the file type as UTF-8. We are large organisation, and it is difficult to know for certain what crazy editor someone may have used to touch the file.

**Comment by gerhardol** [comment] 2021-01-12 22:53
Duplicate of #7146

If this is caused in the same as #8634, it was fixed in #8661 
UTF-7 is either the default in GE or was set in the session

![image](https://user-images.githubusercontent.com/6248932/104384180-51427380-5531-11eb-9064-f4d0527f8306.png)

**Comment by lyricaljourney** [comment] 2021-01-13 00:15
"Files content encoding" was not set in GE. I have set it to "Uncode (UTF-8)" and checked the same file in the same commit and the crash is still occurring.

**Comment by RussKie** [comment] 2021-01-13 11:02
Can you please provide a simple repro?

**Comment by RussKie** [comment] 2021-01-20 06:47
Holler when you have a repro, and we'll reopen this.

**Closed by RussKie** 2021-01-20 06:47 UTC
