### ISSUE TITLE
[NBug] Could not load file or assembly 'System.DirectoryServices, ...

### ISSUE THREAD

**Issue by tomichp** [gitextensions/gitextensions#10804] opened 2023-03-15 22:03 UTC
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.14
- DPI 144dpi (150% scaling)

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.DirectoryServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.DirectoryServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at GitUI.CommandsDialogs.FormSettings.InitializeComponent()
   at GitUI.CommandsDialogs.FormSettings..ctor(GitUICommands commands, SettingsPageReference initialPage)
   at GitUI.CommandsDialogs.FormSettings.ShowSettingsDialog(GitUICommands uiCommands, IWin32Window owner, SettingsPageReference initialPage)
   at GitUI.GitUICommands.<>c__DisplayClass116_0.<StartSettingsDialog>g__Action|0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent)
   at GitUI.GitUICommands.StartSettingsDialog(IWin32Window owner, SettingsPageReference initialPage)
   at GitUI.GitUICommands.StartSettingsDialog(IGitPlugin gitPlugin)
   at GitExtensions.Plugins.GitHub3.GitHub3Plugin.Execute(GitUIEventArgs args)
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass70_0.<RegisterPlugins>b__2(Object <p0>, EventArgs <p1>)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Pushing to GitHub is failing.  Also trying to open the GitHub plugin [Plugins->GitHub] generates this error.

### Steps to reproduce

Attempting to push to GitHub generates this error.
Also trying to load the GitHub plugin generates this error [Plugins->GitHub].

### Did this work in previous version of GitExtensions?

This error spontaneously appeared.

**Comment by tomichp** [comment] 2023-03-15 22:24
Closing all GitExtensions and re-launching seems to resolve the error.

**Comment by gerhardol** [comment] 2023-03-15 22:34
Duplicate of https://github.com/gitextensions/gitextensions/issues/10368
Duplicate of https://github.com/gitextensions/gitextensions/issues/10624

This error seem to occur related to Windows and/or .NET updates and seem to be resolved by app or possible PC restarts.
Not sure if this can be detected, this has occurred a number of times.

Similar issues can occur if a portable installation is updated by overwriting the with new version.
You can copy the settings though from old to new.

**Closed** 2023-03-19 17:18 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
