### ISSUE TITLE
dark theme does not work

### ISSUE THREAD

**Issue by andsoft1** [gitextensions/gitextensions#10326] opened 2022-11-04 08:17 UTC
### Environment

- GitExtensions version: 4 (GitExtensions-4.0.0-cba315df5.msi)
- GIT version: 2.38.1
- OS version: Win 10
- .NET version:  .NET 6/ Framework 4.8

### Issue description

Dark theme o other does not work properly.
Some components are displayed as dark and others are light. So the view is mixed. 
Not possible to work.
Only default theme works fine, but is too light as for me.

### Steps to reproduce

switch to dark theme in colour settings

### Did this work in previous version of GitExtensions?

yes, in version GitExtensions-3.5.4.12724-65f01f399.msi was correct

**Comment by gerhardol** [comment] 2022-11-04 08:38
Duplicate of #10312

**Closed by gerhardol** 2022-11-04 08:38 UTC
Labels: :eyeglasses: status: needs review
