### ISSUE TITLE
[NBug] Unexpected artificial commit in Git command: 11111111111111...

### ISSUE THREAD

**Issue by simosilva** [gitextensions/gitextensions#9450] opened 2021-08-06 12:51 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Unexpected artificial commit in Git command: 1111111111111111111111111111111111111111
   at GitCommands.ArgumentBuilderExtensions.Add(ArgumentBuilder builder, ObjectId objectId)
   at GitCommands.GitModule.GetRevision(ObjectId objectId, Boolean shortFormat, Boolean loadRefs)
   at GitUI.UserControls.CommitDiff.SetRevision(ObjectId objectId, String fileToSelect)
   at GitUI.HelperDialogs.FormCommitDiff..ctor(GitUICommands commands, ObjectId objectId)
   at GitUI.RevisionGridControl.<>c__DisplayClass181_0.<ViewSelectedRevisions>g__ProvideForm|1()
   at GitUI.GitUICommands.ShowModelessForm(IWin32Window owner, Boolean requiresValidWorkingDir, EventHandler`1 preEvent, EventHandler`1 postEvent, Func`1 provideForm)
   at GitUI.RevisionGridControl.ViewSelectedRevisions()
   at GitUI.RevisionGridControl.OnGridViewDoubleClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseDoubleClick(MouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseDoubleClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
fyi, came out of nowhere doing other stuff I cannot tell how to reproduce

## Environment
- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment] 2021-08-06 13:17
Duplicate of #9084 
Corrected in master, #9087

**Closed by gerhardol** 2021-08-06 13:17 UTC
Labels: potential-duplicate
