### ISSUE TITLE
[NBug] error: pathspec 'src/pages/guest/LoginPage.tsx' did not mat...

### ISSUE THREAD

**Issue by Krzaczek24** [gitextensions/gitextensions#10506] opened 2022-12-08 19:21 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: checkout aea00d0c3c1752e5623a26df9d8b5f982925dc1e -- "src/pages/guest/LoginPage.tsx"
Working directory: D:\Git\DFMS\DFMS.Frontend.TypeScriptReactWithMobx\

```
GitExtUtils.ExternalOperationException: error: pathspec 'src/pages/guest/LoginPage.tsx' did not match any file(s) known to git
 ---> System.Exception: error: pathspec 'src/pages/guest/LoginPage.tsx' did not match any file(s) known to git
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.RunCommandAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.RunBatchCommand(IExecutable executable, ICollection`1 batchArguments, Action`1 action, Byte[] input, Boolean createWindow)
   at GitCommands.GitModule.CheckoutFiles(IReadOnlyList`1 files, ObjectId revision, Boolean force)
   at GitUI.CommandsDialogs.RevisionDiffControl.ResetSelectedItemsTo(Boolean actsAsChild)
   at GitUI.CommandsDialogs.RevisionDiffControl.resetFileToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

I moved a file from one direction to another and made changes in that file.
Next, I tried to reset file content to previous state and get an exception, but I think Git Extensions have a problem because of different previous location of that file

### Steps to reproduce

Create a file with some content.
Commit that file.
Move a file to another location.
Make changes in that file.
Commit those changes.
Now try to reset that single file to previous commit. <- throwing an exception

### Did this work in previous version of GitExtensions?

Im not sure,
its not so common to reset single file to previous version when it was previously in different directory

**Comment by mstv** [comment] 2022-12-09 17:46
Duplicate of #10468

**Closed by mstv** 2022-12-09 17:46 UTC
Labels: :eyeglasses: status: needs review
