### ISSUE TITLE
z-index issue

### ISSUE THREAD

**Issue by Monody2010** [gitextensions/gitextensions#5551] opened 2018-10-11 06:33 UTC
**an UI bug**

**The main window will on the top of z-index after right click on touched files in commit window, and the pop up context menu shows in main window.**

**Environment:**

- GitExtensions version: 2.51.05
- GIT version: 2.19.1.windows.1
- OS version: Windows 7 Professional Service Pack 1 
- .NET version: 4.7.02558 461310

![image](https://user-images.githubusercontent.com/8831636/46784800-19e92900-cd62-11e8-865d-36aace3b5d4a.png)

**Comment by RussKie** [comment] 2018-10-11 07:16
Please disable conemu as described in https://github.com/gitextensions/gitextensions/issues/3570#issuecomment-284229149

Duplicate of #3570
Duplicate of #3593

**Comment by RussKie** [comment] 2018-10-11 07:17
Duplicate of #3570

**Comment by RussKie** [comment] 2018-10-11 07:17
Duplicate of #3593

**Closed by RussKie** 2018-10-11 07:16 UTC
