### ISSUE TITLE
[NBug] ConEmuCD was not loaded.

### ISSUE THREAD

**Issue by CarlSargunar** [gitextensions/gitextensions#6747] opened 2019-06-04 12:53 UTC
## Error Details
```
ConEmu.WinForms.GuiMacroExecutor+GuiMacroException: ConEmuCD was not loaded.
   at ConEmu.WinForms.GuiMacroExecutor.ExecuteInProcessAsync(Int32 nConEmuPid, String asMacro)
   at ConEmu.WinForms.ConEmuSession.ExecuteGuiMacroTextAsync(String macrotext)
   at ConEmu.WinForms.GuiMacroBuilder.ExecuteAsync()
   at ConEmu.WinForms.ConEmuSession.WriteOutputTextAsync(String text)
   at GitUI.FormStatus.Done(Boolean isSuccess)
   at GitUI.FormProcess.<>c__DisplayClass43_0.<OnExit>b__0()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

**Comment by CarlSargunar** [comment] 2019-06-04 12:54
2nd or 3rd instance of this happening for me

**Comment by pmiossec** [comment] 2019-06-04 13:07
>2nd or 3rd instance of this happening for me

Ok. So perhaps you could update the first message to explained us how you get this issue (The "Steps to reproduce" and "Steps to reproduce" parts that you didn't filled when submitting the original bug...).


Because, with just the name and the stacktrace of the error, we are not able to understand what exactly happened that triggered this error (because we don't have it our self) and, so, fix it....

**Comment by pmiossec** [comment] 2019-06-04 13:20
Maybe @Maximus5 has an idea from where the problem could come from?

**Comment by CarlSargunar** [comment] 2019-06-04 17:19
Steps to replicate would be difficult as you would need my repository, but essentially I did a commit and push step with a some large binary and text files as part of the commit (Approx 8Mb). The repo is a medium sized - approx 3 years old, about 2 gig in size. 3 Concurrent developers doing sort-of-git-flow style checkout and commit.

This has happened previously but I didn't take a note of the size of the files in the commit last time.

I'll try and capture more detail if it happens again, not sure what else I can send as all info is already captured. 

Thanks

**Comment by gerhardol** [comment] 2019-06-05 23:09
Duplicate of #6675 

To do something with this issue, we need to know how to reproduce. Until then we will close the issue, linking to the first occurrence.

The only "fix" right now is to disable ConEmu or at least disable bydefault and throw pops to the user that enabling ConEmu may cause issues.

**Closed by gerhardol** 2019-06-05 23:09 UTC
Labels: potential-duplicate
