### ISSUE TITLE
Crash when selecting TMerge for DiffTool/MergeTool

### ISSUE THREAD

**Issue by kiwidoggie** [gitextensions/gitextensions#7454] opened 2019-11-26 15:46 UTC
## Current behaviour

When selecting TMerge from the options menu for Diff or Merge tool, GitExtensions crashes.

## Expected behaviour

It works/does not crash

## Steps to reproduce

Just open up the options and select the Tmerge/TortoiseMerge option and it crashes.

## Screenshots

![image](https://user-images.githubusercontent.com/9152262/69648563-6e13a300-1020-11ea-9e73-96461dc17b12.png)

## Did this work in previous version of GitExtensions

N/A (it worked before, but this is a fresh install with all latest software so I don't remember the last version it worked with)

## Environment

- GitExtensions version: Git Extensions [3.2.1.6628]
- GIT version: git version 2.23.0.windows.1
- OS version: Windows 10 1909 18363.476
- .NET version: Latest (2.0-4.8 + Core 3.x)

## Diagnostics

N/A

**Comment by gerhardol** [comment] 2019-11-26 16:10
Fixed in master
(if you hade copied the NBug info I would have added the reference to the correction too)

**Closed by gerhardol** 2019-11-26 16:10 UTC

**Comment by gerhardol** [comment] 2019-11-26 20:50
duplicate of #7169
Corrected in #7172
