### ISSUE TITLE
[NBug] Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by GonenOneView** [gitextensions/gitextensions#9062] opened 2021-04-11 07:13 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.IO.StreamReader.ReadToEnd()
   at GitCommands.EncodingHelper.DecodeString(Byte[] output, Byte[] error, Encoding& encoding)
   at GitCommands.ExecutableExtensions.<GetOutputAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.GetSingleDiff(ObjectId firstId, ObjectId secondId, String fileName, String oldFileName, String extraDiffArguments, Encoding encoding, Boolean cacheResult, Boolean isTracked)
   at GitUI.GitUIExtensions.GetItemPatch(GitModule module, GitItemStatus file, ObjectId firstId, ObjectId secondId, String diffArgs, Encoding encoding)
   at GitUI.GitUIExtensions.<ViewChangesAsync>g__GetSelectedPatch|1_1(FileViewer fileViewer, ObjectId firstId, ObjectId selectedId, GitItemStatus file)
   at GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, String defaultText, Action openWithDiffTool)
   at GitUI.CommandsDialogs.RevisionDiffControl.<ShowSelectedFileDiffAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.RevisionDiffControl.<<DiffFiles_SelectedIndexChanged>b__36_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Crashed again, I have 128GB of memory, opened the project, and tried to look at the diff of a huge (3GB) push, just selected the "diff" tab when the push was selected and it crashed.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.2.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2021-04-11 09:50
A repo where this can be reproduced?

**Comment by Gonenb** [comment] 2021-04-11 10:09
> A repo where this can be reproduced?

Sorry, work repo, can't expose it

**Comment by RussKie** [comment] 2021-04-11 11:20
>  ...look at the diff of a huge (3GB) push

Is that a single file?

**Comment by Gonenb** [comment] 2021-04-11 11:41
The first file, that is auto selected when I choose the diff tab, is 330mb

**Comment by EbenZhang** [comment] 2021-04-13 01:57
Git is not efficient at managing large files. You may want to move the large files out of source control or use git-lfs  https://git-lfs.github.com/ to store it at some other place.

**Comment by Gonenb** [comment] 2021-04-13 07:25
We are using git-lfs. the solutions seems to be to compile git-extentions in 64bit

**Comment by RussKie** [comment] 2021-04-27 12:53
Duplicate of #9061

**Closed by RussKie** 2021-04-27 12:53 UTC
