### ISSUE TITLE
[NBug] Indeks był spoza zakresu. Musi mieć wartość nieujemną i mni...

### ISSUE THREAD

**Issue by nowackib** [gitextensions/gitextensions#9051] opened 2021-04-05 00:42 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentOutOfRangeException: Index out of range. Must be greater than 0 and smaller than collection size.
Parameter name: index
   in System.Collections.ArrayList.get_Item(Int32 index)
   in System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
   in System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
   in GitUI.RevisionGridControl.OnGridViewCellMouseDown(Object sender, DataGridViewCellMouseEventArgs e)
   in System.Windows.Forms.DataGridView.OnCellMouseDown(DataGridViewCellMouseEventArgs e)
   in System.Windows.Forms.DataGridView.OnMouseDown(MouseEventArgs e)
   in GitUI.UserControls.RevisionGrid.RevisionDataGridView.OnMouseDown(MouseEventArgs e)
   in System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.DataGridView.WndProc(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
i just clicked on some random commits after checking history of some very old commit. Have been switching between Diff and Commit views in there.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2021-04-06 22:24
Duplicate of #7374
Corrected in #8534, please try the 3.5 RC1
(There was a correction for #7374 in #7921 that is in 3.4)

**Closed** 2021-04-21 00:04 UTC
Labels: :beetle: type: bug, :mailbox_with_no_mail: needs: author feedback, :zzz: status: no recent activity
