### ISSUE TITLE
Text filter: sort search results by date

### ISSUE THREAD

**Issue by igroglaz** [gitextensions/gitextensions#10074] opened 2022-07-14 11:08 UTC
### Feature description

Not sure is current behaviour a bug or a "feature".. But anyway - it will be great to be able to sort searching results by the date, with recents on top.. Eg atm we have:
![Untitled-1](https://user-images.githubusercontent.com/39904162/178968934-856754b4-56f8-4e18-8cc7-d6785e026679.png)

On the screenshot above - fresh commits presented on top and at bottom.. which makes very hard to understand whats going on...

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.36.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4515.0
- DPI 144dpi (150% scaling)

**Comment by igroglaz** [comment] 2022-07-17 10:01
Thanks.. Considering 1st suggestion: I've already got such setting, but it doesn't help:
![image](https://user-images.githubusercontent.com/39904162/179393191-97e86441-b29e-4fe9-9ff1-be72ba7ad7b1.png)

Not sure what do you meant - to have 'sort commits by author date' or not.. just in case - I've turned it on, it didn't help either:

![image](https://user-images.githubusercontent.com/39904162/179393230-1effc128-1536-4303-8137-c4f71616f8b5.png)
(as you can see there is '2 days ago' commit selected) which is in wrong order.

**Comment by pmiossec** [comment] 2022-07-17 11:18
Can you post the same 2 screenshots but when you uncheck 'Show author date' that will display the committer date (which is the real date of creation of the commit) and that I imagine could have an impact on sorting...

**Comment by mstv** [comment] 2022-07-17 16:53
> Considering your second suggestion ('In master, also topo order') - failed to find it in the UI

`master` means (builds of) the current development branch 

---

If you have rebased or cherry-picked, the commits have got different author and commit dates.
Git's default sort order is more or less "by commit date". In order to get this, turn off both `Sort commit by author date` and `Arrange commits by topo order`.

![grafik](https://user-images.githubusercontent.com/36601201/179414551-6dc68cbe-74e3-42f4-b7e4-8d3d547090d1.png)

---

Is the displayed order different from the one in the Git output (refer to the Git Command Log, hit `F12`):

![grafik](https://user-images.githubusercontent.com/36601201/179416218-b12e0c1a-2303-4c70-bebe-f44b7e53ee03.png)

**Comment by igroglaz** [comment] 2022-07-18 10:15
Folk, thanks for your help.

The thing is that I have proper sorting for 'master':
![image](https://user-images.githubusercontent.com/39904162/179486838-94354be9-b9be-466f-8fe1-d32f8cbc4f3f.png)

and 'master' got such settings:
![image](https://user-images.githubusercontent.com/39904162/179486899-4cbc0fc1-5efa-416b-89b4-d96194067c32.png)

but I have wrong sorting when I search stuff, eg when I search 'score' there:
![image](https://user-images.githubusercontent.com/39904162/179487292-4c3de88f-52ff-4a83-a37d-d7b604177fa1.png)

My repo when I do the search: https://github.com/igroglaz/Tangaria

----------


@pmiossec:
> Can you post the same 2 screenshots but when you uncheck 'Show author date' that will display the committer date (which is the real date of creation of the commit) and that I imagine could have an impact on sorting?

![image](https://user-images.githubusercontent.com/39904162/179488022-cc2ddc45-a678-48e2-b40d-b00b9bdd3d6f.png)

and

![image](https://user-images.githubusercontent.com/39904162/179488198-48de06e5-d461-48e5-992f-01ac2c5dcc8d.png)

-----------

@mstv 
> > Considering your second suggestion ('In master, also topo order') - failed to find it in the UI
> If you have rebased or cherry-picked, the commits have got different author and commit dates. Git's default sort order is more or less "by commit date". In order to get this, turn off both `Sort commit by author date` and `Arrange commits by topo order`.
> 
> ![grafik](https://user-images.githubusercontent.com/36601201/179414551-6dc68cbe-74e3-42f4-b7e4-8d3d547090d1.png)
> 

Strange, I can't find 'topo order' option, though my main default branch called 'dev' and I clicked at the same spot as you did. My result:
![image](https://user-images.githubusercontent.com/39904162/179488665-af9eb7b6-cf5f-4132-8dcd-8444947a7302.png)


> Is the displayed order different from the one in the Git output (refer to the Git Command Log, hit `F12`):
> 
> ![grafik](https://user-images.githubusercontent.com/36601201/179416218-b12e0c1a-2303-4c70-bebe-f44b7e53ee03.png)

![image](https://user-images.githubusercontent.com/39904162/179490305-10da542d-f305-4f67-8767-c3fde4297760.png)
(this log in text mode: https://pastebin.com/0nQqCdKd )


----------------

Wow.. folks :) Seems it's different problem: seems Git Extensions `search` showing stuff which it shouldn't.. eg I'm trying to find 'score', but it shows in search commits that does not have 'score' in it...

**Comment by gerhardol** [comment] 2022-07-18 21:39
Search is fixed in master version of GE 
topo order is added in master version of GE
You can find a portable version on the first page (an alpha build is planned).

The sorting is done by Git:
https://git-scm.com/docs/git-log#_commit_ordering

(By the the way, the problem with search was that it had a compatibility mode for very old versions that did not work in all situdations. That is a reason to keep functionality as close as possible to Git, not any special implementation.)

**Comment by mstv** [comment] 2022-07-18 21:59
> `master` means (builds of) the current development branch

;-) ... of Git Extensions: https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts
It has new features but no dark mode support ATM.

---

Thank you for sharing the repo!!!

GE does display the commits in the order as Git list them.
`git -c log.showSignature=false log --max-count=100000 -z --all --boundary --not --glob=notes --not --grep=""score"" --regexp-ignore-case --parents`
As you mentioned, Git lists commits which do not contain the search string - **after** the ones containing the search string.
This is caused by adding the argument `--boundary`.

> --boundary
    Output uninteresting commits at the boundary, which are usually not shown. 

The GE code does not explain why it is added.
There is no setting in order to suppress it (yet).

---

You should not sort by `author date`. Rather use the implicit sort by `commit date`.

**Comment by gerhardol** [comment] 2022-07-19 21:40
> As you mentioned, Git lists commits which do not contain the search string - **after** the ones containing the search string. This is caused by adding the argument `--boundary`.

The 'in memory' search in 3.5 is adding more search hits.

> > --boundary
> > Output uninteresting commits at the boundary, which are usually not shown.
> 
> The GE code does not explain why it is added. There is no setting in order to suppress it (yet).

--boundary and --all are always used together. I guess it is to include parents. It seems like --boundary and --all should be excluded with --grep.
https://git-scm.com/docs/git-log#Documentation/git-log.txt---all

https://github.com/gerhardol/gitextensions/pull/new/feature/i10074-grep-boundary

**Comment by mstv** [comment] 2022-07-20 16:43
> https://github.com/gerhardol/gitextensions/pull/new/feature/i10074-grep-boundary

LGTM (just needs two whitespace fixes)

**Closed** 2022-07-25 14:40 UTC
Labels: type: feature request, :construction: status: in progress
