### ISSUE TITLE
[linux/mono] Crashes by entering settings

### ISSUE THREAD

**Issue by gitfineon** [gitextensions/gitextensions#5355] opened 2018-08-27 09:34 UTC
**Do you want to request a *feature* or report a *bug*?**
BUG: unable to open settings since version 2.51.03 (there is no *-Mono.zip for version 2.51.02)

**What is the current behavior?**
Following the instructions [How-To: run Git-Extensions on Linux](https://github.com/gitextensions/gitextensions/wiki/How-To:-run-Git-Extensions-on-Linux), step 6 "Configuring GitExtensions" is not possible due to the fact that the application crashes on opening settings.

```
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
  at System.IO.Path.Combine (System.String path1, System.String path2, System.String path3) [0x00006] in <dca3b561b8ad4f9fb10141d81b39ff45>:0 
  at GitUI.CommandsDialogs.SettingsDialog.MergeToolsHelper.CheckFileExists (System.String path, System.String location, System.String fileName, System.String& fullName) [0x00000] in <879b25d354464ad887f8e4b3f7531c19>:0 
  at GitUI.CommandsDialogs.SettingsDialog.MergeToolsHelper.FindFileInFolders (System.String fileName, System.String[] locations) [0x00033] in <879b25d354464ad887f8e4b3f7531c19>:0 
  at GitUI.CommandsDialogs.SettingsDialog.Pages.EditorHelper.GetEditorCommandLine (System.String editorName, System.String executableName, System.String commandLineParameter, System.String[] installFolders) [0x00000] in <879b25d354464ad887f8e4b3f7531c19>:0 
  at GitUI.CommandsDialogs.SettingsDialog.Pages.EditorHelper.GetNotepadPP () [0x00000] in <879b25d354464ad887f8e4b3f7531c19>:0 
  at GitUI.CommandsDialogs.SettingsDialog.Pages.EditorHelper.GetEditors () [0x0001c] in <879b25d354464ad887f8e4b3f7531c19>:0 
  at GitUI.CommandsDialogs.SettingsDialog.Pages.GitConfigSettingsPage.Init (GitUI.CommandsDialogs.SettingsDialog.ISettingsPageHost aPageHost) [0x00023] in <879b25d354464ad887f8e4b3f7531c19>:0 
  at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.Create[T] (GitUI.CommandsDialogs.SettingsDialog.ISettingsPageHost aPageHost) [0x00005] in <879b25d354464ad887f8e4b3f7531c19>:0 
  at GitUI.CommandsDialogs.FormSettings..ctor (GitUI.GitUICommands aCommands, GitUI.CommandsDialogs.SettingsDialog.SettingsPageReference initalPage) [0x00158] in <879b25d354464ad887f8e4b3f7531c19>:0 
  at (wrapper remoting-invoke-with-check) GitUI.CommandsDialogs.FormSettings:.ctor (GitUI.GitUICommands,GitUI.CommandsDialogs.SettingsDialog.SettingsPageReference)
  at GitUI.CommandsDialogs.FormSettings.ShowSettingsDialog (GitUI.GitUICommands uiCommands, System.Windows.Forms.IWin32Window owner, GitUI.CommandsDialogs.SettingsDialog.SettingsPageReference initalPage) [0x00021] in <879b25d354464ad887f8e4b3f7531c19>:0 
  at GitUI.GitUICommands+<>c__DisplayClass392_0.<StartSettingsDialog>b__0 () [0x00000] in <879b25d354464ad887f8e4b3f7531c19>:0 
  at GitUI.GitUICommands.DoActionOnRepo (System.Windows.Forms.IWin32Window owner, System.Boolean requiresValidWorkingDir, System.Boolean changesRepo, GitUIPluginInterfaces.GitUIEventHandler preEvent, GitUIPluginInterfaces.GitUIPostActionEventHandler postEvent, System.Func`1[TResult] action) [0x0002d] in <879b25d354464ad887f8e4b3f7531c19>:0 
  at GitUI.GitUICommands.StartSettingsDialog (System.Windows.Forms.IWin32Window owner, GitUI.CommandsDialogs.SettingsDialog.SettingsPageReference initialPage) [0x00028] in <879b25d354464ad887f8e4b3f7531c19>:0 
  at GitUI.CommandsDialogs.FormBrowse.SettingsClick (System.Object sender, System.EventArgs e) [0x0000b] in <879b25d354464ad887f8e4b3f7531c19>:0 
  at System.Windows.Forms.ToolStripItem.OnClick (System.EventArgs e) [0x0001c] in <5d999439b3404adfac86e7eebb5f00d6>:0 
  at System.Windows.Forms.ToolStripButton.OnClick (System.EventArgs e) [0x0001a] in <5d999439b3404adfac86e7eebb5f00d6>:0 
  at System.Windows.Forms.ToolStripItem.HandleClick (System.Int32 mouse_clicks, System.EventArgs e) [0x00036] in <5d999439b3404adfac86e7eebb5f00d6>:0 
  at System.Windows.Forms.ToolStripItem.FireEvent (System.EventArgs e, System.Windows.Forms.ToolStripItemEventType met) [0x00061] in <5d999439b3404adfac86e7eebb5f00d6>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripItem:FireEvent (System.EventArgs,System.Windows.Forms.ToolStripItemEventType)
  at System.Windows.Forms.ToolStrip.OnMouseUp (System.Windows.Forms.MouseEventArgs mea) [0x00057] in <5d999439b3404adfac86e7eebb5f00d6>:0 
  at System.Windows.Forms.Control.WmLButtonUp (System.Windows.Forms.Message& m) [0x0007e] in <5d999439b3404adfac86e7eebb5f00d6>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x0016f] in <5d999439b3404adfac86e7eebb5f00d6>:0 
  at System.Windows.Forms.ScrollableControl.WndProc (System.Windows.Forms.Message& m) [0x00000] in <5d999439b3404adfac86e7eebb5f00d6>:0 
  at System.Windows.Forms.ToolStrip.WndProc (System.Windows.Forms.Message& m) [0x00000] in <5d999439b3404adfac86e7eebb5f00d6>:0 
  at GitUI.ToolStripEx.WndProc (System.Windows.Forms.Message& m) [0x00000] in <879b25d354464ad887f8e4b3f7531c19>:0 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <5d999439b3404adfac86e7eebb5f00d6>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <5d999439b3404adfac86e7eebb5f00d6>:0 
  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x0008e] in <5d999439b3404adfac86e7eebb5f00d6>:0 
```
GitExtensions-2.51.03-Mono.zip additionally prints in the beginning `Could not set X locale modifiers`, but it is not printed with the latest (*2.51.04-Mono.zip) version.

**Environment you encounter the issue:**

- GitExtensions version: > 2.51.01
- GIT version: 2.7.4
- OS version: Ubuntu 16.04.5 LTS
- .NET version: mono-complete 5.10.1.20 ([Pinned mono version](https://stackoverflow.com/questions/33763177/install-older-version-of-mono/33763688) 4.6.1.5, as used in the instructions does not solve the issue.)

**Did this work in previous version of GitExtensions (which)?**
Works as expected with version 2.51.01 and prior.

**Comment by RussKie** [comment] 2018-08-27 10:38
Duplicate of #5187

**Closed** 2018-08-27 10:39 UTC
