### ISSUE TITLE
Integration plugins are failed to load

### ISSUE THREAD

**Issue by pravic** [gitextensions/gitextensions#3983] opened 2017-09-08 10:16 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

> Failed to load plugin JenkinsIntegration.dll : 
Exception info:
Отсутствует реализация метода "Initialize" в типе "JenkinsIntegration.JenkinsAdapter" из сборки "JenkinsIntegration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".
Отсутствует реализация метода "Initialize" в типе "TfsIntegration.TfsAdapter" из сборки "TfsIntegration, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null".
Отсутствует реализация метода "Initialize" в типе "TeamCityIntegration.TeamCityAdapter" из сборки "TeamCityIntegration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just opened GitEx program, without opening repository.

**What is the expected behavior?**
As in previous versions, no errors.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: git version 2.11.1.windows.1
- OS version: Windows 7 SP1 x64

**Did this work in previous version of GitExtensions (which)?**

The latest 2.49.xx used to work fine. Moreover, on another machine (also win7x64) it doesn't throw such exceptions - may be settings are different (for example, if integration plugins are disabled on that PC).

**Comment by gregsohl** [comment] 2017-09-20 20:44
I had this same issue in (I think) 2.50.1, on one machine only. While I don't know the cause, an uninstall, reinstall corrected the issue.

**Comment by RussKie** [comment] 2017-12-13 21:53
@pravic have you tried uninstall-install as Greg suggested?

**Comment by pravic** [comment] 2017-12-14 04:39
No, I haven't. I just deleted those plugins.

**Comment by RussKie** [comment] 2017-12-14 05:08
I'm going to close it then, since we can't get any information to progress it further.

**Closed by RussKie** 2017-12-14 05:08 UTC
Labels: bug, GE plugin
