### ISSUE TITLE
Dark Theme does not work correctly

### ISSUE THREAD

**Issue by hakanaltindis** [gitextensions/gitextensions#10411] opened 2022-11-16 08:43 UTC
### Environment

- Git Extensions: 4.0.0.15569
- Build: cba315df5366fca01240d93b6e5a5077fd5e6630
- Git: 2.38.1.windows.1
- OS: Microsoft Windows NT 10.0.19044.0
- NET version: .NET 6.0.11

### Issue description

I think there is a problem in dark theme.

![image](https://user-images.githubusercontent.com/6873753/202130128-75e811f4-7730-4df3-a60f-92c26f1ebbd7.png)

### Steps to reproduce

Tools -> Settings -> Appearance -> Color - Theme change to Dark

After restart git extension, Theme is shown above image. 

And the "Use system-defined visual style (looks bad with dark colors) selection is checked. It does not working again.

![image](https://user-images.githubusercontent.com/6873753/202131054-015cc189-9012-43c5-928e-76ccd7f0e8cd.png)

**Comment by gerhardol** [comment] 2022-11-16 08:47
Duplicate of #10312

**Comment by pmiossec** [comment] 2022-11-16 08:47
Dark theme is no more supported in v4.0 because no technical solution has been found working with .net core/5.0 (like announced in the release notes: https://github.com/gitextensions/gitextensions/discussions/10310#discussion-4525909 )
Duplicate of #10373, #10369, #10361, #10331, #10326, #10312
Also discussed in https://github.com/gitextensions/gitextensions/discussions/10310#discussioncomment-4068052

**Closed** 2022-11-16 08:47 UTC
Labels: :eyeglasses: status: needs review

**Comment by hakanaltindis** [comment] 2022-11-16 09:07
I missed previous issues. Thank you for your explanation.
