### ISSUE TITLE
Unable to create new repository from windows explorer (v2.48.03)

### ISSUE THREAD

**Issue by Chris-Rogers** [gitextensions/gitextensions#2637] opened 2015-02-02 02:22 UTC
After getting the latest version (v2.48.03) on both Windows 7 (64 bit) and Windows 8.1 (64 bit), GitExtensions no longer is able to create a new repository from a windows explorer window.

To reproduce on this machine:
Use windows explorer to view any non-git folder (eg C:\Temp\SomeDirectory)
Right click and select "GitExt Create new repository"

Instead of creating a new repository, a dialog box opens which shows the supported command line usage for gitex.cmd
![image](https://cloud.githubusercontent.com/assets/3664452/5995123/646927f0-aade-11e4-8998-349f710b7a22.png)

Apologies if this has already been reported.  I wasn't able to find an open case that described this issue.

Thanks

**Comment by Chris-Rogers** [comment] 2015-02-02 02:35
Sorry - after posting that, I was able to find that this is a duplicate and that this has already been addressed.  Please accept my apologies.

Is there any ETA on when the next version may be released?

**Comment by KindDragon** [comment] 2015-02-02 08:37
Duplicate of #2564.
No ETA yet

**Closed by KindDragon** 2015-02-02 08:37 UTC
