### ISSUE TITLE
Git Extensions asks for SSH passphrase when using OpenSSH as ssh client

### ISSUE THREAD

**Issue by janhavel1** [gitextensions/gitextensions#9646] opened 2021-10-12 11:32 UTC
### Environment

- GitExtensions version:3.5.4
- GIT version: 2.33.0.windows.2
- OS version: Windows 10
- .NET version: 

### Issue description

Setting to use OpenSSH causes git shows up SSH password prompt on each pull or push. 
If changing setting to other ssh client: c:\Windows\System32\OpenSSH\ssh.exe, it starts to behave correctly, no password prompt anymore.
There is a similar issue that complains it is not possible to browse for this pathname and it still continues - I had to paste the path from TotalCommander that is able to see hidden system files and folders. 
The reason is that probably GIT_SSH is not used eventhough it points to the same pathname
GIT_SSH=C:\Windows\System32\OpenSSH\ssh.exe
So either fix  GE to use it GIT_SSH or at least note in the documentation that OpenSSH may not work or that it may require manual setting below.
![image](https://user-images.githubusercontent.com/92371511/136946130-f85c9f05-7e72-4251-8025-e429e4fcf293.png)
It took me half a day fo figure it out, it drove me crazy so I decided to report it; it may help others if they google it.

### Steps to reproduce

-OpenSSH Authentication Agent service is running
-GIT_SSH=C:\Windows\System32\OpenSSH\ssh.exe
in a repo accessed through SSH (gitlab.com in my case)
C:\git\monitoring>git pull
Already up to date.\
![image](https://user-images.githubusercontent.com/92371511/136946911-133b440c-4cc7-4bde-becd-3fe486144dcb.png)
the same repo in GE with ssh client = OpenSSH
![image](https://user-images.githubusercontent.com/92371511/136947017-ab92fe87-bdd9-4063-98e0-054f8f5fb121.png)
the same repo in GE with other ssh client = c:\Windows\System32\OpenSSH\ssh.exe
![image](https://user-images.githubusercontent.com/92371511/136947272-a38c575d-47e7-4738-a7f3-1fc2a5d25c5e.png)

### Did this work in previous version of GitExtensions?

Probably no.

**Comment by gerhardol** [comment] 2021-10-16 16:49
Duplicate of #9355

GE is always setting (or unsetting) the environment variable GIT_SSH to the GE settings values (you can override with GIT_SSH_COMMAND).
With OpenSSH, the variable is unset as Git then uses the bundled OpenSSH.

C:\Windows\System32\OpenSSH\ssh.exe is a different implementation.
So of course you need to set the path.

It is not possible to browse for paths in System32 due to GE being 32bit, see https://github.com/gitextensions/gitextensions/issues/9355#issuecomment-879043595
So that have to be pasted manually (GE does not use the value internally).

**Closed by gerhardol** 2021-10-16 16:49 UTC
Labels: :eyeglasses: status: needs review

**Comment by efaruk** [comment] 2024-06-19 11:05
Just one tip when using GIT_SSH_COMMAND environment variable instead of giving "C:\Windows\System32\OpenSSH\ssh.exe" as value you must use forward slashes like this "C:/Windows/System32/OpenSSH/ssh.exe" otherwise GE will end up with a path as "C:WindowsSystem32OpenSSHssh.exe" as it removes back slashes from the given path and you'll end up with a file not found error.
