### ISSUE TITLE
Bug in Commit Dialog - clicking in commit message changes displayed diff if diff is from unstaged files

### ISSUE THREAD

**Issue by rluiten** [gitextensions/gitextensions#5068] opened 2018-06-12 21:49 UTC
**What is the current behavior?**

If I have an unstaged file top left list pane select showing a diff in the top right pane as soon as I click in the window commit message to type a comment the selected diff is changed and the first stage file is selected in the lower left pane and the diff displayed is for that file.

This does not occur if there are no staged files.

This change of selected diff file does not occur if the selected file is the staged area bottom left pane.

I have also noticed that in certain cases if the cursor is already active in the commit message pane not sure under what conditions this occurs then clicking there again does not cause a change in the displayed diff.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

As above.

**What is the expected behavior?**

Do not change which diff is displayed in the top right pane when the commit message area is clicked to set curosr in it.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.01 and 2.51.02
- GIT version: git version 2.17.1.windows.2
- OS version: Windows 10 Enteprise 1709

**Did this work in previous version of GitExtensions (which)?**

I believe this is a new behavior, but can't nail down when i first noticed it.

**Comment by vbjay** [comment] 2018-06-12 22:04
You want to see what is being committed and not what is being ignored when
typing in the commit meesage.

**Comment by rluiten** [comment] 2018-06-12 22:11
Is this a new behavior ? I did not notice it before.

I respectfully disagree, I want to see what I have selected for viewing, jumping the diff to the first staged file does not help my work flow.

**Comment by vbjay** [comment] 2018-06-12 22:15
Workflow: Stage changes. Add message describing STAGED changes. Commit.

Clicking in the commit message textbox should show the staged changes and
not what is yet to be staged.

**Comment by pmme** [comment] 2018-06-15 04:55
https://github.com/gitextensions/gitextensions/pull/3920

I for one was pleased to note the new behaviour. 
Prior to #3920 I would stage files, click into the commit message, then realise I was seeing unstaged changes, click on a staged file, then click back into the commit message.

**Comment by RussKie** [comment] 2018-06-15 08:23
I suppose we can close it as "by design".

**Closed** 2018-06-16 05:56 UTC
Labels: discussion
