### ISSUE TITLE
[NBug] SSH key file could not be found

### ISSUE THREAD

**Issue by holstebroe** [gitextensions/gitextensions#10555] opened 2022-12-19 14:44 UTC
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

''

```
GitUI.NBugReports.UserExternalOperationException: SSH key file could not be found
 ---> System.IO.FileNotFoundException: SSH key file could not be found
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.PuttyHelpers.ThrowIfFileNotFound(String filePath, String errorMessage, String heading)
   at GitUI.Infrastructure.PuttyHelpers.StartPageantIfConfigured(Func`1 sshKeyFileLoader)
   at GitUI.CommandsDialogs.FormPush.StartPageant(String remote)
   at GitUI.CommandsDialogs.FormPush.PushChanges(IWin32Window owner)
   at GitUI.CommandsDialogs.FormPush.PushClick(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Tried to push to an SMB remote directory. No SSH key needed or expected.

### Steps to reproduce

1. Create a remote repository from an SMB url, example "\\mymachine.myhost.com\git\MyRepo"
2. Push to that repo.

### Did this work in previous version of GitExtensions?

Yes, pushing to remote SMB repositories has worked in all versions up til 4.x

**Comment by holstebroe** [comment] 2022-12-19 14:46
Workaround: I selected some random private key file in the remote repository window. After that I could push to the key-less SMB remote.

**Comment by gerhardol** [comment] 2022-12-19 15:36
Duplicate of #10530
Please try the solution in #10545

**Closed by gerhardol** 2022-12-19 15:36 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
