### ISSUE TITLE
[NBug] El valor no puede ser nulo.Parameter name: value

### ISSUE THREAD

**Issue by hdiaza-dev** [gitextensions/gitextensions#9496] opened 2021-08-13 12:22 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentNullException: El valor no puede ser nulo.
Nombre del parámetro: value
   en ConEmu.WinForms.ConEmuStartInfo.set_ConsoleProcessCommandLine(String value)
   en GitUI.CommandsDialogs.FormBrowse.<FillTerminalTab>b__201_0(Object sender, TabControlCancelEventArgs args)
   en System.Windows.Forms.TabControl.OnSelecting(TabControlCancelEventArgs e)
   en System.Windows.Forms.TabControl.WmSelChange()
   en System.Windows.Forms.TabControl.WndProc(Message& m)
   en GitUI.CommandsDialogs.FullBleedTabControl.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
i've just installed it and when i go to console tab occurs this.

## Environment
- Git Extensions 3.5.2.12435
- Build 77413699a9c25b160a6a622311529372b5d87f5b
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4390.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2021-08-14 13:21
Duplicate of #9471
Set path to Linux tools

**Closed by gerhardol** 2021-08-14 13:21 UTC
Labels: potential-duplicate
