### ISSUE TITLE
Fails to start in windows 10

### ISSUE THREAD

**Issue by azatsh** [gitextensions/gitextensions#4973] opened 2018-05-21 16:11 UTC
When opening .exe file in windows 10 there is an issue: "Windows cannot access the specified file, device, or file. You may not have appropriate permissions to access the item".
I tried to change the security settings for the file, added full permissions, but it did not help.
Also I tried to run it in compatibility mode (win7, win8) and it also did not help.

Neither installed nor portable version works.

- Environment: Windows 10 Enterprise 64 bit.
- GitExtensions version: 2.51.01
- GIT version: 
- OS version: Windows 10 Enterprise 64 bit.

**Comment by gerhardol** [comment] 2018-05-21 19:16
How did you install? Installer, as admin?
What file? Path?
Antivirus?

**Comment by RussKie** [comment] 2018-05-22 04:40
this may happen if windows blocks dlls when it thinks it came from an
untrusted source.
You can unblock them manually (right click > unblock) or run a script
(google)

**Comment by RussKie** [comment] 2018-05-22 06:46
try disabling mcafee and try again?

what .net version do you have installed?

**Comment by azatsh** [comment] 2018-05-22 08:34
Okay, seems McAfee blocks the application, I don't know why.

**Comment by vbjay** [comment] 2018-05-22 10:27
McAfee has never played nice with developers. McAfee is crap. Try avast.

**Comment by RussKie** [comment] 2018-05-22 10:40
Amen... Our work laptops are unusable thanks to McAfee...

**Comment by RussKie** [comment] 2018-05-22 10:50
Closing since we established the root cause.
Feel free to update if you have more information.

**Closed by RussKie** 2018-05-22 10:50 UTC
Labels: info needed

**Comment by azatsh** [comment] 2018-05-22 10:54
I have no choice, it's a corporate standard in our company.
Thank you all !

**Comment by RussKie** [comment] 2018-05-22 11:00
McAfee is run on our corporate devices but we have no dramas running GE... 😯
