### ISSUE TITLE
Add stash to left panel tree

### ISSUE THREAD

**Issue by katrash** [gitextensions/gitextensions#10095] opened 2022-07-28 16:14 UTC
### Feature description

It will be more effective and nicer to have the stashes as tree nodes in the left panel along with the branches and other nodes. This allows the user to go directly to the stash in the commits panel on the right.

### Environment

N/A

**Comment by gerhardol** [comment] 2022-07-29 20:52
Duplicate of #5460 

See also #5371

**Closed** 2022-07-29 20:52 UTC
Labels: type: feature request
