### ISSUE TITLE
Proceudre entry point not found

### ISSUE THREAD

**Issue by Sundaramn** [gitextensions/gitextensions#4013] opened 2017-09-20 18:43 UTC
**Do you want to request a *feature* or report a *bug*?**  Report a bug

**What is the current behavior?**  not able to pull the changes from github

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**  Have upgraded to latest git extension ( 2.50.02 ) since then it is failing.

**What is the expected behavior?**  
Able to pull the GitHub repositories without issue
**Environment you encounter the issue:**  

- GitExtensions version:  2.50.02
- GIT version:  2.14.1
- OS version:  windows 10

**Did this work in previous version of GitExtensions (which)?**
It worked fine with previous version.. i wasn't sure it should be prior 2.50

**Comment by Sundaramn** [comment] 2017-09-20 18:44
![image](https://user-images.githubusercontent.com/7227563/30661488-03c67c66-9df9-11e7-9468-d409a95eadb6.png)

**Comment by jbialobr** [comment] 2017-09-20 18:48
Duplicate of #4005

**Closed by jbialobr** 2017-09-20 18:48 UTC
