### ISSUE TITLE
Title in Commit Window not refreshed after "Create branch"

### ISSUE THREAD

**Issue by matthiaslischka** [gitextensions/gitextensions#4091] opened 2017-10-23 16:47 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Title of the commit window still says "Commit to _\<old branch\>_" after creating a new branch with the "Create branch" feature available within the commit window.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
 - Open commit window
 - Click "Create branch"
 - Enter Name and actually create a branch
 - **(!)** Title still has the old branch name

**What is the expected behavior?**
Title should have the name of the new branch since this commit will actually go to the new branch and not to the old one anymore.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.01
- GIT version: 2.14.2.windows.1
- OS version: Windows 10 Enterprise Version 1703

**Did this work in previous version of GitExtensions (which)?**
Yes. Most of them. Love this tool. ;)

**Comment by gerhardol** [comment] 2017-10-23 19:43
Fixed in 2.51 #3993 
This feature was new in 2.50 so cannot have worked in previous versions....

**Comment by RussKie** [comment] 2017-10-23 19:59
Duplicate of #3982

**Closed by RussKie** 2017-10-23 19:59 UTC
