### ISSUE TITLE
Unreadable texts in dark theme

### ISSUE THREAD

**Issue by matthew11** [gitextensions/gitextensions#1947] opened 2013-07-02 08:07 UTC
![gitext](https://f.cloud.github.com/assets/4918748/735228/fed6dfb8-e2ed-11e2-87f1-adcd54149506.png)
--- GitExtensions2.44, 1.8.1.2, Linux 3.8.0.25 with XFCE4 and mono 2.10.8.1

See the attachment.

**Comment by aaronbond** [comment] 2016-10-12 00:28
i also get this issue, any chance it will eventually be fixed?

**Comment by mica100** [comment] 2016-11-15 13:33
still a problem in the history log background. Is there a chance to set the background color?

Text is white but background too, even if set to something dark in Windows settings.

Menus, also right mouse menu, lower part of browse main window (with commit details) and commit dialog take the windows colors. There is no problem with this anymore.

Only the background in the history log window.

**Comment by aaronbond** [comment] 2016-11-23 05:16
this project has 636 issues :( not much chance this one would be a priority, i've just had to move to a light theme because i really do use gitextensions a lot, it's a nice ui to have when i need one on top of git.

**Comment by jbialobr** [comment] 2017-04-05 08:58
Only partially fixed. (Closed automagically by github).

**Comment by safield** [comment] 2017-10-28 20:12
I am having this issue on Linux Mint 18.2, using Mint-y dark theme.

The proper solution is to have git ext adopt the dark theme color for its windows, or a less desirable fix would be to NOT adopt the dark themes light text.

The problem arises because the font is changing to the dark themes light font, but the background is not changing to toe dark themes dark themes dark background. This results on light text on light background.

**Comment by RussKie** [comment] 2017-10-29 13:31
Is the latest version still the same bad as on the screenshot above?

There are a number of issues with dark theme support, even on Windows.
Sadly for you and other Mono users Linux support isn't high on our todo list - no one from the core team uses Linux/Mono full time.
PRs are always welcome though.

**Comment by safield** [comment] 2017-10-29 22:10
In 2.50.02 version the issue is just as bad as the first screenshot provided.

**Comment by gerhardol** [comment] 2019-06-15 21:44
Closed by #6651

**Closed by gerhardol** 2019-06-15 21:44 UTC
Labels: area: linux/mono, area: user experience, status: pull request only, up for grabs
