### ISSUE TITLE
Flickering in FormCommit when selecting not the first item in Staged/Unstaged

### ISSUE THREAD

**Issue by mdonatas** [gitextensions/gitextensions#7266] opened 2019-10-08 19:10 UTC
## Current behavior
When selecting not the first item by mouse in Staged/Unstaged lists you first see diff of the first item for a short while before seeing the diff of the item clicked on.

## Expected behavior
See selected items diff immediately

## Screenshots
![](https://spurgius.com/interwebs/img/201910082159_flicker.gif)

This happens because `FormCommit` in `Unstaged_Enter` / `Staged_Enter` resets the `FileStatusList.SelectedIndex` to `0` regardless of what's been clicked on.

Most likely introduced in https://github.com/gitextensions/gitextensions/pull/3920

**Comment by mstv** [comment] 2019-10-08 19:24
Thank you for the link to the potential source.
Duplicate of #6561.
Unfortunately, the other WIP bugfix #7247 in this area does not solve this issue.

**Closed by mstv** 2019-10-08 19:24 UTC

**Comment by mdonatas** [comment] 2019-10-08 20:17
@mstv I have this fixed my personal build. Will create a PR to show the solution. Not sure if it's the correct one though.

**Comment by mstv** [comment] 2019-10-09 06:06
> I have this fixed in my personal build. Will create a PR to show the solution.

Sounds very good. I have finished my bugfix #7247. At a first glance, I don't expect notable merge conflicts. I hope I'll find time to review your PR in the evening.
