### ISSUE TITLE
Why no depth support of clone?

### ISSUE THREAD

**Issue by SetoKaiba** [gitextensions/gitextensions#2842] opened 2015-06-24 05:28 UTC
I found that GitCommandHelpers.CloneCmd is with support of depth parameter.
Why no depth in UI?
```
                var cloneCmd = GitCommandHelpers.CloneCmd(_NO_TRANSLATE_From.Text, dirTo,
                            CentralRepository.Checked, cbIntializeAllSubmodules.Checked, Branches.Text, null);
```
The last parameter is null.

**Comment by Radrik5** [comment] 2015-06-24 05:37
Probably duplicate of #2709.

**Closed** 2015-06-24 09:26 UTC
