### ISSUE TITLE
Command Line: Without Options Open Browser In Current Folder

### ISSUE THREAD

**Issue by Dyoung0606** [gitextensions/gitextensions#7803] opened 2020-02-24 15:56 UTC
## Feature description
1. In a command prompt window, change to a directory that contains a git repo.
1. Run "gitextensions" (with no parameters/options)

At the moment, gitextensions opens a screen showing all recent repos.
It would be handy if running gitextensions with no options behaved the way "gitextensions browse ." does; i.e., open the browser in the current repo/branch/etc.

It used to open the current repo; opening an empty workspace is new behavior.
Though I'm unsure which version introduced the change. It's also possible I simply remember it wrong and it's always been this way.  In either event, please update the tool so running with no options behaves as if "browse ."

Thanks!

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3468.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment] 2020-02-24 16:11
From what I understood, the `gitex.com` file is here for that.

So just call `gitex`.

**Comment by pmiossec** [comment] 2020-02-24 16:13
Duplicate of #7542

**Closed by pmiossec** 2020-02-24 16:13 UTC

**Comment by pmiossec** [comment] 2020-02-24 16:17
A bugfix has not been released yet, so probably you will have to update the content of the file with the content of this one: https://github.com/gitextensions/gitextensions/blob/master/Bin/gitex.cmd
