### ISSUE TITLE
Branch Filter crash

### ISSUE THREAD

**Issue by vzabavnov** [gitextensions/gitextensions#4759] opened 2018-04-02 17:59 UTC
GitExtensions.exe [2.51]
CLR: 4.0.30319.42000

Exception:
System.ArgumentOutOfRangeException: System.Object get_Item(Int32) @ System.Windows.Forms.ComboBox+ObjectCollection
Message:
InvalidArgument=Value of '0' is not valid for 'index'.
Parameter name: index

Pre-requirements: repository must have two branches

How to get it:
1. open history for file
2. in "Branches" manually enter first branch name, space, and second branch name.
3. press Enter -> nothing is filtered
4. click by mouse in the Filter field -> you've got it

**Comment by RussKie** [comment] 2018-04-05 01:04
Duplicate of #4370

**Closed by RussKie** 2018-04-05 01:04 UTC
