### ISSUE TITLE
My index is clean but GitExtensions reports 2 pending commits

### ISSUE THREAD

**Issue by fabvit** [gitextensions/gitextensions#5141] opened 2018-07-06 14:44 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

Anyway GitExtensions commit icon is yellow (instead of green) and tells me that therre are 2 pending commits.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Environment you encounter the issue:**

- GitExtensions version: 2.51.03
- GIT version: git version 2.18.0.windows.1
- OS version: Windows 7 Pro x64
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**
Yes it worked as expected in v2.51.02

**Comment by vbjay** [comment] 2018-07-06 16:08
Search for issues before posting your own.

**Comment by gerhardol** [comment] 2018-07-06 16:14
Duplicate of #5127

**Closed by gerhardol** 2018-07-06 16:14 UTC
