### ISSUE TITLE
Stash parent graph node "untracked files" is hidden

### ISSUE THREAD

**Issue by kunszabo** [gitextensions/gitextensions#4979] opened 2018-05-24 15:34 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

When "Include untracked files in stash" is enabled, the stash node in the commit graph has an extra orphan parent that contains the untracked files. This node gets hidden when scrolling it out of view and back because the graph is automatically resized one lane less than necessary (see screenshot)
![image](https://user-images.githubusercontent.com/1556671/40495243-117c9a30-5f77-11e8-9628-f23881a17cd2.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Enable "Include untracked files in stash" option
- Create some untracked files in a repository
- Create a stash
- Scroll back and forth in the commit list. The new stash node and its parents should be scrolled off the visible area and then scrolled back.
- The commit graph is automatically resized so that the node representing the untracked files is hidden

**What is the expected behavior?**

The node of the untracked files should be visible even after scrolling it out of view and back.
(see screenshot):
![image](https://user-images.githubusercontent.com/1556671/40495723-435417b2-5f78-11e8-8f74-0fe63b6de5a1.png)

**Environment you encounter the issue:**

- GitExtensions version: 2.51.01
- GIT version: 2.15.1.windows.2
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**

Not checked.

**Comment by drewnoakes** [comment] 2018-05-25 13:06
I have observed this too in the past.

**Comment by gerhardol** [comment] 2018-05-28 21:16
This occurs when untracked files is the commit furthest to the right. The algorithm to calculate number of the steps is not calculating this correctly for stash.

**Comment by gerhardol** [comment] 2018-08-15 20:45
The graph handling is changed a lot in master, primarily #5087 
This problem however occurs more often tracked in #5167 
Closing this as a duplicate of #5167

**Comment by mstv** [comment] 2018-08-30 18:58
Unfortunately, this part of the issue was not solved by the solution #5356 of #5167.

**Comment by gerhardol** [comment] 2018-08-30 21:11
> Unfortunately, this part of the issue was not solved by the solution #5356 of #5167.

How to recreate?

**Comment by mstv** [comment] 2018-08-30 22:01
* checkout the most recent branch and modify a file
![grafik](https://user-images.githubusercontent.com/36601201/44881509-3187b900-acb0-11e8-9a34-7f67f31cf02c.png)
* stash the change (after a noticeable delay, the `Commit` button is updated)
![grafik](https://user-images.githubusercontent.com/36601201/44881546-5f6cfd80-acb0-11e8-8532-bce7e52e23f6.png) ![grafik](https://user-images.githubusercontent.com/36601201/44881690-c985a280-acb0-11e8-9fa8-0aa5817e4f2a.png))

**Comment by RussKie** [comment] 2018-08-30 22:16
I can't replicate it in v3 😞 
No matter what I try I don't get the dangling entry...

**Comment by mstv** [comment] 2018-08-30 22:36
These screenshots are from v3. There must be visible not more than two parallel branches.
Try moving the splitter up, please.

**Comment by RussKie** [comment] 2018-08-31 05:29
![image](https://user-images.githubusercontent.com/4403806/44894342-997ee380-ad32-11e8-9382-383ce393031c.png)

**Comment by mstv** [comment] 2018-08-31 06:15
![grafik](https://user-images.githubusercontent.com/36601201/44895715-dbd5ff80-acf5-11e8-8134-ee9f71894237.png)

**Comment by RussKie** [comment] 2018-09-01 04:33
Thanks Michael, that option helped.
At the latest master it all renders correctly
![image](https://user-images.githubusercontent.com/4403806/44942436-0b6b3180-adf4-11e8-9138-d239296cd4d0.png)

**Comment by mstv** [comment] 2018-09-01 11:45
@RussKie, move up the splitter, please, so that "Merge pull request #5367 ..." is the last visible commit.

**Comment by RussKie** [comment] 2018-09-01 13:42
![image](https://user-images.githubusercontent.com/4403806/44946497-adb10680-ae40-11e8-871e-a3aa3721e96b.png)

**Comment by mstv** [comment] 2018-09-01 23:40
The sequence of "index on ..." and "untracked files ..." is different for you (Git 2.18.0.w.x64) and gerhardol & me (Git 2.17.1.w.2-x64).
The commit for "untracked files ..." is one second older than "index on ..." with Git 2.17.1.w.2-x64.

**Comment by RussKie** [comment] 2018-09-02 01:50
I actually wondered about the order.

I think I may have an installation with an older version of git to try...

**Comment by RussKie** [comment] 2018-09-02 03:41
I checked my screenshot was taken with git 2.16.2.windows.1

**Comment by gerhardol** [comment] 2022-07-29 19:29
![image](https://user-images.githubusercontent.com/6248932/181830716-002f6a05-1eac-4794-8d47-6055d81c87f9.png)

I do not see this in latest master, there has been rendering changes.
Closing

**Closed by gerhardol** 2022-07-29 19:29 UTC
Labels: type: bug :bug:, area: user experience, status: reproducible
