### ISSUE TITLE
[NBug] 值不能为 null。参数名: key

### ISSUE THREAD

**Issue by zjh-coder** [gitextensions/gitextensions#8160] opened 2020-05-28 02:19 UTC
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentNullException: 值不能为 null。
参数名: key
   在 System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, TValue addValue, Func`3 updateValueFactory)
   在 GitUIPluginInterfaces.CredentialsSetting.CredentialsControlBinding.SaveSetting(ISettingsSource settings, CredentialsControl control)
   在 GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.PageToSettings()
   在 GitUI.CommandsDialogs.FormSettings.Save()
   在 GitUI.CommandsDialogs.FormSettings.Ok_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
this happened when I tried to add Jira Commit Hint

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2020-05-28 20:08
Duplicate of #6704

Please try the build in #8123 that has changes to Jira for 3.4

**Closed** 2020-09-28 05:36 UTC
