### ISSUE TITLE
Default pull action is _always_ used, even if another action is selected from the dropdown menu (3.00.00.01-beta1)

### ISSUE THREAD

**Issue by amaiorano** [gitextensions/gitextensions#5548] opened 2018-10-10 19:08 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If a default pull action is selected from the Pull button arrow -> Set default Pull button action, then it will _always_ perform this action, even if you try to select another action from that Pull button arrow pulldown menu.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Select "Fetch" as a default Pull action:

![image](https://user-images.githubusercontent.com/6893883/46759759-2c019380-cc9e-11e8-8a20-9cecd4969cf3.png)

Now try to select Pull - merge:

![image](https://user-images.githubusercontent.com/6893883/46759787-3ae84600-cc9e-11e8-9612-de38412d6f12.png)

Notice that it will fetch:

![image](https://user-images.githubusercontent.com/6893883/46759806-450a4480-cc9e-11e8-99d8-578d0f9c7c1c.png)

**What is the expected behavior?**

The default pull action should only be used for when the button is pressed.

**Environment you encounter the issue:**

- GitExtensions version: 3.00.00.01-beta1
- GIT version: git version 2.19.0.windows.1
- OS version: Windows 10 Pro
- .NET version: ?

**Did this work in previous version of GitExtensions (which)?**
2.51.05

**Comment by pmiossec** [comment] 2018-10-10 19:59
Duplicate of #5420 (and #5539) 😉

**Comment by pmiossec** [comment] 2018-10-10 20:05
But I admit that I'm looking forward for this bug to be fixed. I don't know who refactored this piece of code and know how to fix it

**Comment by gerhardol** [comment] 2018-10-10 20:50
Closed as a duplicate

**Closed by gerhardol** 2018-10-10 20:50 UTC

**Comment by RussKie** [comment] 2018-10-10 22:07
Duplicate of #5420
