### ISSUE TITLE
[NBug] git checkout-index: BAREQChecker/Reporters/EmailReportersss...

### ISSUE THREAD

**Issue by EatATaco** [gitextensions/gitextensions#10443] opened 2022-11-23 13:56 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: checkout-index --index --force -- "BAREQChecker/Reporters/EmailReporterssss.cs"
Working directory: C:\Users\barnesc\source\repos\test\BAREQChecker\

```
GitExtUtils.ExternalOperationException: git checkout-index: BAREQChecker/Reporters/EmailReporterssss.cs is not in the cache
 ---> System.Exception: git checkout-index: BAREQChecker/Reporters/EmailReporterssss.cs is not in the cache
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetBatchOutput(IExecutable executable, ICollection`1 batchArguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.ResetFiles(IReadOnlyList`1 files)
   at GitUI.CommandsDialogs.FormCommit.ResetSoftClick(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.FormCommit.ResetSelectedFiles()
   at GitUI.CommandsDialogs.FormCommit.ExecuteCommand(Int32 cmd)
   at ResourceManager.GitExtensionsFormBase.ProcessHotkey(Keys keyData)
   at GitUI.CommandsDialogs.FormCommit.ProcessHotkey(Keys keyData)
   at ResourceManager.GitExtensionsFormBase.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

1. Renamed file
2. Staged the changes
3. Hit 'r' on the staged combined file
4. Kaboom

### Steps to reproduce

1. Renamed file
2. Staged the 2 files (original name removed, and new name added)
3. (the files have now combined into one entry, showing the name change)
4. Attempted to revert with 'r' on the staged change 

Was able to easily reproduce multiple times.

### Did this work in previous version of GitExtensions?

No idea

**Comment by gerhardol** [comment] 2022-11-23 23:00
Duplicate of #10423
Renamed files also need to be handled with other commands

**Closed by gerhardol** 2022-11-23 23:00 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
