### ISSUE TITLE
[NBug] git checkout-index: src/.editorconfig is not in the cache

### ISSUE THREAD

**Issue by fschmied** [gitextensions/gitextensions#10929] opened 2023-04-29 12:17 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.16
- DPI 96dpi (no scaling)

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: checkout-index --index --force -- "src/.editorconfig"
Working directory: C:\Development\SignPath.TimestampingServerProxy\

```
GitExtUtils.ExternalOperationException: git checkout-index: src/.editorconfig is not in the cache
 ---> System.Exception: git checkout-index: src/.editorconfig is not in the cache
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetBatchOutput(IExecutable executable, ICollection`1 batchArguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.ResetFiles(IReadOnlyList`1 files)
   at GitUI.CommandsDialogs.FormCommit.ResetSoftClick(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.FormCommit.ResetSelectedFiles()
   at GitUI.CommandsDialogs.FormCommit.ExecuteCommand(Int32 cmd)
   at ResourceManager.GitExtensionsFormBase.ProcessHotkey(Keys keyData)
   at GitUI.CommandsDialogs.FormCommit.ProcessHotkey(Keys keyData)
   at ResourceManager.GitExtensionsFormBase.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

Moved .editorconfig from repository root directory to "src" subfolder, staged this change, then reset the change.

### Steps to reproduce

Prepare repository with `.editorconfig` in repository root directory and src subfolder. Commit. Move `.editorconfig` from repository root directory to `src` subfolder, stage this change, then reset the change.

**Comment by gerhardol** [comment] 2023-04-29 19:34
Duplicate of #10470
stage/unstage the file to remove conflict before reset

Before 4.0, Git errors were silently ignored. Reset of files need special handling per type, not all cases were handled.
4.1 handles some common scenarios, some situations that require data structure changes for conflicted files with added/removed files are not handled still.

--

Related, in upcoming 4.1
renamed file changed in https://github.com/gitextensions/gitextensions/pull/10853
conflicts in the contents changed in https://github.com/gitextensions/gitextensions/issues/10423

**Closed by gerhardol** 2023-04-29 19:34 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
