### ISSUE TITLE
Expand / collapse button of ExListView is not working

### ISSUE THREAD

**Issue by NikolayXHD** [gitextensions/gitextensions#5427] opened 2018-09-14 01:55 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Despite #5093 collapse / expand button in group header is not working neither in Dashboard nor FileStatusList. collapse / expand by double-clicking group header works though.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1a. Click collapse button in any group header in FileStatusList. Nothing happens.

![image](https://user-images.githubusercontent.com/12046452/45525119-59137100-b7da-11e8-8243-9d68673159f7.png)

1b. Click collapse button in any group header in Dashboard. Nothing happens.

![image](https://user-images.githubusercontent.com/12046452/45525082-397c4880-b7da-11e8-9920-af04529a0ceb.png)

**What is the expected behavior?**

The group collapses.

**Environment you encounter the issue:**

Windows 7

**Comment by gerhardol** [comment] 2018-09-15 00:31
Duplicate of #5332 and #4886, but as there is a PR all can be closed?

**Closed** 2018-09-16 12:42 UTC
Labels: area: user experience
