### ISSUE TITLE
Diff on commit not treated as diff to local when possible (duplicate)

### ISSUE THREAD

**Issue by ZulfinZ** [gitextensions/gitextensions#9599] opened 2021-09-30 11:11 UTC
## Current behaviour
The diff tool opens with two temporary files in the comparison

## Expected behaviour
When local file changes are committed, when opening the diff tool, the local file should be used instead of a temporary file
**This is a duplicate of issue as #4748**.
Unfortunately, this issue still exists with git version 2.32.0.windows.2 (and git version 2.33.0.windows.2) and wasn't resolved.

## Steps to reproduce
Please see #4748

## Did this work in previous version of GitExtensions
Yes. Git version change broke this feature.
The last git version working with it was 2.14.3

## Environment

- GitExtensions version: 3.5.3.12551 (and 3.5.4)
- GIT version: 2.32.0.windows.2 (or 2.33.0.windows.2)
- OS version: windows 10 64bit (Microsoft Windows NT 10.0.19042.0)
- .NET version: 4.8.4390.0

**Comment by pmiossec** [comment] 2021-09-30 11:43
@ZulfinZ I don't know what you expect because as said in this comment (https://github.com/gitextensions/gitextensions/issues/4748#issuecomment-378474594 ) it is now how git is working when GitExtensions launch the git command to diff a file in the diff tool configured.
I don't think GE won't be able to change this behavior

**Comment by ZulfinZ** [comment] 2021-10-05 07:04
I understand that this behavior change is due to git and not gitExtension, but since gitExtension triggered the compare command (and opens the diff tool), it this case "First -> Working directory" comparison could be triggered automatically.
When the local copy is the same as the "Second", no point in using temporary files.

It is very useful to do some changes in the diff tool. Doing it accidentally on the temporary file is very frustrating.

**Comment by pmiossec** [comment] 2021-10-05 07:24
>  When the local copy is the same as the "Second", no point in using temporary files.

I think you didn't understand: that's git that create the temporary files and not GitExtensions. It just run the command:

`git difftool --gui --no-prompt -M -C "8fcbeb7688543db0605c6c325cb9224738f9e854" "d4229e7dd312e0eaf75cba7f0caa41eb32dd8cb8" -- "path/to/a/file.cs"`

So there is no way for GitExtensions to even prevent git to do it...

**Comment by pmiossec** [comment] 2021-10-05 07:27
> It is very useful to do some changes in the diff tool. Doing it accidentally on the temporary file is very frustrating.

The diff tool (p4merge) I use set automatically the files as read-only and you have to explicitly put it in write mode if you want to edit one file. SO why don't you ask for fixing this behavior in your diff tool? 😉

**Comment by ZulfinZ** [comment] 2021-10-05 07:36
Ok, but when "First -> Second" diff is triggered, and second == local, GitExtensions can trigger diff "First -> Working directory" instead.

**Comment by gerhardol** [comment] 2021-10-05 07:36
Maybe the request is to run a git-status before git-difftool to determine the arguments. (There is a race condition here.)
(To handle other than HEAD, also selected commit to HEAD must be compared too (can be done with other than git-diff)).
That would be the same as Alt-F3 (or F3 in FileTree). You can change the hotkeys for diff.

(I am not sure I want this feature, for sure will not implement it.)

**Comment by ZulfinZ** [comment] 2021-10-05 07:41
> > It is very useful to do some changes in the diff tool. Doing it accidentally on the temporary file is very frustrating.
> 
> The diff tool (p4merge) I use set automatically the files as read-only and you have to explicitly put it in write mode if you want to edit one file. SO why don't you ask for fixing this behavior in your diff tool? 😉

I don't see how this is related. In this case, the diff tool opens with temporary files on both sides (even the local==second)

**Comment by RussKie** [comment] 2021-10-08 03:27
I suggest the issue is closed and raised to git instead. I don't think we
should be attempting to fix this as a) it has perf implications, b) it may
be fixed by git and then we'll have to unfix this or fix it again.
If you want to automate it  perhaps you can write a script...

**Closed** 2021-12-03 12:00 UTC
Labels: :zzz: status: no recent activity, :mailbox_with_no_mail: needs: author feedback
