### ISSUE TITLE
[NBug] After updating the latest version of git, gitextensions begin to throw an exception

### ISSUE THREAD

**Issue by hakanaltindis** [gitextensions/gitextensions#10404] opened 2022-11-15 11:32 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: remote
Working directory: C:\Projects\Turkuaz\

```
GitExtUtils.ExternalOperationException
 ---> System.Exception
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.GitModule.GetRemoteNames()
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.<>c__DisplayClass15_0.<PopulateRemotes>b__0()
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.PopulateRemotes(List`1 allRemotes, Boolean enabled)
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.LoadRemotes(Boolean loadDisabled)
   at GitUI.CommandsDialogs.FormPull.BindRemotesDropDown(String selectedRemoteName)
   at GitUI.CommandsDialogs.FormPull..ctor(GitUICommands commands, String defaultRemoteBranch, String defaultRemote, PullAction pullAction)
   at GitUI.GitUICommands.<>c__DisplayClass95_0.<StartPullDialogInternal>g__Action|0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent)
   at GitUI.GitUICommands.StartPullDialogInternal(IWin32Window owner, Boolean pullOnShow, Boolean& pullCompleted, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.GitUICommands.StartPullDialogAndPullImmediately(Boolean& pullCompleted, IWin32Window owner, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.GitUICommands.StartPullDialogAndPullImmediately(IWin32Window owner, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.CommandsDialogs.FormBrowse.DoPull(PullAction pullAction, Boolean isSilent)
   at GitUI.CommandsDialogs.FormBrowse.ToolStripButtonPullClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnButtonClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

After I installed lastest version of git, treeview of commits is gone. There is just empty screen. And I try to fetch, GitExtension throw the exception.

Before I installed lastest version, GitExtension was working correctly. The version was 2.35.xx before updating.

### Steps to reproduce

I deleted GitExtension 3.3.xx version from my PC.
I installed the latest version of GitExtension
After that it was working fine.
It informed me about that there is a new version for git.
And I updated git version from 2.35.xx to 2.38.1.windows.1
After that GitExtension does not show anything in the tree view pane.
Finally when I try to fetch, it throw the exception.

### Did this work in previous version of GitExtensions?

No

**Comment by pmiossec** [comment] 2022-11-15 11:47
Seems duplicate of #10349.
But it could also be #9954 the reason ( especially this comment: https://github.com/gitextensions/gitextensions/issues/9954#issuecomment-1098375030 )

**Comment by hakanaltindis** [comment] 2022-11-15 12:06
Yeah, they are mostly similar. But I think not the same. The below image is my view.

![image](https://user-images.githubusercontent.com/6873753/201912621-3b4476c6-6827-4ff9-9391-da13500a506f.png)

I deleted my repo, and cloned it again. But the same issue is continue.

After that I tried the command of the comment of your suggestion `git clean -x -d --dry-run`. It did not say anything.

![image](https://user-images.githubusercontent.com/6873753/201914541-af67f078-7890-48c1-8a3e-7470ed25d89f.png)
 
Btw, I can work with git commands in command line. I did not understand which one of them is relevant for the issue. Git or GitExtension?

**Comment by pmiossec** [comment] 2022-11-15 12:13
Can you open 'Git command log` in the 'Tools' menu (or 'F12') and refresh the grid.
Then can you post the arguments and the output of the command that doesn't exit with '0' (that should be `git remote -v`) after running it from the command line?

Maybe you will have a clue of what need to be fixed...

**Comment by pmiossec** [comment] 2022-11-15 12:17
I also see that you run windows terminal as Administrator.
Is it really needed? If you don't run the command as Admin or if your run GitExtensions as Admin, does that solve the issue?
Normally, you should never run as Administrator and a possibility is that you altered rights and git is no more able to run when not run in Administrator....

**Comment by hakanaltindis** [comment] 2022-11-15 12:35
I hopefully understand you correctly :)

First of all, I fetched again while developer tools was opening.

![image](https://user-images.githubusercontent.com/6873753/201918298-73776b43-51c7-4732-b9e9-32179f5109d0.png)

You can see detail about the command in below:

```
File name:   C:\Program Files\Git\bin\git.exe
Arguments:   remote
Working dir: <project path>
Process ID:  21576
Started at:  2022-11-15T15:16:06.9739184+03:00
UI Thread?:  True
Duration:    82,266 ms
Exit code:   GitExtUtils.ExternalOperationException
 ---> System.Exception
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.GitModule.GetRemoteNames()
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.<>c__DisplayClass15_0.<PopulateRemotes>b__0()
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.PopulateRemotes(List`1 allRemotes, Boolean enabled)
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.LoadRemotes(Boolean loadDisabled)
   at GitUI.CommandsDialogs.FormPull.BindRemotesDropDown(String selectedRemoteName)
   at GitUI.CommandsDialogs.FormPull..ctor(GitUICommands commands, String defaultRemoteBranch, String defaultRemote, PullAction pullAction)
   at GitUI.GitUICommands.<>c__DisplayClass95_0.<StartPullDialogInternal>g__Action|0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent)
   at GitUI.GitUICommands.StartPullDialogInternal(IWin32Window owner, Boolean pullOnShow, Boolean& pullCompleted, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.GitUICommands.StartPullDialogAndPullImmediately(Boolean& pullCompleted, IWin32Window owner, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.GitUICommands.StartPullDialogAndPullImmediately(IWin32Window owner, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.CommandsDialogs.FormBrowse.DoPull(PullAction pullAction, Boolean isSilent)
   at GitUI.CommandsDialogs.FormBrowse.ToolStripButtonPullClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnButtonClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
Call stack:  not captured
```

> I also see that you run windows terminal as Administrator. Is it really needed? If you don't run the command as Admin or if your run GitExtensions as Admin, does that solve the issue? Normally, you should never run as Administrator and a possibility is that you altered rights and git is no more able to run when not run in Administrator....

First, I opened GitExtension as Admin, it worked correctly.

Second, I tried to fetch in command line without Admin. I got an error like that.
![image](https://user-images.githubusercontent.com/6873753/201919581-cb1cbdbc-73d7-40d6-9e10-5681fd9c0c21.png)

Third, I deleted repo again. And cloned it in command line without admin. After that, GitExtension begin to work correctly.

I think, we got the problem.
Why did this not happen before? What is changed about user?

**Comment by hakanaltindis** [comment] 2022-11-15 12:44
Is there any way to solve it without re-cloning. Because I have more than 80 repositories. I should not need to not re-clone them.

**Comment by pmiossec** [comment] 2022-11-15 13:06
> Why did this not happen before? What is changed about users or ownership?

It's a security mitigation from git done in 2.35.1.windows.2
https://github.com/gitextensions/gitextensions/issues/9954#issuecomment-1098355624

>Is there any way to solve it without re-cloning. Because I have more than 80 repositories. I should not need to not re-clone them

Your Admin and regular user accounts are not the same and so this warning is displayed in git outputs that prevent GitExtensions to interpret them.

Good practice: never use Admin account in your powershell session by default (to clone the repositories)

Workaround: run the `git config` command given by git. Not sure but I think that the command is working to allow ALL the folders `git config --global --add safe.directory *`
Maybe another workaround (not tested): From windows file explorer, change the owner and rights for all your repositories to grant your regular user account.

**Comment by gerhardol** [comment] 2022-11-15 23:11
Dulicate of #10349

**Closed by gerhardol** 2022-11-15 23:11 UTC
Labels: :eyeglasses: status: needs review
