### ISSUE TITLE
Branch name does not appear in Visual Studio 2013.

### ISSUE THREAD

**Issue by MiloDC** [gitextensions/gitextensions#2559] opened 2014-12-13 01:55 UTC
The setting "Show current branch in Visual Studio" (Settings -> Git Extensions -> Appearance) has no effect on the Git Extensions toolbar in Visual Studio 2013.

The name of the branch never shows.

**Comment by KindDragon** [comment] 2015-01-22 21:11
Duplicate of #2560

**Closed by KindDragon** 2015-01-22 21:11 UTC
