### ISSUE TITLE
[NBug] fatal: unrecognized argument: ->

### ISSUE THREAD

**Issue by grantleeman** [gitextensions/gitextensions#11682] opened 2024-04-16 12:55 UTC
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.44.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.29
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Users\GrantLeeman\AppData\Local\Programs\Git\bin\git.exe
Arguments: -c log.showSignature=false log --pretty=%ci
%an
%s --max-count=1 origin/HEAD -> origin/master --
Working directory: C:\Dev\Repos\Vegas\

```
GitExtUtils.ExternalOperationException: fatal: unrecognized argument: ->
 ---> System.Exception: fatal: unrecognized argument: ->
   --- End of inner exception stack trace ---
   at async Task<string> GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 147
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at IEnumerable<Branch> GitExtensions.Plugins.DeleteUnusedBranches.DeleteUnusedBranchesForm.GetObsoleteBranches(RefreshContext context, string curBranch)+MoveNext() in C:/projects/gitextensions/Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs:line 106
   at void System.Collections.Generic.List<T>.InsertRange(int index, IEnumerable<T> collection)
   at void GitUI.SortableBindingList<T>.AddRange(IEnumerable<T> items) in C:/projects/gitextensions/GitUI/SortableBindingList.cs:line 20
   at async Task GitExtensions.Plugins.DeleteUnusedBranches.DeleteUnusedBranchesForm.RefreshObsoleteBranchesAsync() in C:/projects/gitextensions/Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs:line 350
   at async void GitUI.TaskManager.InvokeAndForget(Control control, Func<Task> asyncAction, CancellationToken cancellationToken)+(?) => { } [1] in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 111
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

Using defaults from Delete Branches plugin (With Delete Remote ticked)

### Steps to reproduce

Use Plugin -> Remove older branches
Search works fine, but when you tick Delete remote branches -> Search again 
Then the error appears

**Comment by gerhardol** [comment] 2024-08-03 21:00
Duplicate of #11375 
Fixed in #11376

**Closed by gerhardol** 2024-08-03 21:00 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
