### ISSUE TITLE
[NBug] Could not find a part of the path GitExtensions\GitExtensions.settings

### ISSUE THREAD

**Issue by carlin-q-scott** [gitextensions/gitextensions#7376] opened 2019-11-01 22:57 UTC
## Current behaviour

git-extensions can't save any configuration. The setup wizard that runs on first start throws this exception once I try to make any configuration changes.

## Expected behaviour
I can finish setting up git-extensions.

## Steps to reproduce
1. Install git-extensions using an admin user account
1. launch it under a regular user account.

## Error Details
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\cscott\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at GitCommands.Settings.FileSettingsCache.SaveImpl()
   at GitCommands.SettingsCache.<>c__DisplayClass3_0.<LockedAction>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.Settings.SettingsContainer`2.Save()
   at GitUI.CommandsDialogs.FormSettings.Save()
   at GitUI.CommandsDialogs.SettingsDialog.Pages.ChecklistSettingsPage.SaveAndRescan_Click(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.ChecklistSettingsPage.GitFound_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Workaround
1. Create the configuration folder listed in the exception message
1. Launch git-extensions

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.20.1.windows.1 (recommended: 2.22.0 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-11-01 23:10
This is the portable edition, then the directory must be writable. How could this be done differently?

NBug popup could be replaced with an info popup.
You can change to store in normal user profile by editing the default .settings file

**Comment by carlin-q-scott** [comment] 2019-11-01 23:36
@gerhardol  I don't think this is the portable edition since it was installed by my machine admin. Does the installer try to make the directory in the error? That would explain why it happened.

**Comment by RussKie** [comment] 2019-11-02 13:16
The folder is under the user's profile so it supposed to be writable.

@carlin-q-scott does the path `C:\Users\cscott\AppData\Roaming\GitExtensions\GitExtensions\` exist? If it does, is it writable? Does `GitExtensions.settings` exist? Is it writable?
What would happen if you start GE as an admin, would it fail with the same error?

**Comment by carlin-q-scott** [comment] 2019-11-02 16:48
@RussKie check out the section of my bug report titled "Workaround".

**Comment by gerhardol** [comment] 2019-11-10 11:10
Duplicate of #7395 
Opened after, but there is a PR connected to the issue

**Closed by gerhardol** 2019-11-10 11:10 UTC
Labels: potential-duplicate

**Comment by carlin-q-scott** [comment] 2019-11-10 17:17
May I ask why people ignored my issue for a week and then imediately fixed the duplicate?

**Comment by mstv** [comment] 2019-11-10 17:42
Your issue was not ignored. We are all volunteers with a real life job. And a workaround was available...
The other issue description let me remember that GE creates folders with a space.
