### ISSUE TITLE
[NBug] InvalidArgument=Value mit dem Wert 0 ist für index ungültig...

### ISSUE THREAD

**Issue by kaesaecracker** [gitextensions/gitextensions#7204] opened 2019-09-27 08:09 UTC
## Current behaviour
I pasted a branch name (copied link of ticket in jira, so maybe with formatting?) into the "Branches: " field of the main GUI and pressed enter. Because nothing happened, I clicked the dropdown arrow of the same field. The crash happened immediately after that.

## Expected behaviour
Empty dropdown if no elements match, no crash

## Steps to reproduce
see current behavior

## Error Details
```
System.ArgumentOutOfRangeException: InvalidArgument=Value mit dem Wert 0 ist für index ungültig.
Parametername: index
   bei System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   bei System.Windows.Forms.ComboBox.get_Text()
   bei System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   bei System.Windows.Forms.ComboBox.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Translation of the error message: "Value 0 is invalid for index"

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment] 2019-09-27 15:21
Duplicate of #6680

**Closed by gerhardol** 2019-09-27 15:21 UTC
