### ISSUE TITLE
Commit graph does not redraw after stash pop

### ISSUE THREAD

**Issue by yegor-mialyk** [gitextensions/gitextensions#9208] opened 2021-05-14 22:54 UTC
## Current behaviour

The commit graph does not redraw after a stash pop (Ctrl+Alt+Down).

## Steps to reproduce

1. Change some file
2. Push to stash (Ctrl+Alt+Up)
    (A stash virtual commit appears on the graph)
3. Pop from stash (Ctrl+Alt+Down).

Expected: A stash virtual commit disappears from the graph
Actual: The graph stays as there is a stash 

## Screenshots

![image](https://user-images.githubusercontent.com/16239726/118338982-6376f300-b4cc-11eb-85fb-16564b7e2278.png)

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4341.0
- DPI 240dpi (250% scaling)

**Comment by mstv** [comment] 2021-05-14 22:58
Duplicate of #9121. Fixed with #9145.

**Closed by mstv** 2021-05-14 22:58 UTC
