### ISSUE TITLE
Don't let progress dialog to grab global focus and jump to top, please

### ISSUE THREAD

**Issue by glacjay** [gitextensions/gitextensions#6386] opened 2019-03-20 04:04 UTC
## Feature description

Currently, when I click 'Commit & push' button, a progress dialog will appear to show commit progress, then I switch to another application. When the commiting finished, a second progress dialog showing push progress will appear, and instead of just working at background, this second progress dialog will jump to topmost position automatically, so I can't see my 'another application' anymore, which is very unfriendly.

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment] 2019-03-20 04:35
The current wording is very unclear. Please reword that it is clear what
the issue is, how to reproduce and what is expected.

**Comment by pmiossec** [comment] 2019-03-20 10:03
@glacjay It's seems to be a duplicate of #6220 trying to be fixed by #6379 that has just been merged.

Please try the last version built ( download it from artifacts here: https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master ) and please reports if it solve or not your problem.

**Comment by gerhardol** [comment] 2019-03-23 00:16
Duplicate of #6220 
Disable ConEmu to get rid of it
Unfortunately, #6379 does not seem to fix the problem

**Closed by gerhardol** 2019-03-23 00:16 UTC
