### ISSUE TITLE
Dark theme does not work on version 4.0.0

### ISSUE THREAD

**Issue by NickPolyder** [gitextensions/gitextensions#10331] opened 2022-11-05 04:30 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

After installing the version 4 the theme selector does not work. I have selected the dark theme and restarted the app and even the pc multiple times but the theme remains the same.
![image](https://user-images.githubusercontent.com/7039167/200096361-96481dec-a1e3-4a2c-af2d-08a9734d9b77.png)

The only places that is affected is the history panel 
![image](https://user-images.githubusercontent.com/7039167/200100304-32990b81-a400-4f1b-9630-67176aa9fcc6.png)

### Steps to reproduce

1. Fresh Install the app
2. Go to Settings > Appearance > Colors > Theme.
3. Change from Default to Dark.
4. Restart GitExtensions.
5. The application is still in default theme.
6. Browse a repo. The History panel has the correct colors.

### Did this work in previous version of GitExtensions?

Yes. It was working in the versions 3.5.2 - 3.5.4

**Comment by vbjay** [comment] 2022-11-05 05:15
Read the changelog along with searching issues next time.

**Comment by gerhardol** [comment] 2022-11-05 09:08
Duplicate of #10312

**Closed** 2022-11-05 09:08 UTC
Labels: :eyeglasses: status: needs review

**Comment by NickPolyder** [comment] 2022-11-05 11:13
@vbjay Sorry for the inconvenience. I saw that there is a label theming and I was searching against that but it seems that the issue #10312 does not have the proper label to it. Also I do not like the way you speak. @gerhardol put way more value into this issue by just saying that it is a duplicate than your response.

Thank you all for your time.

**Comment by vbjay** [comment] 2022-11-05 14:00
1. I was not rude. I was direct.  I don't beat around the bush.
2. A lot of people do this. They blast issues without reading tfe changelog. It would have cleared it up.
3. We have already had a few people post the exact same issue. 
4. Clearly mentioned
 https://github.com/gitextensions/gitextensions/releases/tag/v4

**Comment by NickPolyder** [comment] 2022-11-06 00:01
@vbjay 
1. To me it did get through as rude. I appreciate that this was not your intention. Maybe adding a `please` or something to help the other person understand the tone of the message it would help. (Keep in mind that not everyone in github have English as their native language).

  2. I expected that the changelog from inside the app
![image](https://user-images.githubusercontent.com/7039167/200147454-b03c0803-ffd0-4e9e-a5f3-49d1226c9163.png)
and the changelog in github would have the same info, apparently not. Maybe it could be a feature request to make the changelog of github and the one in the app (see screen above) be the same or at least have the same data. 

3. In my case as I mentioned above if the issue had the label `area: theming` I would have found it. As I checked for the issues but used that specific label and it did not come up. 

Thank you for your time.

**Comment by gerhardol** [comment] 2022-11-06 00:15
>     2. I expected that the changelog from inside the app
>        and the changelog in github would have the same info, apparently not. Maybe it could be a feature request to make the changelog of github and the one in the app (see screen above) be the same or at least have the same data.

>     3. In my case as I mentioned above if the issue had the label `area: theming` I would have found it. As I checked for the issues but used that specific label and it did not come up.

The changelog in the app is generated, the one in GH is manually created and can be clarified.
As the the change in #8522 was to migrate to #8522 and there were a bunch of other temporary changes it would not be correct to list all those in the PR subject.

What could be done is to add a general link to GH releases.

**Comment by NickPolyder** [comment] 2022-11-06 00:34
>As the the change in https://github.com/gitextensions/gitextensions/pull/8522 was to migrate to https://github.com/gitextensions/gitextensions/pull/8522 and there were a bunch of other temporary changes it would not be correct to list all those in the PR subject.

I am not sure what you mean here. If it is about the label `area: theming` I meant that the label could be added in the issue #10312  That way everybody that uses that to see for the theming issue would be directed to that.

> What could be done is to add a general link to GH releases. 

A link to the GH changelog for the current version with a description saying `for the full release details see here: [github release](/link-to-github-release)` I think it would be sufficient.

Thank you for your time.

**Comment by RussKie** [comment] 2022-11-06 22:32
Thank you for your feedback @NickPolyder.


> A link to the GH changelog for the current version with a description saying `for the full release details see here: [github release](/link-to-github-release)` I think it would be sufficient.

The release has the link, or were you having something else in mind?
![image](https://user-images.githubusercontent.com/4403806/200198819-07f5a338-b90f-492e-930d-46b4361528eb.png)

**Comment by NickPolyder** [comment] 2022-11-07 00:03
Hello @RussKie we were talking about the  change log that is under the `Help` menu. 

![image](https://user-images.githubusercontent.com/7039167/200202704-9b238660-d10f-4083-b87a-a76c3097fd11.png)

![image](https://user-images.githubusercontent.com/7039167/200202677-e07264fa-4dbc-46bb-a3a5-896d4e1e15f8.png)

To me the change log in the app would be far more helpful if it was more like the github changelog page. that was way more info than just links.

Thank you for your time.
