### ISSUE TITLE
[NBug] Object reference not set to an instance of an object. (repo-local settings)

### ISSUE THREAD

**Issue by mklinke** [gitextensions/gitextensions#10433] opened 2022-11-22 06:54 UTC
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.11
- DPI 144dpi (150% scaling)

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUIPluginInterfaces.NumberSetting`1.NumericUpDownBinding.LoadSetting(ISettingsSource settings, NumericUpDown control)
   at GitUIPluginInterfaces.SettingControlBinding`2.LoadSetting(ISettingsSource settings)
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.SettingsToPage()
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.LoadSettings()
   at GitUI.CommandsDialogs.SettingsDialog.RepoDistSettingsPage.SetCurrentSettings(RepoDistSettings settings)
   at GitUI.CommandsDialogs.SettingsDialog.RepoDistSettingsPage.SetLocalSettings()
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageHeader.<>c__DisplayClass2_0.<ConfigureHeader>b__0(Object a, EventArgs b)
   at System.Windows.Forms.RadioButton.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.RadioButton.set_Checked(Boolean value)
   at System.Windows.Forms.RadioButton.OnClick(EventArgs e)
   at System.Windows.Forms.RadioButton.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Periodic background fetch is not working. So I tried to check the settings (Opened "periodic background fetch" settings.). The effective settings show that it should be enabled (period is set to 300). Wanted to check other sources of the settings, so I switched "Settings source:" from "Effective" to "Local for current repository" and the error dialog showed up.

### Steps to reproduce

- Launch GitExtensions
- Open repository from dashboard
- Open "Plugins" -> "Periodic background fetch". 
- Switch "Settings source:" from "Effective" to "Local for current repository" 

=> and the error dialog shows up.

### Did this work in previous version of GitExtensions?

Yes, < 4.0.0

**Comment by RussKie** [comment] 2022-11-23 06:29
Duplicate of #10323

**Closed by RussKie** 2022-11-23 06:29 UTC
Labels: :eyeglasses: status: needs review, potential-duplicate
